import type { Client } from "../types/client.js";
import type {
  ComplianceCheckResult,
  ComplianceReport,
} from "../types/compliance.js";
import { ComplianceStatus } from "../types/compliance.js";
import { generateId, formatDate } from "../utils/helpers.js";

/**
 * ReportGenerator — Produces compliance reports from check results.
 * Supports multiple output formats.
 */
export class ReportGenerator {
  /**
   * Generate a ComplianceReport from check results and client data.
   */
  generate(
    results: ComplianceCheckResult[],
    client: Client
  ): ComplianceReport {
    return {
      id: generateId("rpt"),
      clientId: client.id,
      states: client.states,
      entityType: client.entityType,
      results,
      generatedAt: new Date().toISOString(),
      generatedBy: "REGULIS",
    };
  }

  /**
   * Format a compliance report as an HTML document.
   */
  formatAsHTML(report: ComplianceReport): string {
    const compliant = report.results.filter(
      (r) => r.status === ComplianceStatus.COMPLIANT
    ).length;
    const nonCompliant = report.results.filter(
      (r) => r.status === ComplianceStatus.NON_COMPLIANT
    ).length;
    const needsReview = report.results.filter(
      (r) => r.status === ComplianceStatus.NEEDS_REVIEW
    ).length;

    const rows = report.results
      .map(
        (r) => `
      <tr>
        <td>${r.ruleId}</td>
        <td>${r.status}</td>
        <td>${r.details}</td>
        <td>${r.remediation}</td>
        <td>${r.deadline ?? "N/A"}</td>
      </tr>`
      )
      .join("");

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Compliance Report — ${report.id}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto; }
    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
    th, td { padding: 0.5rem; border: 1px solid #ddd; text-align: left; }
    th { background: #f5f5f5; }
    .summary { display: flex; gap: 2rem; margin: 1rem 0; }
    .summary div { padding: 1rem; border-radius: 4px; }
    .compliant { background: #d4edda; }
    .non-compliant { background: #f8d7da; }
    .needs-review { background: #fff3cd; }
  </style>
</head>
<body>
  <h1>Vernen Legal Compliance Report</h1>
  <p>Report ID: ${report.id}</p>
  <p>Client: ${report.clientId}</p>
  <p>Entity Type: ${report.entityType}</p>
  <p>States: ${report.states.join(", ")}</p>
  <p>Generated: ${formatDate(report.generatedAt)}</p>
  <p>Generated By: ${report.generatedBy}</p>

  <div class="summary">
    <div class="compliant">Compliant: ${compliant}</div>
    <div class="non-compliant">Non-Compliant: ${nonCompliant}</div>
    <div class="needs-review">Needs Review: ${needsReview}</div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Rule ID</th>
        <th>Status</th>
        <th>Details</th>
        <th>Remediation</th>
        <th>Deadline</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <footer>
    <p>&copy; Vernen Legal Compliance. Report generated by ${report.generatedBy}.</p>
  </footer>
</body>
</html>`;
  }

  /**
   * Format a compliance report as PDF.
   * Stub — will integrate with a PDF generation service.
   */
  formatAsPDF(_report: ComplianceReport): Uint8Array {
    // PDF generation will be implemented with a Cloudflare-compatible library.
    // For now, return an empty buffer.
    return new Uint8Array(0);
  }
}
