/**
 * VERNEN™ Form Loader Script
 * Reads JSON annotation files and generates INSERT SQL for the court_forms table.
 *
 * Usage: npx tsx src/db/load-forms.ts > src/db/seed-forms.sql
 *
 * This script generates SQL only — it does not execute against D1.
 * Run the generated SQL with: wrangler d1 execute DB --file=src/db/seed-forms.sql
 *
 * © 2024-2026 Michael Vernen Thomas Hartmann. All Rights Reserved.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";

// ═══════════════════════════════════════════════════════════════════════════════
// CONFIGURATION
// ═══════════════════════════════════════════════════════════════════════════════

const ANNOTATIONS_DIR = path.resolve(__dirname, "../data/annotations");
const REGISTRY_PATH = path.resolve(__dirname, "../data/forms/form_registry.json");

const SUPPORTED_LANGUAGES = ["en", "es", "zh", "vi", "so", "ti", "am", "ar", "ht", "ko", "pt", "ru", "tl"];

// ═══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════════

function escapeSql(str: string): string {
  return str.replace(/'/g, "''");
}

function extractFormCode(data: any): string {
  return (
    data.metadata?.form_id ||
    data.meta?.form_id ||
    data.form_id ||
    "UNKNOWN"
  ).toUpperCase();
}

function extractTitle(data: any): string {
  return (
    data.metadata?.title ||
    data.meta?.form_title ||
    data.title_en ||
    data.title ||
    "Untitled Form"
  );
}

function extractTier(data: any, registryForms: any[]): string {
  const formCode = extractFormCode(data);
  // Check registry for tier
  const registryEntry = registryForms.find((f: any) => f.id === formCode);
  if (registryEntry) return "A"; // tier A forms are in the main array

  if (data.metadata?.tier) return data.metadata.tier;
  if (data.meta?.tier) return data.meta.tier;
  return "A";
}

function extractCategory(data: any, registryForms: any[]): string {
  const formCode = extractFormCode(data);
  const registryEntry = registryForms.find((f: any) => f.id === formCode);
  if (registryEntry?.category) return registryEntry.category;

  if (data.metadata?.category) return data.metadata.category;
  if (data.meta?.category) return data.meta.category;

  // Infer from form code
  if (formCode.startsWith("FL-")) return "family_law";
  if (formCode.startsWith("DV-")) return "domestic_violence";
  if (formCode.startsWith("FW-")) return "fee_waiver";
  if (formCode.startsWith("MC-")) return "general";
  return "general";
}

function countFields(data: any): number {
  let count = 0;

  if (data.metadata?.total_fields) return data.metadata.total_fields;

  if (Array.isArray(data.fields)) {
    count += data.fields.length;
  }

  if (Array.isArray(data.sections)) {
    for (const section of data.sections) {
      if (Array.isArray(section.fields)) {
        count += section.fields.length;
      }
    }
  }

  return count;
}

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════════

function main(): void {
  const output: string[] = [];

  output.push("-- VERNEN™ Court Forms Seed Data");
  output.push("-- Generated by src/db/load-forms.ts");
  output.push(`-- Generated at: ${new Date().toISOString()}`);
  output.push("-- © 2024-2026 Michael Vernen Thomas Hartmann. All Rights Reserved.");
  output.push("");

  // Load form registry for metadata enrichment
  let registryForms: any[] = [];
  try {
    const registryRaw = fs.readFileSync(REGISTRY_PATH, "utf-8");
    const registry = JSON.parse(registryRaw);
    registryForms = [...(registry.forms || []), ...(registry.tier_b_forms || [])];
  } catch (err) {
    output.push(`-- WARNING: Could not load form registry: ${err}`);
  }

  // Read all annotation files
  let annotationFiles: string[] = [];
  try {
    annotationFiles = fs.readdirSync(ANNOTATIONS_DIR).filter(f => f.endsWith(".json"));
  } catch (err) {
    output.push(`-- ERROR: Could not read annotations directory: ${err}`);
    console.log(output.join("\n"));
    process.exit(1);
  }

  output.push(`-- Processing ${annotationFiles.length} annotation files`);
  output.push("");

  for (const file of annotationFiles.sort()) {
    const filePath = path.join(ANNOTATIONS_DIR, file);
    let data: any;

    try {
      const raw = fs.readFileSync(filePath, "utf-8");
      data = JSON.parse(raw);
    } catch (err) {
      output.push(`-- SKIPPED ${file}: parse error (${err})`);
      continue;
    }

    const formCode = extractFormCode(data);
    const title = extractTitle(data);
    const tier = extractTier(data, registryForms);
    const category = extractCategory(data, registryForms);
    const fieldCount = countFields(data);
    const languages = JSON.stringify(SUPPORTED_LANGUAGES);
    const dataStr = JSON.stringify(data);
    const id = crypto.randomUUID();

    output.push(`-- ${formCode}: ${title} (${fieldCount} fields, tier ${tier})`);
    output.push(
      `INSERT OR REPLACE INTO court_forms (id, form_code, title, tier, category, field_count, languages, data)` +
      ` VALUES ('${escapeSql(id)}', '${escapeSql(formCode)}', '${escapeSql(title)}', '${escapeSql(tier)}', '${escapeSql(category)}', ${fieldCount}, '${escapeSql(languages)}', '${escapeSql(dataStr)}');`
    );
    output.push("");
  }

  output.push(`-- Total forms loaded: ${annotationFiles.length}`);

  console.log(output.join("\n"));
}

main();
