-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 6
-- ═══════════════════════════════════════════════════════════════════════════
-- CPS/Child Welfare (WIC §300 subsections), Tarasoff, and Family Law
-- expansion standards for ADVOCIS and REGULIS Citizens.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — CPS / Child Welfare (WIC §300 subsections)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_031', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(a)', 'WIC § 300(a)', 'Serious Physical Harm Inflicted by Parent', 'Child has suffered or is at substantial risk of suffering serious physical harm inflicted nonaccidentally by the parent or guardian.', '["Nonaccidental serious physical harm by parent/guardian","Substantial risk of future harm sufficient","Age-appropriate spanking to buttocks is excluded","Includes willful or negligent cruelty by any household member"]', '[{"section":"300(a)","description":"Serious physical harm inflicted nonaccidentally upon the minor by the parent or guardian"}]', '["dependency_petition","detention_report","jurisdiction_disposition_report","CPS_referral"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_032', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(b)(1)', 'WIC § 300(b)(1)', 'Failure to Protect — Serious Physical Harm or Illness', 'Child has suffered or is at substantial risk of suffering serious physical harm or illness as a result of the failure or inability of the parent to adequately supervise or protect the child.', '["Failure or inability to supervise or protect","Failure to provide adequate food, clothing, shelter, or medical treatment","Inability to provide regular care due to substance abuse or mental illness","No requirement of parental fault — focus is on child safety"]', '[{"section":"300(b)(1)","description":"Neglect — failure to protect from serious physical harm or illness"}]', '["dependency_petition","detention_report","medical_records","CPS_referral","substance_abuse_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_033', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(c)', 'WIC § 300(c)', 'Serious Emotional Damage', 'Child is suffering serious emotional damage or is at substantial risk of suffering serious emotional damage evidenced by severe anxiety, depression, withdrawal, or untoward aggressive behavior.', '["Serious emotional damage — not speculative","Evidenced by severe anxiety, depression, withdrawal, or aggression","No reasonable means for parent to protect without court intervention","Professional assessment typically required"]', '[{"section":"300(c)","description":"Serious emotional damage caused by conduct of parent or guardian or who has no parent capable of providing care"}]', '["dependency_petition","psychological_evaluation","school_records","therapist_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_034', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(d)', 'WIC § 300(d)', 'Sexual Abuse', 'Child has been sexually abused or there is substantial risk of being sexually abused by parent, guardian, or household member, or the parent has failed to adequately protect the child.', '["Sexual abuse as defined in Penal Code § 11165.1","Includes acts by parent, guardian, or household member","Substantial risk of future abuse sufficient","Parent failure to protect from known abuser"]', '[{"section":"300(d)","description":"Sexual abuse or substantial risk thereof — cross-references Penal Code § 11165.1"}]', '["dependency_petition","forensic_interview","SART_exam","CPS_referral","law_enforcement_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_035', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(e)', 'WIC § 300(e)', 'Severe Physical Abuse — Under Age 5', 'Child under age five has suffered severe physical abuse by a parent or any person known to the parent, if the parent knew or reasonably should have known the person was physically abusing the child.', '["Applies to children under age 5","Severe physical abuse — single or multiple acts","Parent knew or should have known of abuse","Triggers bypass of reunification services under § 361.5(b)"]', '[{"section":"300(e)","description":"Severe physical abuse of child under 5 — defined by reference to PC § 273a and severe injuries"}]', '["dependency_petition","medical_records","forensic_exam","detention_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_036', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(f)', 'WIC § 300(f)', 'Death of Child by Parent Abuse or Neglect', 'The child''s parent or guardian caused the death of another child through abuse or neglect.', '["Prior child death caused by parent abuse or neglect","Triggers bypass of reunification services under § 361.5(b)","Criminal conviction not required — civil standard applies","Includes death of any child, not limited to sibling"]', '[{"section":"300(f)","description":"Parent caused death of another child through abuse or neglect"}]', '["dependency_petition","death_certificate","coroner_report","criminal_records","prior_CPS_history"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_037', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(g)', 'WIC § 300(g)', 'Left Without Provision for Support', 'Child has been left without any provision for support, or parent has been incarcerated or institutionalized and cannot arrange for care of the child.', '["Child left without provision for support","Parent incarcerated or institutionalized","No reasonable plan for child care by parent","Voluntary surrender or abandonment"]', '[{"section":"300(g)","description":"No provision for support — incarceration, institutionalization, or abandonment"}]', '["dependency_petition","detention_report","incarceration_records","social_worker_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_038', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(h)', 'WIC § 300(h)', 'Freed for Adoption but Not Placed', 'Child has been freed for adoption by one or both parents for 12 months by either relinquishment or termination of parental rights, and has not been adopted.', '["Parental rights terminated or relinquished","12-month period without adoption placement","Agency must demonstrate diligent efforts to place","Court may order additional efforts or alternative plan"]', '[{"section":"300(h)","description":"Freed for adoption for 12+ months without placement"}]', '["adoption_assessment","TPR_order","placement_report","permanency_plan"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_039', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(i)', 'WIC § 300(i)', 'Cruelty', 'Child has been subjected to an act or acts of cruelty by the parent or guardian or a member of the household, or the parent has failed to adequately protect the child from such acts.', '["Acts of cruelty by parent, guardian, or household member","Includes acts that endanger child health or well-being","Parent failure to protect from cruelty by others","May overlap with 300(a) but broader scope"]', '[{"section":"300(i)","description":"Cruelty — acts endangering child health, person, or well-being"}]', '["dependency_petition","CPS_referral","medical_records","law_enforcement_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_040', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300(j)', 'WIC § 300(j)', 'Sibling Abuse or Neglect', 'Child''s sibling has been abused or neglected as defined in subdivisions (a), (b), (d), (e), or (i), and there is a substantial risk that the child will be abused or neglected.', '["Sibling was abused/neglected under 300(a),(b),(d),(e), or (i)","Substantial risk that this child will also be abused or neglected","Court considers circumstances of sibling abuse","Court considers age and gender of each child"]', '[{"section":"300(j)","description":"Sibling abuse/neglect with substantial risk to subject child"}]', '["dependency_petition","prior_CPS_history","sibling_case_records","detention_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — CPS Procedural Standards
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_041', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 361.5', 'WIC § 361.5', 'Reunification Services', 'Governs when reunification services must be provided and when they may be bypassed in dependency proceedings.', '["Reunification services required unless bypass applies","6 months for children under 3, 12 months for older children","18 months maximum in most cases","Bypass grounds include severe abuse (300(e)), sibling death (300(f)), chronic abuse, prior failed reunification"]', '[{"section":"361.5(a)","description":"Mandatory reunification services upon removal"},{"section":"361.5(b)","description":"Bypass grounds — enumerated exceptions to reunification"},{"section":"361.5(e)","description":"No services if parent not provided with reasonable services in prior case"}]', '["reunification_plan","case_plan","status_review_report","bypass_motion"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_042', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 366.26', 'WIC § 366.26', 'Selection of Permanent Plan — Adoption or Guardianship', 'Governs the selection and implementation hearing for permanent plans when reunification fails, including adoption, guardianship, and long-term foster care.', '["Adoption is preferred permanent plan","Legal guardianship if adoption not appropriate","Long-term foster care as last resort","Parental rights terminated if adoption selected","Indian Child Welfare Act (ICWA) placement preferences apply"]', '[{"section":"366.26(b)","description":"Hearing to select permanent plan"},{"section":"366.26(c)(1)","description":"Termination of parental rights if child likely to be adopted"},{"section":"366.26(c)(3)","description":"Beneficial relationship exception to TPR"}]', '["permanency_plan","adoption_assessment","guardianship_petition","TPR_order","366.26_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_043', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 364', 'WIC § 364', 'Review Hearings — Child Not Removed', 'Governs periodic review hearings when a child remains in the home of the parent under dependency jurisdiction.', '["Review hearing within 6 months of initial disposition","Court determines if conditions justify continued jurisdiction","Agency must show by preponderance that conditions still exist","Jurisdiction terminated if conditions no longer exist"]', '[{"section":"364(c)","description":"Court shall terminate jurisdiction unless conditions still exist warranting jurisdiction"},{"section":"364(d)","description":"If child removed at review — standard removal findings required"}]', '["status_review_report","social_worker_report","court_order","364_hearing_report"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_044', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 355', 'WIC § 355', 'Court Findings at Jurisdictional Hearing', 'Establishes evidentiary standards and procedures at the jurisdictional hearing in dependency proceedings.', '["Preponderance of evidence standard for jurisdiction","Social study admissible and constitutes prima facie evidence","Hearsay in social study — corroboration may be required","Objection to specific hearsay requires corroborating evidence for sustained allegation"]', '[{"section":"355(a)","description":"Proof by preponderance of the evidence"},{"section":"355(b)","description":"Social study as prima facie evidence"},{"section":"355(c)","description":"Hearsay corroboration requirement upon objection"}]', '["jurisdiction_disposition_report","social_study","court_findings","355_hearing_transcript"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_045', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 317', 'WIC § 317', 'Appointment of Counsel for Child', 'Requires appointment of counsel for a child in dependency proceedings unless the court finds the child would not benefit from counsel.', '["Court shall appoint counsel for child unless no benefit","Counsel represents child — not parent or agency","Counsel has duty to investigate independently","May advocate position different from social worker recommendation"]', '[{"section":"317(a)","description":"Mandatory appointment of counsel for child"},{"section":"317(c)","description":"Duties of appointed counsel — investigate, advocate, appear at hearings"},{"section":"317(e)","description":"Counsel must be competent in dependency law"}]', '["appointment_order","counsel_declaration","minor_counsel_report","objection_filing"]', '["california-cps-child-welfare-audit"]', 'California Juvenile Court / DCFS', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — Duty to Warn Case Law
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_046', 'ADVOCIS', 'CASE_LAW', 'CA', 'Tarasoff v. Regents of the University of California (1976) 17 Cal.3d 425', 'Tarasoff', 'Duty to Warn — Therapist Obligation to Identifiable Victims', 'When a therapist determines or should determine that a patient presents a serious danger of violence to another, the therapist incurs an obligation to use reasonable care to protect the foreseeable victim.', '["Duty to warn identifiable potential victims of patient violence","Therapist must exercise reasonable care to protect foreseeable victim","Confidentiality yields to peril to public — protective privilege ends where public peril begins","Codified in Cal. Civ. Code § 43.92 and Cal. Evid. Code § 1024"]', '[{"section":"Tarasoff I (1974)","description":"Duty to warn — therapist must warn identifiable victim"},{"section":"Tarasoff II (1976)","description":"Expanded to duty to protect — broader obligation beyond mere warning"}]', '["threat_assessment","mandatory_report","therapist_disclosure","CPS_referral","law_enforcement_notification"]', '["california-cps-child-welfare-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Family Law Expansion
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_072', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 70', 'FC § 70', 'Date of Separation — Definition', 'Defines the date of separation as the date a complete and final break in the marital relationship has occurred, requiring both expressed intent and conduct consistent with termination.', '["Date of separation requires both intent and conduct","Complete and final break in marital relationship","Expressed intent to end marriage to the other spouse","Conduct consistent with intent to end the marriage"]', '[{"section":"70(a)","description":"Date of separation defined as complete and final break"},{"section":"70(b)","description":"Requires both expressed intent and conduct consistent with ending marriage"}]', '["dissolution_petition","FL-100","FL-110","property_declaration","FL-142"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_073', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 852', 'FC § 852', 'Transmutation of Property Between Spouses', 'Transmutation of community to separate property or separate to community property requires an express written declaration by the adversely affected spouse.', '["Express written declaration required for transmutation","Must be made, joined in, consented to, or accepted by adversely affected spouse","Oral or implied transmutations invalid after 1985","Writing must expressly state change in character of property"]', '[{"section":"852(a)","description":"Transmutation requires express declaration in writing by adversely affected spouse"},{"section":"852(b)","description":"Not enforceable as between parties without compliance"},{"section":"852(e)","description":"Gifts of clothing/personal effects exempt if not substantial in value"}]', '["transmutation_agreement","interspousal_transfer","quitclaim_deed","property_declaration"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_074', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 3024', 'FC § 3024', 'Counseling Before Custody Modification', 'Court may require parents to participate in outpatient counseling with a licensed mental health professional or mediation as a condition of modifying custody or visitation.', '["Court may order counseling before custody modification","Licensed mental health professional required","Counselor may provide recommendations to court","Costs allocated between parties by court order"]', '[{"section":"3024","description":"Counseling or mediation may be required before modifying custody or visitation orders"}]', '["custody_modification","counseling_order","mediation_report","FL-300"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_075', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 3065', 'FC § 3065', 'Domestic Violence and Parenting Classes', 'Court shall require a batterer to participate in a batterer treatment program as a condition of custody or visitation. Court shall not require victim to participate in joint counseling.', '["Batterer treatment program required as condition of custody/visitation","52-week minimum batterer intervention program","No joint counseling ordered with victim of DV","Parenting class may be separate requirement","Cost borne by batterer unless hardship shown"]', '[{"section":"3065","description":"Mandatory batterer intervention program and prohibition on joint counseling with DV victim"}]', '["DV_restraining_order","custody_order","batterer_program_enrollment","parenting_class_certificate"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_076', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 4050-4076', 'FC §§ 4050-4076', 'Uniform Guideline for Determining Child Support', 'Statewide uniform guideline for calculating child support based on income of both parents, timeshare percentage, tax filing status, and allowable deductions.', '["Mandatory statewide guideline — presumed correct","Calculated from both parents net disposable income","Timeshare percentage affects support amount","Guideline may be rebutted only under FC § 4057(b) special circumstances","Income includes salary, commissions, bonuses, rental income, and imputed income from assets"]', '[{"section":"4055","description":"Algebraic formula for guideline child support"},{"section":"4057(a)","description":"Guideline amount is presumptively correct"},{"section":"4057(b)","description":"Rebuttal factors — special circumstances"},{"section":"4058","description":"Definition of annual gross income for support"},{"section":"4062","description":"Add-on expenses — childcare, health insurance, education"}]', '["FL-150","FL-155","DissoMaster_printout","child_support_order","income_declaration"]', '["california-family-law-expansion-audit"]', 'California Family Court / DCSS', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_077', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 2106', 'FC § 2106', 'Attorney Fees for Disclosure Disputes', 'Court shall impose monetary sanctions and may award attorney fees against a party who fails to comply with preliminary or final declaration of disclosure obligations.', '["Mandatory sanctions for disclosure noncompliance","Attorney fees may be awarded to compliant party","Court may preclude noncompliant party from presenting undisclosed evidence","Remedies cumulative with FC § 1101 breach of fiduciary duty"]', '[{"section":"2106(a)","description":"Sanctions for failure to comply with disclosure requirements"},{"section":"2106(b)","description":"Attorney fees and costs as sanction"},{"section":"2106(c)","description":"Preclusion sanction for undisclosed assets or income"}]', '["FL-140","FL-141","FL-142","disclosure_motion","sanctions_order"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_078', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 3600', 'FC § 3600', 'Temporary Child Support', 'Court may order any amount of child support during the pendency of a proceeding that is necessary for the support of the child.', '["Temporary support ordered during pendency of proceeding","Amount based on needs of child and ability of parents to pay","Not limited by guideline calculation — court has broad discretion","Effective from date of filing or from date ordered"]', '[{"section":"3600","description":"Temporary child support — court may order any amount necessary during proceeding"}]', '["temporary_support_order","FL-300","FL-305","FL-150","income_declaration"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_079', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 4330', 'FC § 4330', 'Spousal Support Termination', 'Spousal support terminates upon death of either party, remarriage of the supported party, or further order of court. For long-term marriages, court retains jurisdiction indefinitely unless parties agree otherwise.', '["Support terminates on death, remarriage, or court order","Long-term marriage (10+ years) — court retains jurisdiction indefinitely","Short-term marriage — support presumed for half the length of marriage","Marital standard of living is benchmark","Gavron warning — supported spouse must become self-supporting"]', '[{"section":"4330(a)","description":"Court may order spousal support for any period of time"},{"section":"4330(b)","description":"Goal of self-support within reasonable time — Gavron warning"}]', '["spousal_support_order","FL-150","FL-157","vocational_evaluation","judgment"]', '["california-family-law-expansion-audit"]', 'California Family Court', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_080', 'REGULIS', 'CASE_LAW', 'CA', 'Marriage of Williamson (2014) 226 Cal.App.4th 1303', 'Marriage of Williamson', 'Vocational Evaluation in Spousal Support', 'Court may order a vocational evaluation to assess a supported spouse''s ability to become self-supporting. Evaluator considers age, health, education, work history, and labor market conditions.', '["Court may order vocational evaluation under FC § 4331","Evaluator assesses earning capacity — not just current earnings","Considers age, health, education, marketable skills, job market","Report admissible as expert opinion on employability","Imputation of income based on ability and opportunity to work"]', '[{"section":"Holding","description":"Vocational evaluation proper for determining earning capacity and imputing income"},{"section":"Standard","description":"Earning capacity based on ability and opportunity — not willingness to work"}]', '["vocational_evaluation","spousal_support_order","FL-150","earning_capacity_report"]', '["california-family-law-expansion-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- END BATCH 6 — 26 standards total
-- ADVOCIS: std_adv_031 through std_adv_046 (16 standards)
-- REGULIS: std_reg_072 through std_reg_080 (9 standards)
-- ═══════════════════════════════════════════════════════════════════════════
