-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 5
-- ═══════════════════════════════════════════════════════════════════════════
-- Case law expansion, constitutional provisions, additional professional
-- standards, and gap-filling across all Citizens.
-- Generated: March 17, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- CASE LAW — Landmark decisions each Citizen must know
-- ═══════════════════════════════════════════════════════════════════════════

-- ADVOCIS — Civil Rights Case Law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_024', 'ADVOCIS', 'CASE_LAW', 'US', 'Monell v. Department of Social Services (1978) 436 U.S. 658', 'Monell', 'Municipal Liability Under § 1983', 'Municipalities can be held liable under § 1983 when a policy or custom causes a constitutional deprivation.', '["Municipality liable for official policy or custom","No respondeat superior for isolated acts","Failure to train can be policy if deliberate indifference","Custom need not be formally adopted"]', '[{"section":"Holding","description":"Municipal liability for policy/custom — not respondeat superior"},{"section":"Custom","description":"Persistent and widespread practice constitutes custom"}]', '["1983_complaint","Monell_claim","municipal_liability","policy_challenge"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_025', 'ADVOCIS', 'CASE_LAW', 'US', 'Graham v. Connor (1989) 490 U.S. 386', 'Graham v. Connor', 'Objective Reasonableness Standard for Use of Force', 'All claims of excessive force by law enforcement analyzed under Fourth Amendment objective reasonableness standard.', '["Objective reasonableness standard","Judged from perspective of reasonable officer on scene","Considers severity of crime, immediate threat, active resistance","Not judged with 20/20 hindsight"]', '[{"section":"Holding","description":"4th Amendment governs excessive force claims"},{"section":"Test","description":"Objective reasonableness — totality of circumstances"}]', '["use_of_force_report","excessive_force_complaint","1983_complaint","police_report"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_026', 'ADVOCIS', 'CASE_LAW', 'US', 'Troxel v. Granville (2000) 530 U.S. 57', 'Troxel', 'Fundamental Right of Parents to Direct Upbringing', 'Parents have a fundamental liberty interest in the care, custody, and control of their children protected by substantive due process.', '["Fundamental right under 14th Amendment","Fit parents presumption — court must give special weight to parent wishes","State cannot infringe without compelling interest","Applies to custody, visitation, and education decisions"]', '[{"section":"Holding","description":"Parental rights are fundamental liberty interest"},{"section":"Standard","description":"Special weight to parents wishes — fit parent presumption"}]', '["custody_order","visitation_order","grandparent_visitation","parental_rights"]', '["constitutional-and-civil-rights-audit","california-family-law-expansion-audit"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_027', 'ADVOCIS', 'CASE_LAW', 'US', 'Santosky v. Kramer (1982) 455 U.S. 745', 'Santosky', 'Clear and Convincing Evidence for Parental Rights Termination', 'Before a state may sever the parent-child relationship, due process requires clear and convincing evidence.', '["Clear and convincing evidence standard required","Preponderance of evidence is insufficient for termination","Fundamental liberty interest of parents at stake","Applies to all states through 14th Amendment"]', '[{"section":"Holding","description":"Clear and convincing evidence required for TPR"},{"section":"Due Process","description":"14th Amendment protects parental rights"}]', '["TPR_petition","dependency_proceeding","parental_rights_order"]', '["constitutional-and-civil-rights-audit","california-cps-child-welfare-audit"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));

-- REGULIS — Key real estate / insurance case law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_069', 'REGULIS', 'CASE_LAW', 'CA', 'Green v. Superior Court (1974) 10 Cal.3d 616', 'Green v. Superior Court', 'Implied Warranty of Habitability', 'Landmark California case establishing implied warranty of habitability in residential leases — tenant may withhold rent for uninhabitable conditions.', '["Implied warranty of habitability in every residential lease","Material breach excuses rent payment","Conditions must be substantial, not trivial","Remedies include rent withholding and repair-and-deduct"]', '[{"section":"Holding","description":"Implied warranty of habitability exists in California residential leases"},{"section":"Remedy","description":"Tenant may withhold rent for material breach"}]', '["habitability_complaint","rent_withholding","repair_request","unlawful_detainer_defense"]', '["california-housing-tenant-rights-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_070', 'REGULIS', 'CASE_LAW', 'CA', 'Marriage of Feldman (2007) 153 Cal.App.4th 1470', 'Feldman', 'Fiduciary Duty Breach — Community Property Concealment', 'Remedies for breach of fiduciary duty between spouses including 100% award of concealed assets.', '["Non-disclosing spouse may forfeit concealed asset entirely","Remedies include 50/100% of undisclosed asset plus attorney fees","Court may impose sanctions","Applies post-separation through final division"]', '[{"section":"Holding","description":"100% of undisclosed asset awarded to innocent spouse"},{"section":"Remedy","description":"FC §1101(h) sanctions for breach of fiduciary duty"}]', '["disclosure_violation","hidden_asset","FL-140","property_division"]', '["california-family-law-expansion-audit","california-real-estate-transaction-fraud-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_071', 'REGULIS', 'CASE_LAW', 'CA', 'Moradi-Shalal v. Fireman''s Fund (1988) 46 Cal.3d 287', 'Moradi-Shalal', 'No Private Right of Action Under Insurance Code § 790.03', 'There is no private cause of action for violation of the unfair claims practices provisions of the Insurance Code.', '["No direct suit under IC § 790.03","Must bring bad faith tort claim instead","Egan v. Mutual of Omaha remains for bad faith tort","DOI administrative enforcement still available"]', '[{"section":"Holding","description":"No private right of action under IC § 790.03"},{"section":"Alternative","description":"Bad faith tort action under covenant of good faith"}]', '["insurance_complaint","bad_faith_claim","denial_letter"]', '["california-insurance-bad-faith-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- ETHICARA — Forensic psychiatry case law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_014', 'ETHICARA', 'CASE_LAW', 'CA', 'People v. Kelly (1976) 17 Cal.3d 24', 'Kelly / Kelly-Frye', 'Scientific Evidence Admissibility — California Standard', 'California standard for admissibility of new scientific evidence — must be generally accepted in the relevant scientific community (Kelly-Frye test).', '["New scientific technique must be generally accepted in relevant field","Testimony from qualified expert required","Court acts as gatekeeper","Applies in California state courts (not Daubert)"]', '[{"section":"Holding","description":"General acceptance test for new scientific evidence in California"},{"section":"Three-prong test","description":"Reliability of method, qualification of witness, correct procedures"}]', '["expert_testimony","scientific_evidence","forensic_report","motion_to_exclude"]', '["abpn-psychiatry-and-neurology-standards-audit","forensic-photo-comparison-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- FISCARA — Banking case law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_025', 'FISCARA', 'CASE_LAW', 'US', 'Safeco Ins. Co. v. Burr (2007) 551 U.S. 47', 'Safeco v. Burr', 'Willful FCRA Violation Standard', 'Willful violation of FCRA requires knowing or reckless disregard — good faith reading of statute defeats willfulness.', '["Willful requires knowing or reckless disregard of FCRA requirements","Reasonable but erroneous interpretation is not willful","Statutory damages ($100-$1,000) only for willful violations","Negligent violations: actual damages only"]', '[{"section":"Holding","description":"Reckless disregard of statutory duty satisfies willfulness"},{"section":"Safe harbor","description":"Good faith interpretation of FCRA defeats willfulness claim"}]', '["FCRA_complaint","adverse_action_notice","consumer_dispute","willful_violation"]', '["fcra-chexsystems-consumer-report-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CONSTITUTIONAL PROVISIONS — Additional amendments
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_028', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. V', '5th Amendment', 'Fifth Amendment — Due Process, Self-Incrimination, Double Jeopardy', 'Federal due process, protection against self-incrimination, double jeopardy, and takings without just compensation.', '["Grand jury indictment for capital crimes","No double jeopardy","No compelled self-incrimination (Miranda)","Due process of law before deprivation","Just compensation for takings"]', '[{"section":"Due Process Clause","description":"Federal government cannot deprive life, liberty, property without due process"},{"section":"Self-Incrimination Clause","description":"Cannot be compelled to be a witness against oneself"},{"section":"Takings Clause","description":"Private property cannot be taken without just compensation"}]', '["criminal_defense","Miranda_warning","grand_jury","eminent_domain","federal_complaint"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_029', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. VI', '6th Amendment', 'Sixth Amendment — Right to Counsel, Speedy Trial, Confrontation', 'Criminal defendant rights including counsel, speedy trial, jury trial, and confrontation of witnesses.', '["Right to speedy and public trial","Right to impartial jury","Right to be informed of charges","Right to confront witnesses","Right to compulsory process for defense witnesses","Right to assistance of counsel"]', '[{"section":"Speedy Trial","description":"Right to speedy trial"},{"section":"Confrontation Clause","description":"Right to confront adverse witnesses"},{"section":"Counsel Clause","description":"Right to effective assistance of counsel"}]', '["criminal_complaint","motion_to_dismiss","habeas_petition","ineffective_counsel_claim"]', '["constitutional-and-civil-rights-audit"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_030', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. VIII', '8th Amendment', 'Eighth Amendment — Cruel and Unusual Punishment, Excessive Bail/Fines', 'Prohibits excessive bail, excessive fines, and cruel and unusual punishment.', '["No excessive bail","No excessive fines (incorporated against states via Timbs v. Indiana)","No cruel and unusual punishment","Proportionality requirement for sentences"]', '[{"section":"Bail Clause","description":"Excessive bail prohibited"},{"section":"Fines Clause","description":"Excessive fines prohibited — incorporated"},{"section":"Punishment Clause","description":"Cruel and unusual punishment prohibited"}]', '["bail_motion","sentencing","conditions_of_confinement","civil_forfeiture"]', '["constitutional-and-civil-rights-audit"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADDITIONAL PROFESSIONAL STANDARDS
-- ═══════════════════════════════════════════════════════════════════════════

-- FACIALEX — additional forensic standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_003', 'FACIALEX', 'PROFESSIONAL_STANDARD', 'US', 'SWGDE Digital & Multimedia Evidence Best Practices', 'SWGDE Standards', 'Scientific Working Group on Digital Evidence', 'Best practices for acquisition, examination, and reporting of digital and multimedia evidence.', '["Chain of custody documentation","Hash verification of digital evidence","Metadata preservation","Write-blocking during acquisition","Peer review of conclusions"]', '[{"section":"Acquisition","description":"Digital evidence acquisition standards"},{"section":"Examination","description":"Analysis methodology"},{"section":"Reporting","description":"Documentation and reporting requirements"}]', '["digital_evidence","photo_analysis","video_evidence","metadata_report"]', '["forensic-photo-comparison-audit"]', 'SWGDE', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_004', 'FACIALEX', 'CASE_LAW', 'US', 'Frye v. United States (1923) 293 F. 1013', 'Frye', 'General Acceptance Test for Scientific Evidence', 'Original standard for admissibility of scientific evidence — must be generally accepted in the particular field.', '["Scientific principle must be generally accepted","Accepted in the particular field to which it belongs","Applied in some state courts instead of Daubert","Stricter test — excludes novel science"]', '[{"section":"Holding","description":"General acceptance test for scientific evidence"},{"section":"Application","description":"Used in California state courts (Kelly-Frye)"}]', '["expert_testimony","scientific_evidence","forensic_report","admissibility_motion"]', '["forensic-photo-comparison-audit"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));

-- VIGILUS — SIM swap / identity crime
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_006', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 530.5', 'PC § 530.5', 'California Identity Theft', 'Using personal identifying information of another person for any unlawful purpose.', '["Willfully obtains personal identifying information","Uses it for any unlawful purpose","Without consent of the person","Includes phishing, SIM swapping, account takeover"]', '[{"section":"530.5(a)","description":"Identity theft — personal identifying information"},{"section":"530.5(c)(3)","description":"Acquiring personal information via electronic means"},{"section":"530.6","description":"Identity theft victim expedited process"}]', '["identity_theft_report","police_report","FTC_affidavit","credit_freeze"]', '[]', 'California AG / DA', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_007', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '47 USC § 222', 'CPNI', 'Customer Proprietary Network Information', 'Telecommunications carriers must protect customer proprietary network information and obtain approval before using for marketing.', '["Carriers must protect CPNI from unauthorized access","Customer approval required for marketing use","SIM swap protections required","Authentication before account changes"]', '[{"section":"222(a)","description":"Privacy of customer information"},{"section":"222(c)","description":"Confidentiality of CPNI"},{"section":"222(d)","description":"Permitted exceptions"}]', '["SIM_swap","account_change","carrier_record","CPNI_complaint"]', '[]', 'FCC', 1, 1, datetime('now'), datetime('now'));

-- INTEGRA — Additional operational guardrails
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_004', 'INTEGRA', 'PROFESSIONAL_STANDARD', 'US', 'ABA Model Rules of Professional Conduct — Technology Competence (Comment 8 to Rule 1.1)', 'ABA Tech Competence', 'Technology Competence Requirement for Attorneys', 'Lawyers must keep abreast of the benefits and risks associated with relevant technology.', '["Duty to understand technology relevant to practice","Includes e-discovery, data security, client communication","Adopted by majority of state bars","Failure may constitute lack of competence"]', '[{"section":"Rule 1.1 Comment 8","description":"Maintaining competence includes technology"},{"section":"Implication","description":"AI-assisted legal tools must meet competence standard"}]', '["compliance_tool","AI_disclosure","technology_assessment","platform_disclaimer"]', '["project-context-and-guardrails"]', 'State Bar', 0, 1, datetime('now'), datetime('now'));

-- PRIVAXIS — Additional federal privacy
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_007', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '20 USC § 1232g (FERPA)', 'FERPA', 'Family Educational Rights and Privacy Act', 'Federal law protecting privacy of student education records.', '["Parents/students right to inspect records","Consent required before disclosure","Annual notification of rights","Complaint mechanism through DOE","Directory information exceptions"]', '[{"section":"1232g(a)","description":"Rights to inspect and amend"},{"section":"1232g(b)","description":"Consent before disclosure"},{"section":"1232g(d)","description":"Students rights after age 18"}]', '["education_record","transcript","student_data","FERPA_consent"]', '[]', 'U.S. Department of Education', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_008', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '15 USC §§ 6501-6506 (COPPA)', 'COPPA', 'Children''s Online Privacy Protection Act', 'Federal law regulating online collection of personal information from children under 13.', '["Verifiable parental consent before collecting PI from children under 13","Privacy policy must be posted","Parental right to review and delete","FTC enforcement — up to $50,120 per violation"]', '[{"section":"6502","description":"Verifiable parental consent requirement"},{"section":"6502(b)","description":"Regulation of unfair/deceptive online collection"},{"section":"6504","description":"Safe harbor programs"}]', '["privacy_policy","parental_consent","child_data","COPPA_compliance"]', '[]', 'FTC', 0, 1, datetime('now'), datetime('now'));

-- CLARIDEX — additional reporting standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_cla_004', 'CLARIDEX', 'FEDERAL_STATUTE', 'US', '26 USC §§ 501(c)(3)', 'IRC § 501(c)(3)', 'Tax-Exempt Organization Requirements', 'Federal requirements for tax-exempt charitable organizations including operational and organizational tests.', '["Organized and operated exclusively for exempt purposes","No private inurement","No substantial lobbying","No political campaign intervention","Annual Form 990 filing"]', '[{"section":"501(c)(3)","description":"Exemption requirements"},{"section":"509(a)","description":"Private foundation vs. public charity"},{"section":"6033","description":"Annual information return (Form 990)"}]', '["Form_990","determination_letter","articles_of_incorporation","exempt_purpose_statement"]', '[]', 'IRS', 0, 1, datetime('now'), datetime('now'));

-- METRIQA — additional analytics standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_met_003', 'METRIQA', 'PROFESSIONAL_STANDARD', 'US', 'SaaS Metrics Standards (Bessemer, a16z, SaaS Capital frameworks)', 'SaaS Metrics', 'Industry Standard SaaS Metrics', 'Industry-standard metrics for measuring SaaS business health and growth.', '["ARR/MRR — Annual/Monthly Recurring Revenue","CAC — Customer Acquisition Cost","LTV — Lifetime Value (LTV:CAC > 3:1)","Churn — Net Revenue Retention > 100%","Rule of 40 (growth rate + profit margin)","Magic Number (revenue efficiency)"]', '[{"section":"ARR/MRR","description":"Revenue run rate metrics"},{"section":"Unit Economics","description":"CAC, LTV, payback period"},{"section":"Efficiency","description":"Burn multiple, Rule of 40, Magic Number"}]', '["investor_deck","financial_model","growth_report","board_presentation"]', '[]', 'Industry Standard', 0, 1, datetime('now'), datetime('now'));

-- NEXARIS — additional partnership standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_nex_004', 'NEXARIS', 'FEDERAL_STATUTE', 'US', '15 USC §§ 41-58 (FTC Act)', 'FTC Act', 'Federal Trade Commission Act', 'Establishes the FTC and prohibits unfair methods of competition and unfair or deceptive acts or practices.', '["Section 5: Unfair methods of competition prohibited","Section 5: Unfair or deceptive acts prohibited","FTC rulemaking authority","Investigative powers and subpoena authority"]', '[{"section":"45","description":"Unfair methods of competition and deceptive practices"},{"section":"46","description":"FTC investigative powers"},{"section":"57a","description":"FTC rulemaking authority"}]', '["FTC_complaint","consent_decree","competitive_practice","partnership_agreement"]', '[]', 'FTC', 0, 1, datetime('now'), datetime('now'));

-- LEXARC — IP and corporate governance
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_006', 'LEXARC', 'FEDERAL_STATUTE', 'US', '17 USC §§ 101-1401 (Copyright Act)', 'Copyright Act', 'Federal Copyright Law', 'Protects original works of authorship including literary, musical, dramatic, and software works.', '["Automatic protection upon fixation in tangible medium","Registration provides additional remedies","Fair use defense (4 factors)","DMCA safe harbors for service providers","Statutory damages: $750-$30,000 per work ($150,000 willful)"]', '[{"section":"102","description":"Subject matter of copyright"},{"section":"106","description":"Exclusive rights"},{"section":"107","description":"Fair use"},{"section":"501","description":"Infringement"},{"section":"512","description":"DMCA safe harbors"}]', '["copyright_registration","DMCA_notice","license_agreement","infringement_complaint"]', '["executive-style-enforcer-corporate-voice-and-structure"]', 'Copyright Office / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_007', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 16100-16962 (Uniform Partnership Act)', 'CA UPA', 'California Revised Uniform Partnership Act', 'Governs general partnerships including formation, partner duties, and dissolution.', '["Partnership formed by association of two or more persons","Partners owe fiduciary duties of loyalty and care","Joint and several liability for partnership obligations","Partnership at will — any partner may dissociate"]', '[{"section":"16202","description":"Formation of partnership"},{"section":"16404","description":"General standards of partner conduct"},{"section":"16801","description":"Events causing dissolution"}]', '["partnership_agreement","partner_duties","dissolution_notice","buyout_agreement"]', '["executive-style-enforcer-corporate-voice-and-structure"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- SYNTARA — additional technology standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_004', 'SYNTARA', 'INTERNATIONAL', 'US', 'ISO/IEC 27001:2022 — Information Security Management Systems', 'ISO 27001', 'Information Security Management System Standard', 'International standard for establishing, implementing, maintaining, and continually improving an ISMS.', '["Risk assessment and treatment methodology","Statement of Applicability","Security controls (Annex A — 93 controls in 4 domains)","Internal audit program","Management review","Continual improvement"]', '[{"section":"Clause 4-10","description":"ISMS requirements"},{"section":"Annex A","description":"93 reference controls"},{"section":"A.5","description":"Organizational controls"},{"section":"A.8","description":"Technological controls"}]', '["ISMS_policy","risk_assessment","SOA","internal_audit","certification"]', '[]', 'ISO / Certification Bodies', 0, 1, datetime('now'), datetime('now'));

-- VESTARA — additional securities
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_ves_004', 'VESTARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 78a-78qq (Securities Exchange Act of 1934)', 'Exchange Act', 'Securities Exchange Act of 1934', 'Governs secondary trading of securities, reporting by public companies, and anti-fraud provisions.', '["Section 10(b) and Rule 10b-5: anti-fraud in connection with securities","Periodic reporting (10-K, 10-Q, 8-K)","Proxy solicitation rules","Insider trading prohibition","SEC registration of exchanges and broker-dealers"]', '[{"section":"78j(b)","description":"Anti-fraud provision (Section 10(b))"},{"section":"78m","description":"Periodic and other reports"},{"section":"78n","description":"Proxy solicitation rules"},{"section":"78p","description":"Short-swing profit recovery (Section 16)"}]', '["10-K","10-Q","8-K","proxy_statement","insider_trading_report"]', '[]', 'SEC', 1, 1, datetime('now'), datetime('now'));
