-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 22
-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS: Additional local rent ordinances (LA, San Jose, Richmond,
-- Mountain View). Labor expansion: WARN, PAGA, meal/rest breaks,
-- wage theft prevention, independent contractor (AB 5), prevailing wage,
-- workers comp, Cal/OSHA.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Additional Local Rent Ordinances
-- ═══════════════════════════════════════════════════════════════════════════

-- NOTE: REGULIS IDs continue from seed 020 (std_reg_149). These start at std_reg_150.

-- LA Rent Stabilization Ordinance
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_150', 'REGULIS', 'STATE_STATUTE', 'CA', 'Los Angeles Municipal Code Ch. XV, Art. 1 (Rent Stabilization Ordinance)', 'LAMC Ch. XV Art. 1 / RSO', 'Los Angeles Rent Stabilization Ordinance', 'Covers approximately 624,000 rental units built before October 1, 1978. Annual allowable increase set by LAHD (typically 3-8%). 12 just cause grounds for eviction. Owner move-in requires relocation assistance. Primary renovation evictions (Ellis Act) subject to extensive requirements. Mandatory registration with LAHD. No vacancy decontrol exemption from just cause.', '["Covers units built before October 1, 1978","Annual allowable increase set by LAHD — based on CPI","12 just cause grounds for eviction","Owner move-in: good faith intent, relocation payment required","Primary renovation: requires extensive notice and relocation","Ellis Act withdrawal: subject to local requirements plus state law","Mandatory registration with LA Housing Department","Relocation assistance: $8,650-$21,200+ depending on tenant category","RAP (Rent Adjustment Program) — petition for adjustments","No vacancy decontrol from just cause (Costa-Hawkins only decontrols rent)"]', '[{"section":"151.01-151.02","description":"Definitions and covered units"},{"section":"151.04","description":"Annual allowable rent increase"},{"section":"151.06","description":"Registration requirements"},{"section":"151.09","description":"12 just cause grounds for eviction"},{"section":"151.09(a)(8)","description":"Owner move-in eviction requirements"},{"section":"151.09(g)","description":"Relocation assistance amounts by category"},{"section":"151.10","description":"Rent adjustment — landlord and tenant petitions"}]', '["rent_increase_notice","eviction_notice","LAHD_registration","relocation_payment","OMI_declaration","rent_adjustment_petition","RAP_hearing"]', '["california-housing-tenant-audit"]', 'LA Housing Department (LAHD)', 1, 1, datetime('now'), datetime('now'));

-- San Jose Apartment Rent Ordinance
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_151', 'REGULIS', 'STATE_STATUTE', 'CA', 'San Jose Municipal Code Ch. 17.23 (Apartment Rent Ordinance — Measure V)', 'SJMC Ch. 17.23 / Measure V', 'San Jose Apartment Rent Ordinance — Measure V', 'Covers apartments (3+ units) built before September 7, 1979. Annual allowable increase of 5% or 8% of CPI (whichever is greater). Just cause required for eviction. Petition process for additional rent increases. Anti-retaliation protections. Tenant may petition for downward rent adjustment for decreased services or habitability issues.', '["Covers apartments of 3+ units built before September 7, 1979","Annual increase: 5% or 8% of CPI, whichever is greater","Just cause required for eviction","Landlord petition for increase above annual adjustment","Tenant petition for decrease based on reduced services","Voluntary vacancy decontrol under Costa-Hawkins","Anti-retaliation protections","Mandatory registration and annual fee","Relocation assistance for no-fault evictions"]', '[{"section":"17.23.200","description":"Covered units — apartments, 3+ units, pre-9/7/1979"},{"section":"17.23.310","description":"Annual allowable rent increase"},{"section":"17.23.460","description":"Just cause eviction requirements"},{"section":"17.23.500","description":"Petition process for additional increases"},{"section":"17.23.600","description":"Tenant petition for decrease"},{"section":"17.23.700","description":"Anti-retaliation provisions"}]', '["rent_increase_notice","eviction_notice","landlord_petition","tenant_petition","registration_filing","relocation_assistance"]', '["california-housing-tenant-audit"]', 'San Jose Rent Stabilization Program', 1, 1, datetime('now'), datetime('now'));

-- Richmond Fair Rent Ordinance
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_152', 'REGULIS', 'STATE_STATUTE', 'CA', 'Richmond Municipal Code Ch. 11.100 (Fair Rent, Just Cause for Eviction, and Homeowner Protection Ordinance)', 'RMC Ch. 11.100', 'Richmond Fair Rent, Just Cause for Eviction, and Homeowner Protection', 'Voter-approved ordinance (Measure L, 2016) covering most rental units. Annual CPI-based increase (max 100% of CPI). Just cause required for all evictions. Elected Rent Board. Broad coverage including single-family homes (unlike many jurisdictions). Relocation assistance for no-fault evictions. Banking of rent increases permitted in limited circumstances.', '["Covers most rental units including single-family homes","Annual increase: 100% of CPI (no additional percentage added)","Just cause required for all evictions","Elected 5-member Rent Board","Relocation assistance for no-fault evictions","Registration required for all covered units","Tenant petitions for rent decrease available","Anti-retaliation and anti-harassment protections","Banking of increases in limited circumstances"]', '[{"section":"11.100.030","description":"Covered units — broad, includes single-family"},{"section":"11.100.040","description":"Annual general adjustment — CPI-based"},{"section":"11.100.050","description":"Just cause for eviction requirements"},{"section":"11.100.060","description":"Petition process — landlord and tenant"},{"section":"11.100.070","description":"Relocation assistance for no-fault evictions"},{"section":"11.100.080","description":"Rent Board — elected, 5 members"}]', '["rent_increase_notice","eviction_notice","rent_board_petition","registration","relocation_payment","hearing_decision"]', '["california-housing-tenant-audit"]', 'Richmond Rent Board', 1, 1, datetime('now'), datetime('now'));

-- Mountain View CSFRA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_153', 'REGULIS', 'STATE_STATUTE', 'CA', 'Mountain View City Code Ch. 36, Art. XVII (CSFRA — Measure V, 2016)', 'CSFRA / MV Measure V', 'Mountain View Community Stabilization and Fair Rent Act', 'Voter-approved (Measure V, 2016). Covers most rental units built before February 1, 1995. Elected 5-member Rental Housing Committee sets annual adjustment. Just cause for eviction. Allows landlords to petition for fair return on investment. Tenant protections include anti-harassment, anti-retaliation, and relocation assistance.', '["Covers units built before February 1, 1995","Elected Rental Housing Committee sets annual adjustment","Just cause required for eviction","Landlord fair return petition available","Tenant petition for excessive rent increase","Anti-harassment and anti-retaliation protections","Relocation assistance for no-fault evictions","Registration required for all covered units"]', '[{"section":"1700","description":"Findings and purpose"},{"section":"1702","description":"Definitions and covered units"},{"section":"1706","description":"Annual general adjustment"},{"section":"1710","description":"Just cause for eviction — enumerated grounds"},{"section":"1712","description":"Petition process for adjustments"},{"section":"1714","description":"Relocation assistance requirements"}]', '["rent_increase_notice","eviction_notice","RHC_petition","registration","relocation_payment","hearing_decision"]', '["california-housing-tenant-audit"]', 'Mountain View Rental Housing Committee', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Labor Law Expansion
-- ═══════════════════════════════════════════════════════════════════════════

-- WARN Act — Federal
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_154', 'REGULIS', 'FEDERAL_STATUTE', 'US', '29 USC §§ 2101-2109 (Worker Adjustment and Retraining Notification Act)', 'WARN Act', 'Federal WARN Act — 60-Day Plant Closing and Mass Layoff Notice', 'Requires employers with 100+ employees to provide 60 calendar days advance written notice of plant closings and mass layoffs. Plant closing: permanent/temporary shutdown affecting 50+ employees. Mass layoff: reduction of 500+ employees or 50-499 if 33% of workforce. Damages for violation: back pay and benefits for each day of violation (up to 60 days). Federal court jurisdiction.', '["60-day advance written notice required","Applies to employers with 100+ full-time employees","Plant closing: facility shutdown affecting 50+ employees at single site","Mass layoff: 500+ employees, or 50-499 if 33%+ of workforce","Notice to: affected workers, state dislocated worker unit, chief elected official of local government","Exceptions: faltering company, unforeseeable business circumstances, natural disaster","Damages: back pay and benefits for each day of violation, up to 60 days","$500/day civil penalty for failure to notify local government","No punitive damages available"]', '[{"section":"2101","description":"Definitions — employer, employee, plant closing, mass layoff"},{"section":"2102(a)","description":"60-day notice requirement"},{"section":"2102(b)","description":"Notice content requirements"},{"section":"2102(c)","description":"Notice to state dislocated worker unit"},{"section":"2103","description":"Exceptions — faltering company, unforeseeable, natural disaster"},{"section":"2104","description":"Damages — back pay and benefits up to 60 days"},{"section":"2104(a)(3)","description":"Civil penalty — $500/day to local government"}]', '["WARN_notice","layoff_notice","plant_closing_notice","employment_records","back_pay_calculation","WARN_violation_complaint"]', '["california-labor-employment-audit"]', 'Federal Courts (private enforcement)', 1, 1, datetime('now'), datetime('now'));

-- CA WARN Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_155', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 1400-1408 (California WARN Act)', 'LC §§ 1400-1408', 'California WARN Act — 60-Day Notice for Mass Layoffs and Relocations', 'California''s WARN Act is broader than federal: covers employers with 75+ employees (vs federal 100), includes relocations, and has no percentage-of-workforce exception. Applies to mass layoff (50+), relocation (100+ miles), or termination. 60-day notice to EDD, local workforce investment board, chief elected official, and affected employees.', '["Applies to employers with 75+ employees in preceding 12 months (not 100)","60-day advance written notice required","Mass layoff: 50+ employees within 30-day period (no percentage exception)","Relocation: moving operations 100+ miles away","Termination: cessation of operations at a covered establishment","Notice to: affected employees, EDD, LWIB, chief elected official","No faltering company exception (unlike federal WARN)","Damages: back pay and value of benefits for each day of violation","Civil penalty payable to each aggrieved employee"]', '[{"section":"1400","description":"Definitions — employer, covered establishment, mass layoff, relocation"},{"section":"1401(a)","description":"60-day notice requirement — broader than federal"},{"section":"1401(b)","description":"Contents of notice"},{"section":"1402","description":"Notice to EDD, LWIB, chief elected official"},{"section":"1402.5","description":"Exceptions — natural disaster, war, physical calamity"},{"section":"1403","description":"Damages — back pay and benefits, attorney fees"},{"section":"1404","description":"No waiver of rights — penalty for violation"}]', '["CA_WARN_notice","EDD_notification","LWIB_notification","layoff_notice","back_pay_calculation","violation_complaint"]', '["california-labor-employment-audit"]', 'California Superior Court / EDD', 1, 1, datetime('now'), datetime('now'));

-- PAGA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_156', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 2698-2699.8 (Private Attorneys General Act — PAGA)', 'LC §§ 2698-2699.8 / PAGA', 'Private Attorneys General Act — Employee Enforcement of Labor Code', 'Allows aggrieved employees to bring representative actions on behalf of themselves and other current/former employees for Labor Code violations. Employee acts as private attorney general. 75% of penalties to LWDA, 25% to employees. Must exhaust administrative remedy: written notice to LWDA and employer 65 days before filing. Reformed by AB 2288/SB 92 (2024) — standing, manageability, penalty structure changes.', '["Aggrieved employee may file representative action for Labor Code violations","Must give written notice to LWDA and employer 65 days before filing (§ 2699.3)","LWDA has 65 days to respond or employee may proceed","Penalties: 75% to LWDA, 25% to aggrieved employees","Default penalty: $100 per employee per pay period (initial), $200 subsequent","Standing: must be aggrieved employee — personally suffered violation","No class action requirements — representative action","2024 reforms (AB 2288/SB 92): penalty caps, cure provisions, standing clarification","Employer cure: 15% penalty reduction if corrected within certain timeframe","Cannot waive PAGA rights in arbitration agreement (Iskanian v. CLS Transportation)"]', '[{"section":"2698","description":"Title — Private Attorneys General Act of 2004"},{"section":"2699(a)","description":"Authority to bring civil action for Labor Code violations"},{"section":"2699(e)","description":"Default penalty — $100/$200 per employee per pay period"},{"section":"2699.3","description":"Administrative exhaustion — 65-day notice to LWDA"},{"section":"2699.3(a)","description":"Notice content requirements"},{"section":"2699.5","description":"Labor Code sections covered by PAGA"},{"section":"2699.8","description":"2024 reforms — penalty structure, cure provisions"}]', '["PAGA_notice","LWDA_filing","representative_action_complaint","penalty_calculation","employer_cure_response","settlement_agreement","LWDA_settlement_approval"]', '["california-labor-employment-audit"]', 'California Superior Court / LWDA', 1, 1, datetime('now'), datetime('now'));

-- Meal and Rest Breaks
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_157', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 226.7, 512 (Meal and Rest Break Requirements)', 'LC §§ 226.7/512', 'California Meal Period and Rest Break Requirements', 'Employer must provide 30-minute duty-free meal period for shifts over 5 hours and second meal for shifts over 10 hours. Rest breaks: 10 minutes per 4 hours worked. Premium pay of one additional hour at regular rate for each missed meal/rest break. Brinker v. Superior Court (2012): employer must provide opportunity, not ensure taken.', '["30-minute meal period required for shifts over 5 hours (§ 512(a))","Second 30-minute meal for shifts over 10 hours (§ 512(a))","Meal period must be duty-free — relieved of all duties","Meal period must begin before end of 5th hour of work","Rest break: 10 minutes per 4 hours worked (IWC Orders)","Rest break must be in middle of each work period as practicable","Premium pay: 1 hour regular rate for each missed meal period (§ 226.7)","Premium pay: 1 hour regular rate for each missed rest break (§ 226.7)","Employer must provide opportunity — not required to ensure taken (Brinker)","On-duty meal period permitted only when nature of work prevents relief and written agreement"]', '[{"section":"512(a)","description":"Meal period required for shifts over 5 hours — 30 minutes"},{"section":"512(a) second","description":"Second meal for shifts over 10 hours"},{"section":"226.7(c)","description":"Premium pay — one hour regular rate for violation"},{"section":"IWC Order 4-2001","description":"Rest break — 10 minutes per 4 hours"},{"section":"Brinker","description":"Provide opportunity, not ensure compliance"}]', '["time_records","meal_period_waiver","premium_pay_calculation","wage_claim","PAGA_notice","class_action_complaint","payroll_records"]', '["california-labor-employment-audit"]', 'California DLSE / Superior Court', 1, 1, datetime('now'), datetime('now'));

-- AB 5 / Independent Contractor
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_158', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 2775 (AB 5 — ABC Test for Independent Contractors)', 'LC § 2775 / AB 5', 'ABC Test for Independent Contractor Classification', 'Codifies Dynamex ABC test: worker is employee unless hiring entity proves ALL three factors: (A) free from control and direction, (B) performs work outside usual course of business, and (C) independently established trade/occupation. Exemptions for specified professions (AB 2257) including licensed professionals, certain gig workers (Prop 22). Misclassification triggers back pay, benefits, penalties.', '["ABC test — all three prongs must be satisfied for IC classification","(A) Free from control and direction in performance of work","(B) Performs work outside usual course of hiring entity business","(C) Customarily engaged in independently established trade, occupation, or business","Failure to satisfy ANY prong = employee classification","Exemptions: licensed professionals, Prop 22 (rideshare/delivery), referral agencies, others (AB 2257)","Borello test retained for exempted categories","Misclassification penalties: back wages, benefits, employer taxes","PAGA enforcement available for misclassification","Willful misclassification: $5,000-$25,000 penalty per violation (LC § 226.8)"]', '[{"section":"2775(a)","description":"Presumption of employee status"},{"section":"2775(b)(1)","description":"ABC test — three-part conjunctive test"},{"section":"2776-2784","description":"Exemptions — professional services, business-to-business, referral agencies"},{"section":"226.8","description":"Willful misclassification penalties — $5K-$25K per violation"},{"section":"Dynamex","description":"Dynamex Operations West v. Superior Court (2018) — origin of ABC test"},{"section":"Prop 22","description":"App-based driver exemption (Proposition 22, 2020)"}]', '["worker_classification_analysis","IC_agreement","ABC_test_evaluation","Borello_factor_analysis","back_pay_calculation","EDD_audit","misclassification_complaint"]', '["california-labor-employment-audit"]', 'California DLSE / EDD / AG / Superior Court', 1, 1, datetime('now'), datetime('now'));

-- Prevailing Wage
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_159', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 1720-1784 (Prevailing Wage — Public Works)', 'LC §§ 1720-1784', 'California Prevailing Wage Law — Public Works Construction', 'Workers on public works projects must be paid prevailing wage rates determined by DIR. Applies to construction, alteration, demolition, installation, or repair work done under contract paid for in whole or in part with public funds. Contractors must be registered with DIR. Certified payroll records required. Penalties for violations.', '["Prevailing wage required for all public works over $1,000 (§ 1771)","Prevailing wage determined by DIR for each craft, classification, and locality","Contractor and subcontractor registration with DIR required (§ 1725.5)","Certified payroll records must be submitted to awarding body (§ 1776)","Apprenticeship requirements — must employ apprentices (§ 1777.5)","Penalties: contractor forfeits up to $200/day per worker for violations (§ 1775)","Debarment: contractor may be barred from public works for violations","Working hour restrictions: 8-hour day, 40-hour week (§ 1810-1815)","Overtime premium: 1.5x prevailing rate for hours over 8/day or 40/week","Joint labor-management enforcement allowed (§ 1771.2)"]', '[{"section":"1720","description":"Definitions — public works, construction"},{"section":"1720.2-1720.4","description":"Public works — what is and is not covered"},{"section":"1725.5","description":"Contractor registration with DIR"},{"section":"1771","description":"Prevailing wage requirement for all public works"},{"section":"1773","description":"DIR determination of prevailing rate"},{"section":"1775","description":"Penalties — up to $200/day per worker"},{"section":"1776","description":"Certified payroll records requirement"},{"section":"1777.5","description":"Apprenticeship requirements"}]', '["certified_payroll_records","prevailing_wage_determination","DIR_registration","public_works_contract","apprenticeship_records","penalty_assessment","debarment_order"]', '["california-labor-employment-audit","california-construction-compliance-audit"]', 'DIR Division of Labor Standards Enforcement', 1, 1, datetime('now'), datetime('now'));

-- Wage Theft Prevention
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_160', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 2810.5 (Wage Theft Prevention Act — AB 469)', 'LC § 2810.5', 'Wage Theft Prevention Act — Written Notice at Hire', 'Requires employers to provide written notice to nonexempt employees at time of hiring containing specified wage and employment information. Must notify of changes within 7 days. Information includes: rate of pay, overtime rate, pay day, employer name/address/phone, workers comp carrier, and any allowances claimed as part of minimum wage.', '["Written notice to nonexempt employees at time of hiring","Notice must include: rate(s) of pay and basis (hourly, salary, piece, commission)","Overtime rate(s) of pay","Regular pay day designated by employer","Employer legal name and DBA","Physical address of employer main office","Employer telephone number","Name, address, phone of workers compensation insurance carrier","Any allowances claimed as part of minimum wage (meals, lodging)","Notice of changes within 7 calendar days","Template available from DLSE (DLSE Notice to Employee form)"]', '[{"section":"2810.5(a)(1)","description":"Rate(s) of pay and basis thereof"},{"section":"2810.5(a)(2)","description":"Allowances claimed as part of minimum wage"},{"section":"2810.5(a)(3)","description":"Regular payday"},{"section":"2810.5(a)(4)","description":"Employer name, address, telephone"},{"section":"2810.5(a)(5)","description":"Workers compensation carrier information"},{"section":"2810.5(a)(8)","description":"Paid sick leave information"},{"section":"2810.5(b)","description":"Notify of changes within 7 calendar days"}]', '["DLSE_notice_to_employee","hiring_notice","wage_notice","change_notice","payroll_records","new_hire_packet"]', '["california-labor-employment-audit"]', 'California DLSE', 1, 1, datetime('now'), datetime('now'));

-- Workers Compensation Basics
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_161', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 3200-6002 (Workers'' Compensation)', 'LC §§ 3200-6002', 'California Workers'' Compensation — No-Fault Workplace Injury System', 'No-fault system: employer liability regardless of fault for work-related injuries and illnesses. Exclusive remedy against employer (workers comp bar) except for intentional harm. Benefits: medical treatment, temporary disability (2/3 of wages), permanent disability, supplemental job displacement, death benefits. Employers must carry workers comp insurance or self-insure.', '["No-fault liability — employer liable regardless of fault for work injuries","Exclusive remedy — workers comp bar against employer tort suits (§ 3600/3602)","Exception: dual capacity doctrine, intentional harm, power press violations","Medical treatment: employer pays all reasonable medical expenses","Temporary disability: 2/3 average weekly wages, max set by statute","Permanent disability: rated by AMA Guides and statutory formula","Supplemental job displacement voucher: $6,000 if no return to work","Death benefits: to dependents, plus burial allowance","Employer must carry insurance or qualify as self-insured (§ 3700)","Failure to carry insurance: misdemeanor, stop order, personal liability"]', '[{"section":"3200-3209","description":"Definitions — employee, employer, injury, course of employment"},{"section":"3600","description":"Conditions of employer liability — arising out of and in course of employment"},{"section":"3602","description":"Exclusive remedy — bar on tort suits against employer"},{"section":"3700","description":"Employer obligation to carry insurance or self-insure"},{"section":"4600","description":"Medical treatment — employer obligation"},{"section":"4650-4656","description":"Temporary disability benefits"},{"section":"4660-4664","description":"Permanent disability rating and benefits"},{"section":"5401","description":"Claims administration — DWC-1 claim form"}]', '["DWC_1_claim_form","workers_comp_policy","medical_report","QME_report","AME_report","temporary_disability_notice","permanent_disability_rating","return_to_work_plan"]', '["california-labor-employment-audit"]', 'DWC (Division of Workers Compensation) / WCAB', 0, 1, datetime('now'), datetime('now'));

-- Cal/OSHA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_162', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 6300-6719 (Cal/OSHA — Occupational Safety and Health)', 'LC §§ 6300-6719 / Cal/OSHA', 'California Occupational Safety and Health Act — Workplace Safety', 'California operates its own OSHA plan (Cal/OSHA) with standards at least as protective as federal OSHA. Employers must provide safe and healthful workplace. Illness and Injury Prevention Program (IIPP) required for all employers. Cal/OSHA may inspect without advance notice. Serious violations: up to $25,000 per violation. Willful violations: up to $156,259 per violation. Criminal penalties for willful violations causing death.', '["Every employer must provide safe and healthful workplace (§ 6400)","Injury and Illness Prevention Program (IIPP) required for all employers (§ 6401.7)","Written IIPP must include: responsibility, compliance, communication, hazard assessment, training, recordkeeping","Cal/OSHA Standards Board adopts safety orders (CCR Title 8)","Inspection authority without advance notice (§ 6314)","Employee right to file complaint — anonymity protected (§ 6309)","Serious violation: up to $25,000 per violation","Willful violation: up to $156,259 per violation","Repeat violation: up to $156,259 per violation","Criminal penalties: willful violation causing death — up to 1 year jail and $100,000 fine"]', '[{"section":"6300","description":"Purpose — safe and healthful working conditions"},{"section":"6400","description":"Employer obligation to provide safe workplace"},{"section":"6401.7","description":"IIPP requirement for all employers"},{"section":"6309","description":"Employee complaint — investigation and anonymity"},{"section":"6314","description":"Inspection authority without advance notice"},{"section":"6423-6432","description":"Penalties — serious, willful, repeat violations"},{"section":"6425","description":"Criminal penalties for willful violation causing death"},{"section":"CCR Title 8","description":"Cal/OSHA Standards Board — safety orders"}]', '["IIPP","Cal_OSHA_inspection_report","citation","abatement_plan","injury_log_OSHA_300","employee_complaint","safety_training_records","hazard_assessment"]', '["california-labor-employment-audit"]', 'Cal/OSHA Division of Occupational Safety and Health', 0, 1, datetime('now'), datetime('now'));
