-- Vernen Legal Compliance — Oregon Employment Rules (Deep Dive)
-- ~80 rules covering wages, leave, discrimination, hiring, safety
-- All citations to Oregon Revised Statutes (ORS) and Oregon Administrative Rules (OAR)
-- IDs start at or-emp-101 (or-emp-006 and or-emp-007 already exist)
-- Created: April 5, 2026

-- ============================================================
-- WAGES & HOURS (20 rules: or-emp-101 through or-emp-120)
-- ============================================================

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-101', 'OR-EMP-101', 'Minimum Wage — Standard Rate', 'Oregon standard minimum wage is $14.70/hour effective July 1, 2024. Applies to all employers statewide except Portland metro and nonurban counties. Adjusted annually for inflation per ORS 653.025. Employers who fail to pay minimum wage are liable for unpaid wages plus penalty wages up to 30 days of wages under ORS 652.150.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-07-01', 'ORS § 653.025', 'https://www.oregon.gov/boli/workers/pages/minimum-wage.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-102', 'OR-EMP-102', 'Minimum Wage — Portland Metro', 'Portland metro area minimum wage is $15.45/hour effective July 1, 2024. Applies to employers within the Portland urban growth boundary as defined by ORS 653.025(2). The Portland metro rate is $0.75 above the standard rate. Employers must pay the rate applicable to the location where work is performed, not the employer''s business address.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-07-01', 'ORS § 653.025(2)', 'https://www.oregon.gov/boli/workers/pages/minimum-wage.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-103', 'OR-EMP-103', 'Minimum Wage — Nonurban Counties', 'Nonurban county minimum wage is $13.70/hour effective July 1, 2024. Applies to Baker, Coos, Crook, Curry, Douglas, Gilliam, Grant, Harney, Jefferson, Klamath, Lake, Malheur, Morrow, Sherman, Umatilla, Union, Wallowa, and Wheeler counties per ORS 653.025(3). Rate is $1.00 below the standard rate.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-07-01', 'ORS § 653.025(3)', 'https://www.oregon.gov/boli/workers/pages/minimum-wage.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-104', 'OR-EMP-104', 'Overtime Pay Requirements', 'Oregon requires overtime at 1.5x regular rate for all hours worked over 40 in a workweek per ORS 653.261. Manufacturing employees must also receive overtime for hours worked over 10 in a single day. Exemptions mirror federal FLSA for executive, administrative, professional, and outside sales employees. Employers must maintain accurate time records per OAR 839-020-0080. Willful failure to pay overtime subjects employer to penalty wages under ORS 652.150.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.261; OAR 839-020-0030', 'https://www.oregon.gov/boli/workers/pages/overtime.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-105', 'OR-EMP-105', 'Meal Periods', 'Employers must provide a 30-minute unpaid meal period for work shifts of 6 or more hours per OAR 839-020-0050. The meal period must be uninterrupted and the employee must be relieved of all duties. If the employer requires the employee to remain on-duty or at the workplace during the meal period, it must be paid. Employees in certain industries (food processing, canneries) have specific scheduling requirements under OAR 839-020-0050(2).', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 839-020-0050', 'https://www.oregon.gov/boli/workers/pages/meals-and-breaks.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-106', 'OR-EMP-106', 'Rest Periods', 'Employers must provide a paid 10-minute rest period for every 4 hours of work or major portion thereof per OAR 839-020-0050(1)(b). Rest periods must be taken approximately in the middle of each 4-hour segment. Rest breaks are paid time and count as hours worked. Employers may not require employees to remain on the premises during rest periods unless necessary for business operations and compensated.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 839-020-0050(1)(b)', 'https://www.oregon.gov/boli/workers/pages/meals-and-breaks.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-107', 'OR-EMP-107', 'Agricultural Worker Overtime', 'Agricultural workers receive overtime at 1.5x regular rate for hours over 55/week (2024), phasing down to 40/week by 2027 under HB 4002 (2022). Schedule: 55 hours (2023-2024), 48 hours (2025-2026), 40 hours (2027+). Applies to employers of agricultural labor as defined in ORS 653.020. Small farms with fewer than 25 employees have a delayed phase-in schedule.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.261(6); HB 4002 (2022)', 'https://www.oregon.gov/boli/workers/pages/overtime.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-108', 'OR-EMP-108', 'Domestic Worker Protections', 'Oregon''s Domestic Workers Protection Act (HB 2015, 2015) extends wage, hour, and anti-discrimination protections to domestic workers including housekeepers, nannies, and home care workers. Domestic workers are entitled to minimum wage, overtime after 40 hours, meal and rest breaks, and protection from harassment and discrimination under ORS 653.020 as amended. Live-in domestic workers have specific overtime rules under OAR 839-020-0004(29).', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.020; HB 2015 (2015)', 'https://www.oregon.gov/boli/workers/pages/domestic-workers.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-109', 'OR-EMP-109', 'Tip Pooling and Tip Credits', 'Oregon prohibits tip credits — employers must pay full minimum wage before tips per ORS 653.035(1). Mandatory tip pools are permitted only among employees who customarily and regularly receive tips. Employers and supervisors may not participate in tip pools. Tips are the property of the employee. Violation subjects employer to civil penalties of up to $1,000 per offense under ORS 653.256.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.035(1); ORS § 653.256', 'https://www.oregon.gov/boli/workers/pages/minimum-wage.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-110', 'OR-EMP-110', 'Final Paycheck — Involuntary Termination', 'When an employee is discharged, all wages earned and unpaid become due and payable no later than the end of the first business day after the discharge per ORS 652.140(1). Failure to pay timely subjects employer to penalty wages equal to 8 hours of pay per day for each day wages remain unpaid, up to 30 days, under ORS 652.150(1). Aggregate employer with 3+ violations in one year faces penalties of up to $200 per employee per BOLI enforcement.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.140(1); ORS § 652.150(1)', 'https://www.oregon.gov/boli/workers/pages/final-paycheck.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-111', 'OR-EMP-111', 'Final Paycheck — Voluntary Resignation', 'When an employee quits with at least 48 hours notice (excluding weekends and holidays), final wages are due on the last day of employment per ORS 652.140(2). If the employee quits without 48 hours notice, wages are due within 5 business days or the next regular payday, whichever comes first, per ORS 652.140(3). Same penalty wage provisions under ORS 652.150 apply for late payment.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.140(2)(3)', 'https://www.oregon.gov/boli/workers/pages/final-paycheck.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-112', 'OR-EMP-112', 'Wage Payment Requirements', 'Employers must establish and maintain a regular payday at least once every 35 days per ORS 652.120. Wages must be paid in lawful money of the United States, by check, or by direct deposit with employee authorization per ORS 652.110. Employers must provide itemized pay statements showing hours worked, rate of pay, gross wages, deductions, and net wages per ORS 652.610(3).', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.110; ORS § 652.120; ORS § 652.610(3)', 'https://www.oregon.gov/boli/employers/pages/paying-wages.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-113', 'OR-EMP-113', 'Payroll Deduction Limitations', 'Employers may not withhold, deduct, or divert any portion of an employee''s wages unless required by law, authorized in writing by the employee for the employee''s benefit, or authorized by collective bargaining agreement per ORS 652.610(1). Deductions for cash shortages, breakage, or loss of equipment are prohibited unless the employee authorizes in writing and the deduction does not reduce pay below minimum wage. Unauthorized deductions are subject to penalty wages under ORS 652.150.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.610(1)(2)', 'https://www.oregon.gov/boli/employers/pages/paying-wages.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-114', 'OR-EMP-114', 'Predictive Scheduling (Fair Work Week)', 'Employers in retail, hospitality, and food service with 500+ employees worldwide must provide work schedules at least 14 days in advance per ORS 653.412. Schedule changes with less than 14 days notice require premium pay: 1 hour at regular rate for additions or time changes, half of scheduled hours for subtracted hours. Employees have the right to rest between shifts (10 hours) and to decline schedule additions. Penalties under ORS 653.450 include $1,000 per violation.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.412-653.470', 'https://www.oregon.gov/boli/workers/pages/predictive-scheduling.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-115', 'OR-EMP-115', 'Child Labor Restrictions', 'Minors under 18 may not work in hazardous occupations per ORS 653.305. Minors 14-15 may work limited hours: 3 hours/school day, 8 hours/non-school day, 18 hours/school week, 40 hours/non-school week per OAR 839-021-0104. Minors must have an employment certificate issued by the school district per ORS 653.315. Employers must keep certificates on file. Violations carry penalties of up to $1,000 per violation under ORS 653.340.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.305-653.340; OAR 839-021-0104', 'https://www.oregon.gov/boli/employers/pages/child-labor.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-116', 'OR-EMP-116', 'Prevailing Wage on Public Works', 'Contractors on public works projects exceeding $50,000 must pay prevailing wage rates as determined by BOLI per ORS 279C.800. Subcontractors at all tiers must comply. Employers must file certified payroll statements with the public agency per ORS 279C.845. Violations can result in debarment from public contracts for up to 3 years per ORS 279C.860 and civil penalties of up to $5,000 per violation.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 279C.800-279C.870', 'https://www.oregon.gov/boli/employers/pages/prevailing-wage-rates.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-117', 'OR-EMP-117', 'Wage Claim Filing and Enforcement', 'Employees may file wage claims with BOLI for unpaid wages, overtime, or penalty wages per ORS 652.330. Claims must be filed within one year for penalty wages or within the statute of limitations for unpaid wages (6 years for written contracts, 2 years for oral). BOLI may investigate, issue compliance orders, and assess civil penalties up to $1,000 per violation under ORS 652.332. Employers who retaliate against employees for filing wage claims face additional penalties under ORS 652.355.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.330-652.355', 'https://www.oregon.gov/boli/workers/pages/wage-claim.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-118', 'OR-EMP-118', 'Employer Record-Keeping Requirements', 'Employers must maintain payroll records for each employee for at least 6 years per ORS 652.750, including: name, address, SSN, occupation, rate of pay, hours worked each day and week, total wages paid each pay period, and all deductions. Records must be available for BOLI inspection upon request. Failure to maintain records creates a rebuttable presumption in favor of the employee''s claimed hours and wages.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.750; OAR 839-020-0080', 'https://www.oregon.gov/boli/employers/pages/paying-wages.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-119', 'OR-EMP-119', 'Wage Theft Prevention Posting', 'Employers must post in a conspicuous location a notice summarizing Oregon wage and hour laws including minimum wage rates, overtime, meal and rest break rights, and how to file a complaint per ORS 653.077. BOLI provides the required poster. Employers with non-English-speaking employees must post in the employees'' primary language if BOLI provides a translated version. Failure to post carries a penalty of up to $500 per violation.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.077; OAR 839-020-0005', 'https://www.oregon.gov/boli/employers/pages/required-postings.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-120', 'OR-EMP-120', 'Independent Contractor Classification', 'Oregon uses a multi-factor economic reality test under ORS 670.600 to determine worker classification. Employers must satisfy all factors to classify a worker as an independent contractor, including: the worker is free from direction and control, the worker is customarily engaged in an independent business, and the worker is responsible for obtaining required licenses. Misclassification subjects the employer to back wages, overtime, penalties, and BOLI enforcement. ORS 670.600 factors are more restrictive than the federal test.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 670.600', 'https://www.oregon.gov/boli/employers/pages/independent-contractors.aspx', 1);

-- ============================================================
-- LEAVE & BENEFITS (15 rules: or-emp-121 through or-emp-135)
-- ============================================================

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-121', 'OR-EMP-121', 'Oregon Family Leave Act (OFLA) — Eligibility and Duration', 'OFLA applies to employers with 25+ employees. Eligible employees who have worked 180+ days and averaged 25+ hours/week may take up to 12 weeks of unpaid, job-protected leave per year for serious health condition, parental leave, sick child leave, or pregnancy disability per ORS 659A.150-659A.186. Employer must maintain benefits during leave. Employees may use accrued paid leave concurrently. BOLI may award back pay, reinstatement, and compensatory damages up to $200,000 for violations.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.150-659A.186', 'https://www.oregon.gov/boli/workers/pages/oregon-family-leave.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-122', 'OR-EMP-122', 'OFLA — Pregnancy Disability Leave', 'In addition to the 12-week OFLA entitlement, employees disabled by pregnancy, childbirth, or a related condition are entitled to an additional 12 weeks of pregnancy disability leave (total possible 24 weeks) per ORS 659A.162. Applies to employers with 25+ employees. Employee need not have worked 180 days; only the 25-hour average applies for pregnancy disability leave. Employer must hold the position or an equivalent position.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.162', 'https://www.oregon.gov/boli/workers/pages/oregon-family-leave.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-123', 'OR-EMP-123', 'Paid Leave Oregon — Employer Contributions', 'Paid Leave Oregon requires a 1% payroll contribution split 60/40 between employee (0.6%) and employer (0.4%) per ORS 657B.150. Employers with fewer than 25 employees are exempt from the employer portion but must still collect and remit the employee share. Contributions are made to the Oregon Employment Department. Employers must begin withholding from day one of employment. Failure to remit triggers penalties of 10% plus interest under ORS 657B.320.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 657B.150; ORS § 657B.320', 'https://paidleave.oregon.gov/employers/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-124', 'OR-EMP-124', 'Paid Leave Oregon — Employee Benefits', 'Eligible employees who have earned $1,000+ in wages during the base year may receive up to 12 weeks of paid family, medical, or safe leave per benefit year, plus 2 additional weeks for pregnancy-related conditions (14 weeks total) per ORS 657B.020. Benefit amount is 100% of wages up to 65% of state average weekly wage, then 50% above that, capped at 120% of state average weekly wage. Employees may take leave for own serious health condition, family member care, bonding with new child, or safety leave (domestic violence, sexual assault, stalking, harassment).', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 657B.020; ORS § 657B.040', 'https://paidleave.oregon.gov/employees/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-125', 'OR-EMP-125', 'Oregon Sick Time — Paid (10+ Employees)', 'Employers with 10+ employees in Oregon (6+ in Portland) must provide paid sick time per ORS 653.601-653.661. Employees accrue 1 hour per 30 hours worked, usable after 90 days, up to 40 hours per year. May be used for employee or family member illness, injury, health condition, preventive care, domestic violence/harassment/sexual assault/stalking purposes, public health emergency closures. Employer may not require documentation for absences of 3 or fewer consecutive days.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.601-653.661', 'https://www.oregon.gov/boli/workers/pages/sick-time.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-126', 'OR-EMP-126', 'Oregon Sick Time — Unpaid (Under 10 Employees)', 'Employers with fewer than 10 employees (fewer than 6 in Portland) must provide unpaid sick time per ORS 653.601-653.661. Same accrual rate (1 hour per 30 hours worked), same 40-hour annual cap, same qualifying uses as paid sick time. Employer must allow employees to use accrued unpaid sick time beginning on the 91st day of employment. Retaliation for using sick time is prohibited and carries civil penalties.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.601-653.661', 'https://www.oregon.gov/boli/workers/pages/sick-time.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-127', 'OR-EMP-127', 'OFLA Bereavement Leave', 'OFLA provides up to 2 weeks of bereavement leave per death of a family member, which counts against the 12-week annual OFLA entitlement per ORS 659A.159. Leave must be completed within 60 days of notice of death. Family members include spouse, domestic partner, parent, child, grandparent, grandchild, parent-in-law, and same-sex domestic partner''s relatives. No limit on number of bereavement events per year. Employer may require documentation.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.159', 'https://www.oregon.gov/boli/workers/pages/oregon-family-leave.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-128', 'OR-EMP-128', 'Domestic Violence Leave', 'Employees who are victims of domestic violence, harassment, sexual assault, or stalking — or whose minor children are victims — are entitled to reasonable leave for safety planning, legal proceedings, medical treatment, counseling, relocation, or seeking services from a victim services provider per ORS 659A.272. Applies to all employers with 6+ employees. Employer must keep information confidential. Retaliation is a separate violation under ORS 659A.030.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.272; ORS § 659A.280', 'https://www.oregon.gov/boli/workers/pages/domestic-violence-protections.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-129', 'OR-EMP-129', 'Jury Duty Leave Protections', 'Employers may not discharge, threaten, or coerce employees for serving on a jury per ORS 10.090. Employers are not required to pay wages during jury service unless there is a company policy or contract. Employer may not require employee to use vacation or sick time for jury duty. Employee must give reasonable notice. Violation is a Class B misdemeanor and the employer may be held in contempt of court. Employee may also bring a civil action for damages.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 10.090', 'https://www.oregonlegislature.gov/bills_laws/ors/ors010.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-130', 'OR-EMP-130', 'Military Leave — Oregon Military Family Leave Act', 'Employers with 25+ employees must provide up to 14 days of unpaid leave per deployment to the spouse or domestic partner of a member of the Armed Forces, National Guard, or Reserves who has been called to active duty or is on leave from active duty per ORS 659A.093. Employee must work an average of 20+ hours/week. Employer must maintain benefits. Job reinstatement is required. OFLA provisions also apply to military family leave.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.093', 'https://www.oregon.gov/boli/workers/pages/military-leave.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-131', 'OR-EMP-131', 'Veteran Preference and Reemployment', 'Oregon provides employment preferences for veterans in public employment per ORS 408.225-408.240. Employers must grant military leave of absence and guarantee reemployment for uniformed service members per ORS 659A.082. Oregon law supplements federal USERRA. Reemployment must be in the same position or a position of equivalent seniority, status, and pay. Employer may not discriminate based on military service per ORS 659A.082.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.082; ORS § 408.225-408.240', 'https://www.oregon.gov/boli/workers/pages/military-leave.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-132', 'OR-EMP-132', 'Bone Marrow and Organ Donation Leave', 'Employers must grant up to 40 hours of paid leave per year for bone marrow donation and up to 40 hours for organ donation per ORS 659A.312. This leave is in addition to any other leave entitlement. Employee must provide medical verification. Applies to all employers. Employer may not retaliate or discriminate against employee for requesting or using donation leave. Leave must be paid at the employee''s regular rate.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.312', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-133', 'OR-EMP-133', 'Voting Leave', 'Oregon conducts elections by mail, so there is no specific polling-place leave statute. However, ORS 260.665 prohibits employers from influencing, threatening, or coercing employees regarding voting. Employers may not require employees to disclose how they voted. Employers may not adopt policies that would interfere with an employee''s right to vote. Violation is a Class C felony under ORS 260.665.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 260.665', 'https://www.oregonlegislature.gov/bills_laws/ors/ors260.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-134', 'OR-EMP-134', 'Paid Leave Oregon — Employer Equivalent Plans', 'Employers may apply to the Oregon Employment Department for approval of an equivalent plan in lieu of participating in the state program per ORS 657B.210. The equivalent plan must provide benefits at least equal to the state plan in amount, duration, and eligibility. Employees may not be required to pay more than they would under the state plan. Plans must be approved before the employer may opt out. BOLI may revoke approval if the plan fails to meet standards.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 657B.210', 'https://paidleave.oregon.gov/employers/equivalent-plans/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-135', 'OR-EMP-135', 'Crime Victim Leave', 'Employees who are crime victims, or whose immediate family members are crime victims, are entitled to leave to attend criminal proceedings per ORS 659A.192. Applies to all employers. Employer may not discharge, threaten, or discriminate against employee for taking leave. Employee must give reasonable advance notice. Leave is unpaid unless employer policy provides otherwise. Employer must allow use of accrued paid leave.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.192', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

-- ============================================================
-- DISCRIMINATION & HARASSMENT (15 rules: or-emp-136 through or-emp-150)
-- ============================================================

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-136', 'OR-EMP-136', 'Oregon Workplace Fairness Act — Protected Classes', 'ORS 659A.030 prohibits employment discrimination based on race, color, religion, sex, sexual orientation, gender identity, national origin, marital status, age (18+), disability, familial status, and expunged juvenile record. Applies to employers with 1+ employees. Broader than federal law: includes sexual orientation, gender identity, and marital status. BOLI may award compensatory damages up to $200,000, plus back pay, front pay, and attorney fees.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.030', 'https://www.oregon.gov/boli/workers/pages/discrimination-at-work.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-137', 'OR-EMP-137', 'Sexual Harassment Protections', 'Oregon prohibits sexual harassment in employment under ORS 659A.030(1)(b), including unwelcome sexual advances, requests for sexual favors, and verbal/physical conduct of a sexual nature that affects employment, unreasonably interferes with work, or creates a hostile environment. Employers are strictly liable for harassment by supervisors. For co-worker harassment, employer is liable if it knew or should have known and failed to take prompt corrective action.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.030(1)(b); ORS § 659A.082', 'https://www.oregon.gov/boli/workers/pages/discrimination-at-work.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-138', 'OR-EMP-138', 'Nondisclosure Agreement Limits on Harassment Claims', 'Oregon Workplace Fairness Act (SB 726, 2019) restricts nondisclosure and nondisparagement provisions in settlement agreements involving discrimination, harassment, or sexual assault claims per ORS 659A.370. Agreements may not prevent the employee from disclosing the underlying conduct. Employee must be given 7 days to revoke. Employer cannot require as condition of employment. Provisions in violation are void and unenforceable. Statute of limitations extended to 5 years for harassment/discrimination claims under ORS 659A.875.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.370; ORS § 659A.875; SB 726 (2019)', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-139', 'OR-EMP-139', 'Equal Pay Act', 'Oregon Equal Pay Act (ORS 652.220) prohibits pay differences based on protected class for work of comparable character requiring substantially similar knowledge, skill, effort, responsibility, and working conditions. Employers may justify differences only by seniority, merit, quantity/quality of production, workplace location, travel, education, training, or experience — but these factors may not be based on protected class. Salary history may not be used to justify pay differentials. Violations subject employer to back pay, compensatory damages, and attorney fees.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.220', 'https://www.oregon.gov/boli/workers/pages/equal-pay.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-140', 'OR-EMP-140', 'Disability Discrimination and Reasonable Accommodation', 'Employers must provide reasonable accommodation for employees with disabilities unless doing so would impose an undue hardship per ORS 659A.112. Oregon''s disability definition is broader than federal ADA: any physical or mental impairment that substantially limits one or more major life activities. Employers must engage in an interactive process. Failure to accommodate or engage in the interactive process is an independent violation. BOLI may award damages up to $200,000 plus equitable relief.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.112; ORS § 659A.118', 'https://www.oregon.gov/boli/workers/pages/disability.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-141', 'OR-EMP-141', 'Religious Accommodation', 'Employers must reasonably accommodate employees'' sincerely held religious beliefs, practices, and observances unless doing so would impose an undue hardship per ORS 659A.033. Accommodation includes schedule modifications, job reassignment, dress code exceptions, and shift swaps. Oregon law defines undue hardship more narrowly than federal law, requiring more than de minimis cost. Employer must engage in an interactive process.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.033', 'https://www.oregon.gov/boli/workers/pages/discrimination-at-work.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-142', 'OR-EMP-142', 'Pregnancy Accommodation', 'Employers with 6+ employees must provide reasonable accommodations for pregnancy, childbirth, and related medical conditions including lactation per ORS 659A.148. Accommodations include more frequent breaks, modified schedules, temporary transfer, seating, lifting limits, and private lactation space. Employer need not create a new position but must modify existing duties. No employee may be required to accept an accommodation they did not request.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.148', 'https://www.oregon.gov/boli/workers/pages/pregnancy-accommodation.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-143', 'OR-EMP-143', 'Age Discrimination', 'Oregon prohibits employment discrimination based on age for individuals 18 and older per ORS 659A.030. This is broader than federal ADEA, which only protects individuals 40+. Employers may not use age as a factor in hiring, promotion, compensation, terms, conditions, or privileges of employment. Mandatory retirement is prohibited except for certain public safety positions (firefighters, law enforcement) per ORS 659A.030(3).', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.030', 'https://www.oregon.gov/boli/workers/pages/discrimination-at-work.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-144', 'OR-EMP-144', 'Whistleblower Protections', 'Oregon prohibits retaliation against employees who in good faith report violations of law, testify in proceedings, or refuse to participate in illegal activity per ORS 659A.199-659A.233. Applies to public and private employers. Employee may report to any public body including federal, state, or local agencies. Whistleblower may recover back pay, reinstatement, compensatory damages, punitive damages, and attorney fees. Statute of limitations is 2 years from the retaliatory action.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.199-659A.233', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-145', 'OR-EMP-145', 'Harassment-Free Workplace Policy Requirement', 'Employers must adopt and distribute a written anti-harassment policy per ORS 659A.375. The policy must include a complaint process, identify individuals to whom complaints can be made, and state that retaliation is prohibited. The policy must be provided to new employees at hire and annually thereafter. Employers with 1+ employees must comply. Policy must cover all protected classes under ORS 659A.030.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.375', 'https://www.oregon.gov/boli/employers/pages/harassment-and-discrimination.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-146', 'OR-EMP-146', 'Discrimination Complaint Process and Remedies', 'Employees may file discrimination complaints with BOLI within 5 years for harassment/discrimination claims per ORS 659A.875 (extended from 1 year by SB 726). BOLI investigates and may issue a finding of substantial evidence. If conciliation fails, BOLI may file a formal charge and conduct a hearing. Remedies include back pay, front pay, compensatory damages up to $200,000, reinstatement, and attorney fees per ORS 659A.885. Employees may alternatively file in circuit court.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.820-659A.885', 'https://www.oregon.gov/boli/workers/pages/complaint.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-147', 'OR-EMP-147', 'Genetic Information Discrimination', 'Employers may not discriminate based on genetic information per ORS 659A.303. Employers may not request, require, or purchase genetic information about an employee or applicant. Genetic testing may not be used as a condition of employment. Genetic information includes family medical history, genetic tests, and genetic counseling. Applies to hiring, termination, compensation, and terms of employment. Violation carries same remedies as other discrimination claims under ORS 659A.885.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.303', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-148', 'OR-EMP-148', 'Credit History Discrimination in Employment', 'Employers may not obtain or use an applicant''s or employee''s credit history for employment purposes per ORS 659A.320 unless the information is substantially job-related and the employer discloses the reason in writing. Exceptions: federally insured banks/credit unions, public safety positions, and positions with fiduciary duties or access to $10,000+ in cash per transaction. Violation is an unlawful employment practice subject to BOLI enforcement and damages.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.320', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-149', 'OR-EMP-149', 'Lactation Accommodation', 'Employers must provide reasonable unpaid rest periods to accommodate an employee who needs to express breast milk for a child 18 months or younger per ORS 653.077(6). Employer must make reasonable efforts to provide a private location (not a bathroom) close to the work area for expressing milk. If providing rest periods would impose undue hardship, employer is exempt. Lactation breaks beyond normal rest periods are unpaid unless employer policy provides otherwise.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.077(6)', 'https://www.oregon.gov/boli/workers/pages/pregnancy-accommodation.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-150', 'OR-EMP-150', 'Hairstyle Discrimination (CROWN Act)', 'Oregon''s CROWN Act (HB 2935, 2021) prohibits discrimination based on natural hairstyles and protective styles associated with race, including braids, locs, twists, tight coils, Bantu knots, afros, cornrows, and head wraps per ORS 659A.030 as amended. Applies to employment, education, housing, and public accommodations. Employers may not impose grooming policies that disproportionately impact employees based on race-associated hair texture or style.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.030; HB 2935 (2021)', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

-- ============================================================
-- HIRING & TERMINATION (15 rules: or-emp-151 through or-emp-165)
-- ============================================================

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-151', 'OR-EMP-151', 'Ban the Box — Criminal History Inquiry Restrictions', 'Employers may not inquire about criminal history on an initial employment application per ORS 659A.360. This applies to all employers. Employers may inquire about criminal history after an initial interview or conditional offer. Exceptions: law enforcement, criminal justice agencies, and positions where federal or state law requires criminal background checks. Employers who violate may face BOLI enforcement, civil penalties up to $1,000 per violation, and compensatory damages.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.360', 'https://www.oregon.gov/boli/employers/pages/ban-the-box.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-152', 'OR-EMP-152', 'Salary History Ban', 'Employers may not screen applicants based on current or past compensation, seek salary history from applicants or current/former employers, or determine compensation based on salary history per ORS 652.220(2). Employers may discuss the applicant''s compensation expectations. If an applicant voluntarily discloses salary history, the employer may consider it but may not rely on it solely to justify a pay disparity. Violations subject employer to Equal Pay Act remedies including back pay and damages.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.220(2)', 'https://www.oregon.gov/boli/workers/pages/equal-pay.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-153', 'OR-EMP-153', 'Pay Transparency — Pay Range Disclosure', 'Employers must include a pay range in job postings per SB 1515 (2023), effective September 2023. The pay range must include the minimum and maximum salary or hourly rate. Applies to all employers with 1+ employees. Internal transfer and promotion postings are included. Employers who do not comply face BOLI enforcement and civil penalties up to $10,000 per violation. Employers must also provide pay range to current employees upon request for their position.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.235; SB 1515 (2023)', 'https://www.oregon.gov/boli/employers/pages/equal-pay.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-154', 'OR-EMP-154', 'At-Will Employment with Exceptions', 'Oregon is an at-will employment state per common law, meaning either party may terminate the relationship at any time for any reason not prohibited by law. Exceptions include: (1) express or implied contract, (2) violation of public policy (ORS 659A.199), (3) implied covenant of good faith and fair dealing (limited), (4) discrimination or retaliation under ORS 659A, (5) union/CBA protections. Employees terminated for exercising legal rights may bring wrongful discharge claims.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Common Law; ORS § 659A.199', 'https://www.oregon.gov/boli/employers/pages/termination.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-155', 'OR-EMP-155', 'Oregon WARN Act — Plant Closings and Mass Layoffs', 'Oregon requires 60 days written notice before a plant closing or mass layoff affecting 25+ employees at a single site per ORS 285A.516. Applies to employers with 100+ employees. Notice must be provided to affected employees, BOLI, and the local workforce development board. Employer that fails to provide required notice is liable for back pay and benefits for each day of violation, up to 60 days. Oregon threshold of 25 employees is lower than federal WARN Act threshold of 50.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 285A.516', 'https://www.oregonlegislature.gov/bills_laws/ors/ors285a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-156', 'OR-EMP-156', 'Noncompete Agreement Restrictions', 'Oregon restricts noncompete agreements under ORS 653.295. A noncompete is void unless: (1) the employee is informed of the terms in a written employment offer at least 2 weeks before the first day of work or on a bona fide advancement; (2) the employee earns at least $113,241 annually (2024 threshold, adjusted annually); (3) the employer has a protectable interest; (4) the restriction does not exceed 12 months. Noncompetes exceeding 12 months are void. Garden leave clauses may substitute.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 653.295', 'https://www.oregonlegislature.gov/bills_laws/ors/ors653.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-157', 'OR-EMP-157', 'Non-Solicitation and Restrictive Covenant Requirements', 'Non-solicitation agreements (of clients or employees) are subject to reasonableness analysis under Oregon common law. Unlike noncompetes, non-solicitation agreements are not governed by ORS 653.295 but must still be supported by consideration, be reasonable in scope and duration, and protect a legitimate business interest. Overly broad non-solicitation agreements may be reformed or voided by courts. Employers should limit duration to 12-18 months and geographic/customer scope to actual contacts.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Common Law; ORS § 653.295 (by analogy)', 'https://www.oregonlegislature.gov/bills_laws/ors/ors653.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-158', 'OR-EMP-158', 'Employment Reference Immunity', 'Oregon provides qualified immunity to employers who disclose information about a current or former employee''s job performance to a prospective employer per ORS 30.178. The immunity applies if the information is provided in good faith. Immunity does not apply if the employer knowingly provides false information, acts with malice, or discloses information in violation of a nondisclosure agreement. Employer is presumed to act in good faith unless rebutted by clear and convincing evidence.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 30.178', 'https://www.oregonlegislature.gov/bills_laws/ors/ors030.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-159', 'OR-EMP-159', 'Personnel File Access', 'Employees and former employees have the right to inspect their personnel records within 45 days of written request per ORS 652.750. Employer must provide access during regular business hours. Former employees retain access rights for 60 days after termination. Employee may obtain copies at reasonable cost. Medical records must be maintained separately and disclosed only as required by law. Employer must maintain records for at least 60 days after termination.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.750', 'https://www.oregonlegislature.gov/bills_laws/ors/ors652.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-160', 'OR-EMP-160', 'Employment Verification and I-9 Compliance', 'Oregon employers must comply with federal I-9 requirements but may not use E-Verify unless required by federal law or contract per ORS 658.452. Employers may not discriminate based on national origin or citizenship status in the I-9 process. Requiring more or different documents than the I-9 form allows is document abuse. Oregon prohibits profiling employees for verification based on appearance, accent, or national origin. Violations are enforced by BOLI as discrimination.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 658.452; ORS § 659A.030', 'https://www.oregonlegislature.gov/bills_laws/ors/ors658.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-161', 'OR-EMP-161', 'Social Media Privacy in Employment', 'Employers may not require employees or applicants to disclose social media usernames, passwords, or other access credentials per ORS 659A.330. Employers may not require employees to add the employer or agent to their social media contacts. Employers may not take adverse action against employees for refusing to disclose social media information. Exceptions: employer may investigate workplace misconduct through publicly available information or when required by law.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.330', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-162', 'OR-EMP-162', 'Drug Testing Restrictions', 'Oregon does not have a comprehensive drug testing statute for private employers but limits testing through case law and ORS 659A.300 (medical marijuana). Employer may test pre-employment, post-accident, for reasonable suspicion, and randomly for safety-sensitive positions. Employer may not discriminate against medical marijuana cardholders per ORS 475C.205 unless federally regulated. Positive test alone is insufficient for discharge in non-safety-sensitive positions without corroboration.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.300; ORS § 475C.205', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659a.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-163', 'OR-EMP-163', 'Separation Notice Requirements', 'When an employee is discharged, the employer must provide a written statement of the reason for termination within 15 days of a written request per ORS 652.750(3). The employer must also provide a letter of service stating dates of employment and job classification upon request. Failure to provide a timely separation notice may support an inference of wrongful termination. Some employers must file a separation notice with the Oregon Employment Department for unemployment insurance purposes.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.750(3)', 'https://www.oregonlegislature.gov/bills_laws/ors/ors652.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-164', 'OR-EMP-164', 'Employer Blacklisting Prohibition', 'Oregon prohibits employer blacklisting — conspiring to prevent a former employee from obtaining employment — per ORS 659.010. Employers may not by written, verbal, or electronic communication attempt to prevent a discharged employee from obtaining employment. Violation is a Class C misdemeanor per ORS 659.030 and the affected employee may bring a civil action for damages. This does not prohibit truthful employment references protected under ORS 30.178.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659.010; ORS § 659.030', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659.html', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-165', 'OR-EMP-165', 'Employee Polygraph Protection', 'Oregon prohibits employers from requiring or requesting that employees or applicants take a lie detector, polygraph, or similar test as a condition of employment or continued employment per ORS 659.225. Exceptions align with federal EPPA: employers may use polygraphs for security-related investigations involving economic loss, but only with proper notice and consent. Violation is an unlawful employment practice subject to BOLI enforcement and civil damages.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659.225', 'https://www.oregonlegislature.gov/bills_laws/ors/ors659.html', 1);

-- ============================================================
-- WORKPLACE SAFETY (15 rules: or-emp-166 through or-emp-180)
-- ============================================================

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-166', 'OR-EMP-166', 'Oregon OSHA — State Plan State Authority', 'Oregon operates its own occupational safety and health program (Oregon OSHA) under ORS 654, approved by federal OSHA as a state-plan state. Oregon OSHA adopts federal OSHA standards and may adopt more stringent standards. Covers all public and private employers. Oregon OSHA conducts inspections, issues citations, and assesses penalties. Maximum penalties: serious violation $15,625, willful violation $156,259, repeat violation $156,259 per OAR 437-001-0145.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654; OAR 437-001-0145', 'https://osha.oregon.gov/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-167', 'OR-EMP-167', 'Heat Illness Prevention — Permanent Rule', 'Oregon OSHA permanent heat illness prevention rule (OAR 437-002-0156) requires employers to provide access to shade and water when temperatures exceed 80°F. At 90°F, employers must implement a heat illness prevention plan including acclimatization for new workers (first 14 days), emergency response procedures, training, and observation of employees showing heat illness symptoms. Applies to all outdoor work and indoor work without effective climate control. High heat procedures at 90°F include 10-minute paid cool-down rest periods every 2 hours.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-002-0156', 'https://osha.oregon.gov/Pages/topics/heat-stress.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-168', 'OR-EMP-168', 'Wildfire Smoke Protections', 'Oregon OSHA permanent wildfire smoke rule (OAR 437-002-1081) requires employers to take protective measures when the Air Quality Index (AQI) for PM2.5 reaches 101 or above. At AQI 101-200: employers must communicate hazards, encourage exposure reduction, and provide NIOSH-approved respirators upon request. At AQI 201-250: mandatory exposure controls or respirator use. At AQI 251+: all outdoor work must use engineering controls, administrative controls, or respirators to reduce exposure. Applies to outdoor workers and indoor workers in unfiltered environments.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-002-1081', 'https://osha.oregon.gov/Pages/topics/wildfire-smoke.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-169', 'OR-EMP-169', 'Workplace Violence Prevention', 'Oregon OSHA general duty clause (ORS 654.010) requires employers to maintain a workplace free from recognized hazards including workplace violence. Healthcare employers must implement workplace violence prevention programs per OAR 437-002-0390 including risk assessments, written plans, employee training, incident reporting, and post-incident response. All employers must report workplace violence incidents causing hospitalization. BOLI enforces protections against domestic violence in the workplace per ORS 659A.272.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.010; OAR 437-002-0390', 'https://osha.oregon.gov/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-170', 'OR-EMP-170', 'Infectious Disease Prevention — Permanent Rule', 'Oregon OSHA adopted a permanent rule for airborne infectious diseases (OAR 437-001-0744) applicable to healthcare, emergency response, and worker transportation settings. Employers must develop an infection control plan, provide respiratory protection, conduct employee training, perform exposure risk assessments, and maintain records. When public health emergency declared, enhanced requirements apply to all workplaces including physical distancing, sanitation, ventilation improvements, and employee notification of exposures.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-001-0744', 'https://osha.oregon.gov/Pages/topics/infectious-disease.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-171', 'OR-EMP-171', 'Agricultural Safety Standards', 'Oregon OSHA agricultural safety standards (OAR 437-004) cover field sanitation, pesticide handling, farm machinery, rollover protection (ROPS), hand labor tools, and transportation of agricultural workers. Employers must provide toilet and handwashing facilities within quarter-mile of field work. Pesticide handlers must receive annual training per Worker Protection Standard. Agricultural worker housing must meet OAR 437-004-1120 standards. Violations carry same penalties as general industry violations.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-004; ORS § 654', 'https://osha.oregon.gov/Pages/topics/agriculture.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-172', 'OR-EMP-172', 'Logging Safety Standards', 'Oregon OSHA logging safety standards (OAR 437-007) are among the most comprehensive in the nation. Requirements include: felling and bucking procedures, yarding and loading, road construction, rigging requirements, log truck operations, helicopter logging, and training/certification. All logging employees must receive initial and annual refresher training per OAR 437-007-0100. Employers must develop and implement a written accident prevention program. Oregon''s logging fatality rate drives enhanced enforcement and inspection targeting.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-007; ORS § 654', 'https://osha.oregon.gov/Pages/topics/forest-activities.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-173', 'OR-EMP-173', 'Ergonomics — Voluntary Guidelines', 'Oregon OSHA provides voluntary ergonomics guidelines under the general duty clause (ORS 654.010). While Oregon does not have a mandatory ergonomics standard, employers with known ergonomic hazards (repetitive motion, heavy lifting, awkward postures) must address them under the general duty clause. Oregon OSHA offers free ergonomic consultations. Industries with high ergonomic injury rates (manufacturing, agriculture, healthcare) may be targeted for inspection. Employers should implement job hazard analyses, workstation assessments, and rotation schedules.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.010; Oregon OSHA Guidelines', 'https://osha.oregon.gov/Pages/topics/ergonomics.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-174', 'OR-EMP-174', 'Right to Refuse Unsafe Work', 'Oregon employees may refuse work they reasonably believe poses imminent danger of death or serious physical harm per ORS 654.062. The employee must first request the employer correct the hazard. If the employer refuses and the danger is imminent, the employee may refuse work without retaliation. Oregon OSHA protects employees who file safety complaints per ORS 654.062(5). Employer may not discharge, demote, or discriminate against employees exercising safety rights. Whistleblower complaint must be filed within 30 days.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.062', 'https://osha.oregon.gov/workers/Pages/safety-rights.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-175', 'OR-EMP-175', 'Hazard Communication Standard', 'Oregon OSHA adopts the federal Hazard Communication Standard (HCS/GHS) under OAR 437-002-0360. Employers must maintain a written hazard communication program, provide Safety Data Sheets (SDS) for all hazardous chemicals, label containers per GHS standards, and train employees on chemical hazards at hire and when new hazards are introduced. Employees have the right to access SDS within a work shift. Agricultural employers have additional requirements under OAR 437-004 for pesticide labeling and training.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-002-0360', 'https://osha.oregon.gov/Pages/topics/hazard-communication.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-176', 'OR-EMP-176', 'Injury and Illness Reporting', 'Employers must report workplace fatalities to Oregon OSHA within 8 hours and hospitalizations, amputations, or loss of an eye within 24 hours per OAR 437-001-0704. Employers must maintain OSHA 300 logs and 300A summaries for establishments with 11+ employees. The 300A summary must be posted from February 1 through April 30 annually. Employers in designated high-hazard industries must electronically submit 300A data to federal OSHA. Failure to report carries penalties up to $15,625 per violation.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-001-0704; OAR 437-001-0700', 'https://osha.oregon.gov/Pages/topics/recordkeeping.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-177', 'OR-EMP-177', 'Safety Committee Requirements', 'Oregon employers with 11+ employees at any single establishment or employers that have a workers'' compensation experience rate at or above 3.0 must establish a safety committee per ORS 654.176. Committees must include employer and employee representatives, meet at least monthly, conduct workplace inspections, review accident and illness data, recommend hazard corrections, and maintain minutes for 3 years. Oregon OSHA may accept an alternative safety meeting format for employers with 10 or fewer employees.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.176; OAR 437-001-0765', 'https://osha.oregon.gov/Pages/topics/safety-committees.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-178', 'OR-EMP-178', 'Workers'' Compensation Insurance Requirement', 'All Oregon employers with 1+ employees must carry workers'' compensation insurance per ORS 656.017. Coverage may be obtained through a private insurer, the State Accident Insurance Fund (SAIF), or self-insurance if approved by the Director of the Department of Consumer and Business Services. Noncomplying employers are subject to penalties equal to twice the premium the employer would have paid, a minimum $1,000 penalty, and personal liability for all injured worker benefits. DCBS may issue stop-work orders per ORS 656.735.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 656.017; ORS § 656.735', 'https://www.oregon.gov/dcbs/workers-comp/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-179', 'OR-EMP-179', 'Fall Protection Standards', 'Oregon OSHA requires fall protection for employees working at heights of 6 feet or more in construction (OAR 437-003-0001, Division 3/M) and 4 feet in general industry (OAR 437-002-0134). Fall protection methods include guardrails, safety nets, personal fall arrest systems, and positioning devices. Employers must train employees on fall hazards and proper equipment use. Fall-related violations are among the most frequently cited Oregon OSHA standards. Serious violations carry penalties up to $15,625.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'OAR 437-003-0001 (Div 3/M); OAR 437-002-0134', 'https://osha.oregon.gov/Pages/topics/fall-protection.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-emp-180', 'OR-EMP-180', 'Oregon OSHA Consultation Program', 'Oregon OSHA provides free, confidential on-site safety consultations to employers per ORS 654.060. Consultation visits do not result in citations or penalties. Employers may request consultations for hazard identification, safety program review, and compliance assistance. Employers who request consultation and implement recommendations may receive a one-year exemption from programmed inspections. Small employers (250 or fewer employees) are prioritized. Oregon OSHA also provides free safety training courses.', 'EMPLOYMENT', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.060', 'https://osha.oregon.gov/consult/', 1);
