-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 8
-- ═══════════════════════════════════════════════════════════════════════════
-- ETHICARA: Complete California Rules of Professional Conduct expansion
-- plus psychotherapist-patient privilege and B&P § 6068.
-- Rules 1.4, 1.15, 3.3, 8.4 already seeded in batches 4/base.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- CALIFORNIA RULES OF PROFESSIONAL CONDUCT — Individual Rules
-- ═══════════════════════════════════════════════════════════════════════════

-- Rule 1.1 — Competence
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_020', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.1', 'RPC 1.1', 'Competence', 'A lawyer shall not intentionally, recklessly, with gross negligence, or repeatedly fail to perform legal services with competence.', '["Legal knowledge and skill reasonably necessary","Thoroughness and preparation reasonably necessary","Mental, emotional, and physical ability to perform","May associate with or refer to competent counsel","Duty to keep abreast of changes in law and practice"]', '[{"section":"1.1(a)","description":"Competence standard — no intentional, reckless, or grossly negligent failure"},{"section":"1.1(b)","description":"Duty of competence includes learning and skill, thoroughness, and preparation"},{"section":"Comment 5","description":"Emergency situations — limited assistance permissible"}]', '["bar_complaint","malpractice_claim","OCTC_investigation","engagement_letter"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.2 — Scope of Representation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_021', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.2', 'RPC 1.2', 'Scope of Representation and Authority', 'Lawyer shall abide by client decisions concerning objectives of representation and consult on means. Client decides whether to settle, plea, or testify.', '["Abide by client decisions on objectives","Consult with client on means of pursuing objectives","Client decides whether to accept settlement in civil case","Client decides whether to plead guilty or testify in criminal case","May limit scope of representation if reasonable and client gives informed consent"]', '[{"section":"1.2(a)","description":"Client authority over objectives; lawyer-client consultation on means"},{"section":"1.2(b)","description":"Limited scope representation with informed written consent"},{"section":"1.2(d)","description":"Lawyer shall not counsel or assist criminal or fraudulent conduct"}]', '["engagement_letter","limited_scope_agreement","settlement_offer","plea_agreement","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.3 — Diligence
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_022', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.3', 'RPC 1.3', 'Diligence', 'A lawyer shall not intentionally, repeatedly, recklessly, or with gross negligence fail to act with reasonable diligence in representing a client.', '["Act with reasonable diligence and promptness","No neglect of entrusted legal matter","Control workload to provide competent diligent service","Carry through to conclusion all matters undertaken","Avoid procrastination and unnecessary delay"]', '[{"section":"1.3(a)","description":"Duty of diligence — no intentional, reckless, or grossly negligent failure"},{"section":"Comment 2","description":"Duty to act with commitment and dedication to client interests"},{"section":"Comment 3","description":"Workload management obligation"}]', '["bar_complaint","malpractice_claim","OCTC_investigation","case_status_report"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.5 — Fees for Legal Services
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_023', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.5', 'RPC 1.5', 'Fees for Legal Services', 'A lawyer shall not make an agreement for, charge, or collect an unconscionable or illegal fee or unconscionable cost.', '["Fee must not be unconscionable","Factors: time, novelty, skill required, fee customary in locality, amount involved, results obtained","Written fee agreement required (B&P 6148)","Contingency fee must be in writing (B&P 6147)","No contingency fee in criminal or certain family law matters"]', '[{"section":"1.5(a)","description":"Unconscionable fee prohibited — factors for determination"},{"section":"1.5(b)","description":"Contingency fee requirements"},{"section":"1.5(c)","description":"No contingency in criminal or certain domestic relations cases"},{"section":"1.5(e)","description":"Fee division among lawyers — client consent required"}]', '["fee_agreement","retainer_agreement","contingency_fee_agreement","billing_statement","fee_dispute"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.6 — Confidentiality of Information
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_024', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.6', 'RPC 1.6', 'Confidential Information of a Client', 'A lawyer shall not reveal information protected by Business and Professions Code section 6068(e) unless the client gives informed consent or disclosure is permitted by specified exceptions.', '["Duty to maintain client confidences and secrets","No disclosure without informed consent except as permitted","Exceptions: prevent reasonably certain death or substantial bodily harm","Exception: prevent criminal act likely to result in substantial financial harm","Must make reasonable efforts to prevent inadvertent or unauthorized disclosure"]', '[{"section":"1.6(a)","description":"General duty of confidentiality — B&P 6068(e)"},{"section":"1.6(b)","description":"Permissive disclosure to prevent death or substantial bodily harm"},{"section":"1.6(c)","description":"Permissive disclosure to prevent criminal fraud causing substantial financial harm"},{"section":"1.6(d)","description":"Disclosure in fee dispute or malpractice defense"}]', '["client_file","privileged_communication","disclosure_request","bar_complaint","malpractice_defense"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.7 — Conflict of Interest: Current Clients
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_025', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.7', 'RPC 1.7', 'Conflict of Interest — Current Clients', 'A lawyer shall not represent a client if representation involves a conflict of interest unless each affected client gives informed written consent.', '["No representation directly adverse to another current client","No representation materially limited by duties to another client, former client, or third person","Informed written consent from each affected client required for waiver","Lawyer must reasonably believe competent and diligent representation possible despite conflict","Some conflicts are nonconsentable"]', '[{"section":"1.7(a)","description":"Direct adversity conflict"},{"section":"1.7(b)","description":"Material limitation conflict"},{"section":"1.7(d)","description":"Informed written consent required from each affected client"},{"section":"1.7(c)","description":"Nonconsentable conflicts — cannot reasonably believe representation unaffected"}]', '["conflict_check","informed_consent_waiver","engagement_letter","motion_to_disqualify","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.8 — Current Clients: Specific Rules
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_026', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.8', 'RPC 1.8', 'Current Clients — Specific Conflict Rules', 'Specific prohibited and restricted transactions between lawyer and current clients including business transactions, literary rights, gifts, financial assistance, and sexual relations.', '["Business transactions with client require fair terms, written disclosure, client opportunity for independent counsel, and informed written consent","No acquiring literary or media rights during representation","No soliciting substantial gifts from client","No financial assistance to client except litigation costs in contingency case","No sexual relations with client unless preexisting relationship"]', '[{"section":"1.8(a)","description":"Business transactions with client — informed written consent and independent counsel"},{"section":"1.8(b)","description":"No literary or media rights during representation"},{"section":"1.8(c)","description":"No soliciting gifts or testamentary provisions"},{"section":"1.8(e)","description":"Financial assistance to client — limited to litigation costs"},{"section":"1.8(j)","description":"No sexual relations with client unless preexisting"}]', '["business_transaction_disclosure","gift_instrument","fee_agreement","bar_complaint","OCTC_investigation"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.9 — Duties to Former Clients
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_027', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.9', 'RPC 1.9', 'Duties to Former Clients', 'A lawyer who has formerly represented a client in a matter shall not thereafter represent another person in the same or substantially related matter adverse to the former client without informed written consent.', '["No representation adverse to former client in same or substantially related matter","Substantially related: substantial risk confidential information would materially advance new client position","Informed written consent from former client required for waiver","Must not use or reveal former client confidential information"]', '[{"section":"1.9(a)","description":"Former client conflict — same or substantially related matter"},{"section":"1.9(b)","description":"Firm imputation for former client conflicts"},{"section":"1.9(c)","description":"Duty not to reveal or use former client confidential information"}]', '["conflict_check","motion_to_disqualify","informed_consent_waiver","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.10 — Imputation of Conflicts
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_028', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.10', 'RPC 1.10', 'Imputation of Conflicts of Interest — General Rule', 'While lawyers are associated in a firm, none of them shall knowingly represent a client when any one of them practicing alone would be prohibited from doing so by Rules 1.7 or 1.9.', '["Firm-wide imputation of conflicts under Rules 1.7 and 1.9","Screening permitted for lateral hires with former client conflicts","Written notice to affected former client required for screening","Timely screening from participation in matter required","Personal interest conflicts (Rule 1.7(b)) not always imputed"]', '[{"section":"1.10(a)","description":"General imputation rule — firm-wide conflict"},{"section":"1.10(b)","description":"Screening exception for lateral lawyers"},{"section":"1.10(c)","description":"Written notice to former client when screen applied"},{"section":"1.10(d)","description":"Exception — personal interest conflicts not imputed if no significant risk"}]', '["conflict_check","lateral_hire_screen","ethical_wall","motion_to_disqualify","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.13 — Organization as Client
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_029', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.13', 'RPC 1.13', 'Organization as Client', 'A lawyer employed or retained by an organization represents the organization acting through its authorized constituents, not the individual constituents.', '["Client is the organization, not its constituents","Must report up to higher authority if constituent acts contrary to organization interest","May refer matter to highest authority if necessary to prevent substantial injury","Must clarify lawyer role when organization interest diverges from constituent interest","May represent both organization and constituent if Rule 1.7 satisfied"]', '[{"section":"1.13(a)","description":"Organization is the client"},{"section":"1.13(b)","description":"Reporting up when constituent acts adversely to organization"},{"section":"1.13(c)","description":"Referral to highest authority to prevent substantial injury"},{"section":"1.13(f)","description":"Clarifying role to organization constituents"}]', '["corporate_representation","board_resolution","internal_investigation","whistleblower_report"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.14 — Client with Diminished Capacity
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_030', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.14', 'RPC 1.14', 'Client with Diminished Capacity', 'When a client has diminished capacity, the lawyer shall maintain a conventional relationship to the extent reasonably possible and may take protective action.', '["Maintain normal lawyer-client relationship as far as reasonably possible","May take reasonably necessary protective action","Protective action includes consulting with family members or support groups","May seek appointment of guardian ad litem or conservator as last resort","Information related to representation of client with diminished capacity is confidential"]', '[{"section":"1.14(a)","description":"Maintain conventional relationship to extent reasonably possible"},{"section":"1.14(b)","description":"Protective action when client at risk of substantial harm"},{"section":"Comment 5","description":"Emergency legal assistance — limited actions permitted"},{"section":"Comment 7","description":"Appointment of guardian or conservator as last resort"}]', '["conservatorship_petition","guardianship_petition","capacity_assessment","protective_action","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.16 — Declining or Terminating Representation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_031', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.16', 'RPC 1.16', 'Declining or Terminating Representation', 'A lawyer shall not represent a client or shall withdraw from representation if the representation will result in violation of law or rules of professional conduct, or the lawyer is impaired.', '["Mandatory withdrawal: representation will violate rules or law","Mandatory withdrawal: lawyer physical or mental condition materially impairs ability","Permissive withdrawal: client persists in criminal or fraudulent course of action","Permissive withdrawal: client makes representation unreasonably difficult","Must take steps to protect client interests upon withdrawal — return papers and refund unearned fees"]', '[{"section":"1.16(a)","description":"Mandatory withdrawal — violation of rules or impairment"},{"section":"1.16(b)","description":"Permissive withdrawal grounds"},{"section":"1.16(d)","description":"Protection of client interests upon termination — papers, refund, notice"}]', '["motion_to_withdraw","substitution_of_attorney","fee_refund","client_file_return","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 1.18 — Duties to Prospective Client
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_032', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.18', 'RPC 1.18', 'Duties to Prospective Client', 'A person who consults with a lawyer about the possibility of forming a client-lawyer relationship is owed duties of confidentiality and conflict avoidance even if no representation results.', '["Confidential information from consultation must be protected","Cannot represent adverse party in same or substantially related matter if received significantly harmful information","Informed written consent from both prospective and actual client can waive conflict","Screening of lawyer who received information may cure firm imputation"]', '[{"section":"1.18(a)","description":"Definition of prospective client"},{"section":"1.18(b)","description":"Confidentiality duty — even without representation"},{"section":"1.18(c)","description":"Conflict of interest from prospective client consultation"},{"section":"1.18(d)","description":"Screening to avoid firm imputation"}]', '["consultation_notes","intake_record","conflict_check","decline_letter","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 3.1 — Meritorious Claims and Contentions
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_033', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 3.1', 'RPC 3.1', 'Meritorious Claims and Contentions', 'A lawyer shall not bring or defend a proceeding, or assert or controvert an issue therein, unless there is a basis in law and fact for doing so that is not frivolous.', '["Must have non-frivolous basis in law and fact","Good faith argument for extension, modification, or reversal of existing law permitted","Defending accused in criminal proceeding: may require prosecution to prove every element","Frivolous includes harassing or malicious intent"]', '[{"section":"3.1(a)","description":"Non-frivolous basis requirement"},{"section":"3.1(b)","description":"Good faith argument for change in law permitted"},{"section":"Comment 2","description":"Criminal defense exception — prosecution burden"}]', '["complaint","motion","demurrer","anti-SLAPP_motion","sanctions_motion","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 3.2 — Delay of Litigation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_034', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 3.2', 'RPC 3.2', 'Delay of Litigation', 'In representing a client, a lawyer shall not use means that have no substantial purpose other than to delay or prolong the proceeding or to cause needless expense.', '["No tactics with sole substantial purpose of delay","No actions primarily to increase expense of litigation","Does not preclude vigorous advocacy","Realizing financial or other benefit from otherwise improper delay prohibited"]', '[{"section":"3.2","description":"Prohibition on dilatory tactics"},{"section":"Comment 1","description":"Financial benefit from delay is not legitimate reason"}]', '["continuance_request","discovery_motion","sanctions_motion","case_management_order"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 3.4 — Fairness to Opposing Party and Counsel
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_035', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 3.4', 'RPC 3.4', 'Fairness to Opposing Party and Counsel', 'A lawyer shall not unlawfully obstruct access to evidence, falsify evidence, counsel or assist a witness to testify falsely, or make frivolous discovery requests.', '["No unlawful obstruction of access to evidence","No alteration, destruction, or concealment of evidence","No falsification of evidence or counseling witness to testify falsely","No frivolous discovery requests","No violation of court rules or orders"]', '[{"section":"3.4(a)","description":"No obstruction or suppression of evidence"},{"section":"3.4(b)","description":"No falsification or destruction of evidence"},{"section":"3.4(d)","description":"No frivolous discovery requests or failure to comply"},{"section":"3.4(f)","description":"No request to refrain from giving relevant information to another party"}]', '["discovery_motion","sanctions_motion","evidence_spoliation","bar_complaint","OCTC_investigation"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 3.8 — Special Responsibilities of a Prosecutor
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_036', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 3.8', 'RPC 3.8', 'Special Responsibilities of a Prosecutor', 'A prosecutor in a criminal case shall not prosecute a charge that the prosecutor knows is not supported by probable cause and shall make timely disclosure of exculpatory evidence.', '["No prosecution without probable cause","Must make reasonable efforts to assure accused is advised of right to counsel","Must timely disclose all exculpatory evidence (Brady)","Must not subpoena lawyer to present evidence about past or present client unless no feasible alternative","Must remedy convictions when new credible material evidence of innocence discovered"]', '[{"section":"3.8(a)","description":"Probable cause requirement"},{"section":"3.8(b)","description":"Right to counsel — reasonable efforts"},{"section":"3.8(d)","description":"Brady disclosure — timely production of exculpatory evidence"},{"section":"3.8(f)","description":"Duty when new evidence of innocence discovered post-conviction"}]', '["Brady_material","discovery_disclosure","charging_document","post-conviction_review","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 4.1 — Truthfulness in Statements to Others
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_037', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 4.1', 'RPC 4.1', 'Truthfulness in Statements to Others', 'In the course of representing a client, a lawyer shall not knowingly make a false statement of material fact or law to a third person.', '["No false statements of material fact to third persons","No false statements of law to third persons","Must disclose material facts when necessary to avoid assisting client fraud (subject to confidentiality)","Misrepresentation can occur through failure to act"]', '[{"section":"4.1(a)","description":"Prohibition on knowingly false statements of material fact or law"},{"section":"4.1(b)","description":"Disclosure duty to avoid assisting client fraud"},{"section":"Comment 1","description":"Misrepresentation can occur by affirmative statement, partial truth, or failure to act"}]', '["demand_letter","settlement_negotiation","transaction_document","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 4.2 — Communication with Represented Person
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_038', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 4.2', 'RPC 4.2', 'Communication with a Represented Person', 'In representing a client, a lawyer shall not communicate directly with a person the lawyer knows to be represented by another lawyer in the matter, unless the lawyer has the consent of the other lawyer.', '["No direct communication with represented person without counsel consent","Applies when lawyer knows person is represented in the matter","Consent of represented person counsel required","Authorized by law exceptions (e.g., service of process)","Applies to organizations through managing agents and persons with authority to bind"]', '[{"section":"4.2(a)","description":"No-contact rule — represented persons"},{"section":"4.2(b)","description":"Consent of counsel or authorization by law"},{"section":"Comment 5","description":"Organizational constituents covered — managing agents"},{"section":"Comment 8","description":"Government investigations exception"}]', '["ex_parte_communication","contact_log","bar_complaint","motion_to_disqualify"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 4.3 — Dealing with Unrepresented Person
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_039', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 4.3', 'RPC 4.3', 'Dealing with Unrepresented Person', 'In dealing on behalf of a client with a person who is not represented by counsel, a lawyer shall not state or imply that the lawyer is disinterested and shall correct any misunderstanding as to the lawyer''s role.', '["Must not state or imply disinterested status","Must identify client whose interests are being represented","Must correct misunderstanding about lawyer role","Must not give legal advice to unrepresented person with interests adverse to client","May state legal position of client"]', '[{"section":"4.3(a)","description":"No implication of disinterestedness"},{"section":"4.3(b)","description":"Correct misunderstanding of lawyer role"},{"section":"4.3(c)","description":"No legal advice to adverse unrepresented person"}]', '["pro_se_communication","demand_letter","contact_log","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 5.1 — Responsibilities of Managerial and Supervisory Lawyers
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_040', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 5.1', 'RPC 5.1', 'Responsibilities of Managerial and Supervisory Lawyers', 'A lawyer with managerial authority in a firm shall make reasonable efforts to ensure the firm has measures giving reasonable assurance of Rules compliance. A supervising lawyer is responsible for another lawyer''s misconduct under specified conditions.', '["Managing lawyers must ensure firm-wide ethics compliance measures","Supervisory lawyers must make reasonable efforts to ensure supervised lawyer compliance","Responsible for subordinate misconduct if: orders or ratifies conduct, or knows and fails to take remedial action","Partners and managing lawyers responsible for firm-level compliance systems"]', '[{"section":"5.1(a)","description":"Managerial duty — firm-wide ethics compliance"},{"section":"5.1(b)","description":"Supervisory duty — reasonable supervision"},{"section":"5.1(c)","description":"Responsibility for subordinate misconduct — ordering, ratifying, or failing to act"}]', '["firm_policy","supervision_record","ethics_training","bar_complaint","OCTC_investigation"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 5.3 — Responsibilities Regarding Nonlawyer Assistants
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_041', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 5.3', 'RPC 5.3', 'Responsibilities Regarding Nonlawyer Assistants', 'A lawyer having managerial authority shall make reasonable efforts to ensure nonlawyer assistants act compatibly with the professional obligations of the lawyer.', '["Managing lawyers must ensure nonlawyer assistants comply with ethics obligations","Supervising lawyers must make reasonable efforts to ensure compatible conduct","Responsible for nonlawyer misconduct if: orders or ratifies, or knows and fails to mitigate","Applies to paralegals, secretaries, investigators, and other nonlawyer staff"]', '[{"section":"5.3(a)","description":"Managerial duty — nonlawyer compliance measures"},{"section":"5.3(b)","description":"Supervisory duty — reasonable efforts"},{"section":"5.3(c)","description":"Responsibility for nonlawyer conduct — ordering, ratifying, or failing to act"}]', '["supervision_record","paralegal_assignment","nonlawyer_training","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 7.1 — Communications Concerning a Lawyer's Services
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_042', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 7.1', 'RPC 7.1', 'Communications Concerning a Lawyer''s Services', 'A lawyer shall not make a false or misleading communication about the lawyer or the lawyer''s services, including material misrepresentation of facts or omission of facts necessary to prevent statements from being misleading.', '["No false or misleading communications about lawyer services","No material misrepresentation of fact","No omission of fact necessary to prevent misleading statement","Includes advertising and marketing communications","Includes firm names, letterhead, and professional designations"]', '[{"section":"7.1(a)","description":"False or misleading communication prohibited"},{"section":"7.1(b)","description":"Definition of false or misleading — includes material misrepresentation and misleading omission"},{"section":"Comment 2","description":"Truthful statements that are misleading are also prohibited"}]', '["advertising","website","marketing_material","letterhead","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

-- Rule 8.1 — Bar Admission and Disciplinary Matters
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_043', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 8.1', 'RPC 8.1', 'Bar Admission and Disciplinary Matters', 'An applicant for admission or a lawyer in connection with a bar admission application or disciplinary matter shall not knowingly make a false statement of material fact or fail to disclose a fact necessary to correct a misapprehension.', '["No false statement of material fact in bar admission or disciplinary matter","Must correct misapprehension known to have arisen","Must respond to lawful demand for information from admissions or disciplinary authority","Rule does not require disclosure of information protected by Rule 1.6"]', '[{"section":"8.1(a)","description":"No false statements of material fact"},{"section":"8.1(b)","description":"No failure to disclose or correct misapprehension"},{"section":"8.1(b)","description":"Cooperate with disciplinary authority — respond to lawful demands"}]', '["bar_application","disciplinary_response","OCTC_investigation","moral_character_determination"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California / Supreme Court', 1, 1, datetime('now'), datetime('now'));

-- Rule 8.3 — Reporting Professional Misconduct
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_044', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 8.3', 'RPC 8.3', 'Reporting Professional Misconduct', 'California does not impose a mandatory reporting duty on lawyers for peer misconduct (unlike ABA Model Rule 8.3), but permissive reporting is allowed and may be ethically required in extreme cases.', '["No mandatory self-reporting duty under California RPC (unlike ABA Model Rules)","Permissive reporting to State Bar allowed","B&P 6068(o) requires reporting of certain court sanctions","Judges have mandatory reporting obligations under CJP rules","Extreme misconduct may trigger ethical duty to report"]', '[{"section":"8.3","description":"California approach — no mandatory peer reporting obligation"},{"section":"B&P 6068(o)","description":"Attorney must report certain judicial sanctions to State Bar"},{"section":"Comment","description":"Permissive reporting does not violate confidentiality when based on generally known information"}]', '["bar_complaint","OCTC_referral","judicial_sanction_report","misconduct_report"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- STATUTORY PROVISIONS — Evidence Code & Business and Professions Code
-- ═══════════════════════════════════════════════════════════════════════════

-- Cal. Evid. Code §§ 1010-1027 — Psychotherapist-Patient Privilege
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_045', 'ETHICARA', 'STATE_STATUTE', 'CA', 'Cal. Evid. Code §§ 1010-1027', 'Evid. Code §§ 1010-1027', 'Psychotherapist-Patient Privilege', 'California statutory privilege protecting confidential communications between patient and psychotherapist from compelled disclosure in legal proceedings.', '["Psychotherapist defined broadly: psychiatrist, psychologist, LCSW, LMFT, and others (§ 1010)","Confidential communication: information transmitted in course of relationship and not intended to be disclosed (§ 1012)","Patient holds the privilege (§ 1014)","Privilege survives death of patient","Exceptions: dangerous patient (Tarasoff), court-ordered examination, child abuse reporting, proceedings to hospitalize patient"]', '[{"section":"1010","description":"Definition of psychotherapist — psychiatrist, psychologist, LCSW, LMFT, etc."},{"section":"1012","description":"Confidential communication defined"},{"section":"1014","description":"Patient privilege — holder may refuse to disclose and prevent others from disclosing"},{"section":"1016","description":"Patient-litigant exception — patient tenders mental condition"},{"section":"1017","description":"Court-appointed psychotherapist exception"},{"section":"1024","description":"Dangerous patient exception (Tarasoff)"},{"section":"1027","description":"Child under 16 victim of crime exception"}]', '["therapy_record","psychiatric_evaluation","forensic_evaluation","privilege_log","motion_to_quash","subpoena"]', '["state-bar-of-california-attorney-conduct-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- Cal. Bus. & Prof. Code § 6068 — Duties of Attorneys
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_046', 'ETHICARA', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code § 6068', 'B&P § 6068', 'Duties of Attorneys', 'Comprehensive statutory enumeration of the duties of California attorneys including support of the Constitution, maintenance of respect for courts, honesty, confidentiality, and compliance with court orders.', '["Support Constitution and laws of the United States and California","Maintain respect due to courts and judicial officers","Counsel or maintain only legal actions and defenses","Employ only means consistent with truth","Maintain inviolate confidence and secrets of client (§ 6068(e))","Abstain from offensive personality","Advance no fact prejudicial to honor or reputation of party unless required by justice","Never reject cause of defenseless or oppressed","Comply with court orders and report certain sanctions (§ 6068(o))","Cooperate with State Bar investigations"]', '[{"section":"6068(a)","description":"Support Constitution and laws"},{"section":"6068(b)","description":"Maintain respect for courts"},{"section":"6068(c)","description":"Only legal actions and defenses"},{"section":"6068(d)","description":"Means consistent with truth"},{"section":"6068(e)","description":"Maintain inviolate client confidences and secrets"},{"section":"6068(h)","description":"Never reject cause of defenseless or oppressed"},{"section":"6068(i)","description":"Cooperate and participate in State Bar investigations"},{"section":"6068(o)","description":"Report judicial sanctions to State Bar within 30 days"}]', '["bar_complaint","disciplinary_proceeding","OCTC_investigation","court_order","sanctions_order"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California / Supreme Court', 1, 1, datetime('now'), datetime('now'));
