-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 2
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Expands the library with standards from banking-financial-document-audit,
-- california-immigration-rights-audit, california-state-agency-correspondence,
-- cad-log-compliance-audit, and fills gaps for INTEGRA, PRIVAXIS, VIGILUS.
--
-- Generated: March 17, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — BATCH 2: Banking & Financial Document Audit expansion
-- ═══════════════════════════════════════════════════════════════════════════

-- ECOA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_008', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1691-1691f', 'ECOA', 'Equal Credit Opportunity Act', 'Prohibits discrimination in credit transactions based on race, color, religion, national origin, sex, marital status, age, or public assistance status.', '["Cannot discriminate in any aspect of credit transaction","Must provide adverse action notice within 30 days","Must retain records for 25 months","Cannot request information about spouse unless joint application"]', '[{"section":"1691(a)","description":"Prohibited bases for discrimination"},{"section":"1691(d)","description":"Adverse action notice requirements"},{"section":"1691e","description":"Civil liability"}]', '["loan_application","adverse_action_notice","credit_decision","underwriting_file"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- EFTA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_009', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1693-1693r', 'EFTA', 'Electronic Fund Transfer Act', 'Consumer protections for electronic fund transfers including ATM, debit card, direct deposit, and online banking.', '["Initial disclosures of terms and conditions","60-day window for unauthorized transfer disputes","Provisional credit within 10 business days","Error resolution within 45 days"]', '[{"section":"1693c","description":"Terms and conditions disclosure"},{"section":"1693f","description":"Error resolution procedures"},{"section":"1693g","description":"Consumer liability limits for unauthorized transfers"},{"section":"1693m","description":"Civil liability"}]', '["bank_statement","EFT_disclosure","debit_card_agreement","error_resolution"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- EFAA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_010', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC §§ 4001-4010', 'EFAA / Reg CC', 'Expedited Funds Availability Act', 'Requires banks to make deposited funds available within specified timeframes and provide holds disclosures.', '["Local checks: next business day availability","Non-local checks: 2 business days","New account exceptions","Must disclose hold policies at account opening"]', '[{"section":"4002","description":"Funds availability schedules"},{"section":"4003","description":"Safeguard exceptions (large deposits, repeated overdrafts)"},{"section":"4005","description":"Disclosure requirements"}]', '["hold_notice","account_disclosure","deposit_receipt"]', '["banking-financial-document-audit"]', 'CFPB / Federal Reserve', 1, 1, datetime('now'), datetime('now'));

-- BSA/AML
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_011', 'FISCARA', 'FEDERAL_STATUTE', 'US', '31 USC §§ 5311-5332', 'BSA', 'Bank Secrecy Act / Anti-Money Laundering', 'Requires financial institutions to maintain records, file reports, and implement AML programs to prevent money laundering and terrorist financing.', '["Currency Transaction Reports (CTR) for transactions over $10,000","Suspicious Activity Reports (SAR) for suspicious transactions","Customer Identification Program (CIP) required","AML compliance program mandatory"]', '[{"section":"5312","description":"Definitions of financial institutions"},{"section":"5313","description":"CTR requirements"},{"section":"5318","description":"AML compliance programs"},{"section":"5318(g)","description":"SAR filing requirements"}]', '["CTR","SAR","CIP_record","AML_program","KYC_document"]', '["banking-financial-document-audit"]', 'FinCEN / OCC / FDIC', 0, 1, datetime('now'), datetime('now'));

-- GLBA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_012', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 6801-6809 (Gramm-Leach-Bliley Act, Title V)', 'GLBA', 'Gramm-Leach-Bliley Act — Financial Privacy', 'Requires financial institutions to protect consumer financial information and provide privacy notices.', '["Annual privacy notice to customers","Opt-out rights for information sharing with non-affiliates","Safeguards Rule: written information security program","Pretexting prohibition"]', '[{"section":"6802","description":"Privacy notice obligations"},{"section":"6802(b)","description":"Opt-out rights"},{"section":"6801(b)","description":"Safeguards for customer information"}]', '["privacy_notice","opt_out_notice","information_security_plan"]', '["banking-financial-document-audit"]', 'CFPB / FTC / OCC', 0, 1, datetime('now'), datetime('now'));

-- UDAAP
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_013', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC § 5531', 'UDAAP', 'Unfair, Deceptive, or Abusive Acts or Practices', 'CFPB authority to prevent unfair, deceptive, or abusive acts or practices in consumer financial products.', '["Unfair: causes substantial injury not reasonably avoidable","Deceptive: misleading representation or omission","Abusive: takes unreasonable advantage of consumer","Applies to all consumer financial products and services"]', '[{"section":"5531(c)","description":"Unfair acts definition"},{"section":"5531(d)","description":"Abusive acts definition"},{"section":"5536","description":"Prohibited acts and penalties"}]', '["marketing_material","account_agreement","fee_schedule","complaint"]', '["banking-financial-document-audit"]', 'CFPB', 0, 1, datetime('now'), datetime('now'));

-- HMDA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_014', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC §§ 2801-2811', 'HMDA', 'Home Mortgage Disclosure Act', 'Requires mortgage lenders to report data about their lending patterns to help identify discriminatory lending practices.', '["Annual LAR (Loan Application Register) filing","Data includes race, ethnicity, sex, income of applicants","Public disclosure of lending data","Applies to depository and non-depository mortgage lenders"]', '[{"section":"2803","description":"Maintenance and reporting of data"},{"section":"2804","description":"Public disclosure requirements"}]', '["LAR","HMDA_report","mortgage_application"]', '["banking-financial-document-audit"]', 'CFPB / FFIEC', 0, 1, datetime('now'), datetime('now'));

-- California Financial Code
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_015', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Fin. Code §§ 22000-22780', 'CFL', 'California Financing Law', 'State licensing and regulation of consumer and commercial lenders and brokers in California.', '["DFPI license required for consumer lending","Rate and fee disclosures","Prohibited practices and grounds for discipline","Annual reporting requirements"]', '[{"section":"22009","description":"Finance lender definition"},{"section":"22302","description":"License requirements"},{"section":"22750","description":"Prohibited practices"}]', '["loan_agreement","lending_license","DFPI_examination","consumer_complaint"]', '["banking-financial-document-audit"]', 'California DFPI', 1, 1, datetime('now'), datetime('now'));

-- Cal Civil Code 1632 — Translation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_016', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1632', 'CC § 1632', 'Contract Translation Requirements', 'Requires translation of contracts negotiated primarily in Spanish, Chinese, Tagalog, Vietnamese, or Korean.', '["Must provide translated contract before signing","Applies to loans, leases, and other specified contracts","Five covered languages","Exception for buyer who provides own interpreter"]', '[{"section":"1632(a)-(b)","description":"Covered languages and contract types"},{"section":"1632(d)","description":"Translation delivery timing"}]', '["loan_agreement","lease","consumer_contract","credit_application"]', '["banking-financial-document-audit","california-housing-tenant-rights-audit"]', 'California Attorney General', 1, 1, datetime('now'), datetime('now'));

-- UCL
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_017', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 17200-17210', 'UCL', 'Unfair Competition Law', 'Broad California statute prohibiting unlawful, unfair, or fraudulent business acts or practices.', '["Three prongs: unlawful, unfair, fraudulent","Borrows violations from any other law (unlawful prong)","Restitution and injunctive relief available","Standing requires injury in fact and lost money or property"]', '[{"section":"17200","description":"Definition of unfair competition"},{"section":"17203","description":"Remedies — restitution, injunction"},{"section":"17204","description":"Standing requirements"}]', '["business_practice","advertising","consumer_complaint","financial_product"]', '["banking-financial-document-audit"]', 'California Attorney General / District Attorney / Private', 1, 1, datetime('now'), datetime('now'));

-- CLRA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_018', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1750-1785', 'CLRA', 'Consumer Legal Remedies Act', 'Prohibits 27 enumerated deceptive practices in transactions for goods or services to consumers.', '["27 enumerated prohibited practices","Actual damages, injunction, restitution, punitive damages available","30-day demand letter required before suit","Class action available"]', '[{"section":"1770","description":"27 prohibited practices"},{"section":"1780","description":"Remedies — damages, injunction, restitution"},{"section":"1782","description":"30-day notice requirement"}]', '["consumer_contract","advertising","sales_agreement","complaint"]', '["banking-financial-document-audit"]', 'California Courts / AG', 1, 1, datetime('now'), datetime('now'));

-- Reg Z
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_019', 'FISCARA', 'FEDERAL_REGULATION', 'US', '12 CFR Part 1026', 'Reg Z', 'Regulation Z — Truth in Lending', 'Implementing regulation for TILA prescribing disclosure forms, timing, and content for consumer credit.', '["Loan Estimate within 3 business days of application","Closing Disclosure 3 business days before consummation","APR calculation methodology","Right of rescission procedures"]', '[{"section":"1026.17-1026.18","description":"Open-end credit disclosures"},{"section":"1026.19","description":"Closed-end mortgage disclosures"},{"section":"1026.37","description":"Loan Estimate content"},{"section":"1026.38","description":"Closing Disclosure content"}]', '["Loan_Estimate","Closing_Disclosure","TILA_disclosure","periodic_statement"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- Reg X
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_020', 'FISCARA', 'FEDERAL_REGULATION', 'US', '12 CFR Part 1024', 'Reg X', 'Regulation X — Real Estate Settlement Procedures', 'Implementing regulation for RESPA covering mortgage servicing, escrow, and loss mitigation.', '["Qualified Written Request response within 30 days","Loss mitigation application review within 30 days","No dual tracking (foreclosure during loss mitigation review)","Escrow account analysis requirements"]', '[{"section":"1024.35","description":"Error resolution procedures"},{"section":"1024.36","description":"Information request procedures"},{"section":"1024.41","description":"Loss mitigation procedures"}]', '["QWR","loss_mitigation_application","escrow_analysis","servicing_transfer"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- Reg E
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_021', 'FISCARA', 'FEDERAL_REGULATION', 'US', '12 CFR Part 1005', 'Reg E', 'Regulation E — Electronic Fund Transfers', 'Implementing regulation for EFTA covering error resolution, unauthorized transfers, and disclosure requirements.', '["Provisional credit within 10 business days","Investigation complete within 45 days (90 for new accounts)","Written determination to consumer","Periodic statement requirements"]', '[{"section":"1005.6","description":"Liability for unauthorized transfers"},{"section":"1005.11","description":"Error resolution procedures"},{"section":"1005.18","description":"Prepaid accounts"}]', '["EFT_dispute","provisional_credit_notice","periodic_statement","prepaid_disclosure"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — BATCH 2: Immigration, State Agency, CAD expansion
-- ═══════════════════════════════════════════════════════════════════════════

-- Immigration — Worker Protections
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_025', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code § 1019', 'LC § 1019', 'Prohibition on Immigration Retaliation', 'Employers cannot retaliate against workers based on immigration status for exercising labor rights.', '["Cannot threaten to report immigration status","Cannot use immigration status to retaliate for filing complaints","Rebuttable presumption of retaliation if action within 90 days"]', '[{"section":"1019(a)","description":"Prohibited unfair immigration-related practices"},{"section":"1019(b)","description":"Rebuttable presumption of retaliation"}]', '["employment_complaint","retaliation_claim","labor_board_filing"]', '["california-immigration-rights-audit"]', 'California Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_026', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code § 1024.6 (AB 450)', 'LC § 1024.6', 'Employer Duties During Immigration Audit', 'Restrictions on employer conduct during federal immigration enforcement actions at the worksite.', '["Must notify employees within 72 hours of I-9 audit notice","Cannot provide voluntary access to non-public areas without warrant","Must post notice of inspection results within 72 hours","Cannot reverify documents not required by federal law"]', '[{"section":"1024.6(a)","description":"Employee notification of I-9 audit"},{"section":"1024.6(b)","description":"Restrictions on voluntary access"},{"section":"1024.6(c)","description":"Results posting requirement"}]', '["I-9_audit_notice","employer_notification","ICE_inspection"]', '["california-immigration-rights-audit"]', 'California Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_027', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 22440-22449', 'B&P §§ 22440-22449', 'Immigration Consultant Regulation', 'Licensing and conduct requirements for immigration consultants including bond, disclosure, and prohibited practices.', '["Must be bonded ($100,000)","Written contract required before services","Cannot represent they are attorneys","Must provide disclaimers in advertising","Cannot make guarantees about immigration outcomes"]', '[{"section":"22441","description":"Bond requirement"},{"section":"22442","description":"Written contract requirements"},{"section":"22443","description":"Prohibited practices"}]', '["immigration_consultant_contract","advertising","client_disclosure"]', '["california-immigration-rights-audit"]', 'California Secretary of State / AG', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_028', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1940.05', 'CC § 1940.05', 'Immigration Status Irrelevant in Tenancy', 'A landlord cannot inquire about or consider immigration or citizenship status of a tenant or applicant.', '["Cannot inquire about immigration status","Cannot consider immigration status in rental decisions","Cannot threaten to disclose status"]', '[{"section":"1940.05(a)","description":"Prohibition on immigration status inquiries"},{"section":"1940.35","description":"Prohibition on immigration enforcement threats"}]', '["rental_application","lease","eviction_notice"]', '["california-immigration-rights-audit","california-housing-tenant-rights-audit"]', 'California CRD', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_029', 'REGULIS', 'FEDERAL_STATUTE', 'US', '8 USC § 1324b', 'INA Anti-Discrimination', 'Immigration and Nationality Act — Anti-Discrimination', 'Federal prohibition on national origin and citizenship status discrimination in hiring, firing, and recruitment.', '["Cannot discriminate based on citizenship status (with exceptions)","Cannot discriminate based on national origin (employers with 4-14 employees)","Document abuse prohibited","Retaliation prohibited"]', '[{"section":"1324b(a)(1)","description":"Citizenship status discrimination"},{"section":"1324b(a)(6)","description":"Document abuse"},{"section":"1324b(g)","description":"Penalties"}]', '["hiring_decision","I-9","employment_verification","discrimination_charge"]', '["california-immigration-rights-audit"]', 'DOJ Immigrant and Employee Rights Section', 1, 1, datetime('now'), datetime('now'));

-- State Agency Correspondence
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_030', 'REGULIS', 'AGENCY_STANDARD', 'CA', 'State Administrative Manual (SAM) §§ 1215-1230', 'SAM §§ 1215-1230', 'Official State Correspondence Standards', 'Standards for format, content, and signature authority of official California state agency correspondence.', '["Standard letter format required","Proper signature authority chain","Classification of correspondence types","Records retention requirements"]', '[{"section":"1215","description":"Official correspondence standards"},{"section":"1220","description":"Letter format requirements"},{"section":"1230","description":"Signature authority"}]', '["agency_letter","official_notice","administrative_decision","notice_of_action"]', '["california-state-agency-correspondence-audit"]', 'Department of General Services', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_031', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code § 6219', 'GC § 6219', 'Plain Language in State Documents', 'State agencies must draft documents in plain, straightforward language.', '["Use simple, clear language","Avoid unnecessary jargon and legalese","Documents must be understandable to intended audience"]', '[{"section":"6219","description":"Plain language requirement for state documents"}]', '["agency_letter","notice","form","regulation"]', '["california-state-agency-correspondence-audit"]', 'Office of Administrative Law', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_032', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 7290-7299.8', 'Dymally-Alatorre Act', 'Dymally-Alatorre Bilingual Services Act', 'Requires state agencies to provide services and translated materials to non-English-speaking populations they serve.', '["Survey language needs of persons served","Employ qualified bilingual staff","Translate vital documents","Provide interpretation services"]', '[{"section":"7292","description":"Agency survey requirements"},{"section":"7295","description":"Bilingual service requirements"},{"section":"7296","description":"Translation of written materials"}]', '["agency_notice","translated_document","language_access_plan"]', '["california-state-agency-correspondence-audit","california-immigration-rights-audit"]', 'State Personnel Board', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_033', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code § 11135', 'GC § 11135', 'Non-Discrimination in State Programs', 'No person shall be unlawfully denied benefits of or be subjected to discrimination under any program or activity funded by the state.', '["Applies to all state-funded programs","Covers race, religion, sex, disability, and other protected classes","Accessibility requirements for facilities and communications","ADA compliance incorporated"]', '[{"section":"11135(a)","description":"Prohibition on discrimination in state programs"},{"section":"11135(b)","description":"Definitions and scope"}]', '["agency_program","state_benefit","accessibility_complaint","accommodation_request"]', '["california-state-agency-correspondence-audit"]', 'California CRD', 1, 1, datetime('now'), datetime('now'));

-- CAD Log — additional standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_034', 'REGULIS', 'PROFESSIONAL_STANDARD', 'US', 'APCO ANS 1.101.3 — Core Competencies', 'APCO Core Competencies', 'Core Competencies for Public-Safety Communications', 'Defines minimum competencies for 911 dispatchers including call processing, radio communications, and stress management.', '["Call intake and processing standards","Radio communication protocols","Stress recognition and management","Multi-tasking and prioritization"]', '[{"section":"Call Processing","description":"Standards for receiving and processing emergency calls"},{"section":"Radio Procedures","description":"Proper radio communication protocols"}]', '["CAD_log","dispatch_record","training_record"]', '["cad-log-compliance-audit"]', 'APCO International', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_035', 'REGULIS', 'PROFESSIONAL_STANDARD', 'US', 'NENA-STA-020 — 911 Call Processing', 'NENA-STA-020', 'NENA 911 Call Processing Standard', 'National standards for processing 911 calls including call answering, interrogation, and dispatch.', '["Answer within 15/40 seconds (90th/95th percentile)","Standardized interrogation protocol","Proper call classification","Accurate location determination"]', '[{"section":"Call Answering","description":"Time-to-answer standards"},{"section":"Call Classification","description":"Proper incident type coding"},{"section":"Location","description":"Caller location verification procedures"}]', '["CAD_log","911_call_record","dispatch_record","PSAP_record"]', '["cad-log-compliance-audit"]', 'NENA', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_036', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 53110-53115.5', 'GC §§ 53110+', 'California 911 Emergency Communication Requirements', 'Requirements for local agencies maintaining 911 systems including equipment, staffing, and access.', '["911 system must be operational and maintained","Access for disabled persons","TTY/TDD capability required","Annual reporting to California 911 Office"]', '[{"section":"53110","description":"911 system requirements"},{"section":"53115","description":"California 911 Emergency Communications Office"}]', '["PSAP_record","911_system_audit","annual_report"]', '["cad-log-compliance-audit"]', 'California 911 Office', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_037', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Health & Safety Code §§ 1797-1799.207', 'HSC §§ 1797+', 'Emergency Medical Services Act', 'Framework for EMS dispatch, response, and mutual aid including dispatch protocols and response time standards.', '["Medical priority dispatch protocols","EMD questioning protocols","Response time compliance","Mutual aid coordination"]', '[{"section":"1797.176","description":"EMS dispatch requirements"},{"section":"1797.220","description":"Local EMS agency authority"},{"section":"1798","description":"EMT and paramedic scope of practice"}]', '["EMS_dispatch","CAD_log","medical_priority_dispatch","EMD_record"]', '["cad-log-compliance-audit"]', 'EMSA / Local EMS Agencies', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — Data Protection & Privacy Compliance
-- No skills yet, but foundational privacy standards for the platform
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_001', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1798.100-1798.199.100', 'CCPA/CPRA', 'California Consumer Privacy Act (as amended by CPRA)', 'Comprehensive consumer privacy law granting rights to know, delete, correct, opt-out, and limit use of personal information.', '["Right to know what personal information is collected","Right to delete personal information","Right to opt-out of sale/sharing","Right to correct inaccurate personal information","Right to limit use of sensitive personal information","12-month lookback period"]', '[{"section":"1798.100","description":"Right to know and access"},{"section":"1798.105","description":"Right to delete"},{"section":"1798.106","description":"Right to correct"},{"section":"1798.120","description":"Right to opt-out of sale/sharing"},{"section":"1798.121","description":"Right to limit sensitive PI use"},{"section":"1798.150","description":"Private right of action for data breaches"}]', '["privacy_policy","data_request","opt_out_request","data_breach_notice"]', '[]', 'California Privacy Protection Agency (CPPA)', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_002', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1798.29, 1798.82', 'CA Data Breach', 'California Data Breach Notification Law', 'Requires businesses to notify California residents when their personal information is exposed in a data breach.', '["Notify affected individuals in most expedient time possible","Notification must include specific content elements","Notify AG if breach affects 500+ residents","Encryption is a safe harbor"]', '[{"section":"1798.29","description":"Agency breach notification requirements"},{"section":"1798.82","description":"Business breach notification requirements"}]', '["breach_notice","incident_report","AG_notification"]', '[]', 'California AG', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_003', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '45 CFR Parts 160, 164 (HIPAA)', 'HIPAA', 'Health Insurance Portability and Accountability Act — Privacy & Security Rules', 'Federal standards for protecting individually identifiable health information (PHI).', '["Privacy Rule: limits use and disclosure of PHI","Security Rule: administrative, physical, technical safeguards","Breach Notification Rule: notify within 60 days","Minimum necessary standard for disclosures"]', '[{"section":"164.502","description":"Uses and disclosures of PHI"},{"section":"164.508","description":"Authorization requirements"},{"section":"164.312","description":"Technical safeguards"},{"section":"164.410-414","description":"Breach notification requirements"}]', '["medical_record","authorization_form","breach_notice","BAA"]', '[]', 'HHS Office for Civil Rights', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Threat Assessment & Operational Risk
-- No skills yet, but foundational risk/security standards
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_001', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 USC §§ 1028-1028A', 'Identity Theft Statutes', 'Federal Identity Theft and Aggravated Identity Theft', 'Federal criminal statutes prohibiting identity theft and providing enhanced penalties for aggravated identity theft.', '["Production or transfer of false identification documents","Possession of identity documents with intent to defraud","Aggravated identity theft: mandatory 2-year consecutive sentence","Applies to use of another persons means of identification"]', '[{"section":"1028","description":"Fraud and related activity in connection with identification documents"},{"section":"1028A","description":"Aggravated identity theft — mandatory consecutive 2 years"}]', '["identity_theft_report","fraud_complaint","credit_freeze","FTC_identity_theft_affidavit"]', '[]', 'DOJ / FBI / FTC', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_002', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 USC §§ 1030', 'CFAA', 'Computer Fraud and Abuse Act', 'Federal law prohibiting unauthorized access to protected computers and computer fraud.', '["Unauthorized access to protected computers","Exceeding authorized access","Trafficking in passwords","Causing damage to protected computers","Civil and criminal remedies"]', '[{"section":"1030(a)(2)","description":"Obtaining information from protected computer"},{"section":"1030(a)(5)","description":"Causing damage to protected computer"},{"section":"1030(g)","description":"Civil action for damages"}]', '["incident_report","forensic_analysis","access_log","security_breach"]', '[]', 'DOJ / FBI', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_003', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 USC §§ 2510-2522', 'Wiretap Act', 'Federal Wiretap Act (Title III)', 'Prohibits intentional interception of wire, oral, or electronic communications.', '["Cannot intercept communications without authorization","One-party or two-party consent depending on jurisdiction","Exclusionary rule for illegally intercepted communications","Civil damages: greater of actual damages or $100/day minimum $10,000"]', '[{"section":"2511","description":"Prohibition on interception"},{"section":"2515","description":"Exclusionary rule"},{"section":"2520","description":"Civil damages"}]', '["wiretap_order","surveillance_record","communications_intercept","civil_complaint"]', '[]', 'DOJ / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_004', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 502', 'PC § 502', 'California Unauthorized Computer Access', 'State law prohibiting unauthorized access to computer systems, data, and networks.', '["Unauthorized access to computer, system, or network","Disruption of computer services","Introduction of contaminant (malware)","Civil and criminal remedies"]', '[{"section":"502(c)","description":"Enumerated prohibited acts"},{"section":"502(e)","description":"Civil action for compensatory damages and injunction"}]', '["computer_fraud_report","incident_report","forensic_analysis"]', '[]', 'California AG / DA', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_005', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code §§ 630-638', 'CA Wiretap / Eavesdropping', 'California Invasion of Privacy Act', 'Two-party consent state — all parties must consent to recording of confidential communications.', '["Two-party consent required for recording","Cannot eavesdrop on confidential communications","Cannot record without consent of all parties","Treble damages available in civil action"]', '[{"section":"631","description":"Wiretapping prohibited"},{"section":"632","description":"Eavesdropping on confidential communications"},{"section":"632.7","description":"Recording cellular/cordless communications"},{"section":"637.2","description":"Civil action — $5,000 per violation or treble damages"}]', '["recording","surveillance","phone_record","communication_intercept"]', '[]', 'California AG / DA', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- INTEGRA — Internal Compliance & Operational Integrity
-- 3 Skills: intake, input refiner, guardrails
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_001', 'INTEGRA', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 3400-3425 (UCCJEA)', 'UCCJEA', 'Uniform Child Custody Jurisdiction and Enforcement Act', 'Determines which state has jurisdiction over child custody matters and provides enforcement mechanisms for custody orders.', '["Home state jurisdiction: state where child lived 6 consecutive months","Exclusive continuing jurisdiction until all parties leave state","Emergency jurisdiction for children at risk","Must enforce valid orders from other states"]', '[{"section":"3421","description":"Initial child custody jurisdiction"},{"section":"3422","description":"Exclusive continuing jurisdiction"},{"section":"3424","description":"Temporary emergency jurisdiction"},{"section":"3443","description":"Enforcement procedures"}]', '["custody_order","jurisdiction_motion","UCCJEA_declaration"]', '["project-context-and-guardrails"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_002', 'INTEGRA', 'COURT_RULE', 'CA', 'California Rules of Court, Rule 5.250', 'CRC 5.250', 'Mandatory Custody Evaluation Procedures', 'Procedures for court-ordered custody evaluations including qualifications, methodology, and report requirements.', '["Evaluator must meet minimum qualifications","Both parties must have opportunity to participate","Report must address best interest factors","Must be completed within court timeframe"]', '[{"section":"5.250(a)","description":"Appointment of evaluator"},{"section":"5.250(b)","description":"Minimum qualifications"},{"section":"5.250(c)","description":"Evaluation methodology"}]', '["custody_evaluation","730_report","court_order"]', '["automated-structuring-input-refiner","project-context-and-guardrails"]', 'Superior Court of California', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_003', 'INTEGRA', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code § 6125', 'B&P § 6125', 'Unauthorized Practice of Law', 'Only active members of the State Bar may practice law in California. AI-assisted compliance tools must not cross this boundary.', '["Only licensed attorneys may practice law","Providing legal advice constitutes practice of law","Legal information vs. legal advice distinction","Compliance platforms must disclaim legal advice"]', '[{"section":"6125","description":"Prohibition on unauthorized practice"},{"section":"6126","description":"Penalties for unauthorized practice"}]', '["platform_disclaimer","compliance_report","legal_information"]', '["master-project-intake-audit-triage","project-context-and-guardrails"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));
