-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Seeds each Citizen's professional knowledge base with authoritative
-- governing standards derived from their assigned skills.
--
-- Generated: March 17, 2026
-- Standard 4 (Knowledge): Knowledge belongs to the Citizen.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Regulatory Intelligence & Multi-jurisdictional Compliance
-- 8 Skills: CAD logs, court orders, state agency, housing, labor,
--           immigration, real estate fraud, insurance bad faith
-- ═══════════════════════════════════════════════════════════════════════════

-- California Rules of Court
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_001', 'REGULIS', 'COURT_RULE', 'CA', 'California Rules of Court, Rule 1.31', 'CRC 1.31', 'Filing Requirements', 'General requirements for filing documents with California courts, including format, signatures, and service.', '["Documents must be signed","Proof of service required","Comply with formatting rules"]', '[{"section":"1.31(a)","description":"Form and format of papers"},{"section":"1.31(b)","description":"Signature requirements"}]', '["court_filing","motion","petition","declaration"]', '["california-court-order-compliance-audit"]', 'Judicial Council of California', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_002', 'REGULIS', 'COURT_RULE', 'CA', 'California Rules of Court, Rule 2.30', 'CRC 2.30', 'Format of Citations', 'Standard format for citing California authorities in court documents.', '["Citations must follow official format","Include parallel citations where available"]', '[{"section":"2.30","description":"Citation format standards"}]', '["court_filing","brief","motion","memorandum"]', '["california-court-order-compliance-audit"]', 'Judicial Council of California', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_003', 'REGULIS', 'COURT_RULE', 'CA', 'California Rules of Court, Rule 5.125', 'CRC 5.125', 'Duty of Disclosure in Family Law', 'Mandatory disclosure requirements in family law proceedings including income, assets, debts, and expenses.', '["Preliminary Declaration of Disclosure required","Final Declaration of Disclosure required","Continuing duty to update"]', '[{"section":"5.125(a)","description":"Preliminary disclosure requirements"},{"section":"5.125(b)","description":"Final disclosure timing"}]', '["FL-140","FL-142","FL-150","FL-160","disclosure"]', '["california-court-order-compliance-audit"]', 'Superior Court of California', 0, 1, datetime('now'), datetime('now'));

-- California Code of Civil Procedure
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_004', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Code Civ. Proc. § 581d', 'CCP § 581d', 'Written Order Required for Dismissal', 'All dismissals ordered by the court must be in writing and signed by the judge.', '["Dismissal must be in writing","Must be signed by the judge","Filed with the clerk"]', '[{"section":"581d","description":"Written dismissal requirement"}]', '["court_order","dismissal"]', '["california-court-order-compliance-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_005', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Code Civ. Proc. § 1003', 'CCP § 1003', 'Motions and Orders', 'Every direction of a court or judge made or entered in writing and not included in a judgment is an order.', '["Orders must be in writing","Must be distinguishable from judgments"]', '[{"section":"1003","description":"Definition of order vs. judgment"}]', '["court_order","motion"]', '["california-court-order-compliance-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

-- California Family Code
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_006', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 215', 'FC § 215', 'Declaration of Disclosure', 'Both parties in a family law proceeding must exchange declarations of disclosure.', '["Preliminary disclosure within 60 days of filing","Final disclosure before settlement","Continuing duty to update material changes"]', '[{"section":"215(a)","description":"Preliminary Declaration of Disclosure"},{"section":"215(c)","description":"Continuing duty to update"}]', '["FL-140","FL-142","FL-150","disclosure"]', '["california-court-order-compliance-audit","california-family-law-expansion-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_007', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 2010-2013', 'FC §§ 2010-2013', 'Jurisdiction and Venue in Dissolution', 'Requirements for filing dissolution actions including residency and venue.', '["6-month California residency required","3-month county residency required","Jurisdiction established by filing petition"]', '[{"section":"2010","description":"Residency requirements"},{"section":"2011","description":"Venue"},{"section":"2012","description":"Transfer of proceeding"}]', '["FL-100","petition","dissolution"]', '["california-court-order-compliance-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_008', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 3022', 'FC § 3022', 'Best Interest of the Child Standard', 'Court must determine custody in accordance with the best interest of the child.', '["Health, safety, and welfare of child paramount","Frequent and continuing contact with both parents","Consider domestic violence history"]', '[{"section":"3022","description":"Best interest standard"},{"section":"3011","description":"Factors court must consider"}]', '["custody_order","court_order","FL-300","FL-341"]', '["california-court-order-compliance-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_009', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 3044', 'FC § 3044', 'Domestic Violence Presumption Against Custody', 'Rebuttable presumption that awarding custody to a person who committed domestic violence is detrimental to the child.', '["Presumption against custody for DV perpetrator","Must be rebutted by preponderance of evidence","Court must state reasons for rebuttal on the record"]', '[{"section":"3044(a)","description":"Rebuttable presumption"},{"section":"3044(b)","description":"Factors to overcome presumption"}]', '["custody_order","DV-130","DVRO","court_order"]', '["california-court-order-compliance-audit","california-family-law-expansion-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

-- California Housing / Tenant Rights (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_010', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1940-1954.06', 'CC §§ 1940-1954', 'California Tenant Protection Act — Habitability & Rights', 'Comprehensive tenant protections including habitability, security deposits, entry restrictions, and anti-retaliation.', '["Implied warranty of habitability","Security deposit limits (2x rent unfurnished)","24-hour notice for entry","Anti-retaliation protections"]', '[{"section":"1941-1942.5","description":"Habitability standards"},{"section":"1942.4","description":"Rent withholding for substandard conditions"},{"section":"1942.5","description":"Anti-retaliation"},{"section":"1946.2","description":"Just cause eviction (AB 1482)"},{"section":"1950.5","description":"Security deposit rules"}]', '["lease","eviction_notice","security_deposit","habitability_complaint"]', '["california-housing-tenant-rights-audit"]', 'California Department of Consumer Affairs', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_011', 'REGULIS', 'FEDERAL_STATUTE', 'US', '42 USC §§ 3601-3619', 'Fair Housing Act', 'Federal Fair Housing Act', 'Prohibits discrimination in housing based on race, color, religion, sex, familial status, national origin, or disability.', '["No discrimination in sale or rental","No discriminatory advertising","Reasonable accommodations for disability","No retaliation for fair housing complaints"]', '[{"section":"3604","description":"Prohibited discrimination in sale/rental"},{"section":"3605","description":"Discrimination in residential real estate transactions"},{"section":"3617","description":"Interference, coercion, intimidation"}]', '["lease","rental_application","eviction_notice","housing_advertisement"]', '["california-housing-tenant-rights-audit"]', 'HUD / DOJ', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_012', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code § 12955', 'FEHA Housing', 'California Fair Employment and Housing Act — Housing', 'California fair housing protections broader than federal law, adding source of income, sexual orientation, gender identity, and other protected classes.', '["All federal protected classes plus source of income, sexual orientation, gender identity, marital status","Applies to most housing including single-family homes","Source of income includes Section 8 vouchers"]', '[{"section":"12955(a)","description":"Prohibited acts"},{"section":"12955(d)","description":"Source of income discrimination"},{"section":"12955(f)","description":"Reasonable accommodations"}]', '["lease","rental_application","eviction_notice","Section_8_voucher"]', '["california-housing-tenant-rights-audit"]', 'California Civil Rights Department (CRD)', 1, 1, datetime('now'), datetime('now'));

-- California Labor / Employment (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_013', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code §§ 200-244', 'LC §§ 200-244', 'California Wage Payment Laws', 'Requirements for payment of wages including timing, form, and penalties for violations.', '["Wages due semi-monthly","Final wages due immediately upon discharge","Waiting time penalties up to 30 days wages","Itemized wage statements required"]', '[{"section":"201","description":"Final wages on discharge"},{"section":"202","description":"Final wages on quit"},{"section":"203","description":"Waiting time penalties"},{"section":"226","description":"Itemized wage statement"}]', '["pay_stub","termination_letter","wage_claim","employment_contract"]', '["california-labor-employment-audit"]', 'California Labor Commissioner / DLSE', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_014', 'REGULIS', 'FEDERAL_STATUTE', 'US', '29 USC §§ 151-169', 'NLRA', 'National Labor Relations Act', 'Protects rights of employees to organize, bargain collectively, and engage in concerted activity.', '["Right to organize and join unions","Right to bargain collectively","Protection from unfair labor practices","Right to strike and picket"]', '[{"section":"157 (§7)","description":"Employee rights"},{"section":"158 (§8)","description":"Unfair labor practices"},{"section":"159 (§9)","description":"Representatives and elections"}]', '["CBA","grievance","unfair_labor_practice_charge","union_election"]', '["california-labor-employment-audit"]', 'National Labor Relations Board (NLRB)', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_015', 'REGULIS', 'FEDERAL_STATUTE', 'US', '29 USC §§ 1001 et seq.', 'ERISA', 'Employee Retirement Income Security Act', 'Federal law governing employee benefit plans including pension, health, and welfare benefits.', '["Fiduciary duties for plan administrators","Reporting and disclosure requirements","Minimum vesting standards","Claims and appeals procedures"]', '[{"section":"1021-1031","description":"Reporting and disclosure"},{"section":"1101-1114","description":"Fiduciary responsibility"},{"section":"1132","description":"Civil enforcement"}]', '["benefit_plan","SPD","pension_statement","401k_document"]', '["california-labor-employment-audit"]', 'Department of Labor / PBGC', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_016', 'REGULIS', 'FEDERAL_STATUTE', 'US', '29 USC §§ 651 et seq.', 'OSH Act', 'Occupational Safety and Health Act', 'Federal workplace safety standards including general duty clause and specific industry standards.', '["General duty to provide safe workplace","Comply with OSHA standards","Report serious injuries/fatalities","Maintain injury/illness records"]', '[{"section":"654 (§5)","description":"General duty clause"},{"section":"657 (§8)","description":"Inspections"},{"section":"660 (§11)","description":"Judicial review"}]', '["OSHA_log","workplace_injury_report","safety_plan"]', '["california-labor-employment-audit"]', 'OSHA / Cal-OSHA', 1, 1, datetime('now'), datetime('now'));

-- California Real Estate Fraud (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_017', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1102-1102.17', 'CC §§ 1102-1102.17', 'Transfer Disclosure Statement Requirements', 'Mandatory disclosures in residential real estate transactions.', '["Seller must complete TDS","Agent must conduct visual inspection","Buyer right to rescind within 3-5 days of disclosure"]', '[{"section":"1102.1","description":"Properties subject to disclosure"},{"section":"1102.6","description":"TDS form requirements"},{"section":"1102.3","description":"Delivery and rescission rights"}]', '["TDS","real_estate_contract","listing_agreement"]', '["california-real-estate-transaction-fraud-audit"]', 'California Department of Real Estate', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_018', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 760-761, 770, 2550, 2640, 2641', 'FC Community Property', 'Community Property Division in Real Estate', 'Community property presumption and equitable division requirements for real property in dissolution.', '["Community property presumption for acquisitions during marriage","Equal division unless written agreement","Reimbursement for separate property contributions","Fiduciary duty between spouses regarding community assets"]', '[{"section":"760","description":"Community property presumption"},{"section":"2550","description":"Equal division mandate"},{"section":"2640","description":"Separate property reimbursement"},{"section":"1101","description":"Fiduciary duties between spouses"}]', '["deed","title_report","divorce_decree","property_division"]', '["california-real-estate-transaction-fraud-audit","california-family-law-expansion-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

-- California Insurance Bad Faith (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_019', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Ins. Code §§ 790-790.10', 'IC §§ 790-790.10', 'Unfair Claims Settlement Practices', 'Prohibits unfair or deceptive acts by insurers in handling claims.', '["Must acknowledge claims promptly","Must not misrepresent policy provisions","Must attempt fair settlement when liability is clear","Must provide reasonable explanation for denial"]', '[{"section":"790.03(h)","description":"16 prohibited unfair practices"},{"section":"790.06","description":"Cease and desist authority"}]', '["insurance_claim","denial_letter","policy","claim_correspondence"]', '["california-insurance-bad-faith-audit"]', 'California Department of Insurance', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_020', 'REGULIS', 'CASE_LAW', 'CA', 'Egan v. Mutual of Omaha Ins. Co. (1979) 24 Cal.3d 809', 'Egan v. Mutual of Omaha', 'Implied Covenant of Good Faith — Insurance Bad Faith', 'Breach of the implied covenant of good faith and fair dealing by an insurer gives rise to tort damages including emotional distress and punitive damages.', '["Insurer must not unreasonably withhold benefits","Genuine dispute doctrine provides defense","Punitive damages available for willful bad faith"]', '[{"section":"Holding","description":"Tort cause of action for insurance bad faith"},{"section":"Damages","description":"Emotional distress and punitive damages recoverable"}]', '["insurance_claim","bad_faith_complaint","denial_letter"]', '["california-insurance-bad-faith-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- California State Agency Correspondence (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_021', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 11340-11361', 'APA — California', 'California Administrative Procedure Act', 'Governs rulemaking and adjudicative proceedings by state agencies, including notice, hearing, and decision requirements.', '["Notice of proposed rulemaking required","Public comment period","Hearing rights for affected parties","Written decision with findings required"]', '[{"section":"11340.5","description":"Underground regulations prohibited"},{"section":"11346","description":"Rulemaking procedures"},{"section":"11425.10","description":"Administrative adjudication"}]', '["agency_letter","administrative_decision","notice_of_action","hearing_notice"]', '["california-state-agency-correspondence-audit"]', 'Office of Administrative Law', 1, 1, datetime('now'), datetime('now'));

-- CAD Log Compliance (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_022', 'REGULIS', 'PROFESSIONAL_STANDARD', 'US', 'APCO/NENA Standards for 9-1-1 CAD Systems', 'APCO/NENA CAD', 'Public Safety CAD Standards', 'Standards for Computer-Aided Dispatch systems used by emergency services including data entry, timestamps, and retention.', '["Accurate timestamping of all events","Complete narrative entry","Proper unit dispatch coding","Data retention per state law"]', '[{"section":"CAD Data Entry","description":"Standards for entering dispatch information"},{"section":"Timestamps","description":"Accuracy and consistency requirements"},{"section":"Retention","description":"Minimum retention periods"}]', '["CAD_log","dispatch_record","911_call_record","incident_report"]', '["cad-log-compliance-audit"]', 'POST / Local Agency', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_023', 'REGULIS', 'STATE_REGULATION', 'CA', 'Cal. Code Regs. tit. 11, §§ 1001-1126', 'POST Regulations', 'POST Standards for Law Enforcement', 'California Commission on POST standards for law enforcement training, conduct, and documentation.', '["Minimum training standards","Use of force documentation","Report writing standards","Dispatch protocol compliance"]', '[{"section":"1070","description":"Minimum standards for training"},{"section":"1081","description":"Field training requirements"}]', '["police_report","use_of_force_report","training_record","CAD_log"]', '["cad-log-compliance-audit"]', 'Commission on POST', 0, 1, datetime('now'), datetime('now'));

-- California Immigration Rights (REGULIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_024', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 7284-7284.12', 'SB 54 — CA Values Act', 'California Values Act (Sanctuary State)', 'Limits California law enforcement cooperation with federal immigration enforcement.', '["Cannot use resources to investigate, interrogate, detain, or arrest for immigration enforcement","Cannot provide personal information solely for immigration enforcement","Limited exceptions for serious felonies"]', '[{"section":"7284.6","description":"Prohibited cooperation"},{"section":"7284.8","description":"Limited exceptions"},{"section":"7284.10","description":"Reporting requirements"}]', '["ICE_detainer","immigration_hold","police_report"]', '["california-immigration-rights-audit"]', 'California Attorney General', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — Client Advocacy & Market Trust
-- 5 Skills: civil rights, Marsy's Law, CPS/welfare, family law, police
-- ═══════════════════════════════════════════════════════════════════════════

-- Constitutional & Civil Rights
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_001', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. XIV, § 1', '14th Amendment — Due Process', 'Fourteenth Amendment Due Process Clause', 'No state shall deprive any person of life, liberty, or property without due process of law.', '["Procedural due process: notice and opportunity to be heard","Substantive due process: fundamental rights protection","Applies to all state actors including courts, agencies, police"]', '[{"section":"Due Process Clause","description":"State deprivation of life, liberty, or property requires due process"},{"section":"Equal Protection Clause","description":"No denial of equal protection of the laws"}]', '["court_order","agency_action","police_action","custody_order"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts / DOJ', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_002', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC § 1983', '§ 1983', 'Civil Action for Deprivation of Rights Under Color of Law', 'Every person who, under color of state law, deprives another of constitutional rights is liable in an action at law.', '["State actor requirement (color of law)","Deprivation of federal constitutional or statutory right","No qualified immunity for clearly established violations","Municipal liability under Monell for policy or custom"]', '[{"section":"1983","description":"Individual liability for constitutional violations"},{"section":"Monell","description":"Municipal liability for policy/custom/failure to train"}]', '["federal_complaint","1983_complaint","civil_rights_complaint"]', '["constitutional-and-civil-rights-audit"]', 'Federal District Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_003', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. IV', '4th Amendment', 'Fourth Amendment — Unreasonable Search and Seizure', 'Protection against unreasonable searches and seizures; warrants require probable cause.', '["Warrant requirement with exceptions","Probable cause standard","Exclusionary rule for illegally obtained evidence","Applies to persons, houses, papers, and effects"]', '[{"section":"Warrant Clause","description":"Warrants require probable cause and particularity"},{"section":"Reasonableness Clause","description":"All searches and seizures must be reasonable"}]', '["search_warrant","arrest_report","police_report","motion_to_suppress"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_004', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. I', '1st Amendment', 'First Amendment — Speech, Religion, Assembly, Press, Petition', 'Congress shall make no law abridging freedom of speech, religion, press, assembly, or petition.', '["Freedom of speech","Freedom of religion","Freedom of press","Right to peaceably assemble","Right to petition for redress of grievances"]', '[{"section":"Speech Clause","description":"Government cannot restrict protected speech"},{"section":"Petition Clause","description":"Right to petition government including courts"}]', '["court_filing","public_records_request","complaint","petition"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Marsy's Law (ADVOCIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_005', 'ADVOCIS', 'CONSTITUTIONAL', 'CA', 'Cal. Const. art. I, § 28', 'Marsy''s Law', 'California Crime Victims'' Bill of Rights (Marsy''s Law)', 'Constitutional rights of crime victims including notification, participation, restitution, and protection.', '["Right to be heard at any proceeding involving release, plea, sentencing, or parole","Right to notification of all proceedings","Right to restitution from convicted defendant","Right to refuse discovery requests from the defendant","Right to be treated with fairness, respect, and dignity"]', '[{"section":"28(a)","description":"Purpose and findings"},{"section":"28(b)","description":"Enumerated victim rights (17 rights)"},{"section":"28(c)","description":"Standing to assert rights"},{"section":"28(e)","description":"Enforcement mechanisms"}]', '["victim_notification","restitution_order","protective_order","parole_hearing"]', '["marsys-law-victim-rights-audit"]', 'California Victim Compensation Board / District Attorney', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_006', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code §§ 679-679.026', 'PC §§ 679+', 'Victim Rights Implementation Statutes', 'Implementing statutes for Marsy''s Law providing specific procedural requirements for victim notification and participation.', '["Law enforcement must provide Marsy''s Law card at scene","Prosecutors must notify victims of all proceedings","CLETS entries must include victim notification flags","Victims may appear at any hearing"]', '[{"section":"679.02","description":"Rights of victims and witnesses"},{"section":"679.026","description":"Notification requirements"}]', '["police_report","victim_notification","CLETS_entry","court_notice"]', '["marsys-law-victim-rights-audit"]', 'California DOJ / District Attorney', 1, 1, datetime('now'), datetime('now'));

-- CPS / Child Welfare (ADVOCIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_007', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code §§ 300-396', 'WIC § 300+', 'Juvenile Dependency Law', 'Governs dependency proceedings when a child is at risk of abuse, neglect, or abandonment.', '["Petition must specify statutory grounds under §300(a)-(j)","Detention hearing within 48 hours","Jurisdiction hearing within 15 days of detention","Disposition hearing within 10 days of jurisdiction"]', '[{"section":"300","description":"Grounds for dependency jurisdiction"},{"section":"305-309","description":"Detention procedures"},{"section":"315-319","description":"Detention hearings"},{"section":"325-361","description":"Jurisdiction and disposition hearings"}]', '["dependency_petition","detention_report","jurisdiction_report","case_plan"]', '["california-cps-child-welfare-audit"]', 'CDSS / County CWS', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_008', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code §§ 11165-11174.3', 'CANRA', 'Child Abuse and Neglect Reporting Act', 'Mandatory reporting requirements for suspected child abuse or neglect.', '["Mandated reporters must report immediately by phone","Written follow-up within 36 hours","Reports to county welfare or law enforcement","Failure to report is a misdemeanor"]', '[{"section":"11165.7","description":"List of mandated reporters"},{"section":"11166","description":"Duty to report"},{"section":"11167","description":"Content of report"},{"section":"11172","description":"Immunity for reporters / penalties for failure"}]', '["mandated_report","CPS_referral","SCAR_report","cross_report"]', '["california-cps-child-welfare-audit"]', 'CDSS / County CWS / Law Enforcement', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_009', 'ADVOCIS', 'AGENCY_STANDARD', 'CA', 'CDSS Manual of Policies and Procedures, Division 31', 'CDSS MPP Div. 31', 'CDSS Child Welfare Services Manual', 'Comprehensive policies governing county child welfare services operations, investigations, and case management.', '["Investigation protocols and timelines","Safety assessment framework","Case plan requirements","Placement preferences (relative, ICWA compliance)"]', '[{"section":"31-002","description":"Purpose and scope of CWS"},{"section":"31-101","description":"Emergency response referrals"},{"section":"31-110","description":"Investigation procedures"}]', '["CWS_referral","safety_assessment","case_plan","court_report"]', '["california-cps-child-welfare-audit"]', 'CDSS', 0, 1, datetime('now'), datetime('now'));

-- Family Law Expansion (ADVOCIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_010', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 4320-4326', 'FC §§ 4320-4326', 'Spousal Support Factors', 'Factors the court must consider in ordering spousal support including standard of living, earning capacity, and domestic violence.', '["Marital standard of living","Earning capacity of each party","Marketable skills and job market","Domestic violence impact","Tax consequences","Balance of hardships"]', '[{"section":"4320","description":"Permanent support factors (14 enumerated)"},{"section":"4320(i)","description":"Documented history of domestic violence"},{"section":"4325","description":"Conviction of domestic violence — rebuttable presumption against support"},{"section":"4326","description":"Criminal conviction effect on support"}]', '["FL-150","FL-157","spousal_support_order","dissolution_judgment"]', '["california-family-law-expansion-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_011', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 6200-6389', 'DVPA', 'Domestic Violence Prevention Act', 'Comprehensive statutory framework for obtaining restraining orders and protective orders in domestic violence cases.', '["Ex parte TRO available without notice","DV-109 temporary orders","Hearing within 21-25 days","Firearms relinquishment required","CLETS entry mandatory"]', '[{"section":"6300","description":"Grounds for issuance of orders"},{"section":"6320","description":"Orders that may be issued"},{"section":"6340","description":"Duration of orders"},{"section":"6389","description":"Firearms relinquishment"}]', '["DV-100","DV-109","DV-110","DV-130","DVRO","restraining_order"]', '["california-family-law-expansion-audit","marsys-law-victim-rights-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_012', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 2100-2113', 'FC §§ 2100-2113', 'Fiduciary Duties Between Spouses in Dissolution', 'Highest duty of good faith and fair dealing owed between spouses from date of separation through division of assets.', '["Full disclosure of all material facts","Fiduciary duty continues until assets divided","Breach remedies include sanctions, fees, and asset presumptions","Cannot transfer community assets without consent"]', '[{"section":"2100","description":"Legislative findings — duty of highest good faith"},{"section":"2102","description":"Continuing duty of disclosure"},{"section":"2107","description":"Remedies for noncompliance"}]', '["FL-140","FL-142","FL-150","FL-160","property_declaration"]', '["california-family-law-expansion-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

-- Case Law — Family Law (ADVOCIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_013', 'ADVOCIS', 'CASE_LAW', 'CA', 'Marriage of LaMusga (2004) 32 Cal.4th 1072', 'LaMusga', 'Move-Away Cases — Burden of Proof', 'In custody move-away cases, the non-custodial parent bears the initial burden of showing the move would cause detriment to the child.', '["Custodial parent has presumptive right to relocate","Non-custodial parent must show detriment","Court must consider all best interest factors","Changed circumstances standard applies"]', '[{"section":"Holding","description":"Burden on non-custodial parent to show detriment from move"},{"section":"Standard","description":"Changed circumstances plus best interest analysis"}]', '["move_away_motion","custody_modification","declaration"]', '["california-family-law-expansion-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_014', 'ADVOCIS', 'CASE_LAW', 'CA', 'Marriage of Burgess (1996) 13 Cal.4th 25', 'Burgess', 'Custodial Parent Relocation Rights', 'Custodial parent has a presumptive right to change the residence of the child subject to the power of the court to restrain a removal that would prejudice the rights or welfare of the child.', '["Presumptive right to relocate with child","Court must find detriment to deny relocation","Applies to parents with sole or primary physical custody"]', '[{"section":"Holding","description":"Custodial parent presumptive relocation right"},{"section":"Test","description":"Would relocation cause detriment to child?"}]', '["move_away_motion","custody_order","court_order"]', '["california-family-law-expansion-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- Police Report Cross-Reference (ADVOCIS)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_015', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 148.5', 'PC § 148.5', 'False Report of a Crime', 'It is a misdemeanor to file a false police report knowing the report to be false.', '["Filing false report is misdemeanor","Knowing falsity required","Applies to emergency and non-emergency reports"]', '[{"section":"148.5(a)","description":"Filing false report with peace officer"},{"section":"148.5(b)","description":"Filing false report with DA/grand jury"}]', '["police_report","911_call","crime_report"]', '["police-report-data-cross-reference"]', 'District Attorney / Law Enforcement', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_016', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 11116', 'PC § 11116', 'CLETS — California Law Enforcement Telecommunications System', 'Requirements for CLETS entries including protective orders, warrants, and missing persons.', '["Protective orders must be entered within 1 business day","Entries must be accurate and timely","Unauthorized access is a crime","Victims may request verification of entry"]', '[{"section":"11116","description":"CLETS entry requirements"},{"section":"11106","description":"CLETS access and restrictions"}]', '["CLETS_entry","protective_order","DVRO","warrant"]', '["police-report-data-cross-reference","marsys-law-victim-rights-audit"]', 'California DOJ', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ETHICARA — Ethical Governance & Professional Standards
-- 3 Skills: ABPN psychiatry, State Bar attorney conduct, USMC military
-- ═══════════════════════════════════════════════════════════════════════════

-- ABPN / Psychiatry Standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_001', 'ETHICARA', 'PROFESSIONAL_STANDARD', 'US', 'ABPN Certification Standards & MOC Requirements', 'ABPN Standards', 'American Board of Psychiatry & Neurology Certification', 'Board certification and maintenance of certification requirements for psychiatrists and neurologists.', '["Initial certification examination","Continuing certification (MOC) every 10 years","Self-assessment activities","Improvement in medical practice activities"]', '[{"section":"Initial Certification","description":"Training and examination requirements"},{"section":"Continuing Certification","description":"MOC components: professionalism, self-assessment, cognitive expertise, practice improvement"}]', '["board_certification","MOC_record","CME_record","practice_improvement"]', '["abpn-psychiatry-and-neurology-standards-audit"]', 'ABPN', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_002', 'ETHICARA', 'PROFESSIONAL_STANDARD', 'US', 'APA Principles of Medical Ethics With Annotations Especially Applicable to Psychiatry', 'APA Ethics', 'APA Psychiatric Ethics Principles', 'Professional ethics standards for psychiatrists covering confidentiality, informed consent, dual relationships, and expert testimony.', '["Competence in area of practice","Confidentiality of patient information","Informed consent for treatment","Honesty in expert testimony","No exploitation of therapeutic relationship"]', '[{"section":"Section 1","description":"Patient welfare is primary"},{"section":"Section 4","description":"Confidentiality"},{"section":"Section 5","description":"Expert testimony standards"},{"section":"Section 7","description":"Professional development"}]', '["psychiatric_evaluation","forensic_report","expert_declaration","treatment_record"]', '["abpn-psychiatry-and-neurology-standards-audit"]', 'APA / State Medical Board', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_003', 'ETHICARA', 'PROFESSIONAL_STANDARD', 'US', 'AAPL Ethics Guidelines for the Practice of Forensic Psychiatry (2005, rev. 2015)', 'AAPL Guidelines', 'Forensic Psychiatry Ethics Guidelines', 'Ethics guidelines specific to forensic psychiatric practice including objectivity, informed consent, and dual roles.', '["Objectivity and honesty in opinions","Disclose limitations of evaluation","Distinguish forensic from therapeutic role","Obtain informed consent or notify of non-confidentiality","Base opinions on adequate data"]', '[{"section":"Confidentiality","description":"Notify evaluee of non-confidential nature"},{"section":"Consent","description":"Informed consent in forensic settings"},{"section":"Honesty and Striving for Objectivity","description":"Honest opinions regardless of retaining party"},{"section":"Qualifications","description":"Only practice in areas of expertise"}]', '["forensic_evaluation","730_evaluation","competency_evaluation","expert_testimony"]', '["abpn-psychiatry-and-neurology-standards-audit"]', 'AAPL / State Medical Board', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_004', 'ETHICARA', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 2000-2529 (Medical Practice Act)', 'B&P Medical Practice Act', 'California Medical Practice Act', 'Governs medical licensure, practice standards, and discipline in California.', '["License required to practice medicine","Standard of care compliance","Reporting requirements for malpractice","Grounds for discipline including incompetence, dishonesty, unprofessional conduct"]', '[{"section":"2234","description":"Unprofessional conduct grounds for discipline"},{"section":"2234.1","description":"Excessive prescribing"},{"section":"2261","description":"Fraud in obtaining license"},{"section":"2220.05","description":"Recommended guidelines for prescribing"}]', '["medical_license","disciplinary_action","malpractice_report","CME_record"]', '["abpn-psychiatry-and-neurology-standards-audit"]', 'Medical Board of California', 1, 1, datetime('now'), datetime('now'));

-- State Bar Attorney Conduct (ETHICARA)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_005', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct (2018)', 'CA RPC', 'California Rules of Professional Conduct', 'Ethical rules governing California-licensed attorneys including competence, confidentiality, conflicts of interest, and client funds.', '["Competence required (Rule 1.1)","Confidentiality of information (Rule 1.6)","Conflict of interest rules (Rules 1.7-1.12)","Client fund handling (Rule 1.15)","Truthfulness to tribunals (Rule 3.3)","Fairness to opposing parties (Rule 3.4)"]', '[{"section":"Rule 1.1","description":"Competence"},{"section":"Rule 1.4","description":"Communication with clients"},{"section":"Rule 1.6","description":"Confidentiality"},{"section":"Rule 1.7","description":"Conflict of interest — current clients"},{"section":"Rule 3.3","description":"Candor toward the tribunal"},{"section":"Rule 8.4","description":"Misconduct"}]', '["attorney_conduct","bar_complaint","OCTC_investigation","disciplinary_proceeding"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_006', 'ETHICARA', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 6000-6238 (State Bar Act)', 'State Bar Act', 'California State Bar Act', 'Statutory framework governing the State Bar, attorney licensing, discipline, and the Client Security Fund.', '["Bar membership required to practice law","Trust account compliance","Reporting requirements for discipline","Client Security Fund claims"]', '[{"section":"6068","description":"Duties of attorneys"},{"section":"6103","description":"Contempt for violation of duty"},{"section":"6106","description":"Moral turpitude and dishonesty"},{"section":"6125","description":"Unauthorized practice of law"}]', '["bar_membership","trust_account","disciplinary_record","client_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California / Supreme Court', 1, 1, datetime('now'), datetime('now'));

-- USMC Military Standards (ETHICARA)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_007', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 U.S.C. Chapter 47 (UCMJ)', 'UCMJ', 'Uniform Code of Military Justice', 'Federal law governing military criminal justice including offenses, courts-martial, and punitive articles.', '["Punitive articles (Articles 77-134)","Non-judicial punishment (Article 15)","Courts-martial procedures","Appellate review rights"]', '[{"section":"Article 15","description":"Non-judicial punishment"},{"section":"Article 31","description":"Rights of accused (Miranda equivalent)"},{"section":"Article 32","description":"Preliminary hearing"},{"section":"Article 120","description":"Sexual assault offenses"},{"section":"Article 134","description":"General article (conduct prejudicial to good order)"}]', '["court_martial","NJP","charge_sheet","SRB"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_008', 'ETHICARA', 'MILITARY_STANDARD', 'US', 'Manual for Courts-Martial, United States (MCM)', 'MCM', 'Manual for Courts-Martial', 'Comprehensive manual prescribing rules of evidence, procedures, and punishments for military courts-martial.', '["Rules for Courts-Martial (RCM)","Military Rules of Evidence (MRE)","Maximum punishments for each offense","Post-trial procedures and appellate rights"]', '[{"section":"RCM 100-199","description":"General provisions and jurisdiction"},{"section":"RCM 300-399","description":"Preferral and referral of charges"},{"section":"MRE 300-399","description":"Privileges and self-incrimination"},{"section":"RCM 1000-1199","description":"Post-trial procedure"}]', '["court_martial","charge_sheet","trial_record","clemency"]', '["usmc-military-standards-audit"]', 'Secretary of the Navy / JAGC', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_009', 'ETHICARA', 'MILITARY_STANDARD', 'US', 'Marine Corps Manual (MCM) / Marine Corps Orders', 'MCO Series', 'Marine Corps Orders and Regulations', 'Service-specific regulations governing Marines including administrative separation, fitness reports, and conduct standards.', '["Administrative separation procedures (MARCORSEPMAN)","Fitness report system (IRAM)","Equal opportunity and harassment policies","Inspector General complaint procedures"]', '[{"section":"MARCORSEPMAN","description":"Administrative separation manual"},{"section":"MCO 1610","description":"Performance evaluation system"},{"section":"MCO 5354","description":"Equal opportunity manual"},{"section":"MCO 5370","description":"Inspector General system"}]', '["fitness_report","SRB","admin_sep_board","IG_complaint","EO_complaint"]', '["usmc-military-standards-audit"]', 'CMC / HQMC', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — Financial Strategy & Fiscal Accountability
-- 2 Skills: banking/financial docs, FCRA/ChexSystems
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_001', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1681-1681x', 'FCRA', 'Fair Credit Reporting Act', 'Comprehensive federal law governing consumer reporting agencies, accuracy of consumer reports, and consumer rights.', '["Consumer reporting agencies must follow reasonable procedures for accuracy","Furnishers must investigate disputes within 30 days","Consumers entitled to free annual report","Obsolete information restrictions (7/10 year rules)","Permissible purpose required for pulling reports"]', '[{"section":"1681b","description":"Permissible purposes for consumer reports"},{"section":"1681e(b)","description":"Accuracy of consumer reports"},{"section":"1681g","description":"Consumer disclosure rights"},{"section":"1681i","description":"Procedure for disputed information"},{"section":"1681n","description":"Civil liability — willful noncompliance"},{"section":"1681o","description":"Civil liability — negligent noncompliance"}]', '["credit_report","consumer_dispute","furnisher_response","adverse_action_notice"]', '["fcra-chexsystems-consumer-report-audit","banking-financial-document-audit"]', 'CFPB / FTC', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_002', 'FISCARA', 'FEDERAL_REGULATION', 'US', '12 CFR Part 1022 (Regulation V)', 'Reg V', 'Regulation V — Fair Credit Reporting', 'CFPB implementing regulation for FCRA covering accuracy, dispute resolution, and identity theft procedures.', '["Reasonable investigation of disputes","Accuracy and integrity of furnished information","Identity theft procedures","Risk-based pricing notices"]', '[{"section":"1022.41","description":"Accuracy and integrity of information"},{"section":"1022.42","description":"Reasonable investigation of disputes"},{"section":"1022.43","description":"Direct disputes with furnishers"}]', '["dispute_investigation","furnisher_policy","identity_theft_report"]', '["fcra-chexsystems-consumer-report-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_003', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1785.1-1785.36', 'CCRAA', 'California Consumer Credit Reporting Agencies Act', 'California analog to FCRA with additional consumer protections.', '["Broader definition of consumer report","Security freeze rights","Identity theft victim protections","Additional accuracy requirements beyond FCRA"]', '[{"section":"1785.15","description":"Consumer right to information"},{"section":"1785.16","description":"Dispute procedures"},{"section":"1785.25","description":"Accuracy requirements"},{"section":"1785.31","description":"Civil penalties"}]', '["credit_report","consumer_dispute","identity_theft","security_freeze"]', '["fcra-chexsystems-consumer-report-audit"]', 'California Attorney General / CRD', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_004', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1601-1667f', 'TILA', 'Truth in Lending Act', 'Federal disclosure requirements for consumer credit transactions including APR, finance charges, and right of rescission.', '["Clear disclosure of APR and finance charges","Right of rescission for certain transactions","Standardized disclosure format","Advertising regulations"]', '[{"section":"1631","description":"Disclosure requirements"},{"section":"1635","description":"Right of rescission"},{"section":"1640","description":"Civil liability for violations"}]', '["loan_agreement","mortgage_disclosure","credit_card_agreement","TILA_disclosure"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_005', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC §§ 2601-2617', 'RESPA', 'Real Estate Settlement Procedures Act', 'Federal law governing disclosures in real estate settlements, prohibiting kickbacks, and limiting escrow deposits.', '["Good faith estimate of settlement costs","HUD-1 settlement statement","Prohibition on kickbacks and referral fees","Escrow account limits"]', '[{"section":"2603","description":"Settlement statement requirements"},{"section":"2607","description":"Prohibition of kickbacks"},{"section":"2609","description":"Escrow account limits"}]', '["HUD-1","closing_disclosure","settlement_statement","escrow_analysis"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_006', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1692-1692p', 'FDCPA', 'Fair Debt Collection Practices Act', 'Federal law regulating third-party debt collectors including prohibited practices and consumer rights.', '["Validation notice within 5 days of initial contact","Cease and desist rights","No harassment, abuse, or deceptive practices","No communication at inconvenient times/places"]', '[{"section":"1692c","description":"Communication restrictions"},{"section":"1692d","description":"Harassment or abuse"},{"section":"1692e","description":"False or misleading representations"},{"section":"1692f","description":"Unfair practices"},{"section":"1692g","description":"Validation of debts"}]', '["collection_letter","debt_validation","cease_and_desist","collection_complaint"]', '["banking-financial-document-audit"]', 'CFPB / FTC', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_007', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1788-1788.33', 'Rosenthal Act', 'Rosenthal Fair Debt Collection Practices Act', 'California supplement to FDCPA that applies to original creditors in addition to third-party collectors.', '["Applies to original creditors (broader than FDCPA)","Same prohibited practices as FDCPA","Additional state remedies available","Can be combined with FDCPA claims"]', '[{"section":"1788.11","description":"Unfair or deceptive acts"},{"section":"1788.12","description":"Threats and coercion"},{"section":"1788.13","description":"Unfair and misleading practices"},{"section":"1788.17","description":"FDCPA incorporated by reference"}]', '["collection_letter","debt_validation","original_creditor_communication"]', '["banking-financial-document-audit"]', 'California Attorney General', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FACIALEX — Forensic Facial Examination & Photo Comparison
-- 1 Skill: forensic photo comparison
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_001', 'FACIALEX', 'PROFESSIONAL_STANDARD', 'US', 'FBI/FISWG Facial Identification Scientific Working Group Standards', 'FISWG Standards', 'Facial Identification Standards', 'Scientific standards for facial comparison and identification used in forensic analysis.', '["Morphological analysis methodology","Comparison conclusions must be categorized","Quality assessment of images required","Documentation of analysis process"]', '[{"section":"Methodology","description":"ACE-V process (Analysis, Comparison, Evaluation, Verification)"},{"section":"Conclusions","description":"Identification, exclusion, inconclusive"},{"section":"Documentation","description":"Case notes and image quality assessment"}]', '["forensic_photo_comparison","facial_identification","photo_evidence"]', '["forensic-photo-comparison-audit"]', 'FBI / FISWG', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, enforcement_url, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_002', 'FACIALEX', 'CASE_LAW', 'US', 'Daubert v. Merrell Dow Pharmaceuticals (1993) 509 U.S. 579', 'Daubert', 'Expert Testimony Admissibility Standard', 'Federal standard for admissibility of expert testimony requiring reliability, relevance, and scientific methodology.', '["Testimony must be based on sufficient facts or data","Product of reliable principles and methods","Expert reliably applied principles to the facts","Trial court is gatekeeper for expert testimony"]', '[{"section":"Reliability factors","description":"Testing, peer review, error rate, general acceptance"},{"section":"Relevance","description":"Must assist trier of fact"},{"section":"Gatekeeper role","description":"Judge evaluates methodology, not conclusions"}]', '["expert_declaration","forensic_report","motion_to_exclude","Daubert_motion"]', '["forensic-photo-comparison-audit","abpn-psychiatry-and-neurology-standards-audit"]', 'Federal Courts', NULL, 1, 1, datetime('now'), datetime('now'));
