-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 21
-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS family law deep-dive: custody factors, best interest, DV
-- presumption, supervised visitation, custody evaluation, mediation,
-- UCCJEA, community property, child support, fiduciary duties.
-- CPS/dependency: jurisdiction, protective custody, detention, removal,
-- review hearings, permanency planning.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — Family Law: Custody and Best Interest
-- ═══════════════════════════════════════════════════════════════════════════

-- Best Interest of the Child
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_057', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 3020-3049 (Best Interest of the Child)', 'FC §§ 3020-3049', 'Best Interest of the Child — Custody Determination Factors', 'California custody law prioritizes the health, safety, and welfare of the child and frequent and continuing contact with both parents. Court must consider all relevant factors including history of abuse by either parent. Legislative policy: children benefit from frequent and continuing contact with both parents, and both parents share rights and responsibilities. DV history is a factor (§ 3020(a)).', '["Health, safety, and welfare of child is paramount (§ 3020)","Frequent and continuing contact with both parents preferred (§ 3020(b))","No preference based on sex of parent (§ 3040)","Court may consider habitual or continual illegal use of controlled substances (§ 3041.5)","Court must consider history of abuse by either parent (§ 3020(a))","Best interest considers: nature and amount of contact, age of child, parental stability","Court must state reasons for custody order if requested (§ 3048)","Friendly parent factor: willingness to facilitate contact with other parent","No presumption for or against joint or sole custody except DV (§ 3040)"]', '[{"section":"3020(a)","description":"Health, safety, welfare paramount; DV history as factor"},{"section":"3020(b)","description":"Frequent and continuing contact with both parents"},{"section":"3040","description":"Order of preference — both parents before third parties, no sex preference"},{"section":"3040(a)(1)","description":"Joint custody to both parents"},{"section":"3040(a)(2)","description":"Sole custody to either parent"},{"section":"3040(a)(3)","description":"Custody to other person — requires finding by clear and convincing evidence"},{"section":"3041.5","description":"Illegal drug use as factor"},{"section":"3048","description":"Statement of reasons for custody order on request"}]', '["custody_order","FL_300","FL_311","custody_declaration","best_interest_analysis","parenting_plan","visitation_schedule"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- DV Rebuttable Presumption
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_058', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 3044 (DV Rebuttable Presumption Against Custody)', 'FC § 3044', 'Domestic Violence Rebuttable Presumption Against Custody', 'Creates rebuttable presumption that it is detrimental to the best interest of the child to award sole or joint physical or legal custody to a person who has perpetrated domestic violence within the previous 5 years. Perpetrator must overcome presumption by preponderance of evidence showing factors in § 3044(b). Finding of DV is required, not merely allegation.', '["Rebuttable presumption against custody to DV perpetrator","Applies to DV within previous 5 years","Finding of DV required — judicial finding, not mere allegation","Must be overcome by preponderance of evidence","Factors to overcome: completion of batterer treatment program, compliance with probation/parole, completion of substance abuse program, compliance with restraining orders, 12-step or domestic violence treatment program","Court must state reasons in writing or on the record if overcoming presumption","Applies to both physical and legal custody — sole and joint","Does not create presumption in favor of other parent — best interest still governs"]', '[{"section":"3044(a)","description":"Rebuttable presumption against DV perpetrator for custody"},{"section":"3044(b)","description":"Factors to overcome presumption — 7 considerations"},{"section":"3044(b)(1)","description":"Completion of batterer intervention program"},{"section":"3044(b)(2)","description":"Compliance with probation or parole terms"},{"section":"3044(b)(3)","description":"Compliance with restraining order terms"},{"section":"3044(b)(5)","description":"Best interest of the child"},{"section":"3044(c)","description":"Written or oral statement of reasons if presumption overcome"},{"section":"3044(d)","description":"Definition — perpetrated domestic violence as judicial finding"}]', '["DV_finding","custody_order","batterer_treatment_completion","restraining_order_compliance","FL_300","FL_312","custody_evaluation"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Supervised Visitation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_059', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 3100-3105 (Supervised Visitation)', 'FC §§ 3100-3105', 'Supervised Visitation — Professional and Nonprofessional Monitors', 'Court may order supervised visitation when necessary to protect child. Professional monitors must meet Uniform Standards of Practice (FC § 3200.5). Court must consider nature of allegations, relationship between child and parent, and impact of supervision on child. Third-party professional supervised visitation providers must be registered with local court.', '["Court may order supervised visitation to protect child safety","Professional monitors must meet Uniform Standards (FC 3200.5)","Nonprofessional monitors selected by agreement or court order","Monitor must have no record of DV, child abuse, or substance abuse","Court must specify conditions: location, duration, cost allocation","Cost of supervision allocated between parties based on ability to pay","Report of any safety concerns required from monitor","Court must consider least restrictive means consistent with child safety","Grandparent or stepparent visitation subject to § 3100-3105"]', '[{"section":"3100","description":"Court authority to grant reasonable visitation"},{"section":"3100(a)","description":"Supervised visitation when necessary for child safety"},{"section":"3100(b)","description":"Grandparent/stepparent visitation rights"},{"section":"3102","description":"Visitation after death of custodial parent"},{"section":"3103","description":"Grandparent visitation when parents in dispute"},{"section":"3104","description":"Grandparent petition in certain circumstances"},{"section":"3105","description":"Court authority over visitation conditions"}]', '["visitation_order","supervised_visitation_order","monitor_report","FL_311","FL_341(d)","professional_monitor_registration","safety_concern_report"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Custody Evaluation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_060', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 3110-3118 (Child Custody Evaluation)', 'FC §§ 3110-3118', 'Child Custody Evaluation — Court-Appointed and Private Evaluators', 'Court may appoint evaluator to investigate and report on custody or visitation issues. Evaluator must meet qualifications per CRC 5.220. Parties entitled to cross-examine evaluator at hearing. Report must include methodology, sources of information, and basis for recommendations. Evaluator must disclose potential bias and conflicts.', '["Court may appoint evaluator sua sponte or on motion","Evaluator must meet qualifications — CRC 5.220 (education, training, experience)","Must interview both parents, children, and relevant third parties","Must consider all relevant factors including DV history","Report must include methodology, sources, and basis for recommendations","Parties have right to cross-examine evaluator at hearing","Evaluator must disclose conflicts of interest and potential bias","Cost allocated between parties based on ability to pay","Report generally confidential but available to parties and counsel","Private evaluators (§ 3111) must meet same standards"]', '[{"section":"3110","description":"Court authority to appoint evaluator"},{"section":"3111","description":"Private child custody evaluator — qualifications"},{"section":"3111.5","description":"Domestic violence training requirements for evaluators"},{"section":"3112","description":"Court to consider report — not bound by recommendation"},{"section":"3113","description":"Confidentiality of evaluation and report"},{"section":"3116","description":"Evaluator must consider child safety first"},{"section":"3118","description":"Standards for evaluators — CRC 5.220"}]', '["custody_evaluation_report","evaluator_appointment_order","FL_327","cross_examination_of_evaluator","evaluator_qualifications","conflict_disclosure","CRC_5.220_compliance"]', '["family-law-custody-audit","fcs-child-custody-recommending-counselor-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Custody Mediation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_061', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 3160-3186 (Custody Mediation)', 'FC §§ 3160-3186', 'Mandatory Custody Mediation — Family Court Services', 'Mediation required before contested custody hearing. Each superior court maintains FCS (Family Court Services) or contracts for mediation. Mediator meets with both parents (separately if DV issues). Some counties are "recommending" (mediator files recommendation with court) and others are "non-recommending" (confidential). DV screening required.', '["Mandatory mediation before contested custody hearing (§ 3170)","Court may waive mediation for good cause (§ 3170(b))","Mediator must screen for DV at outset (§ 3181)","DV victim may meet separately from perpetrator (§ 3181(b))","Support person may attend with DV victim (§ 3181(c))","Recommending vs non-recommending counties — varies by local court","Mediator recommendations (if recommending county) filed with court","Parties may bring counsel to mediation in certain circumstances","Mediator has mandatory reporting duties for child abuse","Agreement reached in mediation must be approved by court"]', '[{"section":"3160","description":"Purpose — reduce acrimony, protect child best interests"},{"section":"3161","description":"Duties of mediator — impartial, focused on best interests"},{"section":"3170","description":"Mandatory mediation before contested custody hearing"},{"section":"3175","description":"Mediator recommendation — recommending counties"},{"section":"3177","description":"Separate meetings for DV cases"},{"section":"3181","description":"DV screening requirements"},{"section":"3182","description":"Referral to other services if agreement not reached"},{"section":"3186","description":"Privilege and confidentiality of mediation communications"}]', '["mediation_appointment","FCS_recommendation","custody_agreement","DV_screening_form","FL_300","mediation_declaration","mediator_recommendation_report"]', '["family-law-custody-audit","fcs-child-custody-recommending-counselor-audit"]', 'California Family Court Services', 0, 1, datetime('now'), datetime('now'));

-- UCCJEA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_062', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 3400-3465 (UCCJEA — Uniform Child Custody Jurisdiction and Enforcement Act)', 'FC §§ 3400-3465 / UCCJEA', 'UCCJEA — Jurisdiction for Child Custody Determinations', 'Determines which state has jurisdiction to make initial or modify custody determinations. Home state jurisdiction is primary basis: state where child lived with parent for 6 consecutive months before proceeding. Prevents forum shopping. Exclusive continuing jurisdiction remains in original state until all parties leave or court declines. Emergency jurisdiction for immediate protection.', '["Home state has priority jurisdiction — 6 months continuous residence (§ 3421(a)(1))","Significant connection jurisdiction if no home state (§ 3421(a)(2))","Exclusive continuing jurisdiction until all parties leave or court declines (§ 3422)","Temporary emergency jurisdiction to protect child or sibling (§ 3424)","Court must communicate with courts of other states before exercising jurisdiction (§ 3410)","Inconvenient forum — court may decline jurisdiction (§ 3427)","Unjustifiable conduct — court must decline jurisdiction if party engaged in misconduct (§ 3428)","UCCJEA declaration required in first custody pleading (§ 3409)","Enforcement of other state custody orders — registration procedure (§ 3444-3461)"]', '[{"section":"3421(a)(1)","description":"Home state jurisdiction — 6 months continuous residence"},{"section":"3421(a)(2)","description":"Significant connection jurisdiction"},{"section":"3422","description":"Exclusive continuing jurisdiction"},{"section":"3424","description":"Temporary emergency jurisdiction"},{"section":"3427","description":"Inconvenient forum — may decline"},{"section":"3428","description":"Unjustifiable conduct — must decline"},{"section":"3409","description":"UCCJEA declaration required in first pleading"},{"section":"3444-3461","description":"Registration and enforcement of out-of-state orders"}]', '["UCCJEA_declaration","FL_105","custody_petition","jurisdictional_motion","interstate_communication_order","registration_of_foreign_order","emergency_custody_petition"]', '["family-law-custody-audit"]', 'California Family Courts / Interstate Coordination', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — Family Law: Financial and Support
-- ═══════════════════════════════════════════════════════════════════════════

-- Community Property Division
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_063', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 2550-2556 (Community Property Division)', 'FC §§ 2550-2556', 'Community Property Division — Equal Division Requirement', 'Court must divide community estate equally (§ 2550). May divide in kind or by assigning values and offsetting. Deliberate misappropriation triggers sanctions (§ 2602). Undisclosed assets may be awarded 100% to other spouse (§ 2556). Date of separation determines community vs separate property. Fiduciary duties continue until distribution.', '["Equal division of community estate required (§ 2550)","Court may divide in kind or by offsetting values","Deliberate misappropriation: court may add breach amount to other side (§ 2602)","Undisclosed community assets may be awarded 100% to other spouse (§ 2556)","Date of separation determines character of property (§ 70)","Quasi-community property divided same as community property (§ 2550)","Debts divided equally except where assignment would be unjust (§ 2551)","Education/training loans assigned to benefited spouse (§ 2641)","Personal injury awards to injured spouse unless justice requires otherwise (§ 2603)"]', '[{"section":"2550","description":"Equal division requirement — community and quasi-community"},{"section":"2551","description":"Characterization of liabilities — equal assignment"},{"section":"2552","description":"Valuation date — trial or agreement"},{"section":"2553","description":"Division by referee or expert"},{"section":"2555","description":"Bifurcation — reserve jurisdiction over property"},{"section":"2556","description":"Undisclosed assets — penalty of 100% to other spouse"},{"section":"2602","description":"Deliberate misappropriation — breach remedies"},{"section":"2603","description":"Personal injury award disposition"}]', '["FL_142","FL_150","FL_160","property_declaration","QDRO","pension_division","judgment","asset_disclosure"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Child Support Guidelines
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_064', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 4050-4076 (Child Support Guidelines)', 'FC §§ 4050-4076', 'California Guideline Child Support — Algebraic Formula', 'Mandatory statewide guideline formula: CS = K[HN - (H%)(TN)]. K factor based on custodial time; HN = high earner net disposable income; TN = total net disposable income. Presumptively correct amount. May deviate only on specific findings on the record. Income includes all sources: salary, commissions, bonuses, rental, investment, social security.', '["Guideline formula: CS = K[HN - (H%)(TN)] (§ 4055)","K = 1 + H% (if H% < 50%) or 2 - 2(H%) (if H% > 50%)","Net disposable income includes all sources of income (§ 4058)","Deductions: taxes, mandatory retirement, health insurance, union dues, hardship (§ 4059)","Guideline amount is presumptively correct (§ 4057)","Deviation only on specific findings — written or on record (§ 4056)","Both parents obligated to support (§ 4053(e))","Income from new spouse not considered (§ 4057.5)","Add-on expenses: childcare for employment, health insurance, education, travel (§ 4062)","Court may impute income if parent voluntarily unemployed/underemployed (§ 4058(b))"]', '[{"section":"4050","description":"Legislative intent — adequate support, both parents share"},{"section":"4053","description":"Principles — both parents responsible, guideline presumptively correct"},{"section":"4055","description":"Guideline formula — algebraic calculation"},{"section":"4056","description":"Deviation — specific findings required on record"},{"section":"4057","description":"Presumption — rebuttal only by § 4057(b) factors"},{"section":"4058","description":"Income defined — all sources"},{"section":"4059-4060","description":"Deductions from gross income"},{"section":"4062","description":"Add-on expenses — childcare, health, education, travel"}]', '["FL_150","FL_155","FL_342","child_support_order","DissoMaster_printout","income_and_expense_declaration","W2_tax_returns","support_modification"]', '["family-law-custody-audit"]', 'California Family Courts / DCSS', 1, 1, datetime('now'), datetime('now'));

-- Fiduciary Duties in Dissolution
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_065', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code §§ 721, 1100, 2100-2113 (Fiduciary Duties in Marriage/Dissolution)', 'FC §§ 721/1100/2100-2113', 'Fiduciary Duties Between Spouses — During Marriage and Dissolution', 'Spouses owe each other fiduciary duties of highest good faith and fair dealing — same as business partners. Duty continues through dissolution until final distribution. Includes duty of full disclosure of all assets, debts, income, and expenses. Breach remedies include sanctions under § 271, asset penalty under § 2107, and tort damages. Automatic Temporary Restraining Orders (ATROs) preserve status quo.', '["Spouses owe fiduciary duties of highest good faith — same as business partners (§ 721)","Duty of full disclosure of all community and separate property (§ 2100)","Preliminary Declaration of Disclosure required (§ 2104) — FL-140/FL-142","Final Declaration of Disclosure required (§ 2105) — FL-141","Cannot transfer, encumber, conceal, or dispose of community property without consent (§ 1100)","ATROs: automatic restraining orders preventing asset dissipation (§ 2040)","Breach: court may award 50-100% of undisclosed asset to other spouse (§ 2107(d))","Sanctions under § 271 for breach of fiduciary duty or litigation misconduct","Duty continues until final distribution of community estate"]', '[{"section":"721(b)","description":"Fiduciary duties between spouses — highest good faith"},{"section":"1100(e)","description":"Written consent for disposition of community property"},{"section":"2100","description":"Duty of full disclosure in dissolution proceedings"},{"section":"2104","description":"Preliminary Declaration of Disclosure — FL-140"},{"section":"2105","description":"Final Declaration of Disclosure — FL-141"},{"section":"2107(d)","description":"Penalty for nondisclosure — 50-100% of undisclosed asset"},{"section":"2040","description":"ATROs — automatic temporary restraining orders"},{"section":"271","description":"Sanctions for breach of fiduciary duty or litigation misconduct"}]', '["FL_140","FL_141","FL_142","FL_150","ATRO_summons","asset_disclosure","breach_of_fiduciary_duty_motion","sanctions_motion"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Sanctions for Litigation Misconduct
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_066', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Fam. Code § 271 (Sanctions for Litigation Misconduct)', 'FC § 271', 'Family Law Sanctions — Frustrating Settlement and Cooperation', 'Court may impose attorney fee sanctions against party or counsel who frustrates settlement or increases litigation costs through uncooperative conduct. Based on furtherance of policy favoring settlement and reduction of litigation costs. Amount may be full attorney fees of other side. Not limited to ability to pay — sanction may exceed ability. Conduct-based, not need-based.', '["Sanctions for conduct that frustrates settlement policy","Applies to party or attorney","Based on extent to which conduct frustrates cooperation","Amount: proportional to bad conduct, may include full attorney fees","Not limited by ability to pay — distinguishes from need-based fees","Court considers all circumstances including nature, persistence of bad conduct","May be imposed at any time during proceedings","Written findings required","Appeal available — abuse of discretion standard","Cannot be used punitively — must relate to settlement frustration"]', '[{"section":"271(a)","description":"Authority to award fees as sanction for frustrating settlement"},{"section":"271(b)","description":"Amount — based on incomes, assets, liabilities"},{"section":"271(c)","description":"Court order must be in writing with reasons stated"},{"section":"271(d)","description":"Sanction is enforceable as money judgment"}]', '["sanctions_motion","FC_271_brief","attorney_fee_declaration","order_on_sanctions","judgment","misconduct_evidence"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — CPS/Dependency: WIC 300 Series
-- ═══════════════════════════════════════════════════════════════════════════

-- WIC 300 — Dependency Jurisdiction
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_067', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 300 (Dependency Jurisdiction)', 'WIC § 300', 'Juvenile Dependency Jurisdiction — Grounds for Court Intervention', 'Defines grounds for juvenile court dependency jurisdiction over children who have suffered or are at substantial risk of suffering serious physical harm. Eleven subdivisions covering neglect, physical abuse, sexual abuse, emotional abuse, and parental incapacity. Must prove by preponderance of evidence at jurisdictional hearing.', '["(a) Serious physical harm inflicted nonaccidentally by parent","(b) Failure to protect — serious physical harm or illness due to parent inability to supervise/protect","(c) Serious emotional damage — no parent willing to provide treatment","(d) Sexual abuse or at substantial risk of sexual abuse","(e) Severe physical abuse under age 5 — as defined in PC 11165.4","(f) Parent caused death of another child through abuse/neglect","(g) Sibling has been abused/neglected as defined in (a)-(j)","(h) Left without provision for support (abandonment)","(i) Cruelty — acts of cruelty by parent","(j) Substantial risk that child will be sexually abused — as defined in PC 11165.1","Proved by preponderance of evidence at jurisdictional hearing"]', '[{"section":"300(a)","description":"Serious physical harm — nonaccidental"},{"section":"300(b)(1)","description":"Failure to protect — neglect, inability to supervise"},{"section":"300(c)","description":"Serious emotional damage"},{"section":"300(d)","description":"Sexual abuse or risk thereof"},{"section":"300(e)","description":"Severe physical abuse — child under 5"},{"section":"300(f)","description":"Parent caused death of another child"},{"section":"300(g)","description":"Sibling abuse/neglect"},{"section":"300(h)","description":"Abandonment — left without provision"},{"section":"300(i)","description":"Cruelty by parent"},{"section":"300(j)","description":"Risk of sexual abuse"}]', '["dependency_petition","JV_100","jurisdictional_hearing_report","social_study","dispositional_report","CPS_referral"]', '["cps-dependency-family-reunification-audit"]', 'Juvenile Court / County CPS (DCFS)', 0, 1, datetime('now'), datetime('now'));

-- WIC 305 — Protective Custody
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_068', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 305 (Protective Custody Without Warrant)', 'WIC § 305', 'Protective Custody — Emergency Removal Without Warrant', 'Social worker or law enforcement may take child into temporary custody without warrant when reasonable cause to believe child is in immediate danger. Must immediately investigate, attempt to maintain child in home with services, and file petition within 48 hours if child is detained. Preference for placement with relative. Child must be released to parent unless continued danger.', '["May take temporary custody without warrant if immediate danger (§ 305)","Must immediately investigate and attempt services to keep child in home","Must release to parent unless continued danger","If detained, must file petition within 48 hours (§ 313)","Preference for placement with relative (§ 309)","Must make reasonable efforts to prevent removal (§ 306)","Must immediately notify parent of removal and rights","Must advise parent of right to counsel","Social worker must complete detention report for court","ICWA inquiry required if child may be Indian child (§ 224.2)"]', '[{"section":"305(a)","description":"Authority — peace officer or social worker may take temporary custody"},{"section":"305(b)","description":"Notification requirements to parent"},{"section":"306","description":"Reasonable efforts to prevent removal"},{"section":"309","description":"Placement preferences — relatives"},{"section":"311","description":"Release from custody — to parent or continued detention"},{"section":"313","description":"Filing petition within 48 hours if detained"}]', '["detention_report","JV_100","JV_101","protective_custody_warrant","social_worker_report","relative_placement_assessment","ICWA_inquiry"]', '["cps-dependency-family-reunification-audit"]', 'Juvenile Court / County CPS / Law Enforcement', 0, 1, datetime('now'), datetime('now'));

-- WIC 319 — Detention Hearing
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_069', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 319 (Detention Hearing)', 'WIC § 319', 'Detention Hearing — 48/72-Hour Judicial Review of Removal', 'Detention hearing must be held within 48 hours (72 hours if weekend/holiday) of removal. Court determines whether prima facie case for jurisdiction and whether continued detention is necessary. Court must order release unless substantial danger to child. Parent has right to counsel at detention. ICWA protections apply if Indian child.', '["Hearing within 48 hours of filing petition (72 if weekend/holiday)","Court makes prima facie finding on jurisdiction","Court determines whether continuance in home contrary to child welfare","Must release unless substantial danger and no reasonable means to protect without removal","Court must consider less restrictive alternatives","Parent has right to appointed counsel if indigent","Child has right to appointed counsel","ICWA active efforts and expert testimony requirements if Indian child","Court must make ICWA findings on record","Temporary visitation orders may be entered"]', '[{"section":"319(a)","description":"Timing — hearing within 48/72 hours"},{"section":"319(b)","description":"Prima facie case finding required"},{"section":"319(c)","description":"Findings for continued detention — substantial danger"},{"section":"319(d)","description":"Less restrictive alternatives must be considered"},{"section":"319(e)","description":"Right to counsel — parent and child"},{"section":"319(f)","description":"Visitation orders — liberal unless safety concern"},{"section":"319(h)","description":"ICWA — active efforts finding required"}]', '["detention_hearing_findings","JV_410","visitation_order","counsel_appointment","ICWA_findings","JV_412","prima_facie_order"]', '["cps-dependency-family-reunification-audit"]', 'Juvenile Court', 0, 1, datetime('now'), datetime('now'));

-- WIC 361 — Removal from Parent
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_070', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 361 (Removal — Dispositional Findings)', 'WIC § 361', 'Dispositional Removal — Clear and Convincing Evidence Standard', 'At disposition, court may remove child from parent only upon clear and convincing evidence of substantial danger to physical health, safety, protection, or well-being and no reasonable means to protect without removal. Reasonable efforts to prevent removal must be made. Case plan for reunification services must be ordered. Placement preferences: relative, NREFM, foster care.', '["Clear and convincing evidence required for removal (§ 361(c)(1))","Substantial danger to physical health, safety, protection, or well-being","No reasonable means to protect child without removal","Reasonable efforts to prevent or eliminate need for removal","Court must consider alternatives: in-home services, removal of offending parent","If removed, reunification services ordered (§ 361.5)","Case plan must be developed (§ 16501.1)","Placement preferences: relative → NREFM → foster care (§ 361.3)","ICWA: active efforts and qualified expert testimony required for Indian child","Court must state facts supporting removal on the record"]', '[{"section":"361(c)(1)","description":"Clear and convincing evidence — substantial danger, no reasonable means"},{"section":"361(c)(4)","description":"Offending parent removal as alternative"},{"section":"361(d)","description":"Court must state facts supporting removal on record"},{"section":"361.2","description":"Placement with noncustodial parent — presumptive right"},{"section":"361.3","description":"Relative placement preference"},{"section":"361.5","description":"Reunification services — 6-12 months depending on child age"}]', '["dispositional_order","JV_415","case_plan","reunification_services_order","ICWA_findings","relative_assessment","reasonable_efforts_finding"]', '["cps-dependency-family-reunification-audit"]', 'Juvenile Court / County CPS', 0, 1, datetime('now'), datetime('now'));

-- WIC 366.21/366.26 — Review and Permanency
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_071', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code §§ 366.21-366.26 (Review Hearings and Permanency Planning)', 'WIC §§ 366.21-366.26', 'Dependency Review Hearings and Permanency Planning — Timelines', 'Structured timeline for dependency proceedings. 6-month review (§ 366.21(e)): assess compliance with case plan. 12-month permanency hearing (§ 366.21(f)): return child or set § 366.26 hearing. 18-month review (§ 366.22): last chance for reunification. 366.26 hearing: select permanent plan — adoption (preferred), legal guardianship, or long-term foster care. Parental rights terminated if adoption selected.', '["6-month review: assess case plan compliance, reasonable services provided (§ 366.21(e))","12-month permanency hearing: return child or set .26 hearing (§ 366.21(f))","18-month review: final reunification opportunity (§ 366.22)","24-month review for certain cases under § 366.25","§ 366.26 hearing: select permanent plan","Permanent plan preference: adoption > guardianship > long-term foster care","If adoption, court terminates parental rights","Beneficial relationship exception — may not terminate if strong bond (§ 366.26(c)(1)(B)(i))","ASFA timelines: permanency decision within 12 months of entering foster care","Sibling group kept together when possible"]', '[{"section":"366.21(e)","description":"6-month review — services and compliance"},{"section":"366.21(f)","description":"12-month permanency hearing — return or set .26"},{"section":"366.22","description":"18-month review — final reunification chance"},{"section":"366.25","description":"24-month review — limited circumstances"},{"section":"366.26(b)","description":"Selection of permanent plan — adoption, guardianship, LTFC"},{"section":"366.26(c)(1)","description":"Termination of parental rights if adoption recommended"},{"section":"366.26(c)(1)(B)(i)","description":"Beneficial relationship exception — regular visitation and benefit"}]', '["6_month_review_report","12_month_permanency_report","18_month_review","366.26_report","adoption_assessment","guardianship_assessment","TPR_order","JV_320","case_plan_update"]', '["cps-dependency-family-reunification-audit"]', 'Juvenile Court / County CPS / CDSS', 0, 1, datetime('now'), datetime('now'));

-- ICWA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_072', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '25 USC §§ 1901-1963 (Indian Child Welfare Act) / Cal. WIC §§ 224-224.6', 'ICWA / 25 USC §§ 1901-1963', 'Indian Child Welfare Act — Tribal Sovereignty and Placement Preferences', 'Federal law protecting Indian children, families, and tribal sovereignty in child custody proceedings. Requires notice to tribes, active efforts (not just reasonable efforts), qualified expert witness testimony before foster care placement. Placement preferences: extended family → tribal foster home → Indian foster home → approved institution. Haaland v. Brackeen (2023): ICWA upheld as constitutional.', '["ICWA inquiry required at outset of every dependency case (§ 224.2)","Notice to tribe within specified timeframes if child may be Indian child","Active efforts to prevent breakup of Indian family — more than reasonable efforts","Qualified expert witness testimony required before foster care placement","Placement preferences: (1) extended family, (2) tribal foster home, (3) Indian foster home, (4) approved institution","Transfer to tribal court on request unless good cause","Beyond a reasonable doubt for termination of parental rights","Clear and convincing evidence for foster care placement","Tribe has right to intervene at any point","Invalidation of proceedings if ICWA violated"]', '[{"section":"1901","description":"Congressional findings — Indian family integrity"},{"section":"1903","description":"Definitions — Indian child, Indian child custody proceeding"},{"section":"1911","description":"Tribal court jurisdiction — exclusive and concurrent"},{"section":"1912","description":"Notice, active efforts, qualified expert witness"},{"section":"1913","description":"Voluntary consent requirements — in writing, before judge"},{"section":"1914","description":"Invalidation of proceedings for ICWA violation"},{"section":"1915","description":"Placement preferences"},{"section":"WIC 224.2","description":"California ICWA inquiry requirements"}]', '["ICWA_notice","tribal_inquiry","ICWA_findings","JV_135","qualified_expert_testimony","active_efforts_finding","placement_preference_documentation","tribal_intervention"]', '["cps-dependency-family-reunification-audit"]', 'Tribal Courts / Juvenile Court / BIA', 0, 1, datetime('now'), datetime('now'));
