-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 15
-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA deep-dive: FCRA sections, FDCPA sections, Rosenthal Act,
-- CA credit reporting, TILA/Reg Z, RESPA/Reg X, ECOA/Reg B, BSA/AML,
-- unclaimed property, CA HBOR, SCRA.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — FCRA Detail (15 USC §§ 1681)
-- ═══════════════════════════════════════════════════════════════════════════

-- FCRA Permissible Purpose
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_034', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1681b (Fair Credit Reporting Act — Permissible Purposes)', 'FCRA § 1681b', 'FCRA Permissible Purpose — Conditions for Obtaining Consumer Reports', 'Restricts who may obtain consumer reports and under what circumstances. A consumer reporting agency may furnish a report only for enumerated permissible purposes: credit transactions, employment screening (with consumer consent), insurance underwriting, legitimate business transactions initiated by consumer, government licensing, and court orders. Obtaining a report without permissible purpose is a federal violation with civil liability.', '["Consumer report may only be furnished for permissible purpose","Credit transaction: written instructions of consumer or credit/insurance/employment evaluation","Employment purpose requires clear written disclosure and consumer authorization BEFORE procurement","Insurance underwriting: connection with underwriting of insurance involving consumer","Legitimate business transaction initiated by consumer","Court order or federal grand jury subpoena","Account review: existing credit relationship for account monitoring","Prescreened offers: firm offer of credit or insurance","Government licensing or benefits determination","No permissible purpose for general curiosity or litigation research without court order"]', '[{"section":"1681b(a)","description":"Enumerated permissible purposes for furnishing consumer reports"},{"section":"1681b(a)(2)","description":"Written instructions of consumer"},{"section":"1681b(a)(3)(A)","description":"Credit transaction — intends to use in connection with credit"},{"section":"1681b(a)(3)(B)","description":"Employment purposes — with consumer consent"},{"section":"1681b(a)(3)(C)","description":"Insurance underwriting purpose"},{"section":"1681b(a)(3)(F)","description":"Legitimate business transaction initiated by consumer"},{"section":"1681b(b)","description":"Conditions for furnishing reports for employment purposes"},{"section":"1681b(c)","description":"Furnishing reports for prescreened offers"},{"section":"1681b(f)","description":"Prohibition on obtaining report under false pretenses"}]', '["credit_application","employment_authorization","consumer_report","prescreened_offer","insurance_application","court_order"]', '["banking-financial-document-audit"]', 'CFPB / FTC', 1, 1, datetime('now'), datetime('now'));

-- FCRA Consumer Disclosure Rights
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_035', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1681g (Fair Credit Reporting Act — Consumer Disclosures)', 'FCRA § 1681g', 'FCRA Consumer Disclosure Rights — Right to Know File Contents', 'Every consumer reporting agency must, upon request, clearly and accurately disclose to the consumer all information in the consumer''s file, sources of information, identification of each person who procured a report in the preceding year (two years for employment), and the consumer''s credit score. Free annual disclosure under § 1681j. Consumer has right to know what is being reported about them.', '["CRA must disclose all information in consumer file upon request","Must identify sources of information in file","Must disclose all inquiries — identity of each person procuring report in past year","Employment inquiries disclosed for past 2 years","Must disclose credit score and key factors","Must provide free annual file disclosure (AnnualCreditReport.com) per § 1681j","Disclosure must be clear, accurate, and in understandable form","Must disclose any risk score or predictor used","Must provide summary of rights with each disclosure","Must provide trained personnel to explain disclosure"]', '[{"section":"1681g(a)(1)","description":"Disclosure of all information in consumer file"},{"section":"1681g(a)(2)","description":"Sources of information disclosed"},{"section":"1681g(a)(3)","description":"Identity of inquirers — past year (2 years employment)"},{"section":"1681g(a)(5)","description":"Identification of inquiries for prescreened offers"},{"section":"1681g(f)","description":"Disclosure of credit scores"},{"section":"1681g(c)","description":"Summary of consumer rights must accompany disclosure"},{"section":"1681j(a)","description":"Free annual disclosure — one per 12-month period from each CRA"},{"section":"1681j(b)","description":"Free disclosure upon adverse action, fraud alert, unemployment, public assistance"}]', '["credit_report","file_disclosure","annual_credit_report","credit_score_disclosure","adverse_action_notice","consumer_rights_summary"]', '["banking-financial-document-audit"]', 'CFPB / FTC', 1, 1, datetime('now'), datetime('now'));

-- FCRA Dispute Procedures
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_036', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1681i (Fair Credit Reporting Act — Dispute Procedures)', 'FCRA § 1681i', 'FCRA Dispute Procedures — Reinvestigation of Disputed Information', 'When a consumer disputes the completeness or accuracy of any item in their file, the CRA must conduct a reasonable reinvestigation within 30 days (extendable to 45 if consumer provides additional info). CRA must forward all relevant information to the furnisher within 5 business days. If information cannot be verified, it must be deleted. Consumer must be notified of results within 5 business days of completion.', '["Consumer may dispute any item in file as inaccurate or incomplete","CRA must conduct reasonable reinvestigation within 30 days","30-day period may extend to 45 days if consumer provides additional information during investigation","CRA must forward dispute and all relevant information to furnisher within 5 business days","If disputed information cannot be verified, CRA must promptly delete or modify","CRA must provide written results to consumer within 5 business days of completion","If reinvestigation does not resolve dispute, consumer may file statement of dispute (100 words)","CRA must note item is disputed in subsequent reports","Frivolous disputes may be rejected with notice to consumer within 5 days","Consumer may request that revised report be sent to recent recipients"]', '[{"section":"1681i(a)(1)","description":"Reinvestigation required within 30 days"},{"section":"1681i(a)(2)","description":"Forward dispute to furnisher within 5 business days"},{"section":"1681i(a)(3)","description":"Determination and recording — delete if unverified"},{"section":"1681i(a)(5)","description":"45-day extension when consumer provides additional information"},{"section":"1681i(a)(6)","description":"Notice of results to consumer within 5 business days"},{"section":"1681i(b)","description":"Consumer statement of dispute — 100 words"},{"section":"1681i(c)","description":"Notification of dispute to recent report recipients"},{"section":"1681i(d)","description":"Notification of deletion to recipients at consumer request"}]', '["credit_dispute_letter","reinvestigation_notice","dispute_results_notice","consumer_statement_of_dispute","furnisher_response","deletion_notice"]', '["banking-financial-document-audit"]', 'CFPB / FTC', 1, 1, datetime('now'), datetime('now'));

-- FCRA Duties of Furnishers
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_037', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1681s-2 (Fair Credit Reporting Act — Duties of Furnishers)', 'FCRA § 1681s-2', 'FCRA Duties of Furnishers of Information — Accuracy and Dispute Obligations', 'Imposes duties on persons who furnish information to consumer reporting agencies. Section (a) requires accuracy — no reporting of information known to be inaccurate. Section (b) creates duties upon notice of dispute from CRA: must investigate, review all relevant information, report results, and correct inaccurate information. Section (b) provides private right of action; section (a) is enforced only by regulators.', '["Must not furnish information known to be inaccurate (§ 1681s-2(a))","Must correct and update information previously reported that is incomplete or inaccurate","Must provide notice to CRA when consumer disputes directly to furnisher","Upon notice of dispute from CRA, must conduct investigation within 30 days","Must review all relevant information provided by CRA with dispute","Must report results of investigation to CRA","Must modify, delete, or permanently block reporting if inaccurate","Must not re-report information that was previously deleted as inaccurate","Must notify consumer if account information reported as disputed","Reasonable procedures to ensure maximum possible accuracy"]', '[{"section":"1681s-2(a)(1)","description":"Duty to provide accurate information — no knowing inaccuracies"},{"section":"1681s-2(a)(2)","description":"Duty to correct and update previously furnished information"},{"section":"1681s-2(a)(3)","description":"Duty not to report information with notice of dispute from consumer"},{"section":"1681s-2(a)(8)","description":"Duty to provide notice of negative information to consumer"},{"section":"1681s-2(b)(1)","description":"Investigation duties upon notice of dispute from CRA"},{"section":"1681s-2(b)(1)(B)","description":"Review all relevant information from CRA"},{"section":"1681s-2(b)(1)(C)","description":"Report results of investigation to CRA"},{"section":"1681s-2(b)(1)(D)","description":"Modify, delete, or block if found inaccurate"},{"section":"1681s-2(b)(1)(E)","description":"Notify all CRAs if information found inaccurate"}]', '["furnisher_dispute_response","ACDV_response","correction_notice","negative_information_notice","investigation_results","data_furnishing_agreement"]', '["banking-financial-document-audit"]', 'CFPB / FTC / State AG', 1, 1, datetime('now'), datetime('now'));

-- FCRA Identity Theft Provisions
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_038', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1681c-1, 1681c-2 (Fair Credit Reporting Act — Identity Theft Protections)', 'FCRA §§ 1681c-1/1681c-2', 'FCRA Identity Theft Provisions — Fraud Alerts and Blocks', 'Provides identity theft victims with tools to protect credit files. Initial fraud alert (1 year) requires only good faith suspicion; extended alert (7 years) requires identity theft report. Active duty military alert for deployed servicemembers. CRA must block reporting of information resulting from identity theft upon submission of identity theft report. Truncation of SSN required on consumer disclosures.', '["Initial fraud alert: 1 year, good faith suspicion of identity theft","Extended fraud alert: 7 years, requires identity theft report (police report or FTC affidavit)","Active duty military alert: 1 year for deployed servicemembers","CRA receiving alert must notify other two nationwide CRAs within 1 business day","Creditor must take reasonable steps to verify identity before extending credit during alert","Consumer may request free credit report upon placing fraud alert","Block of information resulting from identity theft upon identity theft report","CRA must block within 4 business days of receiving documentation","Furnisher notified of block and may not re-report blocked information","CRA must not include blocked information in subsequent reports"]', '[{"section":"1681c-1(a)","description":"Initial fraud alert — 1 year upon good faith suspicion"},{"section":"1681c-1(b)","description":"Extended fraud alert — 7 years with identity theft report"},{"section":"1681c-1(c)","description":"Active duty military alert"},{"section":"1681c-1(d)","description":"Procedures — CRA must notify other nationwide CRAs within 1 day"},{"section":"1681c-1(h)","description":"Free credit report upon placing fraud alert"},{"section":"1681c-2(a)","description":"Block of information resulting from identity theft"},{"section":"1681c-2(b)","description":"4 business day block requirement after documentation received"},{"section":"1681c-2(c)","description":"Notification to furnisher of block"},{"section":"1681c-2(d)","description":"Furnisher may not re-report blocked information"}]', '["fraud_alert_request","identity_theft_report","FTC_identity_theft_affidavit","police_report","block_request","credit_freeze_request","active_duty_alert"]', '["banking-financial-document-audit"]', 'CFPB / FTC', 1, 1, datetime('now'), datetime('now'));

-- FCRA Civil Liability
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_039', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1681n, 1681o (Fair Credit Reporting Act — Civil Liability)', 'FCRA §§ 1681n/1681o', 'FCRA Civil Liability — Willful and Negligent Noncompliance', 'Establishes private right of action for FCRA violations. Willful noncompliance (§ 1681n): actual damages or statutory damages ($100-$1,000 per violation), plus punitive damages, plus attorney fees. Negligent noncompliance (§ 1681o): actual damages plus attorney fees. Two-year statute of limitations from discovery, maximum five years from violation. Class actions permitted for willful violations.', '["Willful noncompliance: actual damages or statutory damages $100-$1,000","Willful noncompliance: punitive damages available","Willful noncompliance: reasonable attorney fees and costs","Negligent noncompliance: actual damages only","Negligent noncompliance: reasonable attorney fees and costs","Statute of limitations: 2 years from discovery of violation","Absolute statute of repose: 5 years from date of violation","Class actions permitted under § 1681n (willful)","Obtaining consumer report under false pretenses: criminal liability up to $5,000 fine and 1 year imprisonment","Unauthorized disclosure by CRA officer: criminal liability"]', '[{"section":"1681n(a)(1)(A)","description":"Willful noncompliance — actual damages"},{"section":"1681n(a)(1)(B)","description":"Willful noncompliance — statutory damages $100-$1,000"},{"section":"1681n(a)(2)","description":"Punitive damages for willful noncompliance"},{"section":"1681n(a)(3)","description":"Attorney fees and costs for willful noncompliance"},{"section":"1681o(a)","description":"Negligent noncompliance — actual damages and attorney fees"},{"section":"1681p","description":"Jurisdiction — federal district court, no amount in controversy"},{"section":"1681q","description":"Criminal liability — obtaining report under false pretenses"},{"section":"1681r","description":"Criminal liability — unauthorized disclosure by CRA officer"}]', '["FCRA_complaint","civil_complaint","class_action_complaint","damages_calculation","attorney_fee_petition","demand_letter"]', '["banking-financial-document-audit"]', 'Federal District Court / CFPB', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — FDCPA Detail (15 USC §§ 1692)
-- ═══════════════════════════════════════════════════════════════════════════

-- FDCPA Prohibited Practices — Harassment
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_040', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1692d (Fair Debt Collection Practices Act — Harassment)', 'FDCPA § 1692d', 'FDCPA Prohibited Practices — Harassment or Abuse', 'Prohibits debt collectors from engaging in conduct the natural consequence of which is to harass, oppress, or abuse any person in connection with collection of a debt. Includes threats of violence, obscene language, repeated telephone calls intended to annoy, publication of shame lists, and calling without meaningful disclosure of identity. Applies to third-party debt collectors, not original creditors (unless using different name).', '["No use or threat of violence or criminal means to harm person, reputation, or property","No use of obscene, profane, or abusive language","No publication of lists of consumers who refuse to pay (shame lists)","No advertising for sale of any debt to coerce payment","No causing telephone to ring repeatedly with intent to annoy, abuse, or harass","No placing calls without meaningful disclosure of caller identity","No threats of arrest or imprisonment","No simulating legal process documents","Applies to third-party debt collectors, not original creditors","CFPB Regulation F (12 CFR § 1006) implements phone call frequency limits: 7 calls per 7 days per debt"]', '[{"section":"1692d(1)","description":"Threats of violence or criminal means"},{"section":"1692d(2)","description":"Obscene or profane language"},{"section":"1692d(3)","description":"Publication of shame lists"},{"section":"1692d(4)","description":"Advertising debt for sale to coerce payment"},{"section":"1692d(5)","description":"Repeated or continuous telephone calls to annoy/harass"},{"section":"1692d(6)","description":"Failure to disclose identity on telephone calls"},{"section":"12 CFR 1006.14(b)","description":"Reg F — 7 calls per 7 days per debt frequency cap"}]', '["collection_call_log","harassment_complaint","cease_and_desist_letter","CFPB_complaint","debt_collection_correspondence"]', '["banking-financial-document-audit"]', 'CFPB / FTC / State AG', 1, 1, datetime('now'), datetime('now'));

-- FDCPA False/Misleading Representations
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_041', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1692e (Fair Debt Collection Practices Act — False Representations)', 'FDCPA § 1692e', 'FDCPA False or Misleading Representations', 'Prohibits debt collectors from using any false, deceptive, or misleading representation or means in connection with collection of any debt. Enumerates 16 specific prohibited representations including false threat of legal action, misrepresentation of debt amount, impersonation of attorney or government official, and false implication that nonpayment will result in arrest or imprisonment.', '["No false representation of character, amount, or legal status of debt","No false representation that individual is attorney when not","No false representation that nonpayment will result in arrest, imprisonment, or seizure of property unless lawful and intended","No threat of legal action not actually intended","No false representation of being affiliated with government","No false implication that consumer committed a crime","No communicating false credit information (including failing to report dispute)","No use of false name or false business name","No false representation that documents are legal process when not","No false representation that documents are not legal process when they are","No collecting any amount not authorized by agreement or law","No misrepresentation of compensation — third party collection","Cannot falsely represent that sale or transfer of debt will cause consumer to lose defenses","Cannot use any false representation or deceptive means to collect","Least sophisticated consumer standard applies"]', '[{"section":"1692e(1)","description":"False affiliation with government"},{"section":"1692e(2)","description":"False representation of character, amount, or legal status of debt"},{"section":"1692e(3)","description":"False representation that person is attorney"},{"section":"1692e(4)","description":"False implication that nonpayment is a crime"},{"section":"1692e(5)","description":"Threat of action that cannot legally be taken or is not intended"},{"section":"1692e(7)","description":"False representation that consumer committed crime to disgrace"},{"section":"1692e(8)","description":"Communicating false credit information — failure to report dispute"},{"section":"1692e(9)","description":"Use of documents simulating legal process"},{"section":"1692e(10)","description":"Any false representation or deceptive means"},{"section":"1692e(11)","description":"Failure to disclose in initial communication that communication is from debt collector"},{"section":"1692e(14)","description":"Use of any business or organization name other than true name"}]', '["collection_letter","debt_validation_notice","demand_letter","legal_threat_letter","CFPB_complaint","FDCPA_complaint"]', '["banking-financial-document-audit"]', 'CFPB / FTC / State AG', 1, 1, datetime('now'), datetime('now'));

-- FDCPA Unfair Practices
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_042', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1692f (Fair Debt Collection Practices Act — Unfair Practices)', 'FDCPA § 1692f', 'FDCPA Unfair Practices — Unconscionable Means of Collection', 'Prohibits debt collectors from using unfair or unconscionable means to collect or attempt to collect any debt. Includes collecting amounts not authorized by agreement or law, accepting postdated checks by more than 5 days without notice, threatening to deposit postdated checks early, causing charges (calls, telegrams) with intent to conceal nature of communication, taking or threatening to take nonjudicial action on property with no security interest, and communicating via postcard.', '["No collection of any amount not expressly authorized by debt agreement or permitted by law","No acceptance of check or instrument postdated by more than 5 days without written notification 3-10 days before deposit","No solicitation of postdated check for purpose of threatening criminal prosecution","No deposit or threat to deposit postdated check before date on check","No causing charges (collect calls, telegrams) to conceal true purpose of communication","No taking or threatening to take nonjudicial action on property unless lawful and there is present right to possession","No communicating with consumer by postcard","No using any language or symbol on envelope other than debt collector address and name (if not indicating debt collection)"]', '[{"section":"1692f(1)","description":"Collection of unauthorized amounts — interest, fees, charges not in agreement or allowed by law"},{"section":"1692f(2)","description":"Acceptance of postdated check more than 5 days without notice"},{"section":"1692f(3)","description":"Solicitation of postdated check for criminal threat purpose"},{"section":"1692f(4)","description":"Depositing or threatening to deposit postdated check before date"},{"section":"1692f(5)","description":"Causing charges to conceal true purpose of communication"},{"section":"1692f(6)","description":"Nonjudicial action on property without security interest or right to possession"},{"section":"1692f(7)","description":"Communication by postcard"},{"section":"1692f(8)","description":"Envelope language or symbols indicating debt collection"}]', '["collection_notice","fee_assessment","postdated_check_notice","collection_call_log","CFPB_complaint","FDCPA_complaint"]', '["banking-financial-document-audit"]', 'CFPB / FTC / State AG', 1, 1, datetime('now'), datetime('now'));

-- FDCPA Validation of Debts
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_043', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1692g (Fair Debt Collection Practices Act — Validation of Debts)', 'FDCPA § 1692g', 'FDCPA Validation of Debts — Consumer Right to Verify Debt', 'Within 5 days of initial communication, debt collector must send written notice containing amount of debt, name of creditor, and statement of consumer''s right to dispute. Consumer has 30 days to dispute in writing; if disputed, collector must cease collection until verification is provided. CFPB Regulation F (12 CFR § 1006.34) requires itemization date and enhanced disclosures.', '["Within 5 days of initial communication, must send written validation notice","Notice must contain: amount of debt","Notice must contain: name of creditor to whom debt is owed","Notice must state: debt is assumed valid unless disputed within 30 days","Notice must state: if disputed in writing within 30 days, collector will obtain verification","Notice must state: upon written request within 30 days, collector will provide name and address of original creditor if different","If consumer disputes in writing within 30 days, collector must cease collection until verification mailed","Verification must be mailed to consumer","Collection activities during 30-day period must not overshadow or be inconsistent with disclosure of dispute rights","Reg F requires itemization date, itemization of current amount, and merchant/creditor name"]', '[{"section":"1692g(a)","description":"Validation notice required within 5 days of initial communication"},{"section":"1692g(a)(1)","description":"Amount of debt"},{"section":"1692g(a)(2)","description":"Name of creditor to whom debt is owed"},{"section":"1692g(a)(3)","description":"30-day dispute period — debt assumed valid unless disputed"},{"section":"1692g(a)(4)","description":"Verification upon written dispute within 30 days"},{"section":"1692g(a)(5)","description":"Original creditor identification upon request"},{"section":"1692g(b)","description":"Cease collection upon dispute until verification provided"},{"section":"12 CFR 1006.34","description":"Reg F — enhanced validation notice content requirements"}]', '["validation_notice","debt_dispute_letter","verification_of_debt","initial_communication","debt_itemization","original_creditor_identification"]', '["banking-financial-document-audit"]', 'CFPB / FTC / State AG', 1, 1, datetime('now'), datetime('now'));

-- FDCPA Cease Communication
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_044', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1692c (Fair Debt Collection Practices Act — Communication in Connection with Debt Collection)', 'FDCPA § 1692c', 'FDCPA Cease Communication and Communication Restrictions', 'Restricts when, where, and with whom debt collectors may communicate. Cannot contact consumer at unusual or inconvenient time or place (before 8 a.m. or after 9 p.m. presumptively inconvenient). Cannot contact at place of employment if employer disapproves. Must cease communication upon written request from consumer (except to notify of specific remedies). Cannot communicate with third parties except to obtain location information.', '["Cannot communicate at unusual or inconvenient time — before 8 a.m. or after 9 p.m. local time presumptively inconvenient","Cannot communicate at unusual or inconvenient place","Cannot contact consumer at place of employment if collector knows employer prohibits","Cannot communicate with consumer known to be represented by attorney (must communicate with attorney)","Must cease all communication upon written request from consumer","After cease request, collector may only notify: collection efforts terminated, specific remedy may be invoked, collector intends to invoke specific remedy","Cannot communicate with third parties other than consumer, attorney, CRA, creditor, or creditor attorney","Third party location information: may contact third party once, must not state that consumer owes debt","Reg F: email and text message communication permitted with proper consent and opt-out procedures"]', '[{"section":"1692c(a)(1)","description":"No communication at unusual or inconvenient time — 8am-9pm safe harbor"},{"section":"1692c(a)(2)","description":"No communication at inconvenient place — workplace if employer disapproves"},{"section":"1692c(a)(3)","description":"No communication if consumer represented by attorney"},{"section":"1692c(b)","description":"No communication with third parties except limited exceptions"},{"section":"1692c(c)","description":"Cease communication upon consumer written request"},{"section":"1692c(c)(1)","description":"Exception — may notify that collection efforts terminated"},{"section":"1692c(c)(2)","description":"Exception — may notify of specific remedy"},{"section":"1692c(c)(3)","description":"Exception — may notify collector intends to invoke remedy"},{"section":"1692b","description":"Acquisition of location information — third party contact rules"}]', '["cease_and_desist_letter","collection_call_log","third_party_contact_record","communication_preference_notice","attorney_representation_notice","CFPB_complaint"]', '["banking-financial-document-audit"]', 'CFPB / FTC / State AG', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — California Consumer Finance
-- ═══════════════════════════════════════════════════════════════════════════

-- Rosenthal Fair Debt Collection Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_045', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1788-1788.33 (Rosenthal Fair Debt Collection Practices Act)', 'CC §§ 1788-1788.33', 'Rosenthal Fair Debt Collection Practices Act — California Debt Collection', 'California''s debt collection law that applies to BOTH original creditors AND third-party debt collectors — broader than federal FDCPA which only covers third-party collectors. Incorporates FDCPA §§ 1692b-1692j by reference. Provides for actual damages, statutory damages ($100-$1,000), and attorney fees. Prohibits the same practices as FDCPA plus additional California-specific protections including time-barred debt disclosure requirements.', '["Applies to original creditors AND third-party debt collectors — broader than FDCPA","Incorporates FDCPA §§ 1692b through 1692j by reference","Prohibits harassment, abuse, false representations, unfair practices","Must not collect interest, fees, or charges not authorized by original agreement","Must not threaten to take action prohibited by law","Must provide written notice that consumer can request original creditor identity","Cannot communicate with debtor in language other than English unless debtor consented to that language","Time-barred debt: must disclose that creditor cannot sue to collect (SB 641)","Statutory damages: $100-$1,000 per action","Actual damages, attorney fees, and costs available","Class action damages capped at lesser of $500,000 or 1% of net worth"]', '[{"section":"1788.1","description":"Legislative intent — protect consumers from unfair debt collection"},{"section":"1788.2","description":"Definitions — debt collector includes original creditors"},{"section":"1788.10","description":"Prohibited practices — threats of violence or criminal means"},{"section":"1788.11","description":"Prohibited practices — obscene language, harassment"},{"section":"1788.12","description":"Prohibited practices — false, deceptive, misleading representations"},{"section":"1788.13","description":"Prohibited practices — unfair or unconscionable means"},{"section":"1788.14","description":"Prohibited practices — collect unauthorized amounts"},{"section":"1788.17","description":"Incorporation of FDCPA §§ 1692b-1692j"},{"section":"1788.30","description":"Liability — actual damages, statutory damages $100-$1,000, attorney fees"},{"section":"1788.33","description":"Time-barred debt disclosure requirements (SB 641)"}]', '["collection_letter","debt_validation_notice","cease_and_desist_letter","time_barred_debt_notice","Rosenthal_complaint","demand_letter","collection_call_log"]', '["banking-financial-document-audit"]', 'California Superior Court / CA AG / DFPI', 1, 1, datetime('now'), datetime('now'));

-- CA Consumer Credit Reporting
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_046', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1785.1-1785.36 (Consumer Credit Reporting Agencies Act)', 'CC §§ 1785.1-1785.36', 'California Consumer Credit Reporting Agencies Act — State Credit Reporting Law', 'California''s state credit reporting law that supplements federal FCRA with additional consumer protections. Provides broader rights in several areas: CRAs must reinvestigate within 30 days, furnishers have investigation duties, and consumers have private right of action with actual or statutory damages. Prohibits reporting of certain information including medical debts paid by insurance within 180 days.', '["CRA must follow reasonable procedures to assure maximum possible accuracy","Consumer may dispute inaccurate information — CRA must reinvestigate within 30 days","CRA must record current status of disputed information pending reinvestigation","If disputed information found inaccurate, CRA must promptly delete","CRA must provide file disclosure to consumer upon request","Consumer entitled to one free report per 12 months","CRA must disclose credit score and key factors","Employment reports: employer must provide copy to applicant if adverse action taken","Medical debt paid by insurance within 180 days cannot be reported","CRA must maintain toll-free telephone number for consumers","CRA must provide trained personnel to explain file contents"]', '[{"section":"1785.10","description":"CRA obligations — reasonable procedures for maximum accuracy"},{"section":"1785.14","description":"Permissible purposes — similar to FCRA § 1681b"},{"section":"1785.15","description":"Consumer file disclosure rights"},{"section":"1785.16","description":"Dispute procedures — reinvestigation within 30 days"},{"section":"1785.16.2","description":"Identity theft victim protections"},{"section":"1785.20.5","description":"Security freeze provisions"},{"section":"1785.25","description":"Furnisher duties — accuracy requirements"},{"section":"1785.31","description":"Civil liability — actual damages or statutory damages"},{"section":"1785.35","description":"Investigative consumer reports — additional protections"},{"section":"1785.36","description":"Security of consumer report information"}]', '["credit_report","file_disclosure","credit_dispute","reinvestigation_notice","security_freeze_request","identity_theft_report","adverse_action_notice"]', '["banking-financial-document-audit"]', 'California Superior Court / CA AG / DFPI', 1, 1, datetime('now'), datetime('now'));

-- CA Security Freeze
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_047', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1785.11.2 (Security Freeze)', 'CC § 1785.11.2', 'California Security Freeze — Consumer Right to Freeze Credit File', 'Consumers may place, temporarily lift, or remove a security freeze on their credit file at no charge. CRA must place freeze within 1 business day of receiving request (3 business days by mail). CRA must temporarily lift freeze within 1 business day of receiving request. Protected consumers (under 16 or incapacitated) may have representative place freeze. CRA may not charge any fee for security freeze placement, temporary lift, or removal.', '["Consumer may place security freeze by telephone, internet, or mail","CRA must place freeze within 1 business day (3 business days by mail)","CRA must temporarily lift freeze within 1 business day of request","Consumer may lift freeze for specific party or specific time period","No fee for placing, temporarily lifting, or removing freeze","CRA must provide unique PIN or password for freeze management","Protected consumer freeze: representative may place for minor under 16 or incapacitated adult","Freeze does not prevent reporting to existing creditors","Freeze does not prevent prescreened offers unless separately opted out","CRA must provide confirmation of freeze within 5 business days"]', '[{"section":"1785.11.2(a)","description":"Consumer right to place security freeze"},{"section":"1785.11.2(b)","description":"CRA must place within 1 business day"},{"section":"1785.11.2(d)","description":"Temporary lift within 1 business day"},{"section":"1785.11.2(e)","description":"Consumer may designate specific party or time period for lift"},{"section":"1785.11.2(h)","description":"No fee for freeze, lift, or removal"},{"section":"1785.11.2(j)","description":"PIN or password for managing freeze"},{"section":"1785.11.2(l)","description":"Protected consumer freeze — minors under 16, incapacitated adults"}]', '["security_freeze_request","freeze_confirmation","temporary_lift_request","freeze_removal_request","protected_consumer_freeze_request"]', '["banking-financial-document-audit"]', 'California Superior Court / CA AG', 1, 1, datetime('now'), datetime('now'));

-- CA Identity Theft — Credit Reporting
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_048', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1785.16.2 (Identity Theft Victim — Credit Reporting)', 'CC § 1785.16.2', 'California Identity Theft Victim Protections — Credit Reporting', 'Enhanced protections for identity theft victims beyond federal FCRA. Upon submission of identity theft report (police report or FTC affidavit), CRA must block fraudulent information within specified timeframe. Victim may also obtain records from businesses that extended credit in victim''s name. Creditors must cease collection of fraudulent debts upon notice. Intersects with Penal Code § 530.5 (identity theft criminal statute).', '["Identity theft victim may submit identity theft report to CRA requesting block","CRA must block fraudulent information resulting from identity theft","Victim may request records from creditor or business that opened fraudulent account","Business must provide copies of application and transaction records within 30 days","Creditor must cease collection efforts on fraudulent debt upon notice with identity theft report","CRA must provide file disclosure at no charge to identity theft victim","Victim may request that CRA notify furnishers of fraudulent information","No charge for any identity theft-related credit reporting services","Intersects with Penal Code § 530.5 — criminal identity theft","Intersects with CC § 1798.92-1798.97 — Identity Theft Resolution"]', '[{"section":"1785.16.2(a)","description":"Block request upon identity theft report"},{"section":"1785.16.2(b)","description":"CRA duty to block fraudulent information"},{"section":"1785.16.2(c)","description":"Notification to furnisher upon block"},{"section":"1785.16.2(d)","description":"Furnisher may not re-report blocked information"},{"section":"1785.16.2(e)","description":"Victim right to obtain records from creditor"},{"section":"Penal Code 530.5","description":"Criminal identity theft — obtaining personal identifying information for unlawful purpose"},{"section":"CC 1798.92-97","description":"Identity Theft Resolution — cessation of collection, creditor duties"}]', '["identity_theft_report","police_report","FTC_affidavit","block_request","creditor_record_request","fraud_alert_request","collection_cessation_notice"]', '["banking-financial-document-audit"]', 'California Superior Court / CA AG / DFPI', 1, 1, datetime('now'), datetime('now'));

-- CA Financial Elder Abuse
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_049', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 15610.30; Cal. Fin. Code §§ 950-956 (Financial Elder Abuse)', 'WIC § 15610.30 / Fin Code §§ 950-956', 'California Financial Elder Abuse — Banking and Financial Exploitation', 'Defines financial abuse of elders (65+) and dependent adults to include taking, secreting, appropriating, obtaining, or retaining property by undue influence, fraud, or wrongful means. Financial institutions have mandatory reporting duties for suspected financial abuse. Banks and broker-dealers may delay disbursements for up to 5 business days if financial abuse suspected. Enhanced civil remedies including treble damages under WIC § 15657.5.', '["Financial abuse: taking, secreting, appropriating property of elder or dependent adult","Includes obtaining property by undue influence, fraud, coercion, or wrongful means","Mandated reporters at financial institutions must report suspected abuse to APS","Financial institutions may delay disbursement up to 5 business days upon suspicion of financial abuse (Fin Code § 950)","Bank officer or employee making good faith report is immune from liability","Investment advisers subject to same reporting and delay authority","Elder: person 65 years of age or older","Dependent adult: person 18-64 with qualifying disability","Civil liability: actual damages, attorney fees, costs","Enhanced damages: treble damages for reckless, oppressive, or malicious conduct (WIC § 15657.5)","Statute of limitations: 4 years from discovery"]', '[{"section":"WIC 15610.30(a)","description":"Definition of financial abuse of elder or dependent adult"},{"section":"WIC 15610.30(b)","description":"Taking by undue influence — presumption when fiduciary"},{"section":"WIC 15630.1","description":"Mandated reporter duties — financial institutions"},{"section":"WIC 15657.5","description":"Treble damages for reckless, oppressive, or malicious financial abuse"},{"section":"Fin Code 950","description":"Financial institution authority to delay disbursement up to 5 business days"},{"section":"Fin Code 951","description":"Notification to APS and law enforcement upon delay"},{"section":"Fin Code 952","description":"Broker-dealer and investment adviser reporting"},{"section":"Fin Code 956","description":"Immunity for good faith reporting"}]', '["APS_report","suspicious_activity_report","financial_abuse_complaint","POA_abuse_report","disbursement_delay_notice","mandated_report","elder_abuse_restraining_order"]', '["banking-financial-document-audit"]', 'Adult Protective Services / CA AG / DFPI / California Superior Court', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — TILA/Reg Z Detail
-- ═══════════════════════════════════════════════════════════════════════════

-- TILA Disclosure Requirements
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_050', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1631-1632 (Truth in Lending Act — Disclosure Requirements)', 'TILA §§ 1631-1632', 'TILA Disclosure Requirements — Annual Percentage Rate and Finance Charges', 'Requires creditors to disclose key credit terms clearly and conspicuously before consummation of transaction. Required disclosures include APR, finance charge, amount financed, total of payments, and payment schedule. Closed-end credit (§ 1638) and open-end credit (§ 1637) have distinct disclosure requirements. Regulation Z (12 CFR § 1026) implements TILA. Failure to make required disclosures creates right of rescission and civil liability.', '["APR must be disclosed as annual percentage rate — most important single disclosure","Finance charge: total cost of credit as a dollar amount","Amount financed: net amount of credit provided to consumer","Total of payments: sum of all payments over life of loan","Payment schedule: number, amount, and timing of payments","Closed-end credit (§ 1638): disclosures before consummation","Open-end credit (§ 1637): disclosures with periodic statement","Disclosures must be clear and conspicuous","APR and finance charge must be more conspicuous than other terms","Creditor identification must be disclosed","Variable rate disclosures: index, margin, caps, adjustment periods","Regulation Z (12 CFR § 1026) provides detailed implementation rules"]', '[{"section":"1631","description":"Disclosure requirements — general duty to disclose"},{"section":"1632","description":"Form of disclosures — clear and conspicuous, meaningful sequence"},{"section":"1637","description":"Open-end credit — periodic statement disclosures"},{"section":"1638","description":"Closed-end credit — disclosures before consummation"},{"section":"1638(a)(1)","description":"Identity of creditor"},{"section":"1638(a)(2)","description":"Amount financed"},{"section":"1638(a)(3)","description":"Itemization of amount financed"},{"section":"1638(a)(4)","description":"Finance charge"},{"section":"1638(a)(7)","description":"Annual percentage rate"},{"section":"1638(a)(8)","description":"Variable rate information"},{"section":"12 CFR 1026","description":"Regulation Z — implementing regulation for TILA"}]', '["TILA_disclosure","Loan_Estimate","Closing_Disclosure","credit_card_agreement","periodic_statement","APR_disclosure","Truth_in_Lending_statement"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- TILA Right of Rescission
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_051', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1635 (Truth in Lending Act — Right of Rescission)', 'TILA § 1635', 'TILA Right of Rescission — Consumer Right to Cancel Secured Transactions', 'Consumer has right to rescind (cancel) any credit transaction in which a security interest is retained or acquired in consumer''s principal dwelling, until midnight of the third business day following consummation or delivery of rescission notice and disclosures, whichever is later. If material TILA disclosures were not provided, right of rescission extends for up to 3 years. Upon rescission, security interest becomes void and creditor must return all money or property within 20 calendar days.', '["Right to rescind until midnight of third business day following consummation","Right extends until 3 years after consummation if material disclosures not provided","Creditor must provide two copies of rescission notice to each consumer","Applies only to transactions secured by consumer principal dwelling","Does not apply to residential mortgage used to finance acquisition of dwelling","Does not apply to refinancing by same creditor with no new advance","Upon rescission, security interest becomes void","Creditor must return money or property within 20 calendar days of rescission","Consumer not liable for finance charges if rescission exercised properly","Right is for each consumer whose principal dwelling is subject to security interest"]', '[{"section":"1635(a)","description":"Right of rescission — 3 business days from consummation or disclosure"},{"section":"1635(b)","description":"Procedures upon rescission — security interest void, creditor returns funds within 20 days"},{"section":"1635(c)","description":"Rebuttable presumption of delivery of rescission notice"},{"section":"1635(e)","description":"Exemptions — purchase money mortgage, refinancing by same creditor"},{"section":"1635(f)","description":"3-year absolute right of rescission expires regardless"},{"section":"1635(i)","description":"Two copies of rescission notice required per consumer"},{"section":"12 CFR 1026.23","description":"Reg Z implementation — right of rescission procedures"}]', '["rescission_notice","TILA_disclosure","Notice_of_Right_to_Cancel","home_equity_loan_agreement","HELOC_agreement","closing_documents"]', '["banking-financial-document-audit"]', 'CFPB / Federal District Court', 1, 1, datetime('now'), datetime('now'));

-- TILA Credit Card Protections
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_052', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1643-1644 (Truth in Lending Act — Credit Card Protections)', 'TILA §§ 1643-1644', 'TILA Credit Card Protections — Unauthorized Use Liability Limits', 'Limits cardholder liability for unauthorized use of credit card to $50, provided card issuer has met notification requirements. Card issuer must provide self-addressed, prestamped notification form. Fraudulent use of credit cards is a federal crime under § 1644. CARD Act (2009) added additional protections: 45-day notice before rate increases, prohibition on double-cycle billing, limitations on fees, and mandatory payment application rules.', '["Cardholder liability for unauthorized use limited to $50 maximum (§ 1643)","$50 cap applies only if issuer provided notification means and card was accepted (unsigned card)","Card issuer bears burden of proof that use was authorized","Unauthorized use: use by person other than cardholder without actual, implied, or apparent authority","Fraudulent use of credit card: federal crime (§ 1644) — up to $10,000 fine and 10 years imprisonment","CARD Act: 45-day advance notice before interest rate increase","CARD Act: prohibition on double-cycle billing","CARD Act: payments in excess of minimum applied to highest-rate balance first","CARD Act: no interest rate increase in first year (except variable rate)","CARD Act: penalty fee must be reasonable and proportional","CARD Act: statements mailed 21 days before due date"]', '[{"section":"1643(a)","description":"Cardholder liability limited to $50 for unauthorized use"},{"section":"1643(a)(1)","description":"Conditions — card accepted, issuer provided notification means, issuer provided identification method"},{"section":"1643(b)","description":"Burden of proof on card issuer for authorized use"},{"section":"1644","description":"Fraudulent use of credit cards — federal crime"},{"section":"1665b","description":"CARD Act — advance notice of rate increase (45 days)"},{"section":"1666c","description":"CARD Act — payment application to highest-rate balance"},{"section":"1666i-1","description":"CARD Act — restrictions on rate increases in first year"},{"section":"1666j","description":"CARD Act — prohibition on double-cycle billing"},{"section":"12 CFR 1026.52","description":"Reg Z — limits on penalty fees"}]', '["credit_card_statement","unauthorized_use_claim","billing_error_notice","rate_increase_notice","cardholder_agreement","fraud_report","CARD_Act_disclosure"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — RESPA/Reg X
-- ═══════════════════════════════════════════════════════════════════════════

-- RESPA Settlement Procedures
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_053', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC §§ 2603-2604 (Real Estate Settlement Procedures Act — Settlement Disclosures)', 'RESPA §§ 2603-2604', 'RESPA Settlement Procedures — Disclosure of Settlement Costs', 'Requires disclosure of settlement costs in federally related mortgage loans. Integrated with TILA under TRID (TILA-RESPA Integrated Disclosure) rule effective 2015: Loan Estimate within 3 business days of application, Closing Disclosure 3 business days before consummation. Replaced HUD-1 Settlement Statement and GFE. Borrower must receive Special Information Booklet at time of application or within 3 business days.', '["Loan Estimate must be provided within 3 business days of receiving application (TRID)","Closing Disclosure must be provided 3 business days before consummation (TRID)","Special Information Booklet (Settlement Costs) provided at application or within 3 business days","Loan Estimate includes estimated settlement charges, loan terms, projected payments","Closing Disclosure includes actual settlement charges, loan terms, cash to close","Changed circumstances may permit revised Loan Estimate","Tolerance limits on fee estimates: zero tolerance, 10% cumulative tolerance, no limit categories","No fee may be collected before Loan Estimate is provided except reasonable credit report fee","Servicer must provide servicing transfer notice 15 days before effective date","Applies to federally related mortgage loans — most 1-4 family residential mortgages"]', '[{"section":"2603","description":"Uniform settlement statement — Closing Disclosure under TRID"},{"section":"2604","description":"Special Information Booklet — provided to applicant"},{"section":"12 CFR 1026.19(e)","description":"Reg Z/TRID — Loan Estimate within 3 business days of application"},{"section":"12 CFR 1026.19(f)","description":"Reg Z/TRID — Closing Disclosure 3 business days before consummation"},{"section":"12 CFR 1026.19(e)(3)","description":"Tolerance limits on estimated charges"},{"section":"12 CFR 1026.19(e)(4)","description":"Changed circumstances permitting revised estimate"},{"section":"12 CFR 1026.37","description":"Content of Loan Estimate"},{"section":"12 CFR 1026.38","description":"Content of Closing Disclosure"}]', '["Loan_Estimate","Closing_Disclosure","Special_Information_Booklet","settlement_statement","servicing_transfer_notice","mortgage_application"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- RESPA Servicing Requirements
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_054', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC § 2605 (Real Estate Settlement Procedures Act — Servicing)', 'RESPA § 2605', 'RESPA Servicing Requirements — Escrow, Transfers, and Error Resolution', 'Governs mortgage loan servicing including escrow accounts, servicing transfers, qualified written requests (QWR), and error resolution. Servicer must respond to QWR within 30 days (5 days acknowledgment). Servicing transfer requires 15-day advance notice. Escrow account analysis required annually; surplus over $50 must be returned within 30 days. Regulation X (12 CFR § 1024) provides additional loss mitigation and foreclosure protections.', '["Servicing transfer notice: 15 days before effective date from transferor, 15 days after from transferee","60-day safe harbor after transfer — no late fees for payments sent to prior servicer","Qualified Written Request (QWR): written correspondence relating to servicing","Must acknowledge QWR within 5 business days","Must respond to QWR within 30 business days (may extend 15 days)","Must not report negative credit information during QWR investigation period","Escrow account analysis required annually","Escrow surplus over $50 must be refunded within 30 days","Escrow shortage may be spread over 12 months","Reg X loss mitigation: must evaluate borrower for all available options","Reg X: no foreclosure referral until borrower 120+ days delinquent","Reg X: no foreclosure sale if complete loss mitigation application pending"]', '[{"section":"2605(a)","description":"Disclosure of servicing assignment, sale, or transfer"},{"section":"2605(b)","description":"Notice of transfer — 15 days from transferor and transferee"},{"section":"2605(c)","description":"Servicing transfer safe harbor — 60 days"},{"section":"2605(e)","description":"Qualified Written Request — duty to respond"},{"section":"2605(e)(2)","description":"30-day response to QWR"},{"section":"2605(e)(3)","description":"No negative credit reporting during QWR period"},{"section":"2605(g)","description":"Escrow account administration"},{"section":"12 CFR 1024.35","description":"Reg X — error resolution procedures"},{"section":"12 CFR 1024.36","description":"Reg X — requests for information"},{"section":"12 CFR 1024.41","description":"Reg X — loss mitigation procedures"},{"section":"12 CFR 1024.41(f)","description":"Reg X — dual tracking prohibition"}]', '["qualified_written_request","servicing_transfer_notice","escrow_analysis_statement","loss_mitigation_application","foreclosure_notice","mortgage_statement","error_resolution_notice"]', '["banking-financial-document-audit"]', 'CFPB / Federal District Court', 1, 1, datetime('now'), datetime('now'));

-- RESPA Anti-Kickback
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_055', 'FISCARA', 'FEDERAL_STATUTE', 'US', '12 USC § 2607 (Real Estate Settlement Procedures Act — Anti-Kickback)', 'RESPA § 2607', 'RESPA Anti-Kickback and Fee-Splitting Prohibitions', 'Prohibits giving or accepting any fee, kickback, or thing of value for referral of settlement service business involving a federally related mortgage loan. Prohibits unearned fee-splitting — no portion of charge except for services actually performed. Affiliated Business Arrangements (AfBA) permitted only with written disclosure, no required use, and no referral fees. Criminal penalties: up to $10,000 fine and 1 year imprisonment per violation.', '["No person shall give or accept any fee, kickback, or thing of value for referral of settlement service business","No splitting of charges except for services actually performed","Affiliated Business Arrangement (AfBA) permitted only with: (1) written disclosure, (2) no required use, (3) no referral fee","Cooperative brokerage and referral arrangements between real estate agents permitted","Employer may pay employee for referrals","Criminal penalty: fine up to $10,000 and/or imprisonment up to 1 year per violation","Private right of action: treble damages (3x amount of kickback or fee)","Statute of limitations: 1 year from date of violation for private action","Attorney fees and costs available to prevailing plaintiff","Settlement services include: title, appraisal, lending, insurance, closing"]', '[{"section":"2607(a)","description":"Anti-kickback — no fee for referral of settlement service business"},{"section":"2607(b)","description":"Fee-splitting — no unearned fees or charges"},{"section":"2607(c)(1)","description":"AfBA safe harbor — disclosure, no required use, no referral fee"},{"section":"2607(c)(2)","description":"Cooperative brokerage permitted between real estate agents"},{"section":"2607(c)(3)","description":"Employer-employee payment for referrals permitted"},{"section":"2607(d)(1)","description":"Criminal penalty — $10,000 fine and/or 1 year imprisonment"},{"section":"2607(d)(2)","description":"Private action — treble damages of kickback or fee amount"},{"section":"2607(d)(5)","description":"Statute of limitations — 1 year from violation"}]', '["AfBA_disclosure","referral_agreement","settlement_service_agreement","closing_statement","marketing_services_agreement","HUD_complaint"]', '["banking-financial-document-audit"]', 'CFPB / HUD / DOJ', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — ECOA/Reg B
-- ═══════════════════════════════════════════════════════════════════════════

-- ECOA Prohibited Discrimination
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_056', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1691 (Equal Credit Opportunity Act — Prohibited Discrimination)', 'ECOA § 1691', 'ECOA Prohibited Discrimination — Equal Access to Credit', 'Prohibits creditors from discriminating against any applicant with respect to any aspect of a credit transaction on the basis of race, color, religion, national origin, sex, marital status, age, receipt of public assistance income, or good faith exercise of rights under the Consumer Credit Protection Act. Covers all types of credit: consumer, commercial, mortgage, credit cards. Regulation B (12 CFR § 1002) implements ECOA.', '["Cannot discriminate on basis of race, color, religion, national origin, sex, marital status, age","Cannot discriminate because all or part of income derives from public assistance","Cannot discriminate for good faith exercise of rights under Consumer Credit Protection Act","Cannot ask marital status on individual unsecured credit application (community property state exception)","Cannot ask about birth control, childbearing intentions, or family plans","Cannot require co-signer if applicant independently qualifies","Spouse signature cannot be required if applicant qualifies independently","Must consider public assistance income same as other income","Must consider part-time employment income","Must consider alimony, child support, separate maintenance income if applicant chooses to disclose","Cannot discount income because of sex, marital status, or source"]', '[{"section":"1691(a)(1)","description":"Prohibited bases: race, color, religion, national origin, sex, marital status, age"},{"section":"1691(a)(2)","description":"Prohibited basis: receipt of public assistance income"},{"section":"1691(a)(3)","description":"Prohibited basis: exercise of CCPA rights"},{"section":"1691(b)","description":"Permissible considerations — creditworthiness factors"},{"section":"1691(c)","description":"Special purpose credit programs permitted"},{"section":"12 CFR 1002.4","description":"Reg B — general rules on discrimination"},{"section":"12 CFR 1002.5","description":"Reg B — rules on taking applications"},{"section":"12 CFR 1002.6","description":"Reg B — rules on evaluating applications"},{"section":"12 CFR 1002.7","description":"Reg B — rules on extending credit — spouse signature restrictions"}]', '["credit_application","loan_application","adverse_action_notice","ECOA_complaint","CFPB_complaint","lending_policy","underwriting_guidelines"]', '["banking-financial-document-audit"]', 'CFPB / DOJ / Federal District Court', 1, 1, datetime('now'), datetime('now'));

-- ECOA Adverse Action Notice
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_057', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1691(d) (Equal Credit Opportunity Act — Adverse Action Notices)', 'ECOA § 1691(d)', 'ECOA Adverse Action Notice — Notification and Statement of Reasons', 'Creditor must notify applicant of adverse action within 30 days and provide statement of specific reasons for denial or termination. Must identify the specific reasons (not boilerplate) — e.g., insufficient income, excessive obligations, inadequate collateral. If credit scoring model used, must disclose key factors. Must provide notice of right to request reasons (if reasons not automatically provided). Regulation B requires ECOA notice on all applications.', '["Must notify applicant of adverse action within 30 days of taking action","Must provide statement of specific reasons for adverse action","Reasons must be specific — not generic boilerplate","If credit score used, must disclose score, range, and key factors adversely affecting score","Must provide name and address of ECOA enforcement agency","Adverse action includes: denial, termination, unfavorable change in terms, refusal to grant at requested amount","Counteroffer not accepted by applicant within reasonable time is adverse action","Must preserve records for 25 months (12 months for small businesses)","Applicant may request statement of reasons within 60 days of adverse action notice","If creditor provides notice of right to request reasons, must provide reasons within 30 days of request"]', '[{"section":"1691(d)(1)","description":"Notice of adverse action within 30 days"},{"section":"1691(d)(2)","description":"Statement of specific reasons for adverse action"},{"section":"1691(d)(3)","description":"Reasons statement — specific factors"},{"section":"1691(d)(6)","description":"Definition of adverse action"},{"section":"12 CFR 1002.9(a)","description":"Reg B — notification requirements within 30 days"},{"section":"12 CFR 1002.9(b)","description":"Reg B — content of notification — specific reasons or right to request"},{"section":"12 CFR 1002.9(c)","description":"Reg B — statement of specific reasons required"},{"section":"12 CFR 1002.12","description":"Reg B — record retention — 25 months"},{"section":"12 CFR 1002 App C","description":"Reg B — sample notification forms"}]', '["adverse_action_notice","credit_denial_letter","counteroffer_notice","credit_score_disclosure","credit_application","ECOA_notice"]', '["banking-financial-document-audit"]', 'CFPB / Federal District Court', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — Additional Standards
-- ═══════════════════════════════════════════════════════════════════════════

-- BSA/AML Reporting
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_058', 'FISCARA', 'FEDERAL_STATUTE', 'US', '31 USC §§ 5311-5332 (Bank Secrecy Act / Anti-Money Laundering)', 'BSA §§ 5311-5332', 'Bank Secrecy Act / Anti-Money Laundering — CTR and SAR Reporting', 'Requires financial institutions to assist government agencies in detecting and preventing money laundering. Currency Transaction Reports (CTR) required for cash transactions over $10,000. Suspicious Activity Reports (SAR) required when institution suspects transaction involves funds from illegal activity or is designed to evade BSA requirements. Structuring transactions to avoid CTR threshold (smurfing) is a federal crime. FinCEN administers BSA.', '["Currency Transaction Report (CTR) required for cash transactions over $10,000","CTR must be filed within 15 calendar days of transaction","Suspicious Activity Report (SAR) required for transactions suspected of involving illegal funds","SAR must be filed within 30 calendar days of detection (60 days if no suspect identified)","SAR filing is confidential — institution may not notify subject of SAR","Structuring: breaking transactions to avoid $10,000 CTR threshold is federal crime","Customer Identification Program (CIP) required — verify identity of account holders","Customer Due Diligence (CDD) rule: identify and verify beneficial owners (25%+ ownership)","Record retention: 5 years for CTRs, SARs, and CDD records","Anti-money laundering (AML) compliance program required: internal controls, compliance officer, training, independent testing","Penalties: civil up to $1M per violation; criminal up to $500K fine and 10 years imprisonment"]', '[{"section":"5313","description":"Currency Transaction Reports — cash transactions over $10,000"},{"section":"5318(g)","description":"Suspicious Activity Reports — transactions involving suspected illegal funds"},{"section":"5318(h)","description":"AML compliance program requirements"},{"section":"5318(l)","description":"Customer Identification Program (CIP)"},{"section":"5324","description":"Structuring prohibition — circumventing CTR requirements"},{"section":"5321","description":"Civil penalties — up to $1M per violation"},{"section":"5322","description":"Criminal penalties — up to $500K and 10 years"},{"section":"5332","description":"Bulk cash smuggling — transporting over $10,000 undeclared"},{"section":"31 CFR 1010.230","description":"Beneficial ownership / CDD rule — 25% ownership threshold"},{"section":"31 CFR 1020.320","description":"SAR filing requirements and timeframes"}]', '["CTR_report","SAR_report","CIP_documentation","CDD_beneficial_ownership","AML_compliance_program","transaction_monitoring_alert","suspicious_transaction_report"]', '["banking-financial-document-audit"]', 'FinCEN / OCC / FDIC / Federal Reserve / DOJ', 0, 1, datetime('now'), datetime('now'));

-- Escheat/Unclaimed Property
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_059', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Code Civ. Proc. §§ 1500-1599 (Unclaimed Property Law)', 'CCP §§ 1500-1599', 'California Unclaimed Property Law — Escheat and Holder Obligations', 'Requires holders of unclaimed property (banks, corporations, insurers, government entities) to report and deliver unclaimed property to the California State Controller after specified dormancy periods. Bank accounts dormant 3 years, uncashed checks 3 years, wages 1 year, safe deposit boxes 3 years. Holder must send due diligence notice to owner before reporting. Owner may claim property from Controller at any time — no statute of limitations.', '["Bank accounts: 3-year dormancy period","Uncashed checks and money orders: 3 years","Wages and payroll: 1 year","Safe deposit box contents: 3 years","Insurance proceeds: 3 years from due date","Holder must send written due diligence notice to last known address 6-12 months before reporting","Report filed annually with State Controller by November 1","Holder must deliver property to Controller with report","Controller publishes notice of unclaimed property","Owner may claim property from Controller at any time — no time limit","Holder immune from liability after delivery to Controller","Penalties for failure to report: 12% per annum interest + $100-$500 per day","Controller may examine holder records"]', '[{"section":"1510","description":"General dormancy period — 3 years for most property"},{"section":"1513","description":"Bank deposits and funds — 3-year dormancy"},{"section":"1514","description":"Uncashed checks and outstanding drafts — 3 years"},{"section":"1516","description":"Insurance proceeds — 3 years"},{"section":"1519","description":"Safe deposit box contents — 3 years"},{"section":"1520","description":"Wages, commissions, and other compensation — 1 year"},{"section":"1530","description":"Holder report to Controller — annual by November 1"},{"section":"1531","description":"Due diligence notice — 6-12 months before report date"},{"section":"1540","description":"Owner claim from Controller — no time limit"},{"section":"1577","description":"Controller authority to examine holder records"},{"section":"1576","description":"Penalties for failure to report"}]', '["unclaimed_property_report","due_diligence_notice","owner_claim_form","dormancy_review","Controller_audit_notice","holder_compliance_report"]', '["banking-financial-document-audit"]', 'California State Controller''s Office', 0, 1, datetime('now'), datetime('now'));

-- CA Homeowner Bill of Rights
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_060', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 2920.5-2944.7 (California Homeowner Bill of Rights)', 'CC §§ 2920.5-2944.7', 'California Homeowner Bill of Rights — Foreclosure Protections', 'Provides comprehensive foreclosure protections for California homeowners. Prohibits dual tracking — servicer cannot advance foreclosure while borrower has pending loan modification application. Requires single point of contact for borrowers in default. Guarantees right to appeal loan modification denial. Prohibits recording Notice of Default until 30 days after initial contact or due diligence. Material violations provide injunctive relief before sale; after sale, treble actual damages.', '["Prohibition on dual tracking — cannot record NOD or NTS while complete loan modification application pending","Single point of contact required for borrowers in default","Right to appeal loan modification denial","Servicer must contact borrower 30 days before recording NOD to explore alternatives","Must assess borrower for all available loss mitigation options","Cannot record NOD until 30 days after initial contact or due diligence requirements met","Written determination on loan modification within 30 days of receiving complete application","If approved for trial modification, permanent modification must be offered if trial completed","Must provide written notice of denial with specific reasons","Borrower may appeal denial — servicer must respond within 15 days","Before sale: injunctive relief available for material violation","After sale: treble actual damages for material violation"]', '[{"section":"2923.4","description":"Material compliance standard"},{"section":"2923.5","description":"Pre-NOD contact requirement — 30 days before recording"},{"section":"2923.55","description":"Due diligence before NOD — letter with loss mitigation options"},{"section":"2923.6","description":"Prohibition on dual tracking — no foreclosure during modification review"},{"section":"2923.6(d)","description":"Right to appeal loan modification denial"},{"section":"2923.7","description":"Single point of contact requirement"},{"section":"2924.9","description":"Written notice of foreclosure prevention alternatives"},{"section":"2924.10","description":"Acknowledgment of loan modification documents within 5 business days"},{"section":"2924.11","description":"Prohibition on recording NTS while modification under review"},{"section":"2924.12","description":"Enforcement — injunctive relief before sale, treble damages after sale"},{"section":"2924.17","description":"Declaration of compliance required with NOD and NTS"}]', '["Notice_of_Default","Notice_of_Trustee_Sale","loan_modification_application","single_point_of_contact_notice","modification_denial","modification_appeal","forbearance_agreement","declaration_of_compliance"]', '["banking-financial-document-audit"]', 'California Superior Court / DFPI / CA AG', 1, 1, datetime('now'), datetime('now'));

-- Servicemembers Civil Relief Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_061', 'FISCARA', 'FEDERAL_STATUTE', 'US', '50 USC §§ 3901-4043 (Servicemembers Civil Relief Act)', 'SCRA §§ 3901-4043', 'Servicemembers Civil Relief Act — Financial Protections for Military', 'Provides comprehensive financial protections for active duty servicemembers, including 6% interest rate cap on pre-service debts, protection from default judgments, stay of proceedings, protection from non-judicial foreclosure, and limits on repossession. Covers all active duty military, National Guard/Reserve on federal active duty, and in some provisions dependents. Protections generally apply from date of active duty orders through period of military service plus applicable post-service lookback.', '["6% interest rate cap on pre-service obligations — including mortgages, credit cards, auto loans","Creditor must forgive interest exceeding 6% — not defer","Protection from default judgment — court must appoint attorney before entry","Stay of civil proceedings — court must grant upon request if service materially affects ability","No non-judicial foreclosure during service and 12 months after (extended from 9 months)","No repossession of property without court order during service","Lease termination right: may terminate residential or vehicle lease upon deployment or PCS","Protection of life insurance: SGLI coverage, no lapse during service","No penalties or adverse credit reporting for exercising SCRA rights","Servicemember must provide written notice and copy of military orders to invoke protections","DOJ may bring civil action for pattern or practice violations","Private right of action with actual damages, declaratory and injunctive relief"]', '[{"section":"3937","description":"Maximum rate of interest — 6% on pre-service obligations"},{"section":"3931","description":"Protection against default judgments — attorney appointment"},{"section":"3932","description":"Stay of proceedings upon application"},{"section":"3953","description":"Mortgage foreclosure protection — no non-judicial foreclosure during service + 12 months"},{"section":"3952","description":"No installment contract repossession without court order"},{"section":"3955","description":"Residential and vehicle lease termination right"},{"section":"3956","description":"Cell phone contract termination right"},{"section":"3958","description":"Professional liability protection — malpractice insurance tolling"},{"section":"3998","description":"Fine up to $55,000 for first violation, $110,000 for subsequent"},{"section":"4042","description":"Private right of action — actual damages, declaratory and injunctive relief"}]', '["military_orders","SCRA_interest_rate_request","lease_termination_notice","stay_of_proceedings_motion","foreclosure_protection_notice","default_judgment_affidavit","DOJ_complaint"]', '["banking-financial-document-audit"]', 'DOJ / Federal District Court', 1, 1, datetime('now'), datetime('now'));
