-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 10
-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS expansion: CCPA detail, HIPAA detail, TCPA, FERPA, COPPA,
-- CAN-SPAM, RFPA, VPPA, DPPA, GLB, CalOPPA, CA breach notification,
-- CMIA, CA Invasion of Privacy, SOPIPA, GDPR cross-references.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — CCPA Detail (California Consumer Privacy Act)
-- ═══════════════════════════════════════════════════════════════════════════

-- CCPA Right to Know (CC §1798.100)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_009', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.100', 'CC § 1798.100', 'CCPA Right to Know — Consumer Access to Personal Information', 'A consumer has the right to request that a business that collects personal information disclose the categories and specific pieces of personal information it has collected about that consumer. Businesses must disclose the categories of sources, the business or commercial purpose for collecting or selling, and the categories of third parties with whom the business shares personal information. Requests must be responded to within 45 days, with one 45-day extension permitted. Businesses must provide information for the preceding 12-month period and may not require a consumer to create an account to make a verifiable request.', '["Disclose categories of personal information collected","Disclose specific pieces of personal information collected","Disclose categories of sources from which PI was collected","Disclose business or commercial purpose for collecting/selling","Disclose categories of third parties with whom PI is shared","Respond to verifiable consumer requests within 45 days","May extend response period by additional 45 days with notice","Provide information for preceding 12-month period","Provide two or more designated methods for submitting requests","Free of charge for first two requests in a 12-month period"]', '[{"section":"1798.100(a)","description":"Right to request disclosure of personal information collected"},{"section":"1798.100(b)","description":"Business obligation to disclose upon verifiable request"},{"section":"1798.100(c)","description":"Prohibition on collecting additional categories without notice"},{"section":"1798.100(d)","description":"Requirement to provide information free of charge"}]', '["privacy_policy","consumer_request_form","data_inventory","DSAR_response","verifiable_consumer_request"]', '["privacy-data-protection-audit"]', 'California Attorney General / California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CCPA Right to Delete (CC §1798.105)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_010', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.105', 'CC § 1798.105', 'CCPA Right to Delete — Consumer Deletion Requests', 'A consumer has the right to request that a business delete any personal information about the consumer which the business has collected from the consumer. Upon receiving a verifiable consumer request, the business must delete the consumer''s personal information from its records and direct any service providers to delete the consumer''s personal information from their records. Nine statutory exceptions permit retention, including completing transactions, detecting security incidents, exercising free speech, complying with legal obligations, and internal uses reasonably aligned with consumer expectations.', '["Delete personal information upon verifiable consumer request","Direct service providers to delete consumer PI","Respond within 45 days of receiving request","Notify consumer of exceptions if deletion is denied","Nine statutory exceptions to deletion requirement","Must verify identity of consumer making request","Cannot require account creation for deletion request","Must provide at least two methods for submitting requests"]', '[{"section":"1798.105(a)","description":"Consumer right to request deletion"},{"section":"1798.105(b)","description":"Business obligation to comply and exceptions"},{"section":"1798.105(c)","description":"Business obligation to direct service provider deletion"},{"section":"1798.105(d)","description":"Enumerated exceptions to deletion"}]', '["deletion_request","DSAR_response","data_retention_policy","service_provider_agreement","deletion_confirmation"]', '["privacy-data-protection-audit"]', 'California Attorney General / California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CCPA Right to Opt-Out of Sale (CC §1798.120)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_011', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.120', 'CC § 1798.120', 'CCPA Right to Opt-Out of Sale of Personal Information', 'A consumer has the right, at any time, to direct a business that sells or shares personal information about the consumer to third parties not to sell or share the consumer''s personal information. Businesses must provide a clear and conspicuous "Do Not Sell or Share My Personal Information" link on their website homepage. Businesses must wait at least 12 months before requesting that a consumer who has opted out authorize the sale of their personal information again. Businesses may not sell the personal information of consumers under 16 without affirmative authorization.', '["Provide clear Do Not Sell or Share My Personal Information link","Honor opt-out requests immediately","Wait 12 months before requesting re-authorization to sell","Do not sell PI of consumers under 16 without opt-in consent","Consumers 13-15 must provide affirmative opt-in","Parent/guardian consent required for consumers under 13","Do not discriminate against consumers who opt out","Respect Global Privacy Control signals as valid opt-out"]', '[{"section":"1798.120(a)","description":"Consumer right to opt out of sale/sharing"},{"section":"1798.120(b)","description":"Business obligation to honor opt-out"},{"section":"1798.120(c)","description":"Prohibition on selling PI of minors without opt-in"},{"section":"1798.120(d)","description":"12-month waiting period before re-solicitation"}]', '["opt_out_request","privacy_policy","Do_Not_Sell_page","consent_record","GPC_signal_log","minor_consent_form"]', '["privacy-data-protection-audit"]', 'California Attorney General / California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CCPA Right to Non-Discrimination (CC §1798.125)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_012', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.125', 'CC § 1798.125', 'CCPA Right to Non-Discrimination for Exercising Privacy Rights', 'A business shall not discriminate against a consumer because the consumer exercised any of their CCPA rights. Prohibited discrimination includes denying goods or services, charging different prices or rates, providing a different level or quality of goods or services, or suggesting the consumer will receive a different price or quality. Businesses may offer financial incentives for the collection, sale, or deletion of personal information if the incentive is reasonably related to the value of the consumer''s data and disclosed in a notice of financial incentive.', '["Do not deny goods or services to consumers exercising rights","Do not charge different prices for exercising rights","Do not provide different quality or level of service","Do not suggest different treatment for exercising rights","Financial incentives must be reasonably related to data value","Financial incentive programs require opt-in consent","Notice of financial incentive must be provided","Consumer may withdraw from incentive program at any time"]', '[{"section":"1798.125(a)(1)","description":"Prohibition on discriminatory practices"},{"section":"1798.125(a)(2)","description":"Permitted price differentials related to data value"},{"section":"1798.125(b)(1)","description":"Financial incentive programs — opt-in requirement"},{"section":"1798.125(b)(2)","description":"Notice of financial incentive requirements"}]', '["non_discrimination_policy","financial_incentive_notice","pricing_policy","loyalty_program_terms","consumer_complaint"]', '["privacy-data-protection-audit"]', 'California Attorney General / California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CPRA Amendments — Right to Correct (CC §1798.106)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_013', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.106', 'CC § 1798.106', 'CPRA Right to Correct Inaccurate Personal Information', 'Added by the California Privacy Rights Act (CPRA, Proposition 24, effective January 1, 2023), this section grants consumers the right to request that a business correct inaccurate personal information that the business maintains about the consumer. Businesses must use commercially reasonable efforts to correct the information as directed by the consumer and must instruct service providers and contractors to make corrections in their records. Businesses may delay or deny correction if the request cannot be verified, but must explain the basis for denial.', '["Correct inaccurate personal information upon verified request","Use commercially reasonable efforts to make corrections","Instruct service providers and contractors to correct records","Respond to correction requests within 45 days","May extend response by additional 45 days with notice","Document basis for denial if correction is refused","Consider totality of circumstances in determining accuracy","Provide at least two designated methods for submitting requests"]', '[{"section":"1798.106(a)","description":"Consumer right to request correction of inaccurate PI"},{"section":"1798.106(b)","description":"Business obligation to correct upon verifiable request"},{"section":"1798.106(c)","description":"Commercially reasonable efforts standard"},{"section":"1798.106(d)","description":"Obligation to direct service provider correction"}]', '["correction_request","DSAR_response","data_quality_policy","service_provider_agreement","correction_confirmation"]', '["privacy-data-protection-audit"]', 'California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CPRA — Sensitive Personal Information (CC §1798.121)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_014', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.121', 'CC § 1798.121', 'CPRA Right to Limit Use and Disclosure of Sensitive Personal Information', 'Added by the CPRA, this section grants consumers the right to direct a business that collects sensitive personal information to limit its use to that which is necessary to perform the services or provide the goods reasonably expected by an average consumer. Sensitive PI includes Social Security numbers, driver''s license numbers, financial account information, precise geolocation, racial/ethnic origin, religious beliefs, union membership, mail/email/text contents, genetic data, biometric data, health information, and sex life/sexual orientation data. Businesses must provide a clear link titled "Limit the Use of My Sensitive Personal Information."', '["Provide Limit the Use of My Sensitive Personal Information link","Limit use of sensitive PI to what is necessary for expected services","Sensitive PI includes SSN, DL, financial accounts, precise geolocation","Sensitive PI includes race, religion, union membership, genetic/biometric data","Sensitive PI includes health data, sex life, mail/email/text contents","Do not use sensitive PI for profiling without consent","Direct service providers to limit use of sensitive PI","Honor limit requests immediately upon receipt"]', '[{"section":"1798.121(a)","description":"Consumer right to limit use of sensitive PI"},{"section":"1798.121(b)","description":"Business obligation to restrict processing upon request"},{"section":"1798.121(c)","description":"Service provider obligations regarding sensitive PI"},{"section":"1798.121(d)","description":"Exceptions for certain necessary processing"}]', '["sensitive_PI_inventory","limit_use_request","privacy_policy","consent_record","data_processing_agreement","Limit_Use_page"]', '["privacy-data-protection-audit"]', 'California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CCPA Service Provider Obligations (CC §1798.140(ag))
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_015', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.140(ag)', 'CC § 1798.140(ag)', 'CCPA Service Provider Obligations — Contractual and Processing Restrictions', 'A service provider is a person or entity that processes personal information on behalf of a business pursuant to a written contract. Service providers must not retain, use, or disclose personal information for any purpose other than performing the services specified in the contract, including retaining, using, or disclosing PI for a commercial purpose other than providing the contracted services. The written contract must prohibit the service provider from selling or sharing the PI, combining PI received from the business with PI from other sources, and using PI outside the direct business relationship.', '["Written contract required between business and service provider","Prohibit retention/use/disclosure outside contracted services","Prohibit selling or sharing received personal information","Prohibit combining PI with data from other sources","Certify understanding of CCPA restrictions","Permit business to monitor compliance","Notify business if unable to meet CCPA obligations","Cooperate with consumer rights requests from the business"]', '[{"section":"1798.140(ag)(1)","description":"Definition of service provider"},{"section":"1798.140(ag)(2)","description":"Written contract requirements"},{"section":"1798.140(ag)(3)","description":"Prohibition on selling/sharing received PI"},{"section":"1798.140(ag)(4)","description":"Prohibition on combining PI from multiple sources"}]', '["service_provider_agreement","data_processing_addendum","vendor_assessment","CCPA_compliance_certification","PI_flow_map"]', '["privacy-data-protection-audit"]', 'California Attorney General / California Privacy Protection Agency', 0, 1, datetime('now'), datetime('now'));

-- CCPA Private Right of Action — Data Breach (CC §1798.150)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_016', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.150', 'CC § 1798.150', 'CCPA Private Right of Action for Data Breaches', 'Any consumer whose nonencrypted and nonredacted personal information is subject to an unauthorized access and exfiltration, theft, or disclosure as a result of the business''s violation of the duty to implement and maintain reasonable security procedures and practices may institute a civil action. Statutory damages range from $100 to $750 per consumer per incident, or actual damages, whichever is greater. This is the only section of the CCPA that provides a private right of action. The consumer must provide 30 days written notice to the business before filing suit, allowing the business to cure the violation.', '["Private right of action for data breaches only","Applies to nonencrypted and nonredacted PI","Business must have failed to maintain reasonable security","Statutory damages: $100-$750 per consumer per incident","Or actual damages, whichever is greater","30-day notice and cure period required before filing","Court may award injunctive or declaratory relief","Class action suits permitted under this section"]', '[{"section":"1798.150(a)(1)","description":"Private right of action for unauthorized access/disclosure"},{"section":"1798.150(a)(2)","description":"Damages: statutory $100-$750 or actual"},{"section":"1798.150(b)","description":"30-day notice and cure period"},{"section":"1798.150(c)","description":"Attorney General notification requirement for class actions"}]', '["breach_notification","incident_response_plan","security_assessment","30_day_cure_notice","class_action_complaint","data_breach_report"]', '["privacy-data-protection-audit"]', 'California Superior Courts / California Attorney General', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — HIPAA Detail
-- ═══════════════════════════════════════════════════════════════════════════

-- HIPAA Privacy Rule (45 CFR Part 160, 164 Subpart E)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_017', 'PRIVAXIS', 'FEDERAL_REGULATION', 'US', '45 CFR Part 160; 45 CFR Part 164, Subpart E', '45 CFR §§ 164.500-534', 'HIPAA Privacy Rule — Standards for Protection of Individually Identifiable Health Information', 'The HIPAA Privacy Rule establishes national standards to protect individuals'' medical records and other individually identifiable health information (protected health information, or PHI). It applies to health plans, health care clearinghouses, and health care providers who conduct standard electronic transactions (covered entities), as well as their business associates. The rule requires appropriate safeguards to protect the privacy of PHI, sets limits on the uses and disclosures that may be made of such information without individual authorization, and gives individuals rights over their health information.', '["Designate a Privacy Officer responsible for compliance","Develop and implement written privacy policies and procedures","Provide Notice of Privacy Practices to all patients","Obtain individual authorization for uses/disclosures not permitted or required","Apply minimum necessary standard to uses and disclosures","Train all workforce members on privacy policies","Implement administrative, technical, and physical safeguards","Maintain documentation of compliance efforts for six years","Establish complaint process for privacy violations","Conduct risk assessments of privacy practices"]', '[{"section":"164.502","description":"Uses and disclosures of PHI — general rules"},{"section":"164.508","description":"Uses and disclosures for which authorization is required"},{"section":"164.510","description":"Uses and disclosures requiring opportunity to agree or object"},{"section":"164.512","description":"Uses and disclosures for which consent/authorization not required"},{"section":"164.520","description":"Notice of Privacy Practices"},{"section":"164.530","description":"Administrative requirements — policies, training, safeguards"}]', '["Notice_of_Privacy_Practices","authorization_form","privacy_policy","workforce_training_record","risk_assessment","complaint_log","BAA"]', '["privacy-data-protection-audit"]', 'HHS Office for Civil Rights (OCR)', 0, 1, datetime('now'), datetime('now'));

-- HIPAA Security Rule (45 CFR Part 164 Subpart C)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_018', 'PRIVAXIS', 'FEDERAL_REGULATION', 'US', '45 CFR Part 164, Subpart C', '45 CFR §§ 164.302-318', 'HIPAA Security Rule — Standards for Protection of Electronic PHI', 'The HIPAA Security Rule establishes national standards to protect electronic protected health information (ePHI) that is created, received, used, or maintained by a covered entity or business associate. It requires appropriate administrative, physical, and technical safeguards to ensure the confidentiality, integrity, and availability of ePHI. The rule is flexible and scalable, allowing covered entities to adopt measures appropriate to their size, complexity, and capabilities. Standards are designated as either "required" or "addressable" implementation specifications.', '["Conduct thorough risk analysis of ePHI vulnerabilities","Implement risk management program to reduce identified risks","Designate a Security Officer responsible for compliance","Implement workforce security — authorization and access controls","Implement security awareness and training program","Establish contingency plan: data backup, disaster recovery, emergency operations","Implement audit controls to record and examine ePHI access","Implement access controls: unique user identification, encryption, auto-logoff","Implement transmission security: integrity controls and encryption","Implement facility access controls and workstation security"]', '[{"section":"164.308","description":"Administrative safeguards — risk analysis, management, training"},{"section":"164.310","description":"Physical safeguards — facility access, workstation, device security"},{"section":"164.312","description":"Technical safeguards — access controls, audit, integrity, transmission"},{"section":"164.314","description":"Organizational requirements — BAAs and group health plans"},{"section":"164.316","description":"Documentation requirements — policies, procedures, retention"}]', '["risk_analysis","security_policy","contingency_plan","audit_log","access_control_policy","encryption_policy","BAA","workforce_training_record","incident_response_plan"]', '["privacy-data-protection-audit"]', 'HHS Office for Civil Rights (OCR)', 0, 1, datetime('now'), datetime('now'));

-- HIPAA Breach Notification Rule (45 CFR §§ 164.400-414)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_019', 'PRIVAXIS', 'FEDERAL_REGULATION', 'US', '45 CFR §§ 164.400-414', '45 CFR §§ 164.400-414', 'HIPAA Breach Notification Rule', 'The Breach Notification Rule requires HIPAA covered entities and their business associates to provide notification following a breach of unsecured protected health information. A breach is defined as an impermissible use or disclosure under the Privacy Rule that compromises the security or privacy of PHI. An exception exists where a covered entity or business associate demonstrates a low probability that the PHI has been compromised based on a four-factor risk assessment. Individual notifications must be provided without unreasonable delay and no later than 60 calendar days from discovery of the breach.', '["Notify affected individuals within 60 days of breach discovery","Notify HHS Secretary — immediately if 500+ individuals affected","Notify HHS Secretary annually if fewer than 500 affected","Notify prominent media outlets if 500+ individuals in a state affected","Conduct four-factor risk assessment to determine if breach occurred","Business associates must notify covered entities within 60 days","Individual notice must be written and sent by first-class mail","Substitute notice permitted when contact information is insufficient","Maintain breach log for incidents affecting fewer than 500 individuals"]', '[{"section":"164.400","description":"Applicability of breach notification requirements"},{"section":"164.402","description":"Definition of breach and exceptions"},{"section":"164.404","description":"Notification to individuals"},{"section":"164.406","description":"Notification to media for breaches affecting 500+"},{"section":"164.408","description":"Notification to HHS Secretary"},{"section":"164.410","description":"Business associate notification to covered entity"},{"section":"164.414","description":"Administrative requirements and burden of proof"}]', '["breach_notification_letter","HHS_breach_report","risk_assessment","breach_log","media_notification","incident_response_report"]', '["privacy-data-protection-audit"]', 'HHS Office for Civil Rights (OCR)', 0, 1, datetime('now'), datetime('now'));

-- HIPAA Right of Access (45 CFR § 164.524)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_020', 'PRIVAXIS', 'FEDERAL_REGULATION', 'US', '45 CFR § 164.524', '45 CFR § 164.524', 'HIPAA Individual Right of Access to Protected Health Information', 'Individuals have the right to inspect and obtain a copy of their protected health information in a designated record set maintained by or for a covered entity. The covered entity must act on a request within 30 days (one 30-day extension permitted). The copy must be provided in the form and format requested if readily producible, or in a readable hard copy. Fees must be limited to reasonable, cost-based amounts for labor, supplies, and postage. HHS OCR has made enforcement of the Right of Access a priority through its Right of Access Initiative, resulting in numerous settlements.', '["Provide access to PHI within 30 days of request","One 30-day extension permitted with written notice","Provide PHI in form and format requested if readily producible","Fees limited to reasonable cost-based amounts","May not charge for search and retrieval time","Must provide copy to designated third party if requested","Only limited grounds for denial exist","Must provide written denial with basis and appeal rights","Maintain documentation of requests and responses"]', '[{"section":"164.524(a)","description":"Right of access — scope and exceptions"},{"section":"164.524(b)","description":"Requirements for request and timely action"},{"section":"164.524(c)","description":"Provision of access — form, format, fees"},{"section":"164.524(d)","description":"Grounds for denial — reviewable and unreviewable"},{"section":"164.524(e)","description":"Documentation requirements"}]', '["medical_records_request","access_denial_letter","fee_schedule","PHI_release_form","third_party_designation","appeal_record"]', '["privacy-data-protection-audit"]', 'HHS Office for Civil Rights (OCR)', 0, 1, datetime('now'), datetime('now'));

-- HIPAA Minimum Necessary Standard (45 CFR § 164.502(b))
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_021', 'PRIVAXIS', 'FEDERAL_REGULATION', 'US', '45 CFR § 164.502(b); 45 CFR § 164.514(d)', '45 CFR § 164.502(b)', 'HIPAA Minimum Necessary Standard', 'When using or disclosing protected health information or when requesting PHI from another covered entity or business associate, a covered entity must make reasonable efforts to limit PHI to the minimum necessary to accomplish the intended purpose. This principle does not apply to disclosures to or requests by a health care provider for treatment, disclosures to the individual who is the subject of the information, uses or disclosures pursuant to an individual''s authorization, disclosures to HHS for compliance investigations, or uses or disclosures required by law.', '["Limit PHI uses and disclosures to minimum necessary","Identify workforce members needing access and categories of PHI needed","Implement policies for routine and non-routine disclosures","For routine requests, limit to reasonably necessary categories","For non-routine requests, review individually on case-by-case basis","Does not apply to treatment disclosures between providers","Does not apply to disclosures to the individual subject","Does not apply to uses pursuant to individual authorization","Reasonable reliance on requesting party is permitted"]', '[{"section":"164.502(b)(1)","description":"Minimum necessary standard for uses"},{"section":"164.502(b)(2)","description":"Minimum necessary standard for disclosures and requests"},{"section":"164.514(d)(1)","description":"Minimum necessary — uses by covered entity"},{"section":"164.514(d)(2)","description":"Minimum necessary — routine disclosures"},{"section":"164.514(d)(3)","description":"Minimum necessary — non-routine disclosures"},{"section":"164.514(d)(4)","description":"Minimum necessary — requests for PHI"},{"section":"164.514(d)(5)","description":"Reasonable reliance exception"}]', '["role_based_access_policy","PHI_access_matrix","disclosure_log","workforce_access_roster","minimum_necessary_policy"]', '["privacy-data-protection-audit"]', 'HHS Office for Civil Rights (OCR)', 0, 1, datetime('now'), datetime('now'));

-- HIPAA Business Associate Requirements (45 CFR § 164.502(e))
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_022', 'PRIVAXIS', 'FEDERAL_REGULATION', 'US', '45 CFR § 164.502(e); 45 CFR § 164.504(e)', '45 CFR § 164.502(e)', 'HIPAA Business Associate Agreement Requirements', 'A covered entity may disclose PHI to a business associate and may allow a business associate to create, receive, maintain, or transmit PHI on its behalf only if the covered entity obtains satisfactory assurances through a written Business Associate Agreement (BAA). The BAA must establish the permitted and required uses and disclosures of PHI, require the BA to implement appropriate safeguards, require reporting of breaches and security incidents, and ensure that subcontractors agree to the same restrictions. Since the HITECH Act, business associates are directly liable for HIPAA compliance.', '["Execute written Business Associate Agreement before sharing PHI","BAA must specify permitted uses and disclosures of PHI","BAA must require appropriate safeguards for PHI","BAA must require BA to report breaches and security incidents","BAA must require BA to ensure subcontractors comply","BAA must require BA to make PHI available for individual access rights","BAA must require return or destruction of PHI upon termination","Covered entity must take action upon knowledge of BA violation","Business associates directly liable under HITECH Act","Maintain inventory of all business associate relationships"]', '[{"section":"164.502(e)(1)","description":"Requirement for business associate agreement"},{"section":"164.502(e)(2)","description":"Exception — not required when disclosure is to provider for treatment"},{"section":"164.504(e)(1)","description":"BAA required before any disclosure to BA"},{"section":"164.504(e)(2)","description":"Required provisions of BAA"},{"section":"164.504(e)(3)","description":"Covered entity obligations regarding BA compliance"},{"section":"164.504(e)(4)","description":"Termination and cure provisions"}]', '["BAA","vendor_inventory","subcontractor_agreement","breach_reporting_protocol","PHI_flow_map","BA_compliance_assessment"]', '["privacy-data-protection-audit"]', 'HHS Office for Civil Rights (OCR)', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — TCPA Detail
-- ═══════════════════════════════════════════════════════════════════════════

-- TCPA Autodialer Restrictions (47 USC § 227(b))
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_023', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '47 USC § 227(b)', '47 USC § 227(b)', 'TCPA Restrictions on Use of Automatic Telephone Dialing Systems and Prerecorded Messages', 'The Telephone Consumer Protection Act prohibits making calls using an automatic telephone dialing system (ATDS) or an artificial or prerecorded voice to wireless telephone numbers, emergency lines, hospital patient rooms, and similar services without prior express consent. Following the Supreme Court''s decision in Facebook v. Duguid (2021), an ATDS is defined as equipment with the capacity to store or produce telephone numbers using a random or sequential number generator and to dial such numbers. Prior express written consent is required for telemarketing calls; prior express consent is required for non-marketing calls.', '["No ATDS calls to wireless numbers without prior express consent","Prior express written consent required for telemarketing via ATDS","No prerecorded/artificial voice calls to residential lines without consent","No calls to emergency lines (911), hospital rooms, or similar services","Caller must provide automated opt-out mechanism during prerecorded calls","Opt-out must be available throughout the duration of the call","ATDS defined per Facebook v. Duguid: random/sequential number generator","Exemptions for emergency calls and calls with prior express consent","Must honor revocation of consent by any reasonable means"]', '[{"section":"227(b)(1)(A)","description":"Prohibition on ATDS/prerecorded calls to emergency lines"},{"section":"227(b)(1)(B)","description":"Prohibition on prerecorded calls to residential lines"},{"section":"227(b)(1)(C)","description":"Prohibition on ATDS calls to cell phones without consent"},{"section":"227(b)(2)","description":"FCC authority to exempt certain calls"},{"section":"227(b)(3)","description":"Private right of action — $500 per violation, trebled for willful"}]', '["consent_record","ATDS_compliance_policy","call_log","opt_out_record","written_consent_form","telemarketing_script"]', '["privacy-data-protection-audit"]', 'Federal Communications Commission (FCC)', 1, 1, datetime('now'), datetime('now'));

-- TCPA Do-Not-Call Provisions (47 USC § 227(c))
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_024', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '47 USC § 227(c)', '47 USC § 227(c)', 'TCPA Do-Not-Call Registry and Company-Specific Do-Not-Call Lists', 'The TCPA requires the FCC to establish regulations for protecting residential telephone subscribers'' privacy rights, including a national Do-Not-Call (DNC) registry. Telemarketers must scrub their call lists against the National Do-Not-Call Registry maintained by the FTC. Companies must also maintain their own internal do-not-call lists of consumers who request not to be called. The company-specific DNC list must be honored for five years. Violations may be enforced by state attorneys general and through private right of action for actual monetary loss or $500 per violation.', '["Scrub call lists against National DNC Registry before calling","Maintain company-specific do-not-call list","Honor company-specific DNC requests for five years","Process DNC requests within 30 days","Train personnel engaged in telephone solicitation on DNC procedures","Maintain written DNC compliance procedures","Identify seller and purpose at beginning of each call","Provide telephone number or address for DNC requests","Update National DNC Registry data at least every 31 days"]', '[{"section":"227(c)(1)","description":"FCC authority to establish DNC regulations"},{"section":"227(c)(2)","description":"Company-specific do-not-call requirements"},{"section":"227(c)(3)","description":"National Do-Not-Call Registry regulations"},{"section":"227(c)(5)","description":"Private right of action — $500 per violation"}]', '["DNC_compliance_policy","call_list_scrub_record","internal_DNC_list","training_record","telemarketing_script","DNC_request_log"]', '["privacy-data-protection-audit"]', 'Federal Communications Commission (FCC) / Federal Trade Commission (FTC)', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — Other Federal Privacy
-- ═══════════════════════════════════════════════════════════════════════════

-- FERPA — Education Records Privacy (20 USC § 1232g)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_025', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '20 USC § 1232g', '20 USC § 1232g', 'Family Educational Rights and Privacy Act (FERPA)', 'FERPA protects the privacy of student education records. It applies to all educational agencies and institutions that receive funds under any program administered by the U.S. Department of Education. FERPA gives parents rights to access their children''s education records, request corrections, and control disclosures. These rights transfer to the student upon reaching 18 years of age or attending a postsecondary institution (eligible student). Schools must have written permission from the parent or eligible student before releasing any information from a student''s education record, subject to enumerated exceptions.', '["Annual notification of rights to parents and eligible students","Allow inspection and review of education records within 45 days","Provide opportunity to request amendment of inaccurate records","Obtain written consent before disclosing personally identifiable information","Maintain record of each disclosure request and to whom disclosed","Directory information may be disclosed only with proper notice and opt-out","FERPA exceptions: school officials with legitimate educational interest","FERPA exceptions: transfer schools, financial aid, accreditation, health/safety","Must comply to maintain eligibility for federal education funding"]', '[{"section":"1232g(a)(1)","description":"Right to inspect and review education records"},{"section":"1232g(a)(2)","description":"Right to request amendment and hearing"},{"section":"1232g(b)(1)","description":"Prohibition on disclosure without consent"},{"section":"1232g(b)(1)(A-J)","description":"Exceptions to consent requirement"},{"section":"1232g(b)(2)","description":"Disclosure requirements and recordkeeping"},{"section":"1232g(d)","description":"Student access rights at postsecondary institutions"}]', '["annual_FERPA_notice","consent_to_release_form","education_record","disclosure_log","directory_information_notice","opt_out_form","amendment_request"]', '["privacy-data-protection-audit"]', 'U.S. Department of Education — Family Policy Compliance Office', 0, 1, datetime('now'), datetime('now'));

-- COPPA — Children's Online Privacy (15 USC §§ 6501-6506)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_026', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '15 USC §§ 6501-6506; 16 CFR Part 312', '15 USC §§ 6501-6506', 'Children''s Online Privacy Protection Act (COPPA)', 'COPPA imposes requirements on operators of websites and online services directed to children under 13 years of age, and on operators of other websites or online services that have actual knowledge they are collecting personal information from children under 13. Operators must provide notice of information practices, obtain verifiable parental consent before collecting personal information from children, give parents the ability to review and delete their child''s information, and maintain the confidentiality, security, and integrity of children''s personal information. The FTC Rule (16 CFR Part 312) implements the statute.', '["Post clear and comprehensive online privacy policy","Provide direct notice to parents before collection","Obtain verifiable parental consent before collecting PI from children under 13","Allow parents to review child''s personal information","Allow parents to revoke consent and require deletion","Do not condition child''s participation on disclosure of more PI than necessary","Maintain confidentiality, security, and integrity of children''s PI","Retain children''s PI only as long as reasonably necessary","Applies to actual knowledge of collection from children under 13","Safe harbor programs available through FTC-approved self-regulatory guidelines"]', '[{"section":"6502(a)","description":"Prohibition on unfair/deceptive collection from children"},{"section":"6502(b)","description":"FTC rulemaking authority and required regulations"},{"section":"6502(b)(1)(A)","description":"Notice requirements"},{"section":"6502(b)(1)(B)","description":"Verifiable parental consent"},{"section":"6502(b)(1)(C)","description":"Parental access to child''s information"},{"section":"6502(b)(1)(D)","description":"Data minimization for children''s PI"},{"section":"6505","description":"State AG enforcement authority"}]', '["children_privacy_policy","parental_consent_form","age_verification_mechanism","parental_access_request","data_retention_policy","COPPA_compliance_assessment"]', '["privacy-data-protection-audit"]', 'Federal Trade Commission (FTC)', 0, 1, datetime('now'), datetime('now'));

-- CAN-SPAM Act (15 USC §§ 7701-7713)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_027', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '15 USC §§ 7701-7713; 16 CFR Part 316', '15 USC §§ 7701-7713', 'CAN-SPAM Act — Controlling the Assault of Non-Solicited Pornography and Marketing', 'The CAN-SPAM Act establishes requirements for commercial electronic mail messages, gives recipients the right to stop receiving commercial emails, and spells out penalties for violations. It applies to all commercial messages — defined as any electronic mail message the primary purpose of which is the commercial advertisement or promotion of a commercial product or service. The Act does not require opt-in consent but mandates opt-out mechanisms. The FTC enforces the Act and has issued implementing regulations at 16 CFR Part 316. CAN-SPAM preempts state laws that regulate commercial email except for fraud and computer crime statutes.', '["Do not use false or misleading header information","Do not use deceptive subject lines","Identify the message as an advertisement","Include valid physical postal address of sender","Provide clear and conspicuous opt-out mechanism","Honor opt-out requests within 10 business days","Do not sell or transfer email addresses of opted-out recipients","Do not use harvested email addresses","Monitor compliance by third parties sending on your behalf","Each separate email in violation constitutes a separate offense"]', '[{"section":"7704(a)(1)","description":"Prohibition on false/misleading transmission information"},{"section":"7704(a)(2)","description":"Prohibition on deceptive subject headings"},{"section":"7704(a)(3)","description":"Inclusion of return address or opt-out mechanism"},{"section":"7704(a)(4)","description":"Prohibition on transmission after opt-out"},{"section":"7704(a)(5)","description":"Identification and physical address requirements"},{"section":"7704(b)","description":"Aggravated violations — harvesting, dictionary attacks, unauthorized relay"},{"section":"7706","description":"Enforcement by FTC, state AGs, and ISPs"}]', '["email_marketing_policy","opt_out_mechanism","email_compliance_checklist","suppression_list","sender_information_record","third_party_monitoring_log"]', '["privacy-data-protection-audit"]', 'Federal Trade Commission (FTC)', 0, 1, datetime('now'), datetime('now'));

-- Right to Financial Privacy Act (12 USC §§ 3401-3422)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_028', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '12 USC §§ 3401-3422', '12 USC §§ 3401-3422', 'Right to Financial Privacy Act (RFPA)', 'The Right to Financial Privacy Act protects the confidentiality of personal financial records by creating a statutory Fourth Amendment protection for bank records. It establishes procedures that federal government authorities must follow when seeking to obtain customers'' financial records from financial institutions. No government authority may have access to the financial records of any customer from a financial institution unless the records are reasonably described and obtained through one of five authorized access methods: customer authorization, administrative subpoena, search warrant, judicial subpoena, or formal written request.', '["Financial records accessible only through five authorized methods","Customer authorization must be knowing and voluntary","Customer must receive notice of government access request","Customer has right to challenge access in court within 10 days","Financial institutions must maintain records of disclosures to government","Government must certify records are relevant to legitimate law enforcement inquiry","Records must be reasonably described in the access request","Customer may authorize access — must be signed and dated","Financial institution may challenge if request is unduly burdensome"]', '[{"section":"3402","description":"Access only through authorized procedures"},{"section":"3403","description":"Confidentiality and prohibition on disclosure"},{"section":"3404","description":"Customer authorization requirements"},{"section":"3405","description":"Administrative subpoena and summons"},{"section":"3406","description":"Search warrant requirements"},{"section":"3407","description":"Judicial subpoena requirements"},{"section":"3408","description":"Formal written request requirements"},{"section":"3410","description":"Customer challenge procedures"},{"section":"3417","description":"Civil penalties for violations"}]', '["customer_authorization","government_access_request","financial_records_subpoena","customer_notice","challenge_motion","disclosure_log"]', '["privacy-data-protection-audit"]', 'U.S. Department of the Treasury / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Cable Communications Privacy Act (47 USC § 551)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_029', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '47 USC § 551', '47 USC § 551', 'Cable Communications Policy Act — Subscriber Privacy Protections', 'Section 551 of the Cable Communications Policy Act of 1984 governs the collection and disclosure of personally identifiable information by cable operators. Cable operators must provide subscribers with a notice of privacy practices at the time of entering into a service agreement and at least once annually thereafter. Cable operators may not collect personally identifiable information without prior written or electronic consent except as necessary to render service or detect unauthorized reception. Subscribers have the right to access and correct their personally identifiable information. Statutory damages of not less than $1,000 or actual damages, whichever is greater.', '["Provide written privacy notice at subscription and annually","Obtain prior consent before collecting PI beyond service necessity","Do not disclose PI without subscriber consent or court order","Destroy PI when no longer necessary for collected purpose","Allow subscriber access to their PI within 30 days","Allow subscriber to correct inaccurate PI","Government access requires court order with clear and convincing evidence","Maintain only PI necessary for legitimate business activity"]', '[{"section":"551(a)","description":"Privacy notice requirements — at subscription and annually"},{"section":"551(b)","description":"Limitations on collection of PI"},{"section":"551(c)","description":"Limitations on disclosure of PI"},{"section":"551(d)","description":"Subscriber access to PI"},{"section":"551(e)","description":"Destruction of PI when no longer needed"},{"section":"551(f)","description":"Civil action — $1,000 statutory damages minimum"},{"section":"551(h)","description":"Government access — court order requirement"}]', '["privacy_notice","subscriber_consent_form","PI_collection_policy","subscriber_access_request","data_destruction_record","court_order"]', '["privacy-data-protection-audit"]', 'Federal Communications Commission (FCC) / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Video Privacy Protection Act (18 USC § 2710)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_030', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '18 USC § 2710', '18 USC § 2710', 'Video Privacy Protection Act (VPPA)', 'The VPPA prohibits a video tape service provider from knowingly disclosing personally identifiable information concerning any consumer of the provider without the consumer''s informed, written consent. Enacted in response to the disclosure of Judge Robert Bork''s video rental records during his Supreme Court confirmation hearings. The Act applies to any person engaged in the business of rental, sale, or delivery of prerecorded video cassette tapes or similar audio visual materials, which courts have extended to cover streaming services. Provides for actual damages of not less than $2,500, punitive damages, attorneys'' fees, and equitable relief.', '["Do not disclose PI of consumers without informed written consent","Consent must be separate and distinct from any other legal agreement","Consent may be given electronically per 2012 amendment","Destroy PI within one year after it is no longer necessary","PI includes information identifying a person as having requested specific materials","Law enforcement access requires warrant, court order, or grand jury subpoena","Actual damages minimum $2,500 per violation","Punitive damages available","Attorneys'' fees and costs recoverable"]', '[{"section":"2710(a)","description":"Definitions — video tape service provider, consumer, PI"},{"section":"2710(b)(1)","description":"Prohibition on disclosure without consent"},{"section":"2710(b)(2)","description":"Permitted disclosures — consent, law enforcement, court order"},{"section":"2710(c)","description":"Civil action — $2,500 minimum, punitive damages, attorneys'' fees"},{"section":"2710(e)","description":"Destruction requirement — one year after no longer necessary"}]', '["consumer_consent_form","video_rental_records","disclosure_log","data_destruction_record","law_enforcement_request","privacy_policy"]', '["privacy-data-protection-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Driver's Privacy Protection Act (18 USC §§ 2721-2725)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_031', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '18 USC §§ 2721-2725', '18 USC §§ 2721-2725', 'Driver''s Privacy Protection Act (DPPA)', 'The DPPA prohibits the knowing disclosure or use of personal information obtained from state motor vehicle records for any purpose not permitted by the Act. Enacted in 1994 after the murder of actress Rebecca Schaeffer, whose address was obtained from California DMV records. The Act restricts state DMVs and their officers, employees, and contractors from disclosing personal information from motor vehicle records. Fourteen enumerated permissible uses exist, including use by government agencies, motor vehicle safety, licensed private investigators, and with the express consent of the person. Liquidated damages of not less than $2,500 per violation.', '["State DMVs may not disclose personal information from motor vehicle records","Fourteen enumerated permissible uses for disclosure","Express consent of the individual is a permissible use","Resale or redisclosure must be for permitted purposes only","Criminal penalties: fines for knowing violations","Civil action: liquidated damages not less than $2,500 per violation","Punitive damages and attorneys'' fees available","State and federal officials subject to Act","Motor vehicle records include name, address, phone, SSN, DL number, photo"]', '[{"section":"2721(a)","description":"Prohibition on disclosure of PI from motor vehicle records"},{"section":"2721(b)","description":"Fourteen permissible uses for disclosure"},{"section":"2722","description":"Additional unlawful acts — false representation to obtain records"},{"section":"2723","description":"Criminal fine for knowing violations"},{"section":"2724","description":"Civil action — $2,500 liquidated damages, punitive, attorneys'' fees"},{"section":"2725","description":"Definitions — motor vehicle record, personal information"}]', '["DMV_records_request","consent_form","permissible_use_certification","disclosure_log","motor_vehicle_record","privacy_policy"]', '["privacy-data-protection-audit"]', 'U.S. Department of Justice / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Gramm-Leach-Bliley Privacy Provisions (15 USC §§ 6801-6809)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_032', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '15 USC §§ 6801-6809; 16 CFR Part 314', '15 USC §§ 6801-6809', 'Gramm-Leach-Bliley Act — Financial Privacy Provisions', 'Title V of the Gramm-Leach-Bliley Act (GLB Act) requires financial institutions to explain their information-sharing practices to customers and to safeguard sensitive data. The Financial Privacy Rule (Regulation P, 12 CFR Part 1016) governs the collection and disclosure of customers'' personal financial information by financial institutions. The Safeguards Rule (16 CFR Part 314, updated 2023) requires financial institutions to develop, implement, and maintain a comprehensive information security program. Financial institutions must provide initial and annual privacy notices and allow customers to opt out of sharing nonpublic personal information with nonaffiliated third parties.', '["Provide initial privacy notice at customer relationship establishment","Provide annual privacy notice to customers","Allow opt-out of sharing NPI with nonaffiliated third parties","Do not disclose account numbers to nonaffiliated third parties for marketing","Develop comprehensive written information security program","Designate qualified individual to oversee security program","Conduct risk assessments of customer information","Implement safeguards to control identified risks","Regularly test and monitor effectiveness of safeguards","Oversee service providers by requiring contractual security obligations","Maintain incident response plan"]', '[{"section":"6801","description":"Protection of nonpublic personal information — policy declaration"},{"section":"6802","description":"Obligations with respect to disclosures of personal information"},{"section":"6803","description":"Disclosure of institution privacy policy — initial and annual"},{"section":"6804","description":"Rulemaking authority — functional regulators"},{"section":"6805","description":"Enforcement — federal banking agencies, SEC, FTC, state insurance"},{"section":"6809","description":"Definitions — financial institution, nonpublic personal information"}]', '["privacy_notice","opt_out_form","information_security_program","risk_assessment","safeguards_policy","vendor_oversight_record","incident_response_plan","annual_privacy_notice"]', '["privacy-data-protection-audit"]', 'FTC / Federal Banking Agencies / SEC / State Insurance Authorities', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — California State Privacy
-- ═══════════════════════════════════════════════════════════════════════════

-- CalOPPA — Online Privacy Protection (BPC §§ 22575-22579)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_033', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 22575-22579', 'BPC §§ 22575-22579', 'California Online Privacy Protection Act (CalOPPA)', 'CalOPPA was the first state law in the nation to require commercial websites and online services to conspicuously post a privacy policy. It applies to any operator of a commercial website or online service that collects personally identifiable information through the internet about individual consumers residing in California who use or visit the commercial website or online service. The law requires the privacy policy to identify the categories of PII collected, categories of third parties with whom information may be shared, the process for reviewing and requesting changes to PII, how the operator notifies consumers of material changes, and the effective date of the policy.', '["Conspicuously post privacy policy on website or online service","Identify categories of PII collected","Identify categories of third parties with whom PII may be shared","Describe process for consumer to review and request changes to PII","Describe how operator notifies consumers of material policy changes","Include effective date of the privacy policy","Disclose how operator responds to Do Not Track signals","Disclose whether third parties may collect PII across sites","Must comply within 30 days of being notified of noncompliance"]', '[{"section":"22575(a)","description":"Conspicuous posting requirement"},{"section":"22575(b)","description":"Required content of privacy policy"},{"section":"22575(b)(5)","description":"Effective date requirement"},{"section":"22575(b)(6)","description":"Do Not Track disclosure"},{"section":"22575(b)(7)","description":"Third-party tracking disclosure"},{"section":"22577","description":"Definitions — operator, PII, conspicuously post"}]', '["privacy_policy","website_compliance_audit","DNT_disclosure","PII_inventory","privacy_policy_changelog"]', '["privacy-data-protection-audit"]', 'California Attorney General', 0, 1, datetime('now'), datetime('now'));

-- CA Data Breach Notification (CC § 1798.82)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_034', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.82', 'CC § 1798.82', 'California Data Breach Notification Law', 'California''s data breach notification statute requires any person or business that conducts business in California, and that owns or licenses computerized data that includes personal information, to disclose a breach of the security of the system to any resident of California whose unencrypted personal information was, or is reasonably believed to have been, acquired by an unauthorized person. Notification must be made in the most expedient time possible and without unreasonable delay. Personal information includes name plus SSN, DL number, financial account numbers, medical information, health insurance information, or biometric data. Notification must be in a specific format prescribed by statute.', '["Notify affected California residents of breach in most expedient time possible","Notification without unreasonable delay","Must use prescribed statutory format for notification","Include name and contact information of notifying entity","Describe types of PI subject to breach","General description of the breach incident","Date or estimated date of breach","Toll-free telephone numbers of major credit reporting agencies if SSN/DL","If 500+ residents affected, submit sample notification to Attorney General","Encryption is a safe harbor — encrypted data not covered"]', '[{"section":"1798.82(a)","description":"Notification obligation and timing"},{"section":"1798.82(b)","description":"Methods of notification — written, electronic, substitute"},{"section":"1798.82(d)","description":"Required content of notification"},{"section":"1798.82(e)","description":"Definition of personal information"},{"section":"1798.82(f)","description":"AG notification if 500+ affected"},{"section":"1798.82(g)","description":"Encryption safe harbor"}]', '["breach_notification_letter","AG_notification","incident_response_plan","breach_assessment","credit_monitoring_offer","data_inventory"]', '["privacy-data-protection-audit"]', 'California Attorney General', 0, 1, datetime('now'), datetime('now'));

-- CA Constitutional Right to Privacy (Art. I, § 1)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_035', 'PRIVAXIS', 'CONSTITUTIONAL', 'CA', 'Cal. Const., Art. I, § 1', 'Art. I, § 1', 'California Constitutional Right to Privacy', 'Article I, Section 1 of the California Constitution enumerates privacy as an inalienable right alongside life, liberty, and the pursuit of happiness. Added by voter initiative (Proposition 11) in 1972, it was intended to constrain both government and private entities. Unlike the federal constitutional right to privacy, California''s constitutional privacy right applies to private actors as well as state actors. Under Hill v. National Collegiate Athletic Assn. (1994) 7 Cal.4th 1, a plaintiff must establish: (1) a legally protected privacy interest, (2) a reasonable expectation of privacy, and (3) a serious invasion of privacy. The defendant may assert the invasion was justified by a competing interest.', '["Privacy is an inalienable right under California Constitution","Applies to both government AND private actors","Three-part test from Hill v. NCAA: legally protected interest, reasonable expectation, serious invasion","Defendant may justify invasion with competing interest","Covers informational privacy — control of personal information","Covers autonomy privacy — freedom to make personal decisions","Applies to employment, medical records, financial information, surveillance","Broader protection than federal Fourth Amendment","Ballot argument: prevent government and business snooping"]', '[{"section":"Art. I, § 1","description":"All people have inalienable rights including privacy"},{"section":"Hill v. NCAA (1994)","description":"Three-part test for privacy claims against private actors"},{"section":"Prop. 11 (1972)","description":"Voter initiative adding privacy as inalienable right"}]', '["privacy_impact_assessment","constitutional_challenge","privacy_complaint","surveillance_policy","employee_monitoring_policy","data_collection_notice"]', '["privacy-data-protection-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- Confidentiality of Medical Information Act (CC §§ 56-56.37)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_036', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 56-56.37', 'CC §§ 56-56.37', 'Confidentiality of Medical Information Act (CMIA)', 'The California Confidentiality of Medical Information Act (CMIA) restricts the disclosure of medical information by health care providers, health care service plans (insurers), and contractors. It provides protections that in many respects exceed HIPAA. The CMIA prohibits any provider of health care, health care service plan, or contractor from disclosing medical information regarding a patient without first obtaining an authorization from the patient, except as specified. Authorizations must be handwritten by the patient or in a typeface no smaller than 14-point type. Negligent release results in $1,000 nominal damages; willful violation results in $5,000 plus actual damages and attorneys'' fees.', '["Do not disclose medical information without patient authorization","Authorization must be handwritten or 14-point type minimum","Authorization must specify who may disclose, what may be disclosed, and to whom","Employer must establish procedure to preserve confidentiality","Employer cannot use medical information for employment discrimination","Medical information includes mental health and substance abuse records","Patient may revoke authorization at any time","$1,000 nominal damages for negligent release","$5,000 per violation plus actual damages for willful disclosure","Applies to providers, plans, contractors, and employers"]', '[{"section":"56.10","description":"Prohibition on disclosure without authorization"},{"section":"56.11","description":"Authorization requirements — form and content"},{"section":"56.13","description":"Employer confidentiality requirements"},{"section":"56.20","description":"Provider obligation to preserve confidentiality"},{"section":"56.26","description":"Pharmaceutical company restrictions"},{"section":"56.35","description":"Negligent disclosure — $1,000 nominal damages"},{"section":"56.36","description":"Willful disclosure — $5,000 plus actual damages and fees"}]', '["patient_authorization_form","medical_information_policy","employer_confidentiality_policy","breach_report","CMIA_compliance_audit","disclosure_log"]', '["privacy-data-protection-audit"]', 'California Courts / California Department of Managed Health Care', 1, 1, datetime('now'), datetime('now'));

-- CA Invasion of Privacy Act (PC §§ 630-638)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_037', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code §§ 630-638', 'PC §§ 630-638', 'California Invasion of Privacy Act (CIPA) — Wiretapping and Electronic Surveillance', 'The California Invasion of Privacy Act is one of the strongest electronic surveillance protection statutes in the nation. California is a "two-party consent" state — all parties to a confidential communication must consent to its recording. Section 631 prohibits wiretapping or intentionally recording confidential telephone communications without the consent of all parties. Section 632 prohibits eavesdropping or recording confidential communications by any means without consent of all parties. Violations are punishable as misdemeanors and carry a private right of action for the greater of $5,000 per violation or three times actual damages.', '["All-party consent required for recording confidential communications","No wiretapping of telephone or telegraph communications (§ 631)","No eavesdropping or recording without all-party consent (§ 632)","No interception of cellular/cordless telephone communications (§ 632.5)","No recording of telephone communications without beep tone warning (§ 632.7)","No intentional recording of confidential communications by eavesdropping device","Criminal penalties: fine up to $2,500 and/or one year imprisonment","Civil damages: $5,000 per violation or three times actual damages","Evidence obtained in violation is inadmissible","Exemptions for law enforcement with court order"]', '[{"section":"630","description":"Legislative declaration — right to privacy in communications"},{"section":"631","description":"Wiretapping prohibition — telephone/telegraph"},{"section":"632","description":"Eavesdropping on or recording confidential communications"},{"section":"632.5","description":"Cellular and cordless telephone communications"},{"section":"632.7","description":"Recording telephone communications without all parties'' consent"},{"section":"635","description":"Criminal penalties — misdemeanor"},{"section":"637.2","description":"Civil action — $5,000 or treble damages"}]', '["call_recording_policy","consent_notice","wiretap_order","surveillance_policy","communication_monitoring_policy","employee_notice"]', '["privacy-data-protection-audit"]', 'California District Attorneys / California Courts', 1, 1, datetime('now'), datetime('now'));

-- Student Online Personal Information Protection Act (BPC § 22584)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_038', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 22584-22584.5', 'BPC § 22584', 'Student Online Personal Information Protection Act (SOPIPA)', 'SOPIPA prohibits operators of websites, online services, online applications, or mobile applications designed and marketed for K-12 school purposes from using student information for non-educational purposes. The Act was the first of its kind in the nation and has served as a model for similar legislation in other states. Operators may not use covered information for targeted advertising directed to students, build advertising profiles, sell student information, or disclose covered information except for legitimate school purposes. The operator must implement and maintain reasonable security procedures and delete covered information upon request from the school or district.', '["Do not use covered information for targeted advertising to K-12 students","Do not build advertising profiles on K-12 students","Do not sell K-12 student information","Do not disclose covered information except for school purposes","Implement and maintain reasonable security procedures","Delete covered information upon school/district request","Do not use covered information to amass non-educational profiles","Allow school/district to access and correct student information","Security practices must protect against unauthorized access","Transparency about data collection and use practices"]', '[{"section":"22584(a)","description":"Prohibition on targeted advertising to students"},{"section":"22584(b)","description":"Prohibition on building advertising profiles"},{"section":"22584(c)","description":"Prohibition on selling student information"},{"section":"22584(d)","description":"Prohibition on unauthorized disclosure"},{"section":"22584(e)","description":"Requirement for reasonable security procedures"},{"section":"22584(f)","description":"Deletion upon school/district request"},{"section":"22584.5","description":"Permitted uses and disclosures"}]', '["student_data_policy","vendor_agreement","data_deletion_request","security_assessment","school_data_inventory","SOPIPA_compliance_certification"]', '["privacy-data-protection-audit"]', 'California Attorney General', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — International Cross-Reference
-- ═══════════════════════════════════════════════════════════════════════════

-- GDPR Right to Erasure (Art. 17)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_039', 'PRIVAXIS', 'INTERNATIONAL', 'EU', 'Regulation (EU) 2016/679, Article 17', 'GDPR Art. 17', 'GDPR Right to Erasure ("Right to Be Forgotten")', 'Article 17 of the General Data Protection Regulation grants data subjects the right to obtain from the controller the erasure of personal data concerning them without undue delay. The controller must erase the data where: the data is no longer necessary for its original purpose, the data subject withdraws consent and there is no other legal ground, the data subject objects under Art. 21 and there are no overriding legitimate grounds, the data has been unlawfully processed, or erasure is required to comply with a legal obligation. Where the controller has made the data public, it must take reasonable steps to inform other controllers processing the data that the data subject has requested erasure. Exceptions exist for exercising the right of freedom of expression, compliance with legal obligations, public health, archiving in the public interest, and establishment/exercise/defense of legal claims.', '["Erase personal data without undue delay upon request","Applies when data no longer necessary for original purpose","Applies when consent is withdrawn and no other legal basis exists","Applies when data subject objects and no overriding grounds exist","Applies when data was unlawfully processed","If data was made public, inform other controllers of erasure request","Take reasonable steps considering available technology and cost","Exceptions: freedom of expression, legal obligations, public health","Exceptions: archiving in public interest, scientific/historical research","Exceptions: establishment, exercise, or defense of legal claims","Respond within one month, extendable by two months for complex requests"]', '[{"section":"Art. 17(1)(a)","description":"Data no longer necessary for collection purpose"},{"section":"Art. 17(1)(b)","description":"Withdrawal of consent"},{"section":"Art. 17(1)(c)","description":"Data subject objects under Art. 21"},{"section":"Art. 17(1)(d)","description":"Unlawful processing"},{"section":"Art. 17(1)(e)","description":"Legal obligation to erase"},{"section":"Art. 17(2)","description":"Obligation to inform other controllers"},{"section":"Art. 17(3)","description":"Exceptions to right to erasure"}]', '["erasure_request","data_processing_record","consent_record","controller_notification","DPIA","privacy_policy","ROPA"]', '["privacy-data-protection-audit"]', 'EU Data Protection Authorities / European Data Protection Board', 1, 1, datetime('now'), datetime('now'));

-- GDPR Data Subject Access Rights (Art. 15)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_040', 'PRIVAXIS', 'INTERNATIONAL', 'EU', 'Regulation (EU) 2016/679, Article 15', 'GDPR Art. 15', 'GDPR Right of Access by the Data Subject', 'Article 15 of the GDPR grants data subjects the right to obtain from the controller confirmation as to whether personal data concerning them is being processed, and where that is the case, access to the personal data and specified information. The controller must provide a copy of the personal data undergoing processing free of charge. For further copies, the controller may charge a reasonable fee based on administrative costs. The information must be provided in a concise, transparent, intelligible, and easily accessible form, using clear and plain language. Response must be provided without undue delay and in any event within one month, extendable by two further months where necessary given the complexity and number of requests.', '["Confirm whether personal data is being processed","Provide access to all personal data being processed","Disclose purposes of the processing","Disclose categories of personal data concerned","Disclose recipients or categories of recipients","Disclose envisaged storage period or criteria for determining period","Inform of right to rectification, erasure, restriction, and objection","Inform of right to lodge complaint with supervisory authority","Provide information on source of data if not collected from data subject","Disclose existence of automated decision-making including profiling","Provide first copy free of charge","Respond within one month, extendable by two months for complex requests","Must not adversely affect rights and freedoms of others"]', '[{"section":"Art. 15(1)(a)","description":"Purposes of the processing"},{"section":"Art. 15(1)(b)","description":"Categories of personal data"},{"section":"Art. 15(1)(c)","description":"Recipients or categories of recipients"},{"section":"Art. 15(1)(d)","description":"Envisaged storage period"},{"section":"Art. 15(1)(e)","description":"Right to rectification, erasure, restriction, objection"},{"section":"Art. 15(1)(f)","description":"Right to lodge complaint with supervisory authority"},{"section":"Art. 15(1)(g)","description":"Source of data"},{"section":"Art. 15(1)(h)","description":"Automated decision-making and profiling"},{"section":"Art. 15(3)","description":"Provision of copy — first copy free"},{"section":"Art. 15(4)","description":"Must not adversely affect rights of others"}]', '["DSAR_response","data_inventory","processing_record","ROPA","privacy_notice","consent_record","automated_decision_disclosure"]', '["privacy-data-protection-audit"]', 'EU Data Protection Authorities / European Data Protection Board', 1, 1, datetime('now'), datetime('now'));
