-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 16
-- ═══════════════════════════════════════════════════════════════════════════
-- ICT Citizen expansion: INTEGRA (internal compliance/whistleblower),
-- SYNTARA (tech/cyber frameworks), VESTARA (investor/securities),
-- METRIQA (audit/analytics standards), CLARIDEX (financial disclosure),
-- NEXARIS (partnerships/antitrust).
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- INTEGRA — Internal Compliance & Whistleblower Protections
-- ═══════════════════════════════════════════════════════════════════════════

-- SOX Whistleblower
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_001', 'INTEGRA', 'FEDERAL_STATUTE', 'US', '18 USC § 1514A (Sarbanes-Oxley § 806)', 'SOX § 806', 'Sarbanes-Oxley Whistleblower Protections', 'Prohibits publicly traded companies from retaliating against employees who report securities fraud, shareholder fraud, or violations of SEC rules. Employee must file OSHA complaint within 180 days. Remedies include reinstatement, back pay, compensatory damages, and attorney fees. Covers employees of publicly traded companies and their contractors/subcontractors.', '["No retaliation for reporting securities fraud to supervisor, SEC, or Congress","Protected activity: reporting fraud, filing SEC complaint, testifying, assisting investigation","File OSHA complaint within 180 days of adverse action","Covers employees of public companies AND contractors/subcontractors","Remedies: reinstatement, back pay with interest, compensatory damages","Attorney fees and costs recoverable","Jury trial right if OSHA does not issue final decision within 180 days","Arbitration clauses void for SOX whistleblower claims"]', '[{"section":"1514A(a)","description":"Prohibited retaliation against whistleblowers"},{"section":"1514A(b)(1)","description":"OSHA complaint procedure — 180 days"},{"section":"1514A(b)(2)","description":"Federal court action if no OSHA decision"},{"section":"1514A(c)","description":"Remedies — reinstatement, back pay, compensatory damages"},{"section":"1514A(e)","description":"Nonenforceability of arbitration clauses"}]', '["whistleblower_complaint","OSHA_filing","SEC_tip_report","retaliation_claim","internal_compliance_report","SOX_complaint"]', '["internal-compliance-audit"]', 'OSHA / SEC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- CA Whistleblower — Labor Code
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_002', 'INTEGRA', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 1102.5-1105 (Whistleblower Protection)', 'LC §§ 1102.5-1105', 'California Whistleblower Protection Act', 'Broad whistleblower protection prohibiting employer retaliation against employees who disclose information about violations of law or refuse to participate in illegal activity. Covers disclosures to government agencies, law enforcement, or any person with authority to investigate. Rebuttable presumption of retaliation within 90 days. Includes protections for refusing to violate law.', '["Cannot retaliate for disclosing violation of state or federal law","Cannot retaliate for disclosing noncompliance with regulation","Cannot retaliate for refusal to participate in illegal activity","Disclosure may be to government agency, law enforcement, or supervisor with authority","Rebuttable presumption of retaliation within 90 days of protected activity","Remedies: reinstatement, back pay, civil penalty up to $10,000","Cannot prevent employee from disclosing information to government agency","Applies to all employers regardless of size"]', '[{"section":"1102.5(a)","description":"Protection for disclosing violation of law to government/authority"},{"section":"1102.5(b)","description":"Protection for disclosing noncompliance with regulation"},{"section":"1102.5(c)","description":"Protection for refusing to participate in illegal activity"},{"section":"1102.5(f)","description":"Rebuttable presumption of retaliation within 90 days"},{"section":"1102.5(h)","description":"Civil penalty up to $10,000 per violation"},{"section":"1103","description":"Cannot adopt rule preventing disclosure to government agency"},{"section":"1105","description":"No waiver of whistleblower rights in employment agreement"}]', '["whistleblower_complaint","retaliation_claim","DLSE_complaint","internal_report","government_agency_disclosure","employment_termination_record"]', '["internal-compliance-audit"]', 'California DLSE / Superior Court', 1, 1, datetime('now'), datetime('now'));

-- False Claims Act — Federal
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_003', 'INTEGRA', 'FEDERAL_STATUTE', 'US', '31 USC §§ 3729-3733 (False Claims Act — Qui Tam)', 'FCA / 31 USC §§ 3729-3733', 'Federal False Claims Act — Qui Tam Whistleblower Provisions', 'Allows private citizens (relators) to file lawsuits on behalf of the government against entities that defraud federal programs. Relator receives 15-30% of recovery. Triple damages plus civil penalties ($13,508-$27,018 per false claim as of 2024). Anti-retaliation provisions protect relators and anyone assisting FCA investigation.', '["Liability for knowingly submitting false claims to government","Liability for knowingly making false statements material to false claim","Triple damages plus civil penalty per false claim ($13,508-$27,018)","Qui tam: private citizen may file on behalf of government","Relator receives 15-25% if government intervenes, 25-30% if not","Complaint filed under seal for 60+ days while government investigates","Anti-retaliation: reinstatement, double back pay, attorney fees","6-year statute of limitations from violation, 3 years from discovery, max 10 years"]', '[{"section":"3729(a)","description":"Liability for false claims — 7 categories"},{"section":"3729(a)(1)","description":"Treble damages and civil penalties"},{"section":"3730(b)","description":"Qui tam filing procedures — under seal"},{"section":"3730(c)","description":"Government election to intervene"},{"section":"3730(d)","description":"Relator share — 15-30% of recovery"},{"section":"3730(h)","description":"Anti-retaliation — reinstatement, double back pay"},{"section":"3731(b)","description":"Statute of limitations — 6/3/10 year framework"}]', '["qui_tam_complaint","seal_filing","relator_share_petition","government_intervention_notice","false_claim_evidence","retaliation_claim","DOJ_civil_division_referral"]', '["internal-compliance-audit"]', 'DOJ Civil Division / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- CA False Claims Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_004', 'INTEGRA', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 12650-12656 (CA False Claims Act)', 'GC §§ 12650-12656', 'California False Claims Act — State Qui Tam', 'California equivalent of federal FCA. Treble damages plus $11,000 civil penalty per false claim. Qui tam provisions allow private citizens to file on behalf of the state. Broader than federal FCA — covers false claims submitted to any political subdivision including cities, counties, and special districts. Anti-retaliation provisions.', '["Treble damages plus $11,000 civil penalty per false claim","Qui tam provisions — private citizen files on behalf of state","Covers claims to state, county, city, and special districts","Relator share: 15-33% depending on government intervention","Anti-retaliation: reinstatement, double back pay, attorney fees","3-year SOL from discovery, max 10 years","AG must be served with copy of qui tam complaint","60-day seal period while government investigates"]', '[{"section":"12651(a)","description":"Liability for false claims to state/local government"},{"section":"12651(b)","description":"Treble damages and civil penalties"},{"section":"12652(c)","description":"Qui tam filing procedures"},{"section":"12652(d)","description":"Government election to intervene"},{"section":"12652(g)","description":"Relator share of recovery"},{"section":"12653","description":"Anti-retaliation protections"}]', '["qui_tam_complaint","AG_notification","false_claim_evidence","retaliation_claim","state_contract_fraud","Medi-Cal_fraud_evidence"]', '["internal-compliance-audit"]', 'CA Attorney General / County DAs', 1, 1, datetime('now'), datetime('now'));

-- SOX Internal Controls
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_005', 'INTEGRA', 'FEDERAL_STATUTE', 'US', 'Sarbanes-Oxley Act §§ 302, 404, 906 (15 USC § 7241, 7262)', 'SOX §§ 302/404/906', 'Sarbanes-Oxley Internal Controls and CEO/CFO Certification', 'Requires CEO and CFO to personally certify accuracy of financial statements and effectiveness of internal controls over financial reporting. Section 404 requires annual management assessment and independent auditor attestation of internal controls. Criminal penalties up to $5M fine and 20 years imprisonment for knowing certification of false financial statements.', '["CEO/CFO must certify financial statements are accurate (§ 302)","Must certify internal controls are effective (§ 302)","Annual management assessment of internal controls (§ 404(a))","Independent auditor attestation of internal controls (§ 404(b))","Disclosure of material weaknesses in internal controls","Criminal penalties: $1M fine/10 years (negligent), $5M/20 years (willful) (§ 906)","Audit committee must be independent directors","Audit committee financial expert required"]', '[{"section":"302","description":"CEO/CFO certification of financial statements and controls"},{"section":"404(a)","description":"Management assessment of internal controls"},{"section":"404(b)","description":"Auditor attestation of internal controls"},{"section":"906","description":"Criminal penalties for false certification"},{"section":"301","description":"Audit committee independence and responsibilities"},{"section":"303","description":"Improper influence on conduct of audits prohibited"}]', '["CEO_certification","CFO_certification","internal_controls_assessment","auditor_attestation_report","material_weakness_disclosure","audit_committee_charter","financial_statements"]', '["internal-compliance-audit"]', 'SEC / PCAOB / DOJ', 0, 1, datetime('now'), datetime('now'));

-- Federal Sentencing Guidelines — Compliance Programs
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_int_006', 'INTEGRA', 'FEDERAL_REGULATION', 'US', 'USSG §8B2.1 (Federal Sentencing Guidelines — Effective Compliance Program)', 'USSG § 8B2.1', 'Federal Sentencing Guidelines — Effective Compliance and Ethics Program', 'Defines what constitutes an effective compliance program for purposes of reduced criminal sentencing. Seven elements framework used by DOJ in corporate prosecution decisions. Having an effective compliance program can reduce culpability score and resulting fines by up to 95%.', '["Written compliance standards and procedures","Compliance officer and committee with adequate resources","Effective training and education programs","Monitoring and auditing systems","Reporting mechanisms including anonymous hotline","Consistent enforcement through disciplinary mechanisms","Response and remediation when violations detected","Due diligence in hiring and assigning compliance responsibilities","Periodic risk assessments","Board-level oversight of compliance program"]', '[{"section":"8B2.1(a)","description":"Due diligence and effective compliance program requirement"},{"section":"8B2.1(b)(1)","description":"Standards and procedures to prevent criminal conduct"},{"section":"8B2.1(b)(2)","description":"High-level oversight and compliance officer"},{"section":"8B2.1(b)(3)","description":"Due diligence in delegating authority"},{"section":"8B2.1(b)(4)","description":"Training and communication"},{"section":"8B2.1(b)(5)","description":"Monitoring, auditing, and reporting mechanisms"},{"section":"8B2.1(b)(6)","description":"Consistent enforcement and discipline"},{"section":"8B2.1(b)(7)","description":"Response to violations and remediation"}]', '["compliance_program_manual","code_of_conduct","training_records","hotline_log","risk_assessment","audit_report","disciplinary_records","board_compliance_minutes"]', '["internal-compliance-audit"]', 'DOJ / Federal Courts', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- SYNTARA — Technology & Cyber Compliance Frameworks
-- ═══════════════════════════════════════════════════════════════════════════

-- NIST Cybersecurity Framework
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_001', 'SYNTARA', 'PROFESSIONAL_STANDARD', 'US', 'NIST Cybersecurity Framework v2.0 (February 2024)', 'NIST CSF 2.0', 'NIST Cybersecurity Framework 2.0 — Govern, Identify, Protect, Detect, Respond, Recover', 'Voluntary framework for managing cybersecurity risk applicable to all organizations regardless of size or sector. Version 2.0 adds Govern function. Six core functions: Govern, Identify, Protect, Detect, Respond, Recover. Required for federal contractors and widely adopted as industry standard of care. Referenced in SEC cyber disclosure rules.', '["GOVERN: Establish cybersecurity risk management strategy, expectations, and policy","IDENTIFY: Understand organization''s assets, risks, and vulnerabilities","PROTECT: Implement safeguards to ensure delivery of critical services","DETECT: Develop and implement activities to identify cybersecurity events","RESPOND: Take action regarding detected cybersecurity incident","RECOVER: Maintain plans for resilience and restore capabilities after incident","Continuous improvement through organizational profiles and tiers","Supply chain risk management integrated across functions"]', '[{"section":"GV","description":"Govern — risk management strategy, roles, policies, oversight"},{"section":"ID","description":"Identify — asset management, risk assessment, supply chain"},{"section":"PR","description":"Protect — access control, training, data security, platform security"},{"section":"DE","description":"Detect — continuous monitoring, adverse event analysis"},{"section":"RS","description":"Respond — incident management, analysis, reporting, mitigation"},{"section":"RC","description":"Recover — recovery planning, improvement, communications"}]', '["cybersecurity_policy","risk_assessment","incident_response_plan","asset_inventory","access_control_matrix","security_training_records","recovery_plan","vendor_risk_assessment"]', '["technology-compliance-audit"]', 'NIST (voluntary) / Referenced by SEC, FTC, HHS', 0, 1, datetime('now'), datetime('now'));

-- SOC 2 Type II
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_002', 'SYNTARA', 'PROFESSIONAL_STANDARD', 'US', 'AICPA SOC 2 Type II (Trust Services Criteria — TSP 100)', 'SOC 2 Type II', 'SOC 2 Type II — Trust Services Criteria Examination', 'Service organization control report examining the design and operating effectiveness of controls over a period of time (typically 12 months). Based on five Trust Services Criteria: Security (required), Availability, Processing Integrity, Confidentiality, Privacy. Widely required by enterprise customers for SaaS/cloud vendors. Issued by independent CPA firm.', '["Security (CC): Protection against unauthorized access — REQUIRED","Availability (A): System available for operation and use as committed","Processing Integrity (PI): System processing is complete, valid, accurate, timely","Confidentiality (C): Information designated confidential is protected","Privacy (P): Personal information collected, used, retained, disclosed per notice","Controls tested for operating effectiveness over audit period","Independent CPA firm performs examination","Management assertion on control effectiveness","Complementary User Entity Controls (CUECs) identified"]', '[{"section":"CC1","description":"Control Environment — commitment to integrity and ethics"},{"section":"CC2","description":"Communication and Information — quality information, internal/external"},{"section":"CC3","description":"Risk Assessment — identify and assess risks"},{"section":"CC4","description":"Monitoring Activities — evaluate and communicate deficiencies"},{"section":"CC5","description":"Control Activities — select and develop controls"},{"section":"CC6","description":"Logical and Physical Access Controls"},{"section":"CC7","description":"System Operations — detect and manage processing anomalies"},{"section":"CC8","description":"Change Management"},{"section":"CC9","description":"Risk Mitigation — business disruption"}]', '["SOC_2_report","management_assertion","auditor_opinion","control_description","test_results","CUEC_listing","bridge_letter","penetration_test"]', '["technology-compliance-audit"]', 'AICPA (voluntary, market-driven)', 0, 1, datetime('now'), datetime('now'));

-- ISO 27001
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_003', 'SYNTARA', 'INTERNATIONAL', 'US', 'ISO/IEC 27001:2022 — Information Security Management Systems', 'ISO 27001:2022', 'ISO 27001 — Information Security Management System (ISMS)', 'International standard for establishing, implementing, maintaining, and continually improving an information security management system (ISMS). Requires risk assessment methodology, Statement of Applicability, and 93 controls organized in 4 themes. Certification by accredited audit body. Required by many government contracts and enterprise procurement.', '["Establish ISMS scope and context of the organization","Information security policy approved by top management","Risk assessment methodology and risk treatment plan","Statement of Applicability (SoA) — which of 93 controls apply","Leadership commitment and resource allocation","Competence, awareness, and communication requirements","Documented information management","Operational planning and control","Performance evaluation — monitoring, measurement, analysis","Internal audit program","Management review at planned intervals","Continual improvement through corrective actions"]', '[{"section":"4","description":"Context of the organization — scope, interested parties"},{"section":"5","description":"Leadership — policy, roles, responsibilities"},{"section":"6","description":"Planning — risk assessment, risk treatment, objectives"},{"section":"7","description":"Support — resources, competence, awareness, documentation"},{"section":"8","description":"Operation — risk treatment implementation"},{"section":"9","description":"Performance evaluation — monitoring, internal audit, management review"},{"section":"10","description":"Improvement — nonconformity, corrective action, continual improvement"},{"section":"Annex A","description":"93 controls in 4 themes: organizational, people, physical, technological"}]', '["ISMS_policy","risk_assessment","risk_treatment_plan","statement_of_applicability","internal_audit_report","management_review_minutes","corrective_action_records","certification_report"]', '["technology-compliance-audit"]', 'Accredited Certification Bodies (ANAB, UKAS)', 0, 1, datetime('now'), datetime('now'));

-- FedRAMP
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_004', 'SYNTARA', 'FEDERAL_REGULATION', 'US', 'FedRAMP Authorization Act (44 USC § 3607-3616) / NIST SP 800-53', 'FedRAMP', 'Federal Risk and Authorization Management Program', 'Government-wide program providing standardized approach to security authorization for cloud products and services used by federal agencies. Based on NIST SP 800-53 controls. Three impact levels: Low, Moderate, High. Authorization through JAB P-ATO or Agency ATO. FedRAMP Authorization Act (2022) codified program into law.', '["Cloud service provider must implement NIST 800-53 controls at appropriate impact level","System Security Plan (SSP) documenting all controls","Third-Party Assessment Organization (3PAO) independent assessment","Continuous monitoring including monthly vulnerability scanning","Annual assessment by 3PAO","Incident response within specified timelines","POA&M (Plan of Action and Milestones) for identified risks","Impact levels: Low (125 controls), Moderate (325 controls), High (421 controls)"]', '[{"section":"Low","description":"Low impact — 125 NIST 800-53 controls"},{"section":"Moderate","description":"Moderate impact — 325 controls — most common"},{"section":"High","description":"High impact — 421 controls — law enforcement, healthcare"},{"section":"JAB P-ATO","description":"Joint Authorization Board Provisional ATO"},{"section":"Agency ATO","description":"Agency-specific Authorization to Operate"},{"section":"ConMon","description":"Continuous monitoring requirements"}]', '["system_security_plan","security_assessment_report","POA_M","continuous_monitoring_report","vulnerability_scan","incident_response_plan","3PAO_assessment","ATO_letter"]', '["technology-compliance-audit"]', 'GSA FedRAMP PMO / Individual Federal Agencies', 0, 1, datetime('now'), datetime('now'));

-- CA SB 1386/AB 375 — Data Breach
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_005', 'SYNTARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1798.29, 1798.82 (Data Breach Notification)', 'CC §§ 1798.29/1798.82', 'California Data Breach Notification Requirements', 'Requires businesses and state agencies to notify California residents when unencrypted personal information is acquired by unauthorized person. Notification must be expedient and without unreasonable delay. If breach affects 500+ residents, must submit sample notification to AG. Specific format and content requirements for notification.', '["Notify affected individuals expeditiously without unreasonable delay","Notification must include: description of incident, types of information involved, steps taken, contact information, toll-free numbers for credit bureaus","If 500+ CA residents affected, submit sample notification to AG","Personal information: SSN, driver''s license, financial account numbers, medical/health information, login credentials","Encrypted data exemption if encryption key not compromised","Substitute notice permitted if cost exceeds $250K or affected individuals exceed 500K","12-month free identity theft prevention if SSN involved"]', '[{"section":"1798.29","description":"State agency breach notification requirements"},{"section":"1798.82(a)","description":"Business breach notification — expedient, without unreasonable delay"},{"section":"1798.82(d)","description":"Notification content requirements"},{"section":"1798.82(e)","description":"Personal information definition"},{"section":"1798.82(f)","description":"AG notification if 500+ CA residents"},{"section":"1798.82(g)","description":"Substitute notice provisions"},{"section":"1798.82(h)","description":"Identity theft prevention services if SSN involved"}]', '["breach_notification_letter","AG_notification","incident_response_report","forensic_investigation","identity_theft_service_enrollment","substitute_notice","credit_monitoring_offer"]', '["technology-compliance-audit"]', 'California AG / Superior Court', 1, 1, datetime('now'), datetime('now'));

-- CMMC
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_syn_006', 'SYNTARA', 'FEDERAL_REGULATION', 'US', '32 CFR Part 170 (CMMC — Cybersecurity Maturity Model Certification)', 'CMMC 2.0', 'Cybersecurity Maturity Model Certification — Defense Contractor Requirements', 'DoD program requiring defense contractors to implement cybersecurity practices and undergo third-party assessment. Three levels: Level 1 (self-assessment, 15 practices), Level 2 (C3PAO assessment, 110 NIST 800-171 practices), Level 3 (DIBCAC assessment, 110+ advanced practices). Required in DoD contracts starting 2025 phased implementation.', '["Level 1: 15 basic cyber hygiene practices — annual self-assessment","Level 2: 110 NIST SP 800-171 practices — triennial C3PAO assessment","Level 3: 110+ practices including NIST 800-172 select — DIBCAC assessment","System Security Plan (SSP) required at all levels","POA&M permitted for Level 2/3 with limitations","Controlled Unclassified Information (CUI) protection required","Phased implementation in DoD contracts starting 2025","Subcontractor flow-down requirements"]', '[{"section":"Level 1","description":"Foundational — 15 practices, self-assessment"},{"section":"Level 2","description":"Advanced — 110 NIST 800-171 practices, C3PAO assessment"},{"section":"Level 3","description":"Expert — 110+ practices, DIBCAC assessment"},{"section":"NIST 800-171","description":"Base control set for Level 2 (CUI protection)"},{"section":"SPRS","description":"Supplier Performance Risk System score submission"}]', '["SSP","POA_M","SPRS_score","C3PAO_assessment","self_assessment","CUI_marking_guide","incident_report","flow_down_clause"]', '["technology-compliance-audit"]', 'DoD CIO / DCMA DIBCAC / Accredited C3PAOs', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VESTARA — Investor Relations & Securities Compliance
-- ═══════════════════════════════════════════════════════════════════════════

-- Regulation D
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_ves_001', 'VESTARA', 'FEDERAL_REGULATION', 'US', '17 CFR §§ 230.501-508 (Regulation D)', 'Reg D', 'Regulation D — Private Placement Exemptions from Securities Registration', 'Safe harbor exemptions from SEC registration for private securities offerings. Rule 504: up to $10M in 12 months. Rule 506(b): unlimited amount, up to 35 non-accredited investors, no general solicitation. Rule 506(c): unlimited amount, accredited investors only, general solicitation permitted with verification. Most common capital raising exemption for startups and private companies.', '["Rule 504: Up to $10M in 12-month period, state registration may apply","Rule 506(b): Unlimited amount, up to 35 sophisticated non-accredited investors","Rule 506(b): No general solicitation or advertising permitted","Rule 506(c): Unlimited amount, accredited investors only","Rule 506(c): General solicitation permitted with reasonable verification","Accredited investor: $200K income ($300K joint) or $1M net worth excl. primary residence","Form D filing within 15 days of first sale","Securities are restricted — holding period applies","Bad actor disqualification (Rule 506(d))"]', '[{"section":"501","description":"Definitions — accredited investor, purchaser representative"},{"section":"502","description":"General conditions — integration, information requirements, limitations on resale"},{"section":"504","description":"Rule 504 — offerings up to $10M"},{"section":"506(b)","description":"Rule 506(b) — no general solicitation, up to 35 non-accredited"},{"section":"506(c)","description":"Rule 506(c) — general solicitation with accredited investor verification"},{"section":"506(d)","description":"Bad actor disqualification"},{"section":"507","description":"Disqualifying conditions for failure to file Form D"}]', '["private_placement_memorandum","subscription_agreement","accredited_investor_questionnaire","Form_D","investor_verification","operating_agreement","shareholder_agreement","blue_sky_filing"]', '["investor-relations-capital-audit"]', 'SEC Division of Corporation Finance', 1, 1, datetime('now'), datetime('now'));

-- Regulation A+
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_ves_002', 'VESTARA', 'FEDERAL_REGULATION', 'US', '17 CFR §§ 230.251-263 (Regulation A)', 'Reg A+', 'Regulation A+ — Mini-IPO Exemption', 'Two-tier offering exemption allowing companies to raise capital from public without full IPO registration. Tier 1: up to $20M in 12 months, state registration required. Tier 2: up to $75M in 12 months, preempts state registration, ongoing reporting required. Securities freely tradeable (not restricted). Available to US and Canadian companies.', '["Tier 1: Up to $20M in 12 months, state blue sky compliance required","Tier 2: Up to $75M in 12 months, state registration preempted","Must file offering statement on Form 1-A with SEC","SEC qualification required before sales","Testing the waters permitted before/after filing","Securities freely tradeable — not restricted securities","Tier 2: Annual (Form 1-K), semi-annual (Form 1-SA), current (Form 1-U) reporting","Non-accredited investor investment limits in Tier 2: 10% of income or net worth","Bad actor disqualification applies"]', '[{"section":"251","description":"Scope of exemption — eligible issuers and offerings"},{"section":"252","description":"Offering statement on Form 1-A"},{"section":"253","description":"Offering circular content requirements"},{"section":"254","description":"Qualification of offering statement"},{"section":"255","description":"Testing the waters — solicitation of interest"},{"section":"257","description":"Ongoing reporting — Tier 2 annual, semi-annual, current"},{"section":"262","description":"Disqualification — bad actors"},{"section":"263","description":"Insignificant deviations from term or condition"}]', '["Form_1_A","offering_circular","testing_the_waters_materials","qualification_order","Form_1_K","Form_1_SA","Form_1_U","investor_subscription"]', '["investor-relations-capital-audit"]', 'SEC', 1, 1, datetime('now'), datetime('now'));

-- Regulation CF — Crowdfunding
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_ves_003', 'VESTARA', 'FEDERAL_REGULATION', 'US', '17 CFR §§ 227.100-503 (Regulation Crowdfunding)', 'Reg CF', 'Regulation Crowdfunding — Securities-Based Crowdfunding', 'Permits companies to raise up to $5M in 12 months through SEC-registered intermediaries (funding portals or broker-dealers). All investors eligible with investment limits based on income/net worth. Must file Form C with SEC. Annual reporting on Form C-AR. Intermediary must conduct background checks and provide investor education materials.', '["Maximum raise: $5M in 12-month period","Must use SEC-registered intermediary (funding portal or broker-dealer)","Investor limits: if income/net worth <$124K, greater of $2,500 or 5% of lesser; if both >$124K, 10% of lesser (max $124K)","Form C filing with SEC — financial statements required","Annual reporting on Form C-AR","Intermediary must conduct background and securities enforcement checks","21-day minimum offering period","Investor may cancel within 48 hours of making commitment","Securities restricted for 12 months"]', '[{"section":"100","description":"Issuer requirements and disqualification"},{"section":"201","description":"Disclosure requirements — Form C"},{"section":"203","description":"Filing requirements and amendments"},{"section":"227","description":"Investor limits based on income/net worth"},{"section":"300","description":"Intermediary requirements — funding portals"},{"section":"301","description":"Intermediary measures to reduce fraud risk"},{"section":"303","description":"Intermediary compensation and conflicts"},{"section":"502","description":"12-month resale restriction"}]', '["Form_C","offering_page","investor_subscription","Form_C_AR","financial_statements","intermediary_agreement","investor_education_materials"]', '["investor-relations-capital-audit"]', 'SEC / FINRA (funding portals)', 1, 1, datetime('now'), datetime('now'));

-- SEC Reporting — 10-K/10-Q
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_ves_004', 'VESTARA', 'FEDERAL_REGULATION', 'US', '17 CFR §§ 249.310, 249.308a (SEC Forms 10-K, 10-Q)', 'SEC 10-K/10-Q', 'SEC Periodic Reporting — Annual (10-K) and Quarterly (10-Q) Filings', 'Public companies must file annual report (10-K) within 60 days of fiscal year end (large accelerated filers) and quarterly reports (10-Q) within 40 days of quarter end. Reports must include audited financial statements, MD&A, risk factors, legal proceedings, executive compensation, and internal controls assessment. Filed via EDGAR.', '["10-K annual report — audited financial statements, MD&A, risk factors","10-Q quarterly report — unaudited interim financial statements","Large accelerated filer: 10-K within 60 days, 10-Q within 40 days","Accelerated filer: 10-K within 60 days, 10-Q within 40 days","Non-accelerated filer: 10-K within 90 days, 10-Q within 45 days","CEO/CFO certification under SOX §§ 302 and 906","Independent auditor report on financial statements","Management assessment of internal controls (10-K)","Filed electronically via EDGAR","Inline XBRL tagging required"]', '[{"section":"10-K Part I","description":"Business, risk factors, properties, legal proceedings"},{"section":"10-K Part II","description":"Financial statements, MD&A, market for securities"},{"section":"10-K Part III","description":"Directors, executive compensation, ownership, governance"},{"section":"10-K Part IV","description":"Exhibits and financial statement schedules"},{"section":"10-Q Part I","description":"Financial statements, MD&A, quantitative/qualitative disclosures"},{"section":"10-Q Part II","description":"Legal proceedings, risk factors, sales of securities"}]', '["10_K_annual_report","10_Q_quarterly_report","auditor_report","CEO_certification","CFO_certification","XBRL_filing","EDGAR_filing","proxy_statement"]', '["investor-relations-capital-audit"]', 'SEC Division of Corporation Finance', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- METRIQA — Performance Analytics & Audit Standards
-- ═══════════════════════════════════════════════════════════════════════════

-- GAAS — Generally Accepted Auditing Standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_met_001', 'METRIQA', 'PROFESSIONAL_STANDARD', 'US', 'AICPA AU-C Sections (Clarified Statements on Auditing Standards)', 'GAAS / AU-C', 'Generally Accepted Auditing Standards — AICPA Clarified Standards', 'Framework for conducting financial audits of nonpublic entities. Three categories: General Standards (training, independence, due care), Standards of Fieldwork (planning, internal control, evidence), Standards of Reporting (GAAP conformity, consistency, disclosure, opinion). Clarified Standards (AU-C) effective for audits of periods ending on/after 12/15/2012.', '["General Standard 1: Adequate technical training and proficiency","General Standard 2: Independence in mental attitude","General Standard 3: Due professional care","Fieldwork Standard 1: Adequate planning and supervision","Fieldwork Standard 2: Understanding of internal control","Fieldwork Standard 3: Sufficient appropriate audit evidence","Reporting Standard 1: State whether statements are in accordance with GAAP","Reporting Standard 2: Identify circumstances of inconsistent application","Reporting Standard 3: Adequate informative disclosures","Reporting Standard 4: Expression of opinion or disclaimer with reasons"]', '[{"section":"AU-C 200","description":"Overall objectives of the independent auditor"},{"section":"AU-C 210","description":"Terms of engagement"},{"section":"AU-C 300","description":"Planning an audit"},{"section":"AU-C 315","description":"Understanding the entity and its environment"},{"section":"AU-C 330","description":"Responding to assessed risks"},{"section":"AU-C 500","description":"Audit evidence"},{"section":"AU-C 700","description":"Forming an opinion and reporting"},{"section":"AU-C 705","description":"Modifications to the auditor report"}]', '["audit_engagement_letter","audit_plan","audit_workpapers","management_representation_letter","auditor_report","internal_control_findings","audit_opinion"]', '["performance-analytics-audit"]', 'AICPA / State Boards of Accountancy', 0, 1, datetime('now'), datetime('now'));

-- PCAOB Standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_met_002', 'METRIQA', 'PROFESSIONAL_STANDARD', 'US', 'PCAOB Auditing Standards (AS 1001-3315)', 'PCAOB AS', 'PCAOB Auditing Standards — Public Company Audit Requirements', 'Mandatory standards for audits of public companies (SEC registrants) and broker-dealers. Established by Sarbanes-Oxley Act. Supersedes AICPA standards for public company audits. Includes integrated audit of financial statements and internal controls (AS 2201). PCAOB conducts inspections of registered audit firms.', '["AS 1001: Responsibilities and functions of the independent auditor","AS 1015: Due professional care in performance of work","AS 2101: Audit planning — risk-based approach","AS 2110: Identifying and assessing risks of material misstatement","AS 2201: Integrated audit of financial statements and internal controls","AS 2301: The auditor response to risks of material misstatement","AS 2401: Consideration of fraud in financial statement audit","AS 2810: Evaluating audit results","AS 3101: The auditor report on financial statements (critical audit matters)"]', '[{"section":"AS 2201","description":"Integrated audit — financial statements and internal controls over financial reporting"},{"section":"AS 2401","description":"Fraud consideration — professional skepticism, fraud risk factors"},{"section":"AS 3101","description":"Auditor report — critical audit matters (CAMs) required"},{"section":"AS 1301","description":"Communications with audit committees"},{"section":"AS 2110","description":"Risk assessment — understand entity, identify ROMM"},{"section":"AS 1215","description":"Audit documentation requirements"}]', '["PCAOB_audit_report","critical_audit_matters","ICFR_opinion","management_letter","audit_committee_communication","inspection_report","audit_workpapers"]', '["performance-analytics-audit"]', 'PCAOB / SEC', 0, 1, datetime('now'), datetime('now'));

-- IIA Standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_met_003', 'METRIQA', 'PROFESSIONAL_STANDARD', 'US', 'IIA International Professional Practices Framework (IPPF) — Global Internal Audit Standards (2024)', 'IIA Standards 2024', 'Global Internal Audit Standards — Institute of Internal Auditors', 'Mandatory requirements for internal audit functions worldwide. 2024 standards organized into five domains: Purpose, Ethics, Governance, Managing, Performing. Internal audit provides independent, objective assurance and consulting activity. CAE must report functionally to the board. Quality assurance and improvement program (QAIP) required.', '["Purpose: Independent assurance and consulting to improve operations","Ethics: Integrity, objectivity, confidentiality, competency","Governance: Board oversight, organizational independence, CAE reporting","Managing: Risk-based audit plan, resource management, quality assurance","Performing: Planning engagements, performing work, communicating results","CAE must report functionally to board/audit committee","Risk-based internal audit plan aligned to strategic objectives","Quality Assurance and Improvement Program (QAIP) required","External quality assessment at least every 5 years"]', '[{"section":"Domain I","description":"Purpose of Internal Auditing — assurance and consulting"},{"section":"Domain II","description":"Ethics and Professionalism — integrity, objectivity, competency"},{"section":"Domain III","description":"Governing the Internal Audit Function — independence, board reporting"},{"section":"Domain IV","description":"Managing Internal Audit — planning, resources, quality"},{"section":"Domain V","description":"Performing Internal Audit Services — engagement execution and reporting"}]', '["internal_audit_charter","risk_based_audit_plan","audit_engagement_report","QAIP","external_quality_assessment","audit_committee_presentation","CAE_report"]', '["performance-analytics-audit"]', 'IIA (professional, voluntary for non-regulated)', 0, 1, datetime('now'), datetime('now'));

-- Data Analytics Standards — ISACA COBIT
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_met_004', 'METRIQA', 'PROFESSIONAL_STANDARD', 'US', 'ISACA COBIT 2019 — Control Objectives for Information and Related Technologies', 'COBIT 2019', 'COBIT 2019 — IT Governance and Management Framework', 'Framework for governance and management of enterprise IT. 40 governance and management objectives across 5 domains. Integrates with NIST, ISO 27001, ITIL, and COSO. Used for IT audit, compliance assessment, and governance maturity evaluation. Widely adopted by internal audit functions for IT control assessment.', '["40 governance and management objectives across 5 domains","EDM: Evaluate, Direct, and Monitor — governance domain","APO: Align, Plan, and Organize — strategic alignment","BAI: Build, Acquire, and Implement — solution delivery","DSS: Deliver, Service, and Support — operational management","MEA: Monitor, Evaluate, and Assess — performance and compliance","Design factors customize framework to organization context","Maturity model with capability levels 0-5","Integrates with COSO, NIST CSF, ISO 27001, ITIL"]', '[{"section":"EDM","description":"Evaluate, Direct, and Monitor — 5 objectives"},{"section":"APO","description":"Align, Plan, and Organize — 14 objectives"},{"section":"BAI","description":"Build, Acquire, and Implement — 11 objectives"},{"section":"DSS","description":"Deliver, Service, and Support — 6 objectives"},{"section":"MEA","description":"Monitor, Evaluate, and Assess — 4 objectives"}]', '["IT_governance_assessment","COBIT_maturity_assessment","IT_audit_report","control_gap_analysis","design_factor_worksheet","governance_framework_mapping"]', '["performance-analytics-audit"]', 'ISACA (professional, voluntary)', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CLARIDEX — Financial Disclosure & Reporting Standards
-- ═══════════════════════════════════════════════════════════════════════════

-- US GAAP
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_cla_001', 'CLARIDEX', 'PROFESSIONAL_STANDARD', 'US', 'FASB Accounting Standards Codification (ASC) — US GAAP', 'US GAAP / ASC', 'US Generally Accepted Accounting Principles — FASB Codification', 'Authoritative source of US accounting standards for nongovernmental entities. Organized in approximately 90 topics covering recognition, measurement, presentation, and disclosure requirements. FASB is designated standard-setter by SEC. All public companies must follow US GAAP for SEC-filed financial statements.', '["Revenue recognition under ASC 606 — 5-step model","Lease accounting under ASC 842 — right-of-use assets","Financial instruments under ASC 320, 321, 326 — CECL model","Consolidation under ASC 810 — variable interest entities","Fair value measurement under ASC 820 — 3-level hierarchy","Going concern evaluation under ASC 205-40","Segment reporting under ASC 280","Stock compensation under ASC 718","Income taxes under ASC 740 — deferred tax assets/liabilities","Business combinations under ASC 805"]', '[{"section":"ASC 606","description":"Revenue from Contracts with Customers — 5-step model"},{"section":"ASC 842","description":"Leases — right-of-use asset and lease liability"},{"section":"ASC 326","description":"Financial Instruments — Credit Losses (CECL)"},{"section":"ASC 820","description":"Fair Value Measurement — 3-level hierarchy"},{"section":"ASC 350","description":"Intangibles — Goodwill and Other"},{"section":"ASC 740","description":"Income Taxes — deferred tax accounting"},{"section":"ASC 805","description":"Business Combinations — acquisition method"}]', '["financial_statements","10_K","10_Q","audit_report","footnotes","MD_and_A","earnings_release","accounting_policy_memo"]', '["financial-disclosure-reporting-audit"]', 'FASB / SEC', 0, 1, datetime('now'), datetime('now'));

-- IFRS
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_cla_002', 'CLARIDEX', 'INTERNATIONAL', 'US', 'IFRS Standards — International Financial Reporting Standards (IASB)', 'IFRS', 'International Financial Reporting Standards — Global Accounting Framework', 'Global accounting standards issued by IASB, required or permitted in 140+ countries. SEC permits foreign private issuers to file IFRS financial statements without US GAAP reconciliation. Key differences from US GAAP include IFRS 16 leases, IFRS 9 financial instruments, IAS 36 impairment, and inventory (no LIFO under IFRS). Convergence efforts ongoing with FASB.', '["IFRS 15: Revenue from Contracts with Customers (converged with ASC 606)","IFRS 16: Leases — single model for lessees (no operating lease exception)","IFRS 9: Financial Instruments — expected credit loss model","IAS 36: Impairment of Assets — single-step impairment model","IAS 2: Inventories — FIFO or weighted average (no LIFO)","IAS 16: Property, Plant and Equipment — revaluation model permitted","IAS 37: Provisions — more expansive recognition than US GAAP","IFRS 3: Business Combinations — bargain purchase gain recognized","IAS 1: Presentation of Financial Statements — required formats"]', '[{"section":"IFRS 15","description":"Revenue recognition — 5-step model (converged)"},{"section":"IFRS 16","description":"Leases — single lessee model, all leases on balance sheet"},{"section":"IFRS 9","description":"Financial instruments — classification, impairment, hedging"},{"section":"IAS 1","description":"Presentation of financial statements"},{"section":"IAS 36","description":"Impairment — indicator-based, single step"},{"section":"IFRS 3","description":"Business combinations — acquisition method"}]', '["IFRS_financial_statements","audit_report","annual_report","foreign_private_issuer_filing","20_F","reconciliation_to_GAAP"]', '["financial-disclosure-reporting-audit"]', 'IASB / Local securities regulators', 0, 1, datetime('now'), datetime('now'));

-- SEC Regulation S-K
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_cla_003', 'CLARIDEX', 'FEDERAL_REGULATION', 'US', '17 CFR Part 229 (Regulation S-K)', 'Reg S-K', 'Regulation S-K — Non-Financial Statement Disclosure Requirements', 'Prescribes non-financial statement disclosure requirements for SEC filings. Covers description of business, risk factors, properties, legal proceedings, management, executive compensation, security ownership, related party transactions, and MD&A. Updated in 2020 to modernize disclosure requirements and reduce duplicative information.', '["Item 101: Description of business — overview, strategy, human capital","Item 103: Legal proceedings — material pending litigation","Item 105: Risk factors — material risks, concise, organized by topic","Item 201: Market information and dividends","Item 301-303: Selected financial data, supplementary data, MD&A","Item 402: Executive compensation — Summary Compensation Table, CD&A","Item 403: Security ownership of management and principal stockholders","Item 404: Related person transactions — $120K threshold","Item 601: Exhibits — material contracts, articles, bylaws, code of ethics"]', '[{"section":"Item 101","description":"Description of business and human capital"},{"section":"Item 103","description":"Legal proceedings disclosure"},{"section":"Item 105","description":"Risk factors — material risks to investment"},{"section":"Item 303","description":"MD&A — results of operations, liquidity, capital resources"},{"section":"Item 402","description":"Executive compensation disclosure requirements"},{"section":"Item 404","description":"Related person transactions"},{"section":"Item 601","description":"Exhibit requirements for SEC filings"}]', '["10_K","10_Q","S_1_registration","proxy_statement","annual_report","executive_compensation_table","risk_factors_section","MD_and_A"]', '["financial-disclosure-reporting-audit"]', 'SEC Division of Corporation Finance', 1, 1, datetime('now'), datetime('now'));

-- SEC Cybersecurity Disclosure
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_cla_004', 'CLARIDEX', 'FEDERAL_REGULATION', 'US', '17 CFR §§ 229.106, 249.308 (SEC Cybersecurity Disclosure Rules, July 2023)', 'SEC Cyber Disclosure', 'SEC Cybersecurity Incident Disclosure and Risk Management Rules', 'Requires registrants to disclose material cybersecurity incidents on Form 8-K within 4 business days of determining materiality. Annual disclosure of cybersecurity risk management, strategy, and governance in 10-K (Item 106). Board oversight and management role in cybersecurity must be disclosed. Effective December 2023.', '["Material incident disclosure on Form 8-K Item 1.05 within 4 business days","Materiality determination — not mere detection triggers obligation","10-K Item 106(b): Describe cybersecurity risk management and strategy","10-K Item 106(c): Describe board oversight of cybersecurity risk","10-K Item 106(c): Describe management role in assessing and managing cyber risk","May delay disclosure up to 120 days if AG determines national security risk","Immaterial incidents may become material through aggregation","No requirement to disclose specific technical details that aid attackers"]', '[{"section":"Item 1.05 (8-K)","description":"Material cybersecurity incident disclosure — 4 business days"},{"section":"Item 106(a)","description":"Definitions — cybersecurity incident, cybersecurity threat"},{"section":"Item 106(b)","description":"Risk management and strategy disclosure in 10-K"},{"section":"Item 106(c)(1)","description":"Board oversight of cybersecurity risk"},{"section":"Item 106(c)(2)","description":"Management role in assessing and managing cyber risk"}]', '["8_K_cyber_disclosure","10_K_Item_106","incident_materiality_assessment","board_cybersecurity_briefing","risk_management_program_description","AG_delay_request"]', '["financial-disclosure-reporting-audit"]', 'SEC', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- NEXARIS — Strategic Partnerships & Competition Law
-- ═══════════════════════════════════════════════════════════════════════════

-- Franchise Disclosure
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_nex_001', 'NEXARIS', 'FEDERAL_REGULATION', 'US', '16 CFR Part 436 (FTC Franchise Rule)', 'FTC Franchise Rule', 'FTC Franchise Rule — Franchise Disclosure Document Requirements', 'Requires franchisors to provide prospective franchisees with a Franchise Disclosure Document (FDD) at least 14 calendar days before signing agreement or payment. FDD must contain 23 specific items covering franchisor background, fees, obligations, financial performance, and audited financial statements. Failure to disclose is unfair or deceptive practice under FTC Act.', '["FDD must be provided at least 14 days before agreement signing or payment","23 required items covering all material franchise relationship terms","Item 19 (Financial Performance Representations) — optional but if made, must have reasonable basis","Audited financial statements of franchisor required (Item 21)","Updated FDD annually within 120 days of fiscal year end","Material changes require quarterly updates","State registration required in registration states (CA, IL, NY, etc.)","Earnings claims only permitted in Item 19 of FDD"]', '[{"section":"Item 1","description":"The Franchisor and any Parents, Predecessors, and Affiliates"},{"section":"Item 2","description":"Business Experience of key personnel"},{"section":"Item 3","description":"Litigation history"},{"section":"Item 5","description":"Initial Fees"},{"section":"Item 6","description":"Other Fees — royalties, advertising, technology"},{"section":"Item 7","description":"Estimated Initial Investment"},{"section":"Item 19","description":"Financial Performance Representations (optional)"},{"section":"Item 20","description":"Outlets and Franchisee Information"},{"section":"Item 21","description":"Audited Financial Statements"},{"section":"Item 22","description":"Contracts — franchise agreement and related documents"}]', '["franchise_disclosure_document","franchise_agreement","financial_performance_representation","audited_financial_statements","state_registration_filing","receipt_page","earnings_claim"]', '["strategic-partnerships-audit"]', 'FTC / State franchise regulators (CA DFPI)', 1, 1, datetime('now'), datetime('now'));

-- Joint Venture Antitrust
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_nex_002', 'NEXARIS', 'FEDERAL_REGULATION', 'US', 'DOJ/FTC Antitrust Guidelines for Collaborations Among Competitors (2000)', 'Competitor Collaboration Guidelines', 'DOJ/FTC Antitrust Guidelines for Competitor Collaborations and Joint Ventures', 'Framework for evaluating antitrust risk of competitor collaborations including joint ventures, strategic alliances, information sharing, and standard-setting. Establishes safety zones and analysis framework. Per se illegal: price fixing, market allocation, output restriction. Rule of reason: joint R&D, production JVs, marketing arrangements. Safety zone: combined market share below 20%.', '["Per se illegal: price fixing, bid rigging, market allocation agreements","Rule of reason analysis for legitimate collaborations","Safety zone: combined market share below 20% in relevant market","Information sharing: disaggregated, historical, managed by third party preferred","Standard-setting: open participation, no exclusion, FRAND licensing","Joint ventures must have legitimate integration creating efficiencies","Ancillary restraints must be reasonably necessary to achieve efficiencies","HSR filing required if transaction meets size-of-person and size-of-transaction thresholds"]', '[{"section":"Section 1","description":"General principles — per se vs rule of reason"},{"section":"Section 2","description":"Framework for analyzing collaborations"},{"section":"Section 3.1","description":"Per se analysis — naked restraints among competitors"},{"section":"Section 3.3","description":"Rule of reason — integration, efficiencies, market power"},{"section":"Section 3.4","description":"Safety zone — combined share below 20%"},{"section":"Section 4.1","description":"R&D collaborations"},{"section":"Section 4.2","description":"Production collaborations"},{"section":"Section 4.3","description":"Marketing collaborations"}]', '["joint_venture_agreement","collaboration_agreement","antitrust_analysis","market_share_assessment","HSR_filing","information_sharing_protocol","standard_setting_policies"]', '["strategic-partnerships-audit"]', 'DOJ Antitrust Division / FTC', 1, 1, datetime('now'), datetime('now'));

-- CA Franchise Investment Law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_nex_003', 'NEXARIS', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 31000-31516 (California Franchise Investment Law)', 'Corp Code §§ 31000-31516', 'California Franchise Investment Law — State Registration and Disclosure', 'California requires franchisors to register with DFPI before offering or selling franchises in the state. More protective than federal FTC rule — includes private right of action for fraud, registration requirement, and relationship protections. Franchisee may rescind within 2 years of franchise sale if FDD not timely provided. Good cause required for termination/nonrenewal.', '["Franchise registration with DFPI before offering or selling","FDD must be provided 14 days before signing or payment","Private right of action for fraud, deceit, or violation of law","Rescission available within 2 years if FDD not timely delivered","Good cause required for termination of franchise agreement","Good cause required for nonrenewal of franchise agreement","90-day notice of termination required (60 days to cure)","Franchisor cannot restrict franchisee right to associate","No waiver of California Franchise Investment Law protections in agreement"]', '[{"section":"31100-31113","description":"Registration requirements and procedures"},{"section":"31114-31119","description":"Exemptions from registration"},{"section":"31200-31210","description":"Disclosure requirements — enhanced beyond FTC"},{"section":"31300","description":"Prohibited practices — fraud, misrepresentation"},{"section":"31301-31302","description":"Private right of action and statute of limitations"},{"section":"31512","description":"Good cause for termination and nonrenewal"},{"section":"31516","description":"Nonwaiver — cannot contractually waive protections"}]', '["franchise_registration","FDD_with_CA_addendum","franchise_agreement","termination_notice","nonrenewal_notice","rescission_demand","DFPI_registration","franchisee_association_notice"]', '["strategic-partnerships-audit"]', 'California DFPI / Superior Court', 1, 1, datetime('now'), datetime('now'));

-- International Trade — Export Controls
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_nex_004', 'NEXARIS', 'FEDERAL_REGULATION', 'US', 'Export Administration Regulations (15 CFR §§ 730-774) / ITAR (22 CFR §§ 120-130)', 'EAR/ITAR', 'Export Controls — EAR and ITAR Compliance for International Partnerships', 'Dual regulatory framework controlling exports of goods, technology, and services. EAR (Commerce/BIS): dual-use items, software, technology classified on Commerce Control List. ITAR (State/DDTC): defense articles and services on US Munitions List. Violations carry severe civil and criminal penalties. Deemed export rule: disclosure of controlled technology to foreign national in US requires license.', '["EAR: Dual-use items classified on Commerce Control List (CCL) by ECCN","ITAR: Defense articles/services on US Munitions List (USML)","License required for controlled exports unless exception/exemption applies","Deemed export: sharing controlled technology with foreign national requires license","Denied Persons, Entity, and SDN list screening required","End-use and end-user restrictions — cannot support WMD programs","ITAR registration with DDTC required for manufacturers/exporters of defense articles","Voluntary self-disclosure reduces penalties","Civil penalties: up to $300K/violation (EAR), $500K/violation (ITAR)","Criminal penalties: up to $1M fine and 20 years imprisonment"]', '[{"section":"EAR Part 734","description":"Scope of EAR — what is subject to regulation"},{"section":"EAR Part 738","description":"Commerce Country Chart — license requirements by destination"},{"section":"EAR Part 740","description":"License exceptions"},{"section":"EAR Part 744","description":"End-use and end-user restrictions"},{"section":"ITAR 120","description":"Purpose and definitions — defense articles and services"},{"section":"ITAR 122","description":"Registration requirements"},{"section":"ITAR 123","description":"Licenses for export and temporary import"},{"section":"ITAR 126","description":"Prohibited destinations and end-uses"}]', '["export_license","commodity_classification","technology_control_plan","deemed_export_assessment","restricted_party_screening","DDTC_registration","voluntary_disclosure","end_user_certificate"]', '["strategic-partnerships-audit"]', 'BIS (Commerce) / DDTC (State) / OFAC (Treasury)', 0, 1, datetime('now'), datetime('now'));
