-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 12
-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC expansion: CA business formation, UCC, trademark, copyright,
-- patent, trade secrets, securities, antitrust, unfair competition.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — California Business Formation
-- ═══════════════════════════════════════════════════════════════════════════

-- CA Revised Uniform LLC Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_008', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 17701.01-17713.13 (California Revised Uniform Limited Liability Company Act)', 'Corp Code § 17701+', 'California Revised Uniform LLC Act', 'Comprehensive statute governing the formation, operation, management, and dissolution of limited liability companies in California. Replaced the Beverly-Killea LLC Act effective January 1, 2014. Provides default rules that may be modified by operating agreement except for non-waivable provisions.', '["Articles of Organization filed with Secretary of State (§ 17702.01)","Operating agreement governs relations among members and managers (§ 17701.10)","Member-managed unless operating agreement provides for manager-managed (§ 17704.07)","Duty of loyalty and duty of care owed by members/managers (§ 17704.09)","Annual Statement of Information required (§ 17702.09)","Registered agent for service of process required (§ 17701.13)","Transferability of membership interests restricted by default (§ 17704.02)","Dissolution triggered by events in § 17707.01"]', '[{"section":"17701.04","description":"Formation — Articles of Organization filing requirements"},{"section":"17701.10","description":"Operating agreement — scope, enforceability, non-waivable provisions"},{"section":"17702.09","description":"Statement of Information — biennial filing requirement"},{"section":"17704.07","description":"Management — member-managed vs. manager-managed structures"},{"section":"17704.09","description":"Standards of conduct — duty of loyalty, duty of care, obligation of good faith and fair dealing"},{"section":"17706.02","description":"Member dissociation — wrongful vs. rightful"},{"section":"17707.01","description":"Dissolution events and procedures"},{"section":"17713.04","description":"Merger and conversion procedures"}]', '["articles_of_organization","operating_agreement","statement_of_information","certificate_of_dissolution","membership_interest_assignment","manager_resolution"]', '["corporate-legal-architecture-audit"]', 'California Secretary of State', 1, 1, datetime('now'), datetime('now'));

-- CA General Corporation Law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_009', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 100-2319 (California General Corporation Law)', 'Corp Code § 100+', 'California General Corporation Law', 'Primary statutory framework governing the formation, governance, and dissolution of general stock corporations in California. Establishes board fiduciary duties, shareholder rights, merger procedures, and corporate formalities. California imposes stricter fiduciary standards than Delaware, including cumulative voting rights by default and broader shareholder inspection rights.', '["Articles of Incorporation filed with Secretary of State (§ 200)","Bylaws adopted by incorporator or board (§ 212)","Annual meeting of shareholders required (§ 600)","Board of directors minimum duties of care and loyalty (§§ 309-310)","Annual Statement of Information within 90 days of fiscal year end (§ 1502)","Cumulative voting in director elections by default (§ 708.1)","Shareholder inspection rights for books and records (§ 1601)","Dissolution requires board resolution and shareholder approval (§ 1900)"]', '[{"section":"200","description":"Articles of Incorporation — required and optional provisions"},{"section":"212","description":"Bylaws — adoption, amendment, and required content"},{"section":"309","description":"Duty of care — informed business judgment standard"},{"section":"310","description":"Interested director transactions — approval requirements"},{"section":"600","description":"Annual meeting of shareholders — notice and quorum"},{"section":"708.1","description":"Cumulative voting rights in director elections"},{"section":"1501","description":"Annual report to shareholders"},{"section":"1502","description":"Statement of Information — annual filing with Secretary of State"},{"section":"1601","description":"Shareholder inspection of books and records"},{"section":"1900-1905","description":"Dissolution procedures — voluntary and involuntary"}]', '["articles_of_incorporation","bylaws","board_resolution","shareholder_agreement","annual_report","statement_of_information","stock_certificate","proxy_statement"]', '["corporate-legal-architecture-audit"]', 'California Secretary of State / California Courts', 1, 1, datetime('now'), datetime('now'));

-- CA Revised Uniform Partnership Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_010', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 16100-16962 (California Revised Uniform Partnership Act)', 'Corp Code § 16100+', 'California Revised Uniform Partnership Act', 'Governs general partnerships including formation by association, partner fiduciary duties, joint and several liability for partnership obligations, dissociation, and dissolution. A partnership is an entity distinct from its partners under RUPA. Partners are default agents of the partnership for carrying on business in the ordinary course.', '["Partnership formed by association of two or more persons carrying on business for profit (§ 16202)","Each partner is agent of the partnership (§ 16301)","Partners jointly and severally liable for partnership obligations (§ 16306)","Duty of loyalty — account for profits, refrain from self-dealing, refrain from competing (§ 16404(b))","Duty of care — refrain from grossly negligent or reckless conduct (§ 16404(c))","Partnership agreement may not eliminate duty of loyalty or unreasonably reduce duty of care (§ 16103)","Partner dissociation — rightful or wrongful (§§ 16601-16603)","Dissolution and winding up (§§ 16801-16807)"]', '[{"section":"16202","description":"Formation — carrying on business for profit creates partnership"},{"section":"16301","description":"Each partner is agent of the partnership"},{"section":"16306","description":"Joint and several liability of partners for all partnership obligations"},{"section":"16401","description":"Partner rights to distributions and access to books/records"},{"section":"16404","description":"General standards of partner conduct — loyalty, care, good faith"},{"section":"16502","description":"Partner right to an accounting"},{"section":"16601","description":"Dissociation events"},{"section":"16801","description":"Events causing dissolution and winding up"}]', '["partnership_agreement","statement_of_partnership","partner_accounting","dissolution_notice","buyout_agreement","statement_of_dissociation"]', '["corporate-legal-architecture-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- CA Revised Uniform LP Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_011', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 15900-15912.07 (California Revised Uniform Limited Partnership Act)', 'Corp Code § 15900+', 'California Revised Uniform Limited Partnership Act', 'Governs formation and operation of limited partnerships in California. Requires at least one general partner with unlimited liability and one limited partner whose liability is limited to their contribution. Certificate of Limited Partnership must be filed with the Secretary of State. Eliminates the control rule — limited partners may participate in management without losing liability protection.', '["Certificate of Limited Partnership filed with Secretary of State (§ 15902.01)","At least one general partner and one limited partner required (§ 15901.02)","General partner has unlimited personal liability (§ 15904.04)","Limited partner liability limited to contribution absent guarantees (§ 15903.03)","Limited partners may participate in management without losing liability shield (§ 15903.03)","Partnership agreement governs relations among partners (§ 15901.10)","Annual Statement of Information required","General partner owes fiduciary duties; limited partner does not by default (§ 15905.08)"]', '[{"section":"15901.02","description":"Definitions — general partner, limited partner"},{"section":"15902.01","description":"Certificate of Limited Partnership — formation and filing"},{"section":"15903.03","description":"Limited partner liability — no control rule"},{"section":"15904.04","description":"General partner — agency authority and personal liability"},{"section":"15905.08","description":"General partner fiduciary duties of loyalty and care"},{"section":"15906.01","description":"Dissociation of limited partner"},{"section":"15908.01","description":"Dissolution events and winding up"},{"section":"15911.01","description":"Merger and conversion"}]', '["certificate_of_limited_partnership","partnership_agreement","statement_of_information","capital_contribution_agreement","dissolution_notice","certificate_of_cancellation"]', '["corporate-legal-architecture-audit"]', 'California Secretary of State', 1, 1, datetime('now'), datetime('now'));

-- CA Nonprofit Corporation Law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_012', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 5000-10841 (California Nonprofit Corporation Law)', 'Corp Code § 5000+', 'California Nonprofit Corporation Law', 'Governs three types of nonprofit corporations: public benefit (§§ 5110-6910), mutual benefit (§§ 7110-8910), and religious (§§ 9110-9690). Public benefit corporations operate for public or charitable purposes and are subject to Attorney General oversight. Board members owe fiduciary duties and must avoid self-dealing transactions. Assets of a dissolved public benefit corporation must be distributed to another public benefit organization.', '["Articles of Incorporation stating nonprofit purpose (§ 5130/7130/9130)","Board of directors required — no fewer than one for mutual benefit, three for public benefit (§ 5151/7151)","No distribution of profits to members or directors (§ 5410)","Attorney General oversight of public benefit corporations (§ 5250)","Annual Statement of Information required","Self-dealing transaction approval under § 5233","IRS Form 1023/1024 for federal tax exemption","FTB Form 3500 for California tax exemption","Dissolution — assets distributed to qualifying charitable organization (§ 6716)"]', '[{"section":"5110-5510","description":"Public benefit corporation — formation and governance"},{"section":"5150","description":"Articles of Incorporation — required provisions"},{"section":"5233","description":"Self-dealing transactions — board approval requirements"},{"section":"5250","description":"Attorney General supervisory powers over public benefit corps"},{"section":"6716","description":"Dissolution — distribution of assets to charitable purpose"},{"section":"7110-7151","description":"Mutual benefit corporation provisions"},{"section":"9110-9690","description":"Religious corporation provisions"},{"section":"5520-5617","description":"Mergers of nonprofit corporations"}]', '["articles_of_incorporation","bylaws","conflict_of_interest_policy","Form_1023","FTB_3500","board_resolution","annual_report","dissolution_plan"]', '["corporate-legal-architecture-audit"]', 'California Secretary of State / Attorney General', 0, 1, datetime('now'), datetime('now'));

-- CA Secretary of State Filing Requirements
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_013', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code § 12190 et seq.; Cal. Corp. Code §§ 1502, 17702.09', 'Gov Code § 12190+', 'California Secretary of State — Business Entity Filing Requirements', 'Secretary of State is the filing office for all California business entities. Formation documents, Statements of Information, amendments, mergers, conversions, and dissolutions must be filed with the SOS. Failure to file the required Statement of Information results in suspension or forfeiture. The SOS maintains the public business entity database and issues Certificates of Good Standing.', '["Articles/Certificate filed to create entity (Corp Code §§ 200, 17702.01, 15902.01)","Statement of Information filed biennially for LLCs, annually for corporations (Corp Code §§ 1502, 17702.09)","Registered agent for service of process required","Amendments to formation documents must be filed","Certificate of Good Standing available upon request","Failure to file SOI leads to suspension by FTB","Foreign entity registration required before transacting business (Corp Code § 2105)","Name reservation available for 60 days (Corp Code § 201.5)"]', '[{"section":"Gov Code 12190","description":"Secretary of State — powers and duties regarding business filings"},{"section":"Corp Code 1502","description":"Corporation — annual Statement of Information"},{"section":"Corp Code 17702.09","description":"LLC — biennial Statement of Information"},{"section":"Corp Code 2105","description":"Foreign corporation qualification to transact business"},{"section":"Corp Code 2117","description":"Penalties for transacting business without qualification"}]', '["articles_of_organization","articles_of_incorporation","statement_of_information","certificate_of_good_standing","name_reservation","foreign_qualification","amendment_filing"]', '["corporate-legal-architecture-audit"]', 'California Secretary of State', 0, 1, datetime('now'), datetime('now'));

-- CA Franchise Tax Board — Annual Minimum Franchise Tax
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_014', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Rev. & Tax. Code §§ 17941, 23151, 23153 (California Franchise Tax)', 'RTC §§ 17941/23153', 'California Franchise Tax Board — Annual Minimum Franchise Tax', 'Every LLC, corporation, and limited partnership doing business in California or organized under California law must pay an annual minimum franchise tax of $800 to the Franchise Tax Board. First-year exemption applies to LLCs but not corporations. LLCs with gross receipts exceeding $250,000 pay an additional annual fee ranging from $900 to $11,790 under RTC § 17942. Failure to pay results in entity suspension and loss of right to transact business.', '["$800 annual minimum franchise tax for LLCs (§ 17941)","$800 annual minimum franchise tax for corporations (§ 23153)","LLC fee based on gross receipts: $900 ($250K-$500K), $2,500 ($500K-$1M), $6,000 ($1M-$5M), $11,790 ($5M+) (§ 17942)","First-year LLC exemption from $800 minimum (§ 17941(d))","Tax due on 15th day of 4th month of taxable year","Entity suspended for nonpayment — cannot transact business, file suit, or defend actions","Revivor requires payment of all back taxes, penalties, and interest","SOS suspends entity upon FTB certificate of noncompliance"]', '[{"section":"17941","description":"Annual tax on LLCs — $800 minimum"},{"section":"17942","description":"LLC annual fee based on gross California receipts"},{"section":"23151","description":"Corporate franchise tax rate — 8.84% of net income"},{"section":"23153","description":"Minimum franchise tax — $800 for corporations"},{"section":"23301","description":"Suspension powers of FTB for nonpayment"},{"section":"23305","description":"Revivor procedures to restore suspended entity"}]', '["FTB_return","franchise_tax_payment","LLC_fee_calculation","suspension_notice","revivor_application","certificate_of_revivor"]', '["corporate-legal-architecture-audit"]', 'California Franchise Tax Board', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — Uniform Commercial Code (California Enactment)
-- ═══════════════════════════════════════════════════════════════════════════

-- UCC Article 2 — Sale of Goods
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_015', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Com. Code §§ 2101-2725 (UCC Article 2 — Sales)', 'Com Code § 2101+', 'UCC Article 2 — Sale of Goods', 'Governs transactions in goods (movable property). Establishes rules for contract formation, warranties, performance, breach, and remedies in commercial sales. The statute of frauds requires a writing for sales of goods priced at $500 or more. Applies only to goods, not services or real property. Merchant rules impose heightened obligations on parties who regularly deal in goods of the kind.', '["Contract formation — offer, acceptance, and consideration (§ 2204)","Statute of Frauds — writing required for goods $500+ (§ 2201)","Express warranties by affirmation, description, or sample (§ 2313)","Implied warranty of merchantability (§ 2314)","Implied warranty of fitness for particular purpose (§ 2315)","Perfect tender rule — buyer may reject if goods fail to conform (§ 2601)","Cover — buyer may purchase substitute goods and recover difference (§ 2712)","4-year statute of limitations from tender of delivery (§ 2725)"]', '[{"section":"2201","description":"Statute of Frauds — contracts for sale of goods $500 or more"},{"section":"2204","description":"Formation — contract may be made in any manner sufficient to show agreement"},{"section":"2302","description":"Unconscionable contracts or clauses"},{"section":"2313","description":"Express warranties — affirmation of fact or promise"},{"section":"2314","description":"Implied warranty of merchantability"},{"section":"2315","description":"Implied warranty of fitness for particular purpose"},{"section":"2601","description":"Buyer right to reject — perfect tender rule"},{"section":"2712","description":"Cover — buyer remedy to purchase substitute goods"},{"section":"2725","description":"Statute of limitations — 4 years from tender of delivery"}]', '["purchase_order","sales_contract","invoice","warranty_disclaimer","UCC_complaint","demand_letter"]', '["corporate-legal-architecture-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- UCC Article 3 — Negotiable Instruments
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_016', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Com. Code §§ 3101-3605 (UCC Article 3 — Negotiable Instruments)', 'Com Code § 3101+', 'UCC Article 3 — Negotiable Instruments', 'Governs promissory notes and drafts (including checks). Establishes requirements for negotiability, holder in due course status, liability of parties, and discharge. A holder in due course takes the instrument free of most defenses except real defenses such as fraud in the factum, duress, and incapacity. Revised Article 3 adopted in California effective 1993.', '["Negotiability requirements — unconditional promise/order, fixed amount of money, payable on demand or at definite time, payable to order or bearer (§ 3104)","Holder in due course — takes for value, in good faith, without notice of defenses (§ 3302)","Real defenses survive HDC status — infancy, duress, incapacity, illegality, fraud in factum (§ 3305(a))","Presentment, dishonor, and notice requirements (§§ 3501-3505)","Drawer liability on dishonored draft (§ 3414)","Indorser liability on dishonored instrument (§ 3415)","Discharge by payment or cancellation (§§ 3601-3604)"]', '[{"section":"3104","description":"Negotiable instrument — definition and formal requirements"},{"section":"3201","description":"Negotiation — transfer of possession plus indorsement"},{"section":"3302","description":"Holder in due course — requirements and protections"},{"section":"3305","description":"Defenses and claims in recoupment — real vs. personal defenses"},{"section":"3401","description":"Signature — liability only attaches to those who sign"},{"section":"3414","description":"Obligation of drawer on dishonored draft"},{"section":"3415","description":"Obligation of indorser on dishonored instrument"},{"section":"3601","description":"Discharge and payment"}]', '["promissory_note","check","draft","indorsement","dishonor_notice","demand_for_payment"]', '["corporate-legal-architecture-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- UCC Article 9 — Secured Transactions
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_017', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Com. Code §§ 9101-9809 (UCC Article 9 — Secured Transactions)', 'Com Code § 9101+', 'UCC Article 9 — Secured Transactions', 'Governs security interests in personal property and fixtures. Establishes rules for attachment, perfection, priority, and enforcement of security interests. Perfection by filing a UCC-1 financing statement with the Secretary of State creates constructive notice. First-to-file-or-perfect rule determines priority among competing security interests. Comprehensive default and enforcement provisions in Part 6.', '["Security agreement must authenticate, describe collateral, and debtor must have rights in collateral (§ 9203)","Attachment requires value given, debtor rights in collateral, and authenticated security agreement (§ 9203)","Perfection by filing UCC-1 financing statement with Secretary of State (§ 9310)","Purchase money security interest (PMSI) superpriority (§ 9324)","First-to-file-or-perfect priority rule (§ 9322)","Financing statement effective for 5 years; continuation statement required (§§ 9515, 9516)","Default — secured party may repossess without breach of peace (§ 9609)","Commercially reasonable disposition of collateral after default (§ 9610)"]', '[{"section":"9203","description":"Attachment — security interest enforceable against debtor"},{"section":"9310","description":"Perfection — when filing required"},{"section":"9312","description":"Perfection by control or possession for specific collateral types"},{"section":"9322","description":"Priority among conflicting security interests — first to file or perfect"},{"section":"9324","description":"Purchase money security interest — superpriority rules"},{"section":"9501","description":"Filing office — Secretary of State for most collateral types"},{"section":"9515","description":"Duration of financing statement — 5 years"},{"section":"9609","description":"Secured party right to take possession after default"},{"section":"9610","description":"Disposition of collateral after default — commercially reasonable standard"}]', '["security_agreement","UCC_1_financing_statement","UCC_3_amendment","UCC_11_search","subordination_agreement","default_notice","disposition_notice"]', '["corporate-legal-architecture-audit"]', 'California Secretary of State / California Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — Intellectual Property — Federal
-- ═══════════════════════════════════════════════════════════════════════════

-- Lanham Act — Trademark Registration
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_018', 'LEXARC', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1051-1072 (Lanham Act — Registration)', 'Lanham Act §§ 1-22', 'Lanham Act — Trademark Registration', 'Federal trademark registration system administered by the USPTO. Registration on the Principal Register provides nationwide constructive notice, prima facie evidence of validity, and the ability to become incontestable after five years of continuous use. Applicants must demonstrate use in commerce or bona fide intent to use. The Trademark Trial and Appeal Board adjudicates opposition and cancellation proceedings.', '["Application on basis of use in commerce (§ 1051(a)) or intent to use (§ 1051(b))","Mark must be distinctive — inherently distinctive or acquired distinctiveness (§ 1052)","Bars to registration — deceptive, scandalous, primarily merely descriptive, primarily geographically descriptive, or likely to cause confusion (§ 1052)","Publication for opposition — 30-day period (§ 1063)","Statement of use required for ITU applications before registration issues (§ 1051(d))","Registration on Principal Register — constructive notice nationwide (§ 1072)","Incontestability after 5 years continuous use and § 15 affidavit (§ 1065)","Renewal every 10 years with § 8 declaration of continued use (§ 1058)"]', '[{"section":"1051(a)","description":"Application based on use in commerce"},{"section":"1051(b)","description":"Application based on bona fide intent to use"},{"section":"1052","description":"Bars to registration — grounds for refusal"},{"section":"1057","description":"Registration — constructive notice and prima facie evidence"},{"section":"1058","description":"Duration and renewal — § 8 affidavit of continued use"},{"section":"1063","description":"Opposition proceedings before TTAB"},{"section":"1064","description":"Cancellation proceedings"},{"section":"1065","description":"Incontestability — § 15 affidavit after 5 years continuous use"},{"section":"1072","description":"Constructive notice of registration"}]', '["trademark_application","specimen_of_use","office_action_response","statement_of_use","section_8_declaration","section_15_declaration","TTAB_opposition","registration_certificate"]', '["corporate-legal-architecture-audit"]', 'USPTO / TTAB', 1, 1, datetime('now'), datetime('now'));

-- Lanham Act — Trademark Infringement
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_019', 'LEXARC', 'FEDERAL_STATUTE', 'US', '15 USC § 1114 (Lanham Act § 32 — Trademark Infringement)', 'Lanham Act § 32', 'Lanham Act — Trademark Infringement', 'Creates a federal cause of action for infringement of registered trademarks. Any person who uses in commerce a reproduction, counterfeit, copy, or colorable imitation of a registered mark in connection with the sale or distribution of goods or services, where such use is likely to cause confusion, is liable for infringement. Remedies include injunctive relief, damages, profits, and in exceptional cases, attorneys fees.', '["Plaintiff must own a valid registered trademark","Defendant used mark in commerce without authorization","Use in connection with sale, offering for sale, distribution, or advertising of goods/services","Likelihood of confusion — multifactor test (Sleekcraft factors in 9th Circuit)","Willful infringement may result in treble damages (§ 1117(b))","Counterfeit marks — mandatory treble damages or statutory damages up to $2M per mark (§ 1117(c))","Innocent infringer defense limits remedy to injunction (§ 1114(2))"]', '[{"section":"1114(1)(a)","description":"Infringement of registered mark — use likely to cause confusion"},{"section":"1114(1)(b)","description":"Infringement by reproduction or counterfeit of registered mark"},{"section":"1114(2)","description":"Innocent infringer defense — printer/publisher limitation"},{"section":"1116","description":"Injunctive relief — TRO, preliminary and permanent injunction"},{"section":"1117(a)","description":"Recovery of profits, damages, and costs"},{"section":"1117(b)","description":"Treble damages for willful use of counterfeit mark"},{"section":"1117(c)","description":"Statutory damages for use of counterfeit mark — up to $2M per mark"}]', '["cease_and_desist_letter","trademark_infringement_complaint","likelihood_of_confusion_analysis","preliminary_injunction_motion","damages_calculation"]', '["corporate-legal-architecture-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Lanham Act — False Designation of Origin
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_020', 'LEXARC', 'FEDERAL_STATUTE', 'US', '15 USC § 1125(a) (Lanham Act § 43(a) — False Designation of Origin)', 'Lanham Act § 43(a)', 'Lanham Act — False Designation of Origin and Unfair Competition', 'Federal unfair competition statute providing a cause of action for false designation of origin and false advertising without requiring federal registration. Protects unregistered trademarks, trade dress, and prohibits false or misleading descriptions of fact in commercial advertising. Two prongs: (1) false association/endorsement and (2) false advertising. This is the primary federal vehicle for trade dress claims and unregistered mark protection.', '["No federal registration required — protects unregistered marks and trade dress","False association — use of word, term, name, symbol, or device likely to cause confusion as to origin, sponsorship, or approval (§ 1125(a)(1)(A))","False advertising — false or misleading description or representation of fact in commercial advertising (§ 1125(a)(1)(B))","Standing requires commercial injury — competitor or directly harmed party (Lexmark Int''l v. Static Control, 572 US 118 (2014))","Trade dress must be nonfunctional and either inherently distinctive or have acquired secondary meaning","Same remedies as registered mark infringement — injunction, damages, profits"]', '[{"section":"1125(a)(1)(A)","description":"False designation of origin — confusion as to source, sponsorship, or approval"},{"section":"1125(a)(1)(B)","description":"False advertising — misleading descriptions or representations of fact"},{"section":"1125(a)(3)","description":"Standing — any person who believes damaged by violation"},{"section":"1125(c)","description":"Dilution of famous marks — blurring and tarnishment"},{"section":"1125(d)","description":"Cybersquatting — bad faith registration of domain names"}]', '["unfair_competition_complaint","false_advertising_complaint","trade_dress_analysis","survey_evidence","consumer_confusion_study","cease_and_desist_letter"]', '["corporate-legal-architecture-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Copyright Act — Subject Matter & Scope
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_021', 'LEXARC', 'FEDERAL_STATUTE', 'US', '17 USC §§ 101-106 (Copyright Act — Subject Matter and Exclusive Rights)', 'Copyright Act §§ 101-106', 'Copyright Act — Subject Matter and Scope of Protection', 'Copyright protection subsists in original works of authorship fixed in a tangible medium of expression. Protection is automatic upon fixation — no registration required for copyright to exist. Eight categories of protectable works: literary, musical, dramatic, pantomime/choreographic, pictorial/graphic/sculptural, motion pictures, sound recordings, and architectural works. The copyright owner holds exclusive rights to reproduce, prepare derivative works, distribute, perform publicly, and display publicly.', '["Originality — minimal creativity threshold (Feist Publications v. Rural Telephone, 499 US 340 (1991))","Fixation in tangible medium of expression required (§ 102(a))","Eight categories of works of authorship (§ 102(a)(1)-(8))","Ideas, procedures, processes, systems, methods of operation not copyrightable (§ 102(b))","Exclusive rights — reproduction, derivative works, distribution, public performance, public display (§ 106)","Work made for hire — employer owns copyright (§ 101 definition, § 201(b))","Duration — life of author plus 70 years; 95 years from publication for works for hire (§ 302)","Fair use defense — purpose, nature, amount, market effect (§ 107)"]', '[{"section":"101","description":"Definitions — including work made for hire, publication, fixed"},{"section":"102(a)","description":"Subject matter — original works of authorship fixed in tangible medium"},{"section":"102(b)","description":"Exclusion — ideas, procedures, processes, systems not copyrightable"},{"section":"103","description":"Compilations and derivative works"},{"section":"106","description":"Exclusive rights — reproduce, derivative works, distribute, perform, display"},{"section":"106A","description":"Rights of attribution and integrity (VARA — visual artists)"},{"section":"107","description":"Fair use — four-factor balancing test"}]', '["copyright_registration","license_agreement","assignment_agreement","work_for_hire_agreement","fair_use_analysis","DMCA_notice"]', '["corporate-legal-architecture-audit"]', 'U.S. Copyright Office / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Copyright Act — Registration & Infringement
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_022', 'LEXARC', 'FEDERAL_STATUTE', 'US', '17 USC §§ 408-412, 501-505 (Copyright Act — Registration and Infringement)', 'Copyright Act §§ 408-412, 501-505', 'Copyright Act — Registration and Infringement Remedies', 'Registration with the Copyright Office is a prerequisite to filing an infringement suit for U.S. works. Timely registration (within 3 months of publication or before infringement) enables statutory damages ($750-$30,000 per work; up to $150,000 for willful infringement) and attorneys fees. Infringement requires proof of ownership and copying — either direct evidence or circumstantial proof of access plus substantial similarity.', '["Registration required before filing suit for U.S. works (§ 411(a); Fourth Estate v. Wall-Street.com, 139 S. Ct. 881 (2019))","Timely registration required for statutory damages and attorneys fees (§ 412)","Infringement — violation of any exclusive right under § 106 (§ 501)","Elements: (1) valid copyright, (2) copying of protectable elements","Actual damages plus infringer profits, or statutory damages at election (§ 504)","Statutory damages: $750-$30,000 per work infringed; up to $150,000 for willful infringement (§ 504(c))","Innocent infringer reduction to $200 per work (§ 504(c)(2))","Injunctive relief — temporary and permanent (§ 502)","Impoundment and disposition of infringing articles (§ 503)"]', '[{"section":"408","description":"Copyright registration in general — permissive"},{"section":"410","description":"Registration of claim — effective date and certificate"},{"section":"411","description":"Registration prerequisite to infringement suit"},{"section":"412","description":"Timely registration required for statutory damages and attorneys fees"},{"section":"501","description":"Infringement of copyright — cause of action"},{"section":"502","description":"Injunctive relief — temporary and final injunctions"},{"section":"503","description":"Impoundment and disposition of infringing articles"},{"section":"504","description":"Damages and profits — actual damages or statutory damages"},{"section":"505","description":"Costs and attorneys fees — court discretion"}]', '["copyright_registration","infringement_complaint","damages_expert_report","injunction_motion","DMCA_takedown","statutory_damages_election"]', '["corporate-legal-architecture-audit"]', 'U.S. Copyright Office / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- DMCA — Safe Harbors
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_023', 'LEXARC', 'FEDERAL_STATUTE', 'US', '17 USC § 512 (Digital Millennium Copyright Act — Online Service Provider Safe Harbors)', 'DMCA § 512', 'DMCA — Online Service Provider Safe Harbors', 'Limits liability of online service providers for copyright infringement by users when the OSP complies with specified conditions. Four safe harbors: (1) transitory digital network communications, (2) system caching, (3) information residing on systems at direction of users, and (4) information location tools. Requires designated DMCA agent, notice-and-takedown procedures, and termination policy for repeat infringers.', '["Designated DMCA agent registered with Copyright Office (§ 512(c)(2))","Notice-and-takedown — expeditious removal upon receiving compliant notice (§ 512(c)(1)(C))","Counter-notification procedure — put-back within 10-14 business days absent court order (§ 512(g))","No actual knowledge of infringing material (§ 512(c)(1)(A))","No financial benefit directly attributable to infringing activity where OSP has right and ability to control (§ 512(c)(1)(B))","Repeat infringer termination policy reasonably implemented (§ 512(i))","Accommodation of standard technical measures (§ 512(i)(1)(B))","Subpoena power to identify infringers (§ 512(h))"]', '[{"section":"512(a)","description":"Transitory digital network communications — conduit safe harbor"},{"section":"512(b)","description":"System caching safe harbor"},{"section":"512(c)","description":"Information stored at direction of users — hosting safe harbor"},{"section":"512(c)(3)","description":"Elements of a compliant DMCA takedown notice"},{"section":"512(d)","description":"Information location tools — search engine safe harbor"},{"section":"512(f)","description":"Misrepresentation in takedown notice — damages liability"},{"section":"512(g)","description":"Counter-notification and put-back procedure"},{"section":"512(i)","description":"Conditions for eligibility — repeat infringer policy and standard technical measures"}]', '["DMCA_takedown_notice","counter_notification","DMCA_agent_designation","repeat_infringer_policy","terms_of_service","copyright_policy"]', '["corporate-legal-architecture-audit"]', 'Federal Courts / U.S. Copyright Office', 1, 1, datetime('now'), datetime('now'));

-- Patent Act — Patentability
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_024', 'LEXARC', 'FEDERAL_STATUTE', 'US', '35 USC §§ 100-105 (Patent Act — Patentability)', 'Patent Act §§ 100-105', 'Patent Act — Conditions for Patentability', 'Establishes the requirements for patentability of inventions. Patent protection grants the inventor a 20-year monopoly (from filing date) in exchange for public disclosure. Four conditions: (1) patentable subject matter, (2) novelty, (3) nonobviousness, and (4) utility. The America Invents Act (2011) converted the U.S. to a first-inventor-to-file system effective March 16, 2013. Abstract ideas, laws of nature, and natural phenomena are not patentable subject matter (Alice Corp. v. CLS Bank, 573 US 208 (2014)).', '["Patentable subject matter — process, machine, manufacture, or composition of matter (§ 101)","Utility — invention must be useful (§ 101)","Novelty — invention must not be anticipated by prior art (§ 102)","First-inventor-to-file priority system (§ 102, AIA amendment)","Nonobviousness — invention must not be obvious to person of ordinary skill in art (§ 103)","Specification must enable person of ordinary skill to make and use invention (§ 112)","Claims define scope of patent protection (§ 112)","20-year term from earliest U.S. filing date (§ 154)","Judicial exceptions: abstract ideas, laws of nature, natural phenomena (Alice/Mayo framework)"]', '[{"section":"100","description":"Definitions — invention, process, patent, inventor"},{"section":"101","description":"Inventions patentable — process, machine, manufacture, composition of matter"},{"section":"102","description":"Conditions for patentability — novelty and prior art"},{"section":"103","description":"Conditions for patentability — nonobviousness"},{"section":"112","description":"Specification — written description, enablement, claims"},{"section":"154","description":"Contents and term of patent — 20 years from filing"}]', '["patent_application","prior_art_search","office_action_response","claims_amendment","continuation_application","patent_grant"]', '["corporate-legal-architecture-audit"]', 'USPTO / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Defend Trade Secrets Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_025', 'LEXARC', 'FEDERAL_STATUTE', 'US', '18 USC § 1836 (Defend Trade Secrets Act of 2016)', 'DTSA § 1836', 'Defend Trade Secrets Act', 'Creates a federal private civil cause of action for trade secret misappropriation. Enacted in 2016 to supplement (not preempt) state trade secret laws. Authorizes ex parte seizure orders in extraordinary circumstances to prevent dissemination. Provides for actual damages plus unjust enrichment, or reasonable royalty. Willful and malicious misappropriation may result in exemplary damages up to 2x actual damages plus attorneys fees. Includes a whistleblower immunity provision requiring notice in employee agreements.', '["Federal civil cause of action for trade secret misappropriation (§ 1836(b))","Trade secret must derive economic value from not being generally known and be subject to reasonable secrecy measures (§ 1839(3))","Misappropriation by improper means or breach of duty (§ 1839(5))","Ex parte seizure in extraordinary circumstances (§ 1836(b)(2))","3-year statute of limitations from discovery (§ 1836(d))","Actual damages plus unjust enrichment, or reasonable royalty (§ 1836(b)(3)(B))","Exemplary damages up to 2x for willful and malicious misappropriation (§ 1836(b)(3)(C))","Attorneys fees for willful/malicious misappropriation or bad faith claim (§ 1836(b)(3)(D))","Whistleblower immunity notice required in employee agreements (§ 1833(b))"]', '[{"section":"1836(b)(1)","description":"Private civil action — owner of trade secret may bring action in federal court"},{"section":"1836(b)(2)","description":"Ex parte seizure — extraordinary circumstances to prevent propagation"},{"section":"1836(b)(3)(A)","description":"Injunctive relief — conditions and limitations"},{"section":"1836(b)(3)(B)","description":"Damages — actual loss, unjust enrichment, or reasonable royalty"},{"section":"1836(b)(3)(C)","description":"Exemplary damages — up to 2x for willful and malicious"},{"section":"1836(d)","description":"Statute of limitations — 3 years from date misappropriation discovered or should have been"},{"section":"1833(b)","description":"Whistleblower immunity — required notice in NDA/employment agreements"},{"section":"1839(3)","description":"Definition of trade secret — economic value from secrecy plus reasonable measures"}]', '["trade_secret_complaint","ex_parte_seizure_motion","NDA_with_whistleblower_notice","trade_secret_inventory","reasonable_measures_audit","injunction_motion"]', '["corporate-legal-architecture-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — California Intellectual Property
-- ═══════════════════════════════════════════════════════════════════════════

-- CA Uniform Trade Secrets Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_026', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 3426-3426.11 (California Uniform Trade Secrets Act)', 'CC §§ 3426-3426.11', 'California Uniform Trade Secrets Act', 'California enactment of the Uniform Trade Secrets Act providing state-law remedies for misappropriation of trade secrets. Supersedes other state civil remedies for trade secret misappropriation except contractual claims. Trade secrets include formulas, patterns, compilations, programs, devices, methods, techniques, or processes that derive independent economic value from not being generally known. CUTSA is the exclusive civil remedy for trade secret misappropriation under California law, preempting common law tort claims based on the same nucleus of facts.', '["Trade secret must derive independent economic value from secrecy (§ 3426.1(d))","Owner must take reasonable measures to maintain secrecy (§ 3426.1(d))","Misappropriation includes acquisition by improper means or breach of duty (§ 3426.1(b))","Injunctive relief — reasonable period to eliminate commercial advantage (§ 3426.2)","Actual damages including unjust enrichment not captured by damages (§ 3426.3)","Exemplary damages up to 2x for willful and malicious misappropriation (§ 3426.3(c))","Attorneys fees for bad faith claim or willful/malicious misappropriation (§ 3426.4)","3-year statute of limitations from discovery or when should have been discovered (§ 3426.6)","CUTSA preempts other civil remedies based on trade secret misappropriation (§ 3426.7)"]', '[{"section":"3426.1","description":"Definitions — trade secret, misappropriation, improper means"},{"section":"3426.2","description":"Injunctive relief — scope and duration"},{"section":"3426.3","description":"Damages — actual loss plus unjust enrichment, or reasonable royalty"},{"section":"3426.3(c)","description":"Exemplary damages — up to 2x for willful and malicious misappropriation"},{"section":"3426.4","description":"Attorneys fees — bad faith or willful/malicious conduct"},{"section":"3426.5","description":"Preservation of secrecy — protective orders during litigation"},{"section":"3426.6","description":"Statute of limitations — 3 years from discovery"},{"section":"3426.7","description":"CUTSA preemption — exclusive civil remedy for trade secret misappropriation"}]', '["trade_secret_complaint","NDA","protective_order","trade_secret_log","injunction_motion","damages_calculation"]', '["corporate-legal-architecture-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- CA Right of Publicity
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_027', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 3344 (Right of Publicity)', 'CC § 3344', 'California Right of Publicity', 'Statutory right of publicity prohibiting unauthorized commercial use of a person''s name, voice, signature, photograph, or likeness. Applies to living persons (§ 3344) and deceased personalities (§ 3344.1 — post-mortem rights for 70 years after death). Plaintiff must prove knowing use for commercial purposes without consent. Damages include greater of actual damages or $750 statutory minimum, plus profits attributable to the use, and punitive damages for knowing violations.', '["Unauthorized use of name, voice, signature, photograph, or likeness (§ 3344(a))","Use must be on or in products, merchandise, goods, services, or for advertising/selling purposes","Defendant must knowingly use plaintiff identity for commercial purpose","Consent is a complete defense","Newsworthy and public affairs exemptions (§ 3344(d))","Post-mortem rights — 70 years after death for deceased personalities (§ 3344.1)","Statutory minimum damages of $750 per unauthorized use (§ 3344(a))","Profits attributable to the unauthorized use (§ 3344(a))","Punitive damages available (§ 3344(a))","Attorneys fees and costs to prevailing party (§ 3344(a))"]', '[{"section":"3344(a)","description":"Liability for unauthorized commercial use of identity — name, voice, signature, photograph, likeness"},{"section":"3344(b)","description":"Consent defense — prior written consent of person"},{"section":"3344(d)","description":"Exemptions — news, public affairs, sports broadcast, political campaigns"},{"section":"3344(e)","description":"Definition — photograph and likeness"},{"section":"3344.1","description":"Post-mortem right of publicity — deceased personality rights for 70 years"}]', '["right_of_publicity_complaint","consent_release","licensing_agreement","cease_and_desist_letter","damages_calculation"]', '["corporate-legal-architecture-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — Securities Law
-- ═══════════════════════════════════════════════════════════════════════════

-- Securities Act 1933 — Registration
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_028', 'LEXARC', 'FEDERAL_STATUTE', 'US', '15 USC §§ 77a-77aa (Securities Act of 1933)', 'Securities Act of 1933', 'Securities Act of 1933 — Registration of Securities', 'Requires registration of securities offerings with the SEC unless an exemption applies. The fundamental purpose is to ensure investors receive material financial and other information concerning securities offered for public sale. Section 5 prohibits the sale or offer to sell securities unless a registration statement is in effect. Section 11 provides strict liability for material misstatements in registration statements. Section 12 provides private right of action for unregistered sales and prospectus fraud.', '["Registration statement (Form S-1) required before public offering (§ 77e)","Prospectus must contain all material information (§ 77j)","Gun-jumping rules — restrictions on offers/sales during waiting period (§ 77e(a)-(c))","Section 11 — strict liability for material misstatements in registration statement (§ 77k)","Section 12(a)(1) — rescission for sale of unregistered securities (§ 77l(a)(1))","Section 12(a)(2) — liability for prospectus fraud — material misstatement or omission (§ 77l(a)(2))","Exemptions — private placements (§ 4(a)(2)), intrastate offerings (§ 3(a)(11)), accredited investors (Reg D)","1-year statute of limitations, 3-year statute of repose (§ 77m)"]', '[{"section":"77b","description":"Definitions — security, sale, offer, issuer, underwriter"},{"section":"77e","description":"Section 5 — prohibition on sale/offer without effective registration statement"},{"section":"77f","description":"Registration of securities — filing and effective date"},{"section":"77j","description":"Information required in prospectus"},{"section":"77k","description":"Section 11 — civil liability for false registration statement"},{"section":"77l","description":"Section 12 — civil liability for unregistered sale or prospectus fraud"},{"section":"77m","description":"Statute of limitations — 1 year from discovery, 3 year repose"},{"section":"77d","description":"Exempt transactions — § 4(a)(1) ordinary trading, § 4(a)(2) private placements"}]', '["registration_statement","prospectus","SEC_filing","offering_memorandum","subscription_agreement","underwriting_agreement","Form_S_1"]', '["corporate-legal-architecture-audit"]', 'SEC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Securities Exchange Act 1934 — Rule 10b-5
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_029', 'LEXARC', 'FEDERAL_REGULATION', 'US', '17 CFR § 240.10b-5 (SEC Rule 10b-5 — Employment of Manipulative and Deceptive Devices)', 'Rule 10b-5', 'SEC Rule 10b-5 — Securities Fraud', 'The most important antifraud provision in federal securities law. Prohibits any act or omission resulting in fraud or deceit in connection with the purchase or sale of any security. Implied private right of action established by case law. Elements of a private 10b-5 claim: (1) material misrepresentation or omission, (2) scienter (intent to deceive or severe recklessness), (3) connection with purchase or sale of security, (4) reliance, (5) economic loss, and (6) loss causation. Applies to insider trading under the classical and misappropriation theories.', '["Material misrepresentation or omission of fact (Rule 10b-5(b))","Scienter — intent to deceive, manipulate, or defraud (Ernst & Ernst v. Hochfelder, 425 US 185 (1976))","In connection with purchase or sale of security (SEC v. Zandford, 535 US 813 (2002))","Reliance — transaction causation (Basic v. Levinson fraud-on-the-market presumption, 485 US 224 (1988))","Economic loss and loss causation (Dura Pharmaceuticals v. Broudo, 544 US 336 (2005))","Insider trading — classical theory (Chiarella) and misappropriation theory (O''Hagan)","PSLRA heightened pleading standards for scienter (15 USC § 78u-4)","2-year/5-year statute of limitations/repose (28 USC § 1658(b))"]', '[{"section":"240.10b-5(a)","description":"Prohibition on employing any device, scheme, or artifice to defraud"},{"section":"240.10b-5(b)","description":"Prohibition on material misstatements or omissions"},{"section":"240.10b-5(c)","description":"Prohibition on any act which operates as fraud or deceit"},{"section":"240.10b5-1","description":"Trading on material nonpublic information — affirmative defense plans"},{"section":"240.10b5-2","description":"Duties of trust or confidence for misappropriation theory"}]', '["securities_fraud_complaint","10b-5_demand_letter","insider_trading_report","Section_16_filing","10b5-1_trading_plan","SEC_enforcement_action"]', '["corporate-legal-architecture-audit"]', 'SEC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Regulation D — Private Placements
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_030', 'LEXARC', 'FEDERAL_REGULATION', 'US', '17 CFR §§ 230.501-508 (SEC Regulation D — Rules Governing Limited Offer and Sale of Securities)', 'Reg D §§ 501-508', 'SEC Regulation D — Private Placement Exemptions', 'Safe harbor rules providing exemptions from Securities Act registration for private offerings. Three principal exemptions: Rule 504 (offerings up to $10 million), Rule 506(b) (unlimited amount, no general solicitation, up to 35 non-accredited sophisticated investors), and Rule 506(c) (unlimited amount, general solicitation permitted, all purchasers must be verified accredited investors). Rule 506 offerings preempt state registration requirements under NSMIA. Form D filing required within 15 days of first sale.', '["Accredited investor definition — income over $200K ($300K joint) or net worth over $1M excluding primary residence (Rule 501(a))","Rule 504 — offerings up to $10 million in 12 months","Rule 506(b) — unlimited amount, no general solicitation, up to 35 non-accredited investors who are sophisticated","Rule 506(c) — unlimited amount, general solicitation permitted, all purchasers must be verified accredited investors","Form D notice filing with SEC within 15 days of first sale (Rule 503)","Bad actor disqualification for certain felons and securities violators (Rule 506(d))","Integration doctrine — separate offerings may be treated as one (Rule 502(a))","Resale restrictions — securities are restricted, legend required (Rule 502(d))","State preemption under NSMIA for Rule 506 offerings — notice filing only"]', '[{"section":"230.501","description":"Definitions — accredited investor, purchaser representative"},{"section":"230.502","description":"General conditions — integration, information requirements, resale limitations"},{"section":"230.503","description":"Form D notice filing requirement"},{"section":"230.504","description":"Rule 504 — exemption for limited offerings up to $10 million"},{"section":"230.506(b)","description":"Rule 506(b) — exemption without general solicitation, up to 35 non-accredited"},{"section":"230.506(c)","description":"Rule 506(c) — exemption with general solicitation, verified accredited only"},{"section":"230.506(d)","description":"Bad actor disqualification provisions"},{"section":"230.508","description":"Insignificant deviations from Reg D requirements"}]', '["private_placement_memorandum","subscription_agreement","accredited_investor_questionnaire","Form_D","investor_suitability","offering_memorandum","restricted_stock_legend"]', '["corporate-legal-architecture-audit"]', 'SEC', 0, 1, datetime('now'), datetime('now'));

-- CA Corporate Securities Law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_031', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Corp. Code §§ 25000-25707 (California Corporate Securities Law of 1968)', 'Corp Code § 25000+', 'California Corporate Securities Law of 1968', 'California blue sky law regulating the offer and sale of securities within the state. Uses qualification (permit) system rather than federal registration approach — Commissioner of Financial Protection and Innovation must qualify offerings unless exempt. Section 25110 requires qualification before any offer or sale. Section 25401 prohibits material misstatements or omissions in connection with securities transactions. Section 25501 provides a private right of action for securities fraud. NSMIA preempts state registration for Rule 506 offerings but California retains antifraud jurisdiction.', '["Qualification (permit) required before offer or sale of securities (§ 25110)","Commissioner of Financial Protection and Innovation reviews and qualifies offerings","Exemptions — § 25102(f) limited offering exemption (up to 35 purchasers), § 25102(n) accredited investor exemption","§ 25401 — unlawful to make material misstatement or omission in securities offer/sale","§ 25501 — private right of action for violation of § 25401 — rescission or damages","§ 25504 — joint and several liability for control persons and aiders","§ 25540 — criminal penalties for willful violations","Notice filing required for Rule 506 offerings — Form D-506"]', '[{"section":"25102","description":"Exempt transactions — enumerated exemptions from qualification"},{"section":"25102(f)","description":"Limited offering exemption — up to 35 purchasers with suitability"},{"section":"25110","description":"Qualification requirement — no offer or sale without qualification or exemption"},{"section":"25113","description":"Qualification by permit — application to Commissioner"},{"section":"25401","description":"Antifraud — material misstatement or omission prohibition"},{"section":"25501","description":"Private right of action — rescission or damages for securities fraud"},{"section":"25504","description":"Joint and several liability — controlling persons and aiders"},{"section":"25540","description":"Criminal penalties — fine up to $10 million and/or imprisonment up to 10 years"}]', '["qualification_application","25102f_notice","offering_circular","subscription_agreement","Form_D_506_notice","investor_suitability_questionnaire","blue_sky_opinion"]', '["corporate-legal-architecture-audit"]', 'California DFPI (Department of Financial Protection and Innovation)', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — Antitrust and Competition Law
-- ═══════════════════════════════════════════════════════════════════════════

-- Sherman Antitrust Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_032', 'LEXARC', 'FEDERAL_STATUTE', 'US', '15 USC §§ 1-7 (Sherman Antitrust Act)', 'Sherman Act §§ 1-7', 'Sherman Antitrust Act', 'Primary federal antitrust statute prohibiting (1) contracts, combinations, and conspiracies in restraint of trade (§ 1), and (2) monopolization, attempted monopolization, and conspiracy to monopolize (§ 2). Section 1 requires concerted action — agreement between two or more entities. Section 2 applies to unilateral conduct. Per se violations include price fixing, bid rigging, and market allocation. Rule of reason analysis applies to most other restraints. Criminal penalties include up to $100 million for corporations and 10 years imprisonment for individuals.', '["§ 1 — Every contract, combination, or conspiracy in restraint of trade is illegal","§ 2 — Monopolization, attempted monopolization, or conspiracy to monopolize is illegal","Per se violations — price fixing, bid rigging, market allocation, group boycotts","Rule of reason — balances procompetitive justifications against anticompetitive harm","§ 1 requires agreement/concerted action between separate entities","§ 2 applies to unilateral conduct — monopoly power plus willful acquisition/maintenance","Criminal penalties: corporations up to $100 million fine; individuals up to $1 million fine and 10 years imprisonment","Treble damages for private plaintiffs under Clayton Act § 4 (15 USC § 15)"]', '[{"section":"1","description":"Restraint of trade — contracts, combinations, conspiracies declared illegal"},{"section":"2","description":"Monopolization — monopolizing, attempting to monopolize, or conspiring to monopolize"},{"section":"3","description":"Restraint of trade in territories and D.C."},{"section":"4","description":"Jurisdiction of courts — equity proceedings by government"},{"section":"6","description":"Property in transit — forfeiture"},{"section":"7","description":"Definitions — person includes corporations and associations"}]', '["antitrust_complaint","DOJ_investigation","consent_decree","market_analysis","merger_review","leniency_application","treble_damages_complaint"]', '["corporate-legal-architecture-audit"]', 'DOJ Antitrust Division / FTC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Clayton Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_033', 'LEXARC', 'FEDERAL_STATUTE', 'US', '15 USC §§ 12-27 (Clayton Antitrust Act)', 'Clayton Act §§ 12-27', 'Clayton Antitrust Act', 'Supplements the Sherman Act by addressing specific anticompetitive practices. Prohibits price discrimination (§ 2, as amended by Robinson-Patman Act), tying arrangements and exclusive dealing (§ 3), and mergers and acquisitions that may substantially lessen competition (§ 7). Section 4 creates the private treble damages remedy — any person injured by antitrust violation may recover threefold damages plus attorneys fees. Section 16 authorizes private injunctive relief. Hart-Scott-Rodino Act (§ 7A) requires pre-merger notification for transactions above threshold.', '["§ 2 — Price discrimination prohibited where effect may substantially lessen competition (Robinson-Patman Act)","§ 3 — Tying arrangements and exclusive dealing contracts prohibited","§ 4 — Private treble damages action — any person injured in business or property","§ 4 — Standing requires antitrust injury — injury of the type the antitrust laws were intended to prevent","§ 7 — Mergers and acquisitions prohibited where effect may be to substantially lessen competition","§ 7A (HSR Act) — Pre-merger notification required above threshold ($119.5M in 2025)","§ 16 — Private parties may seek injunctive relief","4-year statute of limitations (§ 4B)"]', '[{"section":"12","description":"Definitions — antitrust laws, commerce, person"},{"section":"13","description":"Price discrimination (Robinson-Patman Act amendment)"},{"section":"14","description":"Tying and exclusive dealing — sale on condition of not dealing with competitor"},{"section":"15","description":"Treble damages — any person injured may sue for threefold damages plus attorneys fees"},{"section":"18","description":"Mergers — acquisition of stock or assets where effect may substantially lessen competition"},{"section":"18a","description":"Hart-Scott-Rodino pre-merger notification — filing and waiting period"},{"section":"26","description":"Injunctive relief for private parties"}]', '["antitrust_complaint","treble_damages_complaint","HSR_filing","merger_review","second_request","consent_decree","competitive_impact_statement"]', '["corporate-legal-architecture-audit"]', 'DOJ Antitrust Division / FTC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- CA Cartwright Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_034', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 16700-16770 (Cartwright Act)', 'BPC §§ 16700-16770', 'California Cartwright Act', 'California''s principal antitrust statute, broader than the federal Sherman Act. Prohibits trusts — combinations to restrain trade, prevent competition, fix prices, or control production. Unlike the Sherman Act, the Cartwright Act covers combinations involving a single entity and its agents. Provides treble damages to any person injured by a trust violation. California courts apply both per se and rule of reason analysis. The Cartwright Act reaches horizontal and vertical restraints, and indirect purchasers have standing to sue (unlike federal antitrust law under Illinois Brick).', '["Trust defined — combination to create or carry out restrictions in trade, limit production, fix prices, or prevent competition (§ 16720)","Broadly covers any person — including single entity acting through agents","Per se violations include price fixing, bid rigging, and market allocation","Rule of reason applies to most vertical restraints","Treble damages for any person injured directly or indirectly (§ 16750)","Indirect purchaser standing — California rejects Illinois Brick doctrine","Attorney General enforcement authority — civil and criminal (§ 16754)","Criminal penalties — felony with fine and/or imprisonment (§ 16755)","4-year statute of limitations (§ 16750.1)"]', '[{"section":"16720","description":"Trust defined — combination to restrain trade, fix prices, prevent competition"},{"section":"16726","description":"Non-compete agreements — prohibition (except as to sale of business or dissolution of partnership)"},{"section":"16750","description":"Private right of action — treble damages for persons injured by trust"},{"section":"16750.1","description":"Statute of limitations — 4 years"},{"section":"16754","description":"Attorney General enforcement — actions for injunctive relief"},{"section":"16755","description":"Criminal penalties — felony for trust violations"}]', '["antitrust_complaint","treble_damages_complaint","AG_enforcement_action","market_analysis","competitive_impact_analysis","injunction_motion"]', '["corporate-legal-architecture-audit"]', 'California Attorney General / California Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- LEXARC — Business Torts
-- ═══════════════════════════════════════════════════════════════════════════

-- CA Unfair Competition Law
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_lex_035', 'LEXARC', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 17200-17210 (Unfair Competition Law)', 'BPC §§ 17200-17210', 'California Unfair Competition Law (UCL)', 'California''s broadest consumer protection and business tort statute. Defines unfair competition as any unlawful, unfair, or fraudulent business act or practice and any false or misleading advertising. Three independent prongs: (1) unlawful — violation of any other law, (2) unfair — conduct whose harm outweighs utility, and (3) fraudulent — conduct likely to deceive members of the public. Standing requires loss of money or property as a result of unfair competition (Prop 64, 2004). Remedies limited to restitution and injunctive relief — no damages or penalties in private actions.', '["Unlawful prong — borrows from any federal, state, or local law violation as predicate (§ 17200)","Unfair prong — business practice whose harm to victim outweighs any legitimate utility","Fraudulent prong — conduct likely to deceive reasonable members of the public","Standing — private plaintiff must have suffered injury in fact and lost money or property (§ 17204, Prop 64)","Remedies in private action limited to restitution and injunctive relief — no damages (§ 17203)","Attorney General, district attorney, and certain city attorneys may seek civil penalties up to $2,500 per violation (§ 17206)","4-year statute of limitations (§ 17208)","Representative actions under § 17203 — standing requirements apply to named plaintiff","Prevailing defendant not entitled to attorneys fees absent contractual or statutory basis"]', '[{"section":"17200","description":"Unfair competition defined — unlawful, unfair, or fraudulent business act or practice"},{"section":"17201","description":"Definitions — unfair competition includes false advertising under § 17500"},{"section":"17203","description":"Remedies — injunction, restitution, and disgorgement of money or property"},{"section":"17204","description":"Standing — person who has suffered injury in fact and lost money or property"},{"section":"17206","description":"Civil penalties — AG, DA, or city attorney may seek up to $2,500 per violation"},{"section":"17208","description":"Statute of limitations — 4 years"}]', '["UCL_complaint","restitution_motion","injunction_motion","unfair_business_practice_analysis","consumer_complaint","AG_enforcement_action"]', '["corporate-legal-architecture-audit"]', 'California Attorney General / District Attorney / California Courts', 1, 1, datetime('now'), datetime('now'));
