-- Vernen Legal Compliance — Texas State Compliance Rules (Seed Texas)
-- ALL categories in single file (~300 rules)
-- Texas Business Organizations Code (BOC), Texas Tax Code, Texas Labor Code, etc.
-- Created: April 5, 2026

-- ============================================================
-- SECTION 1: FORMATION (25 rules) — Texas Business Organizations Code
-- ============================================================

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-001', 'TX-FORM-001', 'Texas LLC Certificate of Formation', 'Domestic limited liability companies must file a Certificate of Formation with the Texas Secretary of State. Filing fee is $300. Certificate must include LLC name (with "Limited Liability Company," "Limited Company," or abbreviation L.L.C., LLC, L.C., LC), registered agent and registered office address, governing authority (member-managed or manager-managed), purpose, and organizer information. Effective on filing or on a delayed effective date up to 90 days later.', 'FORMATION', 'STATE', 'TX', '["LLC"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 3.005; § 3.010; § 101.001', 'https://www.sos.state.tx.us/corp/forms_boc.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-002', 'TX-FORM-002', 'Texas For-Profit Corporation Certificate of Formation', 'Domestic for-profit corporations must file a Certificate of Formation with the Texas Secretary of State. Filing fee is $300. Required content includes corporate name, purpose, period of duration, registered agent/office, number of authorized shares (par or no-par), initial directors, and organizer. Corporate name must contain "Corporation," "Company," "Incorporated," "Limited," or an abbreviation.', 'FORMATION', 'STATE', 'TX', '["CORPORATION","S_CORP"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 21; § 3.007; § 5.054', 'https://www.sos.state.tx.us/corp/forms_boc.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-003', 'TX-FORM-003', 'Texas Nonprofit Corporation Formation', 'Texas nonprofit corporations file Certificate of Formation under BOC Chapter 22. Filing fee is $25. Must specify whether the corporation has members, manner of director election, and purpose. 501(c)(3) language must be added separately for federal tax exemption — Texas does not require it for state formation but does for state franchise tax exemption.', 'FORMATION', 'STATE', 'TX', '["NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 22; § 22.051', 'https://www.sos.state.tx.us/corp/nonprofit_org.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-004', 'TX-FORM-004', 'Texas Registered Agent Requirement', 'Every domestic and foreign filing entity must continuously maintain a registered agent and registered office in Texas. Agent must be (1) an individual resident of Texas, or (2) an organization registered to do business in Texas. The registered office must be a physical street address in Texas (no P.O. boxes). Agent must consent in writing to appointment. Failure to maintain may result in involuntary termination.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 5.201; § 5.202; § 5.206', 'https://www.sos.state.tx.us/corp/registeredagent.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-005', 'TX-FORM-005', 'Texas Assumed Name Certificate (DBA)', 'A business entity that conducts business under a name other than its legal name must file an Assumed Name Certificate with the Texas Secretary of State (for entities) and/or the county clerk where the business is located. Filing fee with SOS is $25. Certificate is effective for 10 years and must be renewed. Sole proprietors and general partnerships file only with the county clerk.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. & Com. Code Ch. 71', 'https://www.sos.state.tx.us/corp/assumedname.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-006', 'TX-FORM-006', 'Texas Series LLC Authorization', 'Texas authorizes series LLCs under BOC § 101.601-101.621. A series LLC may establish one or more designated series of members, managers, membership interests, or assets, each with separate rights, powers, duties, and liability shielding. To obtain liability separation between series, the certificate of formation and company agreement must provide for it and records of each series must be maintained separately.', 'FORMATION', 'STATE', 'TX', '["LLC"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 101.601 through § 101.621', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.101.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-007', 'TX-FORM-007', 'Texas Professional Entity Requirements', 'Licensed professionals (physicians, attorneys, CPAs, architects, engineers, etc.) may organize as a Professional Corporation (PC), Professional Limited Liability Company (PLLC), or Professional Association (PA). All owners must be licensed in the same profession (with limited exceptions). Filing must include statement of professional purpose. Filing fee is $300.', 'FORMATION', 'STATE', 'TX', '["CORPORATION","LLC"]', '2024-01-01', 'Tex. Bus. Orgs. Code Title 7 (Ch. 301-305)', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.301.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-008', 'TX-FORM-008', 'Texas Limited Partnership Formation', 'A Texas limited partnership is formed by filing a Certificate of Formation with the Secretary of State. Filing fee is $750. Must include name (with "Limited Partnership," "L.P.," or "LP"), registered agent/office, name and address of each general partner, and address of principal office. Limited partners are not liable beyond their capital contributions if they do not participate in control.', 'FORMATION', 'STATE', 'TX', '["PARTNERSHIP"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 153; § 3.011', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.153.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-009', 'TX-FORM-009', 'Texas Limited Liability Partnership (LLP) Registration', 'A general or limited partnership becomes an LLP by filing an Application for Registration of an LLP with the Secretary of State. Filing fee is $200 per partner (capped). LLP registration provides liability protection to partners against partnership obligations. Annual renewal required by June 1 each year. Failure to renew terminates LLP status.', 'FORMATION', 'STATE', 'TX', '["PARTNERSHIP"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 152.802; § 152.806', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.152.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-010', 'TX-FORM-010', 'Texas Foreign Entity Registration', 'A foreign entity transacting business in Texas must file an Application for Registration with the Secretary of State. Fees: $750 for foreign LLC/corporation, $750 for foreign LP. Failure to register subjects the entity to civil penalties equal to all fees and franchise taxes that should have been paid plus penalty, and bars maintaining a lawsuit in Texas courts.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 9; § 9.001; § 9.051', 'https://www.sos.state.tx.us/corp/forms_boc.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-011', 'TX-FORM-011', 'Texas Franchise Tax as Formation Gate', 'A Texas entity is not in good standing if it has not filed required franchise tax reports or paid franchise tax. The Comptroller may forfeit the entity''s right to transact business. Forfeiture results in personal liability of officers and directors for debts incurred after forfeiture. Reinstatement requires payment of all back taxes, penalties, and interest plus a tax clearance letter.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Tax Code § 171.251; § 171.252; § 171.255', 'https://comptroller.texas.gov/taxes/franchise/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-012', 'TX-FORM-012', 'Texas Entity Name Distinguishability', 'The name of a filing entity must be distinguishable in the records of the Secretary of State from the name of any other existing domestic or foreign filing entity, name reservation, or registered name. Differences in punctuation, capitalization, articles, conjunctions, prepositions, abbreviations, or entity designators are not sufficient to distinguish names.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 5.053', 'https://www.sos.state.tx.us/corp/namefilingsfaqs.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-013', 'TX-FORM-013', 'Texas Name Reservation', 'A person may reserve the exclusive use of an entity name for 120 days by filing an Application for Reservation of Name with the Secretary of State. Filing fee is $40. Reservation may be renewed for additional 120-day periods. Reservation may be transferred to another person by written notice to the Secretary of State.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 5.101 through § 5.106', 'https://www.sos.state.tx.us/corp/namefilingsfaqs.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-014', 'TX-FORM-014', 'Texas LLC Company Agreement (Operating Agreement)', 'Texas LLCs are governed by a "company agreement" (operating agreement). The agreement is not required to be filed with the state and may be written, oral, or implied. The company agreement governs relations among members, managers, and the LLC itself, including capital contributions, allocations, distributions, transfer restrictions, and dissolution.', 'FORMATION', 'STATE', 'TX', '["LLC"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 101.052; § 101.053', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.101.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-015', 'TX-FORM-015', 'Texas Corporate Bylaws Requirement', 'Texas for-profit corporations must adopt bylaws to manage the business and affairs of the corporation. Bylaws are adopted by the board of directors or, if directors are not named in the certificate of formation, by the incorporators. Bylaws are not filed with the state but must be maintained at the principal office and made available for shareholder inspection.', 'FORMATION', 'STATE', 'TX', '["CORPORATION","S_CORP"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 21.057; § 21.058', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.21.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-016', 'TX-FORM-016', 'Texas Initial Organizational Meeting', 'After formation, the directors named in the certificate of formation (or the incorporators if directors are not named) must hold an organizational meeting to adopt bylaws, elect officers, authorize issuance of shares, and conduct other initial business. May be held in person or by unanimous written consent.', 'FORMATION', 'STATE', 'TX', '["CORPORATION","S_CORP"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 21.059', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.21.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-017', 'TX-FORM-017', 'Texas Corporate Books and Records', 'Texas corporations must maintain books and records of account, minutes of shareholder, board, and committee meetings, and a record of shareholders giving names, addresses, and number/class of shares held. Records must be maintained at the principal office or with the secretary or registered agent. Shareholders have inspection rights upon written demand stating proper purpose.', 'FORMATION', 'STATE', 'TX', '["CORPORATION","S_CORP"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 3.151; § 21.218', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.3.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-018', 'TX-FORM-018', 'Texas Public Benefit Corporation', 'Texas authorized public benefit corporations effective September 1, 2017 (amended 2023). A Texas PBC is a for-profit corporation organized for the purpose of producing a public benefit and operating in a responsible and sustainable manner. Must include "Public Benefit Corporation" or "PBC" in name and identify specific public benefit purposes in certificate of formation. Annual benefit report required to shareholders.', 'FORMATION', 'STATE', 'TX', '["CORPORATION","S_CORP"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 21, Subchapter S (§ 21.951-21.959)', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.21.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-019', 'TX-FORM-019', 'Texas LLC Management Structure Election', 'Texas LLCs must elect either member-managed or manager-managed structure in the certificate of formation. In member-managed LLCs, all members have authority to bind the LLC. In manager-managed LLCs, only designated managers have such authority. Members in manager-managed LLCs are like passive investors.', 'FORMATION', 'STATE', 'TX', '["LLC"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 101.251; § 101.252', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.101.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-020', 'TX-FORM-020', 'Texas Conversion of Entity', 'A Texas entity may convert to a different type of entity (e.g., LLC to corporation) by filing a Certificate of Conversion plus a Certificate of Formation for the converted entity. Filing fee is $300 plus the filing fee for the new entity type. Plan of conversion must be approved by owners as required for a fundamental business transaction.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 10, Subchapter C (§ 10.101-10.108)', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.10.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-021', 'TX-FORM-021', 'Texas Merger Filing', 'A Texas merger requires filing a Certificate of Merger with the Secretary of State plus a plan of merger approved by each constituent organization as provided by its governing documents and the BOC. Filing fee is $300. Merger may be between same or different entity types.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 10, Subchapter A (§ 10.001-10.014)', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.10.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-022', 'TX-FORM-022', 'Texas Voluntary Termination (Dissolution)', 'A Texas entity may voluntarily wind up and terminate by filing a Certificate of Termination with the Secretary of State after winding up its affairs. Filing fee is $40. Must obtain a Certificate of Account Status from the Texas Comptroller showing that all franchise taxes have been paid before termination is effective.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code Ch. 11; § 11.101; § 11.105', 'https://www.sos.state.tx.us/corp/forms_boc.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-023', 'TX-FORM-023', 'Texas Reinstatement After Forfeiture', 'An entity that has been involuntarily terminated or forfeited may apply for reinstatement by filing an Application for Reinstatement and Request to Set Aside Tax Forfeiture, paying all back franchise taxes, penalties, and interest, and obtaining a tax clearance letter from the Comptroller. Filing fee is $75.', 'FORMATION', 'STATE', 'TX', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 11.253; Tex. Tax Code § 171.313', 'https://www.sos.state.tx.us/corp/forms_boc.shtml', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-024', 'TX-FORM-024', 'Texas Statement of Authority', 'A general partnership or LLP may file a Statement of Authority with the Secretary of State to grant or limit authority of partners to transfer real property or enter into transactions. Filing fee is $25. Provides constructive notice to third parties of the scope of partner authority.', 'FORMATION', 'STATE', 'TX', '["PARTNERSHIP"]', '2024-01-01', 'Tex. Bus. Orgs. Code § 152.302; § 152.303', 'https://statutes.capitol.texas.gov/Docs/BO/htm/BO.152.htm', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('tx-form-025', 'TX-FORM-025', 'Texas Sole Proprietorship — No Formation Filing', 'A sole proprietorship in Texas requires no formation filing with the Secretary of State. The owner is personally liable for all business debts. If operating under a name other than the owner''s legal name, an Assumed Name Certificate must be filed with the county clerk where the business is located. Local business licenses may also be required.', 'FORMATION', 'STATE', 'TX', '["SOLE_PROPRIETORSHIP"]', '2024-01-01', 'Tex. Bus. & Com. Code Ch. 71', 'https://www.sos.state.tx.us/corp/assumedname.shtml', 1);
