-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 23
-- ═══════════════════════════════════════════════════════════════════════════
-- Cross-domain landmark case law batch 3: qualified immunity, pleading,
-- constitutional rights, employment discrimination, CA labor, financial
-- standing, privacy/technology, housing, family law.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- QUALIFIED IMMUNITY / § 1983 (ADVOCIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Harlow v. Fitzgerald — Qualified Immunity Objective Test
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_035', 'ADVOCIS', 'CASE_LAW', 'US', 'Harlow v. Fitzgerald, 457 U.S. 800 (1982)', 'Harlow v. Fitzgerald', 'Qualified Immunity — Objective Legal Reasonableness Standard', 'Replaced subjective good-faith immunity test with objective standard. Government officials performing discretionary functions are shielded from liability for civil damages insofar as their conduct does not violate clearly established statutory or constitutional rights of which a reasonable person would have known. Eliminated subjective component (good faith/malice inquiry) because it created factual disputes defeating summary judgment. QI protects "all but the plainly incompetent or those who knowingly violate the law."', '["Objective test: did conduct violate clearly established law at time of action","Eliminated subjective good-faith inquiry from QI analysis","Clearly established means contours of right sufficiently clear that reasonable official would understand conduct violates it","Officials performing discretionary functions receive QI","QI is immunity from suit, not merely defense to liability","QI question should be resolved at earliest possible stage — summary judgment","Burden on plaintiff to show right was clearly established","Protects all but plainly incompetent or knowing violators"]', '[{"section":"Holding","description":"QI turns on objective legal reasonableness under clearly established law, not subjective intent"},{"section":"Standard","description":"Would a reasonable official understand that conduct violated clearly established right"},{"section":"Procedure","description":"QI resolved at summary judgment — immunity from suit not just liability"},{"section":"Impact","description":"Foundation of modern qualified immunity doctrine — two-step Saucier analysis built on this"}]', '["qualified_immunity_motion","summary_judgment_motion","1983_complaint","clearly_established_law_brief","interlocutory_appeal"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Hope v. Pelzer — Obvious Clarity Standard
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_036', 'ADVOCIS', 'CASE_LAW', 'US', 'Hope v. Pelzer, 536 U.S. 730 (2002)', 'Hope v. Pelzer', 'Qualified Immunity — Obvious Clarity Without Materially Similar Facts', 'Plaintiff need not identify a case with materially similar facts to overcome qualified immunity. General constitutional principles can clearly establish a right when the unlawfulness of the conduct is apparent from pre-existing law. Handcuffing inmate to hitching post in the sun for seven hours was obviously unconstitutional under Eighth Amendment even without case with identical facts. Officials can be on notice that their conduct is unlawful even in novel factual circumstances.', '["No requirement of prior case with materially similar facts to defeat QI","General statements of law can clearly establish right in obvious cases","Obvious clarity: conduct so egregious that any reasonable officer would know it violated Constitution","Officials on notice their conduct violates established law even in novel circumstances","Eighth Amendment cruel and unusual punishment standard applied","Broad hope of law — not just narrow factual precedent — determines clearly established","Rejects rigid requirement of factually identical prior case"]', '[{"section":"Holding","description":"Materially similar prior case not required — general constitutional principles can clearly establish right"},{"section":"Obvious Clarity","description":"When unlawfulness is apparent from pre-existing law, specific factual precedent unnecessary"},{"section":"Application","description":"Hitching post punishment obviously cruel and unusual without identical prior case"},{"section":"Impact","description":"Limits ability of officials to claim QI in cases of obvious constitutional violation"}]', '["qualified_immunity_opposition","clearly_established_law_brief","obvious_clarity_argument","1983_complaint","eighth_amendment_claim"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- City of Canton v. Harris — Failure to Train
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_037', 'ADVOCIS', 'CASE_LAW', 'US', 'City of Canton v. Harris, 489 U.S. 378 (1989)', 'City of Canton v. Harris', 'Municipal Liability — Failure to Train Under Deliberate Indifference Standard', 'Municipality may be liable under § 1983 for failure to train employees where the failure amounts to deliberate indifference to the rights of persons with whom employees come into contact. Inadequacy of training must be closely related to the ultimate injury. Must show: (1) training program inadequate relative to tasks officers must perform, (2) inadequacy resulted from municipality''s deliberate indifference, (3) inadequacy actually caused the constitutional violation. Single-incident liability possible when need for training is so obvious.', '["Failure to train can be policy or custom for Monell municipal liability","Deliberate indifference: municipality knows of need and disregards it","Training inadequacy must be closely related to constitutional injury","Three elements: inadequate program, deliberate indifference, causation","Pattern of violations normally required to show deliberate indifference","Single-incident liability where need for training is obvious and predictable","Not simple negligence — must rise to deliberate indifference","City must have actual or constructive notice of deficiency"]', '[{"section":"Holding","description":"Municipality liable under § 1983 for failure to train amounting to deliberate indifference"},{"section":"Standard","description":"Deliberate indifference — not negligence — to known training deficiency"},{"section":"Causation","description":"Training inadequacy must be closely related to the constitutional violation"},{"section":"Single Incident","description":"Possible liability from single incident where need for training is obvious"},{"section":"Impact","description":"Established failure-to-train as viable Monell theory — extends Canton to failure to supervise"}]', '["failure_to_train_claim","Monell_claim","deliberate_indifference_evidence","municipal_liability_complaint","pattern_and_practice_evidence","police_training_records_request"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PLEADING STANDARDS (ADVOCIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Bell Atlantic Corp. v. Twombly — Plausibility Pleading
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_038', 'ADVOCIS', 'CASE_LAW', 'US', 'Bell Atlantic Corp. v. Twombly, 550 U.S. 544 (2007)', 'Twombly', 'Plausibility Pleading Standard — Retirement of "No Set of Facts" Test', 'Replaced Conley v. Gibson''s "no set of facts" standard with plausibility pleading requirement under FRCP 8(a)(2). Complaint must contain enough factual matter, accepted as true, to state a claim to relief that is plausible on its face. Claim has facial plausibility when plaintiff pleads factual content that allows court to draw reasonable inference that defendant is liable. Allegations must nudge claims across line from conceivable to plausible. Labels, conclusions, and formulaic recitation of elements not sufficient.', '["Plausibility standard replaces Conley no-set-of-facts test","Factual matter must state claim plausible on its face","Court draws reasonable inferences in plaintiff''s favor","Labels, conclusions, formulaic recitation insufficient","Factual content must allow inference of liability","Conceivable is not enough — must be plausible","Applied through Iqbal to all federal civil cases","Two-step analysis: identify conclusory statements, then assess plausibility of remaining facts"]', '[{"section":"Holding","description":"Complaint must state plausible claim — retired Conley no-set-of-facts standard"},{"section":"Plausibility","description":"Facial plausibility when factual content allows reasonable inference of liability"},{"section":"Threshold","description":"Claims must be nudged from conceivable to plausible"},{"section":"Impact","description":"Heightened pleading standard — extended to all civil cases by Ashcroft v. Iqbal (2009)"}]', '["federal_complaint","motion_to_dismiss_12b6","opposition_to_motion_to_dismiss","amended_complaint","plausibility_analysis"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CONSTITUTIONAL / CIVIL RIGHTS (ADVOCIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Griswold v. Connecticut — Right to Privacy
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_039', 'ADVOCIS', 'CASE_LAW', 'US', 'Griswold v. Connecticut, 381 U.S. 479 (1965)', 'Griswold v. Connecticut', 'Right to Privacy in Marital Relations — Penumbras of the Bill of Rights', 'Struck down Connecticut law criminalizing use of contraceptives by married couples. Right to privacy found in penumbras and emanations of the First, Third, Fourth, Fifth, and Ninth Amendments. The marital relationship lies within a zone of privacy created by several fundamental constitutional guarantees. Government may not intrude into the sacred precincts of marital bedrooms. Foundation for substantive due process privacy rights expanded in Eisenstadt, Roe, Lawrence, and Obergefell.', '["Right to privacy exists in penumbras of Bill of Rights","First Amendment: right of association and periphery rights","Third Amendment: prohibition on quartering soldiers implies privacy of home","Fourth Amendment: right against unreasonable searches — privacy of persons and effects","Fifth Amendment: self-incrimination clause — zone of privacy","Ninth Amendment: enumerated rights shall not be construed to deny other rights retained by people","Marital relationship within zone of constitutional privacy","State cannot regulate intimate decisions of married couples"]', '[{"section":"Holding","description":"Right to marital privacy found in penumbras and emanations of Bill of Rights"},{"section":"Penumbras","description":"Specific guarantees in Bill of Rights have penumbras formed by emanations giving them life and substance"},{"section":"Zone of Privacy","description":"Marriage lies within zone of privacy created by several constitutional guarantees"},{"section":"Impact","description":"Foundation for modern privacy jurisprudence — Eisenstadt, Roe, Lawrence, Obergefell"}]', '["privacy_rights_motion","due_process_claim","constitutional_challenge","family_privacy_argument","substantive_due_process_brief"]', '["victim-rights-marsys-law-audit"]', 'US Supreme Court', 1, 1, datetime('now'), datetime('now'));

-- Lawrence v. Texas — Liberty and Intimate Conduct
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_040', 'ADVOCIS', 'CASE_LAW', 'US', 'Lawrence v. Texas, 539 U.S. 558 (2003)', 'Lawrence v. Texas', 'Due Process Liberty Protects Intimate Conduct Between Consenting Adults', 'Struck down Texas anti-sodomy statute. Overruled Bowers v. Hardwick (1986). Liberty under the Due Process Clause gives persons the full right to engage in private conduct without government intervention. Adults may choose to enter personal relationships in the confines of their homes and their own private lives and still retain their dignity as free persons. Moral disapproval alone is not a legitimate state interest sufficient to justify intrusion into personal and private life.', '["Liberty under Due Process Clause protects intimate conduct","Overruled Bowers v. Hardwick — liberty interest not limited to those historically recognized","Private consensual conduct between adults is constitutionally protected","Moral disapproval alone not legitimate state interest to justify intrusion","Dignity of free persons includes right to define personal relationships","State cannot demean existence or control destiny by criminalizing private conduct","Not decided on Equal Protection grounds — broader liberty rationale","Petitioners entitled to respect for their private lives"]', '[{"section":"Holding","description":"Due Process liberty protects intimate conduct between consenting adults — overrules Bowers"},{"section":"Liberty Interest","description":"Right to make choices about intimate conduct is a form of liberty protected by Constitution"},{"section":"Moral Disapproval","description":"Moral disapproval alone insufficient state interest to criminalize private conduct"},{"section":"Impact","description":"Foundation for dignity-based liberty jurisprudence — cited in Obergefell and Windsor"}]', '["due_process_liberty_claim","privacy_rights_motion","substantive_due_process_brief","equal_protection_claim","constitutional_challenge"]', '["victim-rights-marsys-law-audit"]', 'US Supreme Court', 1, 1, datetime('now'), datetime('now'));

-- Brown v. Board of Education — Equal Protection
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_041', 'ADVOCIS', 'CASE_LAW', 'US', 'Brown v. Board of Education, 347 U.S. 483 (1954)', 'Brown v. Board of Education', 'Separate But Equal Is Inherently Unequal — Equal Protection Clause', 'Unanimously overruled Plessy v. Ferguson''s "separate but equal" doctrine in public education. Segregation of children in public schools solely on basis of race, even where physical facilities and other tangible factors are equal, deprives children of the minority group of equal educational opportunities. Separate educational facilities are inherently unequal and violate the Equal Protection Clause of the Fourteenth Amendment. Education is the most important function of state and local governments.', '["Separate but equal is inherently unequal in public education","Overruled Plessy v. Ferguson separate but equal doctrine","Segregation solely on race denies equal educational opportunity","Equal Protection Clause of 14th Amendment prohibits racial segregation","Education is most important function of state and local governments","Psychological harm of segregation — generates feeling of inferiority","Cannot turn back clock — must consider public education in light of its full development","Unanimous decision — Warren Court"]', '[{"section":"Holding","description":"Separate educational facilities are inherently unequal — violates Equal Protection"},{"section":"Overruling","description":"Plessy v. Ferguson separate but equal doctrine overruled in public education"},{"section":"Education","description":"Education is perhaps the most important function of state and local governments"},{"section":"Impact","description":"Foundational civil rights decision — catalyst for Civil Rights Movement and desegregation"}]', '["equal_protection_claim","civil_rights_complaint","desegregation_order","14th_amendment_brief","discrimination_claim"]', '["victim-rights-marsys-law-audit"]', 'US Supreme Court', 1, 1, datetime('now'), datetime('now'));

-- Shelley v. Kraemer — State Action Doctrine
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_042', 'ADVOCIS', 'CASE_LAW', 'US', 'Shelley v. Kraemer, 334 U.S. 1 (1948)', 'Shelley v. Kraemer', 'Judicial Enforcement of Restrictive Covenants as State Action — Equal Protection', 'Racially restrictive covenants standing alone do not violate the Fourteenth Amendment because they are private agreements. However, judicial enforcement of racially restrictive covenants constitutes state action violating the Equal Protection Clause. When a state court enforces a discriminatory private agreement, the state has made the discrimination its own act. State action is present whenever the state has become significantly involved in private discrimination.', '["Private racially restrictive covenants alone are not state action","Judicial enforcement of discriminatory covenants IS state action","State court enforcement makes private discrimination the act of the state","14th Amendment Equal Protection applies to state judicial action","State involvement transforms private discrimination into constitutional violation","State cannot enforce private agreements that achieve what state itself cannot constitutionally do","Expands state action doctrine to judicial enforcement","Right to acquire and use property without discrimination"]', '[{"section":"Holding","description":"Judicial enforcement of racially restrictive covenants is state action violating Equal Protection"},{"section":"State Action","description":"Court enforcement transforms private discrimination into state discrimination"},{"section":"Private Covenants","description":"Standing alone they are private — but enforcement converts to state action"},{"section":"Impact","description":"Expanded state action doctrine — courts enforcing discrimination become the discriminator"}]', '["state_action_claim","equal_protection_motion","housing_discrimination_complaint","restrictive_covenant_challenge","14th_amendment_brief"]', '["victim-rights-marsys-law-audit"]', 'US Supreme Court / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- New York Times Co. v. Sullivan — Actual Malice / First Amendment
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_043', 'ADVOCIS', 'CASE_LAW', 'US', 'New York Times Co. v. Sullivan, 376 U.S. 254 (1964)', 'NYT v. Sullivan', 'Actual Malice Standard for Defamation of Public Officials — First Amendment', 'First Amendment requires public official suing for defamation to prove statement was made with actual malice — knowledge that statement was false or reckless disregard of whether it was false or not. Protects uninhibited, robust, and wide-open debate on public issues. Erroneous statements are inevitable in free debate and must be protected to give breathing space to freedoms of expression. Actual malice must be proven by clear and convincing evidence. Extended to public figures by Curtis Publishing v. Butts.', '["Public official must prove actual malice to recover for defamation","Actual malice: knowledge of falsity or reckless disregard of truth","Reckless disregard: subjective awareness of probable falsity","Not mere negligence — must be subjective fault","Clear and convincing evidence standard — not preponderance","First Amendment protects robust debate on public issues","Erroneous statement inevitable in free debate — must be protected","Breathing space needed for freedoms of expression to survive"]', '[{"section":"Holding","description":"Public officials must prove actual malice — knowledge of falsity or reckless disregard — for defamation"},{"section":"Actual Malice","description":"Subjective standard — defendant knew statement was false or had high awareness of probable falsity"},{"section":"Proof Standard","description":"Clear and convincing evidence, not mere preponderance"},{"section":"Impact","description":"Constitutional protection for speech about public officials — extended to public figures"}]', '["defamation_defense","first_amendment_brief","actual_malice_analysis","anti_SLAPP_motion","public_official_defamation_response"]', '["victim-rights-marsys-law-audit"]', 'US Supreme Court / Federal and State Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- EMPLOYMENT DISCRIMINATION (REGULIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Bostock v. Clayton County — Title VII Sexual Orientation/Transgender
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_044', 'REGULIS', 'CASE_LAW', 'US', 'Bostock v. Clayton County, 590 U.S. 644 (2020)', 'Bostock v. Clayton County', 'Title VII Prohibits Employment Discrimination Based on Sexual Orientation and Transgender Status', 'Title VII''s prohibition on discrimination "because of sex" necessarily encompasses discrimination based on sexual orientation and transgender status. An employer who fires an individual merely for being gay or transgender violates Title VII because it is impossible to discriminate against a person for being gay or transgender without discriminating against that individual based on sex. Textualist analysis: discrimination on these bases necessarily involves consideration of sex — "but for" the employee''s sex, the employer would not have acted differently.', '["Title VII because of sex includes sexual orientation and transgender status","Impossible to discriminate on sexual orientation without considering sex","But-for causation: sex need not be sole or primary cause","Textualist interpretation of statutory language","Employer fires male employee for being attracted to men — but would not fire female employee for same — sex is but-for cause","Applies to all Title VII protections: hiring, firing, terms and conditions","No religious employer exemption addressed in this case","RFRA and First Amendment defenses left open for future cases"]', '[{"section":"Holding","description":"Title VII prohibits employment discrimination based on sexual orientation and transgender status"},{"section":"Textualism","description":"Because of sex necessarily encompasses orientation and gender identity — impossible to separate"},{"section":"But-For Causation","description":"Sex need not be sole cause — if sex was one but-for cause, Title VII is violated"},{"section":"Impact","description":"Extended Title VII protections to LGBTQ+ employees nationwide"}]', '["title_vii_complaint","eeoc_charge","employment_discrimination_claim","wrongful_termination_complaint","lgbtq_discrimination_claim"]', '["california-labor-employment-audit"]', 'EEOC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Burlington Northern v. White — Retaliation Standard
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_045', 'REGULIS', 'CASE_LAW', 'US', 'Burlington Northern & Santa Fe Railway Co. v. White, 548 U.S. 53 (2006)', 'Burlington Northern v. White', 'Title VII Retaliation — Materially Adverse Action Standard Broader Than Discrimination', 'Title VII anti-retaliation provision is not limited to workplace-related or employment-related retaliatory acts. A plaintiff must show employer''s action might have dissuaded a reasonable worker from making or supporting a charge of discrimination. Retaliation standard is broader than substantive discrimination standard — covers any materially adverse action, not just ultimate employment decisions. Context matters — reassignment of duties, schedule changes, or suspensions without pay can constitute actionable retaliation depending on circumstances.', '["Retaliation standard broader than substantive discrimination standard","Materially adverse: would dissuade reasonable worker from making charge","Not limited to employment actions — covers conduct outside workplace","No need to show ultimate employment decision (hiring, firing, demotion)","Context matters — same action may be material in one context but not another","Reassignment, schedule changes, suspension without pay can be retaliatory","Reasonable person standard — objective but context-dependent","Anti-retaliation provision has distinct purpose from anti-discrimination provision"]', '[{"section":"Holding","description":"Retaliation encompasses any materially adverse action that might dissuade reasonable worker from complaining"},{"section":"Broader Standard","description":"Retaliation provision covers more than just workplace employment actions"},{"section":"Context Dependent","description":"Whether action is materially adverse depends on circumstances facing particular employee"},{"section":"Impact","description":"Expanded retaliation claims beyond ultimate employment decisions — significant employee protection"}]', '["retaliation_complaint","eeoc_retaliation_charge","title_vii_retaliation_claim","adverse_action_documentation","whistleblower_retaliation_claim"]', '["california-labor-employment-audit"]', 'EEOC / Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CALIFORNIA-SPECIFIC LABOR LAW (REGULIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Brinker Restaurant Corp. v. Superior Court — Meal Periods
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_046', 'REGULIS', 'CASE_LAW', 'CA', 'Brinker Restaurant Corp. v. Superior Court, 53 Cal.4th 1004 (2012)', 'Brinker v. Superior Court', 'Employer Duty to Provide Meal Period Opportunity — Timing Requirements', 'Employer must provide meal period opportunity but need not ensure employees do no work during the period. First meal period must be provided no later than end of fifth hour of work. Second meal period required no later than end of tenth hour. Employer satisfies obligation by relieving employee of all duty, relinquishing control, permitting reasonable opportunity to take uninterrupted 30-minute break, and not impeding or discouraging employee from doing so. No rolling five-hour requirement for second meal period.', '["Employer must provide meal period — not police actual consumption","First meal period: no later than end of 5th hour of work","Second meal period: no later than end of 10th hour of work","Employer must relieve employee of all duty for meal period","Must relinquish control over employee activities during break","Must permit reasonable opportunity for uninterrupted 30-minute break","Must not impede or discourage employee from taking break","No rolling 5-hour requirement — measured from start of shift for first, from end of first meal for second","Premium pay owed for non-compliant meal periods under Labor Code § 226.7"]', '[{"section":"Holding","description":"Employer must provide meal period opportunity — not ensure no work is performed"},{"section":"Timing - First Meal","description":"No later than end of 5th hour of work"},{"section":"Timing - Second Meal","description":"No later than end of 10th hour of work"},{"section":"Employer Obligation","description":"Relieve of duty, relinquish control, permit opportunity, not impede or discourage"},{"section":"Impact","description":"Definitive CA Supreme Court guidance on meal period obligations — resolved class cert and timing disputes"}]', '["meal_period_audit","wage_hour_complaint","class_action_certification","labor_code_violation_claim","meal_period_waiver","premium_pay_calculation"]', '["california-labor-employment-audit"]', 'CA DLSE / CA Superior Courts', 1, 1, datetime('now'), datetime('now'));

-- Dynamex Operations West v. Superior Court — ABC Test
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_047', 'REGULIS', 'CASE_LAW', 'CA', 'Dynamex Operations West v. Superior Court, 4 Cal.5th 903 (2018)', 'Dynamex', 'ABC Test for Independent Contractor Classification — Adopted by AB 5', 'Adopted ABC test for determining worker classification under California wage orders. Worker is presumed to be employee unless hiring entity demonstrates all three factors: (A) worker is free from control and direction in performance of work, both under contract and in fact; (B) worker performs work outside usual course of hiring entity''s business; (C) worker is customarily engaged in independently established trade, occupation, or business of same nature. Replaced multifactor Borello test for wage order claims. Codified by AB 5 (Lab. Code § 2775).', '["ABC test presumes worker is employee — burden on hiring entity to prove otherwise","A prong: free from control and direction — contract AND in fact","B prong: work outside usual course of hiring entity''s business","C prong: customarily engaged in independently established trade or business","All three prongs must be satisfied or worker is employee","Replaced Borello multifactor test for wage order claims","Codified in Labor Code § 2775 et seq. by AB 5 (2019)","Hiring entity bears burden of proof on all three prongs"]', '[{"section":"Holding","description":"ABC test adopted for worker classification — presumption of employment"},{"section":"A Prong","description":"Free from control and direction in contract and fact"},{"section":"B Prong","description":"Work outside usual course of hiring entity business"},{"section":"C Prong","description":"Customarily engaged in independently established trade or business"},{"section":"Impact","description":"Dramatically changed CA independent contractor law — codified by AB 5 — B prong most difficult to satisfy"}]', '["worker_classification_audit","independent_contractor_agreement","ab5_compliance_review","wage_order_claim","misclassification_complaint","edd_audit_response"]', '["california-labor-employment-audit"]', 'CA DLSE / EDD / CA Courts', 1, 1, datetime('now'), datetime('now'));

-- Iskanian v. CLS Transportation — PAGA Waivers
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_048', 'REGULIS', 'CASE_LAW', 'CA', 'Iskanian v. CLS Transportation, 59 Cal.4th 348 (2014)', 'Iskanian v. CLS Transportation', 'PAGA Claims Not Waivable by Arbitration Agreements — Representative Actions Survive', 'PAGA representative action waivers in pre-dispute arbitration agreements are unenforceable as contrary to California public policy. PAGA claims are law enforcement actions brought on behalf of the state — the employee acts as proxy or agent of the state. Because PAGA claim belongs to the state, employee cannot waive the state''s claim through private agreement. FAA does not preempt California rule invalidating PAGA waivers because PAGA is a qui tam-like action, not a dispute between private parties. Note: partially limited by Viking River Cruises v. Moriana (2022) regarding individual PAGA claims.', '["PAGA representative action waivers unenforceable","PAGA is law enforcement action — employee acts as state''s proxy","Employee cannot waive state''s claim through private arbitration agreement","FAA does not preempt — PAGA is not private dispute between parties","PAGA claim belongs to state of California — not the individual employee","Public policy prevents private waiver of state enforcement mechanism","Qui tam-like nature of PAGA distinguishes from private arbitration","Viking River Cruises (2022) later held individual PAGA claims may be compelled to arbitration","Standing PAGA representative claims survive even after Viking River"]', '[{"section":"Holding","description":"PAGA waivers in arbitration agreements are unenforceable — employee acts as state proxy"},{"section":"State Action","description":"PAGA is qui tam-like — employee enforces state labor law as state agent"},{"section":"FAA Preemption","description":"FAA does not preempt because PAGA is not private dispute"},{"section":"Impact","description":"Preserved PAGA as enforcement tool — partially limited by Viking River Cruises v. Moriana (2022) on individual claims"}]', '["paga_complaint","arbitration_agreement_review","paga_waiver_challenge","class_action_arbitration_motion","representative_paga_action","labor_code_violation_paga"]', '["california-labor-employment-audit"]', 'CA LWDA / CA Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FINANCIAL / STANDING (FISCARA)
-- ═══════════════════════════════════════════════════════════════════════════

-- Spokeo v. Robins — Article III Standing / Concrete Injury
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_049', 'FISCARA', 'CASE_LAW', 'US', 'Spokeo, Inc. v. Robins, 578 U.S. 330 (2016)', 'Spokeo v. Robins', 'Article III Standing — Concrete Injury Required Beyond Bare Statutory Violation', 'Article III standing requires plaintiff to show injury in fact that is (1) concrete, (2) particularized, and (3) actual or imminent. Concreteness is distinct from particularization. A bare procedural violation of a statute, divorced from any concrete harm, does not satisfy Article III injury-in-fact requirement. However, intangible injuries can be concrete — Congress''s judgment in creating statutory right is instructive. Risk of real harm can satisfy concreteness. Not every statutory violation automatically creates standing.', '["Article III standing requires concrete and particularized injury in fact","Concrete and particularized are distinct requirements","Bare procedural statutory violation alone may not confer standing","Intangible injuries can be concrete — not limited to tangible harm","Congress''s judgment in creating statutory right is relevant but not dispositive","Risk of real harm can satisfy concreteness requirement","Historical practice of recognizing injury type informs analysis","Dissemination of false information may constitute concrete harm"]', '[{"section":"Holding","description":"Bare statutory violation without concrete harm does not satisfy Article III standing"},{"section":"Concreteness","description":"Injury must be real, not abstract — distinct from particularization requirement"},{"section":"Intangible Injuries","description":"Can be concrete if historically recognized or Congress elevated to legally cognizable"},{"section":"Impact","description":"Gateway for standing challenges in statutory violation cases — refined by TransUnion v. Ramirez"}]', '["standing_motion","motion_to_dismiss_standing","article_iii_standing_brief","statutory_violation_complaint","concrete_injury_analysis"]', '["banking-financial-document-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- TransUnion LLC v. Ramirez — Standing Refined
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_050', 'FISCARA', 'CASE_LAW', 'US', 'TransUnion LLC v. Ramirez, 594 U.S. 413 (2021)', 'TransUnion v. Ramirez', 'Refined Spokeo — No Standing Without Concrete Harm From Statutory Violation', 'Refined Spokeo''s concrete injury requirement. Only 1,853 of 8,185 class members had standing because only their inaccurate credit files were disseminated to third parties. Remaining class members with inaccurate internal files but no dissemination suffered no concrete harm. Central question: whether plaintiffs have suffered harm with close relationship to harm traditionally recognized as providing basis for lawsuit. No concrete harm = no Article III standing, regardless of statutory violation. Congress cannot manufacture standing by granting right to sue without real injury.', '["Concrete harm required — internal statutory violation without dissemination insufficient","Close relationship to traditionally recognized harms required","Only class members with third-party dissemination had standing","Internal inaccuracy alone without external publication not concrete harm","Congress cannot manufacture Article III standing by creating right to sue","Reputational harm requires publication to third party — parallel to defamation","Risk of future harm must be sufficiently imminent — not speculative","Article III standing assessed member by member in class actions"]', '[{"section":"Holding","description":"Class members without third-party dissemination of inaccurate files lacked Article III standing"},{"section":"Concrete Harm Test","description":"Close relationship to harm traditionally recognized as basis for lawsuit"},{"section":"Congressional Power","description":"Congress cannot confer Article III standing by statute alone — injury must be concrete"},{"section":"Class Actions","description":"Standing must be assessed member by member"},{"section":"Impact","description":"Major limitation on statutory damages class actions — particularly FCRA, TCPA, privacy statutes"}]', '["standing_challenge","class_certification_opposition","article_iii_standing_motion","fcra_standing_analysis","concrete_harm_evidence","class_member_standing_analysis"]', '["banking-financial-document-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVACY / TECHNOLOGY (PRIVAXIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Rosenbach v. Six Flags — BIPA Standing
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_051', 'PRIVAXIS', 'CASE_LAW', 'IL', 'Rosenbach v. Six Flags Entertainment Corp., 2019 IL 123186 (Ill. 2019)', 'Rosenbach v. Six Flags', 'BIPA Standing — No Actual Injury Required for Statutory Violation', 'Under Illinois Biometric Information Privacy Act (BIPA), a person "aggrieved" by a violation need not allege actual injury or adverse effect beyond the statutory violation itself. The violation of the statutory right is itself sufficient injury. BIPA''s protections are preventive and prophylactic — actual injury requirement would undermine BIPA''s purpose. When private entity collects biometric data without informed consent, the harm to individual''s right to privacy is real and significant. Contrasts with federal standing under Spokeo/TransUnion.', '["BIPA violation itself confers standing — no actual injury required","Aggrieved person includes anyone whose rights under BIPA are violated","BIPA protections are preventive and prophylactic in nature","Actual injury requirement would undermine legislative purpose","Collection without consent is itself real and significant harm","Private right of action explicitly created by BIPA § 20","Statutory damages: $1,000 per negligent violation, $5,000 per intentional/reckless violation","Illinois state court standing — distinct from federal Article III standing under Spokeo"]', '[{"section":"Holding","description":"BIPA statutory violation alone confers standing — no actual injury beyond violation required"},{"section":"Aggrieved Person","description":"Broadly defined — anyone whose statutory rights under BIPA are violated"},{"section":"Prophylactic Purpose","description":"BIPA designed to prevent harm before it occurs — actual injury requirement would defeat purpose"},{"section":"Impact","description":"Foundation for massive BIPA class action litigation — billions in potential statutory damages"}]', '["bipa_complaint","biometric_privacy_claim","class_action_bipa","consent_compliance_audit","biometric_data_collection_policy","statutory_damages_calculation"]', '["privacy-data-protection-audit"]', 'Illinois State Courts', 1, 1, datetime('now'), datetime('now'));

-- Van Buren v. United States — CFAA "Exceeds Authorized Access"
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_052', 'PRIVAXIS', 'CASE_LAW', 'US', 'Van Buren v. United States, 593 U.S. 374 (2021)', 'Van Buren v. United States', 'CFAA — "Exceeds Authorized Access" Means Accessing Off-Limits Areas, Not Misusing Authorized Access', 'Computer Fraud and Abuse Act''s "exceeds authorized access" provision covers those who obtain information from particular areas of the computer — such as files, folders, or databases — to which their computer access does not extend. It does not cover those who access information for improper purposes but from areas they are otherwise authorized to access. A police officer who ran license plate database search for personal reasons had authorized access and did not violate CFAA even though the search violated department policy. Gates-up-or-down model adopted.', '["Exceeds authorized access = accessing areas of computer that are off-limits","Does not mean misusing access to areas where access is authorized","Gates-up-or-down model: either you can access the area or you cannot","Policy-based access restrictions do not create CFAA liability","Officer running authorized database for personal purpose did not exceed access","Rejects broad interpretation that would criminalize commonplace computer activity","Narrow reading avoids making felons of millions who violate computer use policies","CFAA § 1030(e)(6): exceeds authorized access means accessing computer with authorization and using access to obtain information not entitled to obtain"]', '[{"section":"Holding","description":"Exceeds authorized access means accessing off-limits computer areas, not misusing authorized access"},{"section":"Gates Model","description":"Access is binary — either user can access the area or cannot — not dependent on purpose"},{"section":"Policy Violations","description":"Violating employer computer use policy does not create CFAA liability"},{"section":"Impact","description":"Narrowed CFAA scope — protects against overcriminalization of routine computer use policy violations"}]', '["cfaa_defense","computer_fraud_claim","authorized_access_analysis","data_breach_complaint","employee_computer_use_policy","cfaa_civil_claim"]', '["privacy-data-protection-audit"]', 'Federal Courts / DOJ', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- HOUSING DISCRIMINATION (REGULIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- Fair Housing Council v. Roommates.com — CDA § 230 / FHA Online
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_053', 'REGULIS', 'CASE_LAW', 'US', 'Fair Housing Council v. Roommates.com, LLC, 521 F.3d 1157 (9th Cir. 2008)', 'Roommates.com', 'CDA § 230 Does Not Immunize Platforms Creating Discriminatory Content — FHA Applies Online', 'Communications Decency Act § 230 does not immunize online platforms that materially contribute to the alleged illegality of content. Roommates.com was not a passive conduit — it required users to disclose protected characteristics (sex, sexual orientation, family status) and used that information to channel listings. A website that creates or develops discriminatory content is an information content provider, not merely an interactive computer service immune under § 230. Fair Housing Act applies to online housing platforms. Distinction between neutral tools and those designed to facilitate discrimination.', '["CDA § 230 immunity does not protect platforms that create or develop illegal content","Material contribution to illegality removes § 230 protection","Requiring disclosure of protected characteristics is content creation, not neutral hosting","FHA prohibitions apply equally to online housing platforms","Platform that designs tools facilitating discrimination is information content provider","Neutral tools available equally to all are protected — discriminatory tools are not","§ 230 protects good-faith screening, not participation in illegality","En banc Ninth Circuit decision — influential nationwide"]', '[{"section":"Holding","description":"§ 230 does not immunize platforms that create or develop discriminatory content — FHA applies online"},{"section":"Content Creation","description":"Requiring protected characteristics and channeling listings = content creation, not passive hosting"},{"section":"Material Contribution","description":"Platform materially contributing to illegality loses § 230 immunity"},{"section":"Impact","description":"Leading authority on § 230 limits in housing discrimination — FHA enforcement extends to digital platforms"}]', '["fha_complaint","housing_discrimination_claim","section_230_defense","online_platform_compliance","content_moderation_policy","digital_housing_audit"]', '["california-housing-tenant-audit"]', 'HUD / Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FAMILY LAW (ADVOCIS)
-- ═══════════════════════════════════════════════════════════════════════════

-- In re Marriage of Burgess — Move-Away / Custodial Parent
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_054', 'ADVOCIS', 'CASE_LAW', 'CA', 'In re Marriage of Burgess, 13 Cal.4th 25 (1996)', 'Marriage of Burgess', 'Move-Away Rights — Custodial Parent Presumptive Right to Relocate With Child', 'Custodial parent has a presumptive right to change the residence of the child. Noncustodial parent bears the burden of showing that the proposed move would cause detriment to the child, warranting a change in custody. Court must consider the best interests of the child in light of all relevant factors. No presumption against relocation. The custodial parent''s reasons for relocating are not determinative but are relevant. Court must consider the stability and continuity of existing custody arrangement. Foundational move-away case — later supplemented by In re Marriage of LaMusga (2004) which addressed changed-circumstance threshold.', '["Custodial parent has presumptive right to change child''s residence","Noncustodial parent bears burden to show detriment warranting custody change","Best interests of child governs — all relevant factors considered","No presumption against relocation — burden is on objecting parent","Custodial parent''s reasons relevant but not determinative","Stability and continuity of existing arrangement considered","Initial custody order: best interests standard applies","Modification: changed circumstances threshold before best interests (LaMusga supplement)","Temporary restraining orders cannot prevent relocation without proper showing"]', '[{"section":"Holding","description":"Custodial parent has presumptive right to relocate — noncustodial must show detriment"},{"section":"Burden","description":"Noncustodial parent bears burden of showing move would cause detriment to child"},{"section":"Best Interests","description":"All relevant factors considered including stability, continuity, and reasons for move"},{"section":"Impact","description":"Foundational CA move-away case — supplemented by LaMusga (2004) on changed-circumstance threshold for modification"}]', '["move_away_motion","custody_modification_request","relocation_opposition","best_interests_analysis","change_of_circumstances_motion","custody_evaluation_report"]', '["family-law-custody-audit"]', 'CA Family Courts', 1, 1, datetime('now'), datetime('now'));
