-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 9
-- ═══════════════════════════════════════════════════════════════════════════
-- UCMJ individual articles (ETHICARA), Labor Code expansion (REGULIS),
-- Banking sub-sections (FISCARA).
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- ETHICARA — UCMJ Individual Articles
-- ═══════════════════════════════════════════════════════════════════════════

-- Art. 15 — Non-Judicial Punishment
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_050', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 815 (UCMJ Art. 15)', 'Art. 15', 'Non-Judicial Punishment Procedures', 'Commanding officers may impose non-judicial punishment for minor offenses without a court-martial. Service member has right to refuse NJP and demand trial by court-martial (except aboard a vessel).', '["Commander determines offense is minor","Service member must be informed of rights","Right to demand trial by court-martial (except aboard vessel)","Right to consult with counsel before deciding","Right to present matters in defense/mitigation","Punishments limited by grade of imposing commander","Appeal to next superior authority within 5 days"]', '[{"section":"815(a)","description":"Authority to impose NJP"},{"section":"815(b)","description":"Punishments authorized by grade"},{"section":"815(c)","description":"Right to demand court-martial in lieu of NJP"},{"section":"815(e)","description":"Appeal of NJP"}]', '["NJP_record","page_11_entry","Article_15_proceedings","punishment_log","appeal_submission"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 31 — Self-Incrimination Rights (Military Miranda)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_051', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 831 (UCMJ Art. 31)', 'Art. 31', 'Self-Incrimination Rights — Military Miranda', 'Military equivalent of Miranda rights requiring warnings before interrogation. Broader than civilian Miranda — applies to any person subject to the UCMJ who suspects an offense has been committed, not only law enforcement.', '["Must inform suspect of nature of accusation","Must advise right to remain silent","Must warn that statements may be used as evidence","Applies to any person subject to UCMJ conducting questioning","Broader than civilian Miranda — not limited to custodial interrogation","Involuntary statements are inadmissible","Applies to both criminal investigators and commanders"]', '[{"section":"831(a)","description":"No compulsory self-incrimination"},{"section":"831(b)","description":"Required warnings before interrogation"},{"section":"831(d)","description":"Inadmissibility of involuntary statements"}]', '["interrogation_record","NCIS_report","CID_report","confession","sworn_statement","rights_waiver"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 32 — Preliminary Hearing Before Court-Martial
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_052', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 832 (UCMJ Art. 32)', 'Art. 32', 'Preliminary Hearing Before General Court-Martial', 'Requires a preliminary hearing before charges may be referred to a general court-martial. The hearing officer determines whether probable cause exists and recommends disposition.', '["Preliminary hearing required before general court-martial referral","Hearing officer must be a judge advocate (O-4 or above)","Accused has right to counsel at hearing","Accused may cross-examine witnesses","Hearing officer issues written report with recommendations","Convening authority not bound by recommendation","Limited to probable cause and jurisdiction determination"]', '[{"section":"832(a)","description":"Requirement for preliminary hearing"},{"section":"832(b)","description":"Hearing officer qualifications"},{"section":"832(c)","description":"Rights of the accused at hearing"},{"section":"832(d)","description":"Report and recommendations"}]', '["Article_32_hearing_report","charge_sheet","DD_Form_458","preliminary_hearing_transcript","counsel_request"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 120 — Sexual Assault Offenses
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_053', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 920 (UCMJ Art. 120)', 'Art. 120', 'Sexual Assault Offenses', 'Comprehensive military sexual assault statute covering rape, sexual assault, aggravated sexual contact, and abusive sexual contact. Mandatory minimum sentences and special victim counsel provisions.', '["Rape — sexual act by force or threat","Sexual assault — sexual act without consent","Aggravated sexual contact — sexual contact by force or threat","Abusive sexual contact — sexual contact without consent","Incapacity to consent (intoxication, sleep, unconsciousness)","Mandatory minimum sentences apply","Special Victims Counsel assigned to victim"]', '[{"section":"920(a)","description":"Rape — elements and penalties"},{"section":"920(b)","description":"Sexual assault — elements and penalties"},{"section":"920(c)","description":"Aggravated sexual contact"},{"section":"920(d)","description":"Abusive sexual contact"}]', '["SARC_report","NCIS_investigation","victim_statement","forensic_exam","restricted_report","unrestricted_report","court_martial_record"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 134 — General Article
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_054', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 934 (UCMJ Art. 134)', 'Art. 134', 'General Article — Conduct Prejudicial to Good Order and Discipline', 'Catch-all provision covering offenses not specifically enumerated in the UCMJ. Three clauses: prejudicial to good order and discipline, service-discrediting, and crimes and offenses not capital.', '["Clause 1: Conduct prejudicial to good order and discipline","Clause 2: Conduct of a nature to bring discredit upon the armed forces","Clause 3: Crimes and offenses not capital (federal assimilative crimes)","Must be conduct beyond mere technical violation","Includes enumerated offenses in MCM Part IV","Examples: adultery, fraternization, drunk and disorderly, communicating a threat"]', '[{"section":"934 Clause 1","description":"Prejudicial to good order and discipline"},{"section":"934 Clause 2","description":"Service-discrediting conduct"},{"section":"934 Clause 3","description":"Noncapital crimes assimilated from federal law"}]', '["charge_sheet","NJP_record","court_martial_record","command_investigation","counseling_record"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 86 — Absence Without Leave
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_055', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 886 (UCMJ Art. 86)', 'Art. 86', 'Absence Without Leave (AWOL/UA)', 'Prohibits absence without authority from unit, organization, or place of duty. Includes failure to go to appointed place of duty and going from appointed place of duty.', '["Failure to go to appointed place of duty at prescribed time","Going from appointed place of duty","Absence from unit/organization/place of duty without authority","Knowledge of appointed time/place not required if duty was reasonable","Aggravated by duration (over 30 days, terminated by apprehension)","Intent to avoid hazardous duty or shirk important service is separate offense"]', '[{"section":"886(1)","description":"Failure to go to appointed place of duty"},{"section":"886(2)","description":"Going from appointed place of duty"},{"section":"886(3)","description":"Absence without leave"}]', '["UA_muster_report","charge_sheet","page_11_entry","apprehension_record","NJP_record","court_martial_record"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 91 — Insubordinate Conduct Toward NCO
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_056', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 891 (UCMJ Art. 91)', 'Art. 91', 'Insubordinate Conduct Toward Warrant Officer, NCO, or Petty Officer', 'Prohibits striking, disobeying, or using contemptuous or disrespectful language toward a warrant officer, noncommissioned officer, or petty officer while that person is in the execution of their office.', '["Striking or assaulting warrant officer/NCO/PO","Willfully disobeying lawful order of warrant officer/NCO/PO","Treating with contempt or being disrespectful in language or deportment","Victim must be in execution of office","Accused must know victim is WO/NCO/PO","Order must be lawful and relate to military duty"]', '[{"section":"891(1)","description":"Striking or assaulting WO/NCO/PO"},{"section":"891(2)","description":"Willfully disobeying lawful order"},{"section":"891(3)","description":"Contemptuous or disrespectful language/deportment"}]', '["charge_sheet","incident_report","witness_statement","NJP_record","court_martial_record","counseling_record"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 92 — Failure to Obey Order or Regulation
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_057', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 892 (UCMJ Art. 92)', 'Art. 92', 'Failure to Obey Order or Regulation', 'Covers violation of general orders/regulations, failure to obey lawful orders, and dereliction of duty. One of the most commonly charged UCMJ articles.', '["Violation of general order or regulation","Failure to obey other lawful order","Dereliction in performance of duties (negligent or willful)","General order must be lawful and published/known","Other lawful order must be specific to accused","Dereliction requires knowledge of duties and failure to perform"]', '[{"section":"892(1)","description":"Violation of or failure to obey lawful general order or regulation"},{"section":"892(2)","description":"Failure to obey other lawful order"},{"section":"892(3)","description":"Dereliction of duty"}]', '["charge_sheet","general_order","SOP","NJP_record","counseling_record","court_martial_record","fitness_report"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));

-- Art. 128 — Assault
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_058', 'ETHICARA', 'MILITARY_STANDARD', 'US', '10 USC § 928 (UCMJ Art. 128)', 'Art. 128', 'Assault', 'Military assault statute covering simple assault, assault consummated by battery, aggravated assault (with dangerous weapon, means/force likely to produce death or grievous bodily harm), and assault on a child.', '["Simple assault — offer or attempt to do bodily harm with apparent present ability","Assault consummated by battery — unlawful force or violence applied","Aggravated assault with dangerous weapon","Aggravated assault with means likely to produce death or grievous bodily harm","Assault on child under 16","Specific intent not required for battery"]', '[{"section":"928(a)","description":"Simple assault"},{"section":"928(b)","description":"Assault consummated by a battery"},{"section":"928(c)","description":"Aggravated assault with dangerous weapon or means likely to cause death/GBH"}]', '["charge_sheet","incident_report","medical_record","witness_statement","NJP_record","court_martial_record","PMO_report"]', '["usmc-military-standards-audit"]', 'JAGC / Military Courts', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Labor Code Expansion
-- ═══════════════════════════════════════════════════════════════════════════

-- LC § 201 — Final Wages on Discharge
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_080', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 201', 'LC § 201', 'Final Wages on Discharge — Immediately Due', 'When an employer discharges an employee, all wages earned and unpaid at the time of discharge are immediately due and payable at the place of discharge.', '["All earned wages due immediately upon discharge","Payment at place of discharge","Applies to all forms of compensation earned","No grace period — immediately means immediately","Includes commissions if determinable","Employer cannot condition payment on return of property"]', '[{"section":"201(a)","description":"Immediate payment of wages upon discharge"},{"section":"201(b)","description":"Seasonal employees in specified industries — 72 hours"}]', '["final_paycheck","termination_record","wage_statement","discharge_notice"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- LC § 202 — Final Wages on Quit
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_081', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 202', 'LC § 202', 'Final Wages on Quit — Within 72 Hours', 'When an employee quits without giving 72 hours prior notice, wages are due within 72 hours. If 72 hours notice is given, wages are due at the time of quitting.', '["Wages due within 72 hours of quitting without notice","Wages due immediately if 72 hours notice given","Payment by mail permitted if employee requests","Singling out does not excuse late payment","Final wages must include all earned compensation"]', '[{"section":"202(a)","description":"72-hour payment window for voluntary quit without notice"},{"section":"202(a)","description":"Immediate payment when 72 hours notice given"}]', '["final_paycheck","resignation_letter","wage_statement","pay_record"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- LC § 203 — Waiting Time Penalties
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_082', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 203', 'LC § 203', 'Waiting Time Penalties — Up to 30 Days Wages', 'If an employer willfully fails to pay final wages on time, the employee''s wages continue as a penalty from the due date at the same rate of pay for up to 30 calendar days.', '["Penalty accrues at daily rate of pay","Maximum 30 calendar days of penalty wages","Willful failure — employer knew wages were due","Good faith dispute is a defense","Penalty calculated on daily rate, not hourly","Each day of non-payment is a separate violation"]', '[{"section":"203(a)","description":"Waiting time penalty — up to 30 days wages"},{"section":"203(b)","description":"Good faith dispute defense"}]', '["wage_claim","DLSE_complaint","penalty_calculation","final_pay_dispute"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- LC § 227.3 — Vacation Pay on Termination
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_083', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 227.3', 'LC § 227.3', 'Vacation Pay on Termination', 'Vested vacation time is treated as wages and must be paid out at the employee''s final rate of pay upon termination. Use-it-or-lose-it policies are prohibited in California.', '["Vested vacation is a form of wages","Must be paid at final rate of pay upon termination","Use-it-or-lose-it policies are illegal","Reasonable cap on accrual is permitted","Applies to termination, resignation, layoff, or death","No forfeiture of earned vacation time"]', '[{"section":"227.3","description":"Vacation wages payable on termination at final rate"}]', '["final_paycheck","vacation_accrual_record","employee_handbook","wage_claim"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- LC § 1102.5 — Whistleblower Protection
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_084', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 1102.5', 'LC § 1102.5', 'Whistleblower Protection', 'Prohibits employer retaliation against employees who report suspected violations of law to government or law enforcement, or who refuse to participate in illegal activity.', '["No retaliation for disclosing violation of law to government agency","No retaliation for disclosing violation to supervisor with authority to investigate","No retaliation for refusing to participate in illegal activity","No retaliation for reporting to person with authority over employee","Rebuttable presumption of retaliation if adverse action within 90 days","Civil penalties and reinstatement available"]', '[{"section":"1102.5(a)","description":"Cannot make rule preventing disclosure of violation"},{"section":"1102.5(b)","description":"Cannot retaliate for disclosure to government or authority"},{"section":"1102.5(c)","description":"Cannot retaliate for refusal to participate in illegal activity"},{"section":"1102.5(f)","description":"Civil penalties up to $10,000 per violation"}]', '["whistleblower_complaint","retaliation_claim","DLSE_complaint","termination_record","internal_report"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner / Attorney General', 1, 1, datetime('now'), datetime('now'));

-- LC §§ 230-230.8 — Time Off Protections
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_085', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code §§ 230-230.8', 'LC §§ 230-230.8', 'Time Off for Jury Duty, Court Appearances, DV/SA/Crime Victims', 'Comprehensive time-off protections for jury duty, court appearances, and victims of domestic violence, sexual assault, stalking, and crime.', '["Cannot discharge or discriminate for jury duty service","Cannot retaliate for court appearance as required by law","Time off for DV/SA/stalking victims to seek medical attention, services, counseling, safety planning","Time off for crime victims to attend judicial proceedings","Reasonable accommodation for DV/SA/stalking victims","Employer must maintain confidentiality of employee status"]', '[{"section":"230(a)","description":"Jury duty protection"},{"section":"230(b)","description":"Court appearance as crime victim protection"},{"section":"230.1","description":"Time off for DV/SA/stalking victims"},{"section":"230.2","description":"Time off for crime victims attending proceedings"},{"section":"230.5","description":"Employer cannot discriminate based on victim status"},{"section":"230.8","description":"Time off for school activities"}]', '["jury_duty_notice","court_subpoena","DV_restraining_order","victim_services_record","accommodation_request"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- LC § 2802 — Employer Reimbursement of Necessary Expenses
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_086', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 2802', 'LC § 2802', 'Employer Reimbursement of Necessary Expenses', 'Employer must indemnify employees for all necessary expenditures and losses incurred in direct consequence of the discharge of duties or employer direction.', '["Must reimburse all necessary expenditures incurred in discharge of duties","Must reimburse losses caused by employer direction","Includes cell phone, internet, mileage, tools, equipment","Applies even if employee does not submit expense report","Cannot require employees to bear business expenses","Interest accrues on unpaid reimbursements"]', '[{"section":"2802(a)","description":"Employer indemnification for necessary expenditures and losses"},{"section":"2802(b)","description":"Definition of necessary expenditures"},{"section":"2802(c)","description":"Applies to losses from employer-required actions"}]', '["expense_report","reimbursement_claim","wage_claim","cell_phone_policy","mileage_log"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- LC § 98.6 — Retaliation for Filing Labor Claim
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_087', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 98.6', 'LC § 98.6', 'Retaliation for Filing Labor Claim or Complaint', 'Prohibits employer retaliation against employees who file or threaten to file labor claims, complaints, or who exercise rights under the Labor Code.', '["Cannot discharge or discriminate for filing wage claim","Cannot retaliate for complaints to Labor Commissioner","Cannot retaliate for exercising any right under Labor Code","Rebuttable presumption of retaliation within 90 days of protected activity","Penalties include reinstatement, back pay, and civil penalty up to $10,000","Labor Commissioner may prosecute action on behalf of employee"]', '[{"section":"98.6(a)","description":"Prohibited retaliation for filing complaints or exercising rights"},{"section":"98.6(b)","description":"Rebuttable presumption of retaliation"},{"section":"98.6(c)","description":"Penalties and remedies"}]', '["DLSE_complaint","wage_claim","retaliation_complaint","termination_record","adverse_action_notice"]', '["california-labor-employment-audit"]', 'California DLSE / Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

-- Cal. Gov. Code §§ 12940-12951 (FEHA Employment)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_088', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 12940-12951 (FEHA)', 'FEHA Employment', 'Fair Employment and Housing Act — Employment Discrimination Provisions', 'California''s primary employment discrimination statute prohibiting discrimination, harassment, and retaliation based on protected characteristics. Applies to employers with 5+ employees (harassment provisions apply to all employers).', '["Discrimination prohibited based on race, color, religion, sex, gender, sexual orientation, marital status, national origin, ancestry, disability, medical condition, age (40+), genetic information, military/veteran status","Harassment prohibited for all employers regardless of size","Employer must take reasonable steps to prevent discrimination and harassment","Reasonable accommodation required for disability and religious beliefs","Interactive process required for disability accommodation","Retaliation prohibited for opposing discrimination or filing complaint"]', '[{"section":"12940(a)","description":"Unlawful employment practices — discrimination"},{"section":"12940(j)","description":"Harassment — applies to all employers"},{"section":"12940(k)","description":"Failure to prevent discrimination/harassment"},{"section":"12940(m)","description":"Failure to accommodate disability"},{"section":"12940(n)","description":"Failure to engage in interactive process"},{"section":"12945.2","description":"CFRA leave provisions"},{"section":"12951","description":"Right to workplace lactation accommodation"}]', '["DFEH_complaint","EEOC_charge","right_to_sue_letter","accommodation_request","interactive_process_record","harassment_complaint","termination_record"]', '["california-labor-employment-audit"]', 'DFEH (now CRD) / Superior Court', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — Banking Sub-Sections
-- ═══════════════════════════════════════════════════════════════════════════

-- 12 CFR Part 1030 (Reg DD) — Truth in Savings
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_030', 'FISCARA', 'FEDERAL_REGULATION', 'US', '12 CFR Part 1030 (Regulation DD)', 'Reg DD', 'Truth in Savings Act — Regulation DD', 'Requires depository institutions to provide uniform disclosures about deposit accounts to enable consumers to make meaningful comparisons. Covers interest rates, fees, and account terms.', '["Disclose APY and interest rate uniformly","Disclose fees and terms before account opening","Provide periodic statements with interest earned and fees charged","Advertising must not be misleading","Balance computation method must be disclosed","Notice required before adverse changes to account terms"]', '[{"section":"1030.3","description":"General disclosure requirements"},{"section":"1030.4","description":"Account disclosures — rates, fees, terms"},{"section":"1030.5","description":"Subsequent disclosures — change in terms notice"},{"section":"1030.6","description":"Periodic statement disclosures"},{"section":"1030.8","description":"Advertising requirements"},{"section":"1030.11","description":"Additional disclosure for overdraft services"}]', '["account_disclosure","deposit_agreement","periodic_statement","fee_schedule","change_in_terms_notice","savings_account_ad"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- 15 USC § 1693g — Consumer Liability for Unauthorized EFTs
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_031', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 1693g', 'EFTA § 909', 'Consumer Liability Limits for Unauthorized Electronic Fund Transfers', 'Establishes tiered consumer liability limits for unauthorized EFTs based on timing of consumer notification. Maximum $50 if reported within 2 business days, $500 within 60 days, unlimited thereafter.', '["$50 maximum liability if reported within 2 business days of learning of loss/theft","$500 maximum liability if reported within 60 days of transmittal of statement","Unlimited liability if not reported within 60 days of statement","Financial institution bears burden of proving consumer liability","Extenuating circumstances may extend reporting deadlines","Institution must prove access device was used and consumer received required disclosures"]', '[{"section":"1693g(a)","description":"Tiered liability limits — $50/$500/unlimited"},{"section":"1693g(b)","description":"Burden of proof on financial institution"},{"section":"1693g(c)","description":"Definition of unauthorized EFT"},{"section":"1693g(d)","description":"Relation to state law"}]', '["unauthorized_transaction_report","EFT_dispute","bank_statement","debit_card_fraud_claim","Reg_E_dispute","provisional_credit_notice"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- Dodd-Frank Act — CFPB Establishment
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_032', 'FISCARA', 'FEDERAL_STATUTE', 'US', 'Dodd-Frank Wall Street Reform Act, 12 USC §§ 5481-5603 (Title X)', 'Dodd-Frank Title X', 'Consumer Financial Protection Act — CFPB Establishment and Authority', 'Title X of Dodd-Frank establishes the Consumer Financial Protection Bureau (CFPB) with authority to regulate consumer financial products and services, enforce federal consumer financial law, and prohibit unfair, deceptive, or abusive acts or practices (UDAAP).', '["CFPB has exclusive rulemaking authority for enumerated consumer laws","Prohibits unfair, deceptive, or abusive acts or practices (UDAAP)","Supervises banks with assets over $10B and nonbank financial companies","Receives and investigates consumer complaints","Can bring enforcement actions with civil money penalties","State attorneys general may enforce CFPB rules","Consumer financial education mandate"]', '[{"section":"5531","description":"Prohibition of UDAAP — unfair, deceptive, or abusive acts/practices"},{"section":"5536","description":"Prohibited acts — violations and enforcement"},{"section":"5552","description":"State attorney general enforcement of CFPB rules"},{"section":"5565","description":"Relief available — restitution, disgorgement, civil penalties"},{"section":"5481","description":"Definitions — covered person, service provider, consumer financial product"}]', '["CFPB_complaint","enforcement_action","consent_order","UDAAP_analysis","supervisory_exam","consumer_complaint"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

-- Cal. Fin. Code §§ 1000-1706 — California Financial Code Banking Operations
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_033', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Fin. Code §§ 1000-1706', 'CFC §§ 1000-1706', 'California Financial Code — Banking Operations', 'California state banking law governing the organization, operation, and regulation of commercial banks, savings banks, and trust companies operating in California.', '["DFPI licensing and supervision of state-chartered banks","Minimum capital requirements for bank formation","Fiduciary duties of bank officers and directors","Restrictions on insider transactions and conflicts of interest","Examination and audit authority of Commissioner","Assessment of fees and penalties for noncompliance","Consumer protection provisions for deposit accounts"]', '[{"section":"1000-1017","description":"General provisions and definitions"},{"section":"1020-1042","description":"Organization and incorporation of banks"},{"section":"1100-1107","description":"Officers, directors, and fiduciary duties"},{"section":"1200-1236","description":"Powers and operations of banks"},{"section":"1500-1563","description":"Savings bank provisions"},{"section":"1600-1706","description":"Trust company operations and regulation"}]', '["bank_charter","DFPI_examination","audit_report","compliance_filing","trust_agreement","bank_operations_manual"]', '["banking-financial-document-audit"]', 'California DFPI (Department of Financial Protection and Innovation)', 0, 1, datetime('now'), datetime('now'));
