-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 7
-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS civil rights expansion: Constitutional amendments, federal civil
-- rights statutes, key civil rights case law, California civil rights.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- CONSTITUTIONAL AMENDMENTS — 13th and 15th
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_040', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. XIII', '13th Amendment', 'Thirteenth Amendment — Abolition of Slavery and Involuntary Servitude', 'Abolishes slavery and involuntary servitude except as punishment for a crime. Grants Congress enforcement power.', '["Slavery and involuntary servitude abolished","Exception only for punishment upon conviction","Congress has power to enforce by appropriate legislation","Basis for 42 USC §§ 1981-1982","Applies to private actors — not limited to state action"]', '[{"section":"Section 1","description":"Neither slavery nor involuntary servitude shall exist within the United States"},{"section":"Section 2","description":"Congress shall have power to enforce this article by appropriate legislation"}]', '["1983_complaint","civil_rights_complaint","federal_complaint","involuntary_servitude_claim"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts / DOJ', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_041', 'ADVOCIS', 'CONSTITUTIONAL', 'US', 'U.S. Const. amend. XV', '15th Amendment', 'Fifteenth Amendment — Voting Rights Regardless of Race', 'Prohibits federal and state governments from denying the right to vote based on race, color, or previous condition of servitude.', '["Right to vote cannot be denied on account of race, color, or previous condition of servitude","Applies to federal and state governments","Congress has enforcement power","Foundation for Voting Rights Act of 1965"]', '[{"section":"Section 1","description":"Right to vote not denied or abridged on account of race, color, or previous condition of servitude"},{"section":"Section 2","description":"Congress shall have power to enforce this article by appropriate legislation"}]', '["voting_rights_complaint","election_challenge","civil_rights_complaint","federal_complaint"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts / DOJ', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FEDERAL CIVIL RIGHTS STATUTES
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_042', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC § 1981', '§ 1981', 'Equal Rights Under the Law — Contracts and Property', 'All persons have the same right to make and enforce contracts, sue, give evidence, and enjoy full and equal benefit of all laws regardless of race.', '["Equal right to make and enforce contracts","Equal right to sue, be parties, give evidence","Full and equal benefit of all laws","Applies to private and public actors","No state action requirement — reaches private discrimination"]', '[{"section":"1981(a)","description":"Equal rights to make and enforce contracts"},{"section":"1981(b)","description":"Make and enforce contracts includes making, performance, modification, and termination"},{"section":"1981(c)","description":"Protection against nongovernmental discrimination"}]', '["employment_discrimination","contract_dispute","civil_rights_complaint","1981_claim"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_043', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC § 1982', '§ 1982', 'Property Rights of Citizens — Race Discrimination', 'All citizens have the same right to inherit, purchase, lease, sell, hold, and convey real and personal property regardless of race.', '["Equal property rights for all citizens","Prohibits racial discrimination in property transactions","Applies to private actors — no state action required","Derived from 13th Amendment enforcement power","Covers real and personal property"]', '[{"section":"§ 1982","description":"All citizens shall have the same right to inherit, purchase, lease, sell, hold, and convey real and personal property"}]', '["property_discrimination","housing_complaint","civil_rights_complaint","1982_claim"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_044', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC § 1988', '§ 1988', 'Attorney Fees in Civil Rights Cases', 'Authorizes courts to award reasonable attorney fees to prevailing parties in civil rights actions under §§ 1981-1983, 1985-1986, and Title VI/IX.', '["Prevailing plaintiff: fees awarded as a matter of course","Prevailing defendant: fees only if action frivolous, unreasonable, or without foundation","Reasonable hourly rate × reasonable hours","Applies to §§ 1981, 1982, 1983, 1985, 1986","Includes expert witness fees in some circuits"]', '[{"section":"1988(b)","description":"Court may allow prevailing party reasonable attorney fee as part of costs"},{"section":"1988(c)","description":"Expert fees in certain actions"}]', '["fee_petition","civil_rights_complaint","1983_complaint","prevailing_party_motion"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_045', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC §§ 2000a-2000a-6 (Title II, Civil Rights Act of 1964)', 'Title II', 'Public Accommodations — Civil Rights Act of 1964', 'Prohibits discrimination based on race, color, religion, or national origin in places of public accommodation affecting interstate commerce.', '["No discrimination in hotels, restaurants, theaters, gas stations","Applies to establishments affecting interstate commerce","Injunctive relief available","Attorney General may intervene","No damages — injunctive relief only"]', '[{"section":"2000a","description":"Prohibition against discrimination in public accommodations"},{"section":"2000a-2","description":"Injunctive relief against discrimination"},{"section":"2000a-3","description":"Civil actions for injunctive relief"},{"section":"2000a-5","description":"Attorney General may institute action"}]', '["public_accommodation_complaint","civil_rights_complaint","discrimination_claim","injunction_petition"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts / DOJ', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_046', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC §§ 2000d-2000d-7 (Title VI, Civil Rights Act of 1964)', 'Title VI', 'Non-Discrimination in Federally Funded Programs', 'Prohibits discrimination on the basis of race, color, or national origin in any program or activity receiving federal financial assistance.', '["No discrimination on basis of race, color, or national origin","Applies to all programs receiving federal funds","Federal agencies must enforce through fund termination or other means","Private right of action for intentional discrimination","Disparate impact actionable under agency regulations"]', '[{"section":"2000d","description":"Prohibition against exclusion from federally assisted programs"},{"section":"2000d-1","description":"Federal authority may terminate funding for noncompliance"},{"section":"2000d-7","description":"Abrogation of state sovereign immunity"}]', '["Title_VI_complaint","federal_funding_challenge","discrimination_claim","agency_complaint"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts / Federal Agencies', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_047', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC §§ 2000e-2000e-17 (Title VII, Civil Rights Act of 1964)', 'Title VII', 'Employment Discrimination — Civil Rights Act of 1964', 'Prohibits employment discrimination based on race, color, religion, sex, or national origin. Covers hiring, firing, compensation, and terms of employment.', '["Applies to employers with 15+ employees","Prohibits disparate treatment and disparate impact","EEOC charge required before suit (exhaustion)","180/300-day filing deadline","Remedies include back pay, reinstatement, compensatory and punitive damages"]', '[{"section":"2000e-2","description":"Unlawful employment practices"},{"section":"2000e-3","description":"Retaliation prohibited"},{"section":"2000e-5","description":"EEOC enforcement procedures and right to sue"},{"section":"2000e-16","description":"Federal employment nondiscrimination"}]', '["EEOC_charge","employment_discrimination","Title_VII_complaint","right_to_sue_letter"]', '["constitutional-and-civil-rights-audit"]', 'EEOC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_048', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '42 USC §§ 12101-12213 (Americans with Disabilities Act)', 'ADA', 'Americans with Disabilities Act — Titles I through III', 'Prohibits discrimination against individuals with disabilities in employment, public services, and public accommodations.', '["Title I: Employment — employers with 15+ employees","Title II: Public services — state and local government","Title III: Public accommodations — private entities","Reasonable accommodation required","Interactive process for accommodations","Undue hardship defense available"]', '[{"section":"12112","description":"Title I — Employment discrimination prohibition"},{"section":"12132","description":"Title II — Public services discrimination prohibition"},{"section":"12182","description":"Title III — Public accommodations discrimination prohibition"},{"section":"12203","description":"Retaliation and coercion prohibited"}]', '["ADA_complaint","EEOC_charge","reasonable_accommodation","accessibility_complaint","DOJ_complaint"]', '["constitutional-and-civil-rights-audit"]', 'EEOC / DOJ / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_049', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '29 USC § 794 (Section 504, Rehabilitation Act of 1973)', 'Section 504', 'Rehabilitation Act — Disability Discrimination in Federally Funded Programs', 'Prohibits disability discrimination by any program or activity receiving federal financial assistance or conducted by a federal agency.', '["No exclusion from federally funded programs solely by reason of disability","Reasonable accommodations required","Applies to all federal agencies and recipients of federal funds","Predates ADA — broader federal coverage","Private right of action available"]', '[{"section":"794(a)","description":"No qualified individual with a disability shall be excluded from any program receiving federal assistance"},{"section":"794(b)","description":"Program or activity defined broadly"},{"section":"794a","description":"Remedies and attorney fees"}]', '["Section_504_complaint","disability_accommodation","federal_funding_complaint","civil_rights_complaint"]', '["constitutional-and-civil-rights-audit"]', 'Federal Agencies / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_050', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '34 USC §§ 12291+ (Violence Against Women Act)', 'VAWA', 'Violence Against Women Act', 'Comprehensive federal legislation addressing domestic violence, dating violence, sexual assault, and stalking with grant programs, protections, and enforcement provisions.', '["Full faith and credit for protection orders across states","Federal interstate domestic violence crimes","Grant programs for victim services","Housing protections for victims","Reauthorized multiple times (1994, 2000, 2005, 2013, 2022)"]', '[{"section":"12291","description":"Definitions and grant conditions"},{"section":"12361","description":"Research and reporting on violence against women"},{"section":"12421","description":"Legal assistance for victims"}]', '["VAWA_petition","protection_order","domestic_violence_complaint","victim_services","immigration_VAWA"]', '["constitutional-and-civil-rights-audit"]', 'DOJ / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_051', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '18 USC §§ 241-242', '§§ 241-242', 'Conspiracy Against Rights / Deprivation of Rights Under Color of Law', 'Federal criminal statutes prohibiting conspiracy to deprive civil rights (§ 241) and deprivation of rights under color of law (§ 242).', '["§ 241: Conspiracy of two or more persons to deprive any person of rights","§ 242: Willful deprivation of rights under color of law","Felony if bodily injury, attempt to kill, or death results","§ 241: Up to 10 years (life if death results)","§ 242: Up to 1 year (10 years if bodily injury; life if death results)"]', '[{"section":"241","description":"Conspiracy against rights — two or more persons conspire to injure, oppress, threaten, or intimidate"},{"section":"242","description":"Deprivation of rights under color of law — willful subjection to different punishments, pains, or penalties by reason of color or race"}]', '["federal_criminal_complaint","civil_rights_referral","DOJ_complaint","police_misconduct","1983_complaint"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'DOJ / FBI / Federal Courts', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- KEY CIVIL RIGHTS CASE LAW
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_052', 'ADVOCIS', 'CASE_LAW', 'US', 'Canton v. Harris (1989) 489 U.S. 378', 'Canton v. Harris', 'Failure to Train as Municipal Policy Under § 1983', 'A municipality may be liable under § 1983 for failure to train its employees where the failure amounts to deliberate indifference to constitutional rights.', '["Failure to train can be basis for Monell liability","Must show deliberate indifference to rights of persons","Need for training must be so obvious — known or obvious risk","Deficiency must be closely related to ultimate injury","Single incident can suffice if predictable and severe"]', '[{"section":"Holding","description":"Failure to train may constitute municipal policy if deliberate indifference shown"},{"section":"Standard","description":"Deliberate indifference — municipality knows training is inadequate and likely to cause violation"}]', '["1983_complaint","Monell_claim","failure_to_train","municipal_liability","police_misconduct"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_053', 'ADVOCIS', 'CASE_LAW', 'US', 'Mathews v. Eldridge (1976) 424 U.S. 319', 'Mathews v. Eldridge', 'Due Process Balancing Test', 'Three-part balancing test for determining what process is due before government deprivation of a protected interest.', '["Factor 1: Private interest affected by official action","Factor 2: Risk of erroneous deprivation through procedures used and probable value of additional safeguards","Factor 3: Government interest including fiscal and administrative burdens","Flexible standard — not one-size-fits-all","Applies to all government benefit and liberty deprivations"]', '[{"section":"Holding","description":"Due process requires balancing private interest, risk of error, and government interest"},{"section":"Three-Factor Test","description":"Balancing test determines what procedural protections are constitutionally required"}]', '["due_process_claim","benefits_appeal","administrative_hearing","1983_complaint","federal_complaint"]', '["constitutional-and-civil-rights-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_054', 'ADVOCIS', 'CASE_LAW', 'US', 'Tennessee v. Garner (1985) 471 U.S. 1', 'Tennessee v. Garner', 'Deadly Force by Police — Fleeing Suspect', 'Deadly force to prevent escape of a fleeing suspect violates the Fourth Amendment unless the officer has probable cause to believe the suspect poses a significant threat of death or serious physical injury.', '["Deadly force is a seizure under the Fourth Amendment","Cannot use deadly force solely to prevent escape","Must have probable cause suspect poses significant threat of death or serious injury","Warning must be given where feasible","Applies to all law enforcement"]', '[{"section":"Holding","description":"Deadly force to prevent escape violates 4th Amendment unless suspect poses significant threat"},{"section":"Standard","description":"Probable cause that suspect poses threat of serious physical harm to officer or others"}]', '["use_of_force_report","officer_involved_shooting","1983_complaint","police_report","excessive_force_complaint"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_055', 'ADVOCIS', 'CASE_LAW', 'US', 'Mapp v. Ohio (1961) 367 U.S. 643', 'Mapp v. Ohio', 'Exclusionary Rule Applies to States', 'Evidence obtained through unreasonable searches and seizures in violation of the Fourth Amendment is inadmissible in state court proceedings through the Fourteenth Amendment.', '["Exclusionary rule applies to states via 14th Amendment","Evidence obtained in violation of 4th Amendment must be excluded","Fruit of the poisonous tree doctrine applies","Good faith exception recognized later in Leon","Applies to both physical evidence and statements"]', '[{"section":"Holding","description":"Exclusionary rule is incorporated against states through 14th Amendment due process"},{"section":"Remedy","description":"All evidence obtained by unconstitutional search and seizure is inadmissible in state court"}]', '["suppression_motion","search_warrant","4th_amendment_challenge","criminal_defense","police_report"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_056', 'ADVOCIS', 'CASE_LAW', 'US', 'Miranda v. Arizona (1966) 384 U.S. 436', 'Miranda v. Arizona', 'Custodial Interrogation Rights', 'Prior to custodial interrogation, a suspect must be informed of the right to remain silent, that statements may be used against them, and the right to an attorney.', '["Warnings required before custodial interrogation","Right to remain silent","Anything said can and will be used in court","Right to an attorney","If cannot afford attorney, one will be appointed","Waiver must be voluntary, knowing, and intelligent"]', '[{"section":"Holding","description":"5th Amendment requires warnings before custodial interrogation"},{"section":"Miranda Warnings","description":"Silence, use against, right to counsel, appointed counsel"},{"section":"Waiver","description":"Must be voluntary, knowing, and intelligent"}]', '["Miranda_warning","custodial_interrogation","suppression_motion","confession","police_report"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'Federal / State Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CALIFORNIA CIVIL RIGHTS
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_057', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 12900-12996 (FEHA Employment Provisions)', 'FEHA Employment', 'Fair Employment and Housing Act — Employment Provisions', 'California law prohibiting employment discrimination based on race, religion, color, national origin, ancestry, physical disability, mental disability, medical condition, genetic information, marital status, sex, gender, sexual orientation, age, or military/veteran status.', '["Applies to employers with 5+ employees (harassment: 1+)","Broader protected classes than Title VII","DFEH/CRD complaint required before suit (exhaustion)","1-year statute of limitations for CRD complaint","Remedies include unlimited compensatory damages, punitive damages, injunctive relief"]', '[{"section":"12940","description":"Unlawful employment practices — discrimination, harassment, retaliation"},{"section":"12940(j)","description":"Employer liability for harassment"},{"section":"12940(k)","description":"Failure to prevent discrimination and harassment"},{"section":"12965","description":"Civil actions and right to sue"}]', '["DFEH_complaint","CRD_complaint","employment_discrimination","harassment_complaint","right_to_sue"]', '["constitutional-and-civil-rights-audit"]', 'CA Civil Rights Department / California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_058', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 149', 'PC § 149', 'Assault Under Color of Authority', 'Every public officer who, under color of authority and without lawful necessity, assaults or beats any person is guilty of a felony.', '["Applies to all public officers","Assault or battery under color of authority","Without lawful necessity","Felony offense","Covers law enforcement, correctional officers, and other public officials"]', '[{"section":"§ 149","description":"Public officer assault under color of authority — felony punishable by imprisonment in state prison"}]', '["criminal_complaint","police_misconduct","excessive_force","internal_affairs","1983_complaint"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'California DA / AG', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_059', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code § 815.2', 'Gov. Code § 815.2', 'Public Entity Vicarious Liability', 'A public entity is liable for injury proximately caused by an act or omission of an employee within the scope of employment if the act or omission would give rise to a cause of action against the employee.', '["Public entity liable for employee acts within scope of employment","Employee must have individual liability","Scope of employment determined by respondeat superior principles","Not liable if employee immune from liability","Foundation for suing government agencies for employee misconduct"]', '[{"section":"815.2(a)","description":"Public entity liable for injury caused by employee act or omission within scope of employment"},{"section":"815.2(b)","description":"Not liable if employee is immune"}]', '["government_tort_claim","police_misconduct","1983_complaint","vicarious_liability","state_court_complaint"]', '["constitutional-and-civil-rights-audit","police-report-data-cross-reference"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));
