-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 17
-- ═══════════════════════════════════════════════════════════════════════════
-- FACIALEX (biometric/facial recognition), FORGE-0 (software/build),
-- SENTINEL-0 (audit independence), plus cross-domain landmark case law.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- FACIALEX — Biometric & Facial Recognition Standards
-- ═══════════════════════════════════════════════════════════════════════════

-- CCPA Biometric Provisions
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_001', 'FACIALEX', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.140(c) (CCPA/CPRA — Biometric Information)', 'CCPA Biometric', 'CCPA/CPRA — Biometric Information as Sensitive Personal Information', 'Under CPRA amendments, biometric information is classified as sensitive personal information requiring enhanced protections. Consumers have the right to limit use and disclosure of biometric data. Biometric info includes physiological, biological, or behavioral characteristics used to establish individual identity: imagery of iris, retina, fingerprint, face, hand, palm, vein patterns, and voice recordings.', '["Biometric information classified as sensitive personal information","Consumer right to limit use and disclosure of biometric data","Purpose limitation: may only use for disclosed purpose","Data minimization: collect only what is necessary","Biometric data must be disclosed in privacy notice","Consumer may opt out of biometric data sharing/selling","Service providers must delete biometric data on request","Special rules for biometric information collected by employees"]', '[{"section":"1798.140(c)","description":"Definition of biometric information"},{"section":"1798.121","description":"Right to limit use of sensitive personal information"},{"section":"1798.100(a)(4)","description":"Right to know biometric data collected"},{"section":"1798.105","description":"Right to delete biometric data"},{"section":"1798.185(a)(16)","description":"AG/CPPA regulations for biometric data"}]', '["biometric_data_inventory","privacy_policy","biometric_consent_form","data_deletion_request","DSAR_response","biometric_impact_assessment"]', '["biometric-facial-recognition-audit"]', 'California Privacy Protection Agency (CPPA) / AG', 1, 1, datetime('now'), datetime('now'));

-- AB 1215 — Facial Recognition Ban in Body Cameras
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_002', 'FACIALEX', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1798.90.51-1798.90.54 (AB 1215, extended by AB 642)', 'CC § 1798.90.51', 'California Facial Recognition Ban in Law Enforcement Body Cameras', 'Prohibits law enforcement from installing, activating, or using facial recognition or other biometric surveillance technology in connection with body-worn cameras. Originally enacted as AB 1215 (2019) with sunset in 2023, extended by AB 642 through 2028. Does not prohibit facial recognition from other camera systems (CCTV, etc.).', '["Law enforcement cannot use facial recognition with body-worn cameras","Prohibition covers installation, activation, and use","Includes any biometric surveillance system on body cameras","Does not prohibit facial recognition on other systems","Extended through January 1, 2028 by AB 642","Applies to all California law enforcement agencies","Includes contract prohibition — cannot hire third party to circumvent"]', '[{"section":"1798.90.51","description":"Prohibition on facial recognition in body cameras"},{"section":"1798.90.52","description":"Definitions — facial recognition, biometric surveillance"},{"section":"1798.90.53","description":"Extension and sunset provisions"},{"section":"1798.90.54","description":"Severability"}]', '["body_camera_policy","facial_recognition_ban_compliance","law_enforcement_technology_audit","biometric_surveillance_policy"]', '["biometric-facial-recognition-audit"]', 'California Legislature / Civil Litigation', 1, 1, datetime('now'), datetime('now'));

-- Illinois BIPA (cross-reference)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_003', 'FACIALEX', 'STATE_STATUTE', 'US', '740 ILCS 14/1-99 (Illinois Biometric Information Privacy Act)', 'BIPA', 'Illinois Biometric Information Privacy Act — Gold Standard for Biometric Privacy', 'Most protective biometric privacy law in the US. Private right of action with statutory damages ($1,000 negligent, $5,000 intentional per violation). Requires written informed consent before collecting biometric identifiers. Must publish retention schedule and destruction guidelines. Landmark Rosenbach v. Six Flags (2019): no actual injury required for standing. Cross-reference standard for California biometric policy development.', '["Written informed consent BEFORE collecting biometric identifier","Must inform in writing of specific purpose and length of collection/storage","Must publish written retention schedule and destruction guidelines","Cannot sell, lease, trade, or profit from biometric identifiers","Must use reasonable standard of care to store and protect","Must destroy biometric data when initial purpose fulfilled or within 3 years of last interaction","Private right of action: $1,000/negligent violation, $5,000/intentional or reckless","No actual injury required for standing (Rosenbach v. Six Flags, 2019)","Covers fingerprint, retina, iris, voiceprint, hand/face geometry scans"]', '[{"section":"14/5","description":"Definitions — biometric identifier, biometric information"},{"section":"14/10","description":"Consent and purpose limitation requirements"},{"section":"14/15(a)","description":"Written policy — retention schedule and destruction guidelines"},{"section":"14/15(b)","description":"Informed written consent before collection"},{"section":"14/15(c)","description":"Prohibition on sale or profit from biometric data"},{"section":"14/15(d)","description":"Prohibition on disclosure without consent"},{"section":"14/15(e)","description":"Reasonable standard of care for storage"},{"section":"14/20","description":"Private right of action — statutory damages"}]', '["biometric_consent_form","retention_policy","destruction_certification","privacy_impact_assessment","biometric_data_inventory","class_action_complaint","BIPA_compliance_audit"]', '["biometric-facial-recognition-audit"]', 'Illinois Circuit Courts (private enforcement)', 1, 1, datetime('now'), datetime('now'));

-- NIST Face Recognition Standards
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_004', 'FACIALEX', 'PROFESSIONAL_STANDARD', 'US', 'NIST FRVT (Face Recognition Vendor Test) / NIST SP 800-76-2', 'NIST FRVT', 'NIST Face Recognition Standards and Vendor Testing', 'NIST conducts ongoing face recognition vendor testing (FRVT) measuring verification, identification, and demographic effect performance. NIST SP 800-76-2 specifies biometric specifications for PIV (Personal Identity Verification) credentials. FRVT demographic effects reports document differential performance across demographics — essential for equity auditing of facial recognition systems.', '["FRVT evaluates 1:1 verification and 1:N identification performance","Demographic effects testing across age, sex, race/ethnicity","False match rate and false non-match rate thresholds","Image quality standards for biometric capture","Liveness/presentation attack detection evaluation","PIV biometric data specifications (SP 800-76-2)","No mandatory compliance but widely referenced as benchmark","Results publicly available for all submitted algorithms"]', '[{"section":"FRVT 1:1","description":"Verification performance — false match/non-match rates"},{"section":"FRVT 1:N","description":"Identification performance — rank accuracy, throughput"},{"section":"FRVT Demographics","description":"Differential performance across demographic groups"},{"section":"FRVT PAD","description":"Presentation attack detection — liveness testing"},{"section":"SP 800-76-2","description":"PIV biometric specifications for federal credentials"}]', '["FRVT_evaluation_report","demographic_impact_assessment","biometric_accuracy_report","algorithm_performance_benchmark","equity_audit","vendor_comparison","PIV_credential_specification"]', '["biometric-facial-recognition-audit"]', 'NIST Information Technology Laboratory', 0, 1, datetime('now'), datetime('now'));

-- CA Deepfake — Sexually Explicit
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_005', 'FACIALEX', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1708.86 (AB 602 — Sexually Explicit Deepfakes)', 'CC § 1708.86', 'California Deepfake Liability — Sexually Explicit Digital Content', 'Creates civil cause of action for persons depicted in sexually explicit deepfake material created without consent. Plaintiff may recover economic and noneconomic damages, punitive damages, and attorney fees. Applies to any person who creates, intentionally discloses, or threatens to disclose deepfake sexually explicit material. Statute of limitations: 3 years from discovery.', '["Civil liability for creating sexually explicit deepfake without consent","Civil liability for intentionally disclosing deepfake material","Civil liability for threatening to disclose deepfake material","Damages: economic, noneconomic, punitive, attorney fees, costs","3-year statute of limitations from discovery or when should have discovered","Defendant includes creator, distributor, and anyone who threatens disclosure","Platform immunity under CDA § 230 may apply to intermediaries","Applies regardless of whether material depicts actual or simulated sexual conduct"]', '[{"section":"1708.86(a)","description":"Definitions — digitization, sexually explicit material, depicted individual"},{"section":"1708.86(b)","description":"Cause of action — creation without consent"},{"section":"1708.86(c)","description":"Cause of action — disclosure without consent"},{"section":"1708.86(d)","description":"Damages — economic, noneconomic, punitive, attorney fees"},{"section":"1708.86(e)","description":"Statute of limitations — 3 years from discovery"}]', '["deepfake_identification_report","takedown_request","civil_complaint","forensic_analysis","platform_notification","damages_calculation"]', '["biometric-facial-recognition-audit"]', 'California Superior Court', 1, 1, datetime('now'), datetime('now'));

-- CA Deepfake — Elections
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fac_006', 'FACIALEX', 'STATE_STATUTE', 'CA', 'Cal. Elec. Code §§ 20010-20012 (AB 730/AB 2655 — Election Deepfakes)', 'EC §§ 20010-20012', 'California Election Deepfake Prohibition — Materially Deceptive Media', 'Prohibits distribution of materially deceptive audio or visual media of a candidate within 120 days of an election (AB 730, 2019). AB 2655 (2024) expanded to require large online platforms to label or remove deceptive AI-generated election content. Candidate may seek injunctive relief and damages. Includes disclosure requirements for AI-generated political advertisements.', '["Cannot distribute materially deceptive media depicting candidate within 120 days of election","Large platforms must label or remove deceptive AI-generated election content (AB 2655)","Materially deceptive: reasonable person would believe depicts real events","Candidate may seek injunctive relief to remove content","Candidate may recover general and special damages","Exemptions: satire/parody if clearly identified, news reporting, documentary","AI-generated political ads must include disclosure of AI use","Platform must provide mechanism to flag AI-generated deceptive content"]', '[{"section":"20010","description":"Definitions — materially deceptive, audio/visual media"},{"section":"20010(a)","description":"Prohibition on deceptive media within 120 days of election"},{"section":"20010(b)","description":"Exemptions — satire, news, documentary"},{"section":"20011","description":"Injunctive relief and damages available to candidate"},{"section":"20012","description":"Platform obligations — label or remove (AB 2655)"}]', '["deepfake_election_content","AI_disclosure_label","platform_takedown","injunction_motion","election_integrity_audit","political_ad_disclosure"]', '["biometric-facial-recognition-audit"]', 'California Superior Court / Secretary of State', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FORGE-0 — Software Build & Licensing Standards
-- ═══════════════════════════════════════════════════════════════════════════

-- Open Source Licensing
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_for_001', 'FORGE-0', 'PROFESSIONAL_STANDARD', 'US', 'OSI-Approved Open Source Licenses (MIT, Apache 2.0, GPL v3, BSD)', 'OSI Licenses', 'Open Source License Compliance — OSI-Approved License Requirements', 'Software build compliance requires tracking and honoring open source license obligations. Permissive licenses (MIT, BSD, Apache 2.0) require attribution. Copyleft licenses (GPL, LGPL, AGPL) require derivative works be distributed under same license. License compatibility matrix determines which combinations are permissible. SBOM (Software Bill of Materials) increasingly required.', '["MIT: Include copyright notice and permission notice in copies — permissive","Apache 2.0: Include NOTICE file, patent grant, state changes — permissive","GPL v3: Derivative works must be GPL, provide source code, no tivoization — copyleft","LGPL: Library linking permitted without copyleft obligation — weak copyleft","AGPL: Network use triggers copyleft — source must be available for SaaS — strong copyleft","BSD 2-Clause: Include copyright notice — permissive","License compatibility: GPL-incompatible licenses cannot be combined with GPL code","SBOM: Enumerate all dependencies and their licenses","Attribution requirements must be met in distributed software"]', '[{"section":"MIT","description":"Permissive — attribution only, no copyleft"},{"section":"Apache 2.0","description":"Permissive — attribution, NOTICE file, patent grant"},{"section":"GPL v3","description":"Strong copyleft — derivatives must be GPL, source available"},{"section":"LGPL v3","description":"Weak copyleft — linking exception for libraries"},{"section":"AGPL v3","description":"Network copyleft — SaaS triggers source requirement"},{"section":"BSD","description":"Permissive — attribution only"}]', '["SBOM","license_inventory","NOTICE_file","LICENSE_file","attribution_document","open_source_policy","dependency_audit","license_compatibility_matrix"]', '["autonomous-build-compliance-audit"]', 'Copyright holders / Civil Courts', 1, 1, datetime('now'), datetime('now'));

-- SBOM Requirements
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_for_002', 'FORGE-0', 'FEDERAL_REGULATION', 'US', 'EO 14028 § 4 / NTIA SBOM Minimum Elements (July 2021)', 'EO 14028 SBOM', 'Software Bill of Materials — Federal Requirements', 'Executive Order 14028 (May 2021) on Improving the Nation''s Cybersecurity requires SBOM for software sold to federal government. NTIA published minimum elements: supplier name, component name, version, unique identifier, dependency relationship, author of SBOM data, and timestamp. CISA leads SBOM efforts. Applies to all software including firmware and open source components.', '["SBOM required for software sold to federal government","Minimum elements: supplier, component name, version, unique identifier","Must include dependency relationships between components","Author of SBOM data and timestamp required","Machine-readable format: SPDX, CycloneDX, or SWID tags","Must be generated for each new release/update","Covers all software including open source, commercial, firmware","Known vulnerability scanning against SBOM components","SBOM must be provided to purchaser and available to CISA upon request"]', '[{"section":"EO 14028 § 4","description":"Enhancing software supply chain security"},{"section":"NTIA Minimum Elements","description":"7 minimum data fields for SBOM"},{"section":"SPDX","description":"Linux Foundation SBOM standard format"},{"section":"CycloneDX","description":"OWASP SBOM standard format"},{"section":"CISA SBOM Guidance","description":"Federal SBOM implementation guidance"}]', '["SBOM_document","dependency_manifest","vulnerability_scan_report","software_attestation","supply_chain_risk_assessment","package_lock_file"]', '["autonomous-build-compliance-audit"]', 'CISA / NIST / Federal Agencies (procurement)', 0, 1, datetime('now'), datetime('now'));

-- Secure Software Development (SSDF)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_for_003', 'FORGE-0', 'PROFESSIONAL_STANDARD', 'US', 'NIST SP 800-218 (Secure Software Development Framework v1.1)', 'NIST SSDF 1.1', 'NIST Secure Software Development Framework', 'Framework of practices for secure software development. Four practice groups: Prepare Organization (PO), Protect Software (PS), Produce Well-Secured Software (PW), Respond to Vulnerabilities (RV). Referenced by EO 14028 and OMB M-22-18 for federal software attestation requirements. Software producers must attest to SSDF conformance for federal sales.', '["PO: Prepare — define security requirements, roles, implement toolchains","PS: Protect — protect development environment, code integrity, archive","PW: Produce — design secure, review/analyze code, test, configure defaults","RV: Respond — identify and confirm vulnerabilities, assess impact, remediate","Federal attestation requirement under OMB M-22-18","Self-attestation form for software sold to government","Third-party assessment for critical software","Continuous compliance — not one-time certification","Applies to all software including open source libraries used"]', '[{"section":"PO","description":"Prepare the Organization — 5 practices"},{"section":"PS","description":"Protect the Software — 3 practices"},{"section":"PW","description":"Produce Well-Secured Software — 9 practices"},{"section":"RV","description":"Respond to Vulnerabilities — 3 practices"},{"section":"OMB M-22-18","description":"Federal self-attestation requirement"}]', '["SSDF_attestation","secure_development_policy","code_review_records","SAST_DAST_reports","vulnerability_management_plan","incident_response_plan","build_environment_documentation"]', '["autonomous-build-compliance-audit"]', 'NIST / CISA / OMB (federal procurement)', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- SENTINEL-0 — Audit Independence & Professional Standards
-- ═══════════════════════════════════════════════════════════════════════════

-- Auditor Independence — SEC/PCAOB
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_sen_001', 'SENTINEL-0', 'FEDERAL_REGULATION', 'US', 'SOX § 201-209 / 17 CFR § 210.2-01 (SEC Rule 2-01) / PCAOB Rule 3520', 'SOX Independence / Rule 2-01', 'Auditor Independence Requirements — SEC, PCAOB, and Sarbanes-Oxley', 'Comprehensive independence requirements for auditors of public companies. SOX § 201 prohibits 9 categories of non-audit services. Mandatory audit partner rotation every 5 years with 5-year cooling off. One-year cooling off before former audit firm personnel can join client in financial oversight role. Audit committee must pre-approve all audit and permitted non-audit services.', '["9 prohibited non-audit services: bookkeeping, financial information systems, appraisal/valuation, actuarial, internal audit, management/HR, broker-dealer, legal, expert services","Audit partner rotation: 5 years on, 5 years off","1-year cooling off: former partner cannot join client in financial oversight role","Audit committee pre-approval of all audit and permitted non-audit services","No financial interest in audit client","No business relationships with audit client","No employment relationships with audit client","Audit fees cannot be contingent on results","Second partner review (concurring reviewer) required"]', '[{"section":"SOX § 201","description":"9 prohibited non-audit services"},{"section":"SOX § 203","description":"Audit partner rotation — 5/5 year requirement"},{"section":"SOX § 206","description":"Conflicts of interest — 1-year cooling off period"},{"section":"Rule 2-01(b)","description":"General independence standard — reasonable investor test"},{"section":"Rule 2-01(c)(1)","description":"Financial relationships — prohibited investments"},{"section":"Rule 2-01(c)(2)","description":"Employment relationships — prohibited positions"},{"section":"Rule 2-01(c)(4)","description":"Non-audit services — prohibited categories"},{"section":"PCAOB Rule 3520","description":"Auditor independence — PCAOB standard"}]', '["independence_declaration","audit_engagement_letter","partner_rotation_schedule","non_audit_services_pre_approval","conflict_of_interest_check","audit_committee_minutes","cooling_off_compliance"]', '["independent-audit-compliance"]', 'SEC / PCAOB / State Boards of Accountancy', 0, 1, datetime('now'), datetime('now'));

-- AICPA Code of Professional Conduct
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_sen_002', 'SENTINEL-0', 'PROFESSIONAL_STANDARD', 'US', 'AICPA Code of Professional Conduct (ET §§ 0.100-2.400)', 'AICPA Code of Conduct', 'AICPA Code of Professional Conduct — CPA Ethical Requirements', 'Professional ethics standards for CPAs including independence, integrity, objectivity, and due care. Conceptual framework approach: identify threats to compliance, evaluate significance, apply safeguards. Six principles: Responsibilities, Public Interest, Integrity, Objectivity/Independence, Due Care, Scope/Nature of Services. Violations subject to AICPA disciplinary action and state board enforcement.', '["Independence required for attest engagements","Integrity: honest and candid, subordinate self-interest","Objectivity: free from conflicts of interest, impartial","Due care: competent, diligent, adequate planning/supervision","Confidentiality: do not disclose client information without consent","Contingent fees prohibited for attest engagements","Commissions/referral fees restricted for attest clients","Acts discreditable to the profession prohibited","Compliance with standards — GAAS, SSARS, SSAE","Conceptual framework: threats, significance, safeguards"]', '[{"section":"ET 0.300","description":"Six principles of professional conduct"},{"section":"ET 1.200","description":"Independence — conceptual framework approach"},{"section":"ET 1.210","description":"Conceptual framework for independence"},{"section":"ET 1.220","description":"Financial interests in attest clients"},{"section":"ET 1.230","description":"Employment/business relationships"},{"section":"ET 1.295","description":"Non-attest services — independence implications"},{"section":"ET 1.310","description":"Integrity and objectivity"},{"section":"ET 1.400","description":"Acts discreditable to the profession"}]', '["independence_analysis","ethics_consultation","confidentiality_agreement","engagement_letter","quality_control_review","disciplinary_proceeding","ethics_complaint"]', '["independent-audit-compliance"]', 'AICPA Ethics Division / State Boards of Accountancy', 0, 1, datetime('now'), datetime('now'));

-- Quality Control — SQCS / ISQM
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_sen_003', 'SENTINEL-0', 'PROFESSIONAL_STANDARD', 'US', 'AICPA QM Section 10A (Quality Management) / ISQM 1', 'QM 10A / ISQM 1', 'Quality Management for Audit Firms — Risk-Based Approach', 'Standards for audit firm quality management systems. Risk-based approach replacing previous element-based SQCS standards. Eight components: firm risk assessment, governance/leadership, ethical requirements, acceptance/continuance, engagement performance, resources, information/communication, monitoring/remediation. Requires annual evaluation of quality management system effectiveness.', '["Firm-level risk assessment process for quality risks","Governance and leadership commitment to quality","Relevant ethical requirements including independence","Acceptance and continuance of client relationships","Engagement performance — direction, supervision, review","Resources — human, technological, intellectual","Information and communication — quality-related information","Monitoring and remediation — proactive quality monitoring","Annual evaluation of quality management system","Root cause analysis of identified deficiencies"]', '[{"section":"QM 10A.30","description":"Firm risk assessment process"},{"section":"QM 10A.31-33","description":"Governance and leadership responsibilities"},{"section":"QM 10A.34-36","description":"Relevant ethical requirements"},{"section":"QM 10A.37-40","description":"Acceptance and continuance policies"},{"section":"QM 10A.41-45","description":"Engagement performance standards"},{"section":"QM 10A.46-51","description":"Resources — human, technological, intellectual"},{"section":"QM 10A.52-56","description":"Monitoring and remediation"},{"section":"QM 10A.57","description":"Annual evaluation of QM system"}]', '["QM_system_documentation","risk_assessment","monitoring_report","root_cause_analysis","peer_review_report","annual_evaluation","remediation_plan","engagement_quality_review"]', '["independent-audit-compliance"]', 'AICPA Peer Review / State Boards of Accountancy', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CROSS-DOMAIN LANDMARK CASE LAW
-- ═══════════════════════════════════════════════════════════════════════════

-- Family Law — Troxel v. Granville
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_001', 'ADVOCIS', 'CASE_LAW', 'US', 'Troxel v. Granville, 530 U.S. 57 (2000)', 'Troxel v. Granville', 'Parental Rights as Fundamental Liberty Interest — Grandparent Visitation', 'Parents have a fundamental liberty interest under the 14th Amendment Due Process Clause in the care, custody, and control of their children. Fit parent''s decision regarding visitation must be given special weight. State court must accord at least some special weight to parent''s own determination of child''s best interests. Washington grandparent visitation statute unconstitutional as applied because it permitted any person to petition for visitation at any time.', '["Parental right to care, custody, control of children is fundamental liberty interest","14th Amendment Due Process Clause protects parental rights","Fit parent presumption: fit parent acts in child best interest","Special weight required to parent''s determination of best interests","State may not substitute its judgment for fit parent without more","Overbroad visitation statutes violate due process","Parent need not show harm to child — burden on petitioner","Plurality opinion — no single standard, but deference to fit parents required"]', '[{"section":"Holding","description":"Parents have fundamental liberty interest in directing upbringing of children"},{"section":"Application","description":"Court must give special weight to fit parent''s determination"},{"section":"Standard","description":"No showing of harm required from fit parent to deny visitation"},{"section":"Impact","description":"Grandparent visitation statutes must include parental deference"}]', '["grandparent_visitation_petition","parental_objection","custody_modification","due_process_motion","visitation_order"]', '["victim-rights-marsys-law-audit","family-law-custody-audit"]', 'US Supreme Court / State Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Civil Rights — Monroe v. Pape
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_002', 'ADVOCIS', 'CASE_LAW', 'US', 'Monroe v. Pape, 365 U.S. 167 (1961)', 'Monroe v. Pape', 'Section 1983 — State Actors Acting Under Color of Law', 'Established that 42 USC § 1983 provides a federal remedy for constitutional violations by state actors. Officers acting "under color of" state law includes abuse of authority — even if actions violate state law. Municipality was not a "person" under § 1983 (later overruled by Monell). Opened courthouse doors for federal civil rights suits against police misconduct.', '["§ 1983 provides federal remedy for constitutional violations by state actors","Under color of law includes misuse of power possessed by virtue of state law","State actor need not be following state policy — individual abuse of authority qualifies","No requirement to exhaust state remedies before filing § 1983 action","Federal and state claims may proceed simultaneously","Opened federal courts to police misconduct claims","Municipality not a person (later overruled by Monell v. Dept of Social Services)"]', '[{"section":"Holding","description":"§ 1983 applies to state officers acting under color of law even when violating state law"},{"section":"Under Color of Law","description":"Misuse of state-conferred authority — not limited to authorized conduct"},{"section":"No Exhaustion","description":"Federal § 1983 action does not require prior state remedy"},{"section":"Impact","description":"Foundation for modern police misconduct litigation"}]', '["1983_complaint","police_misconduct_complaint","civil_rights_complaint","qualified_immunity_motion","damages_claim"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Monell v. Department of Social Services
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_003', 'ADVOCIS', 'CASE_LAW', 'US', 'Monell v. Dept. of Social Services, 436 U.S. 658 (1978)', 'Monell', 'Municipal Liability Under § 1983 — Custom, Policy, or Practice', 'Overruled Monroe v. Pape to hold municipalities are "persons" subject to suit under § 1983. However, municipality cannot be liable on respondeat superior theory. Must show constitutional violation resulted from official policy, widespread custom, or deliberate indifference by final policymaker. Three theories: (1) official policy/ordinance, (2) widespread practice/custom, (3) failure to train/supervise (Canton).', '["Municipalities are persons under § 1983 — can be sued","No respondeat superior — must show policy/custom caused violation","Official policy: formal policy, ordinance, or regulation","Custom: widespread practice so permanent and well-settled as to have force of law","Final policymaker: person with authority to make policy in area at issue","Failure to train: deliberate indifference standard (City of Canton v. Harris)","Single incident may establish policy if decision made by final policymaker","Punitive damages not available against municipalities"]', '[{"section":"Holding","description":"Municipalities are persons under § 1983"},{"section":"Policy/Custom","description":"Must prove policy, custom, or practice caused violation"},{"section":"No Respondeat Superior","description":"Cannot hold city liable solely because it employs tortfeasor"},{"section":"Final Policymaker","description":"Policy made by official with final authority in relevant area"},{"section":"Impact","description":"Foundation for suing cities and counties for systemic violations"}]', '["1983_complaint_against_municipality","Monell_claim","policy_or_custom_evidence","final_policymaker_identification","failure_to_train_claim","pattern_and_practice_evidence"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Brady v. Maryland
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_004', 'ADVOCIS', 'CASE_LAW', 'US', 'Brady v. Maryland, 373 U.S. 83 (1963)', 'Brady v. Maryland', 'Prosecutorial Duty to Disclose Exculpatory Evidence', 'Prosecution must disclose all evidence favorable to the accused that is material to guilt or punishment. Suppression of material exculpatory evidence violates due process regardless of good or bad faith of prosecution. Extended to impeachment evidence (Giglio v. US). Brady violation requires: (1) evidence is favorable, (2) prosecution suppressed it, (3) prejudice resulted (reasonable probability of different outcome).', '["Prosecution must disclose evidence favorable to defense","Includes exculpatory AND impeachment evidence (Giglio)","Applies regardless of good or bad faith of prosecution","Material: reasonable probability result would have been different","Duty extends to evidence in possession of police (Kyles v. Whitley)","Prosecution team includes all law enforcement involved in case","Remedy: new trial if Brady violation established","Brady list: officers with sustained dishonesty findings"]', '[{"section":"Holding","description":"Suppression of material exculpatory evidence violates due process"},{"section":"Materiality","description":"Reasonable probability of different result had evidence been disclosed"},{"section":"Scope","description":"Includes impeachment evidence (Giglio v. United States)"},{"section":"Police Files","description":"Prosecution duty extends to evidence held by police team (Kyles v. Whitley)"},{"section":"Impact","description":"Foundation for criminal discovery obligations"}]', '["Brady_disclosure","discovery_motion","exculpatory_evidence","impeachment_material","Brady_list","new_trial_motion","habeas_petition"]', '["victim-rights-marsys-law-audit","ca-post-law-enforcement-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Graham v. Connor — Excessive Force
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_005', 'ADVOCIS', 'CASE_LAW', 'US', 'Graham v. Connor, 490 U.S. 386 (1989)', 'Graham v. Connor', 'Excessive Force — Objective Reasonableness Standard', 'All claims of excessive force by law enforcement during arrest, investigatory stop, or seizure analyzed under 4th Amendment objective reasonableness standard — not substantive due process. Reasonableness judged from perspective of reasonable officer on scene, not 20/20 hindsight. Factors: severity of crime, immediate threat to officers/others, actively resisting/attempting flight. Totality of circumstances.', '["Excessive force claims analyzed under 4th Amendment reasonableness","Objective standard: reasonable officer in same circumstances","NOT judged with 20/20 hindsight","Graham factors: (1) severity of crime at issue, (2) whether suspect poses immediate threat, (3) whether suspect actively resisting or attempting to flee","Totality of circumstances analysis","Allowance for split-second decisions under tense, uncertain, rapidly evolving circumstances","Applies to seizures of persons during arrest and investigatory stops","Does not require subjective intent to harm"]', '[{"section":"Holding","description":"4th Amendment objective reasonableness governs excessive force claims"},{"section":"Graham Factors","description":"Severity of crime, immediate threat, active resistance/flight"},{"section":"Perspective","description":"Reasonable officer on scene, not hindsight"},{"section":"Totality","description":"All circumstances considered, not mechanical checklist"},{"section":"Impact","description":"Standard for all police use-of-force litigation"}]', '["use_of_force_report","1983_excessive_force_complaint","body_camera_footage","witness_statements","medical_records","internal_affairs_investigation","Graham_factor_analysis"]', '["victim-rights-marsys-law-audit","ca-post-law-enforcement-audit"]', 'Federal Courts / State Courts', 1, 1, datetime('now'), datetime('now'));

-- Miranda v. Arizona
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_006', 'ADVOCIS', 'CASE_LAW', 'US', 'Miranda v. Arizona, 384 U.S. 436 (1966)', 'Miranda', 'Miranda Warnings — Custodial Interrogation Protections', 'Police must inform suspects of their rights before custodial interrogation. Statements obtained without Miranda warnings are inadmissible in prosecution case-in-chief. Four required warnings: right to remain silent, anything said can be used against you, right to attorney, if cannot afford attorney one will be appointed. Waiver must be knowing, voluntary, and intelligent. Vega v. Tekoh (2022): no § 1983 damages for Miranda violation alone.', '["Custodial interrogation triggers Miranda requirement","Four warnings required: silence, used against you, attorney, appointed attorney","Waiver must be knowing, voluntary, and intelligent","Invocation of right to silence must be honored — questioning must cease","Invocation of right to attorney must be honored — no further questioning without attorney","Statements without Miranda inadmissible in case-in-chief","Public safety exception: immediate threat permits unwarned questioning (Quarles)","No § 1983 damages for Miranda violation alone (Vega v. Tekoh, 2022)","Fruit of poisonous tree may apply to derivative evidence"]', '[{"section":"Holding","description":"Custodial interrogation requires Miranda warnings"},{"section":"Four Warnings","description":"Silence, used against, attorney, appointed attorney"},{"section":"Waiver","description":"Must be knowing, voluntary, and intelligent"},{"section":"Invocation","description":"Questioning must cease upon invocation of rights"},{"section":"Exception","description":"Public safety exception (New York v. Quarles)"},{"section":"Limitation","description":"No § 1983 damages for violation alone (Vega v. Tekoh, 2022)"}]', '["Miranda_waiver_form","interrogation_recording","suppression_motion","arrest_report","custodial_interrogation_record","rights_advisement"]', '["ca-post-law-enforcement-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Terry v. Ohio — Stop and Frisk
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_007', 'ADVOCIS', 'CASE_LAW', 'US', 'Terry v. Ohio, 392 U.S. 1 (1968)', 'Terry v. Ohio', 'Investigatory Stop and Frisk — Reasonable Suspicion Standard', 'Officers may briefly stop a person based on reasonable articulable suspicion of criminal activity (less than probable cause). Pat-down frisk permitted if officer reasonably believes person is armed and dangerous. Scope of frisk limited to outer clothing for weapons. Reasonable suspicion requires specific articulable facts, not hunches. Foundation for all stop-and-frisk jurisprudence.', '["Brief investigatory stop permitted on reasonable articulable suspicion","Reasonable suspicion: specific, articulable facts suggesting criminal activity","Less than probable cause but more than mere hunch","Pat-down frisk permitted if reasonable belief person is armed and dangerous","Frisk limited to outer clothing for weapons — plain feel doctrine (Dickerson)","Duration must be reasonably related to purpose of stop","Officer must be able to articulate basis for suspicion","Fruits of unlawful Terry stop subject to exclusionary rule"]', '[{"section":"Holding","description":"Brief stop permitted on reasonable articulable suspicion"},{"section":"Frisk","description":"Pat-down for weapons if reasonable belief of danger"},{"section":"Scope","description":"Outer clothing only — limited to weapons detection"},{"section":"Standard","description":"Specific articulable facts, not hunches or profiles"},{"section":"Impact","description":"Foundation for investigatory stop jurisprudence"}]', '["stop_and_frisk_report","field_interview_card","reasonable_suspicion_documentation","suppression_motion","RIPA_data","body_camera_footage","4th_amendment_motion"]', '["ca-post-law-enforcement-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Tarasoff v. Regents
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_008', 'ETHICARA', 'CASE_LAW', 'CA', 'Tarasoff v. Regents of University of California, 17 Cal.3d 425 (1976)', 'Tarasoff', 'Duty to Warn/Protect — Therapist Liability for Patient Threats', 'When a therapist determines, or pursuant to professional standards should determine, that a patient presents a serious danger of violence to a foreseeable victim, the therapist has a duty to use reasonable care to protect the intended victim. Codified in California Civil Code § 43.92 which limits duty to situations where patient has communicated a serious threat of physical violence against a reasonably identifiable victim.', '["Therapist has duty to protect when patient poses serious danger to identifiable victim","Duty arises when therapist determines OR should determine danger exists","Duty to use reasonable care — may include warning victim, notifying police, or taking other steps","Codified: CC § 43.92 limits to communicated serious threat against reasonably identifiable victim","Discharge of duty: reasonable efforts to communicate threat to victim and law enforcement","Privilege (psychotherapist-patient) yields to public safety","Must be serious threat of physical violence — not property damage or vague statements","Applies to all licensed mental health professionals in California"]', '[{"section":"Holding","description":"Duty to protect foreseeable victims of patient violence"},{"section":"Standard","description":"When therapist determines or should determine serious danger exists"},{"section":"Codification","description":"CC § 43.92 — communicated threat against identifiable victim"},{"section":"Discharge","description":"Reasonable efforts to communicate to victim and law enforcement"},{"section":"Limitation","description":"Serious threat of physical violence — specific, identifiable victim"},{"section":"Impact","description":"National standard for therapist duty to warn/protect"}]', '["Tarasoff_warning","police_notification","threat_assessment","patient_record","duty_to_warn_documentation","risk_assessment","liability_analysis"]', '["professional-ethics-standards-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- Daubert v. Merrell Dow — Expert Testimony
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_009', 'ETHICARA', 'CASE_LAW', 'US', 'Daubert v. Merrell Dow Pharmaceuticals, 509 U.S. 579 (1993)', 'Daubert', 'Expert Testimony Admissibility — Scientific Reliability Standard', 'Replaced Frye "general acceptance" test with multi-factor reliability inquiry for expert testimony under Federal Rule of Evidence 702. Trial judge serves as gatekeeper. Daubert factors: (1) testable/tested theory, (2) peer review, (3) known error rate, (4) standards controlling technique, (5) general acceptance. California retains Sargon (Daubert-like) for expert testimony, and Kelly/Frye for novel scientific evidence.', '["Trial judge is gatekeeper for expert testimony admissibility","Expert testimony must be based on sufficient facts or data","Testimony must be product of reliable principles and methods","Principles must be reliably applied to facts of case","Daubert factors (non-exclusive): testability, peer review, error rate, standards, general acceptance","Not limited to scientific testimony — applies to all expert testimony (Kumho Tire)","California: Sargon standard for expert opinions, Kelly/Frye for novel scientific techniques","Judge evaluates methodology, not conclusions"]', '[{"section":"Holding","description":"Trial judge as gatekeeper — reliability inquiry replaces Frye"},{"section":"Daubert Factors","description":"Testability, peer review, error rate, standards, acceptance"},{"section":"Kumho Tire","description":"Extended to all expert testimony, not just scientific"},{"section":"FRE 702","description":"Codified Daubert standard in Federal Rules of Evidence"},{"section":"California","description":"Sargon for expert opinions, Kelly/Frye for novel scientific evidence"},{"section":"Impact","description":"Standard for expert testimony in federal courts and most states"}]', '["expert_report","Daubert_motion","voir_dire_of_expert","FRE_702_analysis","methodology_challenge","Sargon_motion","Kelly_Frye_motion"]', '["professional-ethics-standards-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Carpenter v. United States — Digital Privacy
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_010', 'PRIVAXIS', 'CASE_LAW', 'US', 'Carpenter v. United States, 585 U.S. 296 (2018)', 'Carpenter', 'Cell-Site Location Information — Warrant Required for Digital Surveillance', 'Government acquisition of cell-site location information (CSLI) constitutes a Fourth Amendment search requiring a warrant. Third-party doctrine does not apply to comprehensive, revealing digital records that provide intimate window into person''s life. 7+ days of historical CSLI requires warrant supported by probable cause. Narrow holding — did not address real-time CSLI, tower dumps, or other digital surveillance.', '["Acquiring 7+ days of historical CSLI is a Fourth Amendment search","Warrant required supported by probable cause","Third-party doctrine inapplicable to comprehensive digital records","Cell phone location data reveals familial, political, professional, religious, sexual associations","Pervasive and cheap surveillance fundamentally different from limited tools of past","Individual maintains legitimate expectation of privacy in physical movements","Narrow holding: does not address real-time CSLI, tower dumps, foreign affairs, or national security","Good faith exception may apply to pre-Carpenter acquisitions"]', '[{"section":"Holding","description":"CSLI acquisition is Fourth Amendment search requiring warrant"},{"section":"Third-Party Doctrine","description":"Does not extend to comprehensive revealing digital records"},{"section":"Scope","description":"7+ days historical CSLI — narrow holding"},{"section":"Not Addressed","description":"Real-time CSLI, tower dumps, national security"},{"section":"Impact","description":"Landmark digital privacy protection — limits warrantless surveillance"}]', '["search_warrant","CSLI_request","suppression_motion","Carpenter_motion","cell_tower_records","digital_surveillance_authorization","probable_cause_affidavit"]', '["privacy-data-protection-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Green v. Superior Court — Habitability
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_011', 'REGULIS', 'CASE_LAW', 'CA', 'Green v. Superior Court, 10 Cal.3d 616 (1974)', 'Green v. Superior Court', 'Implied Warranty of Habitability — Rent Withholding Defense', 'Established that California residential leases contain implied warranty of habitability. Breach is defense to unlawful detainer action. Tenant may withhold rent proportional to reduced value of premises. Standard: whether premises substantially comply with building and housing code standards materially affecting health and safety. Landlord obligation is nondelegable.', '["Residential leases include implied warranty of habitability","Breach of warranty is affirmative defense to unlawful detainer","Tenant may withhold rent proportional to diminished value","Standard: substantial compliance with codes materially affecting health/safety","Landlord duty is nondelegable — cannot shift to tenant or third party","Tenant need not vacate to assert warranty","Applies even if tenant knew of defects at move-in","Must affect health and safety — cosmetic issues insufficient"]', '[{"section":"Holding","description":"Implied warranty of habitability in residential leases"},{"section":"Defense","description":"Complete defense to unlawful detainer for nonpayment"},{"section":"Standard","description":"Substantial compliance with codes affecting health/safety"},{"section":"Remedy","description":"Rent proportional to diminished value of premises"},{"section":"Impact","description":"Foundation for California tenant habitability rights"}]', '["habitability_defense","rent_withholding_notice","code_enforcement_report","UD_answer","building_inspection","repair_demand"]', '["california-housing-tenant-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

-- In re Marriage of Brown — Community Property Pensions
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_012', 'REGULIS', 'CASE_LAW', 'CA', 'In re Marriage of Brown, 15 Cal.3d 838 (1976)', 'In re Marriage of Brown', 'Community Property Division of Pensions — Time Rule Formula', 'Non-vested pension rights are community property subject to division upon dissolution. Established the "time rule" formula: community property fraction = years of service during marriage / total years of service at retirement. Each spouse entitled to 50% of community property portion. Applies to all defined benefit pension plans. QDRO or COAP required for implementation.', '["Non-vested pension benefits are community property","Time rule formula: CP fraction = marital service years / total service years","Each spouse entitled to 50% of community property fraction","Applies at time of retirement/payment, not dissolution","Both vested and non-vested pension interests divisible","Applies to all defined benefit plans: government, military, private","QDRO (private) or COAP (CalPERS) required for implementation","In-kind division preferred over offset where possible"]', '[{"section":"Holding","description":"Non-vested pension benefits are divisible community property"},{"section":"Time Rule","description":"CP years of service / total years of service"},{"section":"Division","description":"50% of community property portion to each spouse"},{"section":"Implementation","description":"QDRO, COAP, or other division order at retirement"},{"section":"Impact","description":"National model for pension division in divorce"}]', '["QDRO","COAP","pension_valuation","time_rule_calculation","dissolution_judgment","FL_150_schedule","pension_division_order"]', '["california-housing-tenant-audit","family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));
