-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 18
-- ═══════════════════════════════════════════════════════════════════════════
-- Cross-domain landmark case law batch 2: family law, employment, housing,
-- privacy/4th Amendment, criminal procedure, police/QI, due process,
-- constitutional/civil rights.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- FAMILY LAW — Move-Away, Putative Spouse, Procedural Reform
-- ═══════════════════════════════════════════════════════════════════════════

-- In re Marriage of LaMusga — Move-Away Standard
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_013', 'ADVOCIS', 'CASE_LAW', 'CA', 'In re Marriage of LaMusga, 32 Cal.4th 1072 (2004)', 'LaMusga', 'Move-Away Standard — Custodial Parent Relocation Rights', 'Custodial parent has presumptive right to change residence with child. Noncustodial parent seeking to prevent relocation bears initial burden of showing the proposed move would cause detriment to the child. If detriment shown, court conducts full best-interest analysis under Family Code § 7501. Factors include: child''s interest in stability and continuity, distance of move, child''s age, relationship with both parents, and whether custodial parent''s move is in good faith. Revised framework from In re Marriage of Burgess (1996).', '["Custodial parent has presumptive right to relocate with child","Noncustodial parent bears burden of showing detriment to child","If detriment shown, court conducts full best-interest analysis","Family Code § 7501: parent entitled to change residence unless change prejudicial to child","Factors: stability, distance, child age, parent relationships, good faith","Court may not prohibit relocation absent showing of detriment","Changed-circumstance threshold applies to modification motions","Best interest of child is paramount — not parent convenience"]', '[{"section":"Holding","description":"Custodial parent presumptively entitled to relocate; noncustodial must show detriment"},{"section":"Burden","description":"Noncustodial parent bears initial burden to demonstrate detriment to child"},{"section":"Best Interest Factors","description":"Stability, distance, age, parental relationships, good faith of move"},{"section":"Burgess Framework","description":"Revised and clarified Burgess move-away standard"},{"section":"Application","description":"If detriment shown, full evidentiary hearing on best interests required"}]', '["move_away_motion","custody_modification","relocation_notice","best_interest_declaration","FL_300_motion","parenting_plan","visitation_schedule"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Montenegro v. Diaz — Putative Spouse Doctrine
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_014', 'REGULIS', 'CASE_LAW', 'CA', 'Montenegro v. Diaz, 26 Cal.4th 249 (2001)', 'Montenegro v. Diaz', 'Putative Spouse Doctrine — Good Faith Belief in Valid Marriage', 'A person who has a good faith belief in the validity of a marriage that is void or voidable is a putative spouse entitled to divide property acquired during the union as quasi-marital property. Good faith belief is subjective and objective: party must actually believe marriage is valid, and that belief must be objectively reasonable. Putative spouse has same rights as legal spouse to quasi-marital property division under Family Code § 2251. Knowledge of impediment at any point terminates putative spouse status prospectively.', '["Good faith belief in valid marriage creates putative spouse status","Putative spouse entitled to quasi-marital property division","Family Code § 2251 governs quasi-marital property rights","Good faith must be both subjective (actual belief) and objectively reasonable","Knowledge of impediment terminates status prospectively","Quasi-marital property divided same as community property","Putative spouse may recover attorney fees under FC § 2254","Status determined at time of marriage ceremony or cohabitation","Both parties may be putative spouses simultaneously"]', '[{"section":"Holding","description":"Good faith belief in valid marriage entitles putative spouse to quasi-marital property"},{"section":"Good Faith Standard","description":"Subjective actual belief plus objective reasonableness"},{"section":"FC § 2251","description":"Quasi-marital property divided as community property"},{"section":"Termination","description":"Knowledge of impediment ends putative spouse status prospectively"},{"section":"Application","description":"Applies to void and voidable marriages equally"}]', '["putative_spouse_petition","quasi_marital_property_declaration","dissolution_petition","property_division","FL_160_property_declaration","good_faith_evidence","marriage_validity_analysis"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));

-- Elkins v. Superior Court — Live Testimony Rights
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_015', 'ADVOCIS', 'CASE_LAW', 'CA', 'Elkins v. Superior Court, 41 Cal.4th 1337 (2007)', 'Elkins', 'Family Law Litigants Entitled to Live Testimony — Due Process in Family Court', 'Family law litigants have the right to present live testimony and cross-examine witnesses, not merely submit written declarations. Local court rules requiring disposition of contested family law matters solely on declarations violate due process and the Evidence Code. Led to sweeping reform: Elkins Family Law Task Force recommendations enacted in Family Code § 217, which creates presumption favoring live testimony at contested hearings. Court must state reasons on record for refusing live testimony.', '["Family law litigants have right to live testimony at contested hearings","Written declarations alone cannot resolve contested issues","Cross-examination right applies in family law proceedings","Family Code § 217: presumption favoring live testimony","Court must state reasons on record for refusing live testimony request","Local rules cannot override statutory right to present evidence","Applies to all contested family law matters including custody, support, property","Self-represented litigants have same testimonial rights as represented parties"]', '[{"section":"Holding","description":"Due process requires live testimony opportunity in contested family law matters"},{"section":"FC § 217","description":"Presumption favoring live testimony enacted in response to Elkins"},{"section":"Cross-Examination","description":"Right to confront and cross-examine witnesses in family court"},{"section":"Elkins Task Force","description":"Led to comprehensive family law procedural reforms"},{"section":"Application","description":"Court must allow live testimony or state reasons for refusal on record"}]', '["live_testimony_request","FC_217_motion","due_process_objection","witness_list","subpoena","trial_brief","self_represented_litigant_rights"]', '["family-law-custody-audit"]', 'California Family Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- EMPLOYMENT — Discrimination, Harassment, Public Employee Speech
-- ═══════════════════════════════════════════════════════════════════════════

-- McDonnell Douglas Corp. v. Green — Burden-Shifting Framework
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_016', 'REGULIS', 'CASE_LAW', 'US', 'McDonnell Douglas Corp. v. Green, 411 U.S. 792 (1973)', 'McDonnell Douglas', 'Employment Discrimination — Burden-Shifting Framework', 'Established the three-step burden-shifting framework for Title VII employment discrimination claims based on circumstantial evidence. Step 1: Plaintiff establishes prima facie case (member of protected class, qualified, adverse action, inference of discrimination). Step 2: Burden shifts to employer to articulate legitimate, nondiscriminatory reason. Step 3: Plaintiff must show employer''s reason is pretext for discrimination. Framework applied to FEHA claims in California (Guz v. Bechtel, 2000).', '["Three-step burden-shifting framework for discrimination claims","Prima facie case: protected class, qualified, adverse action, inference of discrimination","Employer must articulate legitimate nondiscriminatory reason","Plaintiff must demonstrate pretext — reason is false or discriminatory motive","Burden of production shifts; burden of persuasion remains with plaintiff","Applies to Title VII race, color, religion, sex, national origin claims","Extended to age (ADEA), disability (ADA), and state law claims","California: Guz v. Bechtel applies McDonnell Douglas to FEHA claims","Circumstantial evidence framework — direct evidence cases follow different path"]', '[{"section":"Holding","description":"Three-step burden-shifting framework for employment discrimination"},{"section":"Step 1 - Prima Facie","description":"Protected class, qualified, adverse action, inference of discrimination"},{"section":"Step 2 - Legitimate Reason","description":"Employer articulates nondiscriminatory reason for action"},{"section":"Step 3 - Pretext","description":"Plaintiff shows reason is pretextual or discriminatory motive more likely"},{"section":"Application","description":"Applies to Title VII, ADEA, ADA, and FEHA claims via circumstantial evidence"}]', '["EEOC_charge","DFEH_complaint","discrimination_complaint","pretext_evidence","performance_records","comparator_evidence","adverse_action_documentation","termination_letter"]', '["california-labor-employment-audit"]', 'Federal Courts / EEOC / CRD', 1, 1, datetime('now'), datetime('now'));

-- Faragher v. City of Boca Raton — Employer Vicarious Liability for Harassment
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_017', 'REGULIS', 'CASE_LAW', 'US', 'Faragher v. City of Boca Raton, 524 U.S. 775 (1998)', 'Faragher', 'Employer Vicarious Liability for Supervisor Sexual Harassment', 'Employer is vicariously liable for actionable hostile environment sexual harassment by a supervisor with authority over the victim. When no tangible employment action is taken, employer may raise affirmative defense with two elements: (1) employer exercised reasonable care to prevent and correct harassing behavior (e.g., anti-harassment policy and complaint procedure), and (2) plaintiff unreasonably failed to take advantage of preventive or corrective opportunities. Tangible employment action (hiring, firing, demotion) makes employer strictly liable — no affirmative defense available.', '["Employer vicariously liable for supervisor harassment creating hostile environment","Tangible employment action: employer strictly liable, no affirmative defense","No tangible action: employer may raise Faragher/Ellerth affirmative defense","Defense element 1: employer exercised reasonable care to prevent and correct","Defense element 2: employee unreasonably failed to use complaint procedures","Anti-harassment policy and complaint procedure are key to defense","Supervisor defined by authority to take tangible employment actions (Vance v. Ball State)","California: FEHA imposes strict liability for supervisor harassment — no Faragher defense (State Dept. of Health v. Superior Court)"]', '[{"section":"Holding","description":"Employer vicariously liable for supervisor hostile environment harassment"},{"section":"Affirmative Defense","description":"Reasonable care to prevent/correct AND employee failed to use procedures"},{"section":"Tangible Employment Action","description":"No defense available — employer strictly liable"},{"section":"California Distinction","description":"FEHA imposes strict liability — no Faragher/Ellerth defense under state law"},{"section":"Application","description":"Employer must have effective anti-harassment policy and complaint mechanism"}]', '["anti_harassment_policy","complaint_procedure","harassment_complaint","investigation_report","corrective_action","EEOC_charge","DFEH_complaint","training_records"]', '["california-labor-employment-audit"]', 'Federal Courts / EEOC', 1, 1, datetime('now'), datetime('now'));

-- Burlington Industries v. Ellerth — Companion to Faragher
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_018', 'REGULIS', 'CASE_LAW', 'US', 'Burlington Industries, Inc. v. Ellerth, 524 U.S. 742 (1998)', 'Ellerth', 'Unfulfilled Supervisor Threats — Constructive Discharge and Affirmative Defense', 'Companion case to Faragher decided the same day. Supervisor''s unfulfilled threats to deny tangible job benefits constitute harassment, not a tangible employment action. Because no tangible employment action was taken, the Faragher/Ellerth affirmative defense is available. Clarified that tangible employment action requires a significant change in employment status decided by supervisor using official authority. Together with Faragher, created the unified framework for employer liability in supervisor harassment cases.', '["Unfulfilled threats by supervisor are harassment, not tangible employment action","Tangible employment action: significant change in employment status","Must be official act of the enterprise using supervisor authority","Examples: discharge, demotion, undesirable reassignment, reduction in benefits","Affirmative defense available when no tangible action taken","Defense: reasonable care to prevent/correct AND employee failure to use procedures","Employer should promulgate anti-harassment policy with complaint procedure","Together with Faragher establishes unified supervisor harassment framework"]', '[{"section":"Holding","description":"Unfulfilled supervisor threats are harassment, not tangible employment action — affirmative defense available"},{"section":"Tangible Employment Action Defined","description":"Significant change in employment status through official authority of enterprise"},{"section":"Faragher/Ellerth Framework","description":"Unified test: tangible action = strict liability; no tangible action = affirmative defense"},{"section":"Employer Obligation","description":"Promulgate policy, provide complaint mechanism, respond to complaints"},{"section":"Application","description":"Determine whether tangible action taken, then apply appropriate liability standard"}]', '["harassment_complaint","investigation_report","anti_harassment_policy","supervisor_threat_documentation","employment_action_records","EEOC_charge","corrective_action"]', '["california-labor-employment-audit"]', 'Federal Courts / EEOC', 1, 1, datetime('now'), datetime('now'));

-- Garcetti v. Ceballos — Public Employee Speech
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_019', 'REGULIS', 'CASE_LAW', 'US', 'Garcetti v. Ceballos, 547 U.S. 410 (2006)', 'Garcetti', 'Public Employee Speech — No First Amendment Protection for Official Duty Speech', 'When public employees make statements pursuant to their official duties, they are not speaking as citizens for First Amendment purposes, and the Constitution does not insulate their communications from employer discipline. Narrowed the Pickering-Connick balancing test by excluding speech made as part of job duties. Employee must speak as citizen on matter of public concern to receive First Amendment protection. California Labor Code § 1102.5 and Government Code § 8547 et seq. may provide broader whistleblower protections than the First Amendment after Garcetti.', '["Speech made pursuant to official duties not protected by First Amendment","Employee must speak as citizen, not as employee performing job duties","Must address matter of public concern (Connick v. Myers threshold)","If both conditions met: Pickering balancing — employee interest vs. employer efficiency","Formal job description not dispositive — practical inquiry into duties","Garcetti does not apply to academic speech (left open, see Demers v. Austin)","California whistleblower statutes may provide broader protection than First Amendment","Labor Code § 1102.5: protects employees reporting violations to government or persons with authority"]', '[{"section":"Holding","description":"Public employee speech pursuant to official duties not protected by First Amendment"},{"section":"Pickering-Connick Framework","description":"Speech as citizen on public concern → balance employee/employer interests"},{"section":"Official Duties Test","description":"Practical inquiry — not limited to formal job description"},{"section":"Academic Exception","description":"Left open whether Garcetti applies to classroom/scholarship speech"},{"section":"Application","description":"Limits § 1983 First Amendment retaliation claims for whistleblowers acting within job duties"}]', '["whistleblower_complaint","1983_retaliation_claim","job_description","duty_speech_analysis","Pickering_balance","government_employee_discipline","Labor_Code_1102.5_complaint"]', '["california-labor-employment-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- HOUSING — Racial Discrimination, Disparate Impact
-- ═══════════════════════════════════════════════════════════════════════════

-- Jones v. Alfred H. Mayer Co. — 42 USC § 1982
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_020', 'REGULIS', 'CASE_LAW', 'US', 'Jones v. Alfred H. Mayer Co., 392 U.S. 409 (1968)', 'Jones v. Mayer', '42 USC § 1982 — All Racial Discrimination in Property Prohibited', 'Congress has power under the 13th Amendment to prohibit all racial discrimination, private and public, in the sale or rental of property. 42 USC § 1982 (derived from Civil Rights Act of 1866) bars all racial discrimination in property transactions without any exemptions. Unlike the Fair Housing Act (Title VIII), § 1982 has no Mrs. Murphy exemption for owner-occupied small dwellings and no exemption for private clubs or religious organizations. Provides only injunctive relief and compensatory damages — no administrative enforcement mechanism.', '["42 USC § 1982 bars all racial discrimination in property sale and rental","Applies to both private and state actors","No exemptions — no Mrs. Murphy, no private club, no religious organization exception","13th Amendment enforcement power — broader than 14th Amendment state action requirement","Covers sale, rental, lease, and inheritance of real and personal property","Private right of action — direct federal court filing","Remedies: injunctive relief and compensatory damages","No administrative exhaustion requirement — file directly in court","Complements Fair Housing Act but independent cause of action"]', '[{"section":"Holding","description":"§ 1982 prohibits all racial discrimination in property, public and private"},{"section":"13th Amendment","description":"Congressional power to eliminate badges and incidents of slavery"},{"section":"No Exemptions","description":"Unlike FHA — no Mrs. Murphy, private club, or religious exemptions"},{"section":"Remedies","description":"Injunctive relief and compensatory damages via private suit"},{"section":"Application","description":"Direct federal court action — no administrative exhaustion required"}]', '["1982_complaint","housing_discrimination_complaint","fair_housing_complaint","injunction_motion","compensatory_damages_claim","real_property_transaction_records","racial_discrimination_evidence"]', '["california-housing-tenant-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Texas Dept. of Housing v. Inclusive Communities — Disparate Impact
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_021', 'REGULIS', 'CASE_LAW', 'US', 'Texas Dept. of Housing & Community Affairs v. Inclusive Communities Project, Inc., 576 U.S. 519 (2015)', 'Inclusive Communities', 'Fair Housing Act — Disparate Impact Claims Cognizable', 'Disparate impact claims are cognizable under the Fair Housing Act. Plaintiffs need not prove discriminatory intent — showing that a practice causes a disproportionate adverse effect on a protected group is sufficient. Adopted burden-shifting framework: (1) plaintiff demonstrates statistically significant disparate impact, (2) defendant shows policy serves legitimate, nondiscriminatory interest, (3) plaintiff demonstrates less discriminatory alternative. Court emphasized limits: must identify specific policy causing disparity, and statistical disparity alone insufficient without causal connection to challenged practice.', '["Disparate impact claims cognizable under Fair Housing Act","No proof of discriminatory intent required","Statistical evidence of disproportionate effect on protected group","Must identify specific policy or practice causing the disparity","Burden-shifting: impact → legitimate interest → less discriminatory alternative","Robust causality requirement — must connect policy to statistical disparity","Defendant''s legitimate interests given substantial deference","Housing authorities and private developers may be defendants","Consistent with Title VII Griggs v. Duke Power framework"]', '[{"section":"Holding","description":"Disparate impact claims are cognizable under the Fair Housing Act"},{"section":"Burden-Shifting","description":"Impact → legitimate interest → less discriminatory alternative"},{"section":"Causality","description":"Must identify specific policy causing statistical disparity"},{"section":"Limits","description":"Statistical disparity alone insufficient — need causal connection"},{"section":"Application","description":"Applies to zoning, lending, insurance, and housing allocation decisions"}]', '["fair_housing_complaint","statistical_analysis","disparate_impact_study","HUD_complaint","lending_data_analysis","zoning_challenge","housing_allocation_records","less_discriminatory_alternative"]', '["california-housing-tenant-audit"]', 'Federal Courts / HUD', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVACY / 4TH AMENDMENT — Expectation of Privacy, Digital Searches, GPS
-- ═══════════════════════════════════════════════════════════════════════════

-- Katz v. United States — Reasonable Expectation of Privacy
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_022', 'PRIVAXIS', 'CASE_LAW', 'US', 'Katz v. United States, 389 U.S. 347 (1967)', 'Katz', 'Reasonable Expectation of Privacy — 4th Amendment Protects People, Not Places', 'Fourth Amendment protects people, not places. Government wiretap of public phone booth without warrant violated Fourth Amendment even though no physical trespass occurred. Justice Harlan''s concurrence established the two-part "reasonable expectation of privacy" test: (1) person exhibits actual (subjective) expectation of privacy, and (2) that expectation is one society recognizes as reasonable (objective). Overruled Olmstead v. United States (1928) which required physical trespass. Foundation for all modern electronic surveillance law.', '["4th Amendment protects people, not places","No physical trespass required for 4th Amendment violation","Harlan two-part test: subjective expectation + objectively reasonable","Government must obtain warrant before intercepting private communications","Warrant requirement applies even in public spaces where privacy expected","Overruled Olmstead physical trespass doctrine","Foundation for Title III (Wiretap Act) warrant requirements","Exceptions: consent, plain view, exigent circumstances, border search","What a person knowingly exposes to public is not protected"]', '[{"section":"Holding","description":"4th Amendment protects people, not places — wiretap of phone booth requires warrant"},{"section":"Harlan Test","description":"(1) Subjective expectation of privacy, (2) objectively reasonable expectation"},{"section":"Olmstead Overruled","description":"Physical trespass no longer required for 4th Amendment search"},{"section":"Public Exposure","description":"What person knowingly exposes to public not protected"},{"section":"Application","description":"Foundation for all electronic surveillance warrant requirements"}]', '["search_warrant","wiretap_order","suppression_motion","Title_III_application","privacy_expectation_analysis","surveillance_authorization","Katz_motion"]', '["privacy-data-protection-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Riley v. California — Cell Phone Search Warrant Required
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_023', 'PRIVAXIS', 'CASE_LAW', 'US', 'Riley v. California, 573 U.S. 373 (2014)', 'Riley', 'Cell Phone Search — Warrant Required Incident to Arrest', 'Police generally must obtain a warrant before searching a cell phone seized incident to arrest. Cell phones differ in both quantitative and qualitative terms from other objects that might be found on an arrestee — they contain the privacies of life. The search-incident-to-arrest exception to the warrant requirement does not apply to cell phones because neither rationale (officer safety, evidence preservation) justifies warrantless digital searches. Unanimous 9-0 decision. Chief Justice Roberts: "Get a warrant."', '["Warrant required before searching cell phone seized incident to arrest","Search-incident-to-arrest exception does not apply to cell phone data","Cell phones contain vast quantities of personal information — the privacies of life","Neither officer safety nor evidence preservation justifies warrantless cell phone search","Officers may examine physical aspects of phone (remove battery, SIM)","Exigent circumstances exception still applies case-by-case","Remote wiping concern can be addressed by turning phone off or Faraday bag","Applies to all digital devices: smartphones, tablets, similar devices","Unanimous decision — no dissent"]', '[{"section":"Holding","description":"Warrant required to search cell phone data incident to arrest"},{"section":"Rationale","description":"Cell phones contain vast personal data — qualitatively different from physical objects"},{"section":"Officer Safety","description":"Digital data cannot be used as weapon — safety rationale does not apply"},{"section":"Evidence Preservation","description":"Remote wiping addressed by Faraday bag or power-off — not by warrantless search"},{"section":"Application","description":"Get a warrant — applies to all digital device searches incident to arrest"}]', '["search_warrant","cell_phone_search","suppression_motion","Faraday_bag_protocol","digital_evidence_protocol","incident_to_arrest_report","4th_amendment_motion"]', '["privacy-data-protection-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- United States v. Jones — GPS Tracking
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_024', 'PRIVAXIS', 'CASE_LAW', 'US', 'United States v. Jones, 565 U.S. 400 (2012)', 'Jones', 'GPS Tracking — Physical Trespass Plus Information Gathering Is 4th Amendment Search', 'Government''s physical installation of a GPS tracking device on a suspect''s vehicle and subsequent use to monitor movements constitutes a search within meaning of the Fourth Amendment. Majority (Scalia) relied on property-based trespass theory — physical occupation of private property for purpose of obtaining information. Alito concurrence applied Katz reasonable expectation of privacy — long-term GPS monitoring violates reasonable expectations. Sotomayor concurrence introduced mosaic theory: comprehensive surveillance reveals more than sum of individual trips.', '["Physical attachment of GPS device to vehicle is 4th Amendment search","Trespass theory: government physically occupied private property to obtain information","Katz expectation of privacy also supports warrant requirement for GPS (Alito concurrence)","Mosaic theory: aggregate of movements reveals more than individual trips (Sotomayor concurrence)","28-day continuous GPS monitoring without valid warrant violated 4th Amendment","Property-based approach: Katz supplemented, not replaced, common law trespass test","Both trespass and reasonable expectation theories provide independent grounds","Warrant required for GPS device installation and monitoring"]', '[{"section":"Holding","description":"GPS tracker installation on vehicle is 4th Amendment search requiring warrant"},{"section":"Trespass Theory","description":"Physical occupation of private property to obtain information (Scalia majority)"},{"section":"Katz Expectation","description":"Long-term monitoring violates reasonable privacy expectations (Alito concurrence)"},{"section":"Mosaic Theory","description":"Comprehensive surveillance reveals more than sum of individual trips (Sotomayor concurrence)"},{"section":"Application","description":"Warrant required for all GPS tracking device installation and monitoring"}]', '["GPS_warrant","tracking_device_order","suppression_motion","surveillance_records","location_data","4th_amendment_motion","trespass_analysis"]', '["privacy-data-protection-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CRIMINAL PROCEDURE — Exclusionary Rule, Right to Counsel, Jury Selection
-- ═══════════════════════════════════════════════════════════════════════════

-- Mapp v. Ohio — Exclusionary Rule
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_025', 'ADVOCIS', 'CASE_LAW', 'US', 'Mapp v. Ohio, 367 U.S. 643 (1961)', 'Mapp v. Ohio', 'Exclusionary Rule — 4th Amendment Applies to States via 14th Amendment', 'All evidence obtained by searches and seizures in violation of the Fourth Amendment is inadmissible in state court proceedings through the Fourteenth Amendment''s Due Process Clause. Extended Weeks v. United States (1914) federal exclusionary rule to the states. Without the exclusionary rule, the Fourth Amendment would be reduced to a form of words. Deterrence rationale: excluding illegally obtained evidence discourages police misconduct. Exceptions subsequently developed: good faith (Leon), inevitable discovery, independent source, attenuation.', '["Evidence obtained in violation of 4th Amendment inadmissible in state courts","4th Amendment exclusionary rule incorporated against states via 14th Amendment","Overruled Wolf v. Colorado (1949) which declined to extend exclusionary rule to states","Deterrence rationale: exclusion discourages unconstitutional police conduct","Fruit of the poisonous tree: derivative evidence also excluded (Wong Sun)","Good faith exception: evidence obtained in reasonable reliance on warrant (United States v. Leon)","Inevitable discovery exception: evidence would have been found lawfully (Nix v. Williams)","Independent source exception: evidence obtained through independent lawful means","Attenuation exception: sufficient intervening circumstances break causal chain"]', '[{"section":"Holding","description":"Exclusionary rule applies to states — illegally seized evidence inadmissible"},{"section":"14th Amendment","description":"Due Process Clause incorporates 4th Amendment against states"},{"section":"Deterrence","description":"Primary purpose is deterring unconstitutional police conduct"},{"section":"Exceptions","description":"Good faith (Leon), inevitable discovery, independent source, attenuation"},{"section":"Application","description":"Motion to suppress under 4th Amendment — Mapp hearing"}]', '["suppression_motion","Mapp_hearing","search_warrant","search_inventory","exclusionary_rule_brief","good_faith_exception_argument","fruit_of_poisonous_tree_motion"]', '["ca-post-law-enforcement-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Gideon v. Wainwright — Right to Counsel
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_026', 'ADVOCIS', 'CASE_LAW', 'US', 'Gideon v. Wainwright, 372 U.S. 335 (1963)', 'Gideon', 'Right to Counsel — 6th Amendment Applies to States for Felony Cases', 'The Sixth Amendment right to counsel is a fundamental right essential to a fair trial, applicable to the states through the Fourteenth Amendment. Any person charged with a felony who cannot afford an attorney must be provided one by the state. Overruled Betts v. Brady (1942) which applied case-by-case "special circumstances" test. Later extended to misdemeanors resulting in actual imprisonment (Argersinger v. Hamlin, 1972) and suspended sentences (Alabama v. Shelton, 2002). Foundation for the public defender system.', '["6th Amendment right to counsel is fundamental right applicable to states via 14th Amendment","State must provide attorney to felony defendants who cannot afford one","Overruled Betts v. Brady special circumstances approach","Extended to misdemeanors with actual imprisonment (Argersinger v. Hamlin)","Extended to suspended sentences (Alabama v. Shelton)","Right attaches at all critical stages of prosecution","Ineffective assistance of counsel claim if representation inadequate (Strickland v. Washington)","Foundation for public defender systems nationwide","Applies in juvenile delinquency proceedings (In re Gault)"]', '[{"section":"Holding","description":"Right to appointed counsel in felony cases — fundamental right via 14th Amendment"},{"section":"Overruled","description":"Betts v. Brady case-by-case approach replaced with categorical rule"},{"section":"Scope","description":"Felonies (Gideon), misdemeanors with imprisonment (Argersinger), suspended sentences (Shelton)"},{"section":"Critical Stages","description":"Right attaches at arraignment, preliminary hearing, trial, sentencing, appeal"},{"section":"Application","description":"State must provide counsel — foundation for public defender system"}]', '["indigency_declaration","counsel_appointment","public_defender_assignment","Faretta_waiver","ineffective_assistance_claim","6th_amendment_motion","habeas_petition"]', '["victim-rights-marsys-law-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Batson v. Kentucky — Race-Based Peremptory Challenges
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_027', 'ADVOCIS', 'CASE_LAW', 'US', 'Batson v. Kentucky, 476 U.S. 79 (1986)', 'Batson', 'Race-Based Peremptory Challenges Violate Equal Protection', 'The Equal Protection Clause prohibits prosecutors from using peremptory challenges to exclude jurors on account of race. Three-step framework: (1) defendant establishes prima facie case of racial discrimination in jury selection, (2) burden shifts to prosecution to offer race-neutral explanation, (3) court determines whether explanation is pretextual. Extended to defense counsel (Georgia v. McCollum), civil cases (Edmonson v. Leesville Concrete), and gender (J.E.B. v. Alabama). California: People v. Wheeler (1978) reached similar result under state constitution.', '["Race-based peremptory challenges violate Equal Protection Clause","Three-step framework: prima facie case → race-neutral explanation → pretext determination","Prima facie case: pattern of strikes + inference of discrimination","Race-neutral explanation: need not be persuasive, but must be facially valid","Court makes ultimate determination of discriminatory intent","Extended to defense peremptory challenges (Georgia v. McCollum)","Extended to civil cases (Edmonson v. Leesville Concrete)","Extended to gender-based strikes (J.E.B. v. Alabama)","California: Wheeler/Batson motion under state constitution"]', '[{"section":"Holding","description":"Race-based peremptory challenges violate Equal Protection"},{"section":"Step 1","description":"Prima facie case — pattern of strikes raising inference of discrimination"},{"section":"Step 2","description":"Race-neutral explanation — facially valid reason required"},{"section":"Step 3","description":"Pretext determination — court evaluates genuineness of explanation"},{"section":"Extensions","description":"Defense (McCollum), civil (Edmonson), gender (J.E.B.)"},{"section":"Application","description":"Batson/Wheeler motion during jury selection — contemporaneous objection"}]', '["Batson_motion","Wheeler_motion","jury_selection_records","peremptory_challenge_log","voir_dire_transcript","race_neutral_explanation","jury_composition_analysis"]', '["victim-rights-marsys-law-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- POLICE / QUALIFIED IMMUNITY — Deadly Force, Immunity Sequence
-- ═══════════════════════════════════════════════════════════════════════════

-- Tennessee v. Garner — Deadly Force
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_028', 'ADVOCIS', 'CASE_LAW', 'US', 'Tennessee v. Garner, 471 U.S. 1 (1985)', 'Tennessee v. Garner', 'Deadly Force — Unconstitutional Unless Suspect Poses Significant Threat', 'Use of deadly force to prevent escape of a fleeing suspect violates the Fourth Amendment unless the officer has probable cause to believe the suspect poses a significant threat of death or serious physical injury to the officer or others. Struck down common-law fleeing felon rule permitting deadly force against any fleeing felon. Where feasible, officer must give warning before using deadly force. Deadly force is a seizure subject to Fourth Amendment reasonableness analysis.', '["Deadly force to prevent escape is a 4th Amendment seizure","Unconstitutional unless suspect poses significant threat of death or serious injury","Probable cause required to believe suspect is dangerous","Common-law fleeing felon rule struck down as unconstitutional","Warning must be given where feasible before using deadly force","Applies to all law enforcement officers — federal, state, local","Must consider whether suspect is actively dangerous vs. merely fleeing","Deadly force not justified solely because suspect committed felony","Balancing: nature of intrusion vs. government interests"]', '[{"section":"Holding","description":"Deadly force to prevent escape unconstitutional unless suspect poses significant threat of death or serious injury"},{"section":"Fleeing Felon Rule","description":"Common-law rule permitting deadly force against any fleeing felon struck down"},{"section":"Warning Requirement","description":"Where feasible, must warn before using deadly force"},{"section":"4th Amendment","description":"Deadly force is seizure subject to reasonableness analysis"},{"section":"Application","description":"Officer must have probable cause suspect poses threat of death or serious physical injury"}]', '["use_of_force_report","officer_involved_shooting_report","1983_complaint","deadly_force_policy","body_camera_footage","witness_statements","internal_affairs_investigation","autopsy_report"]', '["ca-post-law-enforcement-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Pearson v. Callahan — Qualified Immunity Sequence
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_029', 'ADVOCIS', 'CASE_LAW', 'US', 'Pearson v. Callahan, 555 U.S. 223 (2009)', 'Pearson', 'Qualified Immunity — Courts May Skip Constitutional Violation Question', 'Modified the mandatory two-step sequence from Saucier v. Katz (2001) for qualified immunity analysis. Courts now have discretion to address either prong first: (1) whether facts show constitutional violation, or (2) whether the right was clearly established at time of conduct. Under Saucier, courts had to decide the constitutional question first. Pearson recognized this rigidity sometimes forced courts to decide difficult constitutional questions unnecessarily. Qualified immunity shields government officials from civil damages liability unless their conduct violates clearly established statutory or constitutional rights.', '["Qualified immunity protects government officials from civil damages unless right clearly established","Two-prong test: (1) constitutional violation occurred, (2) right was clearly established","Courts may address either prong first — no mandatory sequence (modified Saucier)","Clearly established: existing precedent places constitutional question beyond debate","Do not need case directly on point — but existing precedent must provide fair warning","Qualified immunity is immunity from suit, not merely immunity from damages","Should be resolved at earliest possible stage — typically summary judgment","Applies to individual capacity suits — not official capacity or municipal liability"]', '[{"section":"Holding","description":"Courts may grant qualified immunity without deciding if constitutional violation occurred"},{"section":"Modified Saucier","description":"Discretion to address either prong first — no mandatory sequence"},{"section":"Clearly Established","description":"Existing precedent must place constitutional question beyond debate"},{"section":"Policy","description":"Qualified immunity is immunity from suit — resolved early in litigation"},{"section":"Application","description":"§ 1983 defendants may win on clearly-established prong without court deciding merits"}]', '["qualified_immunity_motion","summary_judgment","1983_complaint","clearly_established_law_brief","case_law_research","motion_to_dismiss","interlocutory_appeal"]', '["ca-post-law-enforcement-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- DUE PROCESS — Procedural Balancing, Pre-Termination Hearing
-- ═══════════════════════════════════════════════════════════════════════════

-- Mathews v. Eldridge — Three-Factor Balancing Test
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_030', 'ADVOCIS', 'CASE_LAW', 'US', 'Mathews v. Eldridge, 424 U.S. 319 (1976)', 'Mathews v. Eldridge', 'Procedural Due Process — Three-Factor Balancing Test', 'Established the three-factor balancing test for determining what process is due before the government deprives a person of a protected interest. Factor 1: the private interest affected by the official action. Factor 2: the risk of erroneous deprivation through current procedures, and probable value of additional procedural safeguards. Factor 3: the government''s interest, including fiscal and administrative burdens of additional procedures. Held that disability benefits could be terminated without pre-termination hearing (distinguishing Goldberg welfare benefits). Applied universally to determine procedural due process requirements.', '["Three-factor balancing test for procedural due process","Factor 1: private interest affected by government action","Factor 2: risk of erroneous deprivation and value of additional safeguards","Factor 3: government interest including administrative burden","Due process is flexible — not fixed set of procedures for all situations","Must have protected liberty or property interest as threshold","Property interest: legitimate claim of entitlement (Roth)","Liberty interest: freedom from bodily restraint, reputation-plus","Applied to determine what process due — not whether process due"]', '[{"section":"Holding","description":"Three-factor balancing test determines what process is constitutionally required"},{"section":"Factor 1","description":"Private interest: nature and weight of individual interest affected"},{"section":"Factor 2","description":"Risk of error: probability of erroneous deprivation and value of safeguards"},{"section":"Factor 3","description":"Government interest: fiscal and administrative burden of additional procedures"},{"section":"Application","description":"Universal test for procedural due process — applied to benefits, employment, liberty, property"}]', '["due_process_motion","Mathews_balancing_analysis","administrative_hearing_request","property_interest_analysis","liberty_interest_analysis","procedural_safeguards_brief","1983_due_process_complaint"]', '["victim-rights-marsys-law-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));

-- Goldberg v. Kelly — Pre-Termination Hearing
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_031', 'ADVOCIS', 'CASE_LAW', 'US', 'Goldberg v. Kelly, 397 U.S. 254 (1970)', 'Goldberg v. Kelly', 'Welfare Benefits — Pre-Termination Hearing Required by Due Process', 'Due process requires that welfare recipients receive an evidentiary hearing before termination of benefits. Welfare benefits are a statutory entitlement — not mere privilege — creating a property interest protected by the Due Process Clause. Minimum procedural requirements: timely and adequate notice of reasons for termination, opportunity to appear and present evidence orally, right to confront and cross-examine adverse witnesses, right to retain counsel, decision based solely on evidence at hearing, statement of reasons and evidence relied upon, impartial decision-maker.', '["Pre-termination evidentiary hearing required before welfare benefits cut off","Welfare benefits are statutory entitlement creating property interest","Due process requires: timely and adequate notice of reasons","Right to appear and present evidence orally — not just written submissions","Right to confront and cross-examine adverse witnesses","Right to retain counsel (not right to appointed counsel)","Impartial decision-maker required","Decision based solely on legal rules and evidence at hearing","Written statement of reasons and evidence relied upon","Brutal need: eligible recipients may lack means to survive pending post-termination hearing"]', '[{"section":"Holding","description":"Due process requires evidentiary hearing before termination of welfare benefits"},{"section":"Property Interest","description":"Welfare benefits are statutory entitlement, not mere privilege"},{"section":"Minimum Procedures","description":"Notice, oral hearing, confrontation, counsel, impartial decision-maker, written reasons"},{"section":"Brutal Need","description":"Recipients on margin of subsistence — cannot wait for post-termination remedy"},{"section":"Application","description":"Template for pre-deprivation hearing requirements in government benefits"}]', '["pre_termination_notice","administrative_hearing_request","due_process_complaint","benefits_appeal","confrontation_demand","1983_complaint","welfare_hearing_decision","written_reasons_demand"]', '["victim-rights-marsys-law-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- CONSTITUTIONAL / CIVIL RIGHTS — Bivens, Pleading Standards, Marriage
-- ═══════════════════════════════════════════════════════════════════════════

-- Bivens v. Six Unknown Named Agents — Federal Officer Damages
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_032', 'ADVOCIS', 'CASE_LAW', 'US', 'Bivens v. Six Unknown Named Agents of Federal Bureau of Narcotics, 403 U.S. 388 (1971)', 'Bivens', 'Implied Damages Action Against Federal Officers — Federal § 1983 Equivalent', 'Recognized an implied private cause of action for damages against federal officers who violate constitutional rights. Federal equivalent of 42 USC § 1983 (which applies only to state actors). Originally applied to Fourth Amendment unreasonable search and seizure. Extended to Fifth Amendment due process (Davis v. Passman, 1979) and Eighth Amendment cruel and unusual punishment (Carlson v. Green, 1980). Supreme Court has since sharply limited Bivens expansion — refusing new contexts in Ziglar v. Abbasi (2017), Hernandez v. Mesa (2020), and Egbert v. Boule (2022).', '["Implied damages action against federal officers for constitutional violations","Federal equivalent of § 1983 — fills gap because § 1983 applies only to state actors","Originally recognized for 4th Amendment (Bivens)","Extended to 5th Amendment due process (Davis v. Passman)","Extended to 8th Amendment cruel and unusual punishment (Carlson v. Green)","Supreme Court has sharply limited expansion since 1980","Ziglar v. Abbasi (2017): new-context test, special factors counseling hesitation","Egbert v. Boule (2022): nearly closed door to new Bivens contexts","Qualified immunity defense available to federal officers","FTCA alternative remedy may foreclose Bivens claim"]', '[{"section":"Holding","description":"Implied cause of action for damages against federal officers violating constitutional rights"},{"section":"Three Recognized Contexts","description":"4th Amendment (Bivens), 5th Amendment (Davis), 8th Amendment (Carlson)"},{"section":"New Context Limitation","description":"Court refuses extension to new contexts — Abbasi, Hernandez, Egbert"},{"section":"Special Factors","description":"Alternative remedies or special factors counsel against new Bivens actions"},{"section":"Application","description":"Very limited — practically restricted to three recognized contexts"}]', '["Bivens_complaint","federal_officer_damages","4th_amendment_claim","qualified_immunity_defense","FTCA_claim","motion_to_dismiss","new_context_analysis"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Ashcroft v. Iqbal — Plausibility Pleading Standard
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_033', 'ADVOCIS', 'CASE_LAW', 'US', 'Ashcroft v. Iqbal, 556 U.S. 662 (2009)', 'Iqbal', 'Plausibility Pleading Standard — Complaint Must Be Facially Plausible', 'To survive a motion to dismiss under Rule 12(b)(6), a complaint must contain factual allegations sufficient to state a claim that is plausible on its face — not merely conceivable. Extended Bell Atlantic Corp. v. Twombly (2007) plausibility standard from antitrust to all civil actions. Two-step analysis: (1) identify conclusory allegations not entitled to presumption of truth, (2) determine whether remaining factual allegations plausibly state a claim. Threadbare recitals of elements supported by conclusory statements are insufficient. Replaced Conley v. Gibson''s "no set of facts" standard.', '["Complaint must state claim plausible on its face — not merely conceivable","Extends Twombly plausibility standard to all civil cases","Two-step analysis: strip conclusory allegations, assess remaining facts for plausibility","Conclusory allegations not entitled to presumption of truth","Factual allegations accepted as true for purposes of motion to dismiss","Plausibility: more than sheer possibility, less than probability","Context-specific analysis drawing on judicial experience and common sense","Replaced Conley v. Gibson ''no set of facts'' standard","Applies to all civil complaints in federal court"]', '[{"section":"Holding","description":"Complaint must state facially plausible claim — extends Twombly to all civil cases"},{"section":"Two-Step Analysis","description":"(1) Identify conclusory allegations, (2) assess factual plausibility of remaining allegations"},{"section":"Plausibility","description":"More than sheer possibility defendant acted unlawfully — must be plausible"},{"section":"Conclusory Allegations","description":"Threadbare recitals of elements are not entitled to truth presumption"},{"section":"Application","description":"Standard for all Rule 12(b)(6) motions to dismiss in federal court"}]', '["complaint","motion_to_dismiss","12b6_motion","amended_complaint","plausibility_analysis","Twombly_Iqbal_brief","factual_allegations","opposition_to_MTD"]', '["victim-rights-marsys-law-audit"]', 'Federal Courts', 1, 1, datetime('now'), datetime('now'));

-- Obergefell v. Hodges — Marriage Equality
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_case_034', 'ADVOCIS', 'CASE_LAW', 'US', 'Obergefell v. Hodges, 576 U.S. 644 (2015)', 'Obergefell', 'Same-Sex Marriage — Fundamental Right Under 14th Amendment', 'The fundamental right to marry is guaranteed to same-sex couples under the Due Process and Equal Protection Clauses of the Fourteenth Amendment. States must both license same-sex marriages and recognize same-sex marriages performed in other states. Four principles supporting the right: (1) personal autonomy in intimate choices, (2) marriage supports a union of committed individuals unlike any other, (3) marriage safeguards children and families, (4) marriage is keystone of social order. 5-4 decision (Kennedy majority). Full faith and credit requires interstate recognition.', '["Same-sex couples have fundamental right to marry under 14th Amendment","Due Process and Equal Protection Clauses both support the right","States must license same-sex marriages","States must recognize same-sex marriages performed in other jurisdictions","Four principles: autonomy, unique union, safeguarding children, social order keystone","Marriage is fundamental right — not merely a privilege","Cannot deny fundamental right based on sexual orientation","All marital benefits and obligations extend equally to same-sex couples","Full faith and credit: interstate recognition required"]', '[{"section":"Holding","description":"Same-sex marriage is fundamental right under Due Process and Equal Protection"},{"section":"Four Principles","description":"Autonomy, unique committed union, safeguarding children/families, social order keystone"},{"section":"Licensing","description":"States must license same-sex marriages"},{"section":"Recognition","description":"States must recognize same-sex marriages from other jurisdictions"},{"section":"Application","description":"All marital rights, benefits, and obligations apply equally to same-sex married couples"}]', '["marriage_license","marriage_certificate","dissolution_petition","adoption_petition","benefits_application","discrimination_complaint","equal_protection_claim","recognition_demand"]', '["victim-rights-marsys-law-audit"]', 'Federal/State Courts', 1, 1, datetime('now'), datetime('now'));
