-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 11
-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS expansion: Identity theft (CA + federal), CFAA, computer fraud,
-- wiretapping, surveillance, stalking, elder abuse, ransomware.
-- Generated: March 18, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Identity Theft (California)
-- ═══════════════════════════════════════════════════════════════════════════

-- PC § 530.5(a) — Using Personal Identifying Information
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_008', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 530.5(a)', 'PC § 530.5(a)', 'Identity Theft — Willful Use of Personal Identifying Information', 'Prohibits every person from willfully obtaining personal identifying information of another person and using that information for any unlawful purpose, including to obtain or attempt to obtain credit, goods, services, real property, or medical information without the consent of that person. Wobbler offense — punishable as misdemeanor or felony with up to three years in state prison and fine up to $10,000.', '["Willful obtaining of personal identifying information","Use for any unlawful purpose without consent","Includes obtaining credit, goods, services, real property, medical information","Wobbler — misdemeanor or felony","Felony: 16 months, 2, or 3 years state prison","Fine up to $10,000","Each unauthorized use may constitute separate offense","Personal identifying information includes name, SSN, DOB, address, DL number, bank accounts, credit card numbers"]', '[{"section":"530.5(a)","description":"Core prohibition — willful use of personal identifying information for unlawful purpose"},{"section":"530.5(e)","description":"Sentencing — may be punished as misdemeanor or felony"}]', '["identity_theft_report","police_report","credit_report","fraud_affidavit","financial_statement","bank_records"]', '["identity-theft-fraud-audit"]', 'California DOJ / County District Attorney', 1, 1, datetime('now'), datetime('now'));

-- PC § 530.5(c) — Acquiring or Retaining Personal Identifying Information
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_009', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 530.5(c)(1)-(3)', 'PC § 530.5(c)', 'Identity Theft — Acquiring or Retaining Personal Identifying Information', 'Prohibits acquiring or retaining possession of personal identifying information of another with the intent to defraud. Subdivision (c)(1) criminalizes acquisition with intent to defraud; (c)(2) criminalizes acquisition or retention of personal identifying information of 10 or more persons; (c)(3) criminalizes trafficking in personal identifying information. Each is a wobbler offense.', '["Acquiring personal identifying information with intent to defraud","Retaining possession of personal identifying information with intent to defraud","10+ persons threshold triggers enhanced provisions under (c)(2)","Selling, transferring, or conveying personal identifying information with knowledge of unlawful use under (c)(3)","Wobbler — misdemeanor or felony for each subdivision","Felony: 16 months, 2, or 3 years state prison","Intent to defraud is required element"]', '[{"section":"530.5(c)(1)","description":"Acquiring or retaining PII with intent to defraud"},{"section":"530.5(c)(2)","description":"Acquiring or retaining PII of 10+ persons"},{"section":"530.5(c)(3)","description":"Selling, transferring, or conveying PII for unlawful use"}]', '["identity_theft_report","police_report","data_breach_records","digital_forensics_report","financial_records"]', '["identity-theft-fraud-audit"]', 'California DOJ / County District Attorney', 1, 1, datetime('now'), datetime('now'));

-- PC § 530.5(d) — Internet/Email Identity Theft
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_010', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 530.5(d)', 'PC § 530.5(d)', 'Identity Theft — Internet or Email Fraud', 'Prohibits willfully obtaining personal identifying information of another and using it to create, operate, or maintain a website, e-mail address, or social media account for the purpose of committing fraud or engaging in unlawful activity. Specifically targets online impersonation, phishing, and digital identity fraud schemes.', '["Willful obtaining of personal identifying information","Use to create or maintain website, email, or social media account","Purpose must be to commit fraud or unlawful activity","Includes phishing, online impersonation, and spoofed accounts","Wobbler — misdemeanor or felony","Felony: 16 months, 2, or 3 years state prison","Fine up to $10,000"]', '[{"section":"530.5(d)","description":"Creating or maintaining online accounts using stolen PII for fraud"},{"section":"530.5(e)","description":"Sentencing provisions"}]', '["identity_theft_report","police_report","email_records","website_records","social_media_records","digital_forensics_report"]', '["identity-theft-fraud-audit"]', 'California DOJ / County District Attorney', 1, 1, datetime('now'), datetime('now'));

-- PC § 530.6 — Identity Theft Victim Rights
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_011', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 530.6', 'PC § 530.6', 'Identity Theft Victim Rights — Law Enforcement Report', 'Establishes the right of identity theft victims to initiate a law enforcement investigation. A person who has learned or reasonably suspects that their personal identifying information has been unlawfully used may initiate a police report with their local law enforcement agency. The agency is required to take the report and provide the victim with a copy. The report may be filed in the jurisdiction where the victim resides.', '["Victim may initiate law enforcement report in jurisdiction of residence","Law enforcement agency shall take the report and provide copy to victim","Report may be filed regardless of where the identity theft occurred","Law enforcement shall not refuse to take report","Victim entitled to copy of the report","Report serves as basis for credit bureau disputes and creditor claims","Jurisdiction of residence — not limited to where crime occurred"]', '[{"section":"530.6(a)","description":"Right to file identity theft police report in jurisdiction of residence"},{"section":"530.6(b)","description":"Law enforcement duty to take report and provide copy"},{"section":"530.6(c)","description":"Report available for use with credit bureaus and creditors"}]', '["police_report","identity_theft_affidavit","victim_declaration","credit_dispute_letter","FTC_identity_theft_report"]', '["identity-theft-fraud-audit"]', 'Local Law Enforcement / California DOJ', 1, 1, datetime('now'), datetime('now'));

-- CC § 1785.11.2 — Credit Report Security Freeze
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_012', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1785.11.2', 'CC § 1785.11.2', 'Identity Theft — Credit Report Security Freeze', 'Allows any consumer to place a security freeze on their credit report by making a request to a consumer credit reporting agency. Once placed, the agency may not release the report without the consumer''s express authorization. Identity theft victims are entitled to a free freeze. The freeze must be placed within 3 business days of receiving the request and lifted within 3 business days of receiving a valid request to remove.', '["Consumer may place security freeze on credit report","Agency may not release frozen report without express authorization","Identity theft victims entitled to free freeze placement","Freeze placed within 3 business days of request","Temporary lift within 3 business days of request","Written confirmation of freeze required","PIN or password must be provided for freeze management","Violations subject to civil penalties"]', '[{"section":"1785.11.2(a)","description":"Right to place security freeze on credit report"},{"section":"1785.11.2(b)","description":"Agency prohibition on releasing frozen report"},{"section":"1785.11.2(d)","description":"3 business day placement requirement"},{"section":"1785.11.2(j)","description":"Free freeze for identity theft victims"}]', '["credit_freeze_request","credit_report","identity_theft_report","freeze_confirmation","PIN_documentation"]', '["identity-theft-fraud-audit"]', 'California Attorney General / FTC', 1, 1, datetime('now'), datetime('now'));

-- SB 1047 / PUC § 2889.5 — SIM Swap Prevention
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_013', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Pub. Util. Code § 2889.5', 'PUC § 2889.5', 'SIM Swap Fraud Prevention — Wireless Carrier Obligations', 'Requires wireless telephone service providers to implement safeguards against unauthorized SIM swaps and port-out fraud. Carriers must authenticate subscriber identity before completing a SIM swap or number transfer. Enacted via SB 1047 to address the growing threat of SIM swap attacks used to intercept two-factor authentication, steal cryptocurrency, and facilitate identity theft.', '["Wireless carriers must verify subscriber identity before SIM swap","Authentication required before number port-out","Carriers must provide notification to subscriber upon SIM change","Customer may request additional security measures","Carriers must maintain records of SIM swap requests","Failure to comply subjects carrier to enforcement action","Subscribers may designate authorized contacts for account changes"]', '[{"section":"2889.5(a)","description":"Carrier duty to authenticate before SIM swap"},{"section":"2889.5(b)","description":"Subscriber notification upon SIM change"},{"section":"2889.5(c)","description":"Customer opt-in for enhanced security measures"},{"section":"2889.5(d)","description":"Carrier record-keeping requirements"}]', '["SIM_swap_complaint","carrier_records","phone_records","authentication_logs","fraud_report","account_activity_records"]', '["identity-theft-fraud-audit"]', 'California PUC / FCC', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Identity Theft (Federal)
-- ═══════════════════════════════════════════════════════════════════════════

-- 18 USC § 1028 — Federal Identity Theft
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_014', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 1028', '18 USC § 1028', 'Federal Identity Theft — Fraud and Related Activity in Connection with Identification Documents', 'Comprehensive federal statute criminalizing fraud and related activity involving identification documents, authentication features, and false identification documents. Prohibits knowingly producing, transferring, or possessing with intent to defraud an identification document, authentication feature, or false identification document. Penalties range up to 15 years imprisonment, or 20-30 years if used in connection with drug trafficking, violent crime, or international terrorism.', '["Producing identification document or authentication feature without authority","Transferring identification document knowing it was stolen or produced without authority","Possessing with intent to defraud five or more identification documents","Possessing identification document not rightfully issued for that person","Producing, transferring, or possessing document-making implement","Possessing, using, or transferring means of identification of another person","Enhanced penalties for connection to drug trafficking or violent crime","Up to 15 years base; 20 years if facilitating drug trafficking; 30 years if facilitating terrorism"]', '[{"section":"1028(a)(1)","description":"Producing identification document without authority"},{"section":"1028(a)(5)","description":"Possessing document-making implements"},{"section":"1028(a)(7)","description":"Possessing, transferring, or using means of identification of another"},{"section":"1028(b)","description":"Penalties — graduated by offense type and connection to other crimes"},{"section":"1028(d)","description":"Definitions — means of identification, identification document"}]', '["federal_indictment","FBI_report","identity_theft_complaint","financial_records","forged_documents","digital_forensics_report"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney', 0, 1, datetime('now'), datetime('now'));

-- 18 USC § 1028A — Aggravated Identity Theft
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_015', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 1028A', '18 USC § 1028A', 'Aggravated Identity Theft — Mandatory Consecutive Sentence', 'Imposes a mandatory consecutive sentence of 2 years imprisonment (5 years for terrorism offenses) for anyone who, during and in relation to any enumerated felony, knowingly transfers, possesses, or uses the means of identification of another person without lawful authority. The sentence must run consecutively to any other term of imprisonment — it cannot be served concurrently. Court may not place defendant on probation for this offense.', '["Mandatory 2-year consecutive sentence (5 years for terrorism)","Must be during and in relation to enumerated felony","Knowing transfer, possession, or use of means of identification","Of another actual person — not fictitious (Flores-Figueroa v. United States, 556 U.S. 646)","Sentence runs consecutively — cannot run concurrently","No probation permitted","Enumerated felonies include theft, fraud, immigration, passport offenses"]', '[{"section":"1028A(a)(1)","description":"2-year mandatory consecutive sentence for identity theft during enumerated felony"},{"section":"1028A(a)(2)","description":"5-year mandatory consecutive sentence for terrorism-related identity theft"},{"section":"1028A(b)","description":"Consecutive sentence requirement — may not run concurrently"},{"section":"1028A(c)","description":"Enumerated predicate felonies"}]', '["federal_indictment","sentencing_memorandum","identity_theft_complaint","financial_records","digital_forensics_report"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Computer Fraud
-- ═══════════════════════════════════════════════════════════════════════════

-- 18 USC § 1030(a)(2) — CFAA Unauthorized Access
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_016', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 1030(a)(2)', '18 USC § 1030(a)(2)', 'CFAA — Unauthorized Access to Obtain Information', 'Prohibits intentionally accessing a computer without authorization, or exceeding authorized access, and thereby obtaining information from any protected computer. After Van Buren v. United States, 593 U.S. 374 (2021), "exceeds authorized access" means accessing areas of the computer the person is not entitled to access — not misusing information one is authorized to obtain. Covers financial records, government information, and information from any protected computer involved in interstate commerce.', '["Intentionally accessing without authorization or exceeding authorized access","Obtaining information from protected computer","Protected computer includes any computer used in interstate/foreign commerce","Van Buren narrowed scope — must access off-limits areas, not misuse permitted access","Misdemeanor for first offense; felony if for commercial advantage, private financial gain, or furtherance of crime","Felony: up to 5 years (10 years for repeat offense)","Civil cause of action under § 1030(g) for compensatory damages and injunctive relief"]', '[{"section":"1030(a)(2)(A)","description":"Obtaining information from financial institution computer"},{"section":"1030(a)(2)(B)","description":"Obtaining information from US Government computer"},{"section":"1030(a)(2)(C)","description":"Obtaining information from any protected computer"},{"section":"1030(e)(2)","description":"Definition of protected computer"},{"section":"1030(g)","description":"Civil action for damages and injunctive relief"}]', '["digital_forensics_report","access_logs","network_logs","FBI_report","civil_complaint","damages_calculation"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- 18 USC § 1030(a)(5) — CFAA Damage to Computer
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_017', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 1030(a)(5)', '18 USC § 1030(a)(5)', 'CFAA — Knowingly Causing Damage to Protected Computer', 'Prohibits knowingly causing the transmission of a program, information, code, or command that intentionally causes damage to a protected computer. Covers three tiers: (A) knowing transmission causing intentional damage; (B) intentional access causing reckless damage; (C) intentional access causing damage and loss. Damage includes impairment of data integrity, availability, or system operation. Loss aggregation threshold of $5,000 in any one-year period.', '["Knowingly transmitting program/code causing intentional damage","Intentional access causing reckless damage","Intentional access causing damage and loss","Damage includes impairment of integrity or availability of data","Loss threshold: $5,000 aggregate in any 1-year period","Intentional damage: up to 10 years (20 years repeat)","Reckless damage: up to 5 years (20 years repeat)","Includes ransomware, malware, wipers, and DDoS attacks"]', '[{"section":"1030(a)(5)(A)","description":"Knowing transmission causing intentional damage"},{"section":"1030(a)(5)(B)","description":"Intentional access causing reckless damage"},{"section":"1030(a)(5)(C)","description":"Intentional access causing damage and loss"},{"section":"1030(e)(8)","description":"Definition of damage — impairment of integrity or availability"},{"section":"1030(e)(11)","description":"Definition of loss — reasonable cost of responding"}]', '["digital_forensics_report","malware_analysis","incident_response_report","access_logs","damages_assessment","FBI_report"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- 18 USC § 1030(a)(6) — CFAA Trafficking Passwords
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_018', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 1030(a)(6)', '18 USC § 1030(a)(6)', 'CFAA — Trafficking in Computer Passwords', 'Prohibits knowingly and with intent to defraud trafficking in any password or similar information through which a computer may be accessed without authorization, if the trafficking affects interstate or foreign commerce, or the computer is used by or for the Government of the United States. Covers sale, transfer, or distribution of stolen credentials, authentication tokens, and access codes.', '["Knowingly trafficking in passwords or similar access information","Intent to defraud required","Computer may be accessed without authorization through the trafficked information","Must affect interstate or foreign commerce or involve government computer","Includes selling credentials on dark web or criminal forums","Up to 1 year imprisonment (first offense); up to 10 years (repeat offense or government computer)","Similar information includes authentication tokens, SSH keys, API keys, session cookies"]', '[{"section":"1030(a)(6)","description":"Trafficking passwords or similar information for unauthorized computer access"},{"section":"1030(c)(2)","description":"Penalties — misdemeanor first offense, felony for repeat or government computer"},{"section":"1030(g)","description":"Civil action available"}]', '["digital_forensics_report","dark_web_intelligence","credential_dump_records","access_logs","FBI_report"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- CA PC § 502 — Unauthorized Computer Access (California)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_019', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 502', 'PC § 502', 'California Comprehensive Computer Data Access and Fraud Act', 'California''s primary computer crime statute. Prohibits knowingly accessing and without permission altering, damaging, deleting, destroying, or otherwise using any data, computer, computer system, or computer network for the purpose of devising or executing any scheme to defraud, deceive, or extort, or wrongfully controlling or obtaining money, property, or data. Broader than federal CFAA — does not require interstate nexus. Wobbler offense with civil remedy provisions.', '["Knowingly accessing without permission and altering, damaging, or destroying data","Knowingly accessing without permission any computer, system, or network","Disrupting or denying computer services to authorized user","Providing or assisting in providing means of access knowing it will be used for unauthorized purpose","Knowingly introducing contaminant (virus, worm) into any system","Taking, copying, or using data without authorization","No interstate commerce nexus required — state jurisdiction","Wobbler offense — misdemeanor or felony","Civil action for compensatory damages, injunctive relief, and other equitable relief"]', '[{"section":"502(c)(1)","description":"Altering, damaging, deleting, or destroying data"},{"section":"502(c)(2)","description":"Disrupting or denying computer services"},{"section":"502(c)(3)","description":"Unauthorized access to data"},{"section":"502(c)(6)","description":"Knowingly introducing contaminant"},{"section":"502(c)(7)","description":"Unauthorized copying of data"},{"section":"502(e)","description":"Civil remedy — compensatory damages and injunctive relief"}]', '["digital_forensics_report","police_report","access_logs","civil_complaint","damages_calculation","incident_response_report"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA / Private Civil Action', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Wiretapping and Surveillance
-- ═══════════════════════════════════════════════════════════════════════════

-- 18 USC §§ 2510-2522 — Federal Wiretap Act (Title III)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_020', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. §§ 2510-2522', '18 USC §§ 2510-2522', 'Federal Wiretap Act (Title III) — Interception of Communications', 'Title III of the Omnibus Crime Control and Safe Streets Act of 1968. Prohibits the intentional interception, use, or disclosure of wire, oral, or electronic communications. Establishes the exclusionary rule for illegally intercepted communications and provides both criminal penalties and civil cause of action. Requires judicial authorization (super warrant) for law enforcement wiretaps with extensive procedural safeguards including minimization requirements and necessity showing.', '["Prohibits intentional interception of wire, oral, or electronic communications","Prohibits use or disclosure of illegally intercepted communications","Prohibits manufacturing or distributing interception devices","Exclusionary rule — illegally intercepted communications inadmissible","One-party consent exception (federal level)","Law enforcement requires judicial super warrant with probable cause","Minimization requirements for authorized wiretaps","Criminal penalties: up to 5 years imprisonment","Civil damages: statutory damages of $10,000 per violation or actual damages, plus attorney fees","Private right of action under § 2520"]', '[{"section":"2511(1)","description":"Prohibition on interception of communications"},{"section":"2511(2)(d)","description":"One-party consent exception"},{"section":"2515","description":"Exclusionary rule — prohibition of use as evidence"},{"section":"2516","description":"Authorization procedure for law enforcement interception"},{"section":"2518","description":"Judicial order requirements and minimization"},{"section":"2520","description":"Civil action — recovery of damages and attorney fees"}]', '["wiretap_order","surveillance_records","intercepted_communications","civil_complaint","motion_to_suppress","damages_calculation"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- 18 USC §§ 2701-2712 — Stored Communications Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_021', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. §§ 2701-2712', '18 USC §§ 2701-2712', 'Stored Communications Act — Unauthorized Access to Stored Communications', 'Part of the Electronic Communications Privacy Act (ECPA). Prohibits intentional unauthorized access to a facility through which an electronic communication service is provided and thereby obtaining, altering, or preventing authorized access to wire or electronic communications in electronic storage. Governs government access to stored communications held by service providers with tiered requirements: subpoena for basic subscriber info, court order (§ 2703(d)) for transaction records, and search warrant for content.', '["Prohibits unauthorized access to stored wire or electronic communications","Prohibits exceeding authorization to access stored communications","Governs when government may compel disclosure from providers","Subpoena sufficient for basic subscriber information","§ 2703(d) court order for transaction records and logs","Search warrant required for content of communications (Carpenter v. United States)","Provider may voluntarily disclose non-content records in limited circumstances","Criminal penalties: up to 5 years for intentional access; up to 10 years for repeat","Civil damages: statutory $1,000 minimum plus actual damages and attorney fees"]', '[{"section":"2701","description":"Prohibition on unauthorized access to stored communications"},{"section":"2702","description":"Voluntary disclosure by service providers — limitations"},{"section":"2703(a)","description":"Government access to contents — warrant required"},{"section":"2703(c)","description":"Government access to records — subpoena or court order"},{"section":"2703(d)","description":"Court order standard — specific and articulable facts"},{"section":"2707","description":"Civil action — damages, attorney fees, equitable relief"}]', '["subpoena","court_order","search_warrant","provider_records","email_records","account_records","civil_complaint"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- 18 USC §§ 3121-3127 — Pen Register Act
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_022', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. §§ 3121-3127', '18 USC §§ 3121-3127', 'Pen Register Act — Prohibition on Pen Registers and Trap and Trace Devices', 'Prohibits the installation or use of a pen register or trap and trace device without first obtaining a court order. Pen registers record outgoing dialing, routing, addressing, or signaling information (not content). Trap and trace devices capture incoming connection information. Government must certify that information likely to be obtained is relevant to an ongoing criminal investigation. Lower standard than probable cause.', '["Prohibition on installing pen register or trap/trace without court order","Pen register captures outgoing dialing/routing/addressing information","Trap and trace captures incoming connection information","Does not capture content of communications","Government certification standard — relevant to ongoing investigation","Lower than probable cause — relevance standard only","Court order valid for 60 days, renewable","Violation: fine and up to 1 year imprisonment","No private right of action under the statute itself"]', '[{"section":"3121(a)","description":"General prohibition on pen registers and trap/trace without court order"},{"section":"3121(b)","description":"Exceptions — provider operations, consent, law enforcement with order"},{"section":"3122","description":"Application for court order"},{"section":"3123","description":"Issuance of order — 60-day duration, renewals"},{"section":"3127","description":"Definitions — pen register, trap and trace device"}]', '["pen_register_order","phone_records","call_detail_records","routing_information","court_order_application"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney', 0, 1, datetime('now'), datetime('now'));

-- CA PC § 632 — Eavesdropping (Two-Party Consent)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_023', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 632', 'PC § 632', 'California Eavesdropping — Two-Party Consent for Confidential Communications', 'California is a two-party (all-party) consent state. Prohibits any person from using an electronic amplifying or recording device to eavesdrop upon or record a confidential communication without the consent of all parties to the communication. A confidential communication is one carried on in circumstances reasonably indicating that the parties intended it to be confined to the parties. Wobbler offense with civil damages provision of $5,000 per violation or three times actual damages.', '["All-party consent required to record confidential communications","Prohibits eavesdropping by electronic amplifying or recording device","Confidential communication — reasonable expectation it is confined to the parties","Excludes communications made in public gatherings or legislative proceedings","Wobbler — felony punishable by up to 1 year or fine up to $2,500 (or both)","Subsequent convictions: state prison","Civil damages: $5,000 per violation or three times actual damages, whichever is greater","Illegally obtained recordings inadmissible in any proceeding"]', '[{"section":"632(a)","description":"Prohibition on recording confidential communications without all-party consent"},{"section":"632(c)","description":"Definition of confidential communication"},{"section":"632(d)","description":"Exceptions — public gatherings, legislative proceedings"},{"section":"637.2","description":"Civil action — $5,000 statutory or treble actual damages"}]', '["recording","audio_file","surveillance_evidence","civil_complaint","motion_to_suppress","wiretap_evidence"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- CA PC § 632.7 — Recording Cell Phone Communications
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_024', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 632.7', 'PC § 632.7', 'California Recording Confidential Communications — Cellular and Cordless Telephones', 'Extends the two-party consent requirement specifically to cellular and cordless telephone communications. Prohibits any person not a party to the communication from intercepting or receiving, and intentionally recording, a communication transmitted between cellular or cordless telephones, between a cellular/cordless phone and a landline, or between a cellular/cordless phone and a cordless phone. Does not require that the communication be "confidential" — broader protection than § 632.', '["Prohibits interception and recording of cellular/cordless telephone communications","Applies to non-parties who intercept and record","Broader than § 632 — does not require communication be confidential","Covers cell-to-cell, cell-to-landline, and cell-to-cordless communications","Fine up to $2,500 per violation","Civil damages: $5,000 per violation or three times actual damages (§ 637.2)","Illegally obtained recordings inadmissible"]', '[{"section":"632.7(a)","description":"Prohibition on intercepting and recording cellular/cordless communications"},{"section":"632.7(b)","description":"Penalty — fine up to $2,500"},{"section":"637.2","description":"Civil remedy — $5,000 statutory or treble damages"}]', '["phone_records","intercepted_recordings","cell_phone_forensics","civil_complaint","surveillance_records"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- CA LC § 435 — Invasion of Privacy in Workplace
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_025', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Lab. Code § 435', 'LC § 435', 'California Invasion of Privacy — Workplace Monitoring and Surveillance', 'Restricts employer use of audio and video recording in the workplace. Employers may not make audio or video recordings of employees in restrooms, locker rooms, or rooms designated for changing clothes unless authorized by court order. Broader workplace monitoring must comply with PC § 632 two-party consent requirements. California Constitution Art. I § 1 provides an independent privacy right enforceable against private employers.', '["No audio or video recording in restrooms, locker rooms, or changing rooms","Employer monitoring must comply with two-party consent (PC § 632)","California constitutional privacy right applies to private employers","Employees must be notified of monitoring practices","Covert recording of employees disfavored under California law","Violation may support civil suit for invasion of privacy","Workers compensation retaliation protections apply"]', '[{"section":"435(a)","description":"Prohibition on recording in restrooms, locker rooms, changing rooms"},{"section":"435(b)","description":"Employer compliance with eavesdropping statutes"},{"section":"Cal. Const. Art. I § 1","description":"California constitutional right to privacy — applies to private employers"}]', '["workplace_policy","monitoring_notice","surveillance_records","employee_complaint","civil_complaint","DLSE_complaint"]', '["identity-theft-fraud-audit"]', 'California DLSE / Private Civil Action', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Stalking and Harassment
-- ═══════════════════════════════════════════════════════════════════════════

-- CA PC § 646.9 — Stalking
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_026', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 646.9', 'PC § 646.9', 'California Stalking — Willful, Malicious, and Repeated Following or Harassment', 'Criminalizes willfully, maliciously, and repeatedly following or willfully and maliciously harassing another person and making a credible threat with the intent to place that person in reasonable fear for their safety or the safety of their immediate family. Includes cyberstalking via electronic communication devices. Wobbler offense — misdemeanor up to 1 year; felony up to 5 years state prison. Enhanced penalties if committed in violation of protective order or with prior conviction.', '["Willful, malicious, and repeated following or harassing","Credible threat with intent to place victim in reasonable fear","Threat to safety of victim or immediate family","Includes electronic and cyber methods of stalking","Wobbler — misdemeanor (up to 1 year) or felony (up to 5 years)","Enhanced to felony if violation of restraining order","Enhanced if prior stalking conviction","Victim entitled to restraining order","GPS/electronic monitoring as condition of probation"]', '[{"section":"646.9(a)","description":"Core prohibition — following/harassing with credible threat"},{"section":"646.9(b)","description":"Felony if committed in violation of restraining order or injunction"},{"section":"646.9(c)","description":"Felony if prior conviction under this section"},{"section":"646.9(e)","description":"Definition of credible threat — includes electronic communications"},{"section":"646.9(g)","description":"Definition of harasses — course of conduct directed at specific person"}]', '["police_report","restraining_order","threat_documentation","electronic_communications","GPS_data","surveillance_records","victim_statement"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA', 1, 1, datetime('now'), datetime('now'));

-- 18 USC § 2261A — Federal Cyberstalking
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_027', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 2261A', '18 USC § 2261A', 'Federal Cyberstalking — Interstate Stalking and Harassment', 'Federal statute criminalizing use of interactive computer services, electronic communication services, or electronic communication systems of interstate commerce to engage in a course of conduct causing substantial emotional distress or reasonable fear of death or serious bodily injury. Part of the Violence Against Women Act framework. Applies when conduct crosses state lines, uses interstate facilities, or occurs within federal jurisdiction. Penalties up to 5 years; up to life imprisonment if death results.', '["Use of interactive computer service or electronic communication for stalking","Course of conduct causing substantial emotional distress","Course of conduct causing reasonable fear of death or serious bodily injury","Interstate nexus — travel, use of mail, or use of interstate facility","Includes surveillance, monitoring, and cyber harassment","Up to 5 years imprisonment; up to 20 years if bodily injury; life if death results","Mandatory restitution to victim","Federal protective order available"]', '[{"section":"2261A(1)","description":"Travel or conduct with intent to kill, injure, harass, or intimidate"},{"section":"2261A(2)","description":"Use of interactive computer service or electronic communication"},{"section":"2261(b)","description":"Penalties — graduated by harm caused"},{"section":"2264","description":"Mandatory restitution to victim"}]', '["FBI_report","electronic_communications","social_media_records","IP_address_records","victim_statement","federal_complaint","restitution_order"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney', 0, 1, datetime('now'), datetime('now'));

-- CA PC § 647(j)(4) — Revenge Porn
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_028', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 647(j)(4)', 'PC § 647(j)(4)', 'California Nonconsensual Pornography — Revenge Porn', 'Criminalizes intentional distribution of an image of the intimate body part or parts of another identifiable person, or an image of the person engaged in sexual intercourse or other sexual conduct, where the person distributing knows or should know that the depicted person did not consent to the distribution, and the image was created under circumstances where the parties agreed or understood the image would remain private. Misdemeanor with up to 6 months and $1,000 fine; enhanced to up to 1 year for subsequent offenses.', '["Intentional distribution of intimate images without consent","Person depicted must be identifiable","Distributor knew or should have known consent was not given","Image created under circumstances of agreed privacy","Includes distribution via electronic means, social media, websites","Misdemeanor: up to 6 months county jail and/or $1,000 fine","Subsequent offenses: up to 1 year county jail and/or $2,000 fine","Civil remedy available under CC § 1708.85"]', '[{"section":"647(j)(4)(A)","description":"Distribution of intimate image without consent — elements"},{"section":"647(j)(4)(B)","description":"Penalties — misdemeanor, enhanced for repeat offenses"},{"section":"CC § 1708.85","description":"Civil action for nonconsensual pornography — damages and injunctive relief"}]', '["police_report","distributed_images","electronic_communications","website_records","social_media_records","civil_complaint","takedown_request"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA / Private Civil Action', 1, 1, datetime('now'), datetime('now'));

-- CA CC § 1708.86 — Sexually Explicit Deepfakes
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_029', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1708.86', 'CC § 1708.86', 'California Deepfake Civil Action — Sexually Explicit Material', 'Creates a private right of action for any depicted individual whose likeness has been used without consent in sexually explicit deepfake material. Covers digitally altered or AI-generated images or videos that realistically depict a person in sexually explicit conduct they did not actually engage in. Plaintiff may recover economic damages, noneconomic damages, punitive damages, and reasonable attorney fees. Court may issue injunctive relief including takedown orders.', '["Private right of action for nonconsensual sexually explicit deepfake","Covers digitally altered or AI-generated material","Material must realistically depict person in sexually explicit conduct","Person did not actually engage in the depicted conduct","No consent to creation or distribution","Recoverable: economic damages, noneconomic damages, punitive damages","Reasonable attorney fees available","Injunctive relief including takedown orders","Statute of limitations: 3 years from discovery or when should have been discovered"]', '[{"section":"1708.86(a)","description":"Definitions — deepfake, depicted individual, sexually explicit material"},{"section":"1708.86(b)","description":"Cause of action — creation or disclosure without consent"},{"section":"1708.86(c)","description":"Damages — economic, noneconomic, punitive, and attorney fees"},{"section":"1708.86(d)","description":"Injunctive relief — takedown orders"}]', '["deepfake_evidence","AI_generated_content","digital_forensics_report","civil_complaint","takedown_order","damages_calculation"]', '["identity-theft-fraud-audit"]', 'Private Civil Action / California AG', 1, 1, datetime('now'), datetime('now'));

-- CA EC § 20010 — Deepfake in Elections
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_030', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Elec. Code § 20010', 'EC § 20010', 'California Deepfake Prohibition — Election-Related Material', 'Prohibits the distribution of materially deceptive audio or visual media of a candidate for elective office within specified periods before an election with intent to injure the candidate''s reputation or to deceive a voter into voting for or against a candidate. Applies within 60 days of an election. Candidate depicted may seek injunctive relief and damages. Requires disclosure if AI-generated content is used in political advertising.', '["Prohibits distribution of materially deceptive audio or visual media of candidates","Applies within 60 days before election","Intent to injure reputation or deceive voters","Covers AI-generated, manipulated, or deepfaked content","Candidate may seek injunctive relief within 60 days of election","Damages available for violation","Political advertising must disclose AI-generated content","First Amendment considerations — limited to materially deceptive content"]', '[{"section":"20010(a)","description":"Prohibition on materially deceptive media of candidates near election"},{"section":"20010(b)","description":"Injunctive relief for depicted candidate"},{"section":"20010(c)","description":"Definition of materially deceptive audio or visual media"},{"section":"20010(d)","description":"Exceptions — satire, parody, news reporting"}]', '["deepfake_evidence","political_advertisement","AI_generated_content","election_complaint","injunction_motion","digital_forensics_report"]', '["identity-theft-fraud-audit"]', 'California Secretary of State / FPPC / Private Civil Action', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Elder and Financial Abuse
-- ═══════════════════════════════════════════════════════════════════════════

-- CA WIC § 15610.30 — Elder Financial Abuse
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_031', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 15610.30', 'WIC § 15610.30', 'California Elder Financial Abuse — Definition and Elements', 'Defines financial abuse of an elder or dependent adult as occurring when a person or entity takes, secretes, appropriates, obtains, or retains real or personal property of an elder or dependent adult for a wrongful use or with intent to defraud, or both. Also includes taking by undue influence as defined in WIC § 15610.70. An elder is any person 65 years of age or older. A dependent adult is any person between 18 and 64 who has limitations restricting their ability to carry out normal activities.', '["Taking, secreting, appropriating, obtaining, or retaining property","Of an elder (65+) or dependent adult (18-64 with limitations)","For wrongful use or with intent to defraud","Includes taking by undue influence","Property includes real and personal property","Includes assisting in any of the above acts","Wrongful use if person knew or should have known the conduct was likely to be harmful","Bad faith basis for asserting control over property"]', '[{"section":"15610.30(a)(1)","description":"Taking property for wrongful use or with intent to defraud"},{"section":"15610.30(a)(2)","description":"Assisting in taking property for wrongful use or with intent to defraud"},{"section":"15610.30(a)(3)","description":"Taking property by undue influence"},{"section":"15610.30(b)","description":"Definition of wrongful use — knew or should have known conduct likely harmful"},{"section":"15610.30(c)","description":"Bad faith — no good faith belief in rightful claim to property"}]', '["financial_records","bank_statements","property_records","power_of_attorney","trust_documents","APS_report","civil_complaint"]', '["identity-theft-fraud-audit"]', 'California APS / County DA / Private Civil Action (WIC § 15657.5)', 1, 1, datetime('now'), datetime('now'));

-- CA WIC § 15630 — Elder Abuse Mandatory Reporting
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_032', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code § 15630', 'WIC § 15630', 'California Elder Abuse Mandatory Reporting — Mandated Reporters', 'Requires mandated reporters who, in their professional capacity or within the scope of their employment, observe or have knowledge of an incident that reasonably appears to be physical abuse, abandonment, abduction, isolation, financial abuse, or neglect of an elder or dependent adult to report immediately or as soon as practicably possible by telephone to the local adult protective services agency or law enforcement. Written follow-up report within 2 working days. Failure to report is a misdemeanor.', '["Mandated reporters must report known or suspected elder abuse","Immediate telephone report to APS or law enforcement","Written follow-up report within 2 working days","Mandated reporters include health practitioners, care custodians, clergy, financial institutions","Covers physical abuse, neglect, abandonment, financial abuse, isolation","Failure to report: misdemeanor — up to 6 months and/or $1,000 fine","Willful failure resulting in death or great bodily injury: up to 1 year and/or $5,000 fine","Reporter identity confidential","Mandated reporter immunity for good faith reports"]', '[{"section":"15630(a)","description":"Mandated reporter duty — immediate telephone report"},{"section":"15630(b)(1)","description":"Written follow-up report within 2 working days"},{"section":"15630(h)","description":"Failure to report — misdemeanor penalties"},{"section":"15631","description":"Reporter immunity for good faith reports"},{"section":"15633","description":"Confidentiality of reporter identity"}]', '["APS_report","SOC_341_report","mandated_reporter_form","incident_report","medical_records","financial_abuse_documentation"]', '["identity-theft-fraud-audit"]', 'California APS / County DA / California DSS', 0, 1, datetime('now'), datetime('now'));

-- CA PC § 368 — Elder Abuse Enhanced Criminal Penalties
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_033', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 368', 'PC § 368', 'California Elder Abuse — Enhanced Criminal Penalties', 'Establishes enhanced criminal penalties for abuse of elders (65+) and dependent adults. Covers physical abuse, neglect, financial exploitation, and endangerment. Declares that crimes against elders and dependent adults are deserving of special consideration and protection. Theft or embezzlement from an elder carries enhanced penalties: if property exceeds $950, felony with 2, 3, or 4 years state prison. Aggravated sentence enhancements for great bodily injury to victim 70 years or older.', '["Enhanced penalties for crimes against elders 65+ and dependent adults","Physical abuse: up to 1 year (misdemeanor) or 2-4 years (felony)","Causing death: enhanced sentencing","Financial exploitation: enhanced penalties when property exceeds $950","Theft from elder exceeding $950: felony — 2, 3, or 4 years state prison","Great bodily injury to elder 70+: additional 5 years consecutive","Willful causing of unjustified pain or suffering","Permits or causes elder to suffer or be placed in endangering situation","Restitution mandatory"]', '[{"section":"368(b)(1)","description":"Felony elder abuse — circumstances likely to produce great bodily harm or death"},{"section":"368(c)","description":"Misdemeanor elder abuse — not likely to produce great bodily harm or death"},{"section":"368(d)","description":"Theft or embezzlement from elder — enhanced felony if over $950"},{"section":"368(e)","description":"Financial exploitation by caretaker or person in position of trust"},{"section":"368(f)","description":"Sentence enhancement for great bodily injury to victim 70+"}]', '["police_report","APS_report","medical_records","financial_records","bank_statements","criminal_complaint","restitution_order"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- VIGILUS — Ransomware and Emerging Threats
-- ═══════════════════════════════════════════════════════════════════════════

-- CA PC § 523 — Ransomware (Extortion by Threatening Letter)
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_034', 'VIGILUS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 523', 'PC § 523', 'California Ransomware — Extortion by Threatening Letter or Electronic Communication', 'Criminalizes sending threatening letters or electronic communications with intent to extort money or other consideration. Applied to ransomware attacks where perpetrators encrypt victim data and demand payment for decryption keys. Combined with PC § 502 (computer crimes) and PC § 520 (extortion), this provides the statutory framework for prosecuting ransomware attacks under California law. Punishable as extortion — felony with 2, 3, or 4 years state prison.', '["Sending threatening letter or electronic communication","Intent to extort money or other consideration","Includes ransomware demands transmitted electronically","Threat to encrypt, destroy, or withhold access to data","Punishable as extortion under PC § 518-527","Felony: 2, 3, or 4 years state prison","Restitution to victims mandatory","Often charged in conjunction with PC § 502 (computer crimes)"]', '[{"section":"523","description":"Extortion by threatening letter or electronic communication"},{"section":"518","description":"Extortion defined — obtaining property through force or fear"},{"section":"520","description":"Extortion — threat to injure person or property"},{"section":"502","description":"Computer crimes — often charged alongside ransomware"}]', '["ransomware_note","encrypted_data_evidence","bitcoin_payment_records","digital_forensics_report","incident_response_report","police_report"]', '["identity-theft-fraud-audit"]', 'California DOJ / County DA / FBI (if interstate)', 0, 1, datetime('now'), datetime('now'));

-- 18 USC § 1951 — Federal Extortion (Hobbs Act) — Ransomware
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_vig_035', 'VIGILUS', 'FEDERAL_STATUTE', 'US', '18 U.S.C. § 1951', '18 USC § 1951', 'Hobbs Act — Federal Extortion and Robbery Affecting Interstate Commerce', 'Federal statute prohibiting robbery or extortion, or attempted robbery or extortion, that in any way or degree obstructs, delays, or affects commerce or the movement of any article or commodity in commerce. Primary federal tool for prosecuting ransomware attacks that affect interstate commerce. Extortion defined as obtaining property from another through wrongful use of actual or threatened force, violence, or fear, or under color of official right. Felony with up to 20 years imprisonment.', '["Extortion or robbery affecting interstate commerce","Extortion: obtaining property through force, violence, fear, or under color of official right","Robbery: taking property by force or fear","Attempt or conspiracy also criminalized","Interstate commerce nexus — de minimis standard","Applied to ransomware: demanding payment to restore access to data","Up to 20 years imprisonment","Conspiracy: same penalties as substantive offense","Cryptocurrency ransoms sufficient for property element"]', '[{"section":"1951(a)","description":"Prohibition on robbery or extortion affecting commerce — up to 20 years"},{"section":"1951(b)(1)","description":"Definition of robbery — taking by force or fear"},{"section":"1951(b)(2)","description":"Definition of extortion — obtaining property through wrongful force, fear, or color of official right"},{"section":"1951(b)(3)","description":"Definition of commerce — all commerce between states or with foreign nations"}]', '["FBI_report","ransomware_note","cryptocurrency_records","digital_forensics_report","federal_indictment","incident_response_report","damages_assessment"]', '["identity-theft-fraud-audit"]', 'FBI / DOJ / US Attorney', 0, 1, datetime('now'), datetime('now'));
