-- ═══════════════════════════════════════════════════════════════════════════
-- GOVERNING STANDARDS LIBRARY SEED DATA — BATCH 4
-- ═══════════════════════════════════════════════════════════════════════════
-- Real estate fraud, local housing ordinances, labor expansion, CPS expansion
-- Generated: March 17, 2026
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Real Estate Transaction Fraud expansion
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_041', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1053-1059', 'CC §§ 1053+', 'Grant Deeds — Essential Elements', 'Requirements for valid transfer of real property by grant deed in California.', '["Must be in writing (Statute of Frauds)","Grantor must have capacity","Must describe property with certainty","Must be signed by grantor","Must be delivered and accepted"]', '[{"section":"1053","description":"Method of transfer — grant"},{"section":"1054","description":"Contents of a grant"},{"section":"1091","description":"Delivery and acceptance"}]', '["grant_deed","quitclaim_deed","deed_of_trust","property_transfer"]', '["california-real-estate-transaction-fraud-audit"]', 'County Recorder', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_042', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 1624', 'CC § 1624', 'Statute of Frauds — Real Property', 'Real property transfers and contracts must be in writing and signed to be enforceable.', '["Agreements for sale of real property must be written","Leases over one year must be written","Written memorandum sufficient","Part performance doctrine exception"]', '[{"section":"1624(a)(3)","description":"Real property agreements"},{"section":"1624(a)(4)","description":"Leases exceeding one year"}]', '["purchase_agreement","listing_agreement","lease","option_agreement"]', '["california-real-estate-transaction-fraud-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_043', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 2924-2924.19', 'CC §§ 2924+', 'California Foreclosure Procedures', 'Non-judicial and judicial foreclosure requirements including notice, timeline, and borrower protections.', '["Notice of Default and 3-month reinstatement period","Notice of Trustee Sale 20 days before sale","Right to cure before sale","Homeowner Bill of Rights protections","Dual tracking prohibition"]', '[{"section":"2924","description":"Non-judicial foreclosure process"},{"section":"2924.9","description":"Notice requirements"},{"section":"2924.11","description":"Dual tracking prohibition"},{"section":"2924.17","description":"Declaration of compliance"}]', '["notice_of_default","notice_of_sale","deed_of_trust","loan_modification"]', '["california-real-estate-transaction-fraud-audit"]', 'California AG / DFPI', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_044', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 1572-1573', 'CC §§ 1572-1573', 'Actual and Constructive Fraud in Transactions', 'Definitions of actual fraud (intentional deception) and constructive fraud (breach of duty without intent) in California.', '["Actual fraud: suggestion as fact of what is not true","Positive assertion in manner not warranted","Suppression of true facts","Promise without intent to perform","Any artifice to deceive"]', '[{"section":"1572","description":"Actual fraud — 5 categories"},{"section":"1573","description":"Constructive fraud — breach of duty"}]', '["fraud_complaint","rescission_action","real_estate_contract","disclosure"]', '["california-real-estate-transaction-fraud-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_045', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 3439-3439.12', 'UVTA', 'Uniform Voidable Transactions Act', 'Allows creditors to void transfers made with intent to defraud or for less than reasonably equivalent value.', '["Transfer voidable if made with actual intent to defraud","Transfer voidable if for less than reasonably equivalent value while insolvent","11 badges of fraud indicators","4-year statute of limitations (7 for actual fraud)"]', '[{"section":"3439.04","description":"Voidable transfer — actual fraud"},{"section":"3439.05","description":"Voidable transfer — constructive fraud"},{"section":"3439.07","description":"Remedies of creditor"}]', '["property_transfer","deed","fraudulent_conveyance","creditor_claim"]', '["california-real-estate-transaction-fraud-audit"]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_046', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code § 3412', 'CC § 3412', 'Quiet Title Action', 'Action to establish title to real property against adverse claims.', '["Must have interest in the property","Must describe adverse claim","May name unknown defendants","Court determines superiority of title"]', '[{"section":"3412","description":"Right to bring quiet title action"}]', '["quiet_title_complaint","title_report","deed","property_dispute"]', '["california-real-estate-transaction-fraud-audit"]', 'Superior Court of California', 1, 1, datetime('now'), datetime('now'));

-- Real Estate Penal Code provisions
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_047', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 115', 'PC § 115', 'Filing False or Forged Documents', 'Felony to knowingly procure or offer a false or forged instrument to be filed or recorded.', '["Applies to documents filed with public offices","Includes deeds, liens, judgments","Felony: 16 months, 2, or 3 years","Each filing is a separate offense"]', '[{"section":"115(a)","description":"Filing/recording false instrument"},{"section":"115(c)","description":"Grand theft enhancement"}]', '["forged_deed","false_lien","fraudulent_recording","notary_fraud"]', '["california-real-estate-transaction-fraud-audit"]', 'District Attorney', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_048', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 470', 'PC § 470', 'Forgery', 'Forging or counterfeiting various written instruments with intent to defraud.', '["Signing another persons name with intent to defraud","Counterfeiting seal or handwriting","Altering, corrupting, or falsifying any record","Felony: 16 months, 2, or 3 years"]', '[{"section":"470(a)","description":"Forgery of signature"},{"section":"470(b)","description":"Counterfeiting"},{"section":"470(d)","description":"Falsifying records"}]', '["forged_deed","forged_signature","altered_document","counterfeit_document"]', '["california-real-estate-transaction-fraud-audit"]', 'District Attorney', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_049', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 368', 'PC § 368', 'Elder and Dependent Adult Financial Abuse', 'Criminal penalties for financial abuse of elders (65+) and dependent adults.', '["Theft, embezzlement, fraud targeting elders/dependents","Enhanced penalties for crimes against elders","Includes real property fraud","Restitution mandatory"]', '[{"section":"368(d)","description":"Theft from elder — felony"},{"section":"368(e)","description":"Financial abuse of dependent adult"},{"section":"368(f)","description":"Enhanced sentencing"}]', '["elder_abuse_report","financial_exploitation","real_estate_fraud","POA_abuse"]', '["california-real-estate-transaction-fraud-audit"]', 'District Attorney / Adult Protective Services', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_050', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Penal Code § 532', 'PC § 532', 'Theft by False Pretenses', 'Obtaining property by knowingly making false pretenses or representations.', '["Knowingly false representation of fact","Intent to defraud","Victim relied on false representation","Value-based felony/misdemeanor threshold"]', '[{"section":"532(a)","description":"Theft by false pretenses elements"}]', '["fraud_complaint","real_estate_fraud","contract_fraud","identity_theft"]', '["california-real-estate-transaction-fraud-audit"]', 'District Attorney', 0, 1, datetime('now'), datetime('now'));

-- Real Estate licensing/DRE
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_051', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Bus. & Prof. Code §§ 10000-10581', 'DRE Act', 'California Real Estate Law', 'Licensing, regulation, and discipline of real estate brokers and salespersons.', '["License required to sell/list real property","Fiduciary duty to clients","Disclosure requirements","Agency relationship disclosure","Trust fund handling requirements"]', '[{"section":"10176","description":"Grounds for revocation — fraud, misrepresentation"},{"section":"10177","description":"Additional grounds — dishonest dealing"},{"section":"10130","description":"License requirement"},{"section":"10131","description":"Real estate broker activities"}]', '["listing_agreement","purchase_agreement","agency_disclosure","DRE_complaint"]', '["california-real-estate-transaction-fraud-audit"]', 'California DRE', 1, 1, datetime('now'), datetime('now'));

-- Recording requirements
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_052', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Gov. Code §§ 27280-27297', 'GC §§ 27280+', 'Document Recording Requirements', 'Requirements for recording documents affecting real property with the County Recorder.', '["Documents must be acknowledged (notarized)","Must comply with formatting requirements","Documentary transfer tax required","Recorder cannot refuse compliant documents"]', '[{"section":"27280","description":"Recorder acceptance requirements"},{"section":"27287","description":"Notarization requirements for deeds"},{"section":"27297","description":"Identity verification for notarization"}]', '["deed","lien","deed_of_trust","reconveyance","lis_pendens"]', '["california-real-estate-transaction-fraud-audit"]', 'County Recorder', 0, 1, datetime('now'), datetime('now'));

-- Probate Code — estate fraud
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_053', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Prob. Code §§ 850-859', 'Prob §§ 850+', 'Conveyances and Transfers — Estate Claims', 'Permits estates, conservators, and guardians to bring actions regarding property that should be in the estate.', '["Petition to recover property belonging to estate","Action against person who took property by fraud or undue influence","Court may compel reconveyance","Applies to real and personal property"]', '[{"section":"850","description":"Petition for property belonging to estate"},{"section":"859","description":"Double damages for bad faith taking"}]', '["estate_petition","conservatorship","property_recovery","undue_influence"]', '["california-real-estate-transaction-fraud-audit"]', 'Superior Court — Probate Division', 1, 1, datetime('now'), datetime('now'));

-- Revenue & Tax — property transfers
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_054', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Rev. & Tax. Code §§ 11911-11930', 'RTC §§ 11911+', 'Documentary Transfer Tax', 'Tax imposed on transfers of real property, based on value of consideration.', '["$1.10 per $1,000 of value (county)","Additional city tax may apply","Exemptions for certain interfamily transfers","Must be declared on deed"]', '[{"section":"11911","description":"Tax imposed on transfers"},{"section":"11921","description":"Exemptions from tax"},{"section":"11930","description":"City transfer taxes"}]', '["deed","transfer_tax_declaration","title_report"]', '["california-real-estate-transaction-fraud-audit"]', 'County Recorder / FTB', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Local Housing Ordinances
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_055', 'REGULIS', 'STATE_STATUTE', 'CA', 'San Francisco Administrative Code Chapter 37', 'SF Rent Ordinance', 'San Francisco Residential Rent Stabilization and Arbitration Ordinance', 'Rent control protections for tenants in San Francisco including rent increase limits and just cause eviction.', '["Annual allowable rent increase set by Rent Board","16 enumerated just cause eviction grounds","Tenant buyout agreement requirements","Capital improvement passthrough limits","Relocation assistance for no-fault evictions"]', '[{"section":"37.3","description":"Rent limitations"},{"section":"37.9","description":"Just cause eviction requirements"},{"section":"37.9E","description":"Relocation assistance"}]', '["rent_increase_notice","eviction_notice","buyout_agreement","OMI_eviction"]', '["california-housing-tenant-rights-audit"]', 'SF Rent Board', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_056', 'REGULIS', 'STATE_STATUTE', 'CA', 'Los Angeles Municipal Code Chapter XV (LAMC §§ 151.00-155.09)', 'LA RSO', 'Los Angeles Rent Stabilization Ordinance', 'Rent control protections for tenants in Los Angeles including allowable increases and just cause eviction.', '["Annual rent increase limited (3-8%)","12 just cause eviction grounds","Relocation assistance for no-fault evictions","Registration with LAHD required","RSO unit designation on title"]', '[{"section":"151.06","description":"Maximum rent adjustment"},{"section":"151.09","description":"Just cause eviction"},{"section":"151.09.G","description":"Relocation assistance"}]', '["rent_increase_notice","eviction_notice","RSO_registration","relocation_notice"]', '["california-housing-tenant-rights-audit"]', 'LA Housing Department (LAHD)', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_057', 'REGULIS', 'STATE_STATUTE', 'CA', 'Oakland Municipal Code §§ 8.22.010-8.22.810 (Just Cause for Eviction)', 'Oakland JCE', 'Oakland Just Cause for Eviction Ordinance', 'Requires just cause for all residential evictions in Oakland with tenant relocation assistance.', '["Just cause required for all evictions","Tenant right to cure for at-fault evictions","Relocation payments for no-fault evictions","RAP (Rent Adjustment Program) oversight"]', '[{"section":"8.22.300","description":"Just cause requirements"},{"section":"8.22.360","description":"Relocation payments"},{"section":"8.22.070","description":"Rent increase limits"}]', '["eviction_notice","relocation_notice","rent_increase","RAP_petition"]', '["california-housing-tenant-rights-audit"]', 'Oakland RAP', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_058', 'REGULIS', 'STATE_STATUTE', 'CA', 'Berkeley Municipal Code Chapter 13.76', 'Berkeley Rent Board', 'Berkeley Rent Stabilization and Eviction for Good Cause Ordinance', 'Comprehensive rent control including individual rent adjustments, just cause eviction, and tenant protections.', '["Annual general adjustment set by Rent Board","Individual rent adjustment petitions","12 good cause eviction grounds","No eviction during school year for families with children"]', '[{"section":"13.76.050","description":"Rent ceiling adjustments"},{"section":"13.76.130","description":"Good cause for eviction"}]', '["rent_increase","eviction_notice","rent_board_petition","adjustment_decision"]', '["california-housing-tenant-rights-audit"]', 'Berkeley Rent Stabilization Board', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_059', 'REGULIS', 'STATE_STATUTE', 'CA', 'Richmond Municipal Code Chapter 11.100 (Fair Rent, Just Cause for Eviction, and Homeowner Protection Ordinance)', 'Richmond Fair Rent', 'Richmond Fair Rent Ordinance', 'Rent control and just cause eviction protections for Richmond tenants.', '["Annual rent increase limited by CPI","Just cause required for eviction","Rent Board established for administration","Relocation assistance for no-fault evictions"]', '[{"section":"11.100.050","description":"Maximum annual rent increase"},{"section":"11.100.060","description":"Just cause for eviction"}]', '["rent_increase","eviction_notice","rent_board_petition"]', '["california-housing-tenant-rights-audit"]', 'Richmond Rent Board', 1, 1, datetime('now'), datetime('now'));

-- Habitability / Health & Safety
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_060', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Health & Safety Code §§ 17920.3-17920.10', 'HSC §§ 17920+', 'Substandard Building Standards', 'Defines conditions that make a building substandard and subject to enforcement action.', '["Inadequate sanitation","Structural hazards","Nuisance conditions","Lead paint hazards","Mold and moisture","Infestation"]', '[{"section":"17920.3","description":"Conditions constituting substandard building"},{"section":"17920.10","description":"Mold remediation standards"}]', '["habitability_complaint","code_violation","inspection_report","repair_request"]', '["california-housing-tenant-rights-audit"]', 'Local Code Enforcement / HCD', 1, 1, datetime('now'), datetime('now'));

-- Section 8 federal
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_061', 'REGULIS', 'FEDERAL_REGULATION', 'US', '24 CFR Part 982', '24 CFR 982', 'Section 8 Housing Choice Voucher Program', 'Federal regulations governing the Section 8 voucher program including eligibility, payment standards, and landlord obligations.', '["Income eligibility requirements","Housing quality standards inspection","Payment standard calculations","Portability between jurisdictions","Landlord participation requirements"]', '[{"section":"982.1","description":"Program purpose and objectives"},{"section":"982.401","description":"Housing quality standards"},{"section":"982.503","description":"Payment standard amounts"}]', '["Section_8_voucher","HQS_inspection","HAP_contract","income_verification"]', '["california-housing-tenant-rights-audit"]', 'HUD', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- REGULIS — Labor/Employment expansion
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_062', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code § 226', 'LC § 226', 'Itemized Wage Statement Requirements', 'Employers must provide accurate itemized wage statements with each payment of wages.', '["Gross wages earned","Total hours worked (non-exempt)","Piece rates and applicable pieces","All deductions","Net wages earned","Inclusive dates of pay period","Employee name and last 4 of SSN","Employer name and address"]', '[{"section":"226(a)","description":"9 required elements on wage statement"},{"section":"226(e)","description":"Penalties for violations — $50 first, $100 subsequent per pay period"}]', '["pay_stub","wage_statement","payroll_record"]', '["california-labor-employment-audit"]', 'California Labor Commissioner / DLSE', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_063', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code § 1198.5', 'LC § 1198.5', 'Personnel File Access Rights', 'Employees and former employees have the right to inspect and copy their personnel records.', '["Current employees: inspect within 30 days of request","Former employees: inspect within 30 days","Right to copy at employee expense","Applies to records used to determine qualifications"]', '[{"section":"1198.5(a)","description":"Right to inspect personnel records"},{"section":"1198.5(b)","description":"Former employee access rights"}]', '["personnel_file","employment_record","performance_review","disciplinary_record"]', '["california-labor-employment-audit"]', 'California Labor Commissioner', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_064', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code §§ 510, 1194', 'LC §§ 510, 1194', 'California Overtime Requirements', 'Daily and weekly overtime requirements exceeding federal FLSA standards.', '["Overtime (1.5x) after 8 hours/day or 40 hours/week","Double time after 12 hours/day","Overtime on 7th consecutive workday","Alternative workweek schedules permitted with 2/3 vote"]', '[{"section":"510","description":"Daily and weekly overtime standards"},{"section":"1194","description":"Right to recover unpaid overtime"}]', '["pay_stub","timecard","overtime_claim","PAGA_notice"]', '["california-labor-employment-audit"]', 'California Labor Commissioner / DLSE', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_065', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code §§ 2698-2699.8', 'PAGA', 'Private Attorneys General Act', 'Allows aggrieved employees to bring representative actions for Labor Code violations on behalf of themselves and other employees.', '["75% of penalties to LWDA, 25% to employees","Pre-suit notice to LWDA and employer required","65-day waiting period","Covers any Labor Code violation with civil penalties"]', '[{"section":"2699(a)","description":"Aggrieved employee standing"},{"section":"2699.3","description":"Notice and cure procedures"},{"section":"2699(g)","description":"Attorney fees to prevailing employee"}]', '["PAGA_notice","PAGA_complaint","LWDA_notice","settlement_agreement"]', '["california-labor-employment-audit"]', 'LWDA / California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_066', 'REGULIS', 'STATE_REGULATION', 'CA', 'Cal. Code Regs. tit. 8, §§ 11000-11170 (IWC Wage Orders)', 'IWC Wage Orders', 'Industrial Welfare Commission Wage Orders', 'Industry-specific and occupation-specific orders governing wages, hours, and working conditions.', '["17 industry-specific wage orders","Meal period requirements (30 min by 5th hour)","Rest period requirements (10 min per 4 hours)","Minimum wage (state exceeds federal)","Reporting time pay"]', '[{"section":"Wage Order 4","description":"Professional, Technical, Clerical"},{"section":"Wage Order 5","description":"Public Housekeeping"},{"section":"Wage Order 16","description":"Construction"}]', '["wage_order","meal_period_waiver","employment_policy","payroll_record"]', '["california-labor-employment-audit"]', 'California DIR / DLSE', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_067', 'REGULIS', 'STATE_STATUTE', 'CA', 'Cal. Labor Code §§ 3070-3098', 'LC §§ 3070+', 'California Apprenticeship Standards', 'Framework for apprenticeship programs including prevailing wage, training standards, and union apprenticeship programs.', '["DAS-approved apprenticeship program required","Ratio of journeyworkers to apprentices","Progressive wage schedule","On-the-job training and related instruction","Prevailing wage compliance on public works"]', '[{"section":"3070","description":"Division of Apprenticeship Standards (DAS) authority"},{"section":"3073","description":"Apprentice agreements"},{"section":"3078","description":"Prevailing wage requirement"}]', '["apprenticeship_agreement","DAS_filing","prevailing_wage_report","training_record"]', '["california-labor-employment-audit"]', 'California DAS / DIR', 0, 1, datetime('now'), datetime('now'));

-- Cal/OSHA
INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_reg_068', 'REGULIS', 'STATE_REGULATION', 'CA', 'Cal. Code Regs. tit. 8, §§ 3200-6184 (Cal/OSHA)', 'Cal/OSHA', 'California Occupational Safety and Health Standards', 'State safety standards that are at least as effective as federal OSHA, with additional California-specific requirements.', '["Injury and Illness Prevention Program (IIPP) mandatory","Heat illness prevention plan","COVID-19 prevention standards","Hazard communication program","Workplace violence prevention plan"]', '[{"section":"3203","description":"IIPP requirement"},{"section":"3395","description":"Heat illness prevention"},{"section":"3205","description":"COVID-19 prevention"},{"section":"5189","description":"Process Safety Management"}]', '["IIPP","safety_inspection","OSHA_log","Cal_OSHA_citation","workplace_injury"]', '["california-labor-employment-audit"]', 'Cal/OSHA / DIR', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ADVOCIS — CPS/Child Welfare expansion
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_021', 'ADVOCIS', 'STATE_REGULATION', 'CA', 'Cal. Code Regs. tit. 22, Division 2', 'CCR tit. 22 Div. 2', 'CDSS Regulations — Social Services', 'Implementing regulations for child welfare services, foster care, and adoptions in California.', '["Licensing standards for foster homes","Placement regulations","Visitation standards","Background check requirements","Caregiver approval standards"]', '[{"section":"Division 2","description":"Department of Social Services regulations"},{"section":"Chapter 1","description":"General provisions and licensing"}]', '["foster_care_license","placement_order","background_check","home_study"]', '["california-cps-child-welfare-audit"]', 'CDSS / Community Care Licensing', 0, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_022', 'ADVOCIS', 'FEDERAL_STATUTE', 'US', '25 USC §§ 1901-1963 (Indian Child Welfare Act)', 'ICWA', 'Indian Child Welfare Act', 'Federal law establishing standards for removal, placement, and adoption of Indian children to protect tribal sovereignty.', '["Active efforts to prevent breakup of Indian family","Placement preferences favoring tribal members","Tribal notification required for dependency proceedings","Qualified expert witness testimony required","Transfer to tribal court upon petition"]', '[{"section":"1912","description":"Pending court proceedings — notice and active efforts"},{"section":"1915","description":"Placement preferences"},{"section":"1911","description":"Tribal jurisdiction"}]', '["ICWA_notice","dependency_petition","placement_order","tribal_notification"]', '["california-cps-child-welfare-audit"]', 'BIA / Tribal Courts / State Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_adv_023', 'ADVOCIS', 'STATE_STATUTE', 'CA', 'Cal. Welf. & Inst. Code §§ 361.3', 'WIC § 361.3', 'Relative Placement Preference', 'When a child is removed, the court must give preferential consideration to relatives for placement.', '["Preferential consideration to relatives for placement","County must assess all relatives who request placement","Relative placement preference applies at all stages","Court must state reasons if relative is not selected"]', '[{"section":"361.3(a)","description":"Preferential consideration for relatives"},{"section":"361.3(d)","description":"Assessment of requesting relatives"}]', '["placement_order","relative_assessment","court_report"]', '["california-cps-child-welfare-audit"]', 'Superior Court — Juvenile Division', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- ETHICARA — State Bar expansion
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_010', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.4', 'RPC 1.4', 'Communication with Clients', 'Attorney must promptly inform client of significant developments and respond to reasonable status inquiries.', '["Promptly inform client of significant developments","Keep client reasonably informed","Comply with reasonable requests for information","Explain matters to extent reasonably necessary"]', '[{"section":"1.4(a)","description":"Duty to inform of significant developments"},{"section":"1.4(b)","description":"Duty to explain matters"}]', '["client_communication","status_update","engagement_letter","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_011', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 1.15', 'RPC 1.15', 'Safekeeping Client Funds and Property', 'Attorney must keep client funds in trust account separate from own funds.', '["Client funds in IOLTA or trust account","No commingling of attorney and client funds","Prompt notification when funds received","Prompt distribution when earned","Records maintained for 5 years"]', '[{"section":"1.15(a)","description":"Trust account requirements"},{"section":"1.15(d)","description":"Notification and distribution"},{"section":"1.15(e)","description":"Recordkeeping requirements"}]', '["trust_account_record","client_ledger","IOLTA_statement","bar_complaint"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_012', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 3.3', 'RPC 3.3', 'Candor Toward the Tribunal', 'Attorney shall not knowingly make false statements of fact or law to a tribunal.', '["No false statements of material fact or law","Must disclose directly adverse legal authority","Must take remedial measures if evidence offered is false","Duty continues to conclusion of proceeding"]', '[{"section":"3.3(a)","description":"False statements prohibited"},{"section":"3.3(b)","description":"Duty regarding false evidence"}]', '["court_filing","declaration","motion","brief","trial_testimony"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California / Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_eth_013', 'ETHICARA', 'COURT_RULE', 'CA', 'California Rules of Professional Conduct, Rule 8.4', 'RPC 8.4', 'Misconduct', 'Defines professional misconduct including criminal acts, dishonesty, and discrimination.', '["Cannot violate Rules of Professional Conduct","Cannot commit criminal act reflecting on honesty","Cannot engage in dishonesty, fraud, deceit, or misrepresentation","Cannot engage in harassment or discrimination","Cannot knowingly assist judge in violation of judicial code"]', '[{"section":"8.4(a)","description":"Violation of rules"},{"section":"8.4(b)","description":"Criminal acts reflecting dishonesty"},{"section":"8.4(c)","description":"Dishonesty, fraud, deceit"},{"section":"8.4(d)","description":"Conduct prejudicial to justice"}]', '["bar_complaint","disciplinary_proceeding","OCTC_investigation"]', '["state-bar-of-california-attorney-conduct-audit"]', 'State Bar of California / Supreme Court', 1, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- FISCARA — Additional banking regulations
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_022', 'FISCARA', 'FEDERAL_REGULATION', 'US', '12 CFR Part 1002', 'Reg B', 'Regulation B — Equal Credit Opportunity', 'Implementing regulation for ECOA prescribing procedures for credit applications, notifications, and recordkeeping.', '["Adverse action notice within 30 days","Cannot request marital status (certain exceptions)","Cannot consider race, color, religion, national origin, sex","Monitoring information for HMDA collected separately"]', '[{"section":"1002.5","description":"Rules concerning requests for information"},{"section":"1002.7","description":"Rules concerning extensions of credit"},{"section":"1002.9","description":"Notifications of adverse action"},{"section":"1002.12","description":"Record retention requirements"}]', '["credit_application","adverse_action_notice","ECOA_notice","underwriting_decision"]', '["banking-financial-document-audit"]', 'CFPB', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_023', 'FISCARA', 'STATE_STATUTE', 'CA', 'Cal. Civ. Code §§ 2954-2955', 'CC §§ 2954-2955', 'California Impound Account / Mortgage Servicing', 'Requirements for impound/escrow accounts maintained by mortgage servicers in California.', '["Annual accounting of impound account required","Limits on impound cushion amount","Interest payment on impound accounts (2% min)","Refund of excess within 30 days"]', '[{"section":"2954","description":"Impound account requirements"},{"section":"2954.1","description":"Annual accounting"},{"section":"2955","description":"Due-on-sale clause restrictions"}]', '["escrow_analysis","annual_escrow_statement","mortgage_servicing","impound_refund"]', '["banking-financial-document-audit"]', 'California DFPI', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_fis_024', 'FISCARA', 'FEDERAL_STATUTE', 'US', '15 USC § 45(a) (FTC Act § 5)', 'FTC Act § 5', 'Unfair or Deceptive Acts or Practices', 'FTC authority to prevent unfair or deceptive acts or practices in or affecting commerce.', '["Unfair: causes or likely to cause substantial injury","Deceptive: representation or omission likely to mislead","Applies to all industries","FTC enforcement actions and consent orders"]', '[{"section":"45(a)(1)","description":"Declaration of unlawfulness"},{"section":"45(a)(2)","description":"FTC empowered to prevent unfair methods of competition"},{"section":"45(n)","description":"Unfairness standard (injury, not avoidable, not outweighed)"}]', '["FTC_complaint","consent_order","business_practice","advertising"]', '["banking-financial-document-audit"]', 'FTC', 0, 1, datetime('now'), datetime('now'));


-- ═══════════════════════════════════════════════════════════════════════════
-- PRIVAXIS — Additional privacy standards
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_004', 'PRIVAXIS', 'STATE_STATUTE', 'CA', 'Cal. Const. art. I, § 1', 'CA Privacy Right', 'California Constitutional Right to Privacy', 'California Constitution expressly includes privacy as an inalienable right.', '["Privacy is an inalienable right under California Constitution","Applies to both government and private actors","Must show reasonable expectation of privacy","Balancing test: privacy interest vs. countervailing interest"]', '[{"section":"Art. I, § 1","description":"Inalienable rights include privacy"}]', '["privacy_complaint","data_collection","surveillance","employment_screening"]', '[]', 'California Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_005', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '47 USC § 227 (Telephone Consumer Protection Act)', 'TCPA', 'Telephone Consumer Protection Act', 'Restricts telemarketing calls, auto-dialed calls, prerecorded messages, text messages, and unsolicited faxes.', '["Prior express written consent for autodialed/prerecorded marketing calls to cell phones","National Do Not Call Registry compliance","$500 per violation ($1,500 treble for willful)","Private right of action","Opt-out mechanism required"]', '[{"section":"227(b)","description":"Autodialer and prerecorded message restrictions"},{"section":"227(c)","description":"Do Not Call provisions"},{"section":"227(b)(3)","description":"Private right of action — $500/$1,500 per violation"}]', '["telemarketing_call","text_message","robocall","TCPA_complaint"]', '[]', 'FCC / Federal Courts', 1, 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO governing_standards (id, citizen_name, standard_type, jurisdiction, citation, short_cite, title, description, requirements, key_sections, document_types, skill_slugs, enforcement_body, private_right_of_action, is_active, created_at, updated_at)
VALUES
('std_pri_006', 'PRIVAXIS', 'FEDERAL_STATUTE', 'US', '18 USC §§ 2701-2712 (Stored Communications Act)', 'SCA', 'Stored Communications Act', 'Governs access to stored electronic communications and transactional records held by third-party service providers.', '["Prohibits unauthorized access to stored communications","Law enforcement must obtain warrant for content","Service providers limited in disclosure","Civil action for violations"]', '[{"section":"2701","description":"Unlawful access to stored communications"},{"section":"2702","description":"Voluntary disclosure restrictions"},{"section":"2703","description":"Required disclosure — government access procedures"},{"section":"2707","description":"Civil action and damages"}]', '["subpoena","search_warrant","preservation_request","SCA_order"]', '[]', 'DOJ / Federal Courts', 1, 1, datetime('now'), datetime('now'));
