-- New York State Compliance Rules
-- Comprehensive seed covering all categories
-- Citations: NY BCL, NY LLCL, NY Tax Law, NY Labor Law, NY Exec Law, NY Gen Bus Law, NY Pub Health Law, etc.

-- ============================================================
-- FORMATION (30 rules)
-- ============================================================
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-001', 'NY-FORM-001', 'NY Business Corporation Certificate of Incorporation', 'Corporations must file a Certificate of Incorporation with the NY Department of State under BCL § 402. Must include corporate name, purpose, county of office, share structure, and registered agent designation. Filing fee $125 minimum.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 402', 'https://www.nysenate.gov/legislation/laws/BSC/402', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-002', 'NY-FORM-002', 'NY LLC Articles of Organization', 'LLCs must file Articles of Organization with NY Department of State under LLCL § 203. Must include LLC name, county of office, agent for service, and dissolution date if any. Filing fee $200.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL § 203', 'https://www.nysenate.gov/legislation/laws/LLC/203', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-003', 'NY-FORM-003', 'NY LLC Publication Requirement', 'Within 120 days of formation, LLCs must publish notice in two newspapers (one daily, one weekly) designated by the county clerk for six consecutive weeks, then file Certificate of Publication with DOS. Failure suspends authority to do business. NYC publication often costs $1,500-$2,000.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL § 206', 'https://www.nysenate.gov/legislation/laws/LLC/206', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-004', 'NY-FORM-004', 'NY Biennial Statement', 'All domestic and foreign corporations and LLCs must file a Biennial Statement with DOS every two years during the calendar month of original formation/qualification. Filing fee $9. Identifies CEO and principal executive office.', 'FORMATION', 'STATE', 'NY', '["LLC","CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 408; NY LLCL § 301(e)', 'https://dos.ny.gov/biennial-statement', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-005', 'NY-FORM-005', 'NY Registered Agent / Agent for Service', 'Every domestic and foreign business entity must designate the NY Secretary of State as agent for service of process and may appoint an additional registered agent within NY. Address must be maintained current.', 'FORMATION', 'STATE', 'NY', '["LLC","CORPORATION","S_CORP","NONPROFIT","PARTNERSHIP"]', '2024-01-01', 'NY BCL § 304; NY LLCL § 301', 'https://www.nysenate.gov/legislation/laws/BSC/304', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-006', 'NY-FORM-006', 'NY Foreign Corporation Authorization', 'Foreign corporations doing business in NY must obtain Authority to do Business by filing Application for Authority with DOS, accompanied by certificate of good standing dated within 1 year. Filing fee $225.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 1304', 'https://www.nysenate.gov/legislation/laws/BSC/1304', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-007', 'NY-FORM-007', 'NY Foreign LLC Authorization', 'Foreign LLCs must file Application for Authority with DOS plus certificate of existence dated within 1 year. Filing fee $250. Subject to publication requirement.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL § 802', 'https://www.nysenate.gov/legislation/laws/LLC/802', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-008', 'NY-FORM-008', 'NY Professional Service Corporation', 'Licensed professionals (medicine, law, accounting, architecture, engineering) forming a corporation must form a PC under BCL Article 15. Each shareholder must be licensed in the profession. Annual report to licensing authority required.', 'FORMATION', 'STATE', 'NY', '["CORPORATION"]', '2024-01-01', 'NY BCL Article 15 §§ 1501-1516', 'https://www.nysenate.gov/legislation/laws/BSC/A15', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-009', 'NY-FORM-009', 'NY Professional Service LLC (PLLC)', 'Professionals forming an LLC must form a PLLC under LLCL Article 12. Members must be licensed. Annual statement to licensing authority required. Subject to LLC publication requirement.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL Article 12 §§ 1201-1211', 'https://www.nysenate.gov/legislation/laws/LLC/A12', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-010', 'NY-FORM-010', 'NY Benefit Corporation', 'NY recognizes benefit corporations under BCL Article 17. Must include public benefit purpose in certificate, publish annual benefit report, and have benefit director consideration of stakeholders.', 'FORMATION', 'STATE', 'NY', '["CORPORATION"]', '2024-01-01', 'NY BCL Article 17 §§ 1701-1709', 'https://www.nysenate.gov/legislation/laws/BSC/A17', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-011', 'NY-FORM-011', 'NY Not-for-Profit Corporation Formation', 'Nonprofits form under N-PCL by filing Certificate of Incorporation with DOS. Must specify Type A, B, C, or D purpose. Some purposes require consent from state agencies (e.g., education from Regents).', 'FORMATION', 'STATE', 'NY', '["NONPROFIT"]', '2024-01-01', 'NY N-PCL § 402', 'https://www.nysenate.gov/legislation/laws/NPC/402', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-012', 'NY-FORM-012', 'NY Charitable Registration (Charities Bureau)', 'Charitable organizations soliciting in NY must register with the Attorney Generals Charities Bureau under EPTL Article 8 and Executive Law Article 7-A. Annual CHAR500 filing required.', 'FORMATION', 'STATE', 'NY', '["NONPROFIT"]', '2024-01-01', 'NY Exec Law § 172; EPTL § 8-1.4', 'https://www.charitiesnys.com', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-013', 'NY-FORM-013', 'NY Limited Partnership Certificate', 'Limited partnerships must file Certificate of Limited Partnership with DOS under Partnership Law § 121-201. Must publish notice similar to LLC publication requirement.', 'FORMATION', 'STATE', 'NY', '["PARTNERSHIP"]', '2024-01-01', 'NY Partnership Law § 121-201', 'https://www.nysenate.gov/legislation/laws/PTR/121-201', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-014', 'NY-FORM-014', 'NY LLP Registration', 'Limited Liability Partnerships register with DOS under Partnership Law Article 8-B. Restricted to professional services in NY. Annual statement and publication required.', 'FORMATION', 'STATE', 'NY', '["PARTNERSHIP"]', '2024-01-01', 'NY Partnership Law § 121-1500', 'https://www.nysenate.gov/legislation/laws/PTR/A8-B', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-015', 'NY-FORM-015', 'NY Assumed Name (DBA) Filing', 'Sole proprietors and partnerships using a name other than the proprietors name must file a Business Certificate (DBA) with the County Clerk under Gen Bus Law § 130. Corporations and LLCs file Certificate of Assumed Name with DOS.', 'FORMATION', 'STATE', 'NY', '["SOLE_PROPRIETORSHIP","PARTNERSHIP","LLC","CORPORATION","S_CORP"]', '2024-01-01', 'NY Gen Bus Law § 130', 'https://www.nysenate.gov/legislation/laws/GBS/130', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-016', 'NY-FORM-016', 'NY Corporate Bylaws', 'NY corporations must adopt bylaws regulating business and affairs. Initial bylaws adopted by incorporators or board. Must address director qualifications, meetings, officer duties.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP","NONPROFIT"]', '2024-01-01', 'NY BCL § 601', 'https://www.nysenate.gov/legislation/laws/BSC/601', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-017', 'NY-FORM-017', 'NY LLC Operating Agreement Requirement', 'NY LLCs must adopt a written operating agreement within 90 days after filing Articles of Organization. Unique NY requirement — failure does not invalidate LLC but may affect member rights.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL § 417', 'https://www.nysenate.gov/legislation/laws/LLC/417', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-018', 'NY-FORM-018', 'NY Corporate Name Restrictions', 'Corporate name must contain Corporation, Incorporated, Limited, Corp., Inc., or Ltd. and be distinguishable from existing entities. Restricted words (bank, trust, insurance, university) require agency consent.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 301', 'https://www.nysenate.gov/legislation/laws/BSC/301', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-019', 'NY-FORM-019', 'NY Annual Meeting of Shareholders', 'NY corporations must hold an annual meeting of shareholders for election of directors. Notice required 10-60 days in advance under BCL § 605.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 602; § 605', 'https://www.nysenate.gov/legislation/laws/BSC/602', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-020', 'NY-FORM-020', 'NY Director Minimum Requirements', 'NY corporations require at least one director, age 18 or over. Articles or bylaws may require more. Director qualifications may be set by bylaws.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 702', 'https://www.nysenate.gov/legislation/laws/BSC/702', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-021', 'NY-FORM-021', 'NY Corporate Records Maintenance', 'NY corporations must keep correct and complete books and records of account, minutes of shareholder/director meetings, and a record of shareholders. Available for shareholder inspection on 5 days written demand.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 624', 'https://www.nysenate.gov/legislation/laws/BSC/624', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-022', 'NY-FORM-022', 'NY LLC Records Maintenance', 'NY LLCs must keep at office: list of members and managers, copy of Articles, tax returns for 3 years, operating agreement, and financial statements for 3 years.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL § 1102', 'https://www.nysenate.gov/legislation/laws/LLC/1102', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-023', 'NY-FORM-023', 'NY Voluntary Dissolution of Corporation', 'Domestic corporations dissolve by filing Certificate of Dissolution with DOS after obtaining tax clearance from NYS Tax Department. Must give notice to creditors.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 1003; § 1004', 'https://www.nysenate.gov/legislation/laws/BSC/1003', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-024', 'NY-FORM-024', 'NY LLC Dissolution', 'LLCs dissolve by filing Articles of Dissolution with DOS upon events specified in operating agreement, member vote, or judicial decree. Wind-up process required.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2024-01-01', 'NY LLCL § 705', 'https://www.nysenate.gov/legislation/laws/LLC/705', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-025', 'NY-FORM-025', 'NY Certificate of Good Standing', 'Available from DOS for entities current on biennial statements and not delinquent. Required for many transactions including foreign qualification in other states.', 'FORMATION', 'STATE', 'NY', '["LLC","CORPORATION","S_CORP","NONPROFIT"]', '2024-01-01', 'NY DOS Practice', 'https://dos.ny.gov/certificate-status', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-026', 'NY-FORM-026', 'NY LLC Transparency Act', 'Effective January 1, 2026, NY LLCs must report beneficial ownership information to NY DOS, mirroring federal CTA. Report identifying info for each beneficial owner.', 'FORMATION', 'STATE', 'NY', '["LLC"]', '2026-01-01', 'NY LLC Transparency Act, Ch. 772 of 2023 as amended', 'https://www.nysenate.gov/legislation/bills/2023/S995', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-027', 'NY-FORM-027', 'NY Merger and Consolidation', 'Mergers require board approval and shareholder approval (two-thirds for pre-1998 corps, majority after). Certificate of Merger filed with DOS.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL §§ 901-906', 'https://www.nysenate.gov/legislation/laws/BSC/A9', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-028', 'NY-FORM-028', 'NY Shareholder Appraisal Rights', 'Dissenting shareholders in mergers, share exchanges, or asset sales have right to demand fair value of shares. Procedure under BCL § 623 must be followed precisely.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 623', 'https://www.nysenate.gov/legislation/laws/BSC/623', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-029', 'NY-FORM-029', 'NY Stock Issuance and Consideration', 'Shares may be issued for consideration including cash, property, services performed, or promissory notes (post-1998). Board determines adequacy of consideration.', 'FORMATION', 'STATE', 'NY', '["CORPORATION","S_CORP"]', '2024-01-01', 'NY BCL § 504', 'https://www.nysenate.gov/legislation/laws/BSC/504', 1);
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('ny-form-030', 'NY-FORM-030', 'NY Cooperative Corporation', 'Cooperatives form under Cooperative Corporations Law. Special rules for housing cooperatives, agricultural co-ops, worker co-ops. Patronage dividends not corporate dividends.', 'FORMATION', 'STATE', 'NY', '["CORPORATION"]', '2024-01-01', 'NY Cooperative Corporations Law', 'https://www.nysenate.gov/legislation/laws/CCO', 1);
