-- Vernen Legal Compliance — Oregon State Compliance Rules (Seed Oregon-1)
-- FORMATION, TAXATION, REPORTING categories
-- 100 rules with real ORS citations
-- Created: April 5, 2026

-- ============================================================
-- SECTION 1: FORMATION (30 rules)
-- ============================================================

-- Oregon Business Corporation Act
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-001', 'OR-FORM-001', 'Oregon Corporation Formation — Articles of Incorporation', 'Domestic business corporations must file Articles of Incorporation with the Oregon Secretary of State. Filing fee is $100. Articles must include corporate name (with "Corporation," "Incorporated," "Company," "Limited," or abbreviation), authorized shares, registered agent name and address, and incorporator information. Name must be distinguishable from existing registered names. Effective upon filing unless a delayed effective date is specified.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.047; ORS § 60.051', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-002', 'OR-FORM-002', 'Oregon Corporation Name Requirements', 'Corporate name must contain "Corporation," "Incorporated," "Company," "Limited," or an abbreviation thereof. Name must be distinguishable on the records of the Secretary of State from existing registered business names, reserved names, and assumed business names. Name reservation available for 120 days at $100 fee. Application for name reservation may be filed with the Secretary of State.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.094; ORS § 60.101', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-003', 'OR-FORM-003', 'Oregon Corporation Bylaws and Organizational Meeting', 'After incorporation, the incorporator or initial directors named in the articles shall hold an organizational meeting to adopt bylaws, elect directors (if not named in articles), appoint officers, and complete organizational matters. Bylaws may contain any provision for managing the business and regulating the affairs of the corporation not inconsistent with law or articles. Bylaws may be adopted, amended, or repealed by the board or shareholders.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.074; ORS § 60.111', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-004', 'OR-FORM-004', 'Oregon Corporation Stock Issuance and Authorized Shares', 'Articles of incorporation must prescribe the classes of shares and number of shares of each class that the corporation is authorized to issue. If more than one class, articles must prescribe a distinguishing designation for each class. Shares may be issued for any tangible or intangible property or benefit to the corporation as determined by the board of directors.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.047; ORS § 60.134; ORS § 60.144', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Oregon LLC Act
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-005', 'OR-FORM-005', 'Oregon LLC Formation — Articles of Organization', 'To form an Oregon LLC, one or more persons must file Articles of Organization with the Secretary of State. Filing fee is $100. Articles must include LLC name (containing "Limited Liability Company" or "LLC"), registered agent name and address, mailing address, whether member-managed or manager-managed, and organizer signature. Effective upon filing unless delayed date specified.', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.047; ORS § 63.054', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-006', 'OR-FORM-006', 'Oregon LLC Name Requirements', 'An LLC name must contain the words "Limited Liability Company" or the abbreviation "L.L.C." or "LLC." Name must be distinguishable from other registered business names on file with the Secretary of State. Name reservation available for 120 days at $100 fee. A professional LLC must include "Professional Limited Liability Company" or "P.L.L.C." or "PLLC."', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.094; ORS § 63.097', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-007', 'OR-FORM-007', 'Oregon LLC Operating Agreement', 'Oregon law permits but does not require a written operating agreement. The operating agreement governs relations among members and between members and the LLC, including management structure, profit/loss allocation, voting rights, transfer restrictions, and dissolution procedures. Operating agreement may be oral, written, or implied. An LLC is not required to file the operating agreement with the Secretary of State.', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.431; ORS § 63.434', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-008', 'OR-FORM-008', 'Oregon Series LLC', 'Oregon recognizes series LLCs under the Oregon LLC Act. A series LLC may establish one or more designated series with separate rights, powers, or duties with respect to specified property or obligations. Each series may have separate members, managers, and assets. The debts and liabilities of one series are enforceable only against assets of that series if proper notice and segregation requirements are met. Articles must state the LLC is a series LLC.', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.930-63.969', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-009', 'OR-FORM-009', 'Oregon LLC Member and Manager Liability Protection', 'Members and managers of an Oregon LLC are not personally liable for the debts, obligations, or liabilities of the LLC solely by reason of being a member or manager. However, members may be personally liable if they personally guarantee LLC obligations, commit tortious acts, fail to maintain LLC separateness, or engage in fraud. Charging order is the exclusive remedy against a member''s interest.', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.165; ORS § 63.249', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Partnerships
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-010', 'OR-FORM-010', 'Oregon General Partnership Formation', 'A general partnership is formed by the association of two or more persons to carry on as co-owners a business for profit. No filing with the Secretary of State is required to form a general partnership, but partners may file a Statement of Partnership Authority ($100 fee) to establish authority of partners to bind the partnership. Partners are jointly and severally liable for partnership obligations.', 'FORMATION', 'STATE', 'OR', '["PARTNERSHIP"]', '2024-01-01', 'ORS § 67.055; ORS § 67.105', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-011', 'OR-FORM-011', 'Oregon Limited Partnership Formation', 'A limited partnership is formed by filing a Certificate of Limited Partnership with the Secretary of State. Filing fee is $100. Certificate must include LP name (containing "Limited Partnership" or "L.P." or "LP"), registered agent, name and address of each general partner, and whether LP is a limited liability limited partnership. Must have at least one general partner and one limited partner.', 'FORMATION', 'STATE', 'OR', '["PARTNERSHIP"]', '2024-01-01', 'ORS § 68.111; ORS § 68.114', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-012', 'OR-FORM-012', 'Oregon Limited Liability Partnership (LLP) Registration', 'A partnership may become an LLP by filing a Statement of Qualification with the Secretary of State. Filing fee is $100. The statement must include partnership name (containing "Limited Liability Partnership" or "LLP"), address of chief executive office, and a brief statement of business. LLP status must be renewed annually as part of the annual report. An LLP partner is not personally liable for partnership obligations solely by reason of being a partner.', 'FORMATION', 'STATE', 'OR', '["PARTNERSHIP"]', '2024-01-01', 'ORS § 67.500; ORS § 67.505', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Nonprofit Corporations
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-013', 'OR-FORM-013', 'Oregon Nonprofit Corporation Formation', 'Oregon nonprofit corporations are formed by filing Articles of Incorporation with the Secretary of State under ORS Chapter 65. Filing fee is $50. Articles must include corporation name, registered agent, whether the corporation has members, and provisions for distribution of assets on dissolution. If seeking 501(c)(3) status, articles must contain appropriate purpose and dissolution clauses.', 'FORMATION', 'STATE', 'OR', '["NONPROFIT"]', '2024-01-01', 'ORS § 65.044; ORS § 65.047', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-014', 'OR-FORM-014', 'Oregon Nonprofit Director and Officer Standards', 'Directors of an Oregon nonprofit corporation must act in good faith, with the care an ordinarily prudent person in a like position would exercise, and in a manner the director reasonably believes to be in the best interests of the corporation. Board must consist of at least three directors. Directors may rely on officers, employees, and professional advisors. Standard duty of loyalty applies; conflicting interest transactions must be properly authorized.', 'FORMATION', 'STATE', 'OR', '["NONPROFIT"]', '2024-01-01', 'ORS § 65.357; ORS § 65.361', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Assumed Business Names
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-015', 'OR-FORM-015', 'Oregon Assumed Business Name Registration', 'Any person or entity carrying on business in Oregon under an assumed business name must register the name with the Secretary of State. Filing fee is $50. Registration must include the assumed business name, registrant''s real name and address, and a description of the business. Registration is effective for two years and must be renewed. Failure to register is a Class A violation subject to a fine of up to $2,000 per occurrence.', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 648.007; ORS § 648.010; ORS § 648.135', 'https://sos.oregon.gov/business/Pages/assumed-business-names.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-016', 'OR-FORM-016', 'Oregon Assumed Business Name Renewal', 'Assumed business name registrations must be renewed every two years from the date of filing. Renewal filing fee is $50. If not renewed, the registration expires and the name becomes available for registration by others. A new registration (not renewal) is required if the name has lapsed. The Secretary of State sends renewal notices approximately 45 days before expiration.', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 648.017; ORS § 648.020', 'https://sos.oregon.gov/business/Pages/assumed-business-names.aspx', 1);

-- Annual Report
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-017', 'OR-FORM-017', 'Oregon Annual Report Filing', 'All Oregon business entities must file an annual report with the Secretary of State by the anniversary date of their formation or registration. Filing fee is $100 for most entities ($50 for nonprofits). Report must include entity name, jurisdiction of formation, registered agent, principal office address, and names and addresses of directors/managers/partners. Late filing results in administrative dissolution or revocation. Online filing available through the Oregon Business Registry.', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.787 (Corp); ORS § 63.787 (LLC); ORS § 65.787 (Nonprofit)', 'https://sos.oregon.gov/business/Pages/annual-report.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-018', 'OR-FORM-018', 'Oregon Annual Report Late Filing Consequences', 'If an entity fails to file its annual report within the required period, the Secretary of State will send a notice of pending administrative dissolution or revocation. The entity has 60 days after notice to file the report and cure the delinquency. If not cured, the entity will be administratively dissolved (domestic) or its authority revoked (foreign). Reinstatement requires filing all past-due reports and paying a $100 reinstatement fee plus all delinquent annual report fees.', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.651 (Corp); ORS § 63.651 (LLC)', 'https://sos.oregon.gov/business/Pages/annual-report.aspx', 1);

-- Registered Agent
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-019', 'OR-FORM-019', 'Oregon Registered Agent Requirement', 'Every Oregon business entity and every foreign entity registered to do business in Oregon must maintain a registered agent in Oregon. The registered agent must be an individual resident of Oregon or a domestic or foreign entity authorized to transact business in Oregon. Agent must maintain a physical street address (not a P.O. Box) in Oregon. Agent change requires filing with the Secretary of State ($100 fee for most entities).', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.111 (Corp); ORS § 63.111 (LLC); ORS § 65.111 (Nonprofit)', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-020', 'OR-FORM-020', 'Oregon Registered Agent Resignation and Removal', 'A registered agent may resign by filing a Statement of Resignation with the Secretary of State. Resignation is effective 31 days after filing. The entity must appoint a successor agent within 60 days after receiving notice of resignation. If no successor is appointed, the Secretary of State may administratively dissolve the entity. An entity may also change its registered agent at any time by filing the appropriate amendment.', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.121 (Corp); ORS § 63.121 (LLC)', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Foreign Entity Registration
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-021', 'OR-FORM-021', 'Oregon Foreign Corporation Registration', 'A foreign corporation must obtain authority from the Secretary of State before transacting business in Oregon. Application for authority requires filing fee of $275. Application must include corporation name, jurisdiction of incorporation, date of incorporation, registered agent in Oregon, and a certificate of existence from the home state. Transacting business without authority results in inability to maintain court actions in Oregon and potential penalties.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.701; ORS § 60.704; ORS § 60.707', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-022', 'OR-FORM-022', 'Oregon Foreign LLC Registration', 'A foreign LLC must register with the Secretary of State before transacting business in Oregon. Registration fee is $275. Application must include LLC name, jurisdiction of formation, registered agent in Oregon, address of principal office, and a certificate of existence from the home state. A foreign LLC that transacts business without registering cannot maintain a proceeding in Oregon courts and may be subject to a civil penalty of up to $500.', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.701; ORS § 63.704; ORS § 63.714', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-023', 'OR-FORM-023', 'Oregon Foreign Entity — Activities Not Constituting Transacting Business', 'Certain activities do not constitute transacting business in Oregon for registration purposes, including: maintaining or defending legal proceedings, holding meetings, maintaining bank accounts, owning property without more, selling through independent contractors, soliciting orders that require acceptance outside Oregon, and conducting isolated transactions completed within 30 days. The list is non-exhaustive; each situation requires individual analysis.', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '2024-01-01', 'ORS § 60.701(2) (Corp); ORS § 63.701(2) (LLC)', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Professional Corporations
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-024', 'OR-FORM-024', 'Oregon Professional Corporation Formation', 'Licensed professionals (physicians, attorneys, engineers, architects, accountants, etc.) may incorporate as professional corporations under ORS Chapter 58. Articles of incorporation must state the professional service to be rendered. Only licensed professionals may be shareholders. Filing fee is $100. Professional corporation does not shield individual professionals from liability for their own malpractice or negligence. Must comply with both ORS 58 and ORS 60.', 'FORMATION', 'STATE', 'OR', '["CORPORATION"]', '2024-01-01', 'ORS § 58.015; ORS § 58.035; ORS § 58.185', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-025', 'OR-FORM-025', 'Oregon Professional LLC Formation', 'Licensed professionals may form professional limited liability companies under ORS Chapter 63. The articles of organization must designate the professional service to be rendered. Only individuals licensed to render the professional service may be members or managers. Name must include "Professional Limited Liability Company" or "PLLC." Professional LLC does not shield individual professionals from personal malpractice liability.', 'FORMATION', 'STATE', 'OR', '["LLC"]', '2024-01-01', 'ORS § 63.074; ORS § 58.015', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Cooperative Associations
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-026', 'OR-FORM-026', 'Oregon Cooperative Association Formation', 'Cooperative associations may be organized under ORS Chapter 62 by five or more persons. Articles of incorporation must be filed with the Secretary of State ($50 filing fee). Articles must include name (containing "cooperative" or "co-op"), purpose, principal place of business, registered agent, number of directors (not fewer than five), and whether organized with or without capital stock. One member, one vote principle applies regardless of shares held.', 'FORMATION', 'STATE', 'OR', '["CORPORATION"]', '2024-01-01', 'ORS § 62.105; ORS § 62.115; ORS § 62.215', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Benefit Companies
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-027', 'OR-FORM-027', 'Oregon Benefit Company Formation', 'Oregon authorizes benefit companies under ORS 60.750-60.770. Any corporation may elect benefit company status by amending its articles to state it is a benefit company and to identify one or more specific public benefits. A benefit company must consider the effects of its actions on shareholders, employees, community, environment, and long-term interests. Requires two-thirds shareholder vote to adopt or terminate benefit company status.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.750; ORS § 60.754; ORS § 60.757', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-028', 'OR-FORM-028', 'Oregon Benefit Company Annual Report', 'An Oregon benefit company must prepare an annual benefit report that describes the ways in which the company pursued general public benefit and any specific public benefit identified in its articles, the extent to which the benefits were created, and any circumstances that hindered benefit creation. Report must be delivered to shareholders and posted on the company''s website (if any). Report must assess performance against a third-party standard.', 'FORMATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 60.766; ORS § 60.770', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);

-- Sole Proprietorship
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-029', 'OR-FORM-029', 'Oregon Sole Proprietorship — No State Formation Filing Required', 'Oregon does not require sole proprietors to file any formation document with the Secretary of State. A sole proprietor operating under their legal name needs only applicable local business licenses and tax registrations. If operating under a name other than the owner''s legal name, must register an Assumed Business Name with the Secretary of State ($50 fee). Sole proprietors bear unlimited personal liability for all business debts and obligations.', 'FORMATION', 'STATE', 'OR', '["SOLE_PROPRIETORSHIP"]', '2024-01-01', 'ORS § 648.007', 'https://sos.oregon.gov/business/Pages/assumed-business-names.aspx', 1);

-- Mergers and Conversions
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-form-030', 'OR-FORM-030', 'Oregon Entity Conversion and Domestication', 'Oregon permits conversion of one type of domestic entity to another (e.g., LLC to corporation) and domestication of foreign entities to Oregon entities. Conversion requires approval of owners/members/shareholders and filing of articles of conversion with the Secretary of State ($100 filing fee). The converting entity retains all property, rights, and obligations. Domestication of a foreign entity requires filing articles of domestication and compliance with ORS 60.487 (Corp) or ORS 63.487 (LLC).', 'FORMATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.472-60.497 (Corp); ORS § 63.472-63.497 (LLC)', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);


-- ============================================================
-- SECTION 2: TAXATION (40 rules)
-- ============================================================

-- Corporate Activity Tax (CAT)
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-001', 'OR-TAX-001', 'Oregon Corporate Activity Tax (CAT) — Overview', 'Oregon imposes the Corporate Activity Tax on businesses with Oregon commercial activity exceeding $1 million per year. The tax is $250 plus 0.57% of Oregon commercial activity exceeding $1 million, after a 35% subtraction for cost of labor or cost inputs (whichever is greater). All entity types are subject, including sole proprietors, LLCs, corporations, and partnerships. Administered by the Oregon Department of Revenue. Quarterly estimated payments required if annual CAT exceeds $5,000.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2020-01-01', 'ORS § 317A.100-317A.158', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-activity-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-002', 'OR-TAX-002', 'Oregon CAT — Commercial Activity Definition', 'Commercial activity for CAT purposes means the total amount realized by a person from transactions and activity in the regular course of the person''s trade or business in Oregon, without deduction for expenses. Includes gross receipts, gross income, and other amounts. Excludes certain items such as interest on loans, receipts from sale of capital assets held for investment, and amounts received from a unitary group member. Sourcing follows market-based rules for services and intangibles.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2020-01-01', 'ORS § 317A.100(1); OAR 150-317-1000-1170', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-activity-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-003', 'OR-TAX-003', 'Oregon CAT — Filing and Payment Deadlines', 'CAT annual returns are due on April 15 following the close of the tax year (calendar-year taxpayers). Quarterly estimated payments are due April 15, July 15, October 15, and January 15. A penalty of 5% of unpaid tax applies for failure to file timely. Interest accrues on underpayments at the rate established by ORS 305.220. Entities with Oregon commercial activity of $750,000 or less are required to register but file a no-tax-due return.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2020-01-01', 'ORS § 317A.137; ORS § 317A.140', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-activity-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-004', 'OR-TAX-004', 'Oregon CAT — Registration Requirement', 'Any person with Oregon commercial activity exceeding $750,000 in a calendar year must register with the Department of Revenue for the CAT. Registration is also required for persons who are part of a unitary group that collectively exceeds $750,000. Registration must be completed within 30 days of exceeding the threshold. Failure to register is subject to penalties. Registration is done through the Oregon Revenue Online system.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2020-01-01', 'ORS § 317A.117', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-activity-tax.aspx', 1);

-- Corporate Excise Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-005', 'OR-TAX-005', 'Oregon Corporate Excise Tax — Rates and Application', 'Oregon imposes a corporate excise tax on corporations doing business in Oregon. The tax rate is 6.6% of taxable income up to $1 million and 7.6% on taxable income exceeding $1 million. Minimum tax ranges from $150 (Oregon sales under $500,000) to $100,000 (Oregon sales of $100 million or more). S corporations pay a reduced minimum tax. Due on the 15th day of the 4th month after the close of the tax year (April 15 for calendar-year filers).', 'TAXATION', 'STATE', 'OR', '["CORPORATION"]', '2024-01-01', 'ORS § 317.061; ORS § 317.090', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-excise-income.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-006', 'OR-TAX-006', 'Oregon Corporate Excise Tax — Minimum Tax Schedule', 'Oregon''s corporate excise tax minimum tax is based on Oregon sales: $150 for sales under $500,000; $500 for $500K-$1M; $1,000 for $1M-$2M; $1,500 for $2M-$3M; $2,000 for $3M-$5M; $4,000 for $5M-$7M; $7,500 for $7M-$10M; $15,000 for $10M-$25M; $30,000 for $25M-$50M; $50,000 for $50M-$75M; $75,000 for $75M-$100M; $100,000 for sales of $100M or more. S corporations pay $150 minimum tax regardless of sales volume.', 'TAXATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 317.090', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-excise-income.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-007', 'OR-TAX-007', 'Oregon Corporate Income Tax — Non-Oregon Corporations', 'Corporations that have income from Oregon sources but are not doing business in Oregon are subject to Oregon corporate income tax (not excise tax). The income tax rate is the same as the excise tax rate: 6.6% on first $1 million and 7.6% on amounts over $1 million. No minimum tax applies to income tax filers. Applicable to corporations deriving income from Oregon real property, Oregon-source rents, royalties, and other fixed or determinable income.', 'TAXATION', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 318.020; ORS § 318.031', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-excise-income.aspx', 1);

-- Personal Income Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-008', 'OR-TAX-008', 'Oregon Personal Income Tax — Rates and Brackets', 'Oregon imposes a graduated personal income tax on residents and nonresidents with Oregon-source income. 2024 rates: 4.75% on first $4,050 (single) / $8,100 (joint); 6.75% on $4,051-$10,200 (single) / $8,101-$20,400 (joint); 8.75% on $10,201-$125,000 (single) / $20,401-$250,000 (joint); 9.9% on income over $125,000 (single) / $250,000 (joint). Brackets are indexed annually for inflation. Pass-through entity income flows to owners'' personal returns.', 'TAXATION', 'STATE', 'OR', '["LLC","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 316.037', 'https://www.oregon.gov/dor/programs/individuals/pages/pit.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-009', 'OR-TAX-009', 'Oregon Personal Income Tax — Withholding Requirements', 'Every employer paying wages to Oregon residents or for services performed in Oregon must withhold Oregon personal income tax. Withholding rates follow graduated tables published by the Department of Revenue. Employers must remit withholdings on a schedule based on total annual withholding: monthly (less than $1,000/quarter), quarterly, or semi-weekly (over $100,000/year). Annual reconciliation on Form WR (Oregon Annual Withholding Tax Reconciliation Report) due February 28.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 316.167; ORS § 316.187', 'https://www.oregon.gov/dor/programs/businesses/pages/payroll-withholding.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-010', 'OR-TAX-010', 'Oregon Pass-Through Entity Elective Tax (PTE-E)', 'Oregon offers an elective pass-through entity tax allowing PTEs (partnerships, S corps, LLCs taxed as partnerships) to pay Oregon income tax at the entity level. Tax rate is 9% on distributive income. Qualifying members receive a credit on their personal returns for their share of the tax paid. Election must be made annually on the PTE-E return. Designed to allow SALT deduction workaround at the federal level. Election due by the original return due date.', 'TAXATION', 'STATE', 'OR', '["LLC","S_CORP","PARTNERSHIP"]', '2024-01-01', 'ORS § 314.990 (PTE-E provisions)', 'https://www.oregon.gov/dor/programs/businesses/pages/pass-through-entity-elective-tax.aspx', 1);

-- No Sales Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-011', 'OR-TAX-011', 'Oregon Has No Sales Tax — Compliance Considerations', 'Oregon is one of five states with no general sales tax or use tax. Businesses selling to Oregon customers do not collect Oregon sales tax. However, businesses selling from Oregon to customers in other states may have sales tax collection obligations in those states based on economic nexus rules (typically $100K in sales or 200 transactions). Oregon businesses must track interstate sales carefully to determine remote seller obligations in destination states.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Oregon Constitution, Article IX (no provision for sales tax)', 'https://www.oregon.gov/dor/programs/businesses/pages/sales-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-012', 'OR-TAX-012', 'Oregon No Use Tax — Out-of-State Purchase Considerations', 'Oregon does not impose a use tax on goods purchased from out-of-state sellers. Oregon residents and businesses purchasing goods from other states do not owe Oregon use tax. However, some Oregon localities have considered local sales taxes, and businesses should monitor local ballot measures. This no-sales-tax status means Oregon businesses competing with out-of-state sellers in Oregon have a price advantage on taxable goods.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Oregon Constitution, Article IX', 'https://www.oregon.gov/dor/pages/index.aspx', 1);

-- TriMet Transit District Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-013', 'OR-TAX-013', 'TriMet Transit District Employer Payroll Tax', 'Employers with employees working within the TriMet district (Portland metro area, portions of Multnomah, Washington, and Clackamas counties) must pay the TriMet employer payroll tax. The rate is 0.8037% (2024) of wages paid for services performed within the district. Filed quarterly with the Oregon Department of Revenue on Form OQ (Oregon Quarterly Tax Report). No employee withholding — this is an employer-only tax. Applies regardless of where the employer is located if work is performed in the district.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 267.380; OAR 150-267-0010 through 0100', 'https://www.oregon.gov/dor/programs/businesses/pages/transit-taxes.aspx', 1);

-- Lane Transit District Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-014', 'OR-TAX-014', 'Lane Transit District Employer Payroll Tax', 'Employers with employees working within the Lane Transit District (Eugene-Springfield area, Lane County) must pay the Lane Transit District employer payroll tax. The rate is 0.77% (2024) of wages paid for services performed within the district. Filed quarterly on Form OQ with the Oregon Department of Revenue. Employer-only tax; no employee withholding. Self-employed individuals with net earnings from self-employment within the district are also subject to the tax.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 267.380 (applied to LTD); OAR 150-267-0010', 'https://www.oregon.gov/dor/programs/businesses/pages/transit-taxes.aspx', 1);

-- Statewide Transit Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-015', 'OR-TAX-015', 'Oregon Statewide Transit Tax (STT)', 'Oregon imposes a statewide transit tax of 0.1% (one-tenth of one percent) on wages earned by employees and on the earnings of self-employed individuals. This is an employee-paid tax that employers must withhold from employee wages. The tax applies to all wages subject to Oregon personal income tax withholding, regardless of where in Oregon the work is performed. Reported on Form OQ quarterly. Funds public transit programs statewide. No employer match required.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2018-07-01', 'ORS § 320.550-320.600', 'https://www.oregon.gov/dor/programs/businesses/pages/statewide-transit-tax.aspx', 1);

-- Workers' Benefit Fund
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-016', 'OR-TAX-016', 'Oregon Workers'' Benefit Fund Assessment', 'All employers subject to Oregon workers'' compensation law must pay the Workers'' Benefit Fund assessment. The assessment is based on hours worked by employees — both employer and employee portions. Rate is set annually by the Department of Consumer and Business Services (DCBS); 2024 combined rate is approximately $0.044 per hour worked (split between employer and employee). Reported quarterly to DCBS. Funds benefits for permanently disabled workers and worker training.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 656.506; ORS § 656.612', 'https://www.oregon.gov/dcbs/assessments/pages/wbf.aspx', 1);

-- Oregon Estate Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-017', 'OR-TAX-017', 'Oregon Estate Tax — $1 Million Exemption', 'Oregon imposes an estate tax on estates of Oregon residents and on Oregon-situs property of nonresidents. The exemption threshold is $1 million — substantially lower than the federal $13.61 million exemption (2024). Tax rates range from 10% to 16% on the taxable estate. Oregon''s low threshold means many estates not subject to federal estate tax still owe Oregon estate tax. Return (Form OR-706) is due 9 months after date of death. Business succession planning must account for this gap.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 118.005-118.840', 'https://www.oregon.gov/dor/programs/individuals/pages/estate.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-018', 'OR-TAX-018', 'Oregon Estate Tax — Natural Resource Credit', 'Oregon provides a natural resource credit against the estate tax for qualifying natural resource property (farmland, forestland, or fishing operations). The credit reduces the estate tax attributable to the natural resource property if the property continues to be used for natural resource purposes. Credit phases out for estates exceeding $15 million. Property must have been owned and used for natural resource purposes for 5 of the 8 years preceding death.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 118.140', 'https://www.oregon.gov/dor/programs/individuals/pages/estate.aspx', 1);

-- Property Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-019', 'OR-TAX-019', 'Oregon Property Tax — Measure 5 Limits', 'Oregon property taxes are subject to Measure 5 (1990) rate limits: $5 per $1,000 of real market value for education and $10 per $1,000 for general government. If combined tax rates exceed these limits, taxes are compressed proportionally. Property is assessed at real market value for compression purposes but taxed on assessed value (which may be lower due to Measure 50). Tax statements issued in October; due November 15 (full payment) or in thirds (November 15, February 15, May 15).', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Oregon Constitution, Article XI, § 11b (Measure 5)', 'https://www.oregon.gov/dor/programs/property/pages/general-info.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-020', 'OR-TAX-020', 'Oregon Property Tax — Measure 50 Assessed Value', 'Measure 50 (1997) limits annual growth in assessed value to 3% per year, unless the property undergoes an exception event (new construction, partition, rezoning, etc.). As a result, assessed value is often significantly lower than real market value. Maximum assessed value (MAV) equals the prior year''s MAV plus 3%. New property is assessed at the lesser of real market value or the MAV calculated using the changed property ratio for the code area.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'Oregon Constitution, Article XI, § 11 (Measure 50); ORS § 308.146', 'https://www.oregon.gov/dor/programs/property/pages/general-info.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-021', 'OR-TAX-021', 'Oregon Business Personal Property Tax', 'Business personal property (machinery, equipment, furniture, fixtures, supplies) with an aggregate real market value of $35,000 or more per county must be reported annually on a personal property return filed with the county assessor. Return is due by March 15. Penalty for late filing is 5-50% of taxes owed. Property is assessed at real market value less statutory depreciation. Leased equipment may be reported by either lessor or lessee depending on the lease terms.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 308.290; ORS § 308.296', 'https://www.oregon.gov/dor/programs/property/pages/personal-property.aspx', 1);

-- Transient Lodging Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-022', 'OR-TAX-022', 'Oregon Transient Lodging Tax', 'Oregon imposes a statewide transient lodging tax of 1.5% on lodging with a rate of $2 or more per night. Local jurisdictions impose additional transient lodging taxes (typically 6-11.5% combined with state). Applies to hotels, motels, vacation rentals, and other transient accommodations for periods of less than 30 days. Tax is collected from the lodging guest and remitted to the Oregon Department of Revenue quarterly. Short-term rental platforms have collection obligations.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 320.300-320.365', 'https://www.oregon.gov/dor/programs/businesses/pages/transient-lodging-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-023', 'OR-TAX-023', 'Oregon Local Transient Lodging Tax Coordination', 'Cities and counties imposing transient lodging taxes must coordinate with the state 1.5% tax. Local taxes typically range from 3% to 10% on top of the state rate. Total combined rates in major Oregon cities: Portland 11.5%, Eugene 4.5%, Bend 10.4%, Salem 9%. Local governments must report transient lodging tax revenue to the Oregon Department of Revenue. Short-term rental platforms (Airbnb, VRBO) are required to collect and remit both state and local taxes.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 320.350; ORS § 320.360', 'https://www.oregon.gov/dor/programs/businesses/pages/transient-lodging-tax.aspx', 1);

-- Marijuana Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-024', 'OR-TAX-024', 'Oregon Marijuana Tax — 17% Retail Rate', 'Oregon imposes a 17% tax on the retail sale of marijuana items by marijuana retailers. Tax is collected from the consumer at the point of sale and remitted to the Oregon Department of Revenue. Returns filed quarterly. Local governments may impose an additional tax of up to 3% on marijuana sales (approved by local voters). Marijuana businesses also subject to all other applicable taxes (income tax, CAT, payroll taxes). Federal 280E deduction limitations apply.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 475C.770-475C.792', 'https://www.oregon.gov/dor/programs/businesses/pages/marijuana.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-025', 'OR-TAX-025', 'Oregon Marijuana Tax — Local Option Tax', 'Cities and counties in Oregon may impose a local tax on the sale of marijuana items within their jurisdiction at a rate of up to 3%. The local tax must be approved by the voters of the jurisdiction. The local tax is in addition to the state 17% tax. Examples: Portland 3%, Eugene 3%, Salem 3%. Local marijuana taxes are administered and collected by the Oregon Department of Revenue. Quarterly filing required for marijuana retailers in local-tax jurisdictions.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 475C.798-475C.808', 'https://www.oregon.gov/dor/programs/businesses/pages/marijuana.aspx', 1);

-- Timber Harvest Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-026', 'OR-TAX-026', 'Oregon Timber Harvest Tax — Privilege Tax', 'Oregon imposes a harvest tax on timber harvested from Oregon lands. The tax rate is set annually by the State Forester and the Department of Revenue. For 2024, the combined rate is approximately $4.0788 per thousand board feet (MBF). Tax is composed of Forest Products Harvest Tax (FPHT) and other assessments including the Oregon Forest Practices Act fund. Timber owners or operators must file a Timber Tax Return by the 15th day of the second month following the quarter of harvest.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 321.005-321.185; ORS § 321.145', 'https://www.oregon.gov/dor/programs/businesses/pages/timber-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-027', 'OR-TAX-027', 'Oregon Small Tract Forestland (STF) Tax Option', 'Owners of 10-5,000 acres of forestland may elect STF designation and pay a per-acre tax instead of the ad valorem property tax on the standing timber value. Annual STF tax rate varies by county and forestland class. Election is made by filing an application with the county assessor by April 1. Once elected, STF status continues until the owner opts out or the land no longer qualifies. Timber harvested from STF land is subject to the additional tax at the time of harvest equal to the value of timber times the STF additional tax rate.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 321.700-321.754', 'https://www.oregon.gov/dor/programs/property/pages/timber-forestland.aspx', 1);

-- Cigarette and Tobacco Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-028', 'OR-TAX-028', 'Oregon Cigarette Tax', 'Oregon imposes a cigarette tax of $1.33 per pack of 20 cigarettes ($3.33 per pack total including the federal $1.01 and an additional $1.00 per pack assessment under Measure 108 effective 2021). Distributors must obtain a license from the Department of Revenue and purchase tax stamps to affix to each pack. Monthly reports required. Untaxed cigarette possession in excess of 400 cigarettes (2 cartons) by a non-licensed person is unlawful. Penalties include seizure and civil fines.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 323.005-323.482; Measure 108 (2020)', 'https://www.oregon.gov/dor/programs/businesses/pages/cigarette-tobacco.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-029', 'OR-TAX-029', 'Oregon Other Tobacco Products (OTP) and Vaping Tax', 'Oregon imposes a tax of 65% of the wholesale price on other tobacco products (cigars, pipe tobacco, smokeless tobacco, etc.). Inhalant delivery systems (vaping products) are taxed at 65% of wholesale price (Measure 108, effective 2021). Licensed distributors remit monthly. Cap on cigar tax is $1.00 per cigar. Retailers who receive untaxed OTP must obtain a distributor license. Online and mail-order sales to Oregon consumers are subject to the tax.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 323.500-323.645; Measure 108 (2020)', 'https://www.oregon.gov/dor/programs/businesses/pages/cigarette-tobacco.aspx', 1);

-- Unemployment Insurance Tax
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-030', 'OR-TAX-030', 'Oregon Unemployment Insurance (UI) Tax', 'Employers who pay wages of $1,000 or more in any calendar quarter, or who have one or more employees for part of a day in 18 or more separate weeks, must pay Oregon UI tax. Tax is paid on the first $52,800 of each employee''s wages (2024 taxable wage base). New employer rate is 2.4%. Experienced rates range from 0.7% to 5.4% based on employer''s contribution and benefit history. Reported quarterly on Form OQ. Domestic employers have a $1,000/quarter threshold.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 657.035; ORS § 657.505', 'https://www.oregon.gov/employ/businesses/pages/unemployment-insurance-tax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-031', 'OR-TAX-031', 'Oregon Paid Leave (Paid Family and Medical Leave Insurance)', 'Oregon''s Paid Leave program requires contributions from employers with 25+ employees and from all employees. Total contribution rate is 1% of employee wages (2024): employees pay 60% (0.6%) and employers with 25+ employees pay 40% (0.4%). Small employers (under 25 employees) only withhold the employee portion. Taxable wage base matches Social Security ($168,600 in 2024). Reported quarterly on Form OQ. Benefits available starting September 3, 2023.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2023-01-01', 'ORS § 657B.010-657B.990', 'https://paidleave.oregon.gov/employers/', 1);

-- Other Taxes
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-032', 'OR-TAX-032', 'Oregon Workers'' Compensation Premium Tax', 'Insurance companies writing workers'' compensation policies in Oregon pay a premium tax to fund the Workers'' Compensation Division. Self-insured employers pay a self-insurance tax assessment instead. The combined assessment includes the Workers'' Benefit Fund, the Employer-at-Injury Program, the Retroactive Program, and DCBS administrative costs. Rates are set annually by DCBS. Failure to secure workers'' compensation coverage subjects employers to penalties of $250/day or double the premium that would have been charged, whichever is greater.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 656.612; ORS § 656.614; ORS § 656.735', 'https://www.oregon.gov/dcbs/insurance/pages/employers.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-033', 'OR-TAX-033', 'Oregon Heavy Equipment Rental Tax', 'Oregon imposes a 2% gross revenue tax on entities engaged in the rental of heavy equipment or machinery for construction, industrial, or forestry use. Applies to equipment with a cost basis of $100,000 or more. Filed annually with the Department of Revenue. Revenue funds the Road Fund. Only applies to short-term rentals (less than 12 months). Long-term leases and rent-to-own arrangements are excluded.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 319.020', 'https://www.oregon.gov/dor/programs/businesses/pages/other-programs.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-034', 'OR-TAX-034', 'Oregon Motor Vehicle Fuel Tax', 'Dealers and users of motor vehicle fuel in Oregon must pay a fuel tax of $0.40 per gallon (2024, including increases from HB 2017). Biodiesel blends and compressed natural gas are also subject to the tax at equivalent rates. Licensed fuel dealers file monthly reports and remit tax to the Oregon Department of Transportation (ODOT). Use-fuel tax applies to diesel and other fuels used in vehicles on public highways. International Fuel Tax Agreement (IFTA) applies to interstate carriers.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 319.020; ORS § 319.530', 'https://www.oregon.gov/odot/ftg/pages/motorfueltax.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-035', 'OR-TAX-035', 'Oregon Weight-Mile Tax for Heavy Vehicles', 'Oregon imposes a weight-mile tax on trucks and truck-tractor combinations with a combined weight over 26,000 pounds operating on Oregon highways. This is instead of the fuel tax for qualifying heavy vehicles. Tax rates vary by weight and number of axles. Carriers must obtain Oregon weight receipts and maintain mileage records. Monthly or quarterly filing required. Rate tables published annually by ODOT. Interstate carriers subject to the tax for Oregon miles traveled.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 825.474-825.494', 'https://www.oregon.gov/odot/ftg/pages/weight-mile.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-036', 'OR-TAX-036', 'Multnomah County Business Income Tax (Preschool for All)', 'Multnomah County imposes a business income tax (Preschool for All, effective 2021) on taxable income of businesses operating in Multnomah County. Rate is 1.5% on taxable income over $5 million, plus an additional 1.5% on taxable income over $25 million. Individual taxpayers with Oregon taxable income over $125,000 (single) or $200,000 (joint) also pay 1.5%/3.0%. Administered by the Multnomah County Revenue Division. Annual filing required by April 15.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2021-01-01', 'Multnomah County Code § 12.400-12.500; Measure 26-214', 'https://www.multco.us/finance/preschool-all-tax', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-037', 'OR-TAX-037', 'Metro Supportive Housing Services Tax', 'Metro regional government (Portland metro area) imposes a Supportive Housing Services income tax. Business tax: 1% on net income for businesses with gross receipts exceeding $5 million. Personal tax: 1% on taxable income over $125,000 (single) or $200,000 (joint). Administered by the Metro Revenue Division. Applies to businesses and individuals with income in Clackamas, Multnomah, and Washington counties. Annual filing required. First tax year was 2021.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2021-01-01', 'Metro Code § 7.07; Measure 26-210', 'https://www.oregonmetro.gov/public-projects/supportive-housing-services/tax', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-038', 'OR-TAX-038', 'Portland Clean Energy Community Benefits Fund Surcharge', 'Portland imposes a 1% surcharge on gross revenue from retail sales in Portland for retailers with at least $1 billion in nationwide revenue and $500,000 in Portland revenue. This is a narrow gross receipts tax affecting only large retailers. Administered by the Portland Revenue Division. Quarterly filing required. Exempts certain items including groceries, medicine, and motor fuel. Revenue funds climate and green energy programs. Effective January 1, 2019.', 'TAXATION', 'STATE', 'OR', '["CORPORATION"]', '2019-01-01', 'Portland City Code § 7.02.500-7.02.700; Measure 26-201', 'https://www.portland.gov/revenue/pcef', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-039', 'OR-TAX-039', 'Oregon Quarterly Combined Tax Report (Form OQ)', 'Oregon employers must file a combined quarterly tax report (Form OQ) with the Oregon Department of Revenue. Form OQ reports withholding, statewide transit tax, TriMet/Lane Transit District taxes, unemployment insurance, Paid Leave contributions, and Workers'' Benefit Fund assessment in a single filing. Due the last day of the month following the quarter (April 30, July 31, October 31, January 31). Electronic filing required for employers with 10+ employees. Late filing subject to 10% penalty.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 316.168; OAR 150-316-0359', 'https://www.oregon.gov/dor/programs/businesses/pages/payroll-withholding.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-tax-040', 'OR-TAX-040', 'Oregon Business Tax Account Registration', 'Before paying wages or conducting taxable activity in Oregon, businesses must register with the Oregon Department of Revenue for a Business Identification Number (BIN). Registration is done through Oregon Business Registry (combined registration with Secretary of State, Department of Revenue, Employment Department, and DCBS). Single registration covers income tax withholding, UI tax, transit taxes, statewide transit tax, workers'' comp, and CAT. Registration is free and can be completed online.', 'TAXATION', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 316.168; ORS § 657.665', 'https://sos.oregon.gov/business/Pages/register.aspx', 1);


-- ============================================================
-- SECTION 3: REPORTING (30 rules)
-- ============================================================

-- Annual Report to Secretary of State
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-001', 'OR-REP-001', 'Oregon Annual Report — Filing Requirements and Content', 'All domestic and authorized foreign business entities must file an annual report with the Oregon Secretary of State. Report must include entity name, state/country of formation, registered agent name and address, principal office address, mailing address, and names and addresses of directors/managers/general partners. LLCs and corporations file on their anniversary date. Fee is $100 (business entities) or $50 (nonprofits). Online filing available via Oregon Business Registry.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.787 (Corp); ORS § 63.787 (LLC); ORS § 65.787 (Nonprofit); ORS § 67.625 (LP)', 'https://sos.oregon.gov/business/Pages/annual-report.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-002', 'OR-REP-002', 'Oregon Annual Report — Due Dates and Grace Period', 'Oregon annual reports are due on the anniversary date of the entity''s formation or registration. The Secretary of State provides a 45-day grace period after the due date before initiating administrative dissolution proceedings. If the report is not filed within the grace period, a notice of pending dissolution/revocation is sent with 60 additional days to cure. Total window is approximately 105 days from the anniversary date before dissolution occurs. No late fees — only risk is dissolution.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 60.787; ORS § 60.651', 'https://sos.oregon.gov/business/Pages/annual-report.aspx', 1);

-- Oregon Employment Department Wage Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-003', 'OR-REP-003', 'Oregon Quarterly Wage Detail Report (Form 132)', 'Employers must file a quarterly wage detail report (Form 132) with the Oregon Employment Department listing each employee''s SSN, name, hours worked, and wages paid. Filed quarterly alongside Form OQ (Oregon Quarterly Tax Report). Due the last day of the month following the quarter. Electronic filing required for employers with 10+ employees. Data is used for UI benefit calculations, new hire reporting verification, and labor market statistics. Penalties apply for late or inaccurate filing.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 657.660; OAR 471-031-0085', 'https://www.oregon.gov/employ/businesses/pages/quarterly-reporting.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-004', 'OR-REP-004', 'Oregon New Hire Reporting', 'Oregon employers must report all newly hired and rehired employees to the Oregon Department of Justice, Division of Child Support within 20 days of the employee''s first day of work. Report must include employee name, address, SSN, date of birth, date of hire, and employer name, address, and federal EIN. Multi-state employers may report to one state if they designate it for federal purposes. Failure to report subjects employers to a penalty of $25 per employee (up to $500 for willful non-compliance).', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 25.790; 42 USC § 653a', 'https://www.oregon.gov/doj/child-support/pages/employer-new-hire.aspx', 1);

-- Oregon OSHA Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-005', 'OR-REP-005', 'Oregon OSHA Workplace Injury and Illness Reporting', 'Oregon operates its own state OSHA plan (Oregon OSHA) under the Department of Consumer and Business Services. Employers must report workplace fatalities within 8 hours and hospitalizations, amputations, or losses of an eye within 24 hours to Oregon OSHA. Employers with 10+ employees (or in designated industries regardless of size) must maintain OSHA 300 logs of workplace injuries and illnesses. Annual summary (Form 300A) must be posted February 1 through April 30.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.062; ORS § 654.071; OAR 437-001-0700', 'https://osha.oregon.gov/', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-006', 'OR-REP-006', 'Oregon OSHA Annual Injury Survey (BLS Survey)', 'Oregon OSHA conducts an annual Survey of Occupational Injuries and Illnesses (part of the federal BLS survey) by selecting employers to participate. Selected employers must complete the survey reporting their OSHA 300 log data. Failure to respond may result in citations and penalties up to $13,653 per violation. Oregon OSHA mails survey forms in January/February for the prior calendar year. Response is mandatory if selected — not voluntary.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 654.062; 29 CFR § 1904.41', 'https://osha.oregon.gov/', 1);

-- DEQ Environmental Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-007', 'OR-REP-007', 'Oregon DEQ Air Quality Reporting — Title V Permits', 'Major sources of air pollution must obtain a Title V operating permit from the Oregon Department of Environmental Quality (DEQ). Permit holders must submit annual compliance certifications and semiannual monitoring reports. Major source thresholds vary by pollutant (e.g., 100 tons/year for criteria pollutants, 10 tons/year for individual HAPs). Permit renewal every 5 years. Non-compliance can result in penalties of up to $25,000 per day per violation.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 468A.040; OAR 340-218-0010 through 0230', 'https://www.oregon.gov/deq/aq/pages/default.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-008', 'OR-REP-008', 'Oregon DEQ Toxics Use and Hazardous Waste Reporting', 'Facilities generating, transporting, or disposing of hazardous waste must register with DEQ and obtain an EPA ID number. Large quantity generators (1,000+ kg/month) must file biennial reports (odd years, due March 1). All generators must maintain manifests for hazardous waste shipments. Oregon also requires Toxics Use Reduction reporting for facilities using specified toxic substances above threshold quantities. Community Right to Know (Tier II) reports due annually by March 1.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 466.005-466.385; OAR 340-100 through 340-113', 'https://www.oregon.gov/deq/hazards-and-cleanup/pages/default.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-009', 'OR-REP-009', 'Oregon DEQ Water Quality Discharge Reporting', 'Facilities discharging pollutants to waters of the state must obtain a National Pollutant Discharge Elimination System (NPDES) permit from DEQ. NPDES permit holders must submit Discharge Monitoring Reports (DMRs) monthly or quarterly as specified in the permit. Stormwater discharge permits require annual reports and a Stormwater Pollution Control Plan. Industrial stormwater permit (1200-Z) requires benchmark monitoring and corrective action reporting. Penalties up to $25,000 per day per violation.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 468B.025; ORS § 468B.050; OAR 340-045', 'https://www.oregon.gov/deq/wq/pages/default.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-010', 'OR-REP-010', 'Oregon Greenhouse Gas Reporting', 'Oregon requires facilities and fuel suppliers that emit 2,500 or more metric tons of CO2 equivalent per year to report greenhouse gas emissions to DEQ. Reporting follows EPA mandatory reporting rule protocols (40 CFR Part 98). Annual reports due by March 31 for the prior calendar year. Third-party verification required for facilities emitting 25,000+ metric tons. Data is publicly available. Oregon''s Climate Protection Program may impose additional reporting for covered entities.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '2024-01-01', 'ORS § 468A.280; OAR 340-215-0030 through 0060', 'https://www.oregon.gov/deq/ghgp/pages/default.aspx', 1);

-- Workers' Compensation Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-011', 'OR-REP-011', 'Oregon Workers'' Compensation Claim Reporting', 'When a worker is injured on the job, the employer must provide the worker with a Form 801 (Report of Job Injury or Illness) and submit it to their workers'' compensation insurer within 5 days of knowledge of the claim. The insurer must accept or deny the claim within 60 days. Employers must also report all claims to the Workers'' Compensation Division. Failure to provide the Form 801 can result in penalties. Employers must not discriminate against workers who file claims (ORS § 659A.040).', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 656.262; OAR 436-060-0010 through 0160', 'https://www.oregon.gov/dcbs/workers-compensation/pages/employers.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-012', 'OR-REP-012', 'Oregon Workers'' Compensation Proof of Coverage Posting', 'Every employer subject to Oregon workers'' compensation law must post a notice in the workplace informing employees of workers'' compensation coverage. The notice must include the insurer''s name, policy number, and contact information for reporting claims. Form 1507 (Notice of Compliance) must be posted in a conspicuous location. Failure to post notice is a Class A violation with penalties up to $2,000. Self-insured employers must post their self-insurance certificate information.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 656.054; OAR 436-050-0040', 'https://www.oregon.gov/dcbs/workers-compensation/pages/employers.aspx', 1);

-- Pay Equity Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-013', 'OR-REP-013', 'Oregon Pay Equity Act — Record-Keeping and Compliance', 'Oregon''s Pay Equity Act (ORS 652.220) prohibits employers from paying different wages to employees performing comparable work based on protected class status, unless justified by specific bona fide factors (seniority, merit, education, training, experience, workplace conditions, etc.). Employers must maintain records of wages, job descriptions, and factors used to determine pay for at least 3 years. No separate pay equity report filing required, but employers must be prepared to demonstrate compliance upon complaint or investigation by BOLI.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.220; ORS § 652.235', 'https://www.oregon.gov/boli/workers/pages/pay-equity.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-014', 'OR-REP-014', 'Oregon Salary History Inquiry Ban', 'Oregon prohibits employers from seeking salary history information from applicants or current employees (ORS 652.220(2)). Employers may not screen applicants based on current or past compensation. Employers may discuss with applicants their compensation expectations for the position. Violations are enforceable through BOLI complaints or civil action. Employers should train hiring personnel and update application forms to ensure compliance. Applies to all employers regardless of size.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.220(2)', 'https://www.oregon.gov/boli/workers/pages/pay-equity.aspx', 1);

-- Beneficial Ownership (State)
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-015', 'OR-REP-015', 'Oregon Beneficial Ownership — State Annual Report Disclosure', 'While Oregon does not have a standalone state-level beneficial ownership reporting requirement separate from the federal FinCEN BOI Report, the annual report filed with the Secretary of State requires disclosure of directors, managers, and general partners. Oregon''s annual report thus captures key control persons but does not require disclosure of 25%+ equity owners who are not also officers/directors/managers. Entities should ensure annual report data is consistent with FinCEN BOI filings.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '2024-01-01', 'ORS § 60.787; ORS § 63.787', 'https://sos.oregon.gov/business/Pages/annual-report.aspx', 1);

-- FinCEN BOI Interaction
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-016', 'OR-REP-016', 'FinCEN BOI Report — Oregon Entity Interaction', 'Oregon LLCs, corporations, and other entities formed by filing with the Oregon Secretary of State are "reporting companies" under the Corporate Transparency Act and must file Beneficial Ownership Information (BOI) reports with FinCEN unless exempt. Oregon entities formed before January 1, 2024 had until January 1, 2025 to file initial reports (subject to court-ordered extensions). Entities formed after January 1, 2024 must file within 90 days of formation (30 days for formations after January 1, 2025). Oregon SOS does not collect BOI data — this is a separate federal filing.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '2024-01-01', '31 USC § 5336; 31 CFR Part 1010.380', 'https://www.fincen.gov/boi', 1);

-- Tax Return Filing Deadlines
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-017', 'OR-REP-017', 'Oregon Personal Income Tax Return Filing Deadline', 'Oregon personal income tax returns (Form OR-40 for residents, OR-40-N for nonresidents, OR-40-P for part-year residents) are due April 15 for calendar-year taxpayers. Automatic 6-month extension available by filing federal extension (Form 4868) or Oregon extension (payment voucher). Extension extends time to file, not time to pay — interest and penalties accrue on unpaid tax after April 15. Pass-through entity owners report their distributive share on personal returns.', 'REPORTING', 'STATE', 'OR', '["LLC","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 314.385; ORS § 316.577', 'https://www.oregon.gov/dor/programs/individuals/pages/pit.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-018', 'OR-REP-018', 'Oregon Corporate Excise/Income Tax Return Filing Deadline', 'Oregon corporate excise tax returns (Form OR-20) and corporate income tax returns (Form OR-20-INC) are due on the 15th day of the 4th month following the close of the tax year (April 15 for calendar-year C corporations). S corporations file Form OR-20-S by the 15th day of the 3rd month (March 15). Extensions available: 6 months for C corps (automatic with federal extension), 6 months for S corps. Estimated tax payments required quarterly if expected tax exceeds $1,000.', 'REPORTING', 'STATE', 'OR', '["CORPORATION","S_CORP"]', '2024-01-01', 'ORS § 314.385; ORS § 317.097', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-excise-income.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-019', 'OR-REP-019', 'Oregon Partnership Return Filing Deadline', 'Oregon partnerships file Form OR-65 (Oregon Partnership Return of Income) by the 15th day of the 3rd month following the close of the tax year (March 15 for calendar-year partnerships). The partnership return is informational — partnerships do not pay Oregon income tax at the entity level (unless PTE-E is elected). Each partner receives Schedule K-1 showing their distributive share. Automatic 6-month extension available with federal extension. Late filing penalty is $100 per partner per month.', 'REPORTING', 'STATE', 'OR', '["PARTNERSHIP"]', '2024-01-01', 'ORS § 314.385; ORS § 314.840', 'https://www.oregon.gov/dor/programs/businesses/pages/partnership.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-020', 'OR-REP-020', 'Oregon CAT Annual Return Filing Deadline', 'Oregon Corporate Activity Tax annual returns are due April 15 following the close of the calendar year. All businesses registered for the CAT must file, even if no tax is due (commercial activity between $750,000 and $1 million). Extension available to October 15 with a valid federal extension. Quarterly estimated payments due April 15, July 15, October 15, and January 15 if annual CAT liability exceeds $5,000. Underpayment penalties and interest apply to late estimated payments.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 317A.137; ORS § 317A.140', 'https://www.oregon.gov/dor/programs/businesses/pages/corporate-activity-tax.aspx', 1);

-- Oregon BOLI Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-021', 'OR-REP-021', 'Oregon Bureau of Labor and Industries (BOLI) — Wage Records', 'Oregon employers must maintain payroll records for at least 3 years showing employee names, addresses, hours worked, wages paid, deductions, and dates of payment. Records must be available for inspection by BOLI upon request. Oregon requires itemized pay stubs showing gross wages, net wages, and itemized deductions each pay period. Employers must pay employees at least monthly and must establish regular paydays. Final paychecks due within specific timeframes (immediately to 5 business days depending on circumstances).', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 652.140; ORS § 652.150; ORS § 652.190', 'https://www.oregon.gov/boli/employers/pages/default.aspx', 1);

INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-022', 'OR-REP-022', 'Oregon Predictive Scheduling Reporting (Portland)', 'Employers in Portland with 500+ employees worldwide in retail, food service, or hospitality must provide work schedules at least 14 days in advance. Schedule changes within 14 days trigger premium pay (time-and-a-half for less than 7 days notice). Employers must provide "right to rest" (10 hours between closing and opening shifts). Employers must offer additional hours to existing part-time employees before hiring new workers. Records of schedules and schedule changes must be maintained for 3 years.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'Portland City Code § 9.30.010-9.30.120', 'https://www.portland.gov/bhr/scheduling', 1);

-- Oregon Paid Leave Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-023', 'OR-REP-023', 'Oregon Paid Leave Contribution Reporting', 'Employers must report Paid Leave contributions quarterly on Form OQ. Reports must include total subject wages and contributions (employee 0.6% + employer 0.4% for 25+ employee firms). Employers must provide employees written notice of Paid Leave program rights. Employers with approved equivalent plans may opt out of the state program but must still report. Model notice must be posted in the workplace. Annual notice to employees required. Benefits provide 12 weeks paid leave (up to 14 for pregnancy complications).', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 657B.150; ORS § 657B.340', 'https://paidleave.oregon.gov/employers/', 1);

-- Oregon Secretary of State Charity Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-024', 'OR-REP-024', 'Oregon Charitable Organization Registration and Reporting', 'Charitable organizations soliciting contributions in Oregon must register with the Oregon Department of Justice (DOJ) Charitable Activities Section before soliciting. Annual financial reports are due within 4 months and 15 days after the fiscal year end. Organizations receiving less than $25,000 annually may file a simplified report. IRS Form 990 may satisfy the financial reporting requirement if filed timely. Registration renewal is automatic upon filing the annual report. Failure to register or report can result in injunctive action.', 'REPORTING', 'STATE', 'OR', '["NONPROFIT"]', '2024-01-01', 'ORS § 128.610-128.769', 'https://www.oregon.gov/doj/charitable-activities/pages/default.aspx', 1);

-- Oregon Data Breach Notification
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-025', 'OR-REP-025', 'Oregon Data Breach Notification', 'Any person or entity that owns or licenses personal information of Oregon consumers must notify affected consumers within 45 days of discovering a breach of security. If more than 250 consumers are affected, must also notify the Oregon Attorney General. Notice must describe the breach, type of information compromised, and contact information. Oregon''s definition of "personal information" includes SSN, driver''s license, financial account numbers, health information, and biometric data. Encryption is a safe harbor if the key was not also compromised.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 646A.604', 'https://www.oregon.gov/doj/consumer-protection/pages/data-breach-notification.aspx', 1);

-- Oregon Employment Discrimination Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-026', 'OR-REP-026', 'Oregon Workplace Harassment Prevention Training Records', 'Oregon employers with one or more employees must conduct anti-harassment training for all employees. As of 2020 (Oregon Workplace Fairness Act, SB 726), employers must train all employees within 6 months of hire or 6 months of the effective date. Training must cover protected classes, definitions of sexual assault and harassment, legal remedies, and how to report. Employers must maintain records of training completion for each employee. Records must be available for BOLI inspection.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 659A.375; SB 726 (2019)', 'https://www.oregon.gov/boli/employers/pages/anti-harassment.aspx', 1);

-- Oregon Liquor Tax Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-027', 'OR-REP-027', 'Oregon Liquor Control Commission (OLCC) Reporting', 'Licensed liquor establishments must comply with OLCC reporting requirements including: monthly privilege tax reports for breweries ($2.60/barrel) and wineries ($0.67/gallon), quarterly production reports, and annual renewal filings. OLCC licensees must maintain records of all purchases, sales, and inventory for 3 years. Marijuana licensees report through the Cannabis Tracking System (CTS/Metrc) with seed-to-sale traceability. OLCC audits may review records without prior notice.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 473.030; ORS § 475C.097', 'https://www.oregon.gov/olcc/pages/index.aspx', 1);

-- Oregon Construction Contractor Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-028', 'OR-REP-028', 'Oregon Construction Contractors Board (CCB) License Renewal Reporting', 'All construction contractors in Oregon must be licensed by the CCB. License must be renewed every two years. Renewal requires proof of current general liability insurance ($500,000 for residential, $1M for commercial), workers'' compensation insurance or exemption, and a surety bond ($20,000 residential, $75,000 commercial). CCB licensees must report any changes in officers, responsible managing individuals, or insurance within 30 days. Performing work without an active license is a Class A misdemeanor.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP"]', '2024-01-01', 'ORS § 701.021; ORS § 701.098; ORS § 701.102', 'https://www.oregon.gov/ccb/pages/default.aspx', 1);

-- Oregon Annual Withholding Reconciliation
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-029', 'OR-REP-029', 'Oregon Annual Withholding Tax Reconciliation (Form WR)', 'Employers must file an annual reconciliation of Oregon income tax withholding on Form WR (Oregon Annual Withholding Tax Reconciliation Report) by January 31. Form WR reconciles total Oregon withholding reported on quarterly Form OQ filings with the total shown on employees'' W-2 forms or 1099 forms. Employers must also file copies of W-2s and 1099s with the Oregon Department of Revenue by January 31 (electronic filing required for 50+ forms). Discrepancies result in assessment of additional tax plus penalties.', 'REPORTING', 'STATE', 'OR', '["LLC","CORPORATION","S_CORP","SOLE_PROPRIETORSHIP","PARTNERSHIP","NONPROFIT"]', '2024-01-01', 'ORS § 316.202; OAR 150-316-0359', 'https://www.oregon.gov/dor/programs/businesses/pages/payroll-withholding.aspx', 1);

-- Oregon Nonprofit Reporting
INSERT OR IGNORE INTO compliance_rules (id, code, title, description, category, level, state, entity_types, effective_date, source, source_url, is_active) VALUES
('or-rep-030', 'OR-REP-030', 'Oregon Nonprofit Annual Report and Property Tax Exemption Reporting', 'Oregon nonprofits must file an annual report with the Secretary of State ($50 fee) on the anniversary of formation. Separately, nonprofits claiming property tax exemption must file an application with the county assessor (initial filing) and maintain exempt use. Changes in property use must be reported to the assessor within 30 days. Nonprofits with tax-exempt status must file IRS Form 990 (or 990-EZ, 990-N) and make it publicly available upon request. Oregon DOJ may request financial reports from charitable organizations at any time.', 'REPORTING', 'STATE', 'OR', '["NONPROFIT"]', '2024-01-01', 'ORS § 65.787; ORS § 307.130; ORS § 128.610', 'https://sos.oregon.gov/business/Pages/annual-report.aspx', 1);
