-- Seed: Document Retention Rules sourced from Federal and California law
-- Each rule cites the actual statute, regulation, or requirement

-- ============================================================
-- FEDERAL TAX RECORDS (IRS)
-- ============================================================

INSERT OR IGNORE INTO retention_rules (id, title, description, document_types, retention_years, retention_months, retention_from, basis, legal_citation, jurisdiction, purposes, storage_requirements, disposal_method, applies_to_entity_types, applies_to_industries, penalty_for_non_compliance, notes, is_active, effective_date, source_url)
VALUES
('RET-FED-TAX-001', 'Federal Tax Returns', 'Business income tax returns and supporting documentation must be retained for the period of limitations on filing amendments or claiming refunds.', '["TAX_RETURN","FINANCIAL_STATEMENT"]', 3, 0, 'TAX_YEAR_END', 'FEDERAL_STATUTE', '26 USC § 6501(a) — Statute of limitations for assessment', 'FEDERAL', '["TAX_AUDIT","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'IRS may assess additional tax within 3 years; extends to 6 years if >25% gross income omitted (§ 6501(e)); no limit for fraud (§ 6501(c))', 'Keep 7 years as best practice to cover the 6-year substantial omission rule plus buffer', 1, '1954-08-16', 'https://www.law.cornell.edu/uscode/text/26/6501'),

('RET-FED-TAX-002', 'Employment Tax Records', 'Records of employment taxes (941, 940, W-2, W-4) must be available for IRS review for at least 4 years after the tax becomes due or is paid, whichever is later.', '["TAX_RETURN","W9","TRAINING_RECORD"]', 4, 0, 'TAX_YEAR_END', 'FEDERAL_REGULATION', '26 CFR § 31.6001-1 — Records of employers', 'FEDERAL', '["TAX_AUDIT","EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Failure to maintain: penalty under IRC § 6721-6722, up to $290 per return (2024)', 'Includes Forms W-2, W-4, 941, 940, 1099 series', 1, '1954-08-16', 'https://www.law.cornell.edu/cfr/text/26/section-31.6001-1'),

('RET-FED-TAX-003', 'Asset and Depreciation Records', 'Records supporting the cost basis, depreciation, and disposition of business assets must be kept until the period of limitations expires for the year of disposition.', '["FINANCIAL_STATEMENT","TAX_RETURN"]', 7, 0, 'LAST_ACTION_DATE', 'FEDERAL_STATUTE', '26 USC § 6001 — Records and returns generally', 'FEDERAL', '["TAX_AUDIT","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Inability to substantiate basis may result in zero basis assignment and full gain recognition', 'Keep for life of asset plus 3-7 years after disposition', 1, '1954-08-16', 'https://www.law.cornell.edu/uscode/text/26/6001'),

-- ============================================================
-- FEDERAL EMPLOYMENT RECORDS
-- ============================================================

('RET-FED-EMP-001', 'FLSA Payroll Records', 'Fair Labor Standards Act requires employers to preserve payroll records, collective bargaining agreements, sales and purchase records for at least 3 years.', '["FINANCIAL_STATEMENT","EMPLOYEE_HANDBOOK"]', 3, 0, 'LAST_ACTION_DATE', 'FEDERAL_STATUTE', '29 USC § 211(c); 29 CFR § 516.5 — FLSA Records to be preserved', 'FEDERAL', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE","REGULATORY_AUDIT"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'WHD investigation; back wages up to 2 years (3 years for willful); liquidated damages equal to back wages', 'Includes basic payroll data: name, address, DOB, sex, occupation, time/day workweek begins, hours per day/week, rate of pay, deductions, wages paid', 1, '1938-06-25', 'https://www.law.cornell.edu/cfr/text/29/section-516.5'),

('RET-FED-EMP-002', 'FLSA Supplementary Records', 'Wage computation records, time cards, piece work tickets, order/shipping records must be preserved for 2 years.', '["TRAINING_RECORD"]', 2, 0, 'LAST_ACTION_DATE', 'FEDERAL_REGULATION', '29 CFR § 516.6 — Records to be preserved 2 years', 'FEDERAL', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Same as FLSA payroll records — WHD investigation and back pay liability', 'Time cards, wage rate tables, work schedules, order/shipping/billing records', 1, '1938-06-25', 'https://www.law.cornell.edu/cfr/text/29/section-516.6'),

('RET-FED-EMP-003', 'Title VII / ADA / GINA Personnel Records', 'Employers with 15+ employees must keep all personnel and employment records for 1 year from date of making the record or personnel action, whichever is later.', '["EMPLOYEE_HANDBOOK","TRAINING_RECORD","ANTI_HARASSMENT_POLICY"]', 1, 0, 'CREATION_DATE', 'FEDERAL_REGULATION', '29 CFR § 1602.14 — Preservation of records made or kept', 'FEDERAL', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'EEOC investigation; Title VII allows compensatory + punitive damages up to $300K; ADA same', 'If charge filed, preserve all records until final disposition. Extends to 2 years for federal contractors (EO 11246)', 1, '1964-07-02', 'https://www.law.cornell.edu/cfr/text/29/section-1602.14'),

('RET-FED-EMP-004', 'ADEA Age Discrimination Records', 'Payroll records under ADEA must be preserved for 3 years; personnel records related to hiring, promotion, demotion, transfer, layoff, termination for 1 year.', '["EMPLOYEE_HANDBOOK","TRAINING_RECORD"]', 3, 0, 'CREATION_DATE', 'FEDERAL_REGULATION', '29 CFR § 1627.3 — Records to be made or kept', 'FEDERAL', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Liquidated damages (double back pay) for willful violations; EEOC enforcement', 'Employee benefit plans and seniority/merit systems: keep for full period plan is in effect plus 1 year after termination', 1, '1967-12-15', 'https://www.law.cornell.edu/cfr/text/29/section-1627.3'),

('RET-FED-EMP-005', 'FMLA Leave Records', 'Family and Medical Leave Act records including leave dates, hours, notices, policies, premium payments must be kept for 3 years.', '["EMPLOYEE_HANDBOOK","TRAINING_RECORD"]', 3, 0, 'CREATION_DATE', 'FEDERAL_REGULATION', '29 CFR § 825.500 — Recordkeeping requirements', 'FEDERAL', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE","ENCRYPTED_STORAGE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'WHD enforcement; back pay, benefits restoration, liquidated damages, attorney fees', 'Medical certifications must be maintained in separate confidential files (ADA requirement)', 1, '1993-02-05', 'https://www.law.cornell.edu/cfr/text/29/section-825.500'),

('RET-FED-EMP-006', 'I-9 Employment Eligibility', 'Form I-9 must be retained for 3 years after date of hire or 1 year after employment ends, whichever is later.', '["OTHER"]', 3, 0, 'CREATION_DATE', 'FEDERAL_STATUTE', '8 USC § 1324a(b)(3) — Retention of verification form; 8 CFR § 274a.2', 'FEDERAL', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE","REGULATORY_AUDIT"]', '["DIGITAL_ACCEPTABLE","TAMPER_EVIDENT"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Civil penalties $252-$2,507 per I-9 violation (2024); pattern violations: criminal penalties', 'E-Verify records follow same retention. Must be available within 3 days of ICE inspection request.', 1, '1986-11-06', 'https://www.law.cornell.edu/uscode/text/8/1324a'),

-- ============================================================
-- FEDERAL SAFETY (OSHA)
-- ============================================================

('RET-FED-OSHA-001', 'OSHA Injury/Illness Records', 'OSHA 300, 300A, and 301 forms must be retained for 5 years following the end of the calendar year the records cover.', '["SAFETY_PLAN","TRAINING_RECORD"]', 5, 0, 'TAX_YEAR_END', 'FEDERAL_REGULATION', '29 CFR § 1904.33 — Retention and updating of old OSHA 300 Logs', 'FEDERAL', '["LEGAL_COMPLIANCE","REGULATORY_AUDIT","EMPLOYMENT_RECORDS"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Citations up to $16,131 per violation; willful: up to $161,323 (2024)', 'Employers with 10 or fewer employees in most industries are exempt from routine recordkeeping', 1, '1970-12-29', 'https://www.law.cornell.edu/cfr/text/29/section-1904.33'),

('RET-FED-OSHA-002', 'OSHA Exposure/Medical Records', 'Employee exposure and medical records related to toxic substances or harmful physical agents must be retained for duration of employment plus 30 years.', '["SAFETY_PLAN","TRAINING_RECORD"]', 30, 0, 'EMPLOYEE_SEPARATION', 'FEDERAL_REGULATION', '29 CFR § 1910.1020 — Access to employee exposure and medical records', 'FEDERAL', '["LEGAL_COMPLIANCE","EMPLOYMENT_RECORDS","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE","ENCRYPTED_STORAGE","OFFSITE_BACKUP"]', 'ARCHIVE_THEN_DESTROY', '"ALL"', '"ALL"', 'Citations; also used as evidence in toxic tort litigation with extended statutes of limitations', 'This is the longest mandatory retention period in federal employment law. Transfer records if business closes.', 1, '1970-12-29', 'https://www.law.cornell.edu/cfr/text/29/section-1910.1020'),

-- ============================================================
-- FEDERAL CORPORATE/FINANCIAL
-- ============================================================

('RET-FED-CORP-001', 'SOX Financial Records', 'Sarbanes-Oxley requires retention of audit work papers and records relevant to the audit or review for 7 years from the conclusion of the audit or review.', '["AUDIT_REPORT","FINANCIAL_STATEMENT","SOC2_REPORT"]', 7, 0, 'AUDIT_COMPLETION', 'FEDERAL_STATUTE', '15 USC § 7213(a)(2)(A)(i) — SOX § 802; 18 USC § 1520', 'FEDERAL', '["LEGAL_COMPLIANCE","REGULATORY_AUDIT","LITIGATION_READINESS"]', '["DIGITAL_WITH_AUDIT_TRAIL","TAMPER_EVIDENT"]', 'SECURE_DELETE', '["CORPORATION","S_CORP"]', '"ALL"', 'Criminal: up to 20 years imprisonment and fines for knowing destruction (18 USC § 1520)', 'Applies to public companies and their auditors. Private companies should follow as best practice.', 1, '2002-07-30', 'https://www.law.cornell.edu/uscode/text/18/1520'),

('RET-FED-CORP-002', 'BOI Reports', 'Beneficial Ownership Information reports filed with FinCEN. FinCEN retains; filers should keep copies of what was submitted.', '["BOI_REPORT"]', 5, 0, 'FILING_DATE', 'FEDERAL_STATUTE', '31 USC § 5336 — Corporate Transparency Act; 31 CFR § 1010.380', 'FEDERAL', '["LEGAL_COMPLIANCE","REGULATORY_AUDIT"]', '["DIGITAL_ACCEPTABLE","ENCRYPTED_STORAGE"]', 'SECURE_DELETE', '["LLC","CORPORATION","S_CORP","PARTNERSHIP"]', '"ALL"', 'Civil penalties up to $591/day; criminal: up to 2 years imprisonment and $10,000 fine', 'Must update within 30 days of any change in beneficial owner information', 1, '2024-01-01', 'https://www.law.cornell.edu/uscode/text/31/5336'),

('RET-FED-CORP-003', 'Corporate Formation Documents', 'Articles of incorporation, bylaws, operating agreements, and amendments should be retained permanently as foundational governance documents.', '["ARTICLES_OF_INCORPORATION","BYLAWS","OPERATING_AGREEMENT"]', 0, 0, 'PERMANENT', 'BEST_PRACTICE', 'State corporation codes; UCC; common law fiduciary duty', 'FEDERAL', '["LEGAL_COMPLIANCE","LITIGATION_READINESS","REFERENCE","HISTORICAL"]', '["DIGITAL_WITH_AUDIT_TRAIL","CERTIFIED_COPY"]', 'NO_DESTRUCTION', '"ALL"', '"ALL"', 'Inability to produce may result in piercing corporate veil, loss of liability protection', 'Keep permanently. These prove the entity exists and define its governance.', 1, '1800-01-01', ''),

-- ============================================================
-- FEDERAL PRIVACY
-- ============================================================

('RET-FED-PRIV-001', 'Privacy Policy Records', 'Records of privacy policies, consent forms, and data processing agreements should be retained for the duration of any applicable statute of limitations on privacy claims.', '["PRIVACY_POLICY","DATA_PROCESSING_AGREEMENT"]', 6, 0, 'LAST_ACTION_DATE', 'BEST_PRACTICE', 'FTC Act § 5; COPPA; state privacy laws (CCPA/CPRA Cal. Civ. Code § 1798.100 et seq.)', 'FEDERAL', '["LEGAL_COMPLIANCE","LITIGATION_READINESS","REGULATORY_AUDIT"]', '["DIGITAL_WITH_AUDIT_TRAIL"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'FTC enforcement actions; state AG enforcement; private right of action under CCPA', 'Keep ALL versions of privacy policies with effective dates. Critical for litigation defense.', 1, '2000-04-21', ''),

-- ============================================================
-- FEDERAL CONTRACTS
-- ============================================================

('RET-FED-CON-001', 'Government Contract Records', 'Federal contractors must retain records for 3 years after final payment on the contract.', '["CONTRACT","FINANCIAL_STATEMENT","AUDIT_REPORT"]', 3, 0, 'CONTRACT_EXPIRATION', 'FEDERAL_REGULATION', '48 CFR § 4.703 — FAR Subpart 4.7 Contractor Records Retention', 'FEDERAL', '["LEGAL_COMPLIANCE","REGULATORY_AUDIT","LITIGATION_READINESS"]', '["DIGITAL_WITH_AUDIT_TRAIL"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'False Claims Act liability (31 USC § 3729): treble damages plus $13,508-$27,018 per claim', 'If audit or investigation is pending, records must be retained until resolution regardless of 3-year rule', 1, '1984-04-01', 'https://www.law.cornell.edu/cfr/text/48/section-4.703'),

-- ============================================================
-- CALIFORNIA-SPECIFIC RECORDS
-- ============================================================

('RET-CA-EMP-001', 'CA Payroll Records', 'California employers must keep payroll records for at least 4 years (covers the 4-year statute of limitations for wage claims under CCP § 337).', '["FINANCIAL_STATEMENT"]', 4, 0, 'CREATION_DATE', 'STATE_STATUTE', 'Cal. Lab. Code § 1174; CCP § 337; IWC Wage Orders', 'CA', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'PAGA penalties: $100/employee first violation, $200/employee subsequent; waiting time penalties: up to 30 days wages', 'CA has longer retention than federal (4 vs 3 years) — always follow the longer requirement', 1, '1937-01-01', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1174&lawCode=LAB'),

('RET-CA-EMP-002', 'CA Personnel Files', 'California employers must retain personnel files for at least 3 years after separation (Lab. Code § 1198.5 access right lasts through employment).', '["EMPLOYEE_HANDBOOK","TRAINING_RECORD","ANTI_HARASSMENT_POLICY"]', 3, 0, 'EMPLOYEE_SEPARATION', 'STATE_STATUTE', 'Cal. Lab. Code § 1198.5; FEHA (Gov. Code § 12946)', 'CA', '["EMPLOYMENT_RECORDS","LEGAL_COMPLIANCE","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE","ENCRYPTED_STORAGE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'FEHA: unlimited compensatory damages, punitive damages, attorney fees; DFEH investigation', 'FEHA requires 4 years for discrimination-related records. Use 4 years as safe harbor.', 1, '1959-09-18', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=12946&lawCode=GOV'),

('RET-CA-TAX-001', 'CA Franchise Tax Board Records', 'California tax returns and supporting records should be kept for at least 4 years (FTB statute of limitations under R&TC § 19057).', '["TAX_RETURN","FINANCIAL_STATEMENT"]', 4, 0, 'TAX_YEAR_END', 'STATE_STATUTE', 'Cal. Rev. & Tax Code § 19057; § 19501', 'CA', '["TAX_AUDIT","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'FTB penalties: 5-25% of tax due for late filing; fraud: 75% penalty', 'If return not filed, no statute of limitations — keep records permanently for unfiled years', 1, '1929-01-01', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=19057&lawCode=RTC'),

('RET-CA-PRIV-001', 'CCPA/CPRA Consumer Request Records', 'Businesses must maintain records of consumer requests and how they were responded to for at least 24 months.', '["PRIVACY_POLICY","DATA_PROCESSING_AGREEMENT","OTHER"]', 2, 0, 'CREATION_DATE', 'STATE_STATUTE', 'Cal. Civ. Code § 1798.130; 11 CCR § 7101', 'CA', '["LEGAL_COMPLIANCE","REGULATORY_AUDIT","PRIVACY"]', '["DIGITAL_WITH_AUDIT_TRAIL","ENCRYPTED_STORAGE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'CPPA enforcement: up to $2,500/violation, $7,500/intentional violation; private right of action for data breaches: $100-$750/consumer/incident', 'Must track: date of request, nature, manner of response, basis for denial if applicable', 1, '2020-01-01', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1798.130&lawCode=CIV'),

('RET-CA-CORP-001', 'CA Annual Statements of Information', 'Copies of Statements of Information (SI-100, SI-550) filed with CA Secretary of State should be retained permanently.', '["ANNUAL_REPORT","COMPLIANCE_CERTIFICATE"]', 0, 0, 'PERMANENT', 'STATE_STATUTE', 'Cal. Corp. Code § 1502 (corporations); § 17702.09 (LLCs)', 'CA', '["LEGAL_COMPLIANCE","REFERENCE","HISTORICAL"]', '["DIGITAL_ACCEPTABLE"]', 'NO_DESTRUCTION', '["LLC","CORPORATION","S_CORP","NONPROFIT","COOPERATIVE"]', '"ALL"', '$250 penalty for late filing (Corp. Code § 2204); may lead to suspension/forfeiture by FTB', 'Due within 90 days of formation, then every year (LLCs biennial). Filed via bizfile.sos.ca.gov.', 1, '1977-01-01', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1502&lawCode=CORP'),

('RET-CA-INS-001', 'CA Workers Compensation Records', 'Workers compensation records, including injury reports and claim files, must be retained for 5 years after injury (or longer if claim is pending).', '["INSURANCE_CERTIFICATE","SAFETY_PLAN"]', 5, 0, 'CLAIM_RESOLUTION', 'STATE_STATUTE', 'Cal. Lab. Code § 6410; 8 CCR § 14300.33', 'CA', '["LEGAL_COMPLIANCE","INSURANCE_CLAIMS","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE"]', 'ARCHIVE_THEN_DESTROY', '"ALL"', '"ALL"', 'DIR penalties; WCAB jurisdiction for up to 5 years; fraud penalties under Ins. Code § 1871.4', 'Statute of limitations for WC claims: 1 year from injury or last provision of benefits', 1, '1913-01-01', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=6410&lawCode=LAB'),

-- ============================================================
-- GENERAL BUSINESS RECORDS
-- ============================================================

('RET-GEN-001', 'Business Licenses and Permits', 'Current and historical business licenses and permits should be retained for the life of the entity plus 3 years.', '["BUSINESS_LICENSE","COMPLIANCE_CERTIFICATE"]', 0, 0, 'PERMANENT', 'BEST_PRACTICE', 'Various municipal codes; state licensing statutes', 'FEDERAL', '["LEGAL_COMPLIANCE","REFERENCE","LITIGATION_READINESS"]', '["DIGITAL_ACCEPTABLE","CERTIFIED_COPY"]', 'NO_DESTRUCTION', '"ALL"', '"ALL"', 'Operating without valid license: misdemeanor in most jurisdictions; contract voidability under Bus. & Prof. Code § 7031 (CA)', 'Keep all versions showing continuous licensing history', 1, '1800-01-01', ''),

('RET-GEN-002', 'Insurance Policies', 'All insurance policies (GL, E&O, D&O, cyber, WC) should be retained permanently or until all possible claims under the policy period have been resolved.', '["INSURANCE_CERTIFICATE"]', 0, 0, 'PERMANENT', 'BEST_PRACTICE', 'Common law; occurrence-based vs claims-made policy considerations', 'FEDERAL', '["INSURANCE_CLAIMS","LITIGATION_READINESS","LEGAL_COMPLIANCE"]', '["DIGITAL_ACCEPTABLE","OFFSITE_BACKUP"]', 'NO_DESTRUCTION', '"ALL"', '"ALL"', 'Inability to locate policy may forfeit coverage for latent claims (asbestos, environmental, long-tail torts)', 'Occurrence policies can be triggered decades later. NEVER destroy insurance policies.', 1, '1800-01-01', ''),

('RET-GEN-003', 'Contracts and Agreements', 'Executed contracts should be retained for the life of the contract plus the applicable statute of limitations (4-6 years in most states).', '["CONTRACT","DATA_PROCESSING_AGREEMENT"]', 6, 0, 'CONTRACT_EXPIRATION', 'BEST_PRACTICE', 'UCC § 2-725 (4 years goods); CCP § 337 (4 years CA written); various state SOLs', 'FEDERAL', '["LEGAL_COMPLIANCE","LITIGATION_READINESS","REFERENCE"]', '["DIGITAL_WITH_AUDIT_TRAIL"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Inability to produce contract may result in unfavorable interpretation or inability to enforce terms', 'Include all amendments, addenda, and correspondence related to contract interpretation', 1, '1800-01-01', ''),

('RET-GEN-004', 'Meeting Minutes and Resolutions', 'Corporate/LLC meeting minutes and written resolutions should be retained permanently as part of the entity permanent record.', '["MEETING_MINUTES","RESOLUTION"]', 0, 0, 'PERMANENT', 'BEST_PRACTICE', 'State corporation codes (Cal. Corp. Code § 1500); LLC operating agreements', 'FEDERAL', '["LEGAL_COMPLIANCE","CORPORATE_GOVERNANCE","LITIGATION_READINESS","HISTORICAL"]', '["DIGITAL_WITH_AUDIT_TRAIL"]', 'NO_DESTRUCTION', '["LLC","CORPORATION","S_CORP","NONPROFIT","COOPERATIVE"]', '"ALL"', 'Failure to maintain may support veil-piercing claims; loss of limited liability protection', 'These prove the entity operates as a separate legal entity and not an alter ego', 1, '1800-01-01', ''),

('RET-GEN-005', 'EIN Assignment Letters', 'IRS EIN assignment letters (CP 575) should be retained permanently. Cannot be reissued.', '["EIN_LETTER"]', 0, 0, 'PERMANENT', 'BEST_PRACTICE', 'IRS procedures; IRC § 6109', 'FEDERAL', '["TAX_AUDIT","LEGAL_COMPLIANCE","REFERENCE"]', '["DIGITAL_ACCEPTABLE","OFFSITE_BACKUP"]', 'NO_DESTRUCTION', '"ALL"', '"ALL"', 'Without EIN letter, entity cannot open bank accounts, file taxes, or onboard with many vendors', 'The IRS does not reissue CP 575 letters. A 147C verification letter can be obtained but is not identical.', 1, '1974-01-01', ''),

-- ============================================================
-- DIGITAL/TECHNOLOGY RECORDS
-- ============================================================

('RET-TECH-001', 'Security Incident Records', 'Records of security incidents, breach notifications, and incident response actions should be retained for at least 6 years.', '["INCIDENT_RESPONSE_PLAN","AUDIT_REPORT","PENETRATION_TEST"]', 6, 0, 'CREATION_DATE', 'BEST_PRACTICE', 'CCPA data breach provisions (Civ. Code § 1798.150); HIPAA § 164.530(j); SOX; state breach notification laws', 'FEDERAL', '["LEGAL_COMPLIANCE","LITIGATION_READINESS","REGULATORY_AUDIT","EVIDENTIARY"]', '["DIGITAL_WITH_AUDIT_TRAIL","ENCRYPTED_STORAGE","TAMPER_EVIDENT"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'CCPA: $100-$750/consumer for breach; FTC enforcement; state AG enforcement; class action exposure', 'Keep all forensic reports, notification records, remediation documentation, and regulatory correspondence', 1, '2003-07-01', ''),

('RET-TECH-002', 'System Access Logs', 'Authentication, access, and audit logs for systems containing personal or financial data should be retained for at least 1 year (3 years for financial systems).', '["AUDIT_REPORT"]', 3, 0, 'CREATION_DATE', 'INDUSTRY_STANDARD', 'PCI DSS Req. 10.7; SOC 2 Trust Services Criteria CC7.2; NIST SP 800-92', 'FEDERAL', '["LEGAL_COMPLIANCE","REGULATORY_AUDIT","EVIDENTIARY","LITIGATION_READINESS"]', '["DIGITAL_WITH_AUDIT_TRAIL","ENCRYPTED_STORAGE"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'PCI DSS non-compliance: $5,000-$100,000/month; SOC 2 audit failure; breach liability', 'Include login/logout, privilege changes, data access, admin actions, failed attempts', 1, '2004-12-15', ''),

('RET-TECH-003', 'Business Continuity and DR Plans', 'Business continuity and disaster recovery plans should be retained for the current version plus at least 3 prior versions or 5 years, whichever is longer.', '["BUSINESS_CONTINUITY_PLAN","INCIDENT_RESPONSE_PLAN"]', 5, 0, 'CREATION_DATE', 'BEST_PRACTICE', 'NIST SP 800-34; ISO 22301; state insurance department requirements', 'FEDERAL', '["LEGAL_COMPLIANCE","REFERENCE","REGULATORY_AUDIT"]', '["DIGITAL_ACCEPTABLE","OFFSITE_BACKUP"]', 'SECURE_DELETE', '"ALL"', '"ALL"', 'Insurance claim denial for failure to maintain; regulatory findings; shareholder derivative suits', 'Test results and exercise reports should be retained alongside the plans', 1, '2010-05-01', ''),

-- ============================================================
-- LITIGATION HOLD (SPECIAL)
-- ============================================================

('RET-LIT-001', 'Litigation Hold — All Documents', 'When litigation is reasonably anticipated, all potentially relevant documents must be preserved regardless of normal retention schedules until the hold is lifted.', '["OTHER"]', 0, 0, 'PERMANENT', 'LITIGATION_HOLD', 'FRCP Rule 37(e); Zubulake v. UBS Warburg; Cal. CCP § 2023.010 (misuse of discovery)', 'FEDERAL', '["LITIGATION_READINESS","EVIDENTIARY","LEGAL_COMPLIANCE"]', '["DIGITAL_WITH_AUDIT_TRAIL","TAMPER_EVIDENT"]', 'NO_DESTRUCTION', '"ALL"', '"ALL"', 'Spoliation sanctions: adverse inference, issue preclusion, default judgment, contempt, monetary sanctions, criminal obstruction (18 USC § 1519)', 'Litigation hold overrides ALL other retention rules. Must be issued as soon as litigation is reasonably anticipated, not when complaint is filed.', 1, '1800-01-01', 'https://www.law.cornell.edu/rules/frcp/rule_37');
