/**
 * Legal disclaimers for Vernen Legal Compliance.
 * Appended to compliance reports, generated documents, audit results, and form guidance.
 */

/**
 * Returns an HTML disclaimer to append to every compliance report.
 */
export function getReportDisclaimer(): string {
  return `
    <div style="margin-top: 2rem; padding: 1.5rem; background: #fff8e1; border: 1px solid #c8a951; border-radius: 6px; font-size: 0.85rem; line-height: 1.6; color: #333;">
      <div style="font-weight: 700; color: #1a2744; font-size: 0.95rem; margin-bottom: 0.75rem; text-transform: uppercase; letter-spacing: 0.5px;">Important Legal Disclaimer</div>
      <p style="margin-bottom: 0.6rem;"><strong>NOT LEGAL ADVICE.</strong> This compliance report is provided by Vernen Legal Compliance for general informational purposes only. It does not constitute legal advice, and should not be relied upon as such. Vernen Legal Compliance is not a law firm and does not provide legal representation.</p>
      <p style="margin-bottom: 0.6rem;"><strong>NO ATTORNEY-CLIENT RELATIONSHIP.</strong> No attorney-client relationship is created between you and Vernen Legal Compliance by your use of this report or any related services. The information in this report does not create any confidential or privileged relationship.</p>
      <p style="margin-bottom: 0.6rem;"><strong>CONSULT A LICENSED ATTORNEY.</strong> You should consult with a licensed attorney in your jurisdiction before making any legal or business decisions based on the contents of this report. An attorney can provide advice tailored to your specific circumstances.</p>
      <p style="margin-bottom: 0.6rem;"><strong>LAWS CHANGE FREQUENTLY.</strong> Federal and state laws, regulations, and administrative rules are subject to frequent amendment, repeal, and reinterpretation. The information in this report is based on publicly available sources as of the date of generation and may not reflect the most recent legal changes.</p>
      <p style="margin-bottom: 0;"><strong>VERIFY WITH OFFICIAL SOURCES.</strong> You are responsible for verifying all information contained in this report with official federal and state government sources, including relevant Secretary of State offices, state agencies, and the U.S. Code of Federal Regulations.</p>
    </div>`;
}

/**
 * Returns an HTML disclaimer for generated legal documents and templates.
 */
export function getDocumentDisclaimer(): string {
  return `
    <div style="margin-top: 2rem; padding: 1.5rem; background: #fff8e1; border: 1px solid #c8a951; border-radius: 6px; font-size: 0.85rem; line-height: 1.6; color: #333;">
      <div style="font-weight: 700; color: #1a2744; font-size: 0.95rem; margin-bottom: 0.75rem; text-transform: uppercase; letter-spacing: 0.5px;">Document Disclaimer</div>
      <p style="margin-bottom: 0.6rem;"><strong>NOT LEGAL ADVICE.</strong> This document is a template generated by Vernen Legal Compliance for general informational purposes only. It does not constitute legal advice. Vernen Legal Compliance is not a law firm and is not your attorney.</p>
      <p style="margin-bottom: 0.6rem;"><strong>NO ATTORNEY-CLIENT RELATIONSHIP.</strong> The generation, delivery, or use of this document does not create an attorney-client relationship between you and Vernen Legal Compliance.</p>
      <p style="margin-bottom: 0.6rem;"><strong>MUST BE REVIEWED BY A LICENSED ATTORNEY.</strong> This document is a template only and has not been tailored to your specific legal needs, business circumstances, or jurisdiction. You must have this document reviewed, customized, and approved by a licensed attorney before using it for any legal, business, or regulatory purpose. Using this template without independent legal review is at your own risk.</p>
      <p style="margin-bottom: 0.6rem;"><strong>LAWS CHANGE FREQUENTLY.</strong> The legal requirements reflected in this template are based on publicly available statutes and regulations as of the date of generation. Legal requirements vary by jurisdiction and are subject to change. This template may not reflect the most recent legal developments.</p>
      <p style="margin-bottom: 0;"><strong>VERIFY WITH OFFICIAL SOURCES.</strong> You are responsible for ensuring that any document you use complies with all applicable laws and regulations in your jurisdiction. Verify all legal requirements with official government sources and qualified legal counsel.</p>
    </div>`;
}

/**
 * Returns an HTML disclaimer for audit results.
 */
export function getAuditDisclaimer(): string {
  return `
    <div style="margin-top: 2rem; padding: 1.5rem; background: #fff8e1; border: 1px solid #c8a951; border-radius: 6px; font-size: 0.85rem; line-height: 1.6; color: #333;">
      <div style="font-weight: 700; color: #1a2744; font-size: 0.95rem; margin-bottom: 0.75rem; text-transform: uppercase; letter-spacing: 0.5px;">Audit Disclaimer</div>
      <p style="margin-bottom: 0.6rem;"><strong>NOT LEGAL ADVICE.</strong> These audit results are generated by an automated compliance analysis engine provided by Vernen Legal Compliance for general informational purposes only. They do not constitute legal advice, a legal opinion, or a professional compliance audit. Vernen Legal Compliance is not a law firm.</p>
      <p style="margin-bottom: 0.6rem;"><strong>NO ATTORNEY-CLIENT RELATIONSHIP.</strong> The generation or review of these audit results does not create an attorney-client relationship between you and Vernen Legal Compliance.</p>
      <p style="margin-bottom: 0.6rem;"><strong>NOT A SUBSTITUTE FOR PROFESSIONAL LEGAL REVIEW.</strong> Automated audit results are algorithmic assessments and are not a substitute for a comprehensive compliance audit or legal review conducted by a licensed attorney or qualified compliance professional. The absence of identified issues does not guarantee compliance with any law or regulation.</p>
      <p style="margin-bottom: 0.6rem;"><strong>LAWS CHANGE FREQUENTLY.</strong> Compliance requirements are based on publicly available statutes and regulations as of the date of the audit. Laws, regulations, and enforcement practices change frequently and may not be fully reflected in these results.</p>
      <p style="margin-bottom: 0;"><strong>VERIFY WITH OFFICIAL SOURCES.</strong> You should verify all audit findings with official federal and state government sources and consult with a licensed attorney or qualified compliance professional to confirm the accuracy and applicability of these results to your specific situation.</p>
    </div>`;
}

/**
 * Returns an HTML disclaimer for form guidance and assisted form completion.
 */
export function getFormDisclaimer(): string {
  return `
    <div style="margin-top: 2rem; padding: 1.5rem; background: #fff8e1; border: 1px solid #c8a951; border-radius: 6px; font-size: 0.85rem; line-height: 1.6; color: #333;">
      <div style="font-weight: 700; color: #1a2744; font-size: 0.95rem; margin-bottom: 0.75rem; text-transform: uppercase; letter-spacing: 0.5px;">Form Guidance Disclaimer</div>
      <p style="margin-bottom: 0.6rem;"><strong>NOT LEGAL ADVICE.</strong> This form guidance is provided by Vernen Legal Compliance for general informational purposes only. It does not constitute legal advice regarding how to complete, file, or submit any government form. Vernen Legal Compliance is not a law firm and is not your attorney.</p>
      <p style="margin-bottom: 0.6rem;"><strong>NO ATTORNEY-CLIENT RELATIONSHIP.</strong> Receiving form guidance through this Service does not create an attorney-client relationship between you and Vernen Legal Compliance.</p>
      <p style="margin-bottom: 0.6rem;"><strong>CONSULT A LICENSED ATTORNEY.</strong> Government forms often have significant legal consequences. Errors or omissions may result in penalties, rejection, or other adverse outcomes. You should consult with a licensed attorney or qualified tax professional before filing any government form based on guidance provided through this Service.</p>
      <p style="margin-bottom: 0.6rem;"><strong>LAWS CHANGE FREQUENTLY.</strong> Form requirements, filing deadlines, fee schedules, and associated regulations change frequently. The guidance provided may not reflect the most recent changes to forms or filing requirements in your jurisdiction.</p>
      <p style="margin-bottom: 0;"><strong>VERIFY WITH OFFICIAL SOURCES.</strong> Always obtain the most current version of any government form directly from the issuing agency's official website. Verify all filing requirements, deadlines, and fees with the relevant government authority.</p>
    </div>`;
}
