/**
 * Document templates for LEX-1 — the legal document generation engine.
 *
 * Each template uses variable substitution ({{VAR}}) and produces
 * substantial, professional legal content with proper disclaimers.
 */

// ---------------------------------------------------------------------------
// Shared components
// ---------------------------------------------------------------------------

const VERNEN_FOOTER = `
<footer style="margin-top:48px;padding-top:24px;border-top:2px solid #1a3a5c;font-size:12px;color:#666;text-align:center;">
  <p style="margin:4px 0;"><strong>Generated by Vernen Legal Compliance</strong></p>
  <p style="margin:4px 0;">Powered by LEX-1&trade; &mdash; Corporate Strategy &amp; Legal Architecture</p>
  <p style="margin:4px 0;">vernenlegal.com &bull; &copy; {{YEAR}} Vernen Legal Compliance. All rights reserved.</p>
  <p style="margin:12px 0 0;font-style:italic;font-size:11px;color:#999;">
    DISCLAIMER: This document is generated for informational purposes only and does not constitute legal advice.
    It should be reviewed by a licensed attorney before use. Vernen Legal Compliance is not a law firm and does
    not provide legal representation. Laws and regulations change frequently; verify all information is current
    before relying on this document.
  </p>
</footer>`;

const DOCUMENT_STYLE = `
<style>
  body { font-family: 'Georgia', 'Times New Roman', serif; color: #222; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 40px 24px; }
  h1 { font-size: 26px; color: #1a3a5c; border-bottom: 3px solid #1a3a5c; padding-bottom: 12px; margin-bottom: 24px; }
  h2 { font-size: 20px; color: #1a3a5c; margin-top: 32px; margin-bottom: 12px; }
  h3 { font-size: 16px; color: #333; margin-top: 24px; }
  p, li { font-size: 14px; }
  ul, ol { padding-left: 24px; }
  .header-meta { font-size: 13px; color: #555; margin-bottom: 32px; }
  .section { margin-bottom: 28px; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #f0f4f8; font-weight: bold; }
  .checklist-item { margin: 8px 0; }
  .checklist-item input[type="checkbox"] { margin-right: 8px; }
</style>`;

// ---------------------------------------------------------------------------
// PRIVACY POLICY TEMPLATE
// ---------------------------------------------------------------------------

export function generatePrivacyPolicyHtml(vars: {
  businessName: string;
  state: string;
  stateFull: string;
  websiteUrl: string;
  collectsEmail: boolean;
  collectsPayment: boolean;
  usesAnalytics: boolean;
  hasMinors: boolean;
  effectiveDate: string;
  entityType: string;
}): string {
  const year = new Date().getFullYear().toString();

  const dataCollectionItems: string[] = [];
  dataCollectionItems.push(`<li><strong>Device and Usage Information:</strong> We automatically collect information about your device, browser type, IP address, operating system, referring URLs, pages visited, and the dates and times of your visits.</li>`);

  if (vars.collectsEmail) {
    dataCollectionItems.push(`<li><strong>Contact Information:</strong> We collect your name, email address, phone number, and mailing address when you voluntarily provide this information through contact forms, account registration, newsletter sign-ups, or other interactions with our services.</li>`);
  }

  if (vars.collectsPayment) {
    dataCollectionItems.push(`<li><strong>Payment and Transaction Data:</strong> When you make a purchase or engage in a financial transaction, we collect billing information, credit or debit card numbers (processed securely through our third-party payment processor), billing address, and transaction history. We do not store complete credit card numbers on our servers.</li>`);
  }

  if (vars.usesAnalytics) {
    dataCollectionItems.push(`<li><strong>Analytics and Tracking Data:</strong> We use cookies, web beacons, pixel tags, and similar tracking technologies to collect information about your browsing behavior, preferences, and interactions with our website. This may include data collected by third-party analytics services such as Google Analytics.</li>`);
  }

  dataCollectionItems.push(`<li><strong>Communications Data:</strong> If you contact us via email, phone, or through our website, we retain records of that correspondence, including the content of your messages and our responses.</li>`);

  const ccpaSection = `
  <div class="section">
    <h2>9. California Privacy Rights (CCPA/CPRA)</h2>
    <p>If you are a California resident, the California Consumer Privacy Act (CCPA), as amended by the California Privacy Rights Act (CPRA), provides you with specific rights regarding your personal information:</p>
    <ul>
      <li><strong>Right to Know:</strong> You have the right to request that we disclose the categories and specific pieces of personal information we have collected about you, the categories of sources from which your personal information was collected, the business or commercial purpose for collecting your personal information, and the categories of third parties with whom we share your personal information.</li>
      <li><strong>Right to Delete:</strong> You have the right to request that we delete personal information we have collected from you, subject to certain exceptions provided by law.</li>
      <li><strong>Right to Correct:</strong> You have the right to request that we correct inaccurate personal information that we maintain about you.</li>
      <li><strong>Right to Opt-Out of Sale/Sharing:</strong> You have the right to opt out of the sale or sharing of your personal information. ${vars.businessName} does not sell personal information as defined under the CCPA/CPRA.</li>
      <li><strong>Right to Non-Discrimination:</strong> We will not discriminate against you for exercising any of your CCPA/CPRA rights.</li>
    </ul>
    <p>To exercise your California privacy rights, please contact us using the information provided in Section 12 below. We will respond to verifiable consumer requests within 45 days.</p>
  </div>`;

  const minorsSection = vars.hasMinors ? `
  <div class="section">
    <h2>10. Children's Privacy (COPPA Compliance)</h2>
    <p>We are committed to protecting the privacy of children. Our services may be accessed by individuals under the age of 13, and we comply with the Children's Online Privacy Protection Act (COPPA).</p>
    <ul>
      <li>We do not knowingly collect personal information from children under 13 without verifiable parental consent.</li>
      <li>If we learn that we have collected personal information from a child under 13 without parental consent, we will take steps to delete that information as quickly as possible.</li>
      <li>Parents or guardians who believe their child has provided personal information to us without their consent may contact us to request deletion of that information.</li>
      <li>We encourage parents and guardians to monitor their children's online activities and to help enforce this Privacy Policy.</li>
    </ul>
    <p>For users between the ages of 13 and 16, we comply with applicable state laws regarding the collection and use of minors' personal information, including obtaining opt-in consent where required.</p>
  </div>` : `
  <div class="section">
    <h2>10. Children's Privacy</h2>
    <p>Our services are not directed to individuals under the age of 13. We do not knowingly collect personal information from children under 13. If we learn that we have inadvertently collected personal information from a child under 13, we will take reasonable steps to delete that information as promptly as possible. If you believe that a child under 13 has provided personal information to us, please contact us using the information in Section 12.</p>
  </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy &mdash; ${vars.businessName}</title>
  ${DOCUMENT_STYLE}
</head>
<body>
  <h1>Privacy Policy</h1>
  <div class="header-meta">
    <p><strong>${vars.businessName}</strong></p>
    <p>Effective Date: ${vars.effectiveDate}</p>
    <p>Last Updated: ${vars.effectiveDate}</p>
    ${vars.websiteUrl !== "N/A" ? `<p>Website: ${vars.websiteUrl}</p>` : ""}
    <p>Governing Law: State of ${vars.stateFull}</p>
  </div>

  <div class="section">
    <h2>1. Introduction</h2>
    <p>${vars.businessName} ("Company," "we," "us," or "our") respects your privacy and is committed to protecting the personal information you share with us. This Privacy Policy describes how we collect, use, disclose, and safeguard your information when you visit our website${vars.websiteUrl !== "N/A" ? ` (${vars.websiteUrl})` : ""}, use our services, or otherwise interact with us.</p>
    <p>By accessing or using our services, you acknowledge that you have read, understood, and agree to be bound by this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not access or use our services.</p>
    <p>This Privacy Policy applies to all information collected through our website, mobile applications (if any), and any related services, sales, marketing, or events (collectively, the "Services").</p>
  </div>

  <div class="section">
    <h2>2. Information We Collect</h2>
    <p>We collect information in several ways, depending on how you interact with our Services:</p>
    <h3>2.1 Information You Provide Directly</h3>
    <ul>
      ${dataCollectionItems.join("\n      ")}
    </ul>
    <h3>2.2 Information Collected Automatically</h3>
    <p>When you access our Services, we may automatically collect certain information, including but not limited to your IP address, browser type, operating system, access times, and the pages you have viewed directly before and after accessing our website. This information is used to analyze trends, administer the site, track users' movements, and gather demographic information.</p>
  </div>

  <div class="section">
    <h2>3. How We Use Your Information</h2>
    <p>We use the information we collect for the following purposes:</p>
    <ul>
      <li>To provide, operate, and maintain our Services;</li>
      <li>To improve, personalize, and expand our Services;</li>
      <li>To understand and analyze how you use our Services;</li>
      <li>To develop new products, services, features, and functionality;</li>
      <li>To communicate with you, including for customer service, to provide you with updates and other information relating to our Services, and for marketing and promotional purposes (with your consent where required);</li>
      <li>To process transactions and send you related information, including purchase confirmations and invoices;</li>
      <li>To send you technical notices, updates, security alerts, and support and administrative messages;</li>
      <li>To respond to your comments, questions, and requests;</li>
      <li>To detect, investigate, and prevent fraudulent transactions and other illegal activities and protect the rights and property of ${vars.businessName} and others;</li>
      <li>To comply with legal obligations and enforce our terms and policies.</li>
    </ul>
  </div>

  <div class="section">
    <h2>4. Legal Bases for Processing (GDPR)</h2>
    <p>If you are located in the European Economic Area (EEA), United Kingdom, or Switzerland, we process your personal data based on the following legal grounds:</p>
    <ul>
      <li><strong>Consent:</strong> Where you have given us clear consent to process your personal data for a specific purpose.</li>
      <li><strong>Contractual Necessity:</strong> Where the processing is necessary for the performance of a contract with you.</li>
      <li><strong>Legal Obligation:</strong> Where we need to process your personal data to comply with a legal obligation.</li>
      <li><strong>Legitimate Interests:</strong> Where the processing is necessary for our legitimate interests (or those of a third party) and your interests and fundamental rights do not override those interests.</li>
    </ul>
  </div>

  <div class="section">
    <h2>5. Disclosure of Your Information</h2>
    <p>We may share information we have collected about you in certain situations:</p>
    <ul>
      <li><strong>Service Providers:</strong> We may share your information with third-party vendors, consultants, and other service providers who perform services on our behalf, such as payment processing, data analysis, email delivery, hosting services, customer service, and marketing assistance.</li>
      <li><strong>Business Transfers:</strong> If we are involved in a merger, acquisition, financing, reorganization, bankruptcy, or sale of company assets, your information may be transferred as part of that transaction.</li>
      <li><strong>Legal Requirements:</strong> We may disclose your information if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</li>
      <li><strong>Vital Interests and Legal Rights:</strong> We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person, or as evidence in litigation in which we are involved.</li>
      <li><strong>With Your Consent:</strong> We may disclose your personal information for any other purpose with your consent.</li>
    </ul>
  </div>

  <div class="section">
    <h2>6. Cookies and Tracking Technologies</h2>
    <p>We may use cookies, web beacons, tracking pixels, and other tracking technologies to collect information about your browsing activities. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Services.</p>
    ${vars.usesAnalytics ? `<p>We use Google Analytics and similar analytics tools to help us understand how our users engage with our Services. These tools may use cookies and similar technologies to collect and analyze information about use of the Services and report on activities and trends. You can learn more about Google Analytics' practices at <a href="https://policies.google.com/technologies/partner-sites">https://policies.google.com/technologies/partner-sites</a>, and you can opt out by downloading the Google Analytics opt-out browser add-on.</p>` : ""}
  </div>

  <div class="section">
    <h2>7. Data Retention</h2>
    <p>We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy, unless a longer retention period is required or permitted by law. When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize it.</p>
    ${vars.collectsPayment ? `<p>For payment and transaction data, we retain records for a minimum of seven (7) years as required by applicable tax and accounting regulations.</p>` : ""}
  </div>

  <div class="section">
    <h2>8. Data Security</h2>
    <p>We implement appropriate technical and organizational security measures designed to protect the security of any personal information we process. These measures include, but are not limited to, encryption of data in transit (TLS/SSL), access controls, regular security assessments, and employee training on data protection practices.</p>
    <p>However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.</p>
  </div>

  ${ccpaSection}

  ${minorsSection}

  <div class="section">
    <h2>11. Changes to This Privacy Policy</h2>
    <p>We reserve the right to update or change this Privacy Policy at any time. If we make material changes to this Privacy Policy, we will notify you either through the email address you have provided to us or by placing a prominent notice on our website. Your continued use of the Services after we post any modifications to the Privacy Policy will constitute your acknowledgment of the modifications and your consent to abide by and be bound by the modified Privacy Policy.</p>
    <p>We encourage you to periodically review this Privacy Policy to stay informed about how we are protecting the information we collect.</p>
  </div>

  <div class="section">
    <h2>12. Contact Us</h2>
    <p>If you have questions or concerns about this Privacy Policy, your personal information, or our data practices, please contact us at:</p>
    <p>
      <strong>${vars.businessName}</strong><br>
      Attn: Privacy Officer<br>
      ${vars.websiteUrl !== "N/A" ? `Website: ${vars.websiteUrl}<br>` : ""}
      State: ${vars.stateFull}
    </p>
  </div>

  ${VERNEN_FOOTER.replace("{{YEAR}}", year)}
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// TERMS OF SERVICE TEMPLATE
// ---------------------------------------------------------------------------

export function generateTermsOfServiceHtml(vars: {
  businessName: string;
  state: string;
  stateFull: string;
  websiteUrl: string;
  serviceType: string;
  entityType: string;
  hasSubscriptions: boolean;
  hasRefundPolicy: boolean;
  effectiveDate: string;
}): string {
  const year = new Date().getFullYear().toString();

  const subscriptionSection = vars.hasSubscriptions ? `
  <div class="section">
    <h2>5. Subscriptions and Recurring Billing</h2>
    <h3>5.1 Subscription Terms</h3>
    <p>Certain portions of the Services may be offered on a subscription basis. By subscribing, you authorize ${vars.businessName} to charge the applicable subscription fee to your designated payment method on a recurring basis (monthly, annually, or as otherwise specified at the time of purchase).</p>
    <h3>5.2 Automatic Renewal</h3>
    <p>Your subscription will automatically renew at the end of each billing period unless you cancel your subscription before the renewal date. You may cancel your subscription at any time through your account settings or by contacting us. Cancellation will take effect at the end of the current billing period.</p>
    <h3>5.3 Price Changes</h3>
    <p>We reserve the right to change subscription prices upon thirty (30) days' prior notice. Price changes will take effect at the start of the next billing period following the date of the price change. Your continued use of the Services after the price change becomes effective constitutes your agreement to pay the modified subscription price.</p>
    <h3>5.4 Free Trials</h3>
    <p>We may offer free trial periods for certain subscription services. At the end of the free trial period, your subscription will automatically convert to a paid subscription unless you cancel before the trial period ends. You will be charged the applicable subscription fee unless you cancel prior to the end of the trial period.</p>
  </div>` : "";

  const refundSection = vars.hasRefundPolicy ? `
  <div class="section">
    <h2>${vars.hasSubscriptions ? "6" : "5"}. Refund Policy</h2>
    <p>${vars.businessName} offers refunds under the following conditions:</p>
    <ul>
      <li><strong>Digital Products and Services:</strong> You may request a full refund within fourteen (14) days of purchase if you are not satisfied with the service, provided that you have not substantially used the service or downloaded the deliverable.</li>
      <li><strong>Custom or Personalized Services:</strong> Refunds for custom work will be evaluated on a case-by-case basis. Once work has commenced on a custom project, refunds may be limited to the portion of work not yet completed.</li>
      <li><strong>Subscription Refunds:</strong> If you cancel a subscription, you will not be charged for subsequent billing periods. We do not provide prorated refunds for partial billing periods unless required by applicable law.</li>
    </ul>
    <p>To request a refund, please contact us with your order details and reason for the refund request. Refunds will be processed to the original payment method within ten (10) business days of approval.</p>
    <p>Notwithstanding the foregoing, refund rights may be subject to additional terms specific to certain products or services, and are subject to all applicable laws of the State of ${vars.stateFull}.</p>
  </div>` : "";

  const nextSection = vars.hasSubscriptions && vars.hasRefundPolicy ? 7 : vars.hasSubscriptions || vars.hasRefundPolicy ? 6 : 5;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Service &mdash; ${vars.businessName}</title>
  ${DOCUMENT_STYLE}
</head>
<body>
  <h1>Terms of Service</h1>
  <div class="header-meta">
    <p><strong>${vars.businessName}</strong></p>
    <p>Effective Date: ${vars.effectiveDate}</p>
    <p>Last Updated: ${vars.effectiveDate}</p>
    ${vars.websiteUrl !== "N/A" ? `<p>Website: ${vars.websiteUrl}</p>` : ""}
    <p>Service Type: ${vars.serviceType}</p>
    <p>Governing Law: State of ${vars.stateFull}</p>
  </div>

  <div class="section">
    <h2>1. Acceptance of Terms</h2>
    <p>These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and ${vars.businessName} ("Company," "we," "us," or "our") governing your access to and use of our website, applications, products, and services (collectively, the "Services").</p>
    <p>By accessing or using the Services, you agree to be bound by these Terms. If you disagree with any part of these Terms, then you may not access or use the Services. If you are using the Services on behalf of a business or other entity, you represent and warrant that you have the authority to bind that entity to these Terms.</p>
    <p>We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of the Services after any such changes constitutes your acceptance of the new Terms. It is your responsibility to review these Terms periodically for changes.</p>
  </div>

  <div class="section">
    <h2>2. Description of Services</h2>
    <p>${vars.businessName} provides ${vars.serviceType} services (the "Services") as described on our website and in any applicable service agreements. The specific features and functionality of the Services may change from time to time at our sole discretion.</p>
    <p>We reserve the right to modify, suspend, or discontinue any part of the Services at any time, with or without notice. We shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the Services or any part thereof.</p>
  </div>

  <div class="section">
    <h2>3. User Accounts and Registration</h2>
    <h3>3.1 Account Creation</h3>
    <p>To access certain features of the Services, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.</p>
    <h3>3.2 Account Security</h3>
    <p>You are responsible for safeguarding the password that you use to access the Services and for any activities or actions under your account. You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
    <h3>3.3 Account Termination</h3>
    <p>We reserve the right to suspend or terminate your account and refuse any and all current or future use of the Services if we reasonably believe that you have violated these Terms, engaged in fraudulent or illegal activity, or for any other reason at our sole discretion.</p>
  </div>

  <div class="section">
    <h2>4. Intellectual Property Rights</h2>
    <h3>4.1 Our Intellectual Property</h3>
    <p>The Services and their entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, audio, design, selection, and arrangement thereof) are owned by ${vars.businessName}, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
    <h3>4.2 Limited License</h3>
    <p>Subject to your compliance with these Terms, ${vars.businessName} grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Services for your personal or internal business purposes.</p>
    <h3>4.3 Restrictions</h3>
    <p>You shall not: (a) copy, modify, or distribute the Services or any content therein; (b) reverse engineer, decompile, or disassemble any part of the Services; (c) use the Services to build a competitive product or service; (d) remove any copyright, trademark, or other proprietary notices; or (e) use any automated means to access the Services.</p>
  </div>

  ${subscriptionSection}

  ${refundSection}

  <div class="section">
    <h2>${nextSection}. Limitation of Liability</h2>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ${vars.businessName.toUpperCase()}, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE SERVICES.</p>
    <p>IN NO EVENT SHALL ${vars.businessName.toUpperCase()}'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES EXCEED THE GREATER OF (A) THE TOTAL AMOUNT YOU HAVE PAID TO ${vars.businessName.toUpperCase()} IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE LIABILITY, OR (B) ONE HUNDRED DOLLARS ($100.00).</p>
    <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
  </div>

  <div class="section">
    <h2>${nextSection + 1}. Indemnification</h2>
    <p>You agree to defend, indemnify, and hold harmless ${vars.businessName} and its officers, directors, employees, contractors, agents, licensors, service providers, subcontractors, and suppliers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms or your use of the Services, including but not limited to any use of the Services' content, products, or functionality other than as expressly authorized in these Terms.</p>
  </div>

  <div class="section">
    <h2>${nextSection + 2}. Disclaimer of Warranties</h2>
    <p>THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE.</p>
    <p>${vars.businessName.toUpperCase()} DOES NOT WARRANT THAT (A) THE SERVICES WILL FUNCTION UNINTERRUPTED, SECURE, OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY ERRORS OR DEFECTS WILL BE CORRECTED; (C) THE SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE SERVICES WILL MEET YOUR REQUIREMENTS.</p>
  </div>

  <div class="section">
    <h2>${nextSection + 3}. Governing Law and Dispute Resolution</h2>
    <h3>${nextSection + 3}.1 Governing Law</h3>
    <p>These Terms shall be governed by and construed in accordance with the laws of the State of ${vars.stateFull}, without regard to its conflict of law provisions. You agree to submit to the personal and exclusive jurisdiction of the courts located within the State of ${vars.stateFull} for the resolution of any disputes.</p>
    <h3>${nextSection + 3}.2 Dispute Resolution</h3>
    <p>Any dispute, controversy, or claim arising out of or relating to these Terms, or the breach, termination, or invalidity thereof, shall first be attempted to be resolved through good-faith negotiation between the parties. If the dispute cannot be resolved through negotiation within thirty (30) days, either party may submit the dispute to binding arbitration administered by the American Arbitration Association ("AAA") in accordance with its Commercial Arbitration Rules.</p>
    <h3>${nextSection + 3}.3 Class Action Waiver</h3>
    <p>YOU AND ${vars.businessName.toUpperCase()} AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Unless both you and ${vars.businessName} agree otherwise, the arbitrator may not consolidate or join more than one person's or party's claims.</p>
  </div>

  <div class="section">
    <h2>${nextSection + 4}. General Provisions</h2>
    <h3>Severability</h3>
    <p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.</p>
    <h3>Waiver</h3>
    <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of ${vars.businessName}.</p>
    <h3>Entire Agreement</h3>
    <p>These Terms, together with the Privacy Policy and any other legal notices or agreements published by ${vars.businessName} on the Services, constitute the entire agreement between you and ${vars.businessName} concerning the Services and supersede all prior agreements, understandings, negotiations, and discussions, whether oral or written.</p>
    <h3>Assignment</h3>
    <p>${vars.businessName} may assign or transfer these Terms, in whole or in part, without restriction. You may not assign or transfer any rights or obligations under these Terms without ${vars.businessName}'s prior written consent.</p>
  </div>

  <div class="section">
    <h2>${nextSection + 5}. Contact Information</h2>
    <p>If you have any questions about these Terms of Service, please contact us at:</p>
    <p>
      <strong>${vars.businessName}</strong><br>
      ${vars.websiteUrl !== "N/A" ? `Website: ${vars.websiteUrl}<br>` : ""}
      State: ${vars.stateFull}
    </p>
  </div>

  ${VERNEN_FOOTER.replace("{{YEAR}}", year)}
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// EMPLOYEE HANDBOOK TEMPLATE
// ---------------------------------------------------------------------------

export function generateEmployeeHandbookHtml(vars: {
  businessName: string;
  state: string;
  stateFull: string;
  entityType: string;
  employeeCount: number;
  effectiveDate: string;
}): string {
  const year = new Date().getFullYear().toString();
  const isCalifornia = vars.state === "CA";
  const isNewYork = vars.state === "NY";
  const isLargeEmployer = vars.employeeCount >= 50;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Employee Handbook &mdash; ${vars.businessName}</title>
  ${DOCUMENT_STYLE}
</head>
<body>
  <h1>Employee Handbook</h1>
  <div class="header-meta">
    <p><strong>${vars.businessName}</strong></p>
    <p>Effective Date: ${vars.effectiveDate}</p>
    <p>Governing Jurisdiction: ${vars.stateFull}</p>
    <p>Entity Type: ${vars.entityType}</p>
  </div>

  <div class="section">
    <h2>Welcome Message</h2>
    <p>Welcome to ${vars.businessName}. We are pleased to have you as part of our team. This Employee Handbook is designed to acquaint you with our company, our expectations, and the benefits and policies that apply to all employees.</p>
    <p>This Handbook is not a contract of employment and does not guarantee employment for any specific duration. Employment with ${vars.businessName} is "at-will," meaning that either you or the Company may terminate the employment relationship at any time, with or without cause or notice, to the extent permitted by law.</p>
    <p>Please read this Handbook carefully and keep it available for future reference. If you have any questions about any policies described herein, please contact your supervisor or the Human Resources department.</p>
  </div>

  <div class="section">
    <h2>1. Employment Policies</h2>
    <h3>1.1 Equal Employment Opportunity</h3>
    <p>${vars.businessName} is an equal opportunity employer. We are committed to providing equal employment opportunities to all employees and applicants without regard to race, color, religion, sex (including pregnancy, sexual orientation, and gender identity), national origin, age, disability, genetic information, marital status, veteran status, or any other characteristic protected by applicable federal, state, or local law.</p>
    <p>This policy applies to all terms, conditions, and privileges of employment, including recruitment, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation, and training.</p>

    <h3>1.2 Anti-Harassment and Anti-Discrimination</h3>
    <p>${vars.businessName} is committed to maintaining a work environment that is free of harassment and discrimination. Harassment based on any protected characteristic, including sexual harassment, is strictly prohibited and will not be tolerated.</p>
    <p><strong>Sexual Harassment</strong> includes unwelcome sexual advances, requests for sexual favors, and other verbal, visual, or physical conduct of a sexual nature when:</p>
    <ul>
      <li>Submission to such conduct is made a term or condition of employment;</li>
      <li>Submission to or rejection of such conduct is used as a basis for employment decisions; or</li>
      <li>Such conduct unreasonably interferes with an individual's work performance or creates an intimidating, hostile, or offensive work environment.</li>
    </ul>
    <p>All employees are required to report any incident of harassment or discrimination immediately to their supervisor, Human Resources, or any member of management. ${vars.businessName} will promptly investigate all complaints and take appropriate corrective action.</p>
    ${isCalifornia ? `<p><strong>California-Specific Requirements:</strong> In accordance with California Government Code Section 12950.1, ${vars.businessName} provides sexual harassment prevention training to all supervisory employees within six months of assumption of a supervisory position, and to all employees within six months of hire. Training is provided every two years thereafter. Non-supervisory employees receive one hour of training; supervisory employees receive two hours.</p>` : ""}
    ${isNewYork ? `<p><strong>New York-Specific Requirements:</strong> In accordance with New York State Human Rights Law and New York City Human Rights Law, all employees receive annual anti-sexual harassment training. This training includes examples of prohibited conduct, information concerning federal, state, and local laws regarding sexual harassment, and the complaint process available to employees.</p>` : ""}

    <h3>1.3 At-Will Employment</h3>
    <p>Employment with ${vars.businessName} is at-will. This means that either you or the Company may terminate the employment relationship at any time, for any reason or no reason, with or without cause or prior notice, to the extent permitted by applicable law. Nothing in this Handbook or any other Company document or communication shall alter the at-will nature of employment, unless expressly agreed to in a written agreement signed by an authorized representative of ${vars.businessName}.</p>

    <h3>1.4 Immigration Law Compliance</h3>
    <p>${vars.businessName} complies with the Immigration Reform and Control Act of 1986 (IRCA) and is committed to employing only individuals who are authorized to work in the United States. Each new employee must complete the Employment Eligibility Verification Form I-9 and present documentation establishing identity and employment authorization.</p>
  </div>

  <div class="section">
    <h2>2. Compensation and Benefits</h2>
    <h3>2.1 Pay Periods and Payroll</h3>
    <p>Employees are paid on a [bi-weekly/semi-monthly] basis. Paychecks reflect all applicable withholdings and deductions required by law. If you believe there is an error in your paycheck, please contact Human Resources or Payroll immediately.</p>
    ${isCalifornia ? `<p><strong>California Requirements:</strong> In accordance with California Labor Code Section 226, your pay stub will include all information required by law, including gross wages earned, total hours worked (for non-exempt employees), piece-rate information if applicable, all deductions, net wages earned, the inclusive dates of the pay period, your name and last four digits of your Social Security number, the name and address of the legal entity employing you, and all applicable hourly rates and corresponding hours worked.</p>` : ""}

    <h3>2.2 Overtime</h3>
    <p>Non-exempt employees are entitled to overtime compensation in accordance with applicable federal and state law. Under the Fair Labor Standards Act (FLSA), overtime is paid at one and one-half (1.5) times the employee's regular rate of pay for all hours worked over forty (40) hours in a workweek.</p>
    ${isCalifornia ? `<p><strong>California Overtime Rules:</strong> California law provides additional overtime protections. Non-exempt employees are entitled to overtime at 1.5 times the regular rate for hours worked over 8 in a workday or over 40 in a workweek, and double time for hours worked over 12 in a workday or over 8 on the seventh consecutive day of work in a workweek.</p>` : ""}
    <p>Overtime work must be approved in advance by your supervisor. Working unauthorized overtime may result in disciplinary action, but you will still be compensated for all hours worked.</p>

    <h3>2.3 Benefits</h3>
    <p>${vars.businessName} offers a benefits package to eligible employees. Specific benefits, eligibility requirements, and enrollment information are provided separately. Benefits may include:</p>
    <ul>
      <li>Health insurance (medical, dental, and vision)</li>
      <li>Retirement savings plan (401(k) or equivalent)</li>
      <li>Paid time off (PTO)</li>
      <li>Paid holidays</li>
      ${isLargeEmployer ? `<li>Family and Medical Leave (FMLA)</li>` : ""}
      <li>Workers' compensation insurance</li>
      <li>Life and disability insurance</li>
    </ul>
    <p>The Company reserves the right to modify, amend, or terminate any benefit plan at any time, subject to applicable law.</p>
  </div>

  <div class="section">
    <h2>3. Leave Policies</h2>
    <h3>3.1 Paid Time Off (PTO)</h3>
    <p>${vars.businessName} provides paid time off to eligible employees. PTO accrues based on length of service and may be used for vacation, personal time, or other purposes. Specific accrual rates and maximum balances are provided in the PTO policy supplement.</p>

    ${isLargeEmployer ? `<h3>3.2 Family and Medical Leave (FMLA)</h3>
    <p>Eligible employees may take up to twelve (12) weeks of unpaid, job-protected leave in a twelve-month period under the Family and Medical Leave Act (FMLA) for the following reasons:</p>
    <ul>
      <li>The birth of a child and to care for the newborn child;</li>
      <li>The placement of a child for adoption or foster care;</li>
      <li>To care for a spouse, child, or parent with a serious health condition;</li>
      <li>A serious health condition that makes the employee unable to perform essential job functions; or</li>
      <li>Any qualifying exigency arising out of a family member's active military duty.</li>
    </ul>
    <p>To be eligible, an employee must have worked for ${vars.businessName} for at least twelve months, have worked at least 1,250 hours during the twelve months preceding the leave, and work at a location where the Company employs 50 or more employees within 75 miles.</p>` : ""}

    ${isCalifornia ? `<h3>3.3 California-Specific Leave</h3>
    <p><strong>California Family Rights Act (CFRA):</strong> Eligible employees may take up to twelve (12) weeks of unpaid, job-protected leave in a twelve-month period for family care and medical leave reasons, including to bond with a new child (birth, adoption, or foster care), to care for a family member with a serious health condition, or for the employee's own serious health condition.</p>
    <p><strong>California Paid Sick Leave:</strong> All employees who work 30 or more days within a year are entitled to paid sick leave. Employees accrue one hour of paid sick leave for every 30 hours worked, up to 80 hours. Paid sick leave may be used for the employee's own health condition, to care for a family member, or for purposes related to domestic violence, sexual assault, or stalking.</p>
    <p><strong>Pregnancy Disability Leave:</strong> Employees disabled by pregnancy, childbirth, or related medical conditions are entitled to up to four months of unpaid leave per pregnancy, with a right to reasonable accommodation and transfer to a less strenuous position if available.</p>` : ""}

    ${isNewYork ? `<h3>3.3 New York-Specific Leave</h3>
    <p><strong>New York Paid Family Leave (PFL):</strong> Eligible employees may take up to twelve (12) weeks of paid family leave to bond with a new child, care for a family member with a serious health condition, or assist with family obligations when a family member is deployed on active military duty. PFL benefits are funded through employee payroll deductions.</p>
    <p><strong>New York Paid Sick Leave:</strong> All employees accrue sick leave at a rate of one hour per 30 hours worked. Employees of employers with 100 or more employees are entitled to up to 56 hours of paid sick leave per year.</p>` : ""}

    <h3>3.${isCalifornia || isNewYork ? "4" : "3"} Jury Duty</h3>
    <p>${vars.businessName} supports employees who are called to serve on a jury. Employees must notify their supervisor as soon as possible after receiving a jury duty summons. Time off for jury duty will be provided in accordance with applicable law.</p>

    <h3>3.${isCalifornia || isNewYork ? "5" : "4"} Bereavement Leave</h3>
    <p>Employees may be granted up to three (3) days of paid bereavement leave upon the death of an immediate family member (spouse, domestic partner, child, parent, sibling, grandparent, or grandchild). Additional unpaid leave may be granted at the discretion of management.</p>
  </div>

  <div class="section">
    <h2>4. Workplace Conduct</h2>
    <h3>4.1 Code of Conduct</h3>
    <p>All employees are expected to conduct themselves in a professional and ethical manner. ${vars.businessName} expects employees to treat colleagues, customers, vendors, and the public with respect and courtesy. Conduct that is unlawful, dishonest, unethical, or that adversely affects the Company's legitimate business interests or reputation will not be tolerated.</p>

    <h3>4.2 Drug-Free Workplace</h3>
    <p>${vars.businessName} is committed to maintaining a drug-free workplace in compliance with the Drug-Free Workplace Act of 1988. The manufacture, distribution, dispensation, possession, or use of illegal drugs or controlled substances in the workplace or while conducting Company business is strictly prohibited.</p>
    ${isCalifornia ? `<p><strong>Note:</strong> While California law permits the use of marijuana for medical and recreational purposes, federal law classifies marijuana as a controlled substance. Employees are prohibited from using or being under the influence of marijuana during work hours or on Company premises, regardless of state law.</p>` : ""}

    <h3>4.3 Workplace Safety</h3>
    <p>${vars.businessName} is committed to providing a safe and healthy work environment in compliance with the Occupational Safety and Health Act (OSHA) and all applicable state safety laws. All employees are expected to comply with all safety rules and regulations, report unsafe conditions or accidents immediately, and participate in safety training programs as required.</p>

    <h3>4.4 Confidentiality</h3>
    <p>During the course of employment, employees may have access to confidential and proprietary information belonging to ${vars.businessName}. Employees are required to protect and maintain the confidentiality of all such information both during and after employment. Unauthorized disclosure of confidential information may result in disciplinary action up to and including termination, as well as potential legal liability.</p>
  </div>

  <div class="section">
    <h2>5. Separation of Employment</h2>
    <h3>5.1 Voluntary Resignation</h3>
    <p>Employees who wish to resign are requested to provide at least two (2) weeks' written notice to their supervisor. Adequate notice allows the Company to plan for the transition and ensures a smooth separation process.</p>

    <h3>5.2 Involuntary Termination</h3>
    <p>${vars.businessName} reserves the right to terminate employment at any time, with or without cause, and with or without notice, consistent with applicable law and the at-will nature of employment.</p>

    <h3>5.3 Final Pay</h3>
    <p>Upon separation, employees will receive their final paycheck in accordance with applicable state law.</p>
    ${isCalifornia ? `<p><strong>California Final Pay Requirements:</strong> Under California Labor Code Sections 201-202, employees who are terminated involuntarily must receive their final wages, including accrued but unused vacation, immediately at the time of termination. Employees who resign with at least 72 hours' notice must receive their final wages on their last day of work. Employees who resign without 72 hours' notice must receive their final wages within 72 hours of resignation.</p>` : ""}

    <h3>5.4 Return of Company Property</h3>
    <p>Upon separation, employees must return all Company property, including but not limited to keys, access cards, equipment, documents, and electronic devices. Failure to return Company property may result in deductions from the final paycheck to the extent permitted by law.</p>
  </div>

  <div class="section">
    <h2>Acknowledgment</h2>
    <p>By signing below, I acknowledge that I have received a copy of the ${vars.businessName} Employee Handbook. I understand that it is my responsibility to read and familiarize myself with the policies and procedures contained herein.</p>
    <p>I understand that this Handbook is not a contract of employment and that my employment with ${vars.businessName} is at-will. I further understand that ${vars.businessName} reserves the right to modify, amend, or revoke any policy or procedure described in this Handbook at any time, with or without notice.</p>
    <br>
    <p>___________________________________ &nbsp;&nbsp;&nbsp;&nbsp; _______________</p>
    <p>Employee Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date</p>
    <br>
    <p>___________________________________</p>
    <p>Printed Name</p>
  </div>

  ${VERNEN_FOOTER.replace("{{YEAR}}", year)}
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// COMPLIANCE CHECKLIST TEMPLATE
// ---------------------------------------------------------------------------

export function generateComplianceChecklistHtml(vars: {
  businessName: string;
  state: string;
  stateFull: string;
  entityType: string;
}): string {
  const year = new Date().getFullYear().toString();

  // Entity-specific formation items
  const formationItems: string[] = [];
  switch (vars.entityType) {
    case "LLC":
      formationItems.push(
        "File Articles of Organization with the Secretary of State",
        "Obtain an Employer Identification Number (EIN) from the IRS",
        "Draft and adopt an Operating Agreement",
        "Publish notice of formation (if required by state law)",
        "Designate a registered agent in the state of formation",
        "File initial report / statement of information (if required)"
      );
      break;
    case "CORPORATION":
    case "S_CORP":
      formationItems.push(
        "File Articles of Incorporation with the Secretary of State",
        "Obtain an Employer Identification Number (EIN) from the IRS",
        "Draft and adopt Corporate Bylaws",
        "Hold organizational meeting of incorporators / initial directors",
        "Issue stock certificates to initial shareholders",
        "Elect S-Corp status with IRS (Form 2553) if applicable",
        "Designate a registered agent in the state of incorporation",
        "File initial annual report / statement of information"
      );
      break;
    case "SOLE_PROPRIETORSHIP":
      formationItems.push(
        "Register a DBA / Fictitious Business Name (if not operating under personal name)",
        "Obtain an Employer Identification Number (EIN) if hiring employees",
        "Register for state and local tax accounts as applicable",
        "Obtain any required local business permits"
      );
      break;
    case "PARTNERSHIP":
      formationItems.push(
        "File a Partnership Agreement (recommended, not always required)",
        "Register the partnership with the Secretary of State (if LP or LLP)",
        "Obtain an Employer Identification Number (EIN) from the IRS",
        "Designate a registered agent (if LP or LLP)",
        "File DBA / Fictitious Business Name if applicable"
      );
      break;
    case "NONPROFIT":
      formationItems.push(
        "File Articles of Incorporation for Nonprofit with the Secretary of State",
        "Obtain an Employer Identification Number (EIN) from the IRS",
        "Draft and adopt Nonprofit Bylaws",
        "Apply for federal tax-exempt status (IRS Form 1023 or 1023-EZ)",
        "Apply for state tax-exempt status",
        "Register for charitable solicitation (if fundraising)",
        "Hold organizational meeting and elect Board of Directors",
        "Designate a registered agent in the state of incorporation"
      );
      break;
    default:
      formationItems.push(
        "File formation documents with the Secretary of State",
        "Obtain an Employer Identification Number (EIN) from the IRS",
        "Designate a registered agent"
      );
  }

  const formationItemsHtml = formationItems
    .map(
      (item) =>
        `<div class="checklist-item"><input type="checkbox"> ${item}</div>`
    )
    .join("\n      ");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Compliance Checklist &mdash; ${vars.businessName || vars.entityType} (${vars.stateFull})</title>
  ${DOCUMENT_STYLE}
</head>
<body>
  <h1>Business Compliance Checklist</h1>
  <div class="header-meta">
    ${vars.businessName ? `<p><strong>${vars.businessName}</strong></p>` : ""}
    <p>Entity Type: ${vars.entityType}</p>
    <p>State: ${vars.stateFull}</p>
    <p>Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div class="section">
    <h2>1. Business Formation &amp; Registration</h2>
    ${formationItemsHtml}
  </div>

  <div class="section">
    <h2>2. Licenses &amp; Permits</h2>
    <div class="checklist-item"><input type="checkbox"> Obtain a general business license from your city or county</div>
    <div class="checklist-item"><input type="checkbox"> Obtain industry-specific licenses or permits (e.g., food service, construction, healthcare)</div>
    <div class="checklist-item"><input type="checkbox"> Register for a state sales tax permit (if selling taxable goods/services)</div>
    <div class="checklist-item"><input type="checkbox"> Obtain a home occupation permit (if operating from a residence)</div>
    <div class="checklist-item"><input type="checkbox"> Obtain a sign permit (if displaying commercial signage)</div>
    <div class="checklist-item"><input type="checkbox"> Verify zoning compliance for business location</div>
    <div class="checklist-item"><input type="checkbox"> Obtain health department permits (if applicable)</div>
    <div class="checklist-item"><input type="checkbox"> Obtain fire department permits (if applicable)</div>
  </div>

  <div class="section">
    <h2>3. Tax Compliance</h2>
    <div class="checklist-item"><input type="checkbox"> Register for federal taxes (income tax, employment taxes)</div>
    <div class="checklist-item"><input type="checkbox"> Register for state income tax withholding (if applicable)</div>
    <div class="checklist-item"><input type="checkbox"> Register for state unemployment insurance tax (SUTA)</div>
    <div class="checklist-item"><input type="checkbox"> Register for state sales and use tax collection</div>
    <div class="checklist-item"><input type="checkbox"> Set up quarterly estimated tax payments</div>
    <div class="checklist-item"><input type="checkbox"> Understand nexus obligations for multi-state operations</div>
    <div class="checklist-item"><input type="checkbox"> Maintain proper accounting records and bookkeeping</div>
    <div class="checklist-item"><input type="checkbox"> File annual tax returns (federal and state)</div>
  </div>

  <div class="section">
    <h2>4. Employment Law Compliance</h2>
    <div class="checklist-item"><input type="checkbox"> Post required federal employment law posters (FLSA, OSHA, FMLA, EEO, etc.)</div>
    <div class="checklist-item"><input type="checkbox"> Post required ${vars.stateFull} state employment law posters</div>
    <div class="checklist-item"><input type="checkbox"> Verify I-9 Employment Eligibility for all employees</div>
    <div class="checklist-item"><input type="checkbox"> Classify workers correctly (employee vs. independent contractor)</div>
    <div class="checklist-item"><input type="checkbox"> Classify employees correctly (exempt vs. non-exempt)</div>
    <div class="checklist-item"><input type="checkbox"> Comply with federal minimum wage requirements ($7.25/hr or state minimum, whichever is higher)</div>
    <div class="checklist-item"><input type="checkbox"> Comply with ${vars.stateFull} minimum wage requirements</div>
    <div class="checklist-item"><input type="checkbox"> Establish overtime policies in compliance with FLSA and state law</div>
    <div class="checklist-item"><input type="checkbox"> Implement anti-harassment and anti-discrimination policies</div>
    <div class="checklist-item"><input type="checkbox"> Provide sexual harassment prevention training (as required by state law)</div>
    <div class="checklist-item"><input type="checkbox"> Create and distribute Employee Handbook</div>
    <div class="checklist-item"><input type="checkbox"> Obtain workers' compensation insurance</div>
    <div class="checklist-item"><input type="checkbox"> Report new hires to the state directory of new hires</div>
    <div class="checklist-item"><input type="checkbox"> Maintain employee personnel files</div>
  </div>

  <div class="section">
    <h2>5. Insurance Requirements</h2>
    <div class="checklist-item"><input type="checkbox"> Obtain general liability insurance</div>
    <div class="checklist-item"><input type="checkbox"> Obtain professional liability / errors and omissions insurance (if applicable)</div>
    <div class="checklist-item"><input type="checkbox"> Obtain workers' compensation insurance (required in most states)</div>
    <div class="checklist-item"><input type="checkbox"> Obtain commercial property insurance</div>
    <div class="checklist-item"><input type="checkbox"> Obtain commercial auto insurance (if using vehicles for business)</div>
    <div class="checklist-item"><input type="checkbox"> Consider cyber liability insurance (if handling sensitive data)</div>
    <div class="checklist-item"><input type="checkbox"> Obtain disability insurance (required in some states: CA, HI, NJ, NY, RI)</div>
  </div>

  <div class="section">
    <h2>6. Data Privacy &amp; Security</h2>
    <div class="checklist-item"><input type="checkbox"> Publish a Privacy Policy on your website</div>
    <div class="checklist-item"><input type="checkbox"> Publish Terms of Service on your website</div>
    <div class="checklist-item"><input type="checkbox"> Comply with the California Consumer Privacy Act (CCPA/CPRA) if applicable</div>
    <div class="checklist-item"><input type="checkbox"> Comply with GDPR if serving EU customers</div>
    <div class="checklist-item"><input type="checkbox"> Implement data breach notification procedures (per state law)</div>
    <div class="checklist-item"><input type="checkbox"> Establish data retention and destruction policies</div>
    <div class="checklist-item"><input type="checkbox"> Implement PCI DSS compliance (if processing credit cards)</div>
    <div class="checklist-item"><input type="checkbox"> Train employees on data privacy and security best practices</div>
  </div>

  <div class="section">
    <h2>7. Ongoing Compliance</h2>
    <div class="checklist-item"><input type="checkbox"> File annual reports / statements of information with the Secretary of State</div>
    <div class="checklist-item"><input type="checkbox"> Renew business licenses and permits annually</div>
    <div class="checklist-item"><input type="checkbox"> File Beneficial Ownership Information (BOI) report with FinCEN (if applicable)</div>
    <div class="checklist-item"><input type="checkbox"> Maintain good standing with the state by paying franchise taxes / annual fees</div>
    <div class="checklist-item"><input type="checkbox"> Review and update corporate governance documents annually</div>
    <div class="checklist-item"><input type="checkbox"> Conduct annual meetings (required for corporations)</div>
    <div class="checklist-item"><input type="checkbox"> Maintain meeting minutes and corporate records</div>
    <div class="checklist-item"><input type="checkbox"> Review and update insurance policies annually</div>
    <div class="checklist-item"><input type="checkbox"> Review employment law poster requirements for updates</div>
    <div class="checklist-item"><input type="checkbox"> Stay informed of changes in federal and ${vars.stateFull} law</div>
  </div>

  ${VERNEN_FOOTER.replace("{{YEAR}}", year)}
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// State name lookup
// ---------------------------------------------------------------------------

export const STATE_NAMES: Record<string, string> = {
  AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California",
  CO: "Colorado", CT: "Connecticut", DE: "Delaware", FL: "Florida", GA: "Georgia",
  HI: "Hawaii", ID: "Idaho", IL: "Illinois", IN: "Indiana", IA: "Iowa",
  KS: "Kansas", KY: "Kentucky", LA: "Louisiana", ME: "Maine", MD: "Maryland",
  MA: "Massachusetts", MI: "Michigan", MN: "Minnesota", MS: "Mississippi", MO: "Missouri",
  MT: "Montana", NE: "Nebraska", NV: "Nevada", NH: "New Hampshire", NJ: "New Jersey",
  NM: "New Mexico", NY: "New York", NC: "North Carolina", ND: "North Dakota", OH: "Ohio",
  OK: "Oklahoma", OR: "Oregon", PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina",
  SD: "South Dakota", TN: "Tennessee", TX: "Texas", UT: "Utah", VT: "Vermont",
  VA: "Virginia", WA: "Washington", WV: "West Virginia", WI: "Wisconsin", WY: "Wyoming",
  DC: "District of Columbia",
};
