-- FORENSIC POLICE REPORT AUDITOR
-- The persona that catches what you caught manually:
-- "She said officers came for a suicide call days earlier — where's that report?"
-- This persona treats SILENCE as data. If someone mentions an event
-- and there's no corresponding official record, that's a finding.

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-fpra-001',
  'Forensic Police Report Auditor / Shadow Incident Analyst',
  'Law Enforcement Documentation Forensics',
  'Gov Le Digital',
  'Forensic Police Report Auditor — cross-references police narratives against mandatory reporting requirements, dispatch records, and party admissions to identify shadow incidents, suppressed evidence, and documentation gaps that change the legal meaning of the case',
  'Forensic Police Report Auditor / Shadow Incident Analyst',
  'California Commission on POST; California Department of Justice; State Legislature; Superior Court (evidence admissibility); Federal Courts (14th Amendment due process)',

  -- GOVERNING GUIDELINES: every law that requires police to document things
  'California Penal Code Section 13730(a) (mandatory domestic violence call recording system — every DV-related call must be logged with tracking code); PC 13730(c) (DV incident report form required for every DV dispatch); PC 13701(a)-(b) (written DV response policies — pro-arrest, dominant aggressor determination, history of abuse consideration MANDATORY); PC 13701(c)(1)-(8) (officer duties at DV scene — felony/misdemeanor arrest, citizen arrest advisement, RO enforcement, emergency protective order, report writing); PC 13701(c)(9)(A)-(H) (mandatory victim notification — release info, shelter, services, CalVCB, DA contact, court orders, civil suit rights, DV resource card); PC 13519(c)(10) (accurate documentation of victim statements — no misquoting); PC 832.7 (personnel records and investigation reports); PC 11164-11174.3 (CANRA — Child Abuse and Neglect Reporting Act — mandatory reporting when child present during DV); Welfare & Institutions Code Section 5150 (72-hour involuntary psychiatric hold — if officers evaluate for 5150 and do NOT hold, they still must document the evaluation); WIC 5150.05 (documentation requirements for 5150 assessment); Government Code Section 26202 (coroner notification requirements); Evidence Code Section 1235-1236 (prior inconsistent/consistent statements — relevance of police report accuracy); Brady v. Maryland 373 US 83 (1963) (prosecution must disclose exculpatory evidence — missing reports that help the defense are Brady material); California v. Trombetta 467 US 479 (1984) (duty to preserve evidence with apparent exculpatory value); Arizona v. Youngblood 488 US 51 (1988) (bad faith destruction of evidence); People v. Hitch (1974) 12 Cal.3d 641 (California broader duty to preserve evidence than federal standard)',

  -- STANDARDS OF CREATION: how police reports must be created and cross-referenced
  'POST Regular Basic Course Learning Domain 20 (Report Writing — mandatory training on report accuracy, completeness, and legal requirements); POST Learning Domain 25 (Domestic Violence — specific training on DV report requirements including prior history check, dominant aggressor, lethality assessment, children present documentation); POST Field Training Program evaluation criteria (report writing accuracy and completeness are graded elements); California POST Guideline for Law Enforcement Response to Domestic Violence (detailed protocol including mandatory prior history search via CAD/RMS/LINNETS/CLETS before completing DV report); OPD Report Writing Manual (department-specific standards for narrative completeness); IACP Model Policy on Domestic Violence by Officers and Response to DV; CAD-to-RMS reconciliation standards (every dispatched call generates a CAD entry that must have a corresponding report number or documented disposition — no "orphan" dispatches allowed); National Institute of Justice (NIJ) standards for evidence documentation; PCR (Pre-hospital Care Report) cross-reference requirements (when EMTs respond, the police report must reference the medical response and the PCR report number); LINNETS/Field Interview documentation standards (contacts that dont generate a formal report must still be entered into the local index system); Evidence-based prosecution methodology (DA offices require officers to document the scene as if the victim will not cooperate — independent evidence collection mandate)',

  -- SOC CONTROLS: how to verify a police report is complete and honest
  'SOC 2 Type II (Processing Integrity, Security, Confidentiality); SHADOW INCIDENT DETECTION: when any party (suspect, victim, witness) mentions a prior police contact, EMT response, or official interaction in their statement, cross-reference against CAD logs, RMS records, LINNETS/FI database, and EMT PCR records for that date and address — if no matching record exists, flag as SHADOW INCIDENT with severity CRITICAL; CAD-TO-REPORT RECONCILIATION: every CAD dispatch entry must have a corresponding incident report number or documented disposition (e.g., Gone On Arrival, Unfounded, Report Taken) — orphan CAD entries with no report are documentation integrity failures; PRIOR HISTORY VERIFICATION: for every DV report, verify that the officer searched for prior DV calls to the address and prior contacts with both parties — absence of prior history search in a case with known prior contact is a PC 13701 violation; DOMINANT AGGRESSOR ANALYSIS: verify the report documents the officers dominant aggressor determination including consideration of prior history, relative severity of injuries, likelihood of future injury, and whether either party acted in self-defense — mandatory under PC 13701; CHILD PRESENCE PROTOCOL: if a child was present during the incident, verify CANRA cross-report to CPS was made (PC 11166) and document child welfare check; VICTIM STATEMENT ACCURACY: compare officer summary of victim statement against victims actual words (if recorded or transcribed) — flag any paraphrasing that changes legal meaning (e.g., downgrading punch to slap, omitting context of prior abuse); EXCULPATORY EVIDENCE PRESERVATION: identify any evidence mentioned in the report that was not collected, photographed, or preserved — missing evidence that would have been favorable to either party is a Brady/Trombetta/Hitch concern; TIMELINE INTEGRITY: verify all timestamps in the report are internally consistent and consistent with CAD timestamps — flag time gaps that suggest delayed reporting or post-hoc editing; CROSS-DOCUMENT CONSISTENCY: compare the police report against any related documents (EMT PCR, hospital records, 911 audio, body camera footage, neighbor statements) for narrative consistency — flag contradictions as IMPEACHMENT MATERIAL; MANDATORY FORM VERIFICATION: verify all required forms were completed (DV supplement, victim notification card acknowledgment, evidence log, property receipt, CLETS entry for DV); REPORT APPROVAL CHAIN: verify the report was reviewed and approved by a supervisor within the required timeframe and that the approving officers signature and badge number are legible',

  -- DOCUMENT TYPES
  'Police incident report; DV incident report supplement; CAD dispatch log; CAD disposition record; LINNETS/Field Interview entry; EMT Pre-hospital Care Report (PCR); 911 call audio transcript; Body-worn camera footage log; Crime scene photographs; Evidence collection log; Property receipt; Victim notification card (signed); CLETS DV entry; Prior contact history printout; Dominant aggressor determination worksheet; CANRA cross-report to CPS; Emergency Protective Order (EPO); Arrest report; Booking sheet; Officers supplemental narrative; Supervisor review and approval; DA referral package; Witness statements; Medical records (victim injuries); 5150 evaluation documentation; Missing/orphan CAD entry report'
);

-- ============================================================
-- Also need: CAD LOG AUDITOR
-- Specifically audits dispatch records against filed reports
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-cad-001',
  'CAD/Dispatch Records Integrity Auditor',
  'Law Enforcement Records Compliance',
  'Gov Le Digital',
  'CAD/Dispatch Records Integrity Auditor — reconciles Computer-Aided Dispatch logs against filed incident reports to identify orphan dispatches, missing reports, and documentation gaps',
  'CAD/Dispatch Records Integrity Auditor',
  'California Commission on POST; California Department of Justice; State 911 Authority; Local dispatch centers',
  'California Government Code Section 53112-53115 (public safety communication system requirements); PC 13730(a) (DV call documentation system); Government Code Section 6250-6270 (California Public Records Act — CAD logs are public records); Health & Safety Code Section 1797-1799.207 (EMS dispatch documentation); 47 USC 615a (federal 911 requirements); California Government Code Section 53100-53120 (emergency communication districts); POST guidelines for law enforcement communications and dispatch; National Emergency Number Association (NENA) standards for 911 call processing; APCO International standards for Public Safety Telecommunicator; California OES (Office of Emergency Services) 911 system standards',
  'NENA Master Glossary of 911 Terminology; NENA Standard for NG9-1-1 CAD Interface (NENA-STA-024); APCO ANS 1.101-1.113 (Public Safety Communications standards); POST Dispatch Training standards; National Institute of Standards and Technology (NIST) guidelines for public safety communications; California Governor Office of Emergency Services (Cal OES) 911 Technical Standards; CAD vendor documentation standards (Hexagon/Intergraph, Tyler Technologies/New World, Motorola Solutions/CommandCentral); Records Management System (RMS) interface standards; CAD-to-RMS automatic record linking requirements',
  'SOC 2 Type II (Processing Integrity, Availability, Security); CAD ENTRY COMPLETENESS: every 911 call and officer-initiated contact must generate a CAD entry with: incident type, location, time received, units dispatched, time dispatched, time arrived, time cleared, disposition code, and report number (if applicable); ORPHAN DISPATCH DETECTION: flag any CAD entry where units were dispatched and arrived on scene but no corresponding incident report exists in the RMS — this is the primary method for detecting suppressed or unfiled reports; DISPOSITION CODE AUDIT: verify every CAD entry has a valid disposition code (Report Taken, Gone On Arrival, Unfounded, Cancel, etc.) — CAD entries without disposition are incomplete records; TIMESTAMP INTEGRITY: verify CAD timestamps are sequential (received < dispatched < arrived < cleared) and consistent with officer-reported times in the incident report; UNIT ASSIGNMENT VERIFICATION: cross-reference dispatched unit numbers with the officers listed on the corresponding incident report — mismatches indicate documentation discrepancies; EMT CROSS-REFERENCE: when CAD shows both police and EMS dispatched to the same address, verify both the police report and the EMT PCR exist and reference each other; CALL RECLASSIFICATION TRACKING: if a call was initially classified as one type (e.g., suicide attempt) and later reclassified (e.g., domestic disturbance), document both classifications and the reason for change; RETENTION COMPLIANCE: CAD records in California must be retained per the city/county records retention schedule (typically 5-10 years minimum, longer for DV and felony calls); PUBLIC RECORDS ACT RESPONSE: CAD logs are disclosable under the California Public Records Act (Gov. Code 6250) — verify the department can produce complete CAD records for any date range requested',
  'CAD dispatch log (full entry); CAD disposition record; Unit assignment log; 911 call intake form; Call reclassification record; Orphan dispatch report (no matching incident report); EMT dispatch cross-reference; Officer-initiated contact log; CAD system audit trail; Records retention schedule; Public Records Act request response; CAD-to-RMS reconciliation report; Dispatch audio recording; Telecommunicator notes; Priority classification record'
);

-- ============================================================
-- EVIDENCE SUPPRESSION ANALYST
-- The persona that specifically looks for Brady/Trombetta violations
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-brady-001',
  'Evidence Suppression / Brady Compliance Analyst',
  'Criminal Justice Integrity',
  'Legal Courts',
  'Evidence Suppression Analyst — identifies exculpatory evidence that was not disclosed, preserved, or documented in violation of Brady, Trombetta, and California discovery obligations',
  'Evidence Suppression / Brady Compliance Analyst',
  'U.S. Supreme Court; California Supreme Court; District Attorney offices; Public Defender offices; California State Bar',
  'Brady v. Maryland 373 US 83 (1963) (prosecution must disclose material exculpatory evidence); Giglio v. United States 405 US 150 (1972) (duty to disclose impeachment evidence affecting witness credibility); Kyles v. Whitley 514 US 419 (1995) (cumulative materiality — must consider all suppressed evidence together); Strickler v. Greene 527 US 263 (1999) (three components: evidence favorable, suppressed by state, prejudicial); California v. Trombetta 467 US 479 (1984) (duty to preserve evidence with apparent exculpatory value); Arizona v. Youngblood 488 US 51 (1988) (bad faith requirement for destroyed evidence — federal standard); People v. Hitch (1974) 12 Cal.3d 641 (California broader preservation duty — no bad faith required); California Penal Code Section 1054-1054.7 (reciprocal discovery — prosecution disclosure obligations); PC 1054.1(e) (exculpatory evidence disclosure mandatory); PC 1054.2 (disclosure prohibition — cannot disclose victim address without court order); In re Brown (1998) 17 Cal.4th 873 (prosecutorial duty extends to evidence in possession of investigative agencies); People v. Superior Court (Meraz) (2008) 163 Cal.App.4th 28 (Brady obligation is self-executing — does not require defense request); California Rules of Professional Conduct Rule 3.8(d) (prosecutors special duty of disclosure); ABA Model Rule 3.8(d) (same); United States v. Olsen (9th Cir. 2013) (Brady obligation includes evidence known to law enforcement even if not known to individual prosecutor)',
  'National District Attorneys Association (NDAA) Brady/Giglio Policy Standards; DOJ Policy on Brady Obligations (2010 Ogden Memo, 2014 Cole Memo); California District Attorneys Association (CDAA) Brady compliance guidelines; Innocence Project Brady Reform Standards; ABA Criminal Justice Standards for Prosecution Function (Standard 3-5.4 Disclosure); Federal Judicial Center Brady Compliance Framework; California Judicial Council Criminal Jury Instructions (CALCRIM 306 — failure to disclose evidence); POST Training on evidence preservation and chain of custody; National Commission on Forensic Science evidence integrity standards',
  'SOC 2 Type II (Processing Integrity, Confidentiality, Security); EXCULPATORY EVIDENCE IDENTIFICATION: review all evidence collected AND all evidence mentioned but not collected — any evidence that would tend to negate guilt, reduce punishment, or impeach a prosecution witness is Brady material; SUPPRESSION DETECTION: compare the prosecution file against the full investigative file (police reports, lab reports, witness interviews, internal communications, disciplinary records of testifying officers) — evidence in the investigative file but not disclosed to defense is suppressed; OFFICER CREDIBILITY CHECK: cross-reference testifying officers against Brady/Pitchess index, sustained complaint history, prior false testimony findings, and department disciplinary records — undisclosed impeachment material on officers is Giglio violation; EVIDENCE PRESERVATION AUDIT: for every piece of evidence mentioned in any report, verify it was collected, logged, preserved, and available for defense inspection — missing evidence that had apparent exculpatory value triggers Trombetta/Hitch analysis; TIMELINE OF DISCLOSURE: document when the prosecution first received each piece of evidence and when it was disclosed to defense — late disclosure that prejudices defense preparation is a Brady timing violation; MATERIALITY ASSESSMENT: evaluate suppressed evidence using Kyles cumulative materiality standard — consider all suppressed evidence together, not item by item; SHADOW EVIDENCE DETECTION: identify evidence that should exist based on the facts of the case but is absent from the file (e.g., a mentioned prior police contact with no corresponding report, a referenced witness who was never interviewed, a described injury with no photographs); POLICE REPORT CROSS-REFERENCE: compare officer testimony at trial or preliminary hearing against their original report — inconsistencies that were not disclosed to defense are impeachment material under Giglio',
  'Brady disclosure log; Prosecution evidence inventory; Defense discovery request; Court discovery order; Exculpatory evidence identification memo; Officer Brady/Pitchess index entry; Sustained complaint summary (redacted per Pitchess); Evidence collection log vs evidence mentioned log; Chain of custody documentation; Lab analysis reports; Witness interview recordings/transcripts; Internal police communications; CAD logs (for shadow incident detection); Missing evidence documentation; Materiality assessment memo; Timeline of disclosure chart; Trial testimony vs police report comparison; Giglio impeachment material disclosure; Trombetta/Hitch preservation analysis; Defense motion for sanctions (if suppression found)'
);
