-- Case-Critical Missing Personas
-- These don't exist in the catalog yet. Full INSERT with triple constraint.

-- ============================================================
-- ABPN DIPLOMATE / BOARD CERTIFICATION AUDITOR
-- The person who verifies a psychiatrist's or neurologist's
-- credentials are real, current, and legitimately obtained.
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-abpn-001',
  'ABPN Diplomate Credential Verification Specialist',
  'Healthcare Credentialing Compliance',
  'Healthcare',
  'ABPN Diplomate Credential Verification Specialist — verifies board certification status, MOC compliance, and credential legitimacy for psychiatrists and neurologists',
  'ABPN Diplomate Credential Verification Specialist',
  'American Board of Psychiatry and Neurology (ABPN); ABMS (American Board of Medical Specialties); National Practitioner Data Bank (NPDB); State Medical Boards',
  'ABPN Bylaws and Policies (certification, MOC, disciplinary actions); ABMS Standards for Initial Certification and Continuing Certification; 42 USC 11101-11152 (Health Care Quality Improvement Act — NPDB reporting); 42 CFR Part 60 (NPDB regulations); 45 CFR 60.12 (reporting requirements); California Bus. & Prof. Code Sections 2000-2529 (Medical Practice Act — licensure verification); CMS Conditions of Participation 42 CFR 482.12(a)(7) (medical staff credentialing); CMS Conditions of Participation 42 CFR 482.22 (medical staff composition); TJC MS.06.01.01-MS.06.01.05 (credentialing and privileging); ABPN subspecialty certifications: Addiction Psychiatry, Child and Adolescent Psychiatry, Forensic Psychiatry, Geriatric Psychiatry, Pain Medicine, Brain Injury Medicine, Neurodevelopmental Disabilities',
  'ABPN Certification Verification Service standards; ABMS Board Certification Report; NPDB Continuous Query enrollment standards; National Committee for Quality Assurance (NCQA) credentialing standards (CR-1 through CR-8); URAC Health Plan credentialing standards; CVO (Credentials Verification Organization) accreditation standards; AMA Physician Masterfile verification; Federation of State Medical Boards (FSMB) DocInfo verification; Joint Commission Medical Staff Standards; CAQH ProView standards for provider data; primary source verification methodology (direct confirmation from issuing body)',
  'SOC 2 Type II (Processing Integrity, Confidentiality, Security); primary source verification documentation for each credential element (medical school, residency, fellowship, board certification, state licensure, DEA registration); ABPN certification status verification (active, expired, revoked, voluntary surrender); MOC (Maintenance of Certification) compliance tracking — ABPN requires ongoing participation including Part 1 (Professional Standing), Part 2 (Lifelong Learning), Part 3 (Assessment of Knowledge), Part 4 (Improvement in Medical Practice); NPDB query documentation (initial and biennial); adverse action reporting verification (malpractice payments, licensure actions, clinical privilege restrictions, DEA actions); hospital privilege verification for each facility; malpractice insurance verification; OIG/GSA exclusion list screening (monthly LEIE check); state medical board disciplinary action search; time-limited credential expiration tracking and re-verification; peer reference verification; competency assessment documentation; AMA profile discrepancy investigation; gap analysis for unexplained practice interruptions',
  'Board certification certificate; MOC status report; NPDB Self-Query Response; NPDB Continuous Query notification; State medical license verification; DEA registration certificate; Medical school diploma verification; Residency completion verification; Fellowship completion verification; Hospital privilege delineation; Malpractice claims history; FSMB Board Action Databank report; AMA Physician Masterfile report; CAQH ProView attestation; OIG exclusion screening results; Peer reference letters; Competency evaluation; CME completion records; Professional liability insurance face sheet'
);

-- ============================================================
-- COMPETENCY EVALUATOR (PC 1367-1376)
-- The person who evaluates whether a defendant is competent
-- to stand trial. Critical — this is a gatekeeper function.
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-comp-eval-001',
  'Competency to Stand Trial Evaluator (PC 1367)',
  'Forensic Mental Health Compliance',
  'Legal Courts',
  'Competency to Stand Trial Evaluator — conducts court-ordered evaluations under PC 1367-1376 to determine if defendant understands proceedings and can assist counsel',
  'Competency to Stand Trial Evaluator (PC 1367)',
  'California Superior Court; Department of State Hospitals (DSH); Board of Psychology; Medical Board of California; ABPN (Forensic Psychiatry subspecialty)',
  'California Penal Code Sections 1367-1376 (competency proceedings); PC 1367 (standard: unable to understand nature of proceedings or assist counsel in rational manner); PC 1368 (doubt of competency — duty to declare); PC 1369 (trial on competency — expert testimony, right to jury); PC 1370 (commitment to DSH if found incompetent — maximum commitment periods); PC 1370.01 (misdemeanor competency — different commitment rules); PC 1370.1 (developmentally disabled defendants — Regional Center evaluation); PC 1372 (certificate of restoration — DSH Medical Director certification); PC 1375 (civil commitment after maximum commitment); Dusky v. United States 362 US 402 (1960) (federal competency standard: sufficient present ability to consult with lawyer with reasonable degree of rational understanding AND rational as well as factual understanding of proceedings); Drope v. Missouri 420 US 162 (1975) (duty to inquire sua sponte); People v. Rodas (2018) 6 Cal.5th 219 (California competency standard); California Rules of Court Rule 4.130 (proceedings regarding mental competence); Evidence Code Section 730 (court-appointed expert); Evidence Code Section 1017 (psychotherapist-patient privilege exception for court-ordered evaluation)',
  'American Academy of Psychiatry and the Law (AAPL) Practice Guidelines for Forensic Psychiatric Evaluation of Defendants Raising the Insanity Defense and for Forensic Assessment of Competency to Stand Trial; APA (American Psychological Association) Specialty Guidelines for Forensic Psychology; ABFP (American Board of Forensic Psychology) certification standards; ABPN subspecialty certification in Forensic Psychiatry; California Board of Psychology forensic evaluation standards; DSH Competency Evaluation guidelines; standardized competency assessment instruments: MacArthur Competence Assessment Tool — Criminal Adjudication (MacCAT-CA), Competency Screening Test (CST), Georgia Court Competency Test (GCCT), Evaluation of Competency to Stand Trial — Revised (ECST-R), Competency to Stand Trial Assessment Instrument (CAI); Judicial Council Form CR-111 (Order for Examination); forensic report writing standards per AAPL Ethics Guidelines',
  'SOC 2 Type II (Processing Integrity, Confidentiality); court order verification before conducting evaluation; Miranda-type advisement to defendant (limits of confidentiality, non-treatment purpose, report will be disclosed to court and counsel); evaluation methodology documentation (instruments used, clinical interview, collateral information reviewed, records reviewed); opinion basis documentation linking clinical findings to Dusky/PC 1367 legal standard; prior competency evaluation review; medication status documentation (capacity to participate may be affected by psychotropic medication — Sell v. United States 539 US 166); malingering assessment documentation (SIRS-2, TOMM, other symptom validity testing); report submission timeliness (court-ordered deadline compliance); DSH admission coordination documentation (if committed); restoration treatment documentation; certificate of restoration review; re-evaluation documentation if competency re-raised; privilege and confidentiality management (evaluation is NOT treatment — no psychotherapist-patient privilege per EC 1017); chain of custody for evaluation notes and records',
  'Court Order for Competency Evaluation (CR-111); Competency Evaluation Report; Competency Assessment Instrument scoring records; Clinical interview notes; Collateral information log; Records reviewed inventory; Malingering assessment results; Certificate of Incompetence (if found IST); DSH Admission Order; Restoration Treatment Plan; Progress Reports to Court; Certificate of Restoration of Competency; Medication capacity evaluation (Sell analysis); Re-evaluation report; Expert testimony preparation materials'
);

-- ============================================================
-- POST COMPLIANCE OFFICER / POST TRAINING AUDITOR
-- Audits whether peace officers have completed required POST
-- training, certification is current, and departments are
-- in compliance with POST standards.
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-post-001',
  'POST Compliance Auditor / Peace Officer Training Standards Specialist',
  'Law Enforcement Training Compliance',
  'Gov Le Digital',
  'POST Compliance Auditor — verifies peace officer training compliance, POST certification status, and department adherence to POST standards',
  'POST Compliance Auditor / Peace Officer Training Standards Specialist',
  'California Commission on Peace Officer Standards and Training (POST); California Department of Justice; State Legislature (via Penal Code)',
  'California Penal Code Sections 13500-13553 (POST enabling statutes); PC 13510 (POST authority to set minimum standards); PC 13510.1 (continuing professional training requirement — 24 hours every 2 years minimum); PC 13515 (elder/dependent adult abuse training); PC 13515.25 (racial profiling — racial and identity profiling training); PC 13515.27 (implicit bias and cultural diversity training); PC 13515.28 (use of force — de-escalation training); PC 13515.29 (mental health crisis intervention training); PC 13516 (domestic violence training); PC 13516.5 (human trafficking training); PC 13517 (sexual assault investigation training); PC 13519 (racial profiling training); PC 13519.4 (hate crimes training); PC 13519.8 (persons with developmental disabilities training); PC 13523 (missing persons training); PC 13525 (elder abuse training for investigators); PC 13540-13542 (fraudulent POST certificates — criminal penalties); Government Code Section 1029-1031.5 (minimum peace officer standards — citizenship, age, fingerprinting, background, psych screening, medical exam); Government Code Section 1031(f) (moral character); 11 CCR Sections 1000-1099 (POST Regulations — training requirements, certification, standards); AB 846 (2020) (disqualification for officers with prior misconduct); SB 2 (2021) (Peace Officer Decertification Act — POST authority to revoke certification); SB 960 (2022) (DACA recipients eligible for peace officer); POST Administrative Manual; POST Regulations Procedure D-1 (Basic Course requirements — 664+ hours minimum)',
  'POST Basic Course curriculum standards (Regular Basic Course — 42 Learning Domains, 664+ hours); POST Field Training Program standards (POST Guidelines, minimum 10 weeks); POST Supervisory Course requirements; POST Management Course; POST Executive Development Course; POST Continuing Professional Training (CPT) guidelines — 24 hours minimum biennially with mandated subjects; POST Perishable Skills Program (PSP) — annual qualification in arrest/control, driver awareness/simulation, tactical firearms; POST Basic Course Waiver standards for lateral transfers; POST Academy instructor certification standards; POST course certification requirements (presentation, testing, and evaluation); POST Regular Basic Course testing standards (comprehensive final, scenario testing); California POST Learning Portal standards; POST Compliance Review methodology; Department Training Manager (DTM) standards and certification',
  'SOC 2 Type II (Processing Integrity, Security, Confidentiality); POST Profile database verification (individual officer training records); Basic Course completion certificate verification; POST certificate issuance tracking (Basic, Intermediate, Advanced, Supervisory, Management, Executive); CPT compliance monitoring — biennial 24-hour requirement with documentation of specific mandated courses completed; Perishable Skills completion tracking (annual firearms qualification records, arrest/control certification, driver training); field training program completion verification (Daily Observation Reports, weekly evaluations, final evaluation); background investigation file completeness audit per Government Code 1031 (personal history statement, polygraph/CVSA, psychological screening report, medical examination, criminal history check, reference checks, prior employer contacts); SB 2 decertification compliance — reporting serious misconduct to POST; National Decertification Index (NDI) query documentation; Brady list / Pitchess motion disclosure tracking; personnel complaint investigation documentation; body-worn camera policy compliance; use of force reporting and review documentation; Early Warning System / Early Intervention System data tracking; department POST compliance audit documentation; Training Records Management System integrity; POST reimbursement audit trail',
  'POST Basic Certificate; POST Intermediate Certificate; POST Advanced Certificate; POST Supervisory Certificate; POST Management Certificate; POST Executive Certificate; Basic Course completion certificate; CPT completion records; Perishable Skills annual qualification records; Field Training Officer (FTO) certification; Daily Observation Reports (DORs); Background investigation file; Personal History Statement (POST PHS-2); Psychological screening report; Medical examination clearance; Polygraph/CVSA results; Department training plan; POST compliance audit report; SB 2 misconduct report; Brady/Pitchess disclosure index; Use of force reports; Body-worn camera policy; Early Warning System alerts; Firearms qualification records; Arrest and control certification; Department POST profile report'
);

-- ============================================================
-- DEPARTMENT-SPECIFIC POLICE OVERSIGHT
-- Oakland PD (consent decree), Antioch PD, Berkeley PD
-- These departments have specific oversight requirements
-- beyond standard POST compliance.
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-opd-oversight-001',
  'Oakland Police Department Compliance Auditor (NSA/Federal Oversight)',
  'Law Enforcement Oversight Compliance',
  'Gov Le Digital',
  'OPD Compliance Auditor — monitors compliance with Negotiated Settlement Agreement, federal court orders, and court-appointed monitor requirements',
  'Oakland Police Department Compliance Auditor (NSA/Federal Oversight)',
  'U.S. District Court, Northern District of California; Court-Appointed Compliance Director/Monitor; Oakland Police Commission; Community Police Review Agency (CPRA); Oakland City Council',
  'Delphine Allen et al. v. City of Oakland (Case No. C00-4599 TEH) — Negotiated Settlement Agreement (NSA) (2003); 42 USC 14141 (now 34 USC 12601) (Pattern or Practice of Police Misconduct); NSA Tasks 1-52 (specific reform requirements); Oakland City Charter Section 604(b)(5) (Police Commission authority); Oakland Municipal Code Chapter 2.45 (Community Police Review Agency); Oakland Measure LL (2016, Police Commission establishment); Oakland Measure S1 (2020, Police Commission expansion); California Government Code Section 3300-3313 (Peace Officers Bill of Rights — POBR); California Penal Code Section 832.7 (personnel records disclosure — SB 1421, SB 16); Penal Code Section 13012 (use of force reporting to DOJ); AB 748 (body camera footage release); SB 1421 (officer misconduct records disclosure); SB 16 (expanded disclosure of sustained findings)',
  'NSA compliance assessment methodology (court-appointed monitor framework); OPD Policy and Procedure Manual standards; NACOLE (National Association for Civilian Oversight of Law Enforcement) standards; DOJ Collaborative Reform Initiative methodology; Police Executive Research Forum (PERF) use of force guidelines; IACP (International Association of Chiefs of Police) model policies; Oakland Police Commission policy review standards; Stanford Criminal Justice Center Monitoring Report methodology; CPRA investigation standards',
  'SOC 2 Type II (Processing Integrity, Security, Confidentiality); NSA task compliance tracking (52 tasks — each with specific measurable requirements); court-appointed monitor quarterly report verification; use of force review documentation (Type I through Type IV classification); Internal Affairs Division investigation timeliness tracking (180-day POBR statute of limitations); complaint classification and disposition tracking; officer discipline audit; early intervention system (Risk Management Dashboard) alert documentation; body-worn camera activation compliance audit; stop data collection per RIPA (AB 953); pursuit policy compliance; training completion verification; community engagement documentation; Police Commission policy recommendation tracking; CPRA investigation outcome tracking; federal court status conference compliance; sustained complaint disclosure per SB 1421/SB 16',
  'Negotiated Settlement Agreement compliance report; Court-appointed monitor quarterly report; NSA task completion documentation; Use of force reports (all types); Internal Affairs investigation files; Citizen complaint files; Early intervention system alerts; Body-worn camera footage audit log; RIPA stop data reports; Pursuit reports; Training compliance records; Police Commission meeting minutes; CPRA investigation reports; Federal court status conference transcripts; Community policing activity reports; Officer discipline records; Brady/Pitchess index; Annual report to court'
);

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-apd-oversight-001',
  'Antioch Police Department Compliance Auditor (DOJ Pattern & Practice)',
  'Law Enforcement Oversight Compliance',
  'Gov Le Digital',
  'Antioch PD Compliance Auditor — monitors compliance with California DOJ pattern and practice investigation findings and reform requirements',
  'Antioch Police Department Compliance Auditor (DOJ Pattern & Practice)',
  'California Department of Justice, Civil Rights Enforcement Section; Antioch City Council; Contra Costa County District Attorney',
  'California Government Code Section 12525.3 (Attorney General authority to investigate pattern or practice of police misconduct — AB 1506/SB 2); California DOJ investigation of Antioch Police Department (initiated 2022, findings 2023); California Penal Code Section 13012 (use of force reporting); Government Code Section 3300-3313 (POBR); Penal Code Section 832.7 (personnel records disclosure); RIPA (AB 953) stop data requirements; SB 2 (Peace Officer Decertification Act); SB 1421 (misconduct records disclosure); Antioch Municipal Code public safety provisions; Contra Costa County protocols for officer-involved incidents',
  'California DOJ pattern and practice investigation methodology; NACOLE civilian oversight standards; California DOJ Racial and Identity Profiling Advisory Board (RIPA Board) recommendations; PERF use of force principles; IACP model policies; California DOJ Use of Force reporting standards; POST training compliance standards specific to identified deficiencies',
  'SOC 2 Type II (Processing Integrity, Security); DOJ findings compliance tracking (each identified deficiency with specific remediation requirement); use of force policy reform documentation; racial profiling and bias-based policing remediation; officer discipline system reform documentation; internal affairs investigation quality review; RIPA stop data analysis for disparities; body-worn camera policy compliance; training reform implementation (bias, de-escalation, crisis intervention); community engagement reform; hiring and background investigation reform; supervision and accountability reform; early intervention system implementation; progress reporting to DOJ; consent decree/settlement compliance (if formalized)',
  'DOJ pattern and practice investigation report; Remediation plan; Use of force policy revisions; Training reform documentation; Internal affairs investigation files; RIPA stop data analysis; Body-worn camera policy and audit; Hiring and screening reforms; Supervision policy changes; Community engagement records; Progress reports to DOJ; Officer discipline tracking; Early intervention system records; Bias-based policing complaints and investigations'
);

-- ============================================================
-- MENTAL HEALTH COURT COORDINATOR / TREATMENT COURT SPECIALIST
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-mhc-001',
  'Mental Health Court Coordinator / Treatment Court Compliance Specialist',
  'Therapeutic Jurisprudence Compliance',
  'Legal Courts',
  'Mental Health Court Coordinator — manages treatment court operations, participant compliance, and coordination between judicial, clinical, and supervision teams',
  'Mental Health Court Coordinator / Treatment Court Compliance Specialist',
  'California Superior Court; Judicial Council of California; SAMHSA; Bureau of Justice Assistance (BJA); California Mental Health Services Authority (CalMHSA)',
  'California Penal Code Section 1001.35-1001.36 (mental health diversion — AB 1810/SB 215); PC 1170.9 (veteran mental health diversion); PC 1367-1376 (competency proceedings — interface with mental health court); Welfare & Institutions Code Section 5600-5778 (Community Mental Health Services Act); WIC Section 5813.5 (Mental Health Services Act — Prop 63 funding for court-involved populations); California Rules of Court Rule 10.951 (collaborative justice courts); 42 USC 3796ii (Mentally Ill Offender Treatment and Crime Reduction Act — federal BJA funding); SAMHSA GAINS Center guidelines for mental health courts; BJA Mental Health Court Grant Program requirements; California Penal Code Section 4011.6 (county mental health liaison in jails)',
  'SAMHSA GAINS Center Essential Elements of Mental Health Courts; National Association of Drug Court Professionals (NADCP) Best Practice Standards (adapted for mental health courts); Council of State Governments (CSG) Justice Center Mental Health Court guidelines; Judicial Council of California Collaborative Justice Courts Advisory Committee standards; BJA Mental Health Court Learning Sites methodology; TAPA Center for Jail Diversion standards; Sequential Intercept Model (SIM) framework; American Psychiatric Association Position Statement on Mental Health Courts; California Behavioral Health Directors Association treatment court standards',
  'SOC 2 Type II (Processing Integrity, Confidentiality); participant eligibility screening documentation (clinical assessment, risk assessment, legal eligibility); treatment plan documentation and court approval; judicial status hearing scheduling and compliance tracking; treatment provider reporting to court; drug testing results and documentation; participant compliance/noncompliance documentation; sanctions and incentives tracking; graduation criteria documentation; recidivism tracking; program outcome data collection; HIPAA/42 CFR Part 2 compliance for clinical information shared with court; participant consent for information sharing; team staffing meeting documentation; referral coordination with community mental health providers; housing and benefits coordination documentation; case closure documentation (graduation, termination, opt-out)',
  'Mental health court eligibility screening; Clinical assessment report; Treatment plan (court-approved); Judicial status hearing minutes; Treatment provider progress reports; Drug test results; Compliance/noncompliance reports; Sanctions and incentives log; Graduation certificate; Participant consent for information sharing; HIPAA authorization; 42 CFR Part 2 consent; Team staffing meeting notes; Community referral documentation; Housing placement records; Benefits enrollment verification; Program outcome data; Recidivism tracking; Case closure summary'
);

-- ============================================================
-- POLICE DEPARTMENT STANDARDS (generic for all CA departments)
-- ============================================================

INSERT OR IGNORE INTO citizen_catalog (id, name, domain, industry, description, professional_title, governing_body, governing_guidelines, standards_of_creation, soc_controls, document_types) VALUES (
  'citizen-capd-001',
  'California Police Department Compliance Auditor (Statewide Standards)',
  'Law Enforcement Compliance',
  'Gov Le Digital',
  'CA Police Department Compliance Auditor — audits any California law enforcement agency against POST, RIPA, POBR, use of force reporting, body camera, and transparency requirements',
  'California Police Department Compliance Auditor (Statewide Standards)',
  'California Commission on POST; California Department of Justice; State Legislature; Local Police Commissions/Oversight Bodies; County Grand Juries',
  'California Penal Code Sections 13500-13553 (POST); PC 13012 (use of force reporting to DOJ); PC 13650-13651 (body-worn camera policies); PC 832.7-832.8 (peace officer personnel records — SB 1421, SB 16); PC 830-832.17 (peace officer definitions and authority); Government Code Sections 1029-1031.5 (minimum standards for peace officers); Government Code Sections 3300-3313 (POBR — Peace Officers Bill of Rights); Government Code Section 12525.2-12525.5 (RIPA — Racial and Identity Profiling Act, AB 953); Government Code Section 7286 (use of force policy requirements — AB 392/SB 230); Penal Code Section 835a (use of deadly force standard — necessity, not just reasonableness); SB 2 (Peace Officer Decertification — POST authority to revoke); SB 960 (peace officer eligibility expansion); AB 748 (body camera footage public release — 45 days); AB 1196 (ban on carotid restraint/chokehold); AB 26 (duty to intercede when observing excessive force); AB 89 (minimum age 21 for peace officers, effective 2025); AB 1506 (AG authority to investigate officer-involved shootings); California Vehicle Code Section 17004.7 (pursuit policy requirements)',
  'POST Regulations (11 CCR 1000-1099); POST Administrative Manual; POST Basic Course standards (42 Learning Domains, 664+ hours); POST Continuing Professional Training standards; POST Perishable Skills Program; IACP Law Enforcement Policy Center model policies; PERF Guiding Principles on Use of Force; CALEA (Commission on Accreditation for Law Enforcement Agencies) standards (voluntary); California DOJ RIPA Board annual report recommendations; California Police Chiefs Association best practices; NACOLE civilian oversight standards; DOJ Collaborative Reform Initiative Technical Assistance Center; BJA Body-Worn Camera Toolkit',
  'SOC 2 Type II (Processing Integrity, Security, Confidentiality); POST certification verification for all sworn personnel; CPT biennial compliance tracking; Perishable Skills annual qualification records; use of force incident reporting and review (all levels per department policy and AB 392/SB 230 compliance); RIPA stop data collection and DOJ submission; body-worn camera activation compliance audit; personnel complaint investigation tracking (citizen complaints and internal); Internal Affairs investigation timeliness (180-day POBR deadline); early warning/early intervention system monitoring; officer discipline documentation; SB 2 serious misconduct reporting to POST; Brady/Pitchess disclosure index maintenance; SB 1421/SB 16 records disclosure compliance; pursuit policy compliance; firearms qualification records; arrest and control recertification; de-escalation training documentation; mental health crisis intervention training (PC 13515.29); bias/cultural diversity training (PC 13519); domestic violence response training (PC 13516); department accreditation compliance (if CALEA); community policing program documentation; federal consent decree/DOJ compliance (if applicable)',
  'POST certification records (all sworn); CPT completion logs; Perishable Skills qualification records; Use of force reports (all types); RIPA stop data submissions; Body-worn camera policy and activation audit; Citizen complaint files; Internal Affairs investigation files; Discipline records; Early warning system alerts; Brady/Pitchess index; SB 1421/SB 16 disclosure records; Pursuit reports; Firearms qualification records; Training completion records (all mandated categories); Department policy manual (current); Annual department report; Consent decree/DOJ compliance reports (if applicable); Community engagement records; Officer background investigation files; Psychological screening records; Medical clearance records'
);
