/**
 * reconcile-names.cjs
 *
 * Reads all gen-triple-*.sql files, extracts the SET clauses,
 * then matches them to incomplete DB records using fuzzy matching.
 * Outputs corrected UPDATE statements with actual DB names.
 */
const fs = require('fs');
const path = require('path');

const SCRIPTS_DIR = path.join(__dirname);

// Read incomplete names from file (generated by wrangler export)
// We'll generate them inline by reading all SQL files and finding unmatched data

// Step 1: Parse all triple constraint data from SQL files
const tripleData = []; // { agentName, guidelines, standards, soc }

const sqlFiles = fs.readdirSync(SCRIPTS_DIR).filter(f =>
  f.startsWith('gen-triple-') && f.endsWith('.sql')
);

for (const file of sqlFiles) {
  const content = fs.readFileSync(path.join(SCRIPTS_DIR, file), 'utf-8');

  // Match UPDATE blocks
  const updateRegex = /UPDATE citizen_catalog SET\s+governing_guidelines = '((?:[^']|'')*)',\s+standards_of_creation = '((?:[^']|'')*)',\s+soc_controls = '((?:[^']|'')*?)'\s+WHERE name (?:=|LIKE) '([^']*?)';/gs;

  let match;
  while ((match = updateRegex.exec(content)) !== null) {
    tripleData.push({
      guidelines: match[1],
      standards: match[2],
      soc: match[3],
      agentName: match[4].replace(/%/g, ''),
      sourceFile: file,
    });
  }
}

console.log(`Parsed ${tripleData.length} triple constraint records from ${sqlFiles.length} SQL files`);

// Step 2: Read the incomplete DB names from a pre-exported file
// For now, we'll generate the reconciliation SQL by matching agent names to DB names
// using substring matching

// Build a lookup: lowercase first 20 chars of agent name -> full triple data
const agentLookup = new Map();
for (const td of tripleData) {
  const key = td.agentName.toLowerCase().substring(0, 30);
  if (!agentLookup.has(key)) {
    agentLookup.set(key, td);
  }
}

// Step 3: Read the DB names export
const dbNamesFile = '/tmp/incomplete-names.txt';
let dbNames = [];
if (fs.existsSync(dbNamesFile)) {
  dbNames = fs.readFileSync(dbNamesFile, 'utf-8').split('\n').filter(Boolean);
}

console.log(`Loaded ${dbNames.length} incomplete DB names`);

// Step 4: Try to match each DB name to agent data
const esc = s => (s || '').replace(/'/g, "''");
const matched = [];
const unmatched = [];

for (const dbName of dbNames) {
  const dbKey = dbName.toLowerCase().substring(0, 30);

  // Try exact prefix match
  let found = agentLookup.get(dbKey);

  // Try without parenthetical
  if (!found) {
    const noParens = dbName.replace(/\s*\([^)]*\)\s*/g, '').trim().toLowerCase().substring(0, 30);
    found = agentLookup.get(noParens);
  }

  // Try searching all agent names for best substring match
  if (!found) {
    const dbLower = dbName.toLowerCase();
    for (const td of tripleData) {
      const agentLower = td.agentName.toLowerCase();
      if (dbLower.includes(agentLower) || agentLower.includes(dbLower.substring(0, 25))) {
        found = td;
        break;
      }
    }
  }

  if (found) {
    matched.push({ dbName, ...found });
  } else {
    unmatched.push(dbName);
  }
}

console.log(`Matched: ${matched.length}, Unmatched: ${unmatched.length}`);

// Step 5: Generate reconciliation SQL
const sqlLines = [
  '-- Name reconciliation: corrected WHERE clauses for DB names',
  '-- Generated: ' + new Date().toISOString(),
  '-- Matched: ' + matched.length,
  '',
];

for (const m of matched) {
  sqlLines.push(
    `UPDATE citizen_catalog SET governing_guidelines = '${esc(m.guidelines)}', standards_of_creation = '${esc(m.standards)}', soc_controls = '${esc(m.soc)}' WHERE name = '${esc(m.dbName)}';`
  );
}

const outPath = path.join(SCRIPTS_DIR, 'reconcile-triple.sql');
fs.writeFileSync(outPath, sqlLines.join('\n'));
console.log(`\nSQL written to: ${outPath}`);
console.log(`\nFirst 5 unmatched:`);
unmatched.slice(0, 5).forEach(n => console.log('  ' + n));
